set specl::appname      "tke"
set specl::version      "1.3.4"
set specl::release      "28"
set specl::rss_url      "http://tke.sourceforge.net/releases"
set specl::download_url "http://tke.sourceforge.net/releases"
