set specl::appname      "tke"
set specl::version      "3.6"
set specl::release      "401"
set specl::rss_url      "http://tke.sourceforge.net/releases"
set specl::download_url "http://tke.sourceforge.net/releases"
