set specl::appname      "tke"
set specl::version      "3.5.7"
set specl::release      "400"
set specl::rss_url      "http://tke.sourceforge.net/releases"
set specl::download_url "http://tke.sourceforge.net/releases"
