source [file join $::tke_dir lib format_lexer.tcl]

set format_txt     ""
set format_value   ""
set format_errmsg  ""
set format_errstr  ""
set format_pos     0
set format_matches [list]

proc get_retval {args} {
  return [join $args {}]
}

######
# Begin autogenerated taccle (version 1.1) routines.
# Although taccle itself is protected by the GNU Public License (GPL)
# all user-supplied functions are protected by their respective
# author's license.  See http://mini.net/tcl/taccle for other details.
######

proc FORMAT_ABORT {} {
    return -code return 1
}

proc FORMAT_ACCEPT {} {
    return -code return 0
}

proc format_clearin {} {
    upvar format_token t
    set t ""
}

proc format_error {s} {
    puts stderr $s
}

proc format_setupvalues {stack pointer numsyms} {
    upvar 1 1 y
    set y {}
    for {set i 1} {$i <= $numsyms} {incr i} {
        upvar 1 $i y
        set y [lindex $stack $pointer]
        incr pointer
    }
}

proc format_unsetupvalues {numsyms} {
    for {set i 1} {$i <= $numsyms} {incr i} {
        upvar 1 $i y
        unset y
    }
}

array set ::format_table {
  6:260,target 3
  17:266,target 24
  33:261,target 4
  3:267,target 9
  26:257 reduce
  15:257,target 15
  26:258 reduce
  26:260 reduce
  0:275,target 14
  26:261 reduce
  26:262 reduce
  1:258,target 12
  26:263 reduce
  26:264 reduce
  27:260,target 7
  26:265 reduce
  26:266 reduce
  26:267 reduce
  24:267,target 3
  26:270 reduce
  26:271 reduce
  36:270,target 10
  7:260,target 3
  18:266,target 24
  34:261,target 4
  21:0 reduce
  4:267,target 9
  16:257,target 21
  13:265,target 13
  21:: reduce
  28:260,target 18
  25:267,target 4
  32:257 shift
  32:258 shift
  32:260 shift
  37:270,target 21
  32:261 shift
  23:258,target 2
  32:262 shift
  32:263 shift
  32:264 shift
  8:260,target 10
  19:266,target 24
  32:266 shift
  35:261,target 20
  32:267 shift
  29:0,target 19
  32:270 shift
  5:267,target 9
  16:274,target 26
  35:0 reduce
  17:257,target 21
  31::,target 8
  32:273 goto
  32:274 goto
  32:275 goto
  3:258,target 9
  14:265,target 14
  29:260,target 19
  0:266,target 8
  9:0 reduce
  35:: reduce
  26:267,target 6
  24:258,target 3
  9:: reduce
  9:260,target 11
  21:266,target 5
  36:261,target 4
  37:257 reduce
  6:267,target 9
  17:274,target 26
  37:258 reduce
  37:260 reduce
  18:257,target 21
  37:261 reduce
  37:262 reduce
  37:263 reduce
  37:264 reduce
  4:258,target 2
  15:265,target 15
  37:265 reduce
  31:260,target 8
  37:266 reduce
  37:267 reduce
  1:266,target 12
  37:270 reduce
  26:0,target 6
  27:267,target 7
  37:271 reduce
  27::,target 7
  25:258,target 4
  37:261,target 21
  7:267,target 9
  18:274,target 26
  19:257,target 21
  20:257,target 30
  4:275,target 14
  5:258,target 2
  16:265,target 16
  32:260,target 3
  28:267,target 18
  0:257,target 1
  13:257 reduce
  26:258,target 6
  13:258 reduce
  13:260 reduce
  13:261 reduce
  13:262 reduce
  23:266,target 2
  13:263 reduce
  2:257 shift
  13:264 reduce
  23:0,target 2
  13:265 reduce
  8:267,target 10
  13:266 reduce
  19:274,target 26
  13:267 reduce
  24::,target 3
  21:257,target 5
  13:270 reduce
  5:275,target 14
  13:271 reduce
  6:258,target 2
  17:265,target 17
  33:260,target 23
  3:266,target 9
  29:267,target 19
  0:274,target 13
  1:257,target 12
  12:264,target 7
  27:258,target 7
  24:266,target 3
  8:0,target 10
  9:267,target 11
  22:257,target 31
  9::,target 11
  6:275,target 14
  18:257 shift
  18:258 shift
  7:258,target 2
  18:265,target 28
  18:260 shift
  34:260,target 3
  18:261 shift
  18:262 shift
  18:263 shift
  7:257 shift
  4:266,target 8
  18:264 shift
  7:258 shift
  18:265 shift
  31:267,target 8
  7:260 shift
  18:266 shift
  7:261 shift
  18:267 shift
  21::,target 5
  7:262 shift
  7:263 shift
  18:270 shift
  7:264 shift
  2:257,target 15
  13:264,target 13
  28:258,target 18
  7:266 shift
  7:267 shift
  18:274 goto
  18:275 goto
  7:270 shift
  25:266,target 4
  7:273 goto
  7:274 goto
  7:275 goto
  23:257,target 2
  7:275,target 14
  8:258,target 10
  19:265,target 29
  35:260,target 20
  23:0 reduce
  5:266,target 8
  32:267,target 9
  3:257,target 9
  14:264,target 14
  24:257 reduce
  24:258 reduce
  29:258,target 19
  24:260 reduce
  23:: reduce
  24:261 reduce
  24:262 reduce
  24:263 reduce
  26:266,target 6
  16:0,target 16
  24:264 reduce
  24:265 reduce
  24:266 reduce
  17::,target 17
  24:267 reduce
  24:257,target 3
  24:270 reduce
  24:271 reduce
  9:258,target 11
  21:265,target 5
  36:260,target 23
  6:266,target 8
  33:267,target 25
  37:0 reduce
  4:257,target 1
  15:264,target 15
  31:258,target 8
  1:265,target 12
  27:266,target 7
  37:: reduce
  3::,target 9
  25:257,target 4
  29:257 reduce
  29:258 reduce
  29:260 reduce
  29:261 reduce
  37:260,target 21
  29:262 reduce
  29:263 reduce
  13:0,target 13
  29:264 reduce
  7:266,target 8
  29:265 reduce
  34:267,target 9
  29:266 reduce
  14::,target 14
  29:267 reduce
  4:274,target 13
  29:270 reduce
  29:271 reduce
  5:257,target 1
  16:264,target 7
  32:258,target 2
  28:266,target 18
  10:? shift
  26:257,target 6
  23:265,target 2
  8:266,target 10
  35:267,target 20
  5:274,target 13
  35:257 reduce
  24:0 reduce
  32:275,target 14
  35:258 reduce
  6:257,target 1
  17:264,target 7
  35:260 reduce
  33:258,target 22
  35:261 reduce
  35:262 reduce
  35:263 reduce
  3:265,target 9
  35:264 reduce
  29:266,target 19
  35:265 reduce
  35:266 reduce
  35:267 reduce
  0:273,target 12
  24:: reduce
  35:270 reduce
  12:263,target 6
  35:271 reduce
  27:257,target 7
  24:265,target 3
  9:266,target 11
  36:267,target 25
  6:274,target 13
  33:275,target 27
  7:257,target 1
  18:264,target 7
  34:258,target 2
  10:?,target 20
  31:266,target 8
  13:263,target 13
  28:257,target 18
  37:0,target 21
  25:265,target 4
  37:267,target 21
  0:257 shift
  7:274,target 13
  0:258 shift
  34:275,target 14
  0:260 shift
  0:261 shift
  8:257,target 10
  19:264,target 7
  35:258,target 20
  0:262 shift
  11:0 accept
  0:263 shift
  0:264 shift
  0:266 shift
  32:266,target 8
  0:267 shift
  0:270 shift
  0:272 goto
  14:263,target 14
  0:273 goto
  29:257,target 19
  0:274 goto
  0:275 goto
  0:264,target 7
  26:265,target 6
  9:257,target 11
  21:264,target 5
  36:258,target 22
  35::,target 20
  16:257 shift
  16:258 shift
  33:266,target 24
  16:260 shift
  25:0 reduce
  16:261 shift
  16:262 shift
  16:263 shift
  5:257 shift
  16:264 shift
  5:258 shift
  15:263,target 15
  16:265 reduce
  5:260 shift
  16:266 shift
  31:257,target 8
  5:261 shift
  16:267 shift
  5:262 shift
  5:263 shift
  1:264,target 12
  16:270 shift
  5:264 shift
  16:271 reduce
  25:: reduce
  27:265,target 7
  5:266 shift
  5:267 shift
  16:274 goto
  16:275 goto
  5:270 shift
  5:273 goto
  36:275,target 27
  5:274 goto
  5:275 goto
  37:258,target 21
  34:266,target 8
  4:273,target 16
  16:263,target 6
  32:257,target 1
  31:0,target 8
  13:271,target 13
  22:257 shift
  28:265,target 18
  23:264,target 2
  8:265,target 10
  35:266,target 20
  12:0 reduce
  5:273,target 17
  32:274,target 13
  17:263,target 6
  33:257,target 21
  3:264,target 9
  14:271,target 14
  29:265,target 19
  0:272,target 11
  12:262,target 5
  27:0,target 7
  24:264,target 3
  27:257 reduce
  28::,target 18
  27:258 reduce
  9:265,target 11
  27:260 reduce
  36:266,target 24
  27:261 reduce
  27:262 reduce
  27:263 reduce
  6:273,target 18
  27:264 reduce
  33:274,target 26
  27:265 reduce
  18:263,target 6
  27:266 reduce
  34:257,target 1
  26:0 reduce
  27:267 reduce
  27:270 reduce
  4:264,target 7
  15:271,target 15
  27:271 reduce
  31:265,target 8
  1:0 reduce
  13:262,target 13
  26:: reduce
  25:264,target 4
  37:266,target 21
  1:: reduce
  7:273,target 19
  34:274,target 13
  19:263,target 6
  35:257,target 20
  24:0,target 3
  33:257 shift
  5:264,target 7
  16:271,target 16
  25::,target 4
  33:258 shift
  33:260 shift
  33:261 shift
  33:262 shift
  33:263 shift
  33:264 shift
  14:262,target 14
  33:266 shift
  33:267 shift
  0:263,target 6
  33:270 shift
  26:264,target 6
  33:271 shift
  33:274 goto
  33:275 goto
  21:263,target 5
  36:257,target 21
  9:0,target 11
  13:0 reduce
  6:264,target 7
  17:271,target 17
  15:262,target 15
  13:: reduce
  21:0,target 5
  1:263,target 12
  12:270,target 10
  27:264,target 7
  36:274,target 26
  37:257,target 21
  7:264,target 7
  27:0 reduce
  16:262,target 5
  13:270,target 13
  28:264,target 18
  27:: reduce
  17:0,target 17
  23:263,target 2
  8:264,target 10
  35:265,target 20
  14:257 reduce
  14:258 reduce
  32:273,target 33
  14:260 reduce
  17:262,target 5
  14:261 reduce
  14:262 reduce
  14:263 reduce
  3:263,target 9
  3:257 reduce
  14:264 reduce
  14:270,target 14
  3:258 reduce
  14:265 reduce
  29:264,target 19
  3:260 reduce
  14:266 reduce
  3:261 reduce
  14:267 reduce
  3:262 reduce
  3:263 reduce
  14:270 reduce
  3:264 reduce
  12:261,target 4
  14:271 reduce
  3:265 reduce
  3:266 reduce
  3:267 reduce
  3:270 reduce
  24:263,target 3
  3:271 reduce
  3:0,target 9
  9:264,target 11
  21:271,target 5
  14:0 reduce
  18:262,target 5
  14:0,target 14
  4:263,target 6
  15:270,target 15
  15::,target 15
  31:264,target 8
  1:271,target 12
  14:: reduce
  13:261,target 13
  19:257 shift
  20:257 shift
  19:258 shift
  19:260 shift
  19:261 shift
  19:262 shift
  19:263 shift
  25:263,target 4
  8:257 reduce
  19:264 shift
  8:258 reduce
  19:265 shift
  8:260 reduce
  19:266 shift
  8:261 reduce
  19:267 shift
  37:265,target 21
  8:262 reduce
  8:263 reduce
  19:270 shift
  8:264 reduce
  8:265 reduce
  34:273,target 36
  8:266 reduce
  8:267 reduce
  19:274 goto
  19:262,target 5
  19:275 goto
  8:270 reduce
  8:271 reduce
  28:0 reduce
  5:263,target 6
  16:270,target 10
  32:264,target 7
  1::,target 12
  14:261,target 14
  3:0 reduce
  28:: reduce
  0:262,target 5
  11:0,target 0
  26:263,target 6
  23:271,target 2
  3:: reduce
  25:257 reduce
  25:258 reduce
  25:260 reduce
  21:262,target 5
  25:261 reduce
  25:262 reduce
  25:263 reduce
  25:264 reduce
  6:263,target 6
  17:270,target 10
  25:265 reduce
  33:264,target 7
  25:266 reduce
  25:267 reduce
  3:271,target 9
  25:270 reduce
  25:271 reduce
  15:261,target 15
  1:262,target 12
  27:263,target 7
  24:271,target 3
  7:263,target 6
  18:270,target 10
  34:264,target 7
  15:0 reduce
  31:257 reduce
  16:261,target 4
  31:258 reduce
  31:260 reduce
  31:261 reduce
  31:262 reduce
  31:263 reduce
  15:: reduce
  28:263,target 18
  31:264 reduce
  31:265 reduce
  31:266 reduce
  31:267 reduce
  25:271,target 4
  31:270 reduce
  31:271 reduce
  23:262,target 2
  8:263,target 10
  19:270,target 10
  35:264,target 20
  35:0,target 20
  29:0 reduce
  17:261,target 4
  3:262,target 9
  29:263,target 19
  0:270,target 10
  26:271,target 6
  29:: reduce
  30:: shift
  12:260,target 23
  36:257 shift
  36:258 shift
  36:260 shift
  36:261 shift
  36:262 shift
  24:262,target 3
  36:263 shift
  36:264 shift
  36:266 shift
  9:263,target 11
  21:270,target 5
  36:264,target 7
  36:267 shift
  36:270 shift
  36:271 shift
  18:261,target 4
  36:274 goto
  36:275 goto
  4:262,target 5
  31:263,target 8
  1:270,target 12
  27:271,target 7
  13:260,target 13
  33::,target 34
  25:262,target 4
  37:264,target 21
  19:261,target 4
  16:0 reduce
  12:257 shift
  5:262,target 5
  12:258 shift
  12:260 shift
  32:263,target 6
  12:261 shift
  12:262 shift
  12:263 shift
  1:257 reduce
  12:264 shift
  28:271,target 18
  1:258 reduce
  14:260,target 14
  1:260 reduce
  12:266 shift
  16:: reduce
  1:261 reduce
  12:267 shift
  1:262 reduce
  0:261,target 4
  1:263 reduce
  12:270 shift
  1:264 reduce
  26:262,target 6
  1:265 reduce
  1:266 reduce
  1:267 reduce
  12:274 goto
  12:275 goto
  23:270,target 2
  1:270 reduce
  1:271 reduce
  8:271,target 10
  28:0,target 18
  21:261,target 5
  29::,target 19
  30::,target 32
  6:262,target 5
  33:263,target 6
  31:0 reduce
  3:270,target 9
  29:271,target 19
  15:260,target 15
  1:261,target 12
  12:267,target 25
  17:257 shift
  27:262,target 7
  31:: reduce
  17:258 shift
  17:260 shift
  17:261 shift
  17:262 shift
  24:270,target 3
  17:263 shift
  6:257 shift
  17:264 shift
  6:258 shift
  17:265 reduce
  6:260 shift
  9:271,target 11
  17:266 shift
  6:261 shift
  17:267 shift
  6:262 shift
  6:263 shift
  17:270 shift
  6:264 shift
  17:271 reduce
  7:262,target 5
  6:266 shift
  34:263,target 6
  6:267 shift
  17:274 goto
  17:275 goto
  6:270 shift
  4:270,target 10
  31:271,target 8
  6:273 goto
  16:260,target 23
  25:0,target 4
  6:274 goto
  6:275 goto
  26::,target 6
  13:267,target 13
  28:262,target 18
  25:270,target 4
  23:261,target 2
  23:257 reduce
  23:258 reduce
  8:262,target 10
  23:260 reduce
  35:263,target 20
  23:261 reduce
  23:262 reduce
  17:0 reduce
  23:263 reduce
  5:270,target 10
  23:264 reduce
  23:265 reduce
  17:260,target 23
  23:266 reduce
  23:267 reduce
  23:270 reduce
  3:261,target 9
  14:267,target 14
  23:271 reduce
  29:262,target 19
  17:: reduce
  26:270,target 6
  12:258,target 22
  23::,target 2
  24:261,target 3
  9:262,target 11
  36:263,target 6
  6:270,target 10
  33:271,target 35
  18:260,target 23
  4:261,target 4
  15:267,target 15
  28:257 reduce
  28:258 reduce
  31:262,target 8
  28:260 reduce
  28:261 reduce
  12:275,target 27
  28:262 reduce
  27:270,target 7
  28:263 reduce
  13:258,target 13
  28:264 reduce
  28:265 reduce
  28:266 reduce
  28:267 reduce
  25:261,target 4
  28:270 reduce
  28:271 reduce
  8::,target 10
  37:263,target 21
  7:270,target 10
  19:260,target 23
  5:261,target 4
  16:267,target 25
  32:262,target 5
  28:270,target 18
  14:258,target 14
  0:260,target 3
  26:261,target 6
  34:257 shift
  34:258 shift
  34:260 shift
  34:261 shift
  34:262 shift
  34:263 shift
  34:264 shift
  8:270,target 10
  35:271,target 20
  34:266 shift
  34:267 shift
  21:260,target 5
  34:270 shift
  6:261,target 4
  17:267,target 25
  34:273 goto
  33:262,target 5
  34:274 goto
  34:275 goto
  29:270,target 19
  15:258,target 15
  15:0,target 15
  1:260,target 12
  12:266,target 24
  16::,target 16
  27:261,target 7
  9:270,target 11
  36:271,target 37
  7:261,target 4
  18:267,target 25
  34:262,target 5
  31:270,target 8
  16:258,target 22
  1:0,target 12
  13:266,target 13
  28:261,target 18
  33:: shift
  12:0,target 1
  37:271,target 21
  23:260,target 2
  13::,target 13
  8:261,target 10
  19:267,target 25
  35:262,target 20
  16:275,target 27
  32:270,target 10
  17:258,target 22
  3:260,target 9
  14:266,target 14
  29:261,target 19
  0:267,target 9
  12:257,target 21
  15:257 reduce
  15:258 reduce
  15:260 reduce
  15:261 reduce
  15:262 reduce
  15:263 reduce
  24:260,target 3
  4:257 shift
  15:264 reduce
  4:258 shift
  15:265 reduce
  4:260 shift
  15:266 reduce
  4:261 shift
  9:261,target 11
  15:267 reduce
  21:267,target 5
  36:262,target 5
  4:262 shift
  4:263 shift
  15:270 reduce
  4:264 shift
  15:271 reduce
  17:275,target 27
  33:270,target 10
  4:266 shift
  4:267 shift
  18:258,target 22
  4:270 shift
  4:260,target 3
  15:266,target 15
  4:273 goto
  31:261,target 8
  4:274 goto
  4:275 goto
  1:267,target 12
  12:274,target 26
  13:257,target 13
  25:260,target 4
  37:262,target 21
  21:257 reduce
  18:275,target 27
  21:258 reduce
  34:270,target 10
  21:260 reduce
  19:258,target 22
  21:261 reduce
  21:262 reduce
  21:263 reduce
  9:257 reduce
  21:264 reduce
  5:260,target 3
  9:258 reduce
  16:266,target 24
  21:265 reduce
  9:260 reduce
  21:266 reduce
  32:261,target 4
  9:261 reduce
  21:267 reduce
  9:262 reduce
  9:263 reduce
  21:270 reduce
  9:264 reduce
  21:271 reduce
  9:265 reduce
  14:257,target 14
  37::,target 21
  9:266 reduce
  8:0 reduce
  9:267 reduce
  0:258,target 2
  9:270 reduce
  9:271 reduce
  26:260,target 6
  23:267,target 2
  8:: reduce
  19:275,target 27
  35:270,target 20
  21:258,target 5
}

array set ::format_rules {
  9,l 273
  11,l 273
  15,l 273
  20,l 275
  19,l 274
  2,l 273
  6,l 273
  12,l 273
  16,l 274
  21,l 275
  3,l 273
  7,l 273
  13,l 273
  0,l 276
  17,l 274
  4,l 273
  8,l 273
  10,l 273
  14,l 273
  18,l 274
  1,l 272
  5,l 273
}

array set ::format_rules {
  5,dc 2
  0,dc 1
  17,dc 2
  12,dc 1
  8,dc 3
  21,dc 8
  3,dc 2
  15,dc 2
  10,dc 1
  6,dc 2
  18,dc 3
  1,dc 1
  13,dc 1
  9,dc 1
  4,dc 2
  16,dc 2
  11,dc 1
  7,dc 2
  20,dc 6
  19,dc 3
  2,dc 2
  14,dc 1
}

array set ::format_rules {
  13,line 62
  7,line 44
  10,line 53
  4,line 35
  18,line 79
  1,line 24
  15,line 68
  9,line 50
  12,line 59
  6,line 41
  21,line 98
  3,line 32
  17,line 76
  14,line 65
  8,line 47
  11,line 56
  5,line 38
  20,line 91
  19,line 82
  2,line 29
  16,line 73
}

proc format_parse {} {
    set format_state_stack {0}
    set format_value_stack {{}}
    set format_token ""
    set format_accepted 0
    while {$format_accepted == 0} {
        set format_state [lindex $format_state_stack end]
        if {$format_token == ""} {
            set ::format_lval ""
            set format_token [format_lex]
            set format_buflval $::format_lval
        }
        if {![info exists ::format_table($format_state:$format_token)]} {
            # pop off states until error token accepted
            while {[llength $format_state_stack] > 0 && \
                       ![info exists ::format_table($format_state:error)]} {
                set format_state_stack [lrange $format_state_stack 0 end-1]
                set format_value_stack [lrange $format_value_stack 0 \
                                       [expr {[llength $format_state_stack] - 1}]]
                set format_state [lindex $format_state_stack end]
            }
            if {[llength $format_state_stack] == 0} {
                format_error "parse error"
                return 1
            }
            lappend format_state_stack [set format_state $::format_table($format_state:error,target)]
            lappend format_value_stack {}
            # consume tokens until it finds an acceptable one
            while {![info exists ::format_table($format_state:$format_token)]} {
                if {$format_token == 0} {
                    format_error "end of file while recovering from error"
                    return 1
                }
                set ::format_lval {}
                set format_token [format_lex]
                set format_buflval $::format_lval
            }
            continue
        }
        switch -- $::format_table($format_state:$format_token) {
            shift {
                lappend format_state_stack $::format_table($format_state:$format_token,target)
                lappend format_value_stack $format_buflval
                set format_token ""
            }
            reduce {
                set format_rule $::format_table($format_state:$format_token,target)
                set format_l $::format_rules($format_rule,l)
                if {[info exists ::format_rules($format_rule,e)]} {
                    set format_dc $::format_rules($format_rule,e)
                } else {
                    set format_dc $::format_rules($format_rule,dc)
                }
                set format_stackpointer [expr {[llength $format_state_stack]-$format_dc}]
                format_setupvalues $format_value_stack $format_stackpointer $format_dc
                set _ $1
                set ::format_lval [lindex $format_value_stack end]
                switch -- $format_rule {
                    1 { 
        set ::format_value $1
       }
                    2 { 
          set _ "$1$2"
         }
                    3 { 
          set _ "$1\\n"
         }
                    4 { 
          set _ "$1\\t"
         }
                    5 { 
          set _ "$1$2"
         }
                    6 { 
          set _ "$1$2"
         }
                    7 { 
          set _ "$1$2"
         }
                    8 { 
          set _ [lindex $::format_matches $3]
         }
                    9 { 
          set _ $1
         }
                    10 { 
          set _ "\\n"
         }
                    11 { 
          set _ "\\t"
         }
                    12 { 
          set _ $1
         }
                    13 { 
          set _ $1
         }
                    14 { 
          set _ $1
         }
                    15 { 
          set _ [lindex $::format_matches $2]
         }
                    16 { 
              set _ "[string tolower [string index $2 0]][string range $2 1 end]"
             }
                    17 { 
              set _ [string totitle $2]
             }
                    18 { 
              set _ [string tolower $2]
             }
                    19 { 
              set _ [string toupper $2]
             }
                    20 { 
               if {[llength [lindex $::format_matches end]] <= $3} {
                 set _ $5
               } else {
                 set _ ""
               }
              }
                    21 { 
               if {[llength [lindex $::format_matches end]] <= $3} {
                 set _ $5
               } else {
                 set _ $7
               }
              }
                }
                format_unsetupvalues $format_dc
                # pop off tokens from the stack if normal rule
                if {![info exists ::format_rules($format_rule,e)]} {
                    incr format_stackpointer -1
                    set format_state_stack [lrange $format_state_stack 0 $format_stackpointer]
                    set format_value_stack [lrange $format_value_stack 0 $format_stackpointer]
                }
                # now do the goto transition
                lappend format_state_stack $::format_table([lindex $format_state_stack end]:$format_l,target)
                lappend format_value_stack $_
            }
            accept {
                set format_accepted 1
            }
            goto -
            default {
                puts stderr "Internal parser error: illegal command $::format_table($format_state:$format_token)"
                return 2
            }
        }
    }
    return 0
}

######
# end autogenerated taccle functions
######

rename format_error format_error_orig
proc format_error {s} {
  set ::format_errstr "[string repeat " " $::format_begpos]^"
  set ::format_errmsg $s
}

