# TKE - Advanced Programmer's Editor
# Copyright (C) 2014-2019  Trevor Williams (phase1geo@gmail.com)
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

######################################################################
# Name:    snip_parser.tac
# Author:  Trevor Williams  (phase1geo@gmail.com)
# Date:    8/10/2015
# Brief:   Parser for snippet syntax.
######################################################################

source [file join $::tke_dir lib snip_lexer.tcl]

set snip_txtt   ""
set snip_value  ""
set snip_errmsg ""
set snip_errstr ""
set snip_pos    0

proc get_retval {args} {
  return [join $args {}]
}

proc merge_values {val1 val2} {
  if {[lindex $val1 end] eq ""} {
    lset val1 end-1 "[lindex $val1 end-1][lindex $val2 0]"
    return "[lrange $val1 0 end-1] [list [lindex $val2 1]]"
  }
  return [concat $val1 $val2]
}

proc apply_tabstop {ts_val ts_tag} {
  set retval [list]
  foreach {val tag} $ts_val {
    lappend retval $val [concat $tag $ts_tag]
  }
  return $retval
}

proc parse_format {str matches} {

  FORMAT__FLUSH_BUFFER

  # Insert the string to scan
  format__scan_string $str

  # Initialize some values
  set ::format_txtt    $::snip_txtt
  set ::format_begpos  0
  set ::format_endpos  0
  set ::format_matches $matches

  # Parse the string
  if {[catch { format_parse } rc] || ($rc != 0)} {
    snippets::display_error $str $::format_errstr $::format_errmsg
    return ""
  }

  return $::format_value

}


######
# Begin autogenerated taccle (version 1.1) routines.
# Although taccle itself is protected by the GNU Public License (GPL)
# all user-supplied functions are protected by their respective
# author's license.  See http://mini.net/tcl/taccle for other details.
######

proc SNIP_ABORT {} {
    return -code return 1
}

proc SNIP_ACCEPT {} {
    return -code return 0
}

proc snip_clearin {} {
    upvar snip_token t
    set t ""
}

proc snip_error {s} {
    puts stderr $s
}

proc snip_setupvalues {stack pointer numsyms} {
    upvar 1 1 y
    set y {}
    for {set i 1} {$i <= $numsyms} {incr i} {
        upvar 1 $i y
        set y [lindex $stack $pointer]
        incr pointer
    }
}

proc snip_unsetupvalues {numsyms} {
    for {set i 1} {$i <= $numsyms} {incr i} {
        upvar 1 $i y
        unset y
    }
}

array set ::snip_table {
  122:266,target 85
  56:257 reduce
  56:258 reduce
  63:266,target 50
  56:260 reduce
  123::,target 86
  46:/,target 59
  56:266 reduce
  56:267 reduce
  1:258,target 72
  56:270 reduce
  87:271,target 13
  56:271 reduce
  126:258,target 99
  34::,target 60
  36:269,target 58
  36:270,target 58
  67:258,target 61
  138:261,target 97
  21:/ shift
  16:257,target 10
  1:/,target 72
  28:260,target 3
  21:: shift
  74:/,target 24
  62:257 reduce
  100:262,target 98
  62:258 reduce
  62:260 reduce
  21:? shift
  112:264,target 100
  62:266 reduce
  92:0,target 17
  31:`,target 61
  62:267 reduce
  62:269 reduce
  65:266,target 56
  136:268,target 14
  46:280,target 67
  3:258,target 75
  77:/ reduce
  71:284,target 105
  26:267,target 5
  38:269,target 66
  38:270,target 66
  77:: reduce
  69:258,target 75
  70:258,target 61
  141:261,target 97
  21:` shift
  67:257 shift
  67:258 shift
  67:260 shift
  77:? reduce
  18:257,target 8
  67:266 shift
  94:263,target 91
  67:267 shift
  67:269 shift
  31:260,target 61
  102:262,target 90
  1:266,target 72
  67:274 goto
  67:276 goto
  67:282 goto
  126:266,target 99
  67:266,target 85
  48:280,target 70
  22:/ reduce
  22:0 reduce
  5:258,target 71
  73:257 reduce
  92:271,target 17
  73:258 reduce
  86:`,target 43
  26:?,target 5
  73:260 reduce
  28:267,target 3
  100:270,target 103
  22:: reduce
  131:258,target 87
  73:266 reduce
  41:269,target 63
  41:270,target 63
  73:267 reduce
  22:? reduce
  72:258,target 29
  73:270 reduce
  73:271 reduce
  23:0,target 20
  21:257,target 34
  96:263,target 88
  122:/,target 85
  33:260,target 64
  104:262,target 98
  3:266,target 75
  78:/ reduce
  116:264,target 84
  54:?,target 31
  78:257 reduce
  78:258 reduce
  78:260 reduce
  109::,target 95
  110::,target 96
  33:/,target 64
  69:266,target 77
  70:266,target 85
  78:: reduce
  22:` reduce
  78:266 reduce
  78:267 reduce
  78:? reduce
  78:270 reduce
  7:258,target 68
  78:271 reduce
  134:284,target 105
  94:271,target 91
  31:267,target 61
  102:270,target 90
  21::,target 32
  74:258,target 24
  8:?,target 69
  67:274,target 88
  23:257,target 20
  98:263,target 99
  137::,target 18
  84:257 reduce
  35:260,target 57
  84:258 reduce
  23:/ reduce
  84:260 reduce
  106:262,target 94
  23:0 reduce
  5:266,target 71
  5:0,target 71
  84:266 reduce
  17:`,target 9
  84:267 reduce
  84:269 reduce
  131:266,target 87
  23:: reduce
  72:266,target 29
  23:? reduce
  9:258,target 70
  96:271,target 88
  33:267,target 64
  104:270,target 103
  88:/,target 48
  45:270,target 56
  76:258,target 21
  79:/ reduce
  80:/ reduce
  89:257 reduce
  90:257 reduce
  89:258 reduce
  90:258 reduce
  89:260 reduce
  90:260 reduce
  70:274,target 88
  89:266 reduce
  90:266 reduce
  25:257,target 16
  3::,target 75
  89:267 reduce
  90:267 reduce
  76::,target 21
  79:: reduce
  80:: reduce
  89:269 reduce
  90:269 reduce
  23:` reduce
  37:260,target 59
  108:262,target 98
  79:? reduce
  80:? reduce
  7:266,target 68
  121:264,target 82
  102:?,target 90
  74:266,target 24
  0:`,target 4
  67:282,target 90
  95:257 shift
  138:284,target 122
  13:?,target 74
  35:267,target 57
  106:270,target 94
  137:258,target 18
  47:270,target 56
  78:258,target 23
  100:285,target 106
  10:0,target 77
  91:261,target 97
  129:?,target 15
  27:257,target 4
  108:/,target 124
  39:260,target 67
  40:260,target 62
  111:262,target 98
  9:266,target 70
  123:264,target 86
  41:?,target 63
  20:/,target 11
  19:/,target 31
  76:266,target 21
  37:0,target 59
  70:282,target 90
  141:284,target 122
  37:267,target 59
  136:/,target 14
  108:270,target 103
  140:258,target 100
  139:258,target 95
  49:270,target 38
  50:270,target 37
  93:261,target 92
  29:257,target 34
  30:257,target 6
  101:260,target 89
  11:271,target 78
  42:260,target 79
  102:257 reduce
  102:258 reduce
  113:262,target 98
  102:260 reduce
  102:261 reduce
  102:262 reduce
  102:263 reduce
  102:264 reduce
  125:264,target 98
  102:265 reduce
  102:266 reduce
  102:267 reduce
  102:270 reduce
  137:266,target 18
  35::,target 57
  102:271 reduce
  25:/ reduce
  25:0 reduce
  78:266,target 23
  0:/ shift
  25:: reduce
  96:?,target 88
  2:/,target 76
  25:? reduce
  39:267,target 67
  40:267,target 62
  75:/,target 25
  111:270,target 103
  142:258,target 101
  0:: shift
  52:270,target 34
  83:258,target 44
  0:? shift
  104:285,target 123
  32:`,target 65
  32:257,target 65
  13:271,target 74
  82:/ reduce
  140:266,target 100
  139:266,target 101
  25:` reduce
  0:` shift
  59:`,target 53
  60:`,target 52
  113:257 shift
  101:267,target 89
  113:258 shift
  113:260 shift
  0:272,target 14
  113:261 shift
  113:262 shift
  42:267,target 79
  113:263 shift
  113:264 shift
  113:270,target 103
  113:265 shift
  113:266 shift
  113:267 shift
  54:270,target 31
  113:270 shift
  85:258,target 42
  116:?,target 84
  97:261,target 97
  26:/ reduce
  26:0 reduce
  34:257,target 60
  105:260,target 93
  82:` reduce
  15:271,target 13
  113:284 goto
  113:285 goto
  46:260,target 62
  117:262,target 83
  1:/ reduce
  1:0 reduce
  26:: reduce
  87:`,target 13
  27:?,target 4
  26:? reduce
  71:264,target 100
  142:266,target 101
  118:257 shift
  1:: reduce
  83:266,target 44
  1:? reduce
  123:/,target 86
  83:/ reduce
  115:269,target 129
  56:270,target 35
  87:258,target 13
  108:285,target 123
  55:?,target 32
  99:261,target 97
  26:` reduce
  111::,target 97
  34:/,target 60
  36:257,target 58
  17:271,target 9
  48:260,target 62
  124:260 shift
  119:262,target 80
  120:262,target 81
  1:` reduce
  124:269 shift
  22::,target 12
  85:266,target 42
  100:? shift
  124:279 goto
  9:?,target 70
  27:/ reduce
  105:267,target 93
  138::,target 139
  27:0 reduce
  62:/,target 49
  83:` reduce
  91:284,target 105
  46:267,target 64
  117:270,target 83
  2:/ reduce
  58:270,target 79
  2:0 reduce
  129:257 reduce
  27:: reduce
  89:258,target 46
  90:258,target 47
  129:258 reduce
  18:`,target 8
  129:260 reduce
  130:260 shift
  111:285,target 123
  27:? reduce
  49::,target 38
  50::,target 37
  129:266 reduce
  129:267 reduce
  2:: reduce
  38:257,target 66
  129:268 reduce
  109:260,target 95
  110:260,target 119
  129:269 reduce
  129:270 reduce
  130:269 shift
  129:271 reduce
  20:271,target 11
  19:271,target 41
  2:? reduce
  51:260,target 33
  122:262,target 85
  134:264,target 100
  3:257 reduce
  3:258 reduce
  3:260 reduce
  84:/ reduce
  89:/,target 46
  90:/,target 47
  87:266,target 13
  3:266 reduce
  3:267 reduce
  3:268 reduce
  3:269 reduce
  3:270 reduce
  3:271 reduce
  46:`,target 4
  27:` reduce
  4::,target 2
  135:260 reduce
  77::,target 22
  48:267,target 64
  119:270,target 80
  120:270,target 81
  101:/ reduce
  2:` reduce
  135:269 reduce
  92:258,target 17
  103:?,target 114
  113:285,target 123
  20:257 reduce
  19:257 shift
  20:258 reduce
  19:258 reduce
  20:260 reduce
  19:260 shift
  100:257,target 94
  10:268,target 77
  101:: reduce
  8:257 reduce
  41:257,target 63
  8:258 reduce
  112:260,target 119
  20:266 reduce
  19:266 shift
  8:260 reduce
  22:271,target 12
  20:267 reduce
  19:267 shift
  101:? reduce
  20:268 reduce
  19:268 shift
  20:270 reduce
  20:269 reduce
  19:270 shift
  19:269 shift
  53:260,target 30
  20:271 reduce
  19:271 shift
  1:`,target 72
  8:266 reduce
  8:267 reduce
  8:268 reduce
  28:/ reduce
  8:270 reduce
  8:269 reduce
  28:0 reduce
  8:271 reduce
  141:257 shift
  84:` reduce
  141:258 shift
  141:260 shift
  141:261 shift
  141:262 shift
  141:263 shift
  141:264 shift
  3:/ reduce
  89:266,target 46
  90:266,target 47
  3:0 reduce
  141:266 shift
  28:: reduce
  141:267 shift
  11:0,target 78
  141:270 shift
  131:?,target 87
  141:271 shift
  28:? reduce
  109:/,target 95
  109:267,target 95
  110:/,target 96
  110:267,target 121
  25:257 reduce
  3:: reduce
  25:258 reduce
  25:260 reduce
  51:267,target 33
  122:270,target 85
  3:? reduce
  141:284 goto
  141:285 goto
  25:266 reduce
  63:269,target 50
  25:267 reduce
  25:268 reduce
  94:258,target 91
  25:270 reduce
  25:269 reduce
  42:?,target 79
  25:271 reduce
  85:/ reduce
  102:257,target 90
  21:/,target 31
  12:268,target 73
  55:260,target 32
  38:0,target 66
  126:262,target 99
  28:` reduce
  138:264,target 100
  137:/,target 18
  31:257 reduce
  61:277,target 25
  102:/ reduce
  3:` reduce
  31:258 reduce
  31:260 reduce
  92:266,target 17
  69:?,target 73
  31:266 reduce
  31:267 reduce
  31:268 reduce
  31:269 reduce
  31:270 reduce
  102:: reduce
  125::,target 98
  31:271 reduce
  48:/,target 59
  112:267,target 121
  97:284,target 105
  53:267,target 30
  102:? reduce
  124:269,target 132
  65:269,target 56
  96:258,target 88
  29:/ shift
  30:/ reduce
  29:0 reduce
  30:0 reduce
  85:` reduce
  36::,target 58
  104:257,target 117
  45:257,target 51
  4:/ shift
  116:260,target 84
  26:271,target 5
  29:: shift
  30:: reduce
  36:257 reduce
  57:260,target 36
  36:258 reduce
  36:260 reduce
  29:? shift
  30:? reduce
  97:?,target 93
  141:264,target 100
  3:/,target 75
  4:: shift
  36:266 reduce
  76:/,target 21
  36:267 reduce
  36:268 reduce
  36:269 reduce
  36:270 reduce
  4:? shift
  36:271 reduce
  94:266,target 91
  33:`,target 64
  102:265,target 90
  1:269,target 72
  1:270,target 72
  86:/ reduce
  99:284,target 105
  55:267,target 32
  126:270,target 99
  67:269,target 87
  29:` reduce
  30:` reduce
  98:258,target 95
  42:257 reduce
  42:258 reduce
  42:260 reduce
  106:257,target 94
  16:268,target 10
  42:266 reduce
  47:257,target 51
  42:267 reduce
  42:268 reduce
  28:271,target 3
  42:269 reduce
  42:270 reduce
  42:271 reduce
  59:260,target 53
  60:260,target 52
  131:262,target 87
  92::,target 17
  103:? shift
  96:266,target 88
  31:/ reduce
  117:?,target 83
  31:0 reduce
  86:` reduce
  3:269,target 75
  3:270,target 75
  47:257 shift
  47:258 shift
  116:267,target 84
  47:260 shift
  5:/ reduce
  5:0 reduce
  31:: reduce
  57:267,target 36
  128:269,target 40
  47:266 shift
  47:267 shift
  31:? reduce
  69:270,target 79
  70:269,target 92
  88:`,target 48
  28:?,target 3
  47:270 shift
  47:271 shift
  5:: reduce
  108:257,target 117
  18:268,target 8
  5:? reduce
  47:278 goto
  49:257,target 38
  50:257,target 37
  121:260,target 82
  31:271,target 61
  25:0,target 16
  62:260,target 49
  87:/ reduce
  87:0 reduce
  11:258,target 78
  53:257 reduce
  53:258 reduce
  53:260 reduce
  87:: reduce
  98:266,target 101
  31:` reduce
  56:?,target 35
  53:266 reduce
  87:? reduce
  53:267 reduce
  106:265,target 94
  5:269,target 71
  5:270,target 71
  53:270 reduce
  35:/,target 57
  53:271 reduce
  104:/ shift
  5:` reduce
  59:267,target 53
  60:267,target 52
  131:270,target 87
  72:270,target 29
  23::,target 20
  104:? shift
  111:257,target 117
  21:268,target 38
  52:257,target 34
  123:260,target 86
  33:271,target 64
  58:257 shift
  32:/ reduce
  58:258 shift
  32:0 reduce
  58:260 shift
  64:260,target 51
  87:` reduce
  140::,target 100
  58:266 shift
  63:/,target 50
  58:267 shift
  13:258,target 74
  58:270 shift
  32:: reduce
  58:271 shift
  7:0,target 68
  32:? reduce
  20:`,target 11
  19:`,target 7
  7:270,target 68
  7:269,target 68
  51::,target 33
  121:267,target 82
  62:267,target 49
  133:269,target 137
  136:`,target 14
  74:270,target 24
  88:/ reduce
  64:257 reduce
  64:258 reduce
  64:260 reduce
  11:266,target 78
  0:260,target 7
  113:257,target 117
  23:268,target 20
  64:266 reduce
  64:267 reduce
  54:257,target 31
  64:269 reduce
  125:260,target 98
  32:` reduce
  35:271,target 57
  66:260,target 54
  5::,target 71
  78::,target 23
  105:/ reduce
  15:258,target 6
  91:264,target 100
  104:?,target 116
  105:: reduce
  111:265,target 97
  9:270,target 70
  9:269,target 70
  69:257 shift
  70:257 shift
  105:? reduce
  69:258 shift
  70:258 shift
  69:260 shift
  70:260 shift
  123:267,target 86
  64:267,target 51
  2:`,target 76
  33:/ reduce
  69:266 shift
  70:266 shift
  135:269,target 39
  33:0 reduce
  69:267 shift
  70:267 shift
  15:?,target 3
  69:270 shift
  70:269 shift
  88:` reduce
  69:271 shift
  76:270,target 21
  70:274 goto
  13:266,target 74
  2:260,target 76
  7:/ reduce
  70:276 goto
  7:0 reduce
  33:: reduce
  25:268,target 16
  70:282 goto
  56:257,target 35
  33:? reduce
  12:0,target 73
  37:271,target 59
  132:?,target 19
  7:: reduce
  68:260,target 55
  140:262,target 100
  139:262,target 98
  111:/,target 97
  7:? reduce
  17:258,target 9
  75:257 reduce
  75:258 reduce
  93:264,target 92
  75:260 reduce
  89:/ reduce
  90:/ reduce
  101:263,target 89
  0:267,target 9
  75:266 reduce
  75:267 reduce
  75:270 reduce
  113:265,target 126
  22:/,target 12
  75:271 reduce
  125:267,target 98
  33:` reduce
  66:267,target 54
  137:270,target 18
  39:0,target 67
  40:0,target 62
  137:269,target 18
  78:270,target 23
  10::,target 77
  106:/ reduce
  15:266,target 8
  7:` reduce
  4:260,target 7
  117:257,target 83
  27:268,target 4
  58:257,target 74
  81:257 shift
  129:260,target 15
  130:260,target 135
  39:271,target 67
  40:271,target 62
  81:259 shift
  106:: reduce
  71:?,target 93
  71:260,target 96
  142:262,target 101
  106:? reduce
  126::,target 99
  49:/,target 38
  50:/,target 37
  20:258,target 11
  19:258,target 7
  34:/ reduce
  34:0 reduce
  81:277 goto
  89:` reduce
  90:` reduce
  2:267,target 76
  8:/ reduce
  37::,target 59
  8:0 reduce
  34:: reduce
  34:? reduce
  68:267,target 55
  140:270,target 100
  139:270,target 103
  8:: reduce
  98:?,target 93
  86:257 reduce
  86:258 reduce
  4:/,target 1
  86:260 reduce
  8:? reduce
  77:/,target 22
  17:266,target 9
  6:259,target 23
  86:266 reduce
  119:257,target 80
  120:257,target 81
  86:267 reduce
  29:268,target 38
  30:268,target 6
  86:269 reduce
  101:271,target 89
  61:257,target 22
  0:275,target 17
  132:260,target 19
  34:`,target 60
  42:271,target 79
  73:260,target 28
  22:258,target 12
  34:` reduce
  97:264,target 100
  91:? shift
  105:263,target 93
  15:274,target 26
  4:267,target 9
  8:` reduce
  92:257 reduce
  117:265,target 83
  92:258 reduce
  92:260 reduce
  129:267,target 15
  92:266 reduce
  71:267,target 102
  92:267 reduce
  107:: shift
  142:270,target 101
  62:`,target 49
  92:268 reduce
  92:269 reduce
  92:270 reduce
  92:271 reduce
  83:269,target 44
  93::,target 92
  20:266,target 11
  19:266,target 36
  8:260,target 69
  122:257,target 85
  35:/ reduce
  32:268,target 65
  35:0 reduce
  63:257,target 50
  134:260,target 96
  75:260,target 25
  9:/ reduce
  9:0 reduce
  35:: reduce
  97:257 shift
  35:? reduce
  97:258 shift
  97:260 shift
  97:261 shift
  99:264,target 100
  97:262 shift
  9:: reduce
  97:263 shift
  81:277,target 44
  89:`,target 46
  90:`,target 47
  97:264 shift
  29:?,target 33
  30:?,target 6
  97:266 shift
  97:267 shift
  9:? reduce
  97:270 shift
  119:265,target 80
  120:265,target 81
  132:267,target 19
  92:/ reduce
  26:0,target 5
  92:0 reduce
  73:267,target 28
  97:283 goto
  97:284 goto
  97:285 goto
  85:269,target 42
  125:/,target 98
  22:266,target 12
  92:: reduce
  35:` reduce
  34:268,target 60
  92:? reduce
  105:271,target 93
  65:257,target 56
  15:282,target 30
  136:260,target 14
  57:?,target 36
  108:/ shift
  9:` reduce
  77:260,target 22
  36:/,target 58
  26:258,target 5
  108:? shift
  109:263,target 95
  110:263,target 99
  8:267,target 69
  122:265,target 85
  36:/ reduce
  36:0 reduce
  134:267,target 102
  92:` reduce
  75:267,target 25
  1:257,target 72
  36:: reduce
  87:269,target 13
  87:270,target 13
  104:257 shift
  64:/,target 51
  104:258 shift
  104:260 shift
  104:261 shift
  139:285,target 106
  104:262 shift
  36:? reduce
  104:263 shift
  104:264 shift
  126:257,target 99
  8:0,target 69
  104:266 shift
  36:268,target 58
  104:267 shift
  21:`,target 42
  67:257,target 83
  104:270 shift
  138:260,target 119
  79:260,target 26
  80:260,target 27
  52::,target 34
  93:/ reduce
  104:284 goto
  28:258,target 3
  104:285 goto
  100:261,target 97
  137:`,target 18
  112:263,target 99
  92:/,target 17
  93:: reduce
  109:257 reduce
  110:257 shift
  36:` reduce
  109:258 reduce
  110:258 shift
  109:260 reduce
  110:260 shift
  93:? reduce
  109:261 reduce
  110:261 shift
  109:262 reduce
  110:262 shift
  136:267,target 14
  109:263 reduce
  110:263 shift
  109:264 reduce
  110:264 shift
  48:`,target 4
  109:265 reduce
  110:265 reduce
  77:267,target 22
  109:266 reduce
  110:266 shift
  109:/ reduce
  109:267 reduce
  110:/ reduce
  110:267 shift
  109:270 reduce
  110:270 shift
  3:257,target 75
  109:271 reduce
  110:271 reduce
  79::,target 26
  80::,target 27
  89:269,target 46
  90:269,target 47
  71:283,target 104
  26:266,target 5
  109:: reduce
  110:: reduce
  38:268,target 66
  109:271,target 95
  110:271,target 96
  69:257,target 74
  70:257,target 83
  105:?,target 93
  110:284 goto
  141:260,target 119
  109:? reduce
  110:? shift
  110:285 goto
  51:271,target 33
  82:260,target 45
  37:/ reduce
  37:0 reduce
  94:262,target 91
  3:`,target 75
  31:258,target 61
  102:261,target 90
  115:260 shift
  16:?,target 10
  37:: reduce
  115:269 shift
  37:? reduce
  126:265,target 99
  138:267,target 121
  13:0,target 74
  115:279 goto
  79:267,target 26
  80:267,target 27
  5:257,target 71
  92:269,target 17
  92:270,target 17
  28:266,target 3
  94:/ reduce
  131:257,target 87
  129:0,target 15
  41:268,target 63
  72:257,target 29
  121:257 reduce
  121:258 reduce
  121:260 reduce
  53:271,target 30
  121:261 reduce
  121:262 reduce
  23:/,target 20
  84:260,target 41
  94:: reduce
  121:263 reduce
  121:264 reduce
  121:265 reduce
  37:` reduce
  121:266 reduce
  121:267 reduce
  94:? reduce
  96:262,target 88
  121:270 reduce
  121:271 reduce
  33:258,target 64
  41:0,target 63
  104:261,target 97
  111:/ reduce
  116:263,target 84
  140:/,target 100
  11::,target 78
  111:: reduce
  141:267,target 121
  111:? shift
  72:?,target 29
  82:267,target 45
  126:257 reduce
  127::,target 134
  7:257,target 68
  51:/,target 33
  126:258 reduce
  134:283,target 138
  94:270,target 91
  126:260 reduce
  38:/ reduce
  126:261 reduce
  38:0 reduce
  126:262 reduce
  126:263 reduce
  31:266,target 61
  126:264 reduce
  126:265 reduce
  126:266 reduce
  126:267 reduce
  126:270 reduce
  126:271 reduce
  74:257,target 24
  38:: reduce
  55:271,target 32
  11:257 reduce
  38::,target 66
  11:258 reduce
  86:260,target 43
  11:260 reduce
  38:? reduce
  0:257 shift
  98:262,target 98
  0:258 shift
  11:266 reduce
  0:260 shift
  11:267 reduce
  11:268 reduce
  35:258,target 57
  11:270 reduce
  11:269 reduce
  106:261,target 94
  11:271 reduce
  99:?,target 93
  0:266 shift
  0:267 shift
  5:/,target 71
  0:268 shift
  0:269 shift
  0:270 shift
  78:/,target 23
  0:271 shift
  0:272 goto
  0:273 goto
  132:257 reduce
  0:274 goto
  131:265,target 87
  132:258 reduce
  0:275 goto
  132:260 reduce
  0:276 goto
  0:281 goto
  35:`,target 57
  0:282 goto
  132:266 reduce
  132:267 reduce
  84:267,target 41
  132:268 reduce
  132:269 reduce
  132:270 reduce
  132:271 reduce
  9:257,target 70
  38:` reduce
  96:270,target 88
  16:257 reduce
  16:258 reduce
  16:260 reduce
  33:266,target 64
  5:257 reduce
  5:258 reduce
  16:266 reduce
  5:260 reduce
  116:271,target 84
  16:267 reduce
  76:257,target 21
  16:268 reduce
  16:270 reduce
  16:269 reduce
  16:271 reduce
  57:271,target 36
  5:266 reduce
  88:260,target 48
  5:267 reduce
  5:268 reduce
  5:269 reduce
  5:270 reduce
  5:271 reduce
  137:257 reduce
  137:258 reduce
  112:? shift
  137:260 reduce
  37:258,target 59
  63:`,target 50
  108:261,target 97
  137:266 reduce
  94::,target 91
  121:263,target 82
  137:267 reduce
  39:/ reduce
  40:/ reduce
  137:268 reduce
  39:0 reduce
  40:0 reduce
  137:269 reduce
  137:270 reduce
  137:271 reduce
  22:257 reduce
  22:258 reduce
  22:260 reduce
  119:?,target 80
  120:?,target 81
  39:: reduce
  40:: reduce
  86:267,target 43
  22:266 reduce
  22:267 reduce
  39:? reduce
  40:? reduce
  22:268 reduce
  22:270 reduce
  22:269 reduce
  98:270,target 103
  22:271 reduce
  35:266,target 57
  137:257,target 18
  31:?,target 61
  78:257,target 23
  100:284,target 105
  10:/,target 77
  91:260,target 96
  96:/ reduce
  27:0,target 4
  39:258,target 67
  40:258,target 62
  27:257 reduce
  111:261,target 97
  27:258 reduce
  27:260 reduce
  96:: reduce
  126:/,target 99
  39:` reduce
  40:` reduce
  123:263,target 86
  96:? reduce
  27:266 reduce
  27:267 reduce
  27:268 reduce
  27:270 reduce
  27:269 reduce
  27:271 reduce
  58:?,target 73
  88:267,target 48
  37:/,target 59
  37:266,target 59
  113:? shift
  140:257,target 100
  139:257,target 94
  121:271,target 82
  81:257,target 107
  25::,target 16
  33:257 reduce
  41:/ reduce
  33:258 reduce
  41:0 reduce
  33:260 reduce
  93:260,target 92
  33:266 reduce
  101:258,target 89
  33:267 reduce
  11:270,target 78
  11:269,target 78
  33:268 reduce
  33:269 reduce
  33:270 reduce
  41:: reduce
  33:271 reduce
  42:258,target 79
  113:261,target 97
  142::,target 101
  41:? reduce
  65:/,target 56
  125:263,target 98
  9:0,target 70
  22:`,target 12
  91:267,target 102
  53::,target 30
  38:257 reduce
  38:258 reduce
  38:260 reduce
  39:266,target 67
  40:266,target 62
  142:257,target 101
  38:266 reduce
  38:267 reduce
  38:268 reduce
  123:271,target 86
  38:269 reduce
  38:270 reduce
  83:257,target 44
  38:271 reduce
  41:` reduce
  93:/,target 92
  104:284,target 122
  97:? shift
  13:270,target 74
  13:269,target 74
  7::,target 68
  140:265,target 100
  106:?,target 94
  42:/ reduce
  42:0 reduce
  93:267,target 92
  101:266,target 89
  0:271,target 13
  42:266,target 79
  42:: reduce
  17:?,target 9
  98:285,target 106
  42:? reduce
  125:271,target 98
  85:257,target 42
  97:260,target 96
  14:0,target 0
  105:258,target 93
  15:269,target 11
  15:270,target 12
  134:?,target 93
  49:257 reduce
  50:257 reduce
  46:258,target 61
  49:258 reduce
  50:258 reduce
  49:260 reduce
  50:260 reduce
  117:261,target 83
  49:266 reduce
  50:266 reduce
  49:267 reduce
  50:267 reduce
  49:270 reduce
  50:270 reduce
  71:263,target 99
  142:265,target 101
  49:271 reduce
  50:271 reduce
  45:?,target 50
  42:` reduce
  101::,target 89
  98:? shift
  2:271,target 76
  42:0,target 79
  12::,target 73
  55:257 reduce
  87:257,target 13
  55:258 reduce
  55:260 reduce
  108:284,target 122
  99:260,target 96
  55:266 reduce
  55:267 reduce
  0:?,target 3
  55:270 reduce
  17:270,target 9
  17:269,target 9
  55:271 reduce
  73:?,target 28
  43:/ shift
  48:258,target 61
  119:261,target 80
  120:261,target 81
  52:/,target 34
  43:: shift
  10:260,target 77
  39::,target 67
  40::,target 62
  97:267,target 102
  61:257 shift
  61:259 shift
  105:266,target 93
  4:271,target 13
  91:283,target 108
  46:266,target 63
  61:268 shift
  129:271,target 15
  79:/,target 26
  80:/,target 27
  89:257,target 46
  90:257,target 47
  111:284,target 122
  61:277 goto
  36:`,target 58
  109:258,target 95
  110:258,target 118
  20:270,target 11
  20:269,target 11
  19:269,target 39
  19:270,target 40
  51:258,target 33
  99:? shift
  122:261,target 85
  134:263,target 99
  116:/ reduce
  66:257 reduce
  66:258 reduce
  66:260 reduce
  12:260,target 73
  66:266 reduce
  116:: reduce
  66:267 reduce
  99:267,target 102
  66:269 reduce
  116:? reduce
  48:266,target 63
  64:`,target 51
  44:/ shift
  61:268,target 81
  132:271,target 19
  92:257,target 17
  113:284,target 122
  73:271,target 28
  44:: shift
  10:267,target 77
  112:258,target 118
  121:?,target 82
  72:257 reduce
  22:270,target 12
  22:269,target 12
  72:258 reduce
  72:260 reduce
  53:258,target 30
  72:266 reduce
  72:267 reduce
  46:274,target 65
  72:270 reduce
  72:271 reduce
  92:`,target 17
  32:?,target 65
  11:/,target 78
  109:266,target 95
  110:266,target 120
  28:0,target 3
  8:271,target 69
  51:266,target 33
  77:257 reduce
  77:258 reduce
  77:260 reduce
  94:257,target 91
  117:/ reduce
  75:271,target 25
  77:266 reduce
  12:267,target 73
  77:267 reduce
  77:270 reduce
  77:271 reduce
  117:: reduce
  55:258,target 32
  38:/,target 66
  126:261,target 99
  117:? reduce
  138:263,target 99
  48:274,target 65
  16:260,target 10
  26::,target 5
  100:264,target 100
  83:257 reduce
  83:258 reduce
  45:: shift
  83:260 reduce
  112:266,target 120
  45:? shift
  97:283,target 110
  53:266,target 30
  83:266 reduce
  87:?,target 13
  83:267 reduce
  83:269 reduce
  66:/,target 54
  136:271,target 14
  96:257,target 88
  46:282,target 68
  77:271,target 22
  23:`,target 20
  116:258,target 84
  26:270,target 5
  26:269,target 5
  54::,target 31
  57:258,target 36
  141:263,target 99
  88:257 reduce
  88:258 reduce
  88:260 reduce
  18:260,target 8
  94:265,target 91
  88:266 reduce
  88:267 reduce
  94:/,target 91
  88:269 reduce
  102:264,target 90
  1:268,target 72
  24:277,target 44
  99:283,target 112
  55:266,target 32
  8::,target 69
  138:271,target 140
  98:257,target 94
  48:282,target 68
  79:271,target 26
  80:271,target 27
  16:267,target 10
  46:/ shift
  94:257 reduce
  94:258 reduce
  94:260 reduce
  28:270,target 3
  28:269,target 3
  94:261 reduce
  94:262 reduce
  59:258,target 53
  60:258,target 52
  94:263 reduce
  94:264 reduce
  131:261,target 87
  94:265 reduce
  94:266 reduce
  94:267 reduce
  94:270 reduce
  94:271 reduce
  5:`,target 71
  18:?,target 8
  21:260,target 35
  96:265,target 88
  104:264,target 100
  3:268,target 75
  15:0,target 1
  116:266,target 84
  57:266,target 36
  99:257 shift
  99:258 shift
  99:260 shift
  141:271,target 142
  99:261 shift
  99:262 shift
  99:263 shift
  99:264 shift
  99:266 shift
  99:267 shift
  132:0,target 19
  46:` shift
  18:267,target 8
  99:270 shift
  121:258,target 82
  31:269,target 61
  31:270,target 61
  102::,target 90
  25:/,target 16
  62:258,target 49
  119:/ reduce
  120:/ reduce
  99:283 goto
  99:284 goto
  99:285 goto
  11:257,target 78
  119:: reduce
  120:: reduce
  67:276,target 89
  23:260,target 20
  142:/,target 101
  13::,target 74
  119:? reduce
  120:? reduce
  106:264,target 94
  5:268,target 71
  101:257 reduce
  101:258 reduce
  101:260 reduce
  1:?,target 72
  101:261 reduce
  101:262 reduce
  74:?,target 24
  101:263 reduce
  101:264 reduce
  59:266,target 53
  60:266,target 52
  101:265 reduce
  101:266 reduce
  101:267 reduce
  129::,target 15
  53:/,target 30
  101:270 reduce
  101:271 reduce
  47:: shift
  47:? shift
  10:`,target 77
  21:267,target 37
  123:258,target 86
  33:269,target 64
  33:270,target 64
  41::,target 63
  64:258,target 51
  13:257,target 74
  106:257 reduce
  106:258 reduce
  106:260 reduce
  106:261 reduce
  7:/,target 68
  70:276,target 89
  106:262 reduce
  25:260,target 16
  106:263 reduce
  106:264 reduce
  106:265 reduce
  106:266 reduce
  106:267 reduce
  106:270 reduce
  108:264,target 100
  106:271 reduce
  7:268,target 68
  37:`,target 59
  121:266,target 82
  62:266,target 49
  121:/ reduce
  0:258,target 6
  121:: reduce
  23:267,target 20
  112:257 shift
  125:258,target 98
  112:258 shift
  121:? reduce
  35:269,target 57
  35:270,target 57
  112:260 shift
  112:261 shift
  66:258,target 54
  112:262 shift
  112:263 shift
  112:264 shift
  112:265 shift
  112:266 shift
  48:/ shift
  112:267 shift
  112:270 shift
  65:`,target 56
  15:257,target 5
  91:263,target 99
  27:260,target 4
  96::,target 88
  111:264,target 100
  112:284 goto
  112:285 goto
  9:268,target 70
  122:?,target 85
  123:266,target 86
  64:266,target 51
  101:/,target 89
  117:257 reduce
  117:258 reduce
  117:260 reduce
  117:261 reduce
  117:262 reduce
  2:258,target 76
  117:263 reduce
  117:264 reduce
  117:265 reduce
  117:266 reduce
  33:?,target 64
  117:267 reduce
  25:267,target 16
  117:270 reduce
  117:271 reduce
  12:/,target 73
  37:269,target 59
  37:270,target 59
  68:258,target 55
  140:261,target 100
  139:261,target 97
  48:` shift
  29:0,target 2
  30:0,target 6
  17:257,target 9
  93:263,target 92
  122:/ reduce
  29:260,target 35
  30:260,target 6
  101:262,target 89
  0:266,target 8
  113:264,target 100
  123:257 reduce
  123:258 reduce
  123:260 reduce
  122:: reduce
  123:261 reduce
  123:262 reduce
  123:263 reduce
  125:266,target 98
  123:264 reduce
  123:265 reduce
  122:? reduce
  123:266 reduce
  66:266,target 54
  116::,target 84
  123:267 reduce
  39:/,target 67
  40:/,target 62
  137:268,target 18
  123:270 reduce
  123:271 reduce
  49:/ reduce
  50:/ reduce
  27:267,target 4
  27::,target 4
  129:258,target 15
  49:: reduce
  50:: reduce
  39:269,target 67
  39:270,target 67
  40:269,target 62
  40:270,target 62
  71:258,target 95
  142:261,target 101
  49:? reduce
  50:? reduce
  20:257,target 11
  19:257,target 34
  128:260 reduce
  67:/,target 82
  32:260,target 65
  2:266,target 76
  128:269 reduce
  13:257 reduce
  13:258 reduce
  13:260 reduce
  55::,target 32
  68:266,target 55
  2:257 reduce
  2:258 reduce
  13:266 reduce
  2:260 reduce
  13:267 reduce
  13:268 reduce
  13:270 reduce
  13:269 reduce
  13:271 reduce
  2:266 reduce
  2:267 reduce
  93:271,target 92
  2:268 reduce
  2:269 reduce
  2:270 reduce
  2:271 reduce
  29:267,target 37
  30:267,target 6
  123:/ reduce
  101:270,target 89
  134:257 shift
  134:258 shift
  0:274,target 16
  132:258,target 19
  134:260 shift
  134:261 shift
  42:269,target 79
  42:270,target 79
  134:262 shift
  134:263 shift
  73:258,target 28
  134:264 shift
  134:266 shift
  134:267 shift
  123:: reduce
  134:270 shift
  22:257,target 12
  123:? reduce
  9::,target 70
  97:263,target 99
  18:257 reduce
  18:258 reduce
  18:260 reduce
  34:260,target 60
  105:262,target 93
  4:266,target 8
  7:257 reduce
  51:/ reduce
  134:283 goto
  7:258 reduce
  134:284 goto
  18:266 reduce
  7:260 reduce
  134:285 goto
  18:267 reduce
  117:264,target 83
  18:268 reduce
  18:270 reduce
  18:269 reduce
  18:271 reduce
  108:?,target 116
  7:266 reduce
  129:266,target 15
  7:267 reduce
  7:268 reduce
  7:270 reduce
  7:269 reduce
  51:: reduce
  7:271 reduce
  71:266,target 101
  140:257 reduce
  139:257 shift
  140:258 reduce
  139:258 shift
  140:260 reduce
  139:260 shift
  51:? reduce
  140:261 reduce
  139:261 shift
  140:262 reduce
  139:262 shift
  140:263 reduce
  139:263 shift
  140:264 reduce
  139:264 shift
  140:265 reduce
  8:258,target 69
  140:266 reduce
  139:266 shift
  140:267 reduce
  139:267 shift
  20:?,target 11
  19:?,target 33
  140:270 reduce
  139:270 shift
  140:271 reduce
  32:267,target 65
  134:258,target 95
  24:257 shift
  24:259 shift
  75:258,target 25
  139:283 goto
  16:0,target 10
  139:284 goto
  139:285 goto
  136:?,target 14
  24:257,target 43
  99:263,target 99
  36:260,target 58
  24:277 goto
  119:264,target 80
  120:264,target 81
  47:?,target 50
  0:282,target 20
  132:266,target 19
  26:/,target 5
  73:266,target 28
  29:257 shift
  30:257 reduce
  29:258 reduce
  30:258 reduce
  29:260 shift
  30:260 reduce
  29:266 shift
  30:266 reduce
  34:267,target 60
  29:267 shift
  30:267 reduce
  105:270,target 93
  29:268 shift
  30:268 reduce
  15:281,target 29
  29:269 shift
  29:270 shift
  30:269 reduce
  30:270 reduce
  136:258,target 14
  29:271 shift
  30:271 reduce
  52:/ reduce
  77:258,target 22
  2:?,target 76
  75:?,target 25
  26:257,target 5
  52:: reduce
  131::,target 87
  54:/,target 31
  38:260,target 66
  52:? reduce
  109:262,target 95
  110:262,target 98
  8:266,target 69
  122:264,target 85
  11:`,target 78
  35:257 reduce
  35:258 reduce
  35:260 reduce
  134:266,target 101
  42::,target 79
  115:279,target 130
  75:266,target 25
  35:266 reduce
  35:267 reduce
  35:268 reduce
  35:269 reduce
  35:270 reduce
  35:271 reduce
  87:268,target 13
  139:284,target 105
  8:/,target 69
  36:267,target 58
  82:/,target 45
  138:258,target 118
  79:258,target 26
  80:258,target 27
  38:`,target 66
  125:/ reduce
  28:257,target 3
  41:257 reduce
  41:258 reduce
  69::,target 72
  100:260,target 96
  41:260 reduce
  10:271,target 77
  41:260,target 63
  112:262,target 98
  125:: reduce
  41:266 reduce
  41:267 reduce
  41:268 reduce
  41:269 reduce
  41:270 reduce
  41:271 reduce
  125:? reduce
  136:266,target 14
  53:/ reduce
  77:266,target 22
  66:`,target 54
  53:: reduce
  38:267,target 66
  109:270,target 95
  110:270,target 103
  53:? reduce
  141:258,target 118
  46:257 shift
  46:258 shift
  46:260 shift
  51:270,target 33
  82:258,target 45
  46:266 shift
  123:?,target 86
  46:267 shift
  94:261,target 91
  31:257,target 61
  102:/,target 90
  102:260,target 90
  46:274 goto
  12:271,target 73
  46:276 goto
  46:280 goto
  46:282 goto
  126:264,target 99
  34:?,target 60
  138:266,target 120
  13:/,target 74
  79:266,target 26
  80:266,target 27
  52:257 reduce
  52:258 reduce
  92:268,target 17
  31:0,target 61
  52:260 reduce
  126:/ reduce
  100:267,target 102
  52:266 reduce
  52:267 reduce
  129:/,target 15
  41:267,target 63
  52:270 reduce
  112:270,target 103
  52:271 reduce
  126:: reduce
  53:270,target 30
  84:258,target 41
  126:? reduce
  96:261,target 88
  117::,target 83
  33:257,target 64
  41:/,target 63
  54:/ reduce
  104:260,target 119
  45:260,target 53
  116:262,target 84
  57:257 reduce
  54:: reduce
  57:258 reduce
  57:260 reduce
  141:266,target 120
  28::,target 3
  54:? reduce
  57:266 reduce
  57:267 reduce
  82:266,target 45
  57:270 reduce
  57:271 reduce
  102:267,target 90
  68:/,target 55
  55:270,target 32
  86:258,target 43
  25:`,target 16
  98:261,target 97
  63:257 reduce
  56::,target 35
  63:258 reduce
  35:257,target 57
  63:260 reduce
  106:260,target 94
  16:271,target 10
  47:260,target 53
  63:266 reduce
  63:267 reduce
  63:269 reduce
  131:264,target 87
  96:/,target 88
  124:279,target 133
  127:: shift
  84:266,target 41
  104:267,target 121
  55:/ reduce
  45:267,target 55
  68:257 reduce
  116:270,target 84
  68:258 reduce
  68:260 reduce
  57:270,target 36
  88:258,target 48
  55:: reduce
  68:266 reduce
  109:?,target 95
  110:?,target 116
  110:285,target 123
  68:267 reduce
  68:269 reduce
  55:? reduce
  37:257,target 59
  108:260,target 119
  18:271,target 8
  49:260,target 38
  50:260,target 37
  121:262,target 82
  7:`,target 68
  21:?,target 33
  86:266,target 43
  74:257 reduce
  74:258 reduce
  17:0,target 9
  74:260 reduce
  137:?,target 18
  74:266 reduce
  106:267,target 94
  74:267 reduce
  116:/,target 84
  74:270 reduce
  47:267,target 55
  74:271 reduce
  100:283,target 113
  59:269,target 53
  60:269,target 52
  91:258,target 95
  112:285,target 123
  27:/,target 4
  39:257,target 67
  40:257,target 62
  111:260,target 119
  21:271,target 41
  52:260,target 34
  123:262,target 86
  79:257 reduce
  80:257 reduce
  79:258 reduce
  80:258 reduce
  79:260 reduce
  80:260 reduce
  56:/ reduce
  15::,target 2
  79:266 reduce
  80:266 reduce
  79:267 reduce
  80:267 reduce
  79:270 reduce
  80:270 reduce
  88:266,target 48
  79:271 reduce
  80:271 reduce
  3:?,target 75
  56:: reduce
  76:?,target 21
  56:? reduce
  108:267,target 121
  132::,target 19
  55:/,target 32
  49:267,target 38
  50:267,target 37
  121:270,target 82
  62:269,target 49
  12:`,target 73
  93:258,target 92
  85:257 reduce
  101:257,target 89
  43::,target 46
  85:258 reduce
  11:268,target 78
  85:260 reduce
  42:257,target 79
  113:260,target 119
  23:271,target 20
  85:266 reduce
  54:260,target 31
  85:267 reduce
  125:262,target 98
  85:269 reduce
  9:/,target 70
  83:/,target 44
  91:266,target 101
  129:/ reduce
  129:0 reduce
  39:`,target 67
  40:`,target 62
  111:267,target 121
  129:: reduce
  91:257 shift
  52:267,target 34
  91:258 shift
  91:260 shift
  123:270,target 86
  91:261 shift
  129:? reduce
  91:262 shift
  91:263 shift
  64:269,target 51
  91:264 shift
  91:266 shift
  91:267 shift
  57:/ reduce
  91:270 shift
  13:268,target 74
  115:260,target 128
  25:271,target 16
  56:260,target 35
  57:: reduce
  91:283 goto
  67:`,target 4
  91:284 goto
  91:285 goto
  57:? reduce
  140:264,target 100
  139:264,target 100
  129:` reduce
  93:266,target 92
  96:257 reduce
  96:258 reduce
  96:260 reduce
  96:261 reduce
  96:262 reduce
  96:263 reduce
  101:265,target 89
  96:264 reduce
  0:269,target 11
  0:270,target 12
  96:265 reduce
  96:266 reduce
  96:267 reduce
  113:267,target 121
  96:270 reduce
  96:271 reduce
  98:284,target 105
  54:267,target 31
  125:270,target 98
  66:269,target 54
  35:?,target 57
  97:258,target 95
  105:257,target 93
  15:268,target 10
  46:257,target 60
  117:260,target 83
  131:/ reduce
  27:271,target 4
  32:0,target 65
  58:260,target 76
  71:262,target 98
  142:264,target 101
  131:/,target 87
  131:: reduce
  131:? reduce
  58:/ shift
  2:269,target 76
  2:270,target 76
  42:/,target 79
  56:267,target 35
  58:: shift
  68:269,target 55
  58:? shift
  99:258,target 95
  29::,target 32
  30::,target 6
  17:268,target 9
  48:257,target 60
  119:260,target 80
  120:260,target 81
  29:271,target 41
  30:271,target 6
  61:259,target 23
  91:?,target 93
  69:/,target 91
  70:/,target 82
  10:258,target 77
  97:266,target 101
  87:0,target 13
  26:`,target 5
  105:265,target 93
  15:276,target 28
  4:270,target 12
  4:269,target 11
  57::,target 36
  117:267,target 83
  132:/ reduce
  132:0 reduce
  58:267,target 78
  108:257 shift
  108:258 shift
  129:269,target 15
  129:270,target 15
  130:269,target 136
  108:260 shift
  108:261 shift
  108:262 shift
  71:270,target 103
  108:263 shift
  108:264 shift
  108:266 shift
  108:267 shift
  132:: reduce
  108:270 shift
  109:257,target 95
  110:257,target 117
  20:268,target 11
  19:268,target 38
  132:? reduce
  51:257,target 33
  122:260,target 85
  32:271,target 65
  63:260,target 50
  59:/ reduce
  60:/ reduce
  134:262,target 98
  108:284 goto
  108:285 goto
  12:258,target 73
  99:266,target 101
  114:257 shift
  111:?,target 116
  119:267,target 80
  120:267,target 81
  132:` reduce
  132:269,target 19
  132:270,target 19
  8:`,target 69
  82:`,target 45
  22:?,target 12
  73:270,target 28
  10:266,target 77
  112:257,target 117
  22:268,target 12
  53:257,target 30
  124:260,target 128
  18:0,target 8
  34:271,target 60
  138:?,target 116
  59:` reduce
  60:` reduce
  65:260,target 56
  119:257 reduce
  120:257 reduce
  119:258 reduce
  120:258 reduce
  117:/,target 83
  119:260 reduce
  120:260 reduce
  119:261 reduce
  120:261 reduce
  119:262 reduce
  120:262 reduce
  119:263 reduce
  120:263 reduce
  119:264 reduce
  120:264 reduce
  119:265 reduce
  120:265 reduce
  119:266 reduce
  120:266 reduce
  119:267 reduce
  120:267 reduce
  119:270 reduce
  120:270 reduce
  119:271 reduce
  120:271 reduce
  49:?,target 38
  50:?,target 37
  109:265,target 95
  110:265,target 96
  105::,target 93
  28:/,target 3
  8:270,target 69
  8:269,target 69
  122:267,target 85
  63:267,target 50
  134:270,target 103
  75:270,target 25
  16::,target 10
  12:266,target 73
  1:260,target 72
  125:257 reduce
  114:257,target 127
  125:258 reduce
  125:260 reduce
  125:261 reduce
  125:262 reduce
  55:257,target 32
  125:263 reduce
  125:264 reduce
  126:260,target 99
  125:265 reduce
  4:?,target 3
  36:271,target 58
  125:266 reduce
  125:267 reduce
  67:260,target 84
  77:?,target 22
  138:262,target 98
  6:277,target 25
  125:270 reduce
  125:271 reduce
  56:/,target 35
  10:257 reduce
  10:258 reduce
  16:258,target 10
  10:260 reduce
  1:0,target 72
  13:`,target 74
  10:266 reduce
  100:263,target 99
  10:267 reduce
  10:268 reduce
  10:270 reduce
  10:269 reduce
  10:271 reduce
  112:265,target 125
  44::,target 48
  131:257 reduce
  131:258 reduce
  65:267,target 56
  131:260 reduce
  131:261 reduce
  136:269,target 14
  136:270,target 14
  129:`,target 15
  131:262 reduce
  131:263 reduce
  131:264 reduce
  77:270,target 22
  131:265 reduce
  131:266 reduce
  131:267 reduce
  3:260,target 75
  84:/,target 41
  131:270 reduce
  131:271 reduce
  116:257,target 84
  71:285,target 106
  26:268,target 5
  15:257 shift
  15:258 shift
  57:257,target 36
  15:260 shift
  128:260,target 40
  38:271,target 66
  41:`,target 63
  4:257 shift
  69:260,target 76
  70:260,target 84
  141:262,target 98
  15:266 shift
  4:260 shift
  15:267 shift
  15:268 shift
  72::,target 29
  15:269 shift
  15:270 shift
  134:? shift
  15:271 shift
  4:266 shift
  18:258,target 8
  15:274 goto
  4:267 shift
  15:275 goto
  4:268 shift
  94:264,target 91
  15:276 goto
  4:270 shift
  4:269 shift
  4:271 shift
  62:/ reduce
  136:257 reduce
  15:281 goto
  102:263,target 90
  136:258 reduce
  15:282 goto
  136:260 reduce
  1:267,target 72
  4:281 goto
  136:266 reduce
  136:267 reduce
  136:268 reduce
  126:267,target 99
  136:269 reduce
  136:270 reduce
  136:271 reduce
  67:267,target 86
  138:270,target 103
  21:257 shift
  68:`,target 55
  21:260 shift
  79:270,target 26
  80:270,target 27
  9:257 reduce
  16:266,target 10
  9:258 reduce
  5:260,target 71
  21:266 shift
  9:260 reduce
  21:267 shift
  21:268 shift
  118:257,target 131
  21:269 shift
  21:270 shift
  28:268,target 3
  21:271 shift
  9:266 reduce
  59:257,target 53
  60:257,target 52
  9:267 reduce
  131:260,target 87
  9:268 reduce
  9:270 reduce
  9:269 reduce
  41:271,target 63
  125:?,target 98
  9:271 reduce
  72:260,target 29
  142:257 reduce
  142:258 reduce
  142:260 reduce
  104:/,target 115
  142:261 reduce
  142:262 reduce
  142:263 reduce
  142:264 reduce
  142:265 reduce
  142:266 reduce
  142:267 reduce
  96:264,target 88
  142:270 reduce
  62:` reduce
  142:271 reduce
  36:?,target 58
  104:263,target 99
  3:267,target 75
  26:257 reduce
  26:258 reduce
  26:260 reduce
  15:/,target 1
  116:265,target 84
  26:266 reduce
  26:267 reduce
  26:268 reduce
  26:270 reduce
  26:269 reduce
  33:0,target 64
  69:267,target 78
  70:267,target 86
  141:270,target 103
  26:271 reduce
  82:269,target 45
  132:/,target 19
  18:266,target 8
  7:260,target 68
  134:285,target 106
  121:257,target 82
  31:268,target 61
  63:/ reduce
  102:271,target 90
  62:257,target 49
  133:260,target 135
  74:260,target 24
  119::,target 80
  120::,target 81
  43:/,target 45
  32:257 reduce
  32:258 reduce
  32:260 reduce
  23:258,target 20
  98:264,target 100
  32:266 reduce
  32:267 reduce
  32:268 reduce
  106:263,target 94
  32:269 reduce
  32:270 reduce
  5:267,target 71
  32:271 reduce
  31::,target 61
  131:267,target 87
  72:267,target 29
  92:?,target 17
  84:269,target 41
  21:266,target 36
  9:260,target 70
  123:257,target 86
  37:257 reduce
  33:268,target 64
  37:258 reduce
  63:` reduce
  37:260 reduce
  64:257,target 51
  27:`,target 4
  135:260,target 39
  45:271,target 57
  37:266 reduce
  76:260,target 21
  37:267 reduce
  136:/ reduce
  37:268 reduce
  58::,target 72
  136:0 reduce
  37:269 reduce
  37:270 reduce
  37:271 reduce
  25:258,target 16
  136:: reduce
  108:263,target 99
  7:267,target 68
  136:? reduce
  121:265,target 82
  64:/ reduce
  74:267,target 24
  0:257,target 5
  86:269,target 43
  138:285,target 123
  23:266,target 20
  125:257,target 98
  35:268,target 57
  106:271,target 94
  66:257,target 54
  112:?,target 116
  137:260,target 18
  47:271,target 57
  78:260,target 23
  136:` reduce
  91:262,target 98
  27:258,target 4
  9:`,target 70
  83:`,target 44
  23:?,target 20
  111:263,target 99
  48:257 shift
  9:267,target 70
  48:258 shift
  48:260 shift
  123:265,target 86
  48:266 shift
  64:` reduce
  48:267 shift
  20:0,target 11
  19:0,target 7
  45:278,target 58
  140:?,target 100
  139:?,target 93
  76:267,target 21
  48:274 goto
  137:/ reduce
  2:257,target 76
  48:276 goto
  137:0 reduce
  88:269,target 48
  48:280 goto
  141:285,target 123
  25:266,target 16
  48:282 goto
  137:: reduce
  37:268,target 59
  136:0,target 14
  68:257,target 55
  140:260,target 100
  139:260,target 96
  51:?,target 33
  137:? reduce
  49:271,target 38
  50:271,target 37
  81:259,target 23
  106::,target 94
  29:/,target 31
  30:/,target 6
  54:257 reduce
  54:258 reduce
  54:260 reduce
  93:262,target 92
  65:/ reduce
  29:258,target 2
  30:258,target 6
  101:261,target 89
  54:266 reduce
  54:267 reduce
  54:270 reduce
  54:271 reduce
  113:263,target 99
  17::,target 9
  125:265,target 98
  137:267,target 18
  5:?,target 71
  47:278,target 69
  78:267,target 23
  78:?,target 23
  137:` reduce
  4:257,target 5
  57:/,target 36
  91:270,target 103
  27:266,target 4
  59:257 reduce
  60:257 reduce
  2:0,target 76
  59:258 reduce
  60:258 reduce
  129:257,target 15
  59:260 reduce
  60:260 reduce
  39:268,target 67
  40:268,target 62
  111:271,target 97
  71:257,target 94
  142:260,target 101
  52:271,target 34
  59:266 reduce
  60:266 reduce
  59:267 reduce
  60:267 reduce
  45::,target 49
  83:260,target 44
  59:269 reduce
  60:269 reduce
  10:/ reduce
  10:0 reduce
  65:` reduce
  32:258,target 65
  10:: reduce
  85:/,target 42
  10:? reduce
  138:: shift
  140:267,target 100
  139:267,target 102
  42:`,target 79
  65:257 reduce
  65:258 reduce
  138:? shift
  65:260 reduce
  0::,target 2
  6:257,target 22
  73::,target 28
  93:270,target 92
  65:266 reduce
  65:267 reduce
  66:/ reduce
  29:266,target 36
  30:266,target 6
  65:269 reduce
  0:273,target 15
  132:257,target 19
  42:268,target 79
  73:257,target 28
  54:271,target 31
  85:260,target 42
  10:` reduce
  97:262,target 98
  34:258,target 60
  70:`,target 4
  105:261,target 93
  10:?,target 77
  71:257 shift
  71:258 shift
  117:263,target 83
  71:260 shift
  71:261 shift
  71:262 shift
  71:263 shift
  71:264 shift
  71:266 shift
  71:267 shift
  142:267,target 101
  71:270 shift
  126:?,target 99
  83:267,target 44
  105:/,target 93
  11:/ reduce
  8:257,target 69
  11:0 reduce
  66:` reduce
  71:283 goto
  32:266,target 65
  71:284 goto
  71:285 goto
  134:257,target 94
  140:/ reduce
  11:: reduce
  37:?,target 59
  75:257,target 25
  56:271,target 35
  16:/,target 10
  11:? reduce
  87:260,target 13
  76:257 reduce
  76:258 reduce
  76:260 reduce
  140:: reduce
  99:262,target 98
  34:0,target 60
  36:258,target 58
  76:266 reduce
  140:? reduce
  139:? shift
  76:267 reduce
  76:270 reduce
  76:271 reduce
  119:263,target 80
  120:263,target 81
  67:/ shift
  0:281,target 19
  85:267,target 42
  121::,target 82
  11:` reduce
  44:/,target 47
  97:270,target 103
  34:266,target 60
  82:257 reduce
  82:258 reduce
  82:260 reduce
  136:257,target 14
  91:285,target 106
  117:271,target 83
  77:257,target 22
  82:266 reduce
  82:267 reduce
  32::,target 65
  58:271,target 80
  82:269 reduce
  89:260,target 46
  90:260,target 47
  38:258,target 66
  93:?,target 92
  109:261,target 95
  110:261,target 97
  12:/ reduce
  12:0 reduce
  72:/,target 29
  122:263,target 85
  67:` shift
  28:`,target 3
  12:: reduce
  87:257 reduce
  87:258 reduce
  87:260 reduce
  87:267,target 13
  12:? reduce
  139:283,target 141
  87:266 reduce
  87:267 reduce
  99:270,target 103
  87:268 reduce
  87:269 reduce
  87:270 reduce
  87:271 reduce
  36:266,target 58
  141:? shift
  138:257,target 117
  119:271,target 80
  120:271,target 81
  79:257,target 26
  80:257,target 27
  68:/ reduce
  92:260,target 17
  100:258,target 95
  10:270,target 77
  10:269,target 77
  41:258,target 63
  112:261,target 97
  93:257 reduce
  12:` reduce
  93:258 reduce
  87::,target 13
  93:260 reduce
  93:261 reduce
  93:262 reduce
  93:263 reduce
  93:264 reduce
  93:265 reduce
  4:281,target 21
  93:266 reduce
  93:267 reduce
  46:276,target 66
  93:270 reduce
  93:271 reduce
  113:?,target 116
  89:267,target 46
  90:267,target 47
  38:266,target 66
  141:257,target 117
  84:`,target 41
  122:271,target 85
  13:/ reduce
  82:257,target 45
  13:0 reduce
  68:` reduce
  98:257 shift
  94:260,target 91
  98:258 shift
  98:260 shift
  98:261 shift
  98:262 shift
  98:263 shift
  98:264 shift
  102:258,target 90
  142:/ reduce
  13:: reduce
  12:270,target 73
  12:269,target 73
  98:266 shift
  141:?,target 116
  98:267 shift
  98:270 shift
  13:? reduce
  119:/,target 80
  120:/,target 81
  126:263,target 99
  142:: reduce
  142:? reduce
  48:276,target 66
  98:283 goto
  137:0,target 18
  98:284 goto
  98:285 goto
  52:?,target 34
  92:267,target 17
  107::,target 46
  31:/,target 61
  69:/ shift
  70:/ shift
  100:266,target 101
  41:266,target 63
  100:257 shift
  100:258 shift
  69:: shift
  100:260 shift
  97:285,target 106
  100:261 shift
  100:262 shift
  13:` reduce
  100:263 shift
  84:257,target 41
  100:264 shift
  18::,target 8
  69:? shift
  100:266 shift
  100:267 shift
  96:260,target 88
  100:270 shift
  104:258,target 118
  79:?,target 26
  80:?,target 27
  45:258,target 52
  116:261,target 84
  100:283 goto
  58:/,target 71
  100:284 goto
  100:285 goto
  3:0,target 75
  15:`,target 4
  105:257 reduce
  14:0 accept
  105:258 reduce
  105:260 reduce
  70:` shift
  94:267,target 91
  105:261 reduce
  105:262 reduce
  105:263 reduce
  105:264 reduce
  105:265 reduce
  102:266,target 90
  105:266 reduce
  105:267 reduce
  1:271,target 72
  105:270 reduce
  105:271 reduce
  132:`,target 19
  99:285,target 106
  126:271,target 99
  86:257,target 43
  86:/,target 43
  98:260,target 96
  106:258,target 94
  16:270,target 10
  16:269,target 10
  47:258,target 52
  1::,target 72
  74::,target 24
  111:257 shift
  111:258 shift
  111:260 shift
  131:263,target 87
  111:261 shift
  111:262 shift
  111:263 shift
  111:264 shift
  111:265 reduce
  111:266 shift
  111:267 shift
  100:?,target 93
  111:270 shift
  111:271 reduce
  71:? shift
  96:267,target 88
  104:266,target 120
  3:271,target 75
  111:284 goto
  45:266,target 54
  111:285 goto
  11:?,target 78
  88:257,target 48
  110:284,target 122
  69:271,target 80
  116:257 reduce
  116:258 reduce
  116:260 reduce
  116:261 reduce
  116:262 reduce
  108:258,target 118
  116:263 reduce
  116:264 reduce
  18:270,target 8
  18:269,target 8
  15:/ shift
  116:265 reduce
  15:0 reduce
  116:266 reduce
  49:258,target 38
  50:258,target 37
  116:267 reduce
  121:261,target 82
  106:/,target 94
  116:270 reduce
  116:271 reduce
  15:: shift
  15:? shift
  11:260,target 78
  38:?,target 66
  17:/,target 9
  98:267,target 102
  106:266,target 94
  5:271,target 71
  35:0,target 57
  122:257 reduce
  47:266,target 54
  122:258 reduce
  122:260 reduce
  122:261 reduce
  122:262 reduce
  72:/ reduce
  122:263 reduce
  122:264 reduce
  122:265 reduce
  131:271,target 87
  91:257,target 94
  122:266 reduce
  122:267 reduce
  112:284,target 122
  72:271,target 29
  122:270 reduce
  122:271 reduce
  72:: reduce
  111:258,target 118
  15:` shift
  21:269,target 39
  21:270,target 40
  72:? reduce
  52:258,target 34
  122::,target 85
  123:261,target 86
  13:260,target 74
  33::,target 64
  108:266,target 120
  7:271,target 68
  16:/ reduce
  49:266,target 38
  50:266,target 37
  16:0 reduce
  94:?,target 91
  12:257 reduce
  12:258 reduce
  0:/,target 1
  12:260 reduce
  73:/,target 28
  93:257,target 92
  1:257 reduce
  1:258 reduce
  74:271,target 24
  16:: reduce
  12:266 reduce
  1:260 reduce
  12:267 reduce
  12:268 reduce
  12:270 reduce
  12:269 reduce
  11:267,target 78
  12:271 reduce
  16:? reduce
  29:`,target 2
  30:`,target 6
  1:266 reduce
  113:258,target 118
  1:267 reduce
  23:270,target 20
  23:269,target 20
  1:268 reduce
  1:269 reduce
  1:270 reduce
  1:271 reduce
  54:258,target 31
  125:261,target 98
  133:260 shift
  133:269 shift
  15:260,target 7
  73:/ reduce
  17:257 reduce
  17:258 reduce
  17:260 reduce
  6:257 shift
  73:: reduce
  111:266,target 120
  17:266 reduce
  9:271,target 70
  6:259 shift
  17:267 reduce
  16:` reduce
  17:268 reduce
  52:266,target 34
  17:270 reduce
  17:269 reduce
  73:? reduce
  17:271 reduce
  6:268 shift
  95:257,target 109
  138:257 shift
  76:271,target 21
  138:258 shift
  138:260 shift
  138:261 shift
  138:262 shift
  13:267,target 74
  6:277 goto
  138:263 shift
  138:264 shift
  138:266 shift
  138:267 shift
  25:270,target 16
  25:269,target 16
  138:270 shift
  56:258,target 35
  138:271 shift
  140:263,target 100
  139:263,target 99
  23:257 reduce
  23:258 reduce
  23:260 reduce
  17:/ reduce
  17:0 reduce
  85:`,target 42
  25:?,target 16
  138:284 goto
  138:285 goto
  23:266 reduce
  17:260,target 9
  23:267 reduce
  93:265,target 92
  23:268 reduce
  23:270 reduce
  23:269 reduce
  23:271 reduce
  101:264,target 89
  17:: reduce
  0:268,target 10
  113:266,target 120
  22:0,target 12
  17:? reduce
  142:?,target 101
  98:283,target 111
  54:266,target 31
  121:/,target 82
  137:271,target 18
  97:257,target 94
  78:271,target 23
  28:257 reduce
  15:267,target 9
  28:258 reduce
  28:260 reduce
  53:?,target 30
  74:/ reduce
  117:258,target 83
  27:270,target 4
  27:269,target 4
  32:/,target 65
  58:258,target 75
  28:266 reduce
  28:267 reduce
  28:268 reduce
  28:270 reduce
  28:269 reduce
  28:271 reduce
  71:261,target 97
  142:263,target 101
  74:: reduce
  17:` reduce
  74:? reduce
  20:260,target 11
  19:260,target 35
  20::,target 11
  19::,target 32
  2:268,target 76
  7:?,target 68
  56:266,target 35
  34:257 reduce
  34:258 reduce
  34:260 reduce
  136::,target 14
  59:/,target 53
  60:/,target 52
  140:271,target 100
  99:257,target 94
  34:266 reduce
  34:267 reduce
  34:268 reduce
  18:/ reduce
  34:269 reduce
  34:270 reduce
  18:0 reduce
  34:271 reduce
  17:267,target 9
  16:`,target 10
  119:258,target 80
  120:258,target 81
  29:270,target 40
  29:269,target 39
  30:269,target 6
  30:270,target 6
  47::,target 49
  0:276,target 18
  18:: reduce
  18:? reduce
  10:257,target 77
  22:260,target 12
  87:/,target 13
  39:257 reduce
  40:257 reduce
  39:258 reduce
  40:258 reduce
  39:260 reduce
  40:260 reduce
  105:264,target 93
  15:275,target 27
  4:268,target 10
  39:266 reduce
  40:266 reduce
  117:266,target 83
  39:267 reduce
  40:267 reduce
  75:/ reduce
  39:268 reduce
  40:268 reduce
  39:269 reduce
  39:270 reduce
  40:269 reduce
  40:270 reduce
  39:271 reduce
  40:271 reduce
  58:266,target 77
  2::,target 76
  129:268,target 15
  75::,target 25
  142:271,target 101
  75:: reduce
  18:` reduce
  75:? reduce
  20:267,target 11
  19:267,target 37
  101:?,target 89
  122:258,target 85
  32:269,target 65
  32:270,target 65
  63:258,target 50
  134:261,target 97
  45:257 shift
  45:258 shift
  45:260 shift
  12:257,target 73
  12:?,target 73
  45:266 shift
  45:267 shift
  24:259,target 23
  45:270 shift
  45:271 shift
  20:/ reduce
  19:/ shift
  6:268,target 24
  20:0 reduce
  19:0 reduce
  45:278 goto
  119:266,target 80
  120:266,target 81
  132:268,target 19
  20:: reduce
  19:: shift
  20:? reduce
  19:? shift
  51:257 reduce
  51:258 reduce
  22:267,target 12
  39:?,target 67
  40:?,target 62
  51:260 reduce
  18:/,target 8
  34:269,target 60
  34:270,target 60
  51:266 reduce
  51:267 reduce
  65:258,target 56
  51:270 reduce
  51:271 reduce
  36:0,target 58
  76:/ reduce
  26:260,target 5
  76:: reduce
  109:264,target 95
  110:264,target 100
  20:` reduce
  19:` reduce
  8:268,target 69
  76:? reduce
}

array set ::snip_rules {
  98,l 284
  9,l 273
  11,l 273
  32,l 278
  53,l 280
  74,l 281
  95,l 283
  6,l 273
  28,l 278
  50,l 280
  49,l 280
  71,l 281
  92,l 283
  3,l 273
  25,l 278
  46,l 280
  67,l 281
  0,l 286
  88,l 283
  22,l 278
  43,l 280
  64,l 281
  85,l 283
  18,l 276
  40,l 279
  39,l 279
  61,l 281
  82,l 283
  15,l 275
  36,l 278
  57,l 281
  78,l 281
  99,l 284
  12,l 274
  33,l 278
  54,l 280
  75,l 281
  96,l 284
  7,l 273
  29,l 278
  30,l 278
  51,l 280
  72,l 281
  93,l 283
  4,l 273
  26,l 278
  47,l 280
  68,l 281
  90,l 283
  89,l 283
  1,l 272
  23,l 278
  44,l 280
  65,l 281
  86,l 283
  19,l 276
  20,l 277
  41,l 280
  62,l 281
  83,l 283
  16,l 276
  37,l 278
  58,l 281
  80,l 283
  79,l 282
  13,l 274
  34,l 278
  100,l 285
  55,l 280
  76,l 281
  97,l 284
  8,l 273
  10,l 273
  31,l 278
  52,l 280
  73,l 281
  94,l 283
  5,l 273
  27,l 278
  48,l 280
  70,l 281
  69,l 281
  91,l 283
  2,l 273
  24,l 278
  45,l 280
  66,l 281
  87,l 283
  21,l 278
  42,l 280
  63,l 281
  84,l 283
  17,l 276
  38,l 278
  60,l 281
  59,l 281
  81,l 283
  14,l 275
  35,l 278
  101,l 285
  56,l 280
  77,l 281
}

array set ::snip_rules {
  63,dc 2
  12,dc 2
  77,dc 1
  26,dc 2
  100,dc 6
  92,dc 1
  3,dc 2
  41,dc 2
  55,dc 1
  70,dc 1
  69,dc 1
  18,dc 10
  84,dc 2
  33,dc 1
  98,dc 3
  9,dc 1
  47,dc 2
  62,dc 2
  11,dc 1
  76,dc 1
  25,dc 2
  91,dc 1
  2,dc 2
  40,dc 1
  39,dc 2
  54,dc 1
  68,dc 1
  17,dc 6
  83,dc 2
  32,dc 1
  97,dc 2
  8,dc 1
  46,dc 2
  61,dc 2
  10,dc 1
  75,dc 1
  24,dc 2
  90,dc 1
  89,dc 1
  1,dc 1
  38,dc 1
  53,dc 1
  67,dc 2
  16,dc 2
  82,dc 2
  31,dc 1
  96,dc 2
  7,dc 1
  45,dc 2
  60,dc 2
  59,dc 2
  74,dc 1
  23,dc 2
  0,dc 1
  88,dc 1
  37,dc 1
  52,dc 1
  66,dc 2
  15,dc 9
  81,dc 2
  29,dc 2
  30,dc 1
  95,dc 2
  6,dc 2
  44,dc 2
  58,dc 2
  73,dc 1
  22,dc 2
  87,dc 3
  36,dc 1
  51,dc 1
  65,dc 2
  14,dc 10
  80,dc 2
  79,dc 3
  28,dc 2
  94,dc 1
  5,dc 2
  43,dc 2
  57,dc 2
  72,dc 1
  21,dc 2
  86,dc 2
  35,dc 1
  50,dc 1
  49,dc 1
  64,dc 2
  13,dc 6
  78,dc 1
  27,dc 2
  101,dc 8
  93,dc 1
  4,dc 2
  42,dc 2
  56,dc 1
  71,dc 1
  19,dc 9
  20,dc 1
  85,dc 2
  34,dc 1
  99,dc 3
  48,dc 2
}

array set ::snip_rules {
  41,line 271
  96,line 444
  7,line 107
  37,line 255
  93,line 433
  4,line 98
  34,line 246
  90,line 424
  89,line 421
  1,line 87
  31,line 237
  86,line 412
  27,line 225
  83,line 403
  24,line 216
  80,line 394
  79,line 389
  21,line 207
  76,line 378
  17,line 159
  73,line 369
  14,line 144
  70,line 360
  69,line 357
  11,line 119
  66,line 348
  63,line 339
  60,line 330
  59,line 327
  56,line 316
  53,line 307
  50,line 298
  49,line 295
  46,line 286
  43,line 277
  98,line 450
  9,line 113
  40,line 266
  39,line 263
  95,line 439
  6,line 104
  36,line 252
  92,line 430
  3,line 95
  33,line 243
  88,line 418
  101,line 461
  29,line 231
  30,line 234
  85,line 409
  26,line 222
  82,line 400
  23,line 213
  78,line 384
  19,line 169
  20,line 202
  75,line 375
  16,line 156
  72,line 366
  13,line 131
  68,line 354
  10,line 116
  65,line 345
  62,line 336
  58,line 324
  55,line 313
  52,line 304
  48,line 292
  45,line 283
  42,line 274
  97,line 447
  8,line 110
  38,line 258
  94,line 436
  5,line 101
  35,line 249
  91,line 427
  2,line 92
  32,line 240
  87,line 415
  100,line 458
  28,line 228
  84,line 406
  25,line 219
  81,line 397
  22,line 210
  77,line 381
  18,line 166
  74,line 372
  15,line 151
  71,line 363
  12,line 128
  67,line 351
  64,line 342
  61,line 333
  57,line 321
  54,line 310
  51,line 301
  47,line 289
  44,line 280
  99,line 453
}

proc snip_parse {} {
    set snip_state_stack {0}
    set snip_value_stack {{}}
    set snip_token ""
    set snip_accepted 0
    while {$snip_accepted == 0} {
        set snip_state [lindex $snip_state_stack end]
        if {$snip_token == ""} {
            set ::snip_lval ""
            set snip_token [snip_lex]
            set snip_buflval $::snip_lval
        }
        if {![info exists ::snip_table($snip_state:$snip_token)]} {
            # pop off states until error token accepted
            while {[llength $snip_state_stack] > 0 && \
                       ![info exists ::snip_table($snip_state:error)]} {
                set snip_state_stack [lrange $snip_state_stack 0 end-1]
                set snip_value_stack [lrange $snip_value_stack 0 \
                                       [expr {[llength $snip_state_stack] - 1}]]
                set snip_state [lindex $snip_state_stack end]
            }
            if {[llength $snip_state_stack] == 0} {
                snip_error "parse error"
                return 1
            }
            lappend snip_state_stack [set snip_state $::snip_table($snip_state:error,target)]
            lappend snip_value_stack {}
            # consume tokens until it finds an acceptable one
            while {![info exists ::snip_table($snip_state:$snip_token)]} {
                if {$snip_token == 0} {
                    snip_error "end of file while recovering from error"
                    return 1
                }
                set ::snip_lval {}
                set snip_token [snip_lex]
                set snip_buflval $::snip_lval
            }
            continue
        }
        switch -- $::snip_table($snip_state:$snip_token) {
            shift {
                lappend snip_state_stack $::snip_table($snip_state:$snip_token,target)
                lappend snip_value_stack $snip_buflval
                set snip_token ""
            }
            reduce {
                set snip_rule $::snip_table($snip_state:$snip_token,target)
                set snip_l $::snip_rules($snip_rule,l)
                if {[info exists ::snip_rules($snip_rule,e)]} {
                    set snip_dc $::snip_rules($snip_rule,e)
                } else {
                    set snip_dc $::snip_rules($snip_rule,dc)
                }
                set snip_stackpointer [expr {[llength $snip_state_stack]-$snip_dc}]
                snip_setupvalues $snip_value_stack $snip_stackpointer $snip_dc
                set _ $1
                set ::snip_lval [lindex $snip_value_stack end]
                switch -- $snip_rule {
                    1 { 
        set ::snip_value $1
       }
                    2 { 
           set _ [concat $1 [list $2 {}]]
          }
                    3 { 
           set _ [concat $1 [list $2 {}]]
          }
                    4 { 
           set _ [concat $1 $2]
          }
                    5 { 
           set _ [concat $1 $2]
          }
                    6 { 
           set _ [concat $1 [list $2 {}]]
          }
                    7 { 
           set _ [list $1 {}]
          }
                    8 { 
           set _ [list $1 {}]
          }
                    9 { 
           set _ $1
          }
                    10 { 
           set _ $1
          }
                    11 { 
           set _ [list $1 {}]
          }
                    12 { 
           if {[set val [snippets::get_tabstop $::snip_txtt $2]] ne ""} {
             set _ [list $val {}]
           } else {
             set _ [list "\$$2" [snippets::set_tabstop $::snip_txtt $2]]
           }
          }
                    13 { 
           set _ [apply_tabstop $5 [snippets::set_tabstop $::snip_txtt $3 $5]]
          }
                    14 { 
             if {[set val [snippets::get_tabstop $::snip_txtt $3]] ne ""} {
               set regexp_opts [list]
               if {[string first g $9] != -1} {
                 lappend regexp_opts -all
               }
               set _ [list [parse_format $7 [regexp -inline {*}$regexp_opts -- $5 $val]] [list]]
             } else {
               set _ [list [get_retval $1 $2 $3 $4 $5 $6 $7 $8 $9 $10] [snippets::set_tabstop $::snip_txtt $3]]
             }
            }
                    15 { 
             if {[set val [snippets::get_tabstop $::snip_txtt $3]] ne ""} {
               set _ [list [parse_format $7 [regexp -inline -- $5 $val]] [list]]
             } else {
               set _ [list [get_retval $1 $2 $3 $4 $5 $6 $7 $8 $9] [snippets::set_tabstop $::snip_txtt $3]]
             }
            }
                    16 { 
            set _ $2
           }
                    17 { 
            set _ [expr {($3 eq "") ? [lindex $5 0] : $3}]
           }
                    18 { 
            set regexp_opts [list]
            if {[string first g $9] != -1} {
              lappend regexp_opts "-all"
            }
            set _ [parse_format $7 [regexp -inline {*}$regexp_opts -- $5 $3]]
           }
                    19 { 
            set _ [parse_format $7 [regexp -inline -- $5 $3]]
           }
                    20 { 
           set txtt $::snip_txtt
           switch -glob $1 {
             SELECTED_TEXT   { set _ [expr {![catch { $txtt get sel.first sel.last } rc] ? $rc : ""}] }
             CLIPBOARD       { set _ [expr {![catch "clipboard get" rc] ? $rc : ""}] }
             CURRENT_LINE    { set _ [$txtt get "insert linestart" "insert lineend"] }
             CURRENT_WORD    { set _ [$txtt get "insert wordstart" "insert wordend"] }
             DIRECTORY       { set _ [file dirname [gui::get_info {} current fname]] }
             FILEPATH        { set _ [gui::get_info {} current fname] }
             FILENAME        { set _ [file tail [gui::get_info {} current fname]] }
             LINE_INDEX      { set _ [lindex [split [$txtt index insert] .] 1] }
             LINE_NUMBER     { set _ [lindex [split [$txtt index insert] .] 0] }
             CURRENT_DATE    { set _ [clock format [clock seconds] -format "%m/%d/%Y"] }
             CURRENT_DATE2   { set _ [clock format [clock seconds] -format "%Y/%m/%d"] }
             CURRENT_TIME    { set _ [clock format [clock seconds] -format "%I:%M %p"] }
             CURRENT_MON     { set _ [clock format [clock seconds] -format "%b"] }
             CURRENT_MONTH   { set _ [clock format [clock seconds] -format "%B"] }
             CURRENT_MON1    { set _ [clock format [clock seconds] -format "%N"] }
             CURRENT_MON2    { set _ [clock format [clock seconds] -format "%m"] }
             CURRENT_DAYN    { set _ [clock format [clock seconds] -format "%a"] }
             CURRENT_DAYNAME { set _ [clock format [clock seconds] -format "%A"] }
             CURRENT_DAY1    { set _ [clock format [clock seconds] -format "%e"] }
             CURRENT_DAY2    { set _ [clock format [clock seconds] -format "%d"] }
             CURRENT_YEAR2   { set _ [clock format [clock seconds] -format "%y"] }
             CURRENT_YEAR    { set _ [clock format [clock seconds] -format "%Y"] }
             CLIPHIST*       {
               regexp {\[(\d+)\]} $1 -> index
               set _ [lindex [cliphist::get_history] $index 1]
             }
           }
          }
                    21 { 
           set _ "$1$2"
          }
                    22 { 
           set _ "$1\n"
          }
                    23 { 
           set _ "$1\t"
          }
                    24 { 
           set _ "$1$2"
          }
                    25 { 
           set _ "$1\$"
          }
                    26 { 
           set _ "$1\("
          }
                    27 { 
           set _ "$1)"
          }
                    28 { 
           set _ "?"
          }
                    29 { 
           set _ ":"
          }
                    30 { 
           set _ $1
          }
                    31 { 
           set _ "\n"
          }
                    32 { 
           set _ "\t"
          }
                    33 { 
           set _ $1
          }
                    34 { 
           set _ "\$"
          }
                    35 { 
           set _ "("
          }
                    36 { 
           set _ ")"
          }
                    37 { 
           set _ "?"
          }
                    38 { 
           set _ ":"
          }
                    39 { 
        set _ "$1$2"
       }
                    40 { 
        set _ $1
       }
                    41 { 
         set _ [merge_values $1 [list $2 {}]]
        }
                    42 { 
         set _ [merge_values $1 [list "\n" {}]]
        }
                    43 { 
         set _ [merge_values $1 [list "\t" {}]]
        }
                    44 { 
         set _ [merge_values $1 [list $2 {}]]
        }
                    45 { 
         set _ [merge_values $1 [list "/" {}]]
        }
                    46 { 
         set _ [merge_values $1 [list $2 {}]]
        }
                    47 { 
         set _ [merge_values $1 [list $2 {}]]
        }
                    48 { 
         set _ [concat $1 $2]
        }
                    49 { 
         set _ [list $1 {}]
        }
                    50 { 
         set _ [list "\n" {}]
        }
                    51 { 
         set _ [list "\t" {}]
        }
                    52 { 
         set _ [list $1 {}]
        }
                    53 { 
         set _ [list "/" {}]
        }
                    54 { 
         set _ [list $1 {}]
        }
                    55 { 
         set _ [list $1 {}]
        }
                    56 { 
         set _ $1
        }
                    57 { 
        set _ "$1$2"
       }
                    58 { 
        set _ "$1\\n"
       }
                    59 { 
        set _ "$1\\t"
       }
                    60 { 
        set _ "$1$2"
       }
                    61 { 
        set _ "$1/"
       }
                    62 { 
        set _ "$1\("
       }
                    63 { 
        set _ "$1)"
       }
                    64 { 
        set _ "$1?"
       }
                    65 { 
        set _ "$1:"
       }
                    66 { 
        set _ "$1$2"
       }
                    67 { 
        set _ "$1$2"
       }
                    68 { 
        set _ $1
       }
                    69 { 
        set _ "\\n"
       }
                    70 { 
        set _ "\\t"
       }
                    71 { 
        set _ $1
       }
                    72 { 
        set _ "/"
       }
                    73 { 
        set _ "("
       }
                    74 { 
        set _ ")"
       }
                    75 { 
        set _ "?"
       }
                    76 { 
        set _ ":"
       }
                    77 { 
        set _ $1
       }
                    78 { 
        set _ $1
       }
                    79 { 
         set _ [expr {![catch "exec $2" rc] ? $rc : ""}]
        }
                    80 { 
          set _ "$1$2"
         }
                    81 { 
          set _ "$1\n"
         }
                    82 { 
          set _ "$1\t"
         }
                    83 { 
          set _ "$1$2"
         }
                    84 { 
          set _ "$1?"
         }
                    85 { 
          set _ "$1$2"
         }
                    86 { 
          set _ "$1$2"
         }
                    87 { 
          set _ "$1\$$3"
         }
                    88 { 
          set _ $1
         }
                    89 { 
          set _ "\n"
         }
                    90 { 
          set _ "\t"
         }
                    91 { 
          set _ $1
         }
                    92 { 
          set _ "?"
         }
                    93 { 
          set _ $1
         }
                    94 { 
          set _ $1
         }
                    95 { 
          set _ "\$$2"
         }
                    96 { 
              set _ "$1$2"
             }
                    97 { 
              set _ "$1$2"
             }
                    98 { 
              set _ "$1$2$3"
             }
                    99 { 
              set _ "$1$2$3"
             }
                    100 { 
               set _ [get_retval $1 $2 $3 $4 $5 $6]
              }
                    101 { 
               set _ [get_retval $1 $2 $3 $4 $5 $6 $7 $8]
              }
                }
                snip_unsetupvalues $snip_dc
                # pop off tokens from the stack if normal rule
                if {![info exists ::snip_rules($snip_rule,e)]} {
                    incr snip_stackpointer -1
                    set snip_state_stack [lrange $snip_state_stack 0 $snip_stackpointer]
                    set snip_value_stack [lrange $snip_value_stack 0 $snip_stackpointer]
                }
                # now do the goto transition
                lappend snip_state_stack $::snip_table([lindex $snip_state_stack end]:$snip_l,target)
                lappend snip_value_stack $_
            }
            accept {
                set snip_accepted 1
            }
            goto -
            default {
                puts stderr "Internal parser error: illegal command $::snip_table($snip_state:$snip_token)"
                return 2
            }
        }
    }
    return 0
}

######
# end autogenerated taccle functions
######

rename snip_error snip_error_orig
proc snip_error {s} {
  set ::snip_errstr "[string repeat " " $::snip_begpos]^"
  set ::snip_errmsg $s
}

