source [file join $::tke_dir lib snip_lexer.tcl]

set snip_txt    ""
set snip_value  ""
set snip_errmsg ""
set snip_errstr ""
set snip_pos    0

proc get_retval {args} {
  return [join $args {}]
}

proc parse_format {str matches} {

  FORMAT__FLUSH_BUFFER

  # Insert the string to scan
  format__scan_string $str

  # Initialize some values
  set ::format_txt     $::snip_txt
  set ::format_begpos  0
  set ::format_endpos  0
  set ::format_matches $matches

  # Parse the string
  if {[catch { format_parse } rc] || ($rc != 0)} {
    puts "ERROR: $::format_errmsg"
    puts -nonewline "line: "
    puts [string map {\n {}} $str]
    puts "      $::format_errstr"
    return ""
  }

  return $::format_value

}


######
# Begin autogenerated taccle (version 1.1) routines.
# Although taccle itself is protected by the GNU Public License (GPL)
# all user-supplied functions are protected by their respective
# author's license.  See http://mini.net/tcl/taccle for other details.
######

proc SNIP_ABORT {} {
    return -code return 1
}

proc SNIP_ACCEPT {} {
    return -code return 0
}

proc snip_clearin {} {
    upvar snip_token t
    set t ""
}

proc snip_error {s} {
    puts stderr $s
}

proc snip_setupvalues {stack pointer numsyms} {
    upvar 1 1 y
    set y {}
    for {set i 1} {$i <= $numsyms} {incr i} {
        upvar 1 $i y
        set y [lindex $stack $pointer]
        incr pointer
    }
}

proc snip_unsetupvalues {numsyms} {
    for {set i 1} {$i <= $numsyms} {incr i} {
        upvar 1 $i y
        unset y
    }
}

array set ::snip_table {
  122:266,target 95
  96:264,target 97
  86:260 reduce
  66:258,target 60
  4:/,target 1
  137:261,target 94
  8:? reduce
  77:/,target 26
  62:` reduce
  56:257 reduce
  6:259,target 23
  17:266,target 9
  63:266,target 49
  56:258 reduce
  123::,target 130
  56:260 reduce
  48:/ shift
  36:?,target 56
  119:257,target 83
  86:266 reduce
  46:/,target 58
  112:269 shift
  86:267 reduce
  3:267,target 73
  65:`,target 52
  30:268,target 6
  29:268,target 38
  26:257 reduce
  86:269 reduce
  15:257,target 5
  26:258 reduce
  116:265,target 79
  91:263,target 88
  61:257,target 47
  15:/,target 1
  26:260 reduce
  132:260,target 14
  91:/ reduce
  56:266 reduce
  0:275,target 17
  56:267 reduce
  34:`,target 58
  42:271,target 77
  1:258,target 70
  56:270 reduce
  27:260,target 4
  128:267,target 19
  73:260,target 25
  56:271 reduce
  112:279 goto
  26:266 reduce
  26:267 reduce
  26:268 reduce
  70:267,target 99
  69:267,target 84
  33:0,target 62
  26:269 reduce
  26:270 reduce
  26:271 reduce
  91:: reduce
  34::,target 58
  9:268,target 68
  36:270,target 56
  36:269,target 56
  82:269,target 39
  22:258,target 12
  97:264,target 97
  67:258,target 53
  34:` reduce
  138:261,target 97
  132:/,target 14
  134:285,target 119
  7:260,target 66
  18:266,target 8
  21:/ shift
  64:266,target 54
  105:263,target 96
  101:/,target 112
  121:257,target 94
  4:267,target 9
  15:274,target 26
  117:257 reduce
  107:/ reduce
  31:268,target 59
  117:258 reduce
  102:271,target 89
  63:/ reduce
  8:` reduce
  16:257,target 10
  117:265,target 80
  117:260 reduce
  92:257 shift
  62:257,target 48
  133:260,target 18
  117:261 reduce
  117:262 reduce
  1:/,target 70
  117:263 reduce
  2:258,target 74
  117:264 reduce
  74:/,target 21
  21:: shift
  28:260,target 3
  130:267,target 99
  117:265 reduce
  74:260,target 21
  62:257 reduce
  117:266 reduce
  62:258 reduce
  119::,target 83
  117:267 reduce
  70:284,target 102
  62:260 reduce
  33:?,target 62
  43:/,target 45
  25:267,target 16
  117:270 reduce
  107:: reduce
  71:267,target 28
  21:? shift
  117:271 reduce
  62:`,target 48
  32:257 reduce
  127:258,target 84
  32:258 reduce
  32:260 reduce
  12:/,target 71
  62:266 reduce
  37:270,target 57
  37:269,target 57
  83:269,target 40
  62:267 reduce
  31:`,target 59
  23:258,target 20
  98:264,target 86
  68:258,target 73
  93::,target 85
  62:269 reduce
  135:285,target 103
  79:277,target 44
  32:266 reduce
  8:260,target 67
  19:266,target 36
  20:266,target 11
  65:266,target 52
  48:` shift
  32:267 reduce
  106:263,target 91
  32:268 reduce
  122:257,target 95
  32:270 reduce
  32:269 reduce
  30:0,target 6
  29:0,target 2
  46:280,target 66
  35:/ reduce
  32:271 reduce
  5:267,target 69
  35:0 reduce
  32:268,target 63
  103:271,target 90
  31::,target 59
  17:257,target 9
  118:265,target 82
  93:263,target 85
  63:257,target 49
  134:260,target 115
  122:/ reduce
  130:284,target 102
  128:/,target 19
  77:/ reduce
  3:258,target 73
  90:271,target 17
  30:260,target 6
  29:260,target 35
  101:262,target 95
  75:260,target 22
  9:/ reduce
  0:266,target 8
  9:0 reduce
  35:: reduce
  26:267,target 5
  72:267,target 24
  113:264,target 81
  128:258,target 19
  97:257 shift
  122:: reduce
  97:258 shift
  38:270,target 64
  38:269,target 64
  35:? reduce
  97:260 shift
  84:269,target 41
  125:266,target 15
  99:264,target 87
  97:261 shift
  70:258,target 92
  69:258,target 60
  97:262 shift
  71:/,target 28
  97:263 shift
  67:257 reduce
  9:: reduce
  21:` shift
  97:264 shift
  90:`,target 17
  67:258 reduce
  9:260,target 68
  21:266,target 36
  116::,target 79
  77:? reduce
  67:260 reduce
  66:266,target 83
  30:?,target 6
  29:?,target 33
  107:263,target 96
  97:266 shift
  40:/,target 60
  39:/,target 65
  97:267 shift
  58:`,target 51
  37:257 reduce
  9:? reduce
  97:270 shift
  63:` reduce
  37:258 reduce
  33:268,target 62
  37:260 reduce
  18:257,target 8
  119:265,target 83
  94:263,target 96
  67:266 reduce
  64:257,target 54
  135:260,target 93
  67:267 reduce
  50:/ reduce
  49:/ reduce
  27:`,target 4
  90::,target 17
  67:269 reduce
  45:271,target 56
  91:271,target 88
  31:260,target 59
  132:267,target 14
  102:262,target 89
  76:260,target 23
  37:266 reduce
  136:/ reduce
  37:267 reduce
  37:268 reduce
  1:266,target 70
  37:270 reduce
  37:269 reduce
  26:0,target 5
  27:267,target 4
  73:267,target 25
  37:271 reduce
  97:283 goto
  130:258,target 92
  97:284 goto
  27::,target 4
  97:285 goto
  40:270,target 60
  40:269,target 60
  39:270,target 65
  39:269,target 65
  85:270,target 13
  85:269,target 13
  25:258,target 16
  125:/,target 15
  71:258,target 28
  136:: reduce
  50:? reduce
  49:? reduce
  137:285,target 119
  22:266,target 12
  67:266,target 53
  108:263,target 96
  35:` reduce
  128:257 reduce
  48:280,target 69
  7:267,target 66
  128:258 reduce
  34:268,target 58
  128:260 reduce
  98:/,target 86
  19:257,target 34
  20:257,target 11
  22:/ reduce
  121:265,target 94
  95:263,target 96
  65:257,target 52
  22:0 reduce
  136:260,target 96
  15:282,target 30
  57:?,target 71
  67:/,target 53
  5:258,target 69
  108:/ reduce
  73:257 reduce
  32:260,target 63
  133:267,target 18
  128:266 reduce
  103:262,target 90
  86:`,target 46
  77:260,target 26
  73:258 reduce
  64:/ reduce
  9:` reduce
  128:267 reduce
  113::,target 81
  73:260 reduce
  26:?,target 5
  128:268 reduce
  36:/,target 56
  2:266,target 74
  128:270 reduce
  128:269 reduce
  28:267,target 3
  128:271 reduce
  74:267,target 21
  115:264,target 78
  89:262,target 95
  22:: reduce
  85:0,target 13
  73:266 reduce
  73:267 reduce
  41:270,target 61
  41:269,target 61
  0:257,target 5
  86:269,target 46
  13:257 reduce
  26:258,target 5
  127:266,target 84
  108:: reduce
  73:270 reduce
  72:258,target 24
  13:258 reduce
  22:? reduce
  73:271 reduce
  13:260 reduce
  23:266,target 20
  68:266,target 75
  110:263,target 96
  109:263,target 96
  2:257 reduce
  23:0,target 20
  125:257,target 15
  2:258 reduce
  2:260 reduce
  8:267,target 67
  13:266 reduce
  35:268,target 55
  13:267 reduce
  106:271,target 91
  13:268 reduce
  21:257,target 34
  122:265,target 95
  96:263,target 96
  66:257,target 81
  13:269 reduce
  13:270 reduce
  137:260,target 115
  13:271 reduce
  122:/,target 95
  47:271,target 56
  36:/ reduce
  2:266 reduce
  93:271,target 85
  36:0 reduce
  33:260,target 62
  2:267 reduce
  134:267,target 117
  78:260,target 27
  2:268 reduce
  2:270 reduce
  2:269 reduce
  3:266,target 73
  2:271 reduce
  30:267,target 6
  29:267,target 37
  134:257 shift
  101:270,target 100
  78:/ reduce
  75:267,target 22
  134:258 shift
  116:264,target 79
  91:262,target 88
  85:?,target 13
  134:260 shift
  132:258,target 14
  0:274,target 16
  134:261 shift
  134:262 shift
  42:270,target 77
  42:269,target 77
  1:257,target 70
  134:263 shift
  87:269,target 44
  54:?,target 31
  36:: reduce
  27:258,target 4
  134:264 shift
  128:266,target 19
  73:258,target 25
  64:/,target 54
  9:`,target 68
  78:257 reduce
  134:266 shift
  83:`,target 40
  78:258 reduce
  134:267 shift
  78:260 reduce
  23:?,target 20
  123:: shift
  70:266,target 98
  69:266,target 83
  36:? reduce
  33:/,target 62
  134:270 shift
  134:271 shift
  48:257 shift
  48:258 shift
  8:0,target 67
  9:267,target 68
  66:274,target 86
  48:260 shift
  36:268,target 56
  22:` reduce
  107:271,target 92
  78:266 reduce
  22:257,target 12
  97:263,target 96
  78:? reduce
  78:267 reduce
  67:257,target 53
  9::,target 68
  21:`,target 42
  138:260,target 97
  18:257 reduce
  78:270 reduce
  18:258 reduce
  134:284,target 118
  78:271 reduce
  7:258,target 66
  18:260 reduce
  64:` reduce
  48:266 shift
  34:260,target 58
  135:267,target 99
  105:262,target 95
  80:260,target 43
  79:259,target 23
  48:267 shift
  51:/ reduce
  45:278,target 57
  7:257 reduce
  4:266,target 8
  19:0,target 7
  20:0,target 11
  134:284 goto
  31:267,target 59
  7:258 reduce
  134:285 goto
  102:270,target 89
  76:267,target 23
  7:260 reduce
  18:266 reduce
  117:264,target 80
  18:267 reduce
  21::,target 32
  133:258,target 18
  48:274 goto
  18:268 reduce
  18:269 reduce
  18:270 reduce
  93:/ reduce
  48:276 goto
  2:257,target 74
  18:271 reduce
  118:/,target 82
  88:269,target 45
  28:258,target 3
  130:266,target 98
  74:258,target 21
  7:266 reduce
  48:280 goto
  7:267 reduce
  70:283,target 101
  7:268 reduce
  48:282 goto
  7:269 reduce
  7:270 reduce
  25:266,target 16
  71:266,target 28
  7:271 reduce
  8:?,target 67
  127:257,target 84
  51:? reduce
  37:268,target 57
  108:271,target 93
  93:: reduce
  23:257,target 20
  98:263,target 86
  68:257,target 72
  110:257 shift
  109:257 shift
  51:?,target 33
  110:258 shift
  109:258 shift
  61:/,target 47
  36:` reduce
  135:284,target 102
  110:260 shift
  109:260 shift
  84:257 reduce
  50:271,target 32
  49:271,target 36
  8:258,target 67
  110:261 shift
  109:261 shift
  84:258 reduce
  80:`,target 43
  35:260,target 55
  136:267,target 96
  110:262 shift
  109:262 shift
  106::,target 91
  106:262,target 91
  84:260 reduce
  81:260,target 42
  19:?,target 33
  20:?,target 11
  23:/ reduce
  110:263 shift
  109:263 shift
  30:/,target 6
  29:/,target 31
  23:0 reduce
  110:264 shift
  109:264 shift
  5:266,target 69
  110:265 shift
  109:265 shift
  54:257 reduce
  48:`,target 4
  32:267,target 63
  110:266 shift
  109:266 shift
  103:270,target 90
  77:267,target 26
  54:258 reduce
  5:0,target 69
  118:264,target 82
  110:267 shift
  109:267 shift
  93:262,target 85
  54:260 reduce
  134:258,target 114
  84:266 reduce
  65:/ reduce
  110:270 shift
  109:270 shift
  84:267 reduce
  17:`,target 9
  130:283,target 134
  3:257,target 73
  24:257 shift
  90:270,target 17
  90:269,target 17
  89:270,target 100
  84:269 reduce
  30:258,target 6
  29:258,target 2
  101:261,target 94
  75:258,target 22
  24:259 shift
  54:266 reduce
  23:: reduce
  54:267 reduce
  112:279,target 126
  26:266,target 5
  72:266,target 24
  54:270 reduce
  16:0,target 10
  113:263,target 81
  54:271 reduce
  128:257,target 19
  23:? reduce
  17::,target 9
  38:268,target 64
  24:257,target 43
  110:284 goto
  109:284 goto
  99:263,target 87
  70:257,target 91
  69:257,target 81
  115:/,target 78
  110:285 goto
  109:285 goto
  51:271,target 33
  9:258,target 68
  36:260,target 56
  137:267,target 117
  107:262,target 95
  82:260,target 39
  24:277 goto
  47:278,target 68
  5:?,target 69
  33:267,target 62
  78:?,target 27
  78:267,target 27
  37:/ reduce
  133:0,target 18
  119:264,target 83
  94:262,target 95
  88:/,target 45
  37:0 reduce
  135:258,target 92
  134::,target 135
  115:257 reduce
  47:?,target 49
  45:270,target 55
  4:257,target 5
  115:258 reduce
  91:270,target 88
  57:/,target 70
  31:258,target 59
  3:`,target 73
  132:266,target 14
  115:260 reduce
  102:261,target 89
  90:257 reduce
  89:257 shift
  80:/ reduce
  76:258,target 23
  0:282,target 20
  115:261 reduce
  90:258 reduce
  89:258 shift
  115:262 reduce
  103::,target 90
  90:260 reduce
  89:260 shift
  16:?,target 10
  115:263 reduce
  89:261 shift
  26:/,target 5
  27:266,target 4
  115:264 reduce
  89:262 shift
  73:266,target 25
  115:265 reduce
  89:263 shift
  60:257 shift
  59:257 reduce
  37:: reduce
  130:257,target 91
  115:266 reduce
  89:264 shift
  59:258 reduce
  2:0,target 74
  115:267 reduce
  60:259 shift
  59:260 reduce
  90:266 reduce
  89:266 shift
  69:274,target 86
  40:268,target 60
  39:268,target 65
  115:270 reduce
  90:267 reduce
  89:267 shift
  85:268,target 13
  3::,target 73
  25:257,target 16
  115:271 reduce
  90:268 reduce
  71:257,target 28
  37:? reduce
  30:257 reduce
  29:257 shift
  90:270 reduce
  90:269 reduce
  89:270 shift
  30:258 reduce
  29:258 reduce
  90:271 reduce
  66:282,target 88
  30:260 reduce
  29:260 shift
  137:284,target 118
  59:266 reduce
  52:271,target 29
  59:267 reduce
  37:260,target 57
  23:` reduce
  138:267,target 97
  108:262,target 95
  83:260,target 40
  60:268 shift
  59:269 reduce
  13:0,target 72
  7:266,target 66
  10:/ reduce
  133:?,target 18
  34:267,target 58
  30:266 reduce
  29:266 shift
  10:0 reduce
  105:270,target 100
  80:267,target 43
  30:267 reduce
  29:267 shift
  121:264,target 94
  95:262,target 95
  65:` reduce
  30:268 reduce
  29:268 shift
  136:258,target 96
  30:270 reduce
  30:269 reduce
  29:270 shift
  29:269 shift
  15:281,target 29
  30:271 reduce
  29:271 shift
  89:283 goto
  60:277 goto
  52:/ reduce
  5:257,target 69
  89:284 goto
  32:258,target 63
  133:266,target 18
  103:261,target 90
  89:285 goto
  77:258,target 26
  138:/ reduce
  10:: reduce
  28:266,target 3
  74:266,target 21
  2:?,target 74
  115:263,target 78
  89:261,target 94
  75:?,target 22
  85:/,target 13
  41:268,target 61
  10:? reduce
  26:257,target 5
  127:265,target 84
  121:257 reduce
  72:257,target 24
  121:258 reduce
  54:/,target 31
  0:`,target 4
  121:260 reduce
  95:257 shift
  121:261 reduce
  95:258 shift
  53:271,target 30
  138:: reduce
  121:262 reduce
  98:271,target 86
  95:260 shift
  52:? reduce
  38:260,target 64
  13:?,target 72
  121:263 reduce
  110:262,target 95
  109:262,target 95
  95:261 shift
  84:260,target 41
  23:/,target 20
  121:264 reduce
  95:262 shift
  121:265 reduce
  95:263 shift
  65:257 reduce
  42:`,target 77
  8:266,target 67
  121:266 reduce
  95:264 shift
  65:258 reduce
  37:` reduce
  35:267,target 55
  121:267 reduce
  106:270,target 91
  81:267,target 42
  65:260 reduce
  122:264,target 95
  96:262,target 95
  95:266 shift
  137:258,target 114
  121:270 reduce
  95:267 shift
  0::,target 2
  11:`,target 76
  121:271 reduce
  35:257 reduce
  95:270 shift
  47:270,target 55
  35:258 reduce
  6:257,target 22
  93:270,target 85
  80:` reduce
  41:0,target 61
  35:260 reduce
  33:258,target 62
  134:266,target 116
  78:258,target 27
  65:266 reduce
  65:267 reduce
  66:/ shift
  42::,target 77
  65:269 reduce
  30:266,target 6
  29:266,target 36
  10:0,target 75
  75:266,target 22
  116:263,target 79
  91:261,target 88
  35:266 reduce
  132:257,target 14
  35:267 reduce
  0:273,target 15
  11::,target 76
  35:268 reduce
  42:268,target 77
  35:270 reduce
  35:269 reduce
  113:271,target 81
  35:271 reduce
  27:257,target 4
  108:/,target 93
  95:283 goto
  73:257,target 25
  95:284 goto
  95:285 goto
  54:271,target 31
  99:271,target 87
  40:260,target 60
  39:260,target 65
  85:260,target 13
  10:` reduce
  8:/,target 67
  9:266,target 68
  72:?,target 24
  36:267,target 56
  107:270,target 100
  82:267,target 39
  82:/,target 39
  97:262,target 95
  138:258,target 97
  127::,target 84
  41:?,target 61
  51:/,target 33
  7:257,target 66
  126:260 shift
  94:270,target 100
  34:258,target 58
  135:266,target 98
  105:261,target 94
  80:258,target 43
  69:`,target 4
  38:/ reduce
  38:0 reduce
  10:?,target 75
  101:285,target 119
  19:/,target 31
  20:/,target 11
  31:266,target 59
  76:266,target 23
  71:257 reduce
  38:`,target 64
  125:/ reduce
  117:263,target 80
  71:258 reduce
  133:257,target 18
  125:0 reduce
  81:/ reduce
  71:260 reduce
  126:269 shift
  41:257 reduce
  28:257,target 3
  74:257,target 21
  41:258 reduce
  41:260 reduce
  38:: reduce
  37:0,target 57
  71:266 reduce
  69:282,target 88
  10:271,target 75
  71:267 reduce
  55:271,target 34
  41:260,target 61
  38::,target 64
  11:257 reduce
  86:260,target 46
  71:270 reduce
  11:258 reduce
  125:: reduce
  71:271 reduce
  38:? reduce
  11:260 reduce
  41:266 reduce
  136:/,target 96
  41:267 reduce
  37:267,target 57
  108:270,target 100
  83:267,target 40
  41:268 reduce
  98:262,target 86
  41:270 reduce
  41:269 reduce
  0:257 shift
  125:? reduce
  41:271 reduce
  0:258 shift
  105:/,target 120
  0:260 shift
  11:266 reduce
  135:283,target 137
  50:270,target 32
  49:270,target 36
  8:257,target 67
  11:/ reduce
  11:267 reduce
  95:270,target 100
  35:258,target 55
  11:0 reduce
  11:268 reduce
  136:266,target 96
  106:261,target 91
  81:258,target 42
  11:269 reduce
  11:270 reduce
  66:` shift
  11:271 reduce
  32:266,target 63
  0:266 shift
  77:266,target 26
  53:/ reduce
  5:/,target 69
  0:267 shift
  118:263,target 82
  93:261,target 85
  68:?,target 71
  0:268 shift
  134:257,target 113
  78:/,target 27
  0:270 shift
  0:269 shift
  0:271 shift
  0:272 goto
  132:257 reduce
  115:271,target 78
  90:268,target 17
  37:?,target 57
  30:257,target 6
  29:257,target 34
  0:273 goto
  11:: reduce
  132:258 reduce
  101:260,target 115
  75:257,target 22
  0:274 goto
  132:260 reduce
  0:275 goto
  66:`,target 4
  0:276 goto
  11:271,target 76
  56:271,target 35
  102:257 reduce
  42:260,target 77
  11:? reduce
  16:/,target 10
  113:262,target 81
  102:258 reduce
  87:260,target 44
  102:260 reduce
  76:257 reduce
  35:`,target 55
  0:281 goto
  132:266 reduce
  102:261 reduce
  76:258 reduce
  0:282 goto
  132:267 reduce
  102:262 reduce
  76:260 reduce
  38:267,target 64
  132:268 reduce
  110:270,target 100
  109:270,target 100
  102:263 reduce
  84:267,target 41
  132:270 reduce
  132:269 reduce
  102:264 reduce
  99:262,target 87
  53:? reduce
  132:271 reduce
  102:265 reduce
  46:257 shift
  102:266 reduce
  46:258 shift
  102:267 reduce
  51:270,target 33
  46:260 shift
  34:0,target 58
  9:257,target 68
  96:270,target 100
  76:266 reduce
  38:` reduce
  36:258,target 56
  137:266,target 116
  107:261,target 94
  102:270 reduce
  82:258,target 39
  76:267 reduce
  102:271 reduce
  35::,target 55
  16:257 reduce
  76:270 reduce
  16:258 reduce
  25:/ reduce
  76:271 reduce
  33:266,target 62
  16:260 reduce
  25:0 reduce
  125:` reduce
  78:266,target 27
  46:266 shift
  133:/,target 18
  119:263,target 83
  94:261,target 94
  81:` reduce
  46:267 shift
  135:257,target 91
  89:285,target 103
  5:257 reduce
  67:/ reduce
  5:258 reduce
  116:271,target 79
  102:/,target 89
  31:257,target 59
  5:260 reduce
  16:266 reduce
  102:260,target 89
  76:257,target 23
  0:281,target 19
  16:267 reduce
  46:274 goto
  0:/ shift
  16:268 reduce
  12:271,target 71
  16:269 reduce
  16:270 reduce
  57:271,target 78
  46:276 goto
  16:271 reduce
  25:: reduce
  88:260,target 45
  5:266 reduce
  46:280 goto
  5:267 reduce
  2:/,target 74
  5:268 reduce
  75:/,target 22
  46:282 goto
  40:267,target 60
  39:267,target 65
  5:270 reduce
  5:269 reduce
  25:? reduce
  85:267,target 13
  5:271 reduce
  137:257 shift
  121::,target 94
  34:?,target 58
  137:258 shift
  44:/,target 47
  0:: shift
  11:` reduce
  137:260 shift
  52:270,target 29
  137:261 shift
  97:270,target 100
  63:`,target 49
  37:258,target 57
  138:266,target 97
  137:262 shift
  108:261,target 94
  83:258,target 40
  137:263 shift
  107:257 shift
  13:/,target 72
  137:264 shift
  107:258 shift
  0:? shift
  120:279,target 129
  107:260 shift
  82:257 reduce
  34:266,target 58
  32:`,target 63
  137:266 shift
  107:261 shift
  82:258 reduce
  80:266,target 43
  137:267 shift
  121:263,target 94
  107:262 shift
  95:261,target 94
  82:260 reduce
  136:257,target 96
  107:263 shift
  40:/ reduce
  39:/ reduce
  137:270 shift
  107:264 shift
  40:0 reduce
  39:0 reduce
  137:271 shift
  107:265 reduce
  52:257 reduce
  117:271,target 80
  107:266 shift
  52:258 reduce
  32:257,target 63
  107:267 shift
  103:260,target 90
  77:257,target 26
  52:260 reduce
  31:0,target 59
  82:266 reduce
  107:270 shift
  82:267 reduce
  82:/ reduce
  13:271,target 72
  107:271 reduce
  32::,target 63
  22:257 reduce
  82:269 reduce
  22:258 reduce
  115:262,target 78
  90:260,target 17
  89:260,target 93
  22:260 reduce
  52:266 reduce
  52:267 reduce
  40:: reduce
  39:: reduce
  41:267,target 61
  112:269,target 125
  86:267,target 46
  52:270 reduce
  137:284 goto
  127:264,target 84
  52:271 reduce
  137:285 goto
  22:266 reduce
  40:? reduce
  39:? reduce
  22:267 reduce
  53:270,target 30
  22:268 reduce
  98:270,target 86
  38:258,target 64
  22:269 reduce
  22:270 reduce
  110:261,target 94
  109:261,target 94
  107:284 goto
  84:258,target 41
  22:271 reduce
  107:285 goto
  25:` reduce
  105:285,target 119
  35:266,target 55
  81:266,target 42
  12:/ reduce
  122:263,target 95
  96:261,target 94
  72:/,target 24
  12:0 reduce
  137:257,target 113
  67:` reduce
  117::,target 80
  31:?,target 59
  118:271,target 82
  41:/,target 61
  33:257,target 62
  78:257,target 27
  54:/ reduce
  0:` shift
  59:`,target 50
  113:257 reduce
  10:/,target 75
  113:258 reduce
  101:267,target 117
  90:0,target 17
  45:260,target 52
  116:262,target 79
  113:260 reduce
  91:260,target 88
  87:257 reduce
  12:: reduce
  28:`,target 3
  113:261 reduce
  87:258 reduce
  0:272,target 14
  113:262 reduce
  91::,target 88
  87:260 reduce
  113:263 reduce
  42:267,target 77
  113:270,target 81
  113:264 reduce
  87:267,target 44
  113:265 reduce
  57:257 shift
  12:? reduce
  113:266 reduce
  57:258 shift
  113:267 reduce
  57:260 shift
  27:0,target 4
  87:266 reduce
  54:270,target 31
  113:270 reduce
  99:270,target 87
  87:267 reduce
  70:264,target 97
  40:258,target 60
  39:258,target 65
  113:271 reduce
  85:258,target 13
  27:257 reduce
  28::,target 3
  87:269 reduce
  54:? reduce
  27:258 reduce
  27:260 reduce
  57:266 shift
  36:266,target 56
  82:266,target 39
  57:267 shift
  97:261,target 94
  40:` reduce
  39:` reduce
  138:257,target 97
  57:270 shift
  57:271 shift
  26:/ reduce
  27:266 reduce
  119:271,target 83
  34:257,target 58
  26:0 reduce
  27:267 reduce
  105:260,target 115
  80:257,target 43
  79:257,target 104
  27:268 reduce
  82:` reduce
  27:269 reduce
  27:270 reduce
  101:284,target 118
  90:?,target 17
  15:271,target 13
  27:271 reduce
  113:/ reduce
  99:/,target 87
  102:267,target 89
  68:/ shift
  46:260,target 61
  117:262,target 80
  68:/,target 89
  1:/ reduce
  1:0 reduce
  88:267,target 45
  87:`,target 44
  26:: reduce
  130:264,target 97
  27:?,target 4
  37:/,target 57
  10:269,target 75
  10:270,target 75
  55:270,target 34
  113:: reduce
  41:258,target 61
  26:? reduce
  118:257 reduce
  86:258,target 46
  118:258 reduce
  118:260 reduce
  107:285,target 119
  93:257 reduce
  25:`,target 16
  118:261 reduce
  93:258 reduce
  37:266,target 57
  1:: reduce
  12:` reduce
  118:262 reduce
  93:260 reduce
  83:266,target 40
  118:263 reduce
  98:261,target 86
  93:261 reduce
  68:? shift
  118:264 reduce
  93:262 reduce
  118:265 reduce
  94:285,target 103
  93:263 reduce
  63:257 reduce
  118:266 reduce
  93:264 reduce
  63:258 reduce
  1:? reduce
  121:271,target 94
  118:267 reduce
  93:265 reduce
  63:260 reduce
  35:257,target 55
  136:265,target 96
  106:260,target 91
  93:266 reduce
  81:257,target 42
  4:281,target 21
  118:270 reduce
  93:267 reduce
  118:271 reduce
  46:276,target 65
  41:/ reduce
  33:257 reduce
  16:271,target 10
  25::,target 16
  93:270 reduce
  41:0 reduce
  33:258 reduce
  103:267,target 90
  93:271 reduce
  47:260,target 52
  33:260 reduce
  118:262,target 82
  93:260,target 85
  63:266 reduce
  63:267 reduce
  127:/ reduce
  83:/ reduce
  63:269 reduce
  115:270,target 78
  90:267,target 17
  89:267,target 99
  101:258,target 114
  33:266 reduce
  33:267 reduce
  33:268 reduce
  11:269,target 76
  11:270,target 76
  56:270,target 35
  41:: reduce
  33:270 reduce
  33:269 reduce
  42:258,target 77
  33:271 reduce
  113:261,target 81
  87:258,target 44
  108:285,target 119
  127:: reduce
  55:?,target 34
  41:? reduce
  38:266,target 64
  84:266,target 41
  65:/,target 52
  99:261,target 87
  84:`,target 41
  95:285,target 103
  26:` reduce
  34:/,target 58
  122:271,target 95
  36:257,target 56
  107:260,target 115
  82:257,target 39
  13:/ reduce
  9:0,target 68
  13:0 reduce
  17:271,target 9
  124:260 reduce
  98:257 reduce
  48:260,target 61
  22:`,target 12
  119:262,target 83
  98:258 reduce
  94:260,target 93
  98:260 reduce
  55:/ reduce
  1:` reduce
  98:261 reduce
  89:284,target 102
  98:262 reduce
  45:267,target 54
  116:270,target 79
  98:263 reduce
  91:267,target 88
  68:257 shift
  102:258,target 89
  98:264 reduce
  68:258 shift
  98:265 reduce
  68:260 shift
  13:: reduce
  98:266 reduce
  12:269,target 71
  12:270,target 71
  124:269 reduce
  98:267 reduce
  57:270,target 77
  38:257 reduce
  22::,target 12
  98:270 reduce
  88:258,target 45
  38:258 reduce
  98:271 reduce
  38:260 reduce
  13:? reduce
  110:285,target 119
  109:285,target 119
  68:266 shift
  119:/,target 83
  68:267 shift
  40:266,target 60
  39:266,target 65
  85:266,target 13
  68:270 shift
  100:? shift
  68:271 shift
  96:285,target 103
  55:? reduce
  38:266 reduce
  38:267 reduce
  38:268 reduce
  37:257,target 57
  9:?,target 68
  138:265,target 97
  108:260,target 115
  83:257,target 40
  38:270 reduce
  38:269 reduce
  41:` reduce
  38:271 reduce
  93:/,target 85
  48:276,target 65
  18:271,target 8
  105:267,target 117
  50:260,target 32
  49:260,target 36
  27:/ reduce
  138::,target 97
  121:262,target 94
  95:260,target 93
  52:?,target 29
  27:0 reduce
  62:/,target 48
  7:`,target 66
  83:` reduce
  81:`,target 42
  46:267,target 63
  117:270,target 80
  107::,target 92
  21:?,target 33
  103:258,target 90
  69:/ shift
  31:/,target 59
  13:269,target 72
  13:270,target 72
  58:269,target 51
  2:/ reduce
  130:257 shift
  2:0 reduce
  130:258 shift
  115:261,target 78
  90:258,target 17
  89:258,target 92
  27:: reduce
  130:260 shift
  129:260 shift
  7::,target 66
  18:`,target 8
  130:261 shift
  130:262 shift
  41:266,target 61
  130:263 shift
  86:266,target 46
  130:264 shift
  127:263,target 84
  27:? reduce
  74:257 reduce
  130:266 shift
  97:285,target 103
  74:258 reduce
  130:267 shift
  74:260 reduce
  17:0,target 9
  38:257,target 64
  2:: reduce
  13:` reduce
  130:270 shift
  129:269 shift
  110:260,target 115
  109:260,target 115
  84:257,target 41
  18::,target 8
  105:284,target 118
  19:271,target 41
  20:271,target 11
  106:267,target 91
  74:266 reduce
  51:260,target 33
  2:? reduce
  122:262,target 95
  116:/,target 79
  96:260,target 93
  74:267 reduce
  74:270 reduce
  74:271 reduce
  47:267,target 54
  42:/ reduce
  118:270,target 82
  93:267,target 85
  42:0 reduce
  134:264,target 97
  130:283 goto
  3:257 reduce
  130:284 goto
  128:/ reduce
  59:269,target 50
  3:258 reduce
  130:285 goto
  128:0 reduce
  101:266,target 116
  90:/,target 17
  84:/ reduce
  45:258,target 51
  3:260 reduce
  116:261,target 79
  91:258,target 88
  0:271,target 13
  58:/,target 51
  42:266,target 77
  87:266,target 44
  42:: reduce
  3:266 reduce
  104::,target 46
  3:267 reduce
  17:?,target 9
  3:268 reduce
  27:/,target 4
  3:270 reduce
  3:269 reduce
  128:: reduce
  125:271,target 15
  70:263,target 96
  46:`,target 4
  42:? reduce
  40:257,target 60
  39:257,target 65
  3:271 reduce
  85:257,target 13
  3:0,target 73
  135:257 shift
  135:258 shift
  21:271,target 41
  135:260 shift
  4::,target 2
  15:`,target 4
  27:` reduce
  135:261 shift
  128:? reduce
  107:267,target 117
  52:260,target 29
  135:262 shift
  97:260,target 93
  135:263 shift
  105:257 shift
  135:264 shift
  105:258 shift
  14:0 accept
  105:260 shift
  80:257 reduce
  79:257 shift
  48:267,target 63
  135:266 shift
  120:269,target 128
  119:270,target 83
  105:261 shift
  94:267,target 99
  80:258 reduce
  69:` shift
  135:264,target 97
  135:267 shift
  105:262 shift
  105:258,target 114
  80:260 reduce
  79:259 shift
  14:0,target 0
  105:263 shift
  101:/ shift
  135:270 shift
  105:264 shift
  56:/ reduce
  2:` reduce
  15:270,target 12
  15:269,target 11
  61:269,target 47
  50:257 reduce
  49:257 reduce
  15::,target 2
  105:266 shift
  102:266,target 89
  50:258 reduce
  49:258 reduce
  46:258,target 60
  117:261,target 80
  105:267 shift
  50:260 reduce
  49:260 reduce
  80:266 reduce
  1:271,target 70
  113:/,target 81
  105:270 shift
  80:267 reduce
  98:/ reduce
  19:257 shift
  20:257 reduce
  132:`,target 14
  88:266,target 45
  80:269 reduce
  19:258 reduce
  20:258 reduce
  130:263,target 96
  19:260 shift
  20:260 reduce
  50:266 reduce
  49:266 reduce
  50:267 reduce
  49:267 reduce
  10:268,target 75
  3:?,target 73
  135:283 goto
  50:270 reduce
  49:270 reduce
  41:257,target 61
  8:257 reduce
  135:284 goto
  112:260,target 124
  86:257,target 46
  76:?,target 23
  50:271 reduce
  49:271 reduce
  8:258 reduce
  135:285 goto
  86:/,target 46
  79:277 goto
  8:260 reduce
  19:266 shift
  20:266 reduce
  107:284,target 118
  19:267 shift
  20:267 reduce
  22:271,target 12
  56:? reduce
  19:268 shift
  20:268 reduce
  132::,target 14
  108:267,target 117
  98:: reduce
  53:260,target 30
  45:?,target 49
  19:269 shift
  19:270 shift
  20:269 reduce
  20:270 reduce
  105:284 goto
  98:260,target 86
  55:/,target 34
  1:`,target 70
  19:271 shift
  20:271 reduce
  105:285 goto
  94:284,target 102
  42:` reduce
  8:266 reduce
  50:267,target 32
  49:267,target 36
  8:267 reduce
  121:270,target 94
  95:267,target 99
  8:268 reduce
  136:264,target 96
  106:258,target 91
  8:269 reduce
  8:270 reduce
  28:/ reduce
  8:271 reduce
  28:0 reduce
  128:` reduce
  16:269,target 10
  16:270,target 10
  84:` reduce
  62:269,target 48
  103:266,target 90
  47:258,target 51
  118:261,target 82
  115:/ reduce
  93:258,target 85
  1::,target 70
  12:`,target 71
  71:/ reduce
  2:271,target 74
  111:257 shift
  42:0,target 77
  90:266,target 17
  89:266,target 98
  3:/ reduce
  101:257,target 113
  85:257 reduce
  3:0 reduce
  85:258 reduce
  43::,target 46
  28:: reduce
  85:260 reduce
  11:0,target 76
  11:268,target 76
  127:271,target 84
  42:257,target 77
  113:260,target 81
  87:257,target 44
  55:257 reduce
  12::,target 71
  115:: reduce
  55:258 reduce
  28:? reduce
  108:284,target 118
  55:260 reduce
  23:271,target 20
  100:?,target 111
  85:266 reduce
  68:271,target 78
  110:267,target 117
  109:267,target 117
  85:267 reduce
  54:260,target 31
  99:260,target 87
  85:268 reduce
  3:: reduce
  25:257 reduce
  128:`,target 19
  85:270 reduce
  85:269 reduce
  25:258 reduce
  95:284,target 102
  85:271 reduce
  71:? reduce
  25:260 reduce
  55:266 reduce
  51:267,target 33
  122:270,target 95
  96:267,target 99
  55:267 reduce
  137:264,target 97
  107:258,target 114
  3:? reduce
  0:?,target 3
  55:270 reduce
  9:/,target 68
  73:?,target 25
  55:271 reduce
  17:269,target 9
  17:270,target 9
  83:/,target 40
  63:269,target 49
  25:266 reduce
  48:258,target 60
  43:/ shift
  25:267 reduce
  119:261,target 83
  94:258,target 92
  25:268 reduce
  128::,target 19
  42:?,target 77
  3:271,target 73
  25:269 reduce
  25:270 reduce
  89:283,target 105
  60:277,target 25
  52:/,target 29
  25:271 reduce
  45:266,target 53
  91:266,target 88
  102:257,target 89
  85:/ reduce
  11:?,target 76
  85:0 reduce
  21:/,target 31
  12:268,target 71
  40:`,target 60
  39:`,target 65
  128:271,target 19
  88:257,target 45
  43:: shift
  110:284,target 118
  109:284,target 118
  10:260,target 75
  55:260,target 34
  116:257 reduce
  38:0,target 64
  116:258 reduce
  85:: reduce
  116:260 reduce
  96:284,target 102
  91:257 reduce
  116:261 reduce
  91:258 reduce
  52:267,target 29
  40::,target 60
  39::,target 65
  116:262 reduce
  97:267,target 99
  91:260 reduce
  28:` reduce
  138:264,target 97
  116:263 reduce
  108:258,target 114
  91:261 reduce
  116:264 reduce
  91:262 reduce
  85:? reduce
  116:265 reduce
  91:263 reduce
  61:257 reduce
  15:/ shift
  18:269,target 8
  18:270,target 8
  116:266 reduce
  91:264 reduce
  64:269,target 54
  61:258 reduce
  15:0 reduce
  116:267 reduce
  105:266,target 116
  91:265 reduce
  61:260 reduce
  50:258,target 32
  49:258,target 36
  121:261,target 94
  95:258,target 92
  91:266 reduce
  116:270 reduce
  106:/,target 91
  91:267 reduce
  4:271,target 13
  116:271 reduce
  102:/ reduce
  31:257 reduce
  125:`,target 15
  91:270 reduce
  57:/ shift
  46:266,target 62
  31:258 reduce
  3:` reduce
  91:271 reduce
  31:260 reduce
  103:257,target 90
  61:266 reduce
  61:267 reduce
  13:268,target 72
  61:269 reduce
  15:: shift
  99:/ reduce
  115:260,target 78
  90:257,target 17
  89:257,target 91
  80:/,target 43
  31:266 reduce
  31:267 reduce
  31:268 reduce
  25:271,target 16
  125::,target 15
  102:: reduce
  71:271,target 28
  38:?,target 64
  31:270 reduce
  31:269 reduce
  11:260,target 76
  15:? shift
  56:260,target 35
  48:/,target 58
  31:271 reduce
  127:262,target 84
  67:`,target 53
  97:284,target 102
  53:267,target 30
  17:/,target 9
  124:269,target 38
  98:267,target 86
  57:? shift
  110:258,target 114
  109:258,target 114
  99:: reduce
  36:`,target 56
  98::,target 86
  19:270,target 40
  19:269,target 39
  20:269,target 11
  20:270,target 11
  65:269,target 52
  106:266,target 91
  51:258,target 33
  122:261,target 95
  96:258,target 92
  30:/ reduce
  5:271,target 69
  29:/ shift
  122:257 reduce
  35:0,target 55
  30:0 reduce
  29:0 reduce
  122:258 reduce
  47:266,target 53
  122:260 reduce
  96:257 shift
  93:266,target 85
  85:` reduce
  134:263,target 96
  122:261 reduce
  96:258 shift
  36::,target 56
  122:262 reduce
  116:/ reduce
  96:260 shift
  122:263 reduce
  96:261 shift
  72:/ reduce
  122:264 reduce
  96:262 shift
  60:268,target 79
  122:265 reduce
  96:263 shift
  66:257 shift
  45:257,target 50
  122:266 reduce
  116:260,target 79
  96:264 shift
  91:257,target 88
  66:258 shift
  4:/ shift
  122:267 reduce
  66:260 shift
  0:270,target 12
  0:269,target 11
  96:266 shift
  30:: reduce
  29:: shift
  26:271,target 5
  122:270 reduce
  103:/,target 90
  96:267 shift
  72:271,target 24
  12:260,target 71
  122:271 reduce
  113:267,target 81
  57:260,target 74
  36:257 reduce
  96:270 shift
  36:258 reduce
  36:260 reduce
  116:: reduce
  66:266 shift
  30:? reduce
  29:? shift
  66:267 shift
  54:267,target 31
  125:270,target 15
  125:269,target 15
  99:267,target 87
  70:262,target 95
  66:269 shift
  3:/,target 73
  4:: shift
  15:` shift
  76:/,target 23
  36:266 reduce
  21:270,target 40
  21:269,target 39
  72:? reduce
  66:269,target 85
  36:267 reduce
  107:266,target 116
  66:274 goto
  52:258,target 29
  36:268 reduce
  122::,target 95
  97:258,target 92
  36:270 reduce
  36:269 reduce
  35:?,target 55
  66:276 goto
  36:271 reduce
  4:? shift
  96:283 goto
  96:284 goto
  64:`,target 54
  48:266,target 62
  96:285 goto
  94:266,target 98
  135:263,target 96
  105:257,target 113
  44:/ shift
  66:282 goto
  33:`,target 62
  15:268,target 10
  132:271,target 14
  102:265,target 89
  46:257,target 59
  117:260,target 80
  92:257,target 106
  86:/ reduce
  1:270,target 70
  1:269,target 70
  27:271,target 4
  73:271,target 25
  13:260,target 72
  127:257 reduce
  58:260,target 51
  32:0,target 63
  130:262,target 95
  127:258 reduce
  127:260 reduce
  44:: shift
  127:261 reduce
  33::,target 62
  10:267,target 75
  127:262 reduce
  55:267,target 34
  127:263 reduce
  126:269,target 132
  127:264 reduce
  127:265 reduce
  72:257 reduce
  127:266 reduce
  72:258 reduce
  22:269,target 12
  22:270,target 12
  127:267 reduce
  72:260 reduce
  67:269,target 53
  108:266,target 116
  53:258,target 30
  127:270 reduce
  98:258,target 86
  30:` reduce
  29:` reduce
  127:271 reduce
  42:257 reduce
  7:271,target 66
  94:283,target 107
  42:258 reduce
  50:266,target 32
  49:266,target 36
  42:260 reduce
  16:/ reduce
  95:266,target 98
  72:266 reduce
  16:0 reduce
  136:263,target 96
  106:257,target 91
  72:267 reduce
  12:257 reduce
  72:270 reduce
  46:274,target 64
  0:/,target 1
  12:258 reduce
  16:268,target 10
  103:/ reduce
  72:271 reduce
  12:260 reduce
  133:271,target 18
  103:265,target 90
  73:/,target 25
  58:/ reduce
  47:257,target 50
  42:266 reduce
  118:260,target 82
  93:257,target 85
  42:267 reduce
  42:268 reduce
  2:270,target 74
  2:269,target 74
  118::,target 82
  42:270 reduce
  42:269 reduce
  32:?,target 63
  1:257 reduce
  28:271,target 3
  74:271,target 21
  42:271 reduce
  42:/,target 77
  1:258 reduce
  115:267,target 78
  60:259,target 23
  59:260,target 50
  1:260 reduce
  12:266 reduce
  16:: reduce
  61:`,target 47
  12:267 reduce
  12:268 reduce
  11:/,target 76
  11:267,target 76
  12:269 reduce
  12:270 reduce
  56:267,target 35
  12:271 reduce
  127:270,target 84
  103:: reduce
  30:`,target 6
  29:`,target 2
  16:? reduce
  113:258,target 81
  1:266 reduce
  1:267 reduce
  1:268 reduce
  23:269,target 20
  23:270,target 20
  68:270,target 77
  1:270 reduce
  1:269 reduce
  110:266,target 116
  109:266,target 116
  54:258,target 31
  1:271 reduce
  99:258,target 87
  133:257 reduce
  8:271,target 67
  28:0,target 3
  133:258 reduce
  95:283,target 108
  133:260 reduce
  51:266,target 33
  96:266,target 98
  30::,target 6
  29::,target 32
  137:263,target 96
  107:257,target 113
  103:257 reduce
  103:258 reduce
  31:/ reduce
  17:268,target 9
  127:/,target 84
  103:260 reduce
  77:257 reduce
  31:0 reduce
  134:271,target 136
  133:266 reduce
  103:261 reduce
  77:258 reduce
  48:257,target 59
  133:267 reduce
  120:260,target 124
  119:260,target 83
  103:262 reduce
  94:257,target 91
  86:` reduce
  77:260 reduce
  133:268 reduce
  103:263 reduce
  3:270,target 73
  3:269,target 73
  133:270 reduce
  133:269 reduce
  117:/ reduce
  103:264 reduce
  30:271,target 6
  29:271,target 41
  133:271 reduce
  103:265 reduce
  75:271,target 22
  73:/ reduce
  47:257 shift
  15:260,target 7
  116:267,target 79
  103:266 reduce
  91:265,target 88
  61:260,target 47
  47:258 shift
  103:267 reduce
  47:260 shift
  77:266 reduce
  5:/ reduce
  103:270 reduce
  77:267 reduce
  5:0 reduce
  12:267,target 71
  103:271 reduce
  57:267,target 76
  31:: reduce
  17:257 reduce
  128:270,target 19
  128:269,target 19
  77:270 reduce
  17:258 reduce
  77:271 reduce
  17:260 reduce
  69:/,target 80
  47:266 shift
  47:267 shift
  117:: reduce
  88:`,target 45
  70:270,target 100
  69:269,target 90
  31:? reduce
  10:258,target 75
  115::,target 78
  55:258,target 34
  47:270 shift
  6:257 shift
  28:?,target 3
  47:271 shift
  38:/,target 64
  6:259 shift
  9:271,target 68
  17:266 reduce
  96:283,target 109
  5:: reduce
  16:` reduce
  17:267 reduce
  52:266,target 29
  17:268 reduce
  97:266,target 98
  73:? reduce
  17:269 reduce
  17:270 reduce
  138:263,target 97
  108:257,target 113
  17:271 reduce
  26:`,target 5
  48:274,target 64
  47:278 goto
  5:? reduce
  18:268,target 8
  58:` reduce
  50:257,target 32
  49:257,target 36
  6:268 shift
  121:260,target 94
  95:257,target 91
  4:269,target 11
  4:270,target 12
  15:276,target 28
  31:271,target 59
  138:257 reduce
  76:271,target 23
  16:260,target 10
  25:0,target 16
  138:258 reduce
  117:267,target 80
  62:260,target 48
  138:260 reduce
  138:261 reduce
  132:/ reduce
  26::,target 5
  138:262 reduce
  132:0 reduce
  87:/ reduce
  6:277 goto
  13:267,target 72
  138:263 reduce
  108:257 shift
  58:267,target 51
  138:264 reduce
  130:270,target 100
  129:269,target 133
  108:258 shift
  138:265 reduce
  115:258,target 78
  108:260 shift
  83:257 reduce
  138:266 reduce
  108:261 shift
  83:258 reduce
  138:267 reduce
  108:262 shift
  83:260 reduce
  25:269,target 16
  25:270,target 16
  108:263 shift
  71:270,target 28
  11:258,target 76
  138:270 reduce
  108:264 shift
  56:258,target 35
  138:271 reduce
  127:261,target 84
  108:265 reduce
  53:257 reduce
  108:266 shift
  53:258 reduce
  132:: reduce
  108:267 shift
  97:283,target 110
  53:260 reduce
  45:? shift
  83:266 reduce
  53:266,target 30
  108:270 shift
  98:266,target 86
  83:267 reduce
  110:257,target 113
  109:257,target 113
  108:271 reduce
  23:257 reduce
  83:269 reduce
  31:` reduce
  23:258 reduce
  132:? reduce
  56:?,target 35
  19:268,target 38
  20:268,target 11
  23:260 reduce
  66:/,target 80
  53:266 reduce
  136:271,target 96
  106:265,target 91
  53:267 reduce
  51:257,target 33
  17:/ reduce
  122:260,target 95
  96:257,target 91
  85:`,target 13
  17:0 reduce
  53:270 reduce
  46:282,target 67
  5:270,target 69
  5:269,target 69
  25:?,target 16
  53:271 reduce
  35:/,target 55
  32:271,target 63
  77:271,target 26
  17:260,target 9
  23:266 reduce
  118:267,target 82
  93:265,target 85
  63:260,target 49
  23:267 reduce
  134:262,target 95
  59:/ reduce
  5:` reduce
  23:268 reduce
  23:269 reduce
  23:270 reduce
  108:284 goto
  23:271 reduce
  108:285 goto
  59:267,target 50
  23:`,target 20
  131:269,target 37
  101:264,target 97
  116:258,target 79
  85::,target 13
  17:: reduce
  0:268,target 10
  26:269,target 5
  26:270,target 5
  72:270,target 24
  12:258,target 71
  113:266,target 81
  57:258,target 73
  104:: shift
  17:? reduce
  22:0,target 12
  54:266,target 31
  23::,target 20
  125:268,target 15
  99:266,target 87
  70:261,target 94
  114:257 shift
  111:257,target 123
  121:/,target 94
  88:257 reduce
  21:268,target 38
  88:258 reduce
  137:271,target 138
  107:265,target 92
  88:260 reduce
  52:257,target 29
  97:257,target 91
  58:257 reduce
  33:271,target 62
  78:271,target 27
  58:258 reduce
  32:/ reduce
  18:260,target 8
  119:267,target 83
  64:260,target 54
  58:260 reduce
  32:0 reduce
  135:262,target 95
  132:` reduce
  88:266 reduce
  88:267 reduce
  87:` reduce
  15:267,target 9
  28:257 reduce
  118:/ reduce
  88:269 reduce
  61:267,target 47
  28:258 reduce
  132:270,target 14
  132:269,target 14
  102:264,target 89
  74:/ reduce
  53:?,target 30
  28:260 reduce
  117:258,target 80
  63:/,target 49
  58:266 reduce
  8:`,target 67
  58:267 reduce
  1:268,target 70
  82:`,target 39
  27:269,target 4
  27:270,target 4
  108::,target 93
  73:270,target 25
  58:269 reduce
  13:258,target 72
  22:?,target 12
  58:258,target 51
  32:: reduce
  32:/,target 63
  130:261,target 94
  28:266 reduce
  24:277,target 44
  28:267 reduce
  7:0,target 66
  10:266,target 75
  28:268 reduce
  55:266,target 34
  28:269 reduce
  28:270 reduce
  118:: reduce
  32:? reduce
  28:271 reduce
  8::,target 67
  19:`,target 7
  20:`,target 11
  22:268,target 12
  17:` reduce
  138:271,target 97
  108:265,target 93
  53:257,target 30
  124:260,target 38
  98:257,target 86
  74:? reduce
  48:282,target 67
  7:269,target 66
  7:270,target 66
  34:271,target 58
  18:0,target 8
  19:260,target 35
  20:260,target 11
  121:267,target 94
  65:260,target 52
  59:` reduce
  136:262,target 96
  19::,target 32
  20::,target 11
  119:257 reduce
  46:/ shift
  16:267,target 10
  119:258 reduce
  62:267,target 48
  133:270,target 18
  133:269,target 18
  120:260 shift
  119:260 reduce
  117:/,target 80
  103:264,target 90
  94:257 shift
  119:261 reduce
  118:258,target 82
  94:258 shift
  119:262 reduce
  94:260 shift
  2:268,target 74
  133:/ reduce
  119:263 reduce
  94:261 shift
  28:269,target 3
  28:270,target 3
  133:0 reduce
  119:264 reduce
  94:262 shift
  88:/ reduce
  74:270,target 21
  119:265 reduce
  115:266,target 78
  94:263 shift
  89:264,target 97
  64:257 reduce
  59:258,target 50
  119:266 reduce
  94:264 shift
  64:258 reduce
  7:?,target 66
  119:267 reduce
  64:260 reduce
  94:266 shift
  0:260,target 7
  11:266,target 76
  120:269 shift
  119:270 reduce
  94:267 shift
  91:/,target 88
  56:266,target 35
  119:271 reduce
  34:257 reduce
  113:257,target 81
  94:270 shift
  34:258 reduce
  136::,target 96
  50:?,target 32
  49:?,target 36
  34:260 reduce
  64:266 reduce
  59:/,target 50
  5:`,target 69
  23:268,target 20
  133:: reduce
  64:267 reduce
  110:265,target 122
  109:265,target 121
  54:257,target 31
  125:260,target 15
  99:257,target 87
  64:269 reduce
  18:?,target 8
  8:269,target 67
  8:270,target 67
  28:/,target 3
  120:279 goto
  35:271,target 55
  34:266 reduce
  32:` reduce
  133:? reduce
  34:267 reduce
  21:260,target 35
  122:267,target 95
  66:260,target 82
  34:268 reduce
  137:262,target 95
  34:270 reduce
  34:269 reduce
  18:/ reduce
  34:271 reduce
  18:0 reduce
  94:283 goto
  5::,target 69
  16:`,target 10
  17:267,target 9
  94:284 goto
  63:267,target 49
  134:270,target 100
  94:285 goto
  119:258,target 83
  105:/ shift
  61:/ reduce
  3:268,target 73
  30:270,target 6
  30:269,target 6
  29:269,target 39
  29:270,target 40
  75:270,target 22
  15:258,target 6
  116:266,target 79
  91:264,target 88
  61:258,target 47
  15:0,target 1
  0:276,target 18
  18:: reduce
  1:260,target 70
  12:266,target 71
  16::,target 10
  57:266,target 75
  128:268,target 19
  125:257 reduce
  125:258 reduce
  114:257,target 127
  125:260 reduce
  99:257 reduce
  18:? reduce
  99:258 reduce
  133:`,target 18
  99:260 reduce
  10:257,target 75
  99:261 reduce
  55:257,target 34
  126:260,target 131
  99:262 reduce
  99:263 reduce
  70:257 shift
  69:257 shift
  9:269,target 68
  9:270,target 68
  125:266 reduce
  99:264 reduce
  70:258 shift
  69:258 shift
  66:276,target 87
  36:271,target 56
  4:?,target 3
  125:267 reduce
  99:265 reduce
  70:260 shift
  69:260 shift
  22:260,target 12
  125:268 reduce
  99:266 reduce
  77:?,target 26
  70:261 shift
  67:260,target 53
  138:262,target 97
  132:0,target 14
  125:270 reduce
  125:269 reduce
  99:267 reduce
  87:/,target 44
  70:262 shift
  6:277,target 25
  125:271 reduce
  70:263 shift
  46:` shift
  40:257 reduce
  39:257 reduce
  99:270 reduce
  70:264 shift
  40:258 reduce
  39:258 reduce
  18:267,target 8
  133::,target 18
  99:271 reduce
  64:267,target 54
  40:260 reduce
  39:260 reduce
  135:270,target 100
  105:264,target 97
  70:266 shift
  69:266 shift
  56:/,target 35
  33:/ reduce
  2:`,target 74
  121:258,target 94
  70:267 shift
  69:267 shift
  33:0 reduce
  133:` reduce
  4:268,target 10
  10:257 reduce
  15:275,target 27
  102::,target 89
  88:` reduce
  70:270 shift
  69:269 shift
  31:270,target 59
  31:269,target 59
  10:258 reduce
  15:?,target 3
  76:270,target 23
  10:260 reduce
  16:258,target 10
  25:/,target 16
  119:/ reduce
  117:266,target 80
  62:258,target 48
  40:266 reduce
  39:266 reduce
  75:/ reduce
  40:267 reduce
  39:267 reduce
  69:274 goto
  40:268 reduce
  39:268 reduce
  1:0,target 70
  40:270 reduce
  40:269 reduce
  39:270 reduce
  39:269 reduce
  2:260,target 74
  13:266,target 72
  69:276 goto
  58:266,target 51
  40:271 reduce
  39:271 reduce
  7:/ reduce
  7:0 reduce
  2::,target 74
  10:266 reduce
  13:`,target 72
  115:257,target 78
  33:: reduce
  10:267 reduce
  70:285,target 103
  10:268 reduce
  10:269 reduce
  10:270 reduce
  25:268,target 16
  69:282 goto
  10:271 reduce
  11:257,target 76
  70:283 goto
  56:257,target 35
  127:260,target 84
  119:: reduce
  70:284 goto
  44::,target 48
  33:? reduce
  70:285 goto
  12:0,target 71
  37:271,target 57
  132:?,target 14
  23:260,target 20
  98:265,target 86
  68:260,target 74
  7:: reduce
  13::,target 72
  18:` reduce
  75:? reduce
  19:267,target 37
  20:267,target 11
  131:260 reduce
  65:267,target 52
  136:270,target 96
  106:264,target 91
  7:? reduce
  122:258,target 95
  61:` reduce
  101:257 shift
  5:268,target 69
  101:258 shift
  32:270,target 63
  32:269,target 63
  101:260 shift
  77:270,target 26
  75:257 reduce
  17:258,target 9
  118:266,target 82
  101:261 shift
  93:264,target 85
  75:258 reduce
  63:258,target 49
  1:?,target 70
  134:261,target 94
  101:262 shift
  75:260 reduce
  101:263 shift
  74:?,target 21
  131:269 reduce
  130:285,target 103
  128:0,target 19
  101:264 shift
  84:/,target 41
  3:260,target 73
  59:266,target 50
  45:257 shift
  101:263,target 96
  101:266 shift
  90:/ reduce
  45:258 shift
  116:257,target 79
  101:267 shift
  90:0 reduce
  45:260 shift
  75:266 reduce
  53:/,target 30
  0:267,target 9
  101:270 shift
  75:267 reduce
  26:268,target 5
  12:257,target 71
  15:257 shift
  113:265,target 81
  75:270 reduce
  57:257,target 72
  12:?,target 71
  15:258 shift
  128:260,target 19
  75:271 reduce
  15:260 shift
  22:/,target 12
  45:266 shift
  45:267 shift
  41:`,target 61
  38:271,target 64
  24:259,target 23
  134:: shift
  125:267,target 15
  99:265,target 87
  70:260,target 93
  69:260,target 82
  47:? shift
  45:270 shift
  4:257 shift
  90:: reduce
  45:271 shift
  4:260 shift
  10:`,target 75
  15:266 shift
  15:267 shift
  21:267,target 37
  66:267,target 84
  33:` reduce
  15:268 shift
  137:270,target 100
  107:264,target 97
  40:0,target 60
  39:0,target 65
  15:270 shift
  15:269 shift
  101:284 goto
  90:? reduce
  15:271 shift
  101:285 goto
  6:268,target 24
  19:/ shift
  20:/ reduce
  45:278 goto
  41::,target 61
  33:270,target 62
  33:269,target 62
  4:266 shift
  19:0 reduce
  20:0 reduce
  78:270,target 27
  4:267 shift
  15:274 goto
  18:258,target 8
  119:266,target 83
  94:264,target 97
  64:258,target 54
  4:268 shift
  15:275 goto
  135:261,target 94
  128:?,target 19
  4:269 shift
  4:270 shift
  15:276 goto
  138:/,target 97
  106:/ reduce
  4:271 shift
  10::,target 75
  62:/ reduce
  4:260,target 7
  7:` reduce
  15:266,target 8
  136:257 reduce
  61:266,target 47
  136:258 reduce
  132:268,target 14
  102:263,target 89
  15:281 goto
  136:260 reduce
  117:257,target 80
  107:/,target 92
  15:282 goto
  136:261 reduce
  1:267,target 70
  136:262 reduce
  19:: shift
  20:: reduce
  27:268,target 4
  136:263 reduce
  106:257 reduce
  13:257,target 72
  136:264 reduce
  106:258 reduce
  58:257,target 51
  136:265 reduce
  130:260,target 93
  129:260,target 131
  106:260 reduce
  81:257 reduce
  4:281 goto
  136:266 reduce
  106:261 reduce
  81:258 reduce
  136:267 reduce
  106:: reduce
  106:262 reduce
  81:260 reduce
  69:276,target 87
  40:271,target 60
  39:271,target 65
  7:/,target 66
  19:? shift
  20:? reduce
  106:263 reduce
  85:271,target 13
  71:?,target 28
  25:260,target 16
  136:270 reduce
  125:0,target 15
  106:264 reduce
  81:/,target 42
  71:260,target 28
  136:271 reduce
  106:265 reduce
  51:257 reduce
  106:266 reduce
  51:258 reduce
  106:267 reduce
  51:260 reduce
  40:?,target 60
  39:?,target 65
  22:267,target 12
  81:266 reduce
  67:267,target 53
  50:/,target 32
  49:/,target 36
  138:270,target 97
  108:264,target 97
  106:270 reduce
  81:267 reduce
  106:271 reduce
  21:257 shift
  81:269 reduce
  7:268,target 66
  34:270,target 58
  34:269,target 58
  18:/,target 8
  21:260 shift
  80:269,target 43
  51:266 reduce
  19:258,target 7
  20:258,target 11
  121:266,target 94
  95:264,target 97
  65:258,target 52
  51:267 reduce
  37:`,target 57
  136:261,target 96
  34:/ reduce
  99::,target 87
  51:270 reduce
  34:0 reduce
  9:257 reduce
  51:271 reduce
  5:260,target 69
  9:258 reduce
  16:266,target 10
  90:` reduce
  62:266,target 48
  9:260 reduce
  21:266 shift
  133:268,target 18
  103:263,target 90
  21:267 shift
  121:/ reduce
  118:257,target 82
  21:268 shift
  76:/ reduce
  36:0,target 56
  2:267,target 74
  21:270 shift
  21:269 shift
  21:271 shift
  28:268,target 3
  115:265,target 78
  89:263,target 96
  60:257,target 22
  59:257,target 50
  37::,target 57
  8:/ reduce
  9:266 reduce
  131:260,target 37
  8:0 reduce
  9:267 reduce
  34:: reduce
  9:268 reduce
  125:?,target 15
  41:271,target 61
  0:258,target 6
  9:269 reduce
  9:270 reduce
  9:271 reduce
  26:260,target 5
  127:267,target 84
  72:260,target 24
  121:: reduce
  34:? reduce
  23:267,target 20
  68:267,target 76
  110:264,target 97
  109:264,target 97
  125:258,target 15
  8:: reduce
  19:` reduce
  20:` reduce
  8:268,target 67
  112:260 shift
  86:257 reduce
  76:? reduce
  35:270,target 55
  35:269,target 55
  86:258 reduce
  81:269,target 42
}

array set ::snip_rules {
  9,l 273
  11,l 273
  32,l 278
  53,l 280
  74,l 281
  95,l 284
  6,l 273
  28,l 278
  50,l 280
  49,l 280
  71,l 281
  92,l 284
  3,l 273
  25,l 278
  46,l 280
  67,l 281
  0,l 286
  88,l 283
  22,l 278
  43,l 280
  64,l 281
  85,l 283
  18,l 276
  40,l 280
  39,l 280
  61,l 281
  82,l 283
  15,l 275
  36,l 278
  57,l 281
  78,l 283
  12,l 274
  33,l 278
  54,l 280
  75,l 281
  96,l 285
  7,l 273
  29,l 278
  30,l 278
  51,l 280
  72,l 281
  93,l 284
  4,l 273
  26,l 278
  47,l 280
  68,l 281
  90,l 283
  89,l 283
  1,l 272
  23,l 278
  44,l 280
  65,l 281
  86,l 283
  19,l 276
  20,l 277
  41,l 280
  62,l 281
  83,l 283
  16,l 276
  37,l 279
  58,l 281
  80,l 283
  79,l 283
  13,l 274
  34,l 278
  55,l 281
  76,l 281
  97,l 285
  8,l 273
  10,l 273
  31,l 278
  52,l 280
  73,l 281
  94,l 284
  5,l 273
  27,l 278
  48,l 280
  70,l 281
  69,l 281
  91,l 283
  2,l 273
  24,l 278
  45,l 280
  66,l 281
  87,l 283
  21,l 278
  42,l 280
  63,l 281
  84,l 283
  17,l 276
  38,l 279
  60,l 281
  59,l 281
  81,l 283
  14,l 275
  35,l 278
  56,l 281
  77,l 282
}

array set ::snip_rules {
  63,dc 2
  12,dc 2
  77,dc 3
  26,dc 2
  92,dc 2
  3,dc 2
  41,dc 2
  55,dc 2
  70,dc 1
  69,dc 1
  18,dc 10
  84,dc 3
  33,dc 1
  9,dc 1
  47,dc 1
  62,dc 2
  11,dc 1
  76,dc 1
  25,dc 2
  91,dc 2
  2,dc 2
  40,dc 2
  39,dc 2
  54,dc 1
  68,dc 1
  17,dc 6
  83,dc 2
  32,dc 1
  97,dc 8
  8,dc 1
  46,dc 2
  61,dc 2
  10,dc 1
  75,dc 1
  24,dc 2
  90,dc 1
  89,dc 1
  1,dc 1
  38,dc 1
  53,dc 1
  67,dc 1
  16,dc 2
  82,dc 2
  31,dc 1
  96,dc 6
  7,dc 1
  45,dc 2
  60,dc 2
  59,dc 2
  74,dc 1
  23,dc 2
  0,dc 1
  88,dc 1
  37,dc 2
  52,dc 1
  66,dc 1
  15,dc 9
  81,dc 2
  29,dc 1
  30,dc 1
  95,dc 3
  6,dc 2
  44,dc 2
  58,dc 2
  73,dc 1
  22,dc 2
  87,dc 1
  36,dc 1
  51,dc 1
  65,dc 2
  14,dc 10
  80,dc 2
  79,dc 2
  28,dc 2
  94,dc 3
  5,dc 2
  43,dc 2
  57,dc 2
  72,dc 1
  21,dc 2
  86,dc 1
  35,dc 1
  50,dc 1
  49,dc 1
  64,dc 2
  13,dc 6
  78,dc 2
  27,dc 2
  93,dc 2
  4,dc 2
  42,dc 2
  56,dc 2
  71,dc 1
  19,dc 9
  20,dc 1
  85,dc 1
  34,dc 1
  48,dc 1
}

array set ::snip_rules {
  41,line 224
  96,line 399
  7,line 76
  37,line 210
  93,line 388
  4,line 64
  34,line 199
  90,line 377
  89,line 374
  1,line 50
  31,line 190
  86,line 365
  27,line 178
  83,line 356
  24,line 169
  80,line 347
  79,line 344
  21,line 160
  76,line 331
  17,line 128
  73,line 322
  14,line 113
  70,line 313
  69,line 310
  11,line 92
  66,line 301
  63,line 292
  60,line 283
  59,line 280
  56,line 271
  53,line 260
  50,line 251
  49,line 248
  46,line 239
  43,line 230
  9,line 84
  40,line 221
  39,line 218
  95,line 394
  6,line 72
  36,line 205
  92,line 385
  3,line 60
  33,line 196
  88,line 371
  29,line 184
  30,line 187
  85,line 362
  26,line 175
  82,line 353
  23,line 166
  78,line 341
  19,line 138
  20,line 155
  75,line 328
  16,line 125
  72,line 319
  13,line 100
  68,line 307
  10,line 88
  65,line 298
  62,line 289
  58,line 277
  55,line 268
  52,line 257
  48,line 245
  45,line 236
  42,line 227
  97,line 402
  8,line 80
  38,line 213
  94,line 391
  5,line 68
  35,line 202
  91,line 380
  2,line 56
  32,line 193
  87,line 368
  28,line 181
  84,line 359
  25,line 172
  81,line 350
  22,line 163
  77,line 336
  18,line 135
  74,line 325
  15,line 120
  71,line 316
  12,line 97
  67,line 304
  64,line 295
  61,line 286
  57,line 274
  54,line 263
  51,line 254
  47,line 242
  44,line 233
}

proc snip_parse {} {
    set snip_state_stack {0}
    set snip_value_stack {{}}
    set snip_token ""
    set snip_accepted 0
    while {$snip_accepted == 0} {
        set snip_state [lindex $snip_state_stack end]
        if {$snip_token == ""} {
            set ::snip_lval ""
            set snip_token [snip_lex]
            set snip_buflval $::snip_lval
        }
        if {![info exists ::snip_table($snip_state:$snip_token)]} {
            # pop off states until error token accepted
            while {[llength $snip_state_stack] > 0 && \
                       ![info exists ::snip_table($snip_state:error)]} {
                set snip_state_stack [lrange $snip_state_stack 0 end-1]
                set snip_value_stack [lrange $snip_value_stack 0 \
                                       [expr {[llength $snip_state_stack] - 1}]]
                set snip_state [lindex $snip_state_stack end]
            }
            if {[llength $snip_state_stack] == 0} {
                snip_error "parse error"
                return 1
            }
            lappend snip_state_stack [set snip_state $::snip_table($snip_state:error,target)]
            lappend snip_value_stack {}
            # consume tokens until it finds an acceptable one
            while {![info exists ::snip_table($snip_state:$snip_token)]} {
                if {$snip_token == 0} {
                    snip_error "end of file while recovering from error"
                    return 1
                }
                set ::snip_lval {}
                set snip_token [snip_lex]
                set snip_buflval $::snip_lval
            }
            continue
        }
        switch -- $::snip_table($snip_state:$snip_token) {
            shift {
                lappend snip_state_stack $::snip_table($snip_state:$snip_token,target)
                lappend snip_value_stack $snip_buflval
                set snip_token ""
            }
            reduce {
                set snip_rule $::snip_table($snip_state:$snip_token,target)
                set snip_l $::snip_rules($snip_rule,l)
                if {[info exists ::snip_rules($snip_rule,e)]} {
                    set snip_dc $::snip_rules($snip_rule,e)
                } else {
                    set snip_dc $::snip_rules($snip_rule,dc)
                }
                set snip_stackpointer [expr {[llength $snip_state_stack]-$snip_dc}]
                snip_setupvalues $snip_value_stack $snip_stackpointer $snip_dc
                set _ $1
                set ::snip_lval [lindex $snip_value_stack end]
                switch -- $snip_rule {
                    1 { 
        set ::snip_value $1
       }
                    2 { 
           set _ [concat $1 [list $2 {}]]
           puts "A ($_)"
          }
                    3 { 
           set _ [concat $1 [list $2 {}]]
           puts "B ($_)"
          }
                    4 { 
           set _ [concat $1 [list $2 {}]]
           puts "C ($_)"
          }
                    5 { 
           set _ [concat $1 $2]
           puts "D ($_)"
          }
                    6 { 
           set _ [concat $1 [list $2 {}]]
           puts "E ($_)"
          }
                    7 { 
           set _ [list $1 {}]
           puts "F ($_)"
          }
                    8 { 
           set _ [list $1 {}]
           puts "G ($_)"
          }
                    9 { 
           set _ [list $1 {}]
           puts "H ($_)"
          }
                    10 { 
           set _ $1
           puts "I ($_)"
          }
                    11 { 
           set _ [list $1 {}]
           puts "J ($_)"
          }
                    12 { 
           set _ [list " " [snippets::set_tabstop $::snip_txt $2]]
          }
                    13 { 
           set _ [list $5 [snippets::set_tabstop $::snip_txt $3 $5]]
          }
                    14 { 
             if {[set val [snippets::get_tabstop $3]] ne ""} {
               set regexp_opts [list]
               if {[string first g $9] != -1} {
                 lappend regexp_opts -all
               }
               set _ [parse_format $7 [regexp -inline {*}$regexp_opts -- $5 $val]]
             } else {
               set _ [get_retval $1 $2 $3 $4 $5 $6 $7 $8 $9 $10]
             }
            }
                    15 { 
             if {[set val [snippets::get_tabstop $3]] ne ""} {
               set _ [parse_format $7 [regexp -inline -- $5 $val]]
             } else {
               set _ [get_retval $1 $2 $3 $4 $5 $6 $7 $8 $9 $10]
             }
            }
                    16 { 
            set _ $2
           }
                    17 { 
            set _ [expr {($3 eq "") ? $5 : $3}]
           }
                    18 { 
            set regexp_opts [list]
            if {[string first g $9] != -1} {
              lappend regexp_opts "-all"
            }
            set _ [parse_format $7 [regexp -inline {*}$regexp_opts -- $5 $3]]
           }
                    19 { 
            set _ [parse_format $7 [regexp -inline {*}$regexp_opts -- $5 $3]]
           }
                    20 { 
           set txt $::snip_txt
           switch $1 {
             SELECTED_TEXT { set _ [$txt get sel.first sel.last] }
             CLIPBOARD     { set _ [expr {![catch "clipboard get" rc] ? $rc : ""}] }
             CURRENT_LINE  { set _ [$txt get "insert linestart" "insert lineend"] }
             CURRENT_WORD  { set _ [$txt get "insert wordstart" "insert wordend"] }
             DIRECTORY     { set _ [file dirname [gui::current_filename]] }
             FILEPATH      { set _ [gui::current_filename] }
             FILENAME      { set _ [file tail [gui::current_filename]] }
             LINE_INDEX    { set _ [lindex [split [$txt index insert] .] 1] }
             LINE_NUMBER   { set _ [lindex [split [$txt index insert] .] 0] }
             CURRENT_DATE  { set _ [clock format [clock seconds] -format "%m/%d/%Y"] }
           }
          }
                    21 { 
           set _ "$1$2"
          }
                    22 { 
           set _ "$1\\n"
          }
                    23 { 
           set _ "$1\\t"
          }
                    24 { 
           set _ "$1$2"
          }
                    25 { 
           set _ "$1\$"
          }
                    26 { 
           set _ "$1\("
          }
                    27 { 
           set _ "$1)"
          }
                    28 { 
           set _ "?"
          }
                    29 { 
           set _ $1
          }
                    30 { 
           set _ "\n"
          }
                    31 { 
           set _ "\t"
          }
                    32 { 
           set _ $1
          }
                    33 { 
           set _ "\$"
          }
                    34 { 
           set _ "("
          }
                    35 { 
           set _ ")"
          }
                    36 { 
           set _ "?"
          }
                    37 { 
        set _ "$1$2"
       }
                    38 { 
        set _ $1
       }
                    39 { 
         set _ "$1$2"
        }
                    40 { 
         set _ "$1\\n"
        }
                    41 { 
         set _ "$1\\t"
        }
                    42 { 
         set _ "$1$2"
        }
                    43 { 
         set _ "$1/"
        }
                    44 { 
         set _ "$1$2"
        }
                    45 { 
         set _ "$1$2"
        }
                    46 { 
         set _ [concat $1 {} $2]
        }
                    47 { 
         set _ $1
        }
                    48 { 
         set _ "\\n"
        }
                    49 { 
         set _ "\\t"
        }
                    50 { 
         set _ $1
        }
                    51 { 
         set _ "/"
        }
                    52 { 
         set _ $1
        }
                    53 { 
         set _ $1
        }
                    54 { 
         set _ $1
        }
                    55 { 
        set _ "$1$2"
       }
                    56 { 
        set _ "$1\\n"
       }
                    57 { 
        set _ "$1\\t"
       }
                    58 { 
        set _ "$1$2"
       }
                    59 { 
        set _ "$1/"
       }
                    60 { 
        set _ "$1\("
       }
                    61 { 
        set _ "$1)"
       }
                    62 { 
        set _ "$1?"
       }
                    63 { 
        set _ "$1:"
       }
                    64 { 
        set _ "$1$2"
       }
                    65 { 
        set _ "$1$2"
       }
                    66 { 
        set _ $1
       }
                    67 { 
        set _ "\\n"
       }
                    68 { 
        set _ "\\t"
       }
                    69 { 
        set _ $1
       }
                    70 { 
        set _ "/"
       }
                    71 { 
        set _ "("
       }
                    72 { 
        set _ ")"
       }
                    73 { 
        set _ "?"
       }
                    74 { 
        set _ ":"
       }
                    75 { 
        set _ $1
       }
                    76 { 
        set _ $1
       }
                    77 { 
         set _ [expr {![catch "exec $2" rc] ? $rc : ""}]
        }
                    78 { 
          set _ "$1$2"
         }
                    79 { 
          set _ "$1\\n"
         }
                    80 { 
          set _ "$1\\t"
         }
                    81 { 
          set _ "$1$2"
         }
                    82 { 
          set _ "$1$2"
         }
                    83 { 
          set _ "$1$2"
         }
                    84 { 
          set _ "$1\$$3"
         }
                    85 { 
          set _ $1
         }
                    86 { 
          set _ "\\n"
         }
                    87 { 
          set _ "\\t"
         }
                    88 { 
          set _ $1
         }
                    89 { 
          set _ $1
         }
                    90 { 
          set _ $1
         }
                    91 { 
          set _ "\$$2"
         }
                    92 { 
              set _ "$1$2"
             }
                    93 { 
              set _ "$1$2"
             }
                    94 { 
              set _ "$1$2$3"
             }
                    95 { 
              set _ "$1$2$3"
             }
                    96 { 
               set _ [get_retval $1 $2 $3 $4 $5 $6]
              }
                    97 { 
               set _ [get_retval $1 $2 $3 $4 $5 $6 $7 $8]
              }
                }
                snip_unsetupvalues $snip_dc
                # pop off tokens from the stack if normal rule
                if {![info exists ::snip_rules($snip_rule,e)]} {
                    incr snip_stackpointer -1
                    set snip_state_stack [lrange $snip_state_stack 0 $snip_stackpointer]
                    set snip_value_stack [lrange $snip_value_stack 0 $snip_stackpointer]
                }
                # now do the goto transition
                lappend snip_state_stack $::snip_table([lindex $snip_state_stack end]:$snip_l,target)
                lappend snip_value_stack $_
            }
            accept {
                set snip_accepted 1
            }
            goto -
            default {
                puts stderr "Internal parser error: illegal command $::snip_table($snip_state:$snip_token)"
                return 2
            }
        }
    }
    return 0
}

######
# end autogenerated taccle functions
######

rename snip_error snip_error_orig
proc snip_error {s} {
  set ::snip_errstr "[string repeat " " $::snip_begpos]^"
  set ::snip_errmsg $s
}

