# api.tcl
msgcat::mcmset cs {

  "Argument list to api::add_file was not an even key/value pair"
  "Argument seznam API :: add_file nebyl ani klíč / hodnota pár"

}

# bgproc.tcl
msgcat::mcmset cs {

  "Unable to run system command (%s)"
  "Nelze spustit příkaz systému (% s)"

}

# diff.tcl
msgcat::mcmset cs {

  "    End: "
  "konec"

  "    Start: "
  "Start"

  "Enter difference command"
  "Zadejte příkaz rozdíl"

  "Enter starting file"
  "Zadejte počáteční soubor"

  "Update"
  "Aktualizovat"

}

# gui.tcl
msgcat::mcmset cs {

  "%s, Line: %d, Column: %d"
  "% S, řádek% d, sloupec% d"

  "Case sensitivity"
  "Rozlišování"

  "Close All Tabs"
  "Zavřít vše"

  "Close Other Tab(s)"
  "Close Ostatní Tab (y)"

  "Close Other*"
  "Close Ostatní *"

  "Close Tab"
  "Zavřít list"

  "Copyright %d-%d"
  "Copyright% d-% d"

  "Delete tab?"
  "Kartu smazat?"

  "Developer:"
  "Vývojář:"

  "Email:"
  "E-mail:"

  "Error"
  "Chyba"

  "Favorited"
  "Oblíbené"

  "File already exists.  Use '!' to force an overwrite"
  "Soubor již existuje.  Použijte '!' přinutit přepsání"

  "File attribute (%s) does not exist"
  "Atribut souboru (% s) neexistuje"

  "File index is out of range"
  "Obsah souboru je mimo rozsah"

  "License:"
  "Licence"

  "Line: %d, Column: %d"
  "Line:% d, sloupec% d"

  "Locked"
  "zamčený, zamknutý"

  "Move*"
  "přesunout"

  "Must be in multicursor mode to insert numbers"
  "Musí být v multicursor režimu vložit čísla"

  "No write permissions.  Use '!' to force write."
  "Žádné oprávnění k zápisu.  Použijte '!' nutit psát."

  "Release Type:"
  "Vydání typ:"

  "Reload file?"
  "Obnovit soubor?"

  "Save request"
  "Uložte žádost"

  "Show in Sidebar"
  "Zobrazit v postranním panelu"

  "Starting number:"
  "Startovní číslo:"

  "Tcl/Tk Version:"
  "Tcl/Tk verze:"

  "Total Lines: %d, Total Characters: %d"
  "Celkem Linky:% d, celkem znaky:% d"

  "Unable to find current file (tab: %s)"
  "Nelze najít aktuální soubor (karta:% s)"

  "Unable to successfully parse number string"
  "Nelze úspěšně analyzovat číselné řetězce"

  "Unable to write file"
  "Nelze zapsat soubor"

  "Untitled"
  "Untitled"

  "Version:"
  "Verze:"

}

# markers.tcl
msgcat::mcmset cs {

  "Marker name:"
  "Název Marker:"

}

# menus.tcl
msgcat::mcmset cs {

  "                                  Profiling Report Sorted By (%s)"
  "Profilování Report řazeny dle (% s)"

  "About TKE"
  "O TKE"

  "Align Cursors"
  "Zarovnání kurzor?"

  "Append Next Occurrence"
  "P?ipojit dalí výskyt"

  "Auto-Indent"
  "Automatické odsazení"

  "Check for Update"
  "Zkontrolujte, zda aktualizaci"

  "Clear All"
  "Vymazat vše"

  "Close All"
  "Zavřít vše"

  "Close Current"
  "Uzav?ít aktuální"

  "Copy"
  "Kopírovat"

  "Create New..."
  "Vytvo?it nový/novou"

  "Create at Current Line"
  "Vytvo?it v aktuálním ?ádku"

  "Create..."
  "Vytvořit"

  "Cut"
  "Snížit"

  "Edit"
  "Upravit"

  "Edit Language"
  "Upravit jazyk"

  "Edit Session - Global"
  "Upravit relace - globální"

  "Edit Session - Language"
  "Upravit relace - jazyk"

  "Edit User"
  "Přidat Uživatele"

  "Edit User - Global"
  "Upravit uivatelské - globální"

  "Edit User - Language"
  "Upravit uivatelské - jazyk"

  "Edit..."
  "Upravit..."

  "File"
  "Soubor"

  "Find"
  "Find"

  "Find In Files"
  "Najít v souborech"

  "Find Matching Pair"
  "Najít odpovídající dvojice"

  "Find and Replace"
  "Najít a nahradit"

  "Format Text"
  "Formát textu"

  "From Clipboard"
  "Ze schránky"

  "Goto Last Tab"
  "Jdi Last Tab"

  "Goto Next Tab"
  "Jdi na Další Tab"

  "Goto Other Pane"
  "Jdi Ostatní Pane"

  "Goto Previous Tab"
  "Jdi na předchozí Tab"

  "Help"
  "Nápověda"

  "Hide Console"
  "Skrýt konzole"

  "Hide Line Numbers"
  "Skrýt čísla řádek"

  "Hide Meta Characters"
  "Skrýt znaky Meta"

  "Hide Sidebar"
  "Skrýt Sidebar"

  "Hide Status Bar"
  "Skrýt Status Bar"

  "Hide Tab Bar"
  "Skrýt liště"

  "Import TextMate Theme..."
  "Importujte TextMate téma..."

  "Indent"
  "Zvětšit odsazení"

  "Indent Mode"
  "Odsadit režim"

  "Indent Off"
  "Odsadit vypnuto"

  "Insert Enumeration"
  "Vloit  vý?et"

  "Insert Text"
  "Vložit text"

  "Install..."
  "nainstalovat"

  "Jump Backward"
  "Skok zp?t"

  "Jump Forward"
  "Skok vp?ed"

  "Launcher"
  "spouštěč"

  "Lock"
  "Uzamknout"

  "Markers"
  "Značky"

  "Menu Bindings"
  "Vázání Menu"

  "Menu Edit user snippets"
  "Menu Edit user fragmenty"

  "Menu: About TKE"
  "Menu: O TKE"

  "Menu: Align cursors"
  "Menu: Zarovnání kurzory"

  "Menu: Append next occurrence"
  "Menu: Připojit další výskyt"

  "Menu: Check for Update"
  "Menu: Zkontrolujte, zda aktualizaci"

  "Menu: Close all tabs"
  "Zavřít vše"

  "Menu: Close current session"
  "Nabídka: Zav?ít aktuální relaci"

  "Menu: Close current tab"
  "Menu: Zavřít aktuální záložku"

  "Menu: Copy text"
  "Nabídka: Kopírovat text"

  "Menu: Create marker at current line"
  "Nabídka: Vytvoření značky na aktuálním řádku"

  "Menu: Create new plugin"
  "Menu: Vytvořit nový plugin"

  "Menu: Create new theme"
  "Menu: Vytvořit nové téma"

  "Menu: Cut text"
  "Nabídka: Vyjmout text"

  "Menu: Delete session"
  "Nabídka: Odstranit relace"

  "Menu: Disable Vim mode"
  "Menu: Vypnutí režimu Vim"

  "Menu: Edit Tke theme"
  "Menu: Úpravy TKE téma"

  "Menu: Edit language snippets"
  "Nabídka: Upravit jazyk fragmenty"

  "Menu: Edit session current language preferences"
  "Menu: Úpravy relace sou?asné jazykové p?edvolby"

  "Menu: Edit session global preferences"
  "Nabídka: Upravit globální nastavení relace"

  "Menu: Edit user current language preferences"
  "Nabídka: Upravit aktuální uivatelské p?edvolby jazyka"

  "Menu: Edit user global preferences"
  "Nabídka: Upravit globální nastavení uivatele"

  "Menu: Edit user menu bindings"
  "Vázání Edit Uživatelské menu: Menu"

  "Menu: Enable Vim mode"
  "Menu: Povolit režim Vim"

  "Menu: Favorite file"
  "Menu: Oblíbený soubor"

  "Menu: Find"
  "Menu: Hledat"

  "Menu: Find and Replace"
  "Menu: Najít a nahradit"

  "Menu: Find in files"
  "Menu: Hledat v souborech"

  "Menu: Find matching character pair"
  "Menu: Najít odpovídající znak dvojice"

  "Menu: Find next occurrence"
  "Menu: Najít další výskyt"

  "Menu: Find previous occurrence"
  "Menu: Najít předchozí výskyt"

  "Menu: Format all text"
  "Menu: Formátování celý text"

  "Menu: Format selected text"
  "Nabídka: Formát vybraného textu"

  "Menu: Goto last tab"
  "Menu: Jdi Poslední záložka"

  "Menu: Goto next difference"
  "Nabídka: Goto další rozdíl"

  "Menu: Goto next tab"
  "Menu: Jdi na další karta"

  "Menu: Goto other pane"
  "Menu: Jdi na další podokno"

  "Menu: Goto previous difference"
  "Nabídka: Goto předchozí rozdíl"

  "Menu: Goto previous tab"
  "Menu: Jdi na předchozí kartu"

  "Menu: Hide Line Numbers"
  "Nabídka: Skrýt čísla řádek"

  "Menu: Hide Tab Bar"
  "Menu: Skrýt liště"

  "Menu: Hide console"
  "Menu: Skrýt konzole"

  "Menu: Hide meta characters"
  "Nabídka: Skrýt znaky meta"

  "Menu: Hide sidebar"
  "Menu: skrýt postranní panel"

  "Menu: Hide status bar"
  "Menu: Skrýt stavový řádek"

  "Menu: Import TextMate theme"
  "Menu: Dovoz TextMate téma"

  "Menu: Indent selected text"
  "Menu: odsazení vybraného textu"

  "Menu: Insert enumeration"
  "Menu: Vložte výčet"

  "Menu: Insert from clipboard"
  "Menu: Vložit ze schránky"

  "Menu: Insert snippet"
  "Menu: Vložit úryvek"

  "Menu: Install plugin"
  "Menu: Instalace plugin"

  "Menu: Jump backward"
  "Nabídka: Skok vzad"

  "Menu: Jump forward"
  "Nabídka: Skok vpřed"

  "Menu: Lock file"
  "Menu: Lock soubor"

  "Menu: Merge panes"
  "Nabídka: Slou?ení podoken"

  "Menu: Move to other pane"
  "Menu: Přechod na jiné tabule"

  "Menu: New file"
  "Menu: Nový soubor"

  "Menu: Open Favorite"
  "Menu: Open Oblíbené"

  "Menu: Open Recent"
  "Menu: Otevřít poslední"

  "Menu: Open directory"
  "Menu: Open directory"

  "Menu: Open file"
  "Menu: Otevřít soubor"

  "Menu: Open session"
  "Nabídka: Otev?ené relace"

  "Menu: Paste and format text from clipboard"
  "Menu: Vložit a formátovat text ze schránky"

  "Menu: Paste text from clipboard"
  "Vložit text ze schránky"

  "Menu: Quit application"
  "Menu: Ukončete aplikaci"

  "Menu: Redo"
  "Menu: Znovu"

  "Menu: Reload all plugins"
  "Menu: Znovu načíst všechny pluginy"

  "Menu: Reload snippets"
  "Nabídka: Reload fragmenty"

  "Menu: Remove all markers"
  "Nabídka: Odebrat všechny značky"

  "Menu: Remove marker from current line"
  "Nabídka: Odstranit značku z aktuálního řádku"

  "Menu: Replace line with script"
  "Nabídka: Nahradit řádek skriptu"

  "Menu: Restart tke"
  "Menu: Restart TKE"

  "Menu: Save all files"
  "Menu: Uložit všechny soubory"

  "Menu: Save current session"
  "Nabídka: Uloit aktuální relaci"

  "Menu: Save file"
  "Menu: Uložit soubor"

  "Menu: Save file as"
  "Menu: Uložit soubor jako"

  "Menu: Save sessions as"
  "Nabídka: Ukládání sezení jako"

  "Menu: Select all occurrences"
  "Menu: Vybrat všechny výskyty"

  "Menu: Select all text"
  "Menu: Vyberte celý text"

  "Menu: Send Bug Report"
  "Nabídka: Odeslat hlášení o chybě"

  "Menu: Send Feedback"
  "Nabídka: Odeslat názor"

  "Menu: Set indent mode to IND"
  "Nabídka: Nastavte režim odsazení na IND"

  "Menu: Set indent mode to IND+"
  "Nabídka: Nastavte režim odsazení na IND +"

  "Menu: Set indent mode to OFF"
  "Nabídka: Sada odsazení režim OFF"

  "Menu: Set user bindings to global bindings"
  "Menu: Nastavení uživatelských vazby na globální vazby"

  "Menu: Set user preferences to global preferences"
  "Menu: Nastavení uživatelských předvoleb na globální preference"

  "Menu: Show Diagnostic Logfile"
  "Nabídka: Show diagnostického protokolu"

  "Menu: Show Line Numbers"
  "Nabídka: Show čísla řádků"

  "Menu: Show Tab Bar"
  "Menu: Show Tab Bar"

  "Menu: Show console"
  "Menu: Zobrazit konzole"

  "Menu: Show file difference"
  "Nabídka: Show souboru rozdílu"

  "Menu: Show last profiling report"
  "Menu: Zobrazit report poslední profilování"

  "Menu: Show meta characters"
  "Nabídka: Show meta znaky"

  "Menu: Show selected line change"
  "Nabídka: Show vybrané linie změna"

  "Menu: Show sidebar"
  "Menu: Zobrazit sidebar"

  "Menu: Show status bar"
  "Menu: Show status bar"

  "Menu: Sort tabs"
  "Menu: Uspořádat karty"

  "Menu: Start profiling"
  "Menu: Start profilování"

  "Menu: Stop profiling"
  "Menu: Stop profilování"

  "Menu: Switch to session"
  "Nabídka: P?epnout do session"

  "Menu: Toggle comment"
  "Nabídka: P?epína? komentá?"

  "Menu: Toggle split view mode"
  "Menu: Přepnout režim Split view"

  "Menu: Undo"
  "Menu: Undo"

  "Menu: Unfavorite file"
  "Menu: Unfavorite soubor"

  "Menu: Unindent selected text"
  "Menu: Unindent vybraný text"

  "Menu: Uninstall plugin"
  "Menu: Odinstalovat plugin"

  "Menu: Unlock file"
  "Menu: Odemknout soubor"

  "Menu: View User Guide"
  "Menu: Zobrazit Uživatelská příručka"

  "Menu: View base preferences file"
  "Menu: Soubor základních předvoleb zobrazení"

  "Menu: View global menu bindings"
  "Menu: Zobrazit globální vazby nabídky"

  "Merge Panes"
  "Slou?it podokna"

  "Next Difference"
  "Dalí rozdíl"

  "Open Directory..."
  "Open Directory ..."

  "Open Favorite"
  "Otevřená Oblíbené"

  "Open File..."
  "Volný sloupec"

  "Open Recent"
  "Otevřít poslední"

  "Paste"
  "Pasta"

  "Paste and Format"
  "Vložit a Formát"

  "Plugins"
  "Plugin"

  "Preferences"
  "Preference"

  "Previous Difference"
  "P?edchozí rozdíl"

  "Profiling started"
  "Profilování začal"

  "Profiling stopped"
  "Profilování se zastavil"

  "Quit"
  "ukončit"

  "Redo"
  "Zrušit vrácení akce"

  "Reload"
  "Načíst znovu"

  "Remove All Markers"
  "Odebrat vechny zna?ky"

  "Remove From Current Line"
  "Odebrat z aktuálního ?ádku"

  "Replace Line With Script"
  "Nahradit ?ádek skriptu"

  "Reset User to Base"
  "Obnovit uživatelské základny"

  "Restart TKE"
  "Restartujte TKE"

  "Save All"
  "Uložit všechny"

  "Save As..."
  "Uložit jako..."

  "Save Current"
  "Uloit aktuální"

  "Select All"
  "Vybrat vše"

  "Select All Occurrences"
  "Vybrat vechny výskyty"

  "Select Next Occurrence"
  "Vybrat dalí výskyt"

  "Select Previous Occurrence"
  "Vybrat p?edchozí výskyt"

  "Selected"
  "Vybrané"

  "Send Bug Report"
  "Odeslat hlášení o chybě"

  "Send Feedback"
  "Odeslat názor"

  "Sessions"
  "Návt?vy"

  "Set Syntax"
  "Nastavit syntaxe"

  "Set Theme"
  "Set Theme"

  "Set User to Global"
  "Nastavit uživatele do globální"

  "Show Console"
  "Zobrazit Console"

  "Show Diagnostic Logfile"
  "Zobrazit diagnostického protokolu"

  "Show File Difference"
  "Zobrazit soubor rozdíl"

  "Show Last Profiling Report"
  "Zobrazit poslední profilování zprávu"

  "Show Line Numbers"
  "Zobrazovat čísla řádků"

  "Show Meta Characters"
  "Zobrazit znaky Meta"

  "Show Selected Line Change"
  "Zobrazit vybranou linku zm?nu"

  "Show Sidebar"
  "Zobrazit Sidebar"

  "Show Status Bar"
  "Show Status Bar"

  "Show Tab Bar"
  "Zobrazit Tab Bar"

  "Show*Profiling*"
  "Ukázat * Profilování *"

  "Smart Indent"
  "Chytré odsazení"

  "Snippet"
  "úryvek"

  "Snippets"
  "Snippet"

  "Sort Tabs"
  "Seřadit Záložky"

  "Split View"
  "Rozd?lený panel"

  "Start Profiling"
  "Začněte profilování"

  "Stop Profiling"
  "Zastavit profilování"

  "Switch To"
  "P?epnout do"

  "Tabs"
  "Karty"

  "Text"
  "Text"

  "Theme Creator"
  "Theme Creator"

  "Toggle Comment"
  "P?epnout komentá?"

  "Tools"
  "nástroje"

  "Undo"
  "Vrátit zpět akci"

  "Unindent"
  "Unindent"

  "Uninstall..."
  "odinstalovat"

  "Unlock"
  "Odemknout"

  "User Guide"
  "Uživatelská příručka"

  "View"
  "Náhled"

  "View Base"
  "Zobrazit základnu"

  "View Global"
  "Zobrazit globální"

  "Vim Mode"
  "Režim Vim"

}

# plugins.tcl
msgcat::mcmset cs {

  "ERROR (%s,%s): %s"
  "Chyba (%s, %s): %s"

  "ERROR:  Plugin name already exists"
  "Chyba: Plugin názvem již existuje"

  "ERROR:  Plugin name is not valid (only alphanumeric and underscores are allowed)"
  "ERROR: Plugin název není platný (pouze alfanumerické a podtržítka jsou povoleny)"

  "ERROR:  Unable to create plugin directory"
  "CHYBA: Nelze vytvořit plugin adresář"

  "ERROR:  Unable to write plugin files"
  "Chyba: Nelze zapsat plugin soubory"

  "Enter plugin name"
  "Zadejte plugin jméno"

  "Plugin %s installed"
  "Plugin% s nainstalován"

  "Plugin %s uninstalled"
  "Plugin% s odinstalován"

  "Plugin Errors"
  "Plugin chyby"

  "Plugins successfully reloaded"
  "Pluginy úspěšně reloaded"

  "Syntax errors found in selected plugins"
  "Syntaktické chyby nalezené ve vybraných pluginů"

}

# search.tcl
msgcat::mcmset cs {

  "%d substitutions done"
  "%d náhrady provádí"

  "No files found in specified directories"
  "Žádné soubory v uvedených adresářích"

  "No search results found"
  "Nic se nenašlo"

  "Search wrapped to beginning of file"
  "Hledat zabalené na začátku souboru"

  "Search wrapped to end of file"
  "Hledat zabalené do konce souboru"

}

# sidebar.tcl
msgcat::mcmset cs {

  "Add Parent Directory"
  "Nadřazená složka"

  "Close Directory Files"
  "Zavřít Directory soubory"

  "Copy Pathname"
  "Kopírovat cestu"

  "Delete directory?"
  "Smazat adresář?"

  "Delete file?"
  "Smazat soubor?"

  "Directory Name:"
  "Název adresáře:"

  "Duplicate"
  "Duplicita"

  "File Name:"
  "&Jméno souboru:"

  "Folder Name:"
  "Název sloky:"

  "Make Current Working Directory"
  "Ujistěte se aktuální pracovní adresář"

  "New Directory"
  "Nový adresář"

  "Open Directory Files"
  "Open Directory soubory"

  "Refresh Directory Files"
  "Obnovit soubory adresáře"

  "Remove Parent from Sidebar"
  "Odstranit Parent z postranního panelu"

  "Remove from Sidebar"
  "Odebrat z postranního panelu"

  "Rename"
  "Odebrat"

  "Show Difference"
  "Zobrazit rozdíl"

}

# snippets.tcl
msgcat::mcmset cs {

  "Snippet: *"
  "úryvek"

}

# syntax.tcl
msgcat::mcmset cs {

  "Syntax error in %s.syntax file"
  "Chyba syntaxe v% s.syntax souboru"

  "Syntax:  %s"
  "Syntax:% s"

  "Theme:  %s"
  "Téma:% s"

}

# themer.tcl
msgcat::mcmset cs {

  "Create"
  "Vytvořit"

  "Create New Theme"
  "Vytvořit nové téma"

  "Create custom"
  "Vytvořte si vlastní"

  "ERROR:  Unable to read %s"
  "CHYBA: Nelze přečíst% s"

  "ERROR:  Unable to write %s"
  "CHYBA: Nelze zapsat% s"

  "Edit theme"
  "Upravit téma"

  "Enter theme name"
  "Zadejte název motivu"

  "Error:  Theme is not a supported theme"
  "Chyba: Téma není podporován téma"

  "Import"
  "Dovoz"

  "Import TextMate Theme"
  "Dovoz TextMate téma"

  "Name:"
  "Jméno:"

  "OK"
  "OK"

  "Reset"
  "Resetovat"

  "Select theme"
  "Vyberte téma"

}

# tke.tcl
msgcat::mcmset cs {

  "Edit theme?"
  "Upravit téma?"

  "Import TextMate theme?"
  "Importovat TextMate téma?"

}

# vim.tcl
msgcat::mcmset cs {

  "File %s successfully written"
  "Soubor %s úspěšně zapsána"

  "Filename %s already exists"
  "Název souboru %s již existuje"

}

# General
msgcat::mcmset cs {

  "All"
  "Všichni"

  "Cancel"
  "Storno"

  "Close"
  "Zavřít"

  "Delete"
  "Odstranit"

  "Favorite"
  "oblíbená položka"

  "Find:"
  "Find"

  "Move to Other Pane"
  "Přesunout do jiné tabule"

  "New File"
  "Nový soubor"

  "Open"
  "Open"

  "Replace:"
  "slova"

  "Save"
  "Uložit"

  "Save As"
  "Uložit jako"

  "Unable to open %s for writing"
  "Nelze otevřít% s pro zápis"

  "Unfavorite"
  "Unfavorite"

}

