# api.tcl
msgcat::mcmset cs {

  "Argument list to api::add_file was not an even key/value pair"
  "Argument seznam API :: add_file nebyl ani klíč / hodnota pár"

  "Plugin"
  "Plugin"

}

# bgproc.tcl
msgcat::mcmset cs {

  "Unable to run system command"
  "Nelze spustit příkaz systému"

}

# diff.tcl
msgcat::mcmset cs {

  "    End: "
  "konec"

  "    Start: "
  "Start"

  "Enter difference command"
  "Zadejte příkaz rozdíl"

  "Enter starting file"
  "Zadejte počáteční soubor"

  "Update"
  "Aktualizovat"

}

# edit.tcl
msgcat::mcmset cs {

  "File successfully written"
  "Soubor úspěšně zapsána"

  "Filename already exists"
  "Název souboru již existuje."

}

# embed_tke.tcl
msgcat::mcmset cs {

  "Find:"
  "Find"

  "Replace:"
  "slova"

}

# gui.tcl
msgcat::mcmset cs {

  "All"
  "Všichni"

  "Case sensitivity"
  "Rozlišování"

  "Close All Tabs"
  "Zavřít vše"

  "Close Other Tabs"
  "Zavřít ostatní karty"

  "Close Other*"
  "Close Ostatní *"

  "Close Tab"
  "Zavřít list"

  "Column"
  "Sloupec"

  "Copyright"
  "Copyright"

  "Delete tab?"
  "Kartu smazat?"

  "Developer"
  "Vývojář"

  "Email"
  "E-mail"

  "Error"
  "Chyba"

  "Favorited"
  "Oblíbené"

  "File already exists.  Use '!' to force an overwrite"
  "Soubor již existuje.  Použijte '!' přinutit přepsání"

  "File attribute does not exist"
  "{attribute} neexistuje!"

  "File index is out of range"
  "Obsah souboru je mimo rozsah"

  "Image displayed in fill-in forms which closes the form UI.  Used in forms such as search, search/replace, and find in files."
  "Obrazy zobrazené v fill-in formách, které uzavírá formuláře UI. Používá se ve formách, jako je vyhledávání, hledání / nahrazování, a najít v souborech."

  "Image used in tab menus to indicate that the file is associated with a difference view."
  "Obrázek použitý v záložce nabídkách znamená, že soubor je spojen s cílem rozdíl."

  "Image used in tab menus to indicate that the file is locked."
  "Image používá v záložce menu, což znamená, že soubor je uzamčen."

  "Image used in tab menus to indicate that the file is readonly."
  "Image používá v záložce menu, což znamená, že soubor je jen pro čtení."

  "Image used in tab to indicate that the tab contains a difference view."
  "Obrázek použitý v kartě k označení, že karta obsahuje pohled rozdíl."

  "Image used in tab to indicate that the tab's file is readonly."
  "Image používá v záložce ukázat, že spis kartě je jen pro čtení."

  "Image used in tab to indicate that the tab’s file is locked."
  "Image používá v záložce ukázat, že spis kartě je uzamčen."

  "Image used in tab which, when clicked, closes the tab."
  "Image používané v kartě, které po kliknutí, uzavře kartu."

  "License"
  "Licence"

  "Line"
  "Linka"

  "Locked"
  "zamčený, zamknutý"

  "Move"
  "Přesunout"

  "Must be in multicursor mode to insert numbers"
  "Musí být v multicursor režimu vložit čísla"

  "No write permissions.  Use '!' to force write."
  "Žádné oprávnění k zápisu.  Použijte '!' nutit psát."

  "Release Type"
  "Typ vydání"

  "Reload file?"
  "Obnovit soubor?"

  "Replace"
  "Nahradit"

  "Save request"
  "Uložte žádost"

  "Show in Sidebar"
  "Zobrazit v postranním panelu"

  "Starting number:"
  "Startovní číslo:"

  "Tcl/Tk Version"
  "Tcl/Tk verze"

  "Total Characters"
  "Celkem znaků"

  "Total Lines"
  "Celkový čáry"

  "Unable to successfully parse number string"
  "Nelze úspěšně analyzovat číselné řetězce"

  "Unable to write file"
  "Nelze zapsat soubor"

  "Version"
  "Verze"

}

# markers.tcl
msgcat::mcmset cs {

  "Marker name:"
  "Název Marker:"

}

# menus.tcl
msgcat::mcmset cs {

  "About TKE"
  "O TKE"

  "Absolute"
  "Absolutní"

  "Align Cursors"
  "Zarovnání kurzor?"

  "Append Next Occurrence"
  "P?ipojit dalí výskyt"

  "Auto-Indent"
  "Automatické odsazení"

  "Bubble Down"
  "Bublina dole"

  "Bubble Up"
  "Vyvěrají"

  "Change Working Directory"
  "Změnit pracovní adresář"

  "Character"
  "Postava"

  "Check for Update"
  "Zkontrolujte, zda aktualizaci"

  "Classic Mac"
  "Klasický Mac"

  "Clear All"
  "Vymazat vše"

  "Close All"
  "Zavřít vše"

  "Close Current"
  "Uzav?ít aktuální"

  "Command"
  "Příkaz"

  "Command Result"
  "Výsledek příkazu"

  "Copy"
  "Kopírovat"

  "Create"
  "Vytvořit"

  "Create at Current Line"
  "Vytvo?it v aktuálním ?ádku"

  "Current Line"
  "Aktuální řádek"

  "Current Number"
  "Aktuální číslo"

  "Current Word"
  "Aktuální slovo"

  "Cursor"
  "Kurzor"

  "Cursor from Line Start"
  "Kurzor od začátku řádku"

  "Cursor to Line End"
  "Kurzor na konec řádku"

  "Cut"
  "Snížit"

  "Display Text Info"
  "Zobrazit informace o textu"

  "Edit"
  "Upravit"

  "Edit Language"
  "Upravit jazyk"

  "Edit Menu Edit user snippets"
  "Úprava Menu Upravit uživatelské fragmenty"

  "Edit Menu: Align cursors"
  "Nabídka úpravy: Zarovnání kurzorů"

  "Edit Menu: Bubble lines down one line"
  "Nabídka úpravy: Bublina řádky o jeden řádek dolů"

  "Edit Menu: Bubble lines up one line"
  "Nabídka úpravy: Bublina řádky o jeden řádek nahoru"

  "Edit Menu: Convert case to lower"
  "Nabídka úpravy: Convert případ nižší"

  "Edit Menu: Convert case to title"
  "Nabídka úpravy: Převod případ na titul"

  "Edit Menu: Convert case to upper"
  "Nabídka úpravy: Převod případ na horní"

  "Edit Menu: Copy text"
  "Nabídka úpravy: Kopírovat text"

  "Edit Menu: Cut text"
  "Nabídka úpravy: Vyjmout text"

  "Edit Menu: Delete current line"
  "Nabídka úpravy: Odstranit aktuální řádek"

  "Edit Menu: Delete current word"
  "Nabídka úpravy: Odstranit aktuální slovo"

  "Edit Menu: Delete from cursor to end of line"
  "Nabídka úpravy: Odstranění od kurzoru do konce řádku"

  "Edit Menu: Delete from start of line to cursor"
  "Nabídka úpravy: Odstraňte ze začátku řádku kurzoru"

  "Edit Menu: Delete template"
  "Nabídka úpravy: Odstranění šablony"

  "Edit Menu: Delete text between character"
  "Nabídka úpravy: Odstranit text mezi znaky"

  "Edit Menu: Delete the current number"
  "Nabídka úpravy: Odstranit aktuální číslo"

  "Edit Menu: Delete the whitespace to left of cursor"
  "Nabídka úpravy: Odstraňte mezery nalevo od kurzoru"

  "Edit Menu: Delete the whitespace to right of cursor"
  "Nabídka úpravy: Odstraňte mezery napravo od kurzoru"

  "Edit Menu: Edit language snippets"
  "Nabídka úpravy: Upravit jazyk fragmenty"

  "Edit Menu: Edit session current language preferences"
  "Nabídka úpravy: Edit session aktuální jazykové předvolby"

  "Edit Menu: Edit session global preferences"
  "Nabídka úpravy: Upravit globální nastavení relace"

  "Edit Menu: Edit template"
  "Menu úpravy: Šablona upravit"

  "Edit Menu: Edit user current language preferences"
  "Nabídka úpravy: Upravit aktuální uživatelské předvolby jazyka"

  "Edit Menu: Edit user global preferences"
  "Nabídka úpravy: Upravit globální nastavení uživatele"

  "Edit Menu: Edit user menu bindings"
  "Nabídka úpravy: Upravit uživatelské menu vazby"

  "Edit Menu: Format indentation for text"
  "Nabídka úpravy: Formát odsazení textu"

  "Edit Menu: Indent selected text"
  "Nabídka úpravy: Odsazení vybraného textu"

  "Edit Menu: Insert command result after current line"
  "Nabídka úpravy: Vložit výsledek příkazu za aktuálním řádkem"

  "Edit Menu: Insert file contents after current line"
  "Nabídka úpravy: Vložit obsah souboru za aktuálním řádkem"

  "Edit Menu: Insert from clipboard"
  "Nabídka úpravy: Vložení ze schránky"

  "Edit Menu: Insert line above current line"
  "Nabídka úpravy: Vložit řádek nad aktuální řádek"

  "Edit Menu: Insert line below current line"
  "Nabídka úpravy: Vložit řádek pod aktuálním řádkem"

  "Edit Menu: Insert snippet"
  "Nabídka upravit: Vložit fragment"

  "Edit Menu: Join lines"
  "Nabídka úpravy: Spojnice"

  "Edit Menu: Move cursor to bottom of screen"
  "Nabídka úpravy: Přesunout kurzor do dolní části obrazovky"

  "Edit Menu: Move cursor to end of current line"
  "Nabídka úpravy: Přesunout kurzor na konec aktuálního řádku"

  "Edit Menu: Move cursor to first line"
  "Nabídka úpravy: Posunout kurzor na první řádek"

  "Edit Menu: Move cursor to last line"
  "Nabídka úpravy: Přesune kurzor na poslední řádek"

  "Edit Menu: Move cursor to middle of screen"
  "Nabídka úpravy: Přesunout kurzor do středu obrazovky"

  "Edit Menu: Move cursor to next page"
  "Nabídka úpravy: Přesune kurzor na další stránku"

  "Edit Menu: Move cursor to next word"
  "Nabídka úpravy: Přesunout kurzor do následujícího slova"

  "Edit Menu: Move cursor to previous page"
  "Nabídka úpravy: Přesune kurzor na předchozí stránku"

  "Edit Menu: Move cursor to previous word"
  "Nabídka úpravy: Přesunout kurzor do předchozího slova."

  "Edit Menu: Move cursor to start of current line"
  "Nabídka úpravy: Přesunout kurzor na začátek aktuálního řádku."

  "Edit Menu: Move cursor to top of screen"
  "Nabídka úpravy: Přesunout kurzor do horní části obrazovky"

  "Edit Menu: Move multicursors down one line"
  "Nabídka úpravy: Přesunout multicursors o jeden řádek dolů"

  "Edit Menu: Move multicursors left one line"
  "Nabídka úpravy: Přesun multicursors vlevo jeden řádek"

  "Edit Menu: Move multicursors right one line"
  "Nabídka úpravy: Přesun multicursors právě jeden řádek"

  "Edit Menu: Move multicursors up one line"
  "Nabídka úpravy: Přesunout multicursors o jeden řádek nahoru"

  "Edit Menu: Paste and format text from clipboard"
  "Nabídka úpravy: Vkládání a formátování textu ze schránky"

  "Edit Menu: Paste text from clipboard"
  "Nabídka úpravy: Vložení textu ze schránky"

  "Edit Menu: Redo"
  "Úprava Menu: znovu:"

  "Edit Menu: Reload snippets"
  "Nabídka úpravy: Reload fragmenty"

  "Edit Menu: Reload template information"
  "Nabídka úpravy: Znovu načíst informace o šabloně"

  "Edit Menu: Replace line with script"
  "Nabídka úpravy: Nahradit řádek skriptu"

  "Edit Menu: Select all text"
  "Nabídka úpravy: Vyberte všechen text"

  "Edit Menu: Set indent mode to IND"
  "Nabídka úpravy: Nastavte režim odsazení na IND"

  "Edit Menu: Set indent mode to IND+"
  "Nabídka úpravy: Nastavte režim odsazení na IND +"

  "Edit Menu: Set indent mode to OFF"
  "Nabídka úpravy: Nastavte odsazení režim off"

  "Edit Menu: Set user bindings to global bindings"
  "Nabídka úpravy: Nastavení uživatele vazeb na globální vazby"

  "Edit Menu: Set user preferences to global preferences"
  "Nabídka úpravy: Nastavit uživatelské předvolby na globální nastavení"

  "Edit Menu: Toggle case of current character"
  "Nabídka úpravy: Velká písmena aktuálního znaku"

  "Edit Menu: Toggle comment"
  "Nabídka úpravy: Přepínač komentář"

  "Edit Menu: Undo"
  "Úprava Menu: zpět"

  "Edit Menu: Unindent selected text"
  "Nabídka úpravy: Zrušit odsazení vybraného textu"

  "Edit Menu: View base preferences file"
  "Menu úpravy: Soubor základních předvoleb zobrazení"

  "Edit Menu: View global menu bindings"
  "Nabídka úpravy: Zobrazení nabídka vazby"

  "Edit Session - Global"
  "Upravit relace - globální"

  "Edit Session - Language"
  "Upravit relace - jazyk"

  "Edit User"
  "Přidat Uživatele"

  "Edit User - Global"
  "Upravit uivatelské - globální"

  "Edit User - Language"
  "Upravit uivatelské - jazyk"

  "Enumeration"
  "Výčet"

  "File"
  "Soubor"

  "File Contents"
  "Obsah souboru"

  "File Menu: Change working directory"
  "Nabídka soubor: Změnit pracovní adresář"

  "File Menu: Close all tabs"
  "Nabídka soubor: Zavřít všechny karty"

  "File Menu: Close current tab"
  "Nabídka soubor: Zavřít současnou kartu"

  "File Menu: Delete current file"
  "Nabídka soubor: Odstranit aktuální soubor"

  "File Menu: Duplicate current file"
  "Nabídka soubor: Duplicitní aktuální soubor"

  "File Menu: Favorite file"
  "Nabídka soubor: Oblíbený soubor"

  "File Menu: Lock file"
  "Nabídka soubor: Soubor se zámkem"

  "File Menu: New file"
  "Nabídka soubor: Nový soubor"

  "File Menu: New file from template"
  "Nabídka soubor: Nový soubor šablony"

  "File Menu: New window"
  "Nabídce soubor: Nové okno"

  "File Menu: Open Favorite"
  "Nabídka soubor: Otevřené oblíbené"

  "File Menu: Open Recent"
  "Nabídka soubor: Otevřít nedávný"

  "File Menu: Open directory"
  "Nabídka soubor: Open directory"

  "File Menu: Open file"
  "Nabídka soubor: Otevřený soubor"

  "File Menu: Quit application"
  "Nabídka soubor: Ukončit aplikaci"

  "File Menu: Rename current file"
  "Nabídka soubor: Přejmenovat aktuální soubor"

  "File Menu: Reopen current file"
  "Soubor Menu: Současný soubor znovu otevřete"

  "File Menu: Save all files"
  "Nabídka soubor: Uložte všechny soubory"

  "File Menu: Save file"
  "Soubor Menu: Soubor uložte"

  "File Menu: Save file as"
  "Nabídka soubor: Uložit soubor jako"

  "File Menu: Save file as template"
  "Nabídka soubor: Uložit soubor jako šablonu"

  "File Menu: Save selected lines"
  "Nabídka soubor: Uložit vybrané řádky"

  "File Menu: Set current file line ending to CR for Classic Mac"
  "Nabídka soubor: Nastavte aktuální řádek souboru končí na CR pro klasický Mac"

  "File Menu: Set current file line ending to CRLF for Windows"
  "Nabídka soubor: Nastavte aktuální řádek souboru končí CRLF pro Windows"

  "File Menu: Set current file line ending to LF for Unix"
  "Nabídka soubor: Nastavte aktuální řádek souboru končí na LF pro Unix"

  "File Menu: Show file difference"
  "Nabídka soubor: Show souboru rozdílu"

  "File Menu: Unfavorite file"
  "Nabídce soubor: Unfavorite soubor"

  "File Menu: Unlock file"
  "Nabídka soubor: Odemknutí souboru"

  "Find In Files"
  "Najít v souborech"

  "Find Matching Pair"
  "Najít odpovídající dvojice"

  "Find Menu: Append next occurrence"
  "Najít Menu: Připojit další výskyt"

  "Find Menu: Create marker at current line"
  "Najít Menu: Vytvoření značky na aktuálním řádku"

  "Find Menu: Find"
  "Najít Menu: najít"

  "Find Menu: Find and Replace"
  "Nabídky Hledat: Hledat a nahradit"

  "Find Menu: Find in files"
  "Najít Menu: Najít v souborech"

  "Find Menu: Find matching character pair"
  "Najít Menu: Najít odpovídající dvojice znaků"

  "Find Menu: Find next occurrence"
  "Najít Menu: Najít následující výskyt"

  "Find Menu: Find previous occurrence"
  "Najít Menu: Najít předchozí výskyt"

  "Find Menu: Goto next difference"
  "Menu najít: Další rozdíl Goto"

  "Find Menu: Goto previous difference"
  "Najít Menu: Goto předchozí rozdíl"

  "Find Menu: Jump backward"
  "Najít Menu: Skok vzad"

  "Find Menu: Jump forward"
  "Najít Menu: Skok vpřed"

  "Find Menu: Jump to line"
  "Najít Menu: Přejít na řádek"

  "Find Menu: Remove all markers"
  "Najít Menu: Odebrat všechny značky"

  "Find Menu: Remove marker from current line"
  "Najít Menu: Odstranit značku z aktuálního řádku"

  "Find Menu: Select all occurrences"
  "Najít Menu: Vybrat všechny výskyty"

  "Find Menu: Show selected line change"
  "Najít Menu: Show vybrané linie změna"

  "Find and Replace"
  "Najít a nahradit"

  "Format Text"
  "Formát textu"

  "From Clipboard"
  "Ze schránky"

  "Goto Last Tab"
  "Jdi Last Tab"

  "Goto Next Tab"
  "Jdi na Další Tab"

  "Goto Other Pane"
  "Jdi Ostatní Pane"

  "Goto Previous Tab"
  "Jdi na předchozí Tab"

  "Help"
  "Nápověda"

  "Help Menu: About TKE"
  "Nabídka Nápověda: O TKE"

  "Help Menu: Check for update"
  "Nabídka Nápověda: Zjišťovat aktualizace"

  "Help Menu: Send bug report"
  "Nabídka Nápověda: Odeslat hlášení o chybě"

  "Help Menu: Send feedback"
  "Nabídka Nápověda: Odeslat názor"

  "Help Menu: View user guide"
  "Nabídka Nápověda: Zobrazit uživatelská příručka"

  "Hide Console"
  "Skrýt konzole"

  "Hide Line Numbers"
  "Skrýt čísla řádek"

  "Hide Marker Map"
  "Skrýt značková mapa"

  "Hide Meta Characters"
  "Skrýt znaky Meta"

  "Hide Sidebar"
  "Skrýt Sidebar"

  "Hide Status Bar"
  "Skrýt Status Bar"

  "Hide Tab Bar"
  "Skrýt liště"

  "Indent"
  "Zvětšit odsazení"

  "Indent Off"
  "Odsadit vypnuto"

  "Indentation"
  "Odsazení"

  "Insert"
  "Vložit"

  "Install"
  "Instalovat"

  "Join Lines"
  "Čáry spojení"

  "Jump Backward"
  "Skok zp?t"

  "Jump Forward"
  "Skok vp?ed"

  "Jump To Line"
  "Přejít na řádek"

  "Launcher"
  "spouštěč"

  "Line Above Current"
  "Linka nad aktuální"

  "Line Below Current"
  "Linka pod aktuální"

  "Line Ending"
  "Poslední řádek"

  "Line Number"
  "Číslo řádku"

  "Line Numbering"
  "Číslování řádků"

  "Lock"
  "Uzamknout"

  "Lower Case"
  "Malá písmena"

  "Markers"
  "Značky"

  "Menu Bindings"
  "Vázání Menu"

  "Menus: About TKE"
  "Menu: O TKE"

  "Merge Panes"
  "Slou?it podokna"

  "Move Cursors Down"
  "Kurzory dolů"

  "Move Cursors Left"
  "Přesunout doleva kurzory"

  "Move Cursors Right"
  "Přesunout doprava kurzory"

  "Move Cursors Up"
  "Kurzory nahoru"

  "Move to First Line"
  "Přesunutí do prvního řádku"

  "Move to Last Line"
  "Přesun do posledního řádku"

  "Move to Line End"
  "Přesunout na konec řádku"

  "Move to Line Start"
  "Přesunout řádek Start"

  "Move to Next Page"
  "Přesunutí na další stránku"

  "Move to Next Word"
  "Přesun do dalšího slova."

  "Move to Previous Page"
  "Přesunutí na předchozí stránku"

  "Move to Previous Word"
  "Přesun na předchozí slovo"

  "Move to Screen Bottom"
  "Přesunout do dolní části obrazovky"

  "Move to Screen Middle"
  "Přesunout na obrazovku střední"

  "Move to Screen Top"
  "Přesunout na obrazovku nahoru"

  "New From Template"
  "Nový ze šablony"

  "New Window"
  "New Window"

  "Next Difference"
  "Dalí rozdíl"

  "Open Directory"
  "Otevřít adresář"

  "Open Favorite"
  "Otevřená Oblíbené"

  "Open File"
  "Volný sloupec"

  "Open Recent"
  "Otevřít poslední"

  "Paste"
  "Pasta"

  "Paste and Format"
  "Vložit a Formát"

  "Plugins"
  "Plugin"

  "Plugins Menu: Create new plugin"
  "Plugins Menu: Vytvořit nový plugin"

  "Plugins Menu: Install plugin"
  "Pluginů Menu: Plugin instalace"

  "Plugins Menu: Reload all plugins"
  "Plugins Menu: Znovu načíst všechny pluginy"

  "Plugins Menu: Uninstall plugin"
  "Plugins Menu: Odinstalovat modul"

  "Preferences"
  "Preference"

  "Previous Difference"
  "P?edchozí rozdíl"

  "Profiling Report Sorted By"
  "Profilování sestavu setříděnou podle"

  "Profiling started"
  "Profilování začal"

  "Profiling stopped"
  "Profilování se zastavil"

  "Quit"
  "ukončit"

  "Redo"
  "Zrušit vrácení akce"

  "Relative"
  "Relativní"

  "Reload"
  "Načíst znovu"

  "Remove All Markers"
  "Odebrat vechny zna?ky"

  "Remove From Current Line"
  "Odebrat z aktuálního ?ádku"

  "Reopen File"
  "Znovu otevřete soubor"

  "Replace Line With Script"
  "Nahradit ?ádek skriptu"

  "Reset User to Base"
  "Obnovit uživatelské základny"

  "Restart TKE"
  "Restartujte TKE"

  "Run BIST"
  "Spustit BIST"

  "Save All"
  "Uložit všechny"

  "Save As Template"
  "Uložit jako šablonu"

  "Save Current"
  "Uloit aktuální"

  "Save Selection As"
  "Uložit výběr jako"

  "Select All"
  "Vybrat vše"

  "Select All Occurrences"
  "Vybrat vechny výskyty"

  "Select Next Occurrence"
  "Vybrat dalí výskyt"

  "Select Previous Occurrence"
  "Vybrat p?edchozí výskyt"

  "Send Bug Report"
  "Odeslat hlášení o chybě"

  "Send Feedback"
  "Odeslat názor"

  "Sessions"
  "Návt?vy"

  "Sessions Menu: Close current session"
  "Relace Menu: Aktuální relaci ukončit"

  "Sessions Menu: Delete session"
  "Relací Menu: Odstranit relace"

  "Sessions Menu: Save current session"
  "Sessions Menu: Uložit aktuální relaci"

  "Sessions Menu: Save sessions as"
  "Sessions Menu: Ukládání sezení jako"

  "Sessions Menu: Switch to session"
  "Sessions Menu: Přepněte na sezení"

  "Set Syntax"
  "Nastavit syntaxe"

  "Set Theme"
  "Set Theme"

  "Set User to Global"
  "Nastavit uživatele do globální"

  "Show Console"
  "Zobrazit Console"

  "Show Diagnostic Logfile"
  "Zobrazit diagnostického protokolu"

  "Show File Difference"
  "Zobrazit soubor rozdíl"

  "Show Last Profiling Report"
  "Zobrazit poslední profilování zprávu"

  "Show Line Numbers"
  "Zobrazovat čísla řádků"

  "Show Marker Map"
  "Ukázat značková mapa"

  "Show Meta Characters"
  "Zobrazit znaky Meta"

  "Show Selected Line Change"
  "Zobrazit vybranou linku zm?nu"

  "Show Sidebar"
  "Zobrazit Sidebar"

  "Show Status Bar"
  "Show Status Bar"

  "Show Tab Bar"
  "Zobrazit Tab Bar"

  "Smart Indent"
  "Chytré odsazení"

  "Snippet"
  "úryvek"

  "Snippets"
  "Snippet"

  "Sort Tabs"
  "Seřadit Záložky"

  "Start Profiling"
  "Začněte profilování"

  "Stop Profiling"
  "Zastavit profilování"

  "Switch To"
  "P?epnout do"

  "Tabs"
  "Karty"

  "Templates"
  "Šablony"

  "Text Between Character"
  "Text mezi znaky"

  "Text Menu: Insert enumeration"
  "Menu textu: Vložit – výčet"

  "Title Case"
  "Všechna první velká"

  "Toggle Case"
  "Zaměnit malá a Velká"

  "Toggle Comment"
  "P?epnout komentá?"

  "Tools"
  "nástroje"

  "Tools Menu: Disable Vim mode"
  "Nabídka nástroje: Zakázat režim, Vim"

  "Tools Menu: Enable Vim mode"
  "Nabídka nástroje: Povolit režim Vim"

  "Tools Menu: Restart TKE"
  "Nabídka nástroje: Restart TKE"

  "Tools Menu: Run BIST"
  "Nabídka nástroje: Spuštění BIST"

  "Tools Menu: Run theme editor"
  "Nabídka Nástroje: Spusťte editor téma"

  "Tools Menu: Show diagnostic logfile"
  "Nabídka nástroje: Zobrazení diagnostického protokolu"

  "Tools Menu: Show last profiling report"
  "Nabídka nástroje: Zobrazit poslední zprávy o profilování"

  "Tools Menu: Start profiling"
  "Nabídka nástroje: Spustit profilování"

  "Tools Menu: Stop profiling"
  "Nabídka nástroje: Zastavit, profilování"

  "Transform"
  "Transformovat"

  "Undo"
  "Vrátit zpět akci"

  "Unindent"
  "Unindent"

  "Uninstall"
  "Odinstalovat"

  "Unix"
  "systém UNIX"

  "Unlock"
  "Odemknout"

  "Upper Case"
  "Majuskule"

  "User Guide"
  "Uživatelská příručka"

  "View"
  "Náhled"

  "View Base"
  "Zobrazit základnu"

  "View Global"
  "Zobrazit globální"

  "View Menu: Absolute line numbering"
  "Nabídka Zobrazit: Absolutní číslování"

  "View Menu: Display text information"
  "Zobrazit Menu: Zobrazí textové informace"

  "View Menu: Goto last tab"
  "Nabídka Zobrazit: Goto poslední karta"

  "View Menu: Goto next tab"
  "Nabídka Zobrazit: Goto další kartu"

  "View Menu: Goto other pane"
  "Nabídka Zobrazit: Goto další podokno"

  "View Menu: Goto previous tab"
  "Nabídka Zobrazit: Goto předchozí kartu"

  "View Menu: Hide console"
  "Nabídka Zobrazit: Skrýt konzole"

  "View Menu: Hide line numbers"
  "Nabídka Zobrazit: Skrýt čísla řádků"

  "View Menu: Hide marker map"
  "Nabídka Zobrazit: Skrýt značková mapa"

  "View Menu: Hide meta characters"
  "Nabídka Zobrazit: Skrýt znaky meta"

  "View Menu: Hide sidebar"
  "Nabídka Zobrazit: Skrýt postranní panel"

  "View Menu: Hide status bar"
  "Nabídka Zobrazit: Skrýt stavový řádek"

  "View Menu: Hide tab bar"
  "Nabídka Zobrazit: Skrýt lištu karet"

  "View Menu: Merge panes"
  "Nabídka Zobrazit: Sloučení podoken"

  "View Menu: Move to other pane"
  "Nabídka Zobrazit: Přechod na další podokno"

  "View Menu: Relative line numbering"
  "Nabídka Zobrazit: Relativní řádek číslování"

  "View Menu: Show console"
  "Nabídka Zobrazit: Show konzole"

  "View Menu: Show line numbers"
  "Nabídka Zobrazit: Zobrazovat čísla řádků"

  "View Menu: Show marker map"
  "Nabídka Zobrazit: Show značková mapa"

  "View Menu: Show meta characters"
  "Nabídka Zobrazit: Show meta znaky"

  "View Menu: Show sidebar"
  "Nabídka Zobrazit: Show kredenc"

  "View Menu: Show status bar"
  "Zobrazit Menu: Zobrazit stavový řádek"

  "View Menu: Show tab bar"
  "Nabídka Zobrazit: Zobrazovat lištu karet"

  "View Menu: Sort tabs"
  "Nabídka Zobrazit: Seřadit karty"

  "View Menu: Toggle split view mode"
  "Nabídka Zobrazit: Přepnout rozdělené zobrazení"

  "Vim Mode"
  "Režim Vim"

  "Whitespace Backward"
  "Whitespace dozadu"

  "Whitespace Forward"
  "Prázdný znak vpřed"

  "Windows"
  "Windows"

}

# plugins.tcl
msgcat::mcmset cs {

  "Always grant from developer"
  "Vždy grant od tohoto vývojáře"

  "ERROR"
  "CHYBA"

  "ERROR:  Plugin name already exists"
  "Chyba: Plugin názvem již existuje"

  "ERROR:  Plugin name is not valid (only alphanumeric and underscores are allowed)"
  "ERROR: Plugin název není platný (pouze alfanumerické a podtržítka jsou povoleny)"

  "ERROR:  Unable to create plugin directory"
  "CHYBA: Nelze vytvořit plugin adresář"

  "ERROR:  Unable to write plugin files"
  "Chyba: Nelze zapsat plugin soubory"

  "Enter plugin name"
  "Zadejte plugin jméno"

  "Grant"
  "Grant"

  "Grant permssion?"
  "Grant permssion?"

  "OK"
  "OK"

  "Plugin Errors"
  "Plugin chyby"

  "Plugin Trust Requested"
  "Plugin Důvěra Požadované"

  "Plugin installed"
  "Plugin nainstalovaný"

  "Plugin requires permission to view or modify your system."
  "Plugin vyžaduje oprávnění k zobrazení nebo změnit váš systém."

  "Plugin uninstalled"
  "Plugin odinstaloval"

  "Plugins successfully reloaded"
  "Pluginy úspěšně reloaded"

  "Reject"
  "Odmítnout"

  "Syntax errors found in selected plugins"
  "Syntaktické chyby nalezené ve vybraných pluginů"

}

# search.tcl
msgcat::mcmset cs {

  "No files found in specified directories"
  "Žádné soubory v uvedených adresářích"

  "No search results found"
  "Nic se nenašlo"

  "Search wrapped to beginning of file"
  "Hledat zabalené na začátku souboru"

  "Search wrapped to end of file"
  "Hledat zabalené do konce souboru"

  "substitutions done"
  "substituce hotovo"

}

# sessions.tcl
msgcat::mcmset cs {

  "Save session?"
  "Uložit relaci"

  "Session state will be lost if not saved"
  "Stavu relace budou ztraceny, pokud nejsou uloženy"

}

# sidebar.tcl
msgcat::mcmset cs {

  "Add Parent Directory"
  "Nadřazená složka"

  "Close Directory Files"
  "Zavřít Directory soubory"

  "Copy Pathname"
  "Kopírovat cestu"

  "Delete directories?"
  "Odstranění adresáře?"

  "Delete directory?"
  "Smazat adresář?"

  "Delete file?"
  "Smazat soubor?"

  "Delete files?"
  "Odstranit soubory?"

  "Directory Name:"
  "Název adresáře:"

  "Folder Name:"
  "Název sloky:"

  "Image displayed in sidebar to indicate that a file is currently opened in an editing buffer."
  "Obrazy zobrazené v bočním panelu, čímž naznačují, že soubor je aktuálně otevřen v editačním vyrovnávací paměti."

  "Make Current Working Directory"
  "Ujistěte se aktuální pracovní adresář"

  "New Directory"
  "Nový adresář"

  "Open Directory Files"
  "Open Directory soubory"

  "Refresh Directory Files"
  "Obnovit soubory adresáře"

  "Remove Parent from Sidebar"
  "Odstranit Parent z postranního panelu"

  "Remove from Sidebar"
  "Odebrat z postranního panelu"

  "Show Difference"
  "Zobrazit rozdíl"

}

# snippets.tcl
msgcat::mcmset cs {

  "Snippet: *"
  "úryvek"

}

# syntax.tcl
msgcat::mcmset cs {

  "Syntax"
  "Syntax"

  "Syntax error in syntax file"
  "Syntaktická chyba v syntaxi souboru"

}

# templates.tcl
msgcat::mcmset cs {

  "Template"
  "Šablona"

  "Template Name"
  "Jméno šablony"

  "deleted"
  "smazané"

  "saved"
  "Černá ovce"

}

# theme.tcl
msgcat::mcmset cs {

  "Background (trough) color used in the sidebar scrollbar."
  "Souvislosti (žlábek), barvy použité v postranním panelu posuvníku."

  "Background (trough) color used in the text scrollbars."
  "Souvislosti (žlábek), barvy použité v textu posuvníky."

  "Background color for all sidebar items that are not selected."
  "Barva pozadí pro všechny postranní položky, které nejsou vybrány."

  "Background color for all sidebar items that are selected."
  "Barva pozadí pro všechny položky postranního panelu, které jsou vybrány."

  "Background color in difference viewer that shows added lines."
  "Barva pozadí v rozdílu prohlížeč, který ukazuje přidané linky."

  "Background color in difference viewer that shows deleted lines."
  "Barva pozadí v rozdílu prohlížeč, který ukazuje smazané linky."

  "Background color of insertion cursor and background marker colors."
  "Barva pozadí vložení kurzoru a zázemí značkovacích barev."

  "Background color of the editing buffer."
  "Barva pozadí pro úpravy vyrovnávací paměti."

  "Background color to display when a button-like ttk widget is pressed."
  "Barva pozadí se zobrazí při stisknutí tlačítka podobný TTK widget."

  "Background color to use for selected text."
  "Barva pozadí použít pro vybraný text."

  "Background color used for all other tabs that are not the current/active tab in the tabbar."
  "Barva pozadí používají pro všechny ostatní karty, které nejsou aktuální / aktivní záložka v liště karet."

  "Background color used for the current/active menu item."
  "Barva pozadí použitý pro aktuální / aktivní položku menu."

  "Background color used for the current/active tab in the tabbar."
  "Barva pozadí používají pro stávající / aktivní kartu v liště karet."

  "Background color used in highlighted text."
  "Barva pozadí používají v zvýrazněném textu."

  "Background color used in menus."
  "Barva pozadí používají v nabídkách."

  "Background color used in the tabbar area."
  "Barva pozadí používané v tabbar oblasti."

  "Color of border drawn around active editing buffer."
  "Barva rámu okolo aktivní pro úpravy vyrovnávací paměti."

  "Color of ttk entry widget text border when the entry has keyboard focus."
  "Barva zadávání TTK widgetu textu okraje, když záznam má fokus klávesnice."

  "Color used to draw the warning width line in the editing buffer (as well as the line separating the gutter from the editing buffer)."
  "Barva slouží ke kreslení šířky varování řádek v editační vyrovnávací paměti (stejně jako čáru oddělující okap z vyrovnávací paměti pro úpravy)."

  "Default 'darkcolor' for all ttk widgets."
  "Default &quot;darkcolor&quot; pro všechny TTK widgetů."

  "Default background color to use for all ttk widgets that are in a disabled state."
  "Výchozí barva pozadí použít pro všechny TTK widgety, které jsou v zakázaném stavu."

  "Default background color to use for all ttk widgets when the mouse cursor hovers over the widget."
  "Výchozí barva pozadí použít pro všechny TTK widgetů, když je kurzor myši nad widget."

  "Default background color to use for all ttk widgets."
  "Výchozí barva pozadí použít pro všechny TTK widgetů."

  "Default border color for all ttk widgets."
  "Výchozí barva hranice všech TTK widgetů."

  "Default color for non-syntax highlighted text."
  "Výchozí barva pro non-syntax zvýrazněný text."

  "Default foreground text color to use for all ttk widgets that are in a disabled state."
  "Výchozí barvu popředí textu použít pro všechny TTK widgety, které jsou v zakázaném stavu."

  "Default foreground text color to use for all ttk widgets."
  "Výchozí barvu popředí textu použít pro všechny TTK widgetů."

  "Determines the number of grips strips to display in the grip area between resizable panes."
  "Určuje počet uzlů proužky zobrazit v úchopové oblasti mezi měnit velikost tabulemi."

  "Determines the thickness of the grip area between resizable panes."
  "Určuje tloušťku uchopení prostoru mezi tabulemi měnit velikost."

  "ERROR:  Unable to read"
  "Chyba: Nelze přečíst"

  "Foreground (slider) color used in the sidebar scrollbar."
  "Popředí (slider), barvy použité v postranním panelu posuvníku."

  "Foreground (slider) color used in the text scrollbars."
  "Popředí (slider), barvy použité v textu posuvníky."

  "Foreground color used in menu items with checks or buttons."
  "Barva popředí používaná v položkách nabídky s šeky nebo tlačítka."

  "Foreground text color for strings."
  "Popředí barvu textu pro řetězce."

  "Foreground text color to use for all miscellaneous1 labeled text."
  "Popředí textu barva se použije pro všechny miscellaneous1 označeny textem."

  "Foreground text color to use for all miscellaneous2 labeled text."
  "Popředí textu barva se použije pro všechny miscellaneous2 označeny textem."

  "Foreground text color to use for all miscellaneous3 labeled text."
  "Popředí textu barva se použije pro všechny miscellaneous3 označeny textem."

  "Foreground text color to use for comments."
  "Popředí Barva textu používat k připomínkám."

  "Foreground text color to use for displaying line numbers."
  "Popředí Barva textu použít pro zobrazování čísla řádků."

  "Foreground text color to use for displaying numbers."
  "Popředí Barva textu použít pro zobrazování čísel."

  "Foreground text color to use for language-specific keywords."
  "Popředí Barva textu použít pro specifické pro jazyk klíčová slova."

  "Foreground text color to use for language-specific punctuation."
  "Popředí Barva textu použít pro konkrétní jazyk interpunkce."

  "Foreground text color to use for meta syntax."
  "Popředí Barva textu použít pro meta syntaxi."

  "Foreground text color to use for precompiler syntax."
  "Popředí Barva textu použít pro prekompilátorem syntaxi."

  "Foreground text color to use for selected text."
  "Popředí textu barva se použije pro vybraný text."

  "Foreground text color used for all other tabs that are not the current/active tab in the tabbar."
  "Pro všechny ostatní karty, které nejsou aktuální/aktivní kartu v tabbar barvu popředí textu."

  "Foreground text color used for menus item that are disabled."
  "Barva popředí textu používá pro menu položky, které jsou zakázány."

  "Foreground text color used for the current/active menu item."
  "Barva popředí textu použit pro aktuální / aktivní položku menu."

  "Foreground text color used for the current/active tab in the tabbar."
  "Barva popředí textu pro proud/aktivní kartu v klepna."

  "Foreground text color used in menus."
  "Barva popředí Text použitý v nabídkách."

  "Foreground text/image color used in tabbar and tabs."
  "Barva popředí text / obraz používá v liště karet a karet."

  "Images"
  "Obrázky"

  "Maximum thickness of the text scrollbar when it is active."
  "Maximální tloušťka textu posuvníku, kdy je aktivní."

  "Maximum thickness of the text scrollbars when they are active."
  "Maximální tloušťky textu posuvníky, když jsou aktivní."

  "Menu Options"
  "Nastavení menu"

  "Menu relief value."
  "Úleva hodnota Menu."

  "Pixel height of the tabbar widget."
  "Výška pixelu tabbar widgetu."

  "Relief used in drawing the tabs."
  "Reliéf používá v kreslení karty."

  "Relief value of the sidebar area."
  "Reliéf hodnota sidebar oblasti."

  "Sidebar Options"
  "Nastavení sidebaru"

  "Sidebar Scrollbar Options"
  "Sidebar Možnosti scrollbar"

  "Specifies the color to display around the sidebar when the sidebar does not have the focus."
  "Určuje barvu, která se zobrazí po postranním panelu, když postranní panel nemá fokus."

  "Specifies the color to display around the sidebar when the sidebar has the focus."
  "Určuje barvu, která se zobrazí po postranní panel, když postranní panel má fokus."

  "Specifies the default background color to use for text that is selected in a standard ttk widget (this does not include the editing buffer)."
  "Určuje výchozí barvu pozadí použít pro text, který je vybrán ve standardním TTK widgetu (toto nezahrnuje úpravu vyrovnávací paměti)."

  "Specifies the default foreground text color to use for text that is selected in a standard ttk widget (this does not include the editing buffer)."
  "Určuje výchozí barvu popředí textu použít pro text, který je vybrán ve standardním TTK widgetu (toto nezahrnuje úpravu vyrovnávací paměti)."

  "Specifies the default relief to use when drawing ttk widgets."
  "Určuje výchozí úlevu pro použití při kreslení TTK widgety."

  "Specifies the disclosure image style to use in the sidebar."
  "Určuje styl zveřejňování obrazu pro použití v postranním panelu."

  "Specifies the pixel thickness of the highlight line."
  "Určuje tloušťku pixelů zvýraznění linie."

  "Syntax Colors"
  "Syntaxe Barvy"

  "Tab Options"
  "Možnosti Karta"

  "Text Scrollbar Options"
  "Textové scrollbar Možnosti"

  "Text color for all sidebar items that are not selected."
  "Barva textu pro všechny postranní položky, které nejsou vybrány."

  "Text color for all sidebar items that are selected."
  "Barva textu pro všechny položky postranního panelu, které jsou vybrány."

  "ttk Widget Colors"
  "TTK Widget Barvy"

}

# themer.tcl
msgcat::mcmset cs {

  "   Show All"
  "Zobrazit vše"

  "   Show Category"
  "Zobrazit kategorii"

  "   Show Color"
  "Show Barva"

  "   Show Selected Option"
  "Show vybrána možnost"

  "   Show Selected Value"
  "Show zvolená hodnota"

  "Categories"
  "Kategorie"

  "Change Base Color"
  "Change Color Základní"

  "Choose Theme"
  "Vyberte si téma"

  "Custom Directory"
  "Vlastní adresář"

  "Custom..."
  "Vlastní..."

  "Delete swatch?"
  "Smazat vzorník?"

  "Description"
  "Popis"

  "Details"
  "Dataily"

  "Done"
  "Hotovo"

  "Export"
  "Exportovat"

  "GIF Photo"
  "GIF foto"

  "Import"
  "Dovoz"

  "Import BMP Data"
  "Importovat data"

  "Import BMP Mask"
  "Importovat BMP Mask"

  "Import Error"
  "Chyba při importu"

  "Import Theme File"
  "Importovat Theme Soubor"

  "Installation Directory"
  "Instalační adresář"

  "Modifications"
  "Pozměňovací návrhy"

  "One-Color Bitmap"
  "One-Color Bitmap"

  "Preview"
  "Náhled"

  "Relief: "
  "Reliéf"

  "Save As:"
  "Uložit jako"

  "Save theme changes?"
  "Uložit změny téma?"

  "Select Directory"
  "Vybrat adresář"

  "Swatch"
  "Swatch"

  "Swatch Colors"
  "Swatch Barvy"

  "Table Filters"
  "Tabulka Filtry"

  "The current theme has unsaved changes"
  "Aktuální téma má neuložené změny"

  "Tree Style: "
  "Tree Style:"

  "Two-Color Bitmap"
  "Dva-Color Bitmap"

  "User Directory"
  "Uživatel Directory"

  "Value"
  "Hodnota"

  "Value: "
  "Hodnota:"

}

# themes.tcl
msgcat::mcmset cs {

  "Theme"
  "Šablona"

  "Theme:*"
  "Šablona"

}

# tke.tcl
msgcat::mcmset cs {

  "Import TKE theme?"
  "Dovoz TKE téma?"

  "Import TextMate theme?"
  "Importovat TextMate téma?"

}

# tkedat.tcl
msgcat::mcmset cs {

  "Unable to read"
  "Nelze přečíst"

}

# vim.tcl
msgcat::mcmset cs {

  "File format unrecognized"
  "Formát souboru nebyl rozpoznán"

  "Filename directory does not exist"
  "Název souboru adresář neexistuje."

  "Illegal modelines value"
  "Ilegální ModeLine hodnota"

  "Shiftwidth value is not an integer"
  "Shiftwidth hodnota není celé číslo"

  "Tabstop value is not an integer"
  "TabStop hodnota není celé číslo"

}

# General
msgcat::mcmset cs {

  "Cancel"
  "Storno"

  "Close"
  "Zavřít"

  "Delete"
  "Odstranit"

  "Duplicate"
  "Duplicita"

  "Favorite"
  "oblíbená položka"

  "File Name:"
  "&Jméno souboru:"

  "Find"
  "Find"

  "Move to Other Pane"
  "Přesunout do jiné tabule"

  "New File"
  "Nový soubor"

  "None"
  "Žádné"

  "Open"
  "Open"

  "Rename"
  "Odebrat"

  "Save"
  "Uložit"

  "Save As"
  "Uložit jako"

  "Split View"
  "Rozd?lený panel"

  "Theme Editor"
  "Editor téma"

  "Unable to write"
  "Nelze zapisovat"

  "Unfavorite"
  "Unfavorite"

}

