# api.tcl
msgcat::mcmset da {

  "Argument list to api::add_file was not an even key/value pair"
  "Argument liste til api :: add_file ikke var en selv nøgle / værdi par"

}

# bgproc.tcl
msgcat::mcmset da {

  "Unable to run system command (%s)"
  "Ikke køre systemet kommando (% s)"

}

# diff.tcl
msgcat::mcmset da {

  "    End: "
  "Slutning"

  "    Start: "
  "Start"

  "Enter difference command"
  "Angiv forskel kommando"

  "Enter starting file"
  "Indtast start fil"

  "Update"
  "Opdater"

}

# gui.tcl
msgcat::mcmset da {

  "%d substitutions done"
  "%d erstatninger udført"

  "%s, Line: %d, Column: %d"
  "% S, Line:% d, kolonne:% d"

  "Close All Tabs"
  "Luk alle faneblade"

  "Close Other Tab(s)"
  "Luk Other Tab (r)"

  "Close Other*"
  "Luk de andre faneblade"

  "Close Tab"
  "Luk faneblad"

  "Copyright %d-%d"
  "Copyright% d-% d"

  "Delete tab?"
  "Slet fane?"

  "Developer:"
  "Udvikler"

  "Email:"
  "E-mail:"

  "Error"
  "Fejl"

  "Favorited"
  "Favoriseret"

  "File attribute (%s) does not exist"
  "Filattribut (% s) eksisterer ikke"

  "File index is out of range"
  "File indeks er uden for rækkevidde"

  "License:"
  "Licens"

  "Line: %d, Column: %d"
  "Line:% d, kolonne:% d"

  "Locked"
  "låst"

  "Move*"
  "bevæge"

  "Must be in multicursor mode to insert numbers"
  "Skal være i multicursor tilstand at indsætte tal"

  "No search results found"
  "Ingen resultater matcher din søgning!"

  "Release Type:"
  "Release Type:"

  "Reload file?"
  "Genindlæs fil"

  "Save request"
  "Spar anmodning"

  "Search wrapped to beginning of file"
  "Søg ombrydes til begyndelsen af filen"

  "Search wrapped to end of file"
  "Søg indpakket til slutningen af filen"

  "Show in Sidebar"
  "Vis i Sidebar"

  "Starting number:"
  "Starttal"

  "Tcl/Tk Version:"
  "Tcl/Tk Version:"

  "Total Lines: %d, Total Characters: %d"
  "Samlet Lines:% d, alt Tegn:% d"

  "Twitter:"
  "Twitter"

  "Unable to find current file (tab: %s)"
  "Kunne ikke finde aktuelle fil (fane:% s)"

  "Unable to successfully parse number string"
  "Ikke kan med held parse nummer streng"

  "Unable to write file"
  "Kunne ikke skrive filen"

  "Untitled"
  "Untitled"

  "Version:"
  "Udgave:"

}

# markers.tcl
msgcat::mcmset da {

  "Marker name:"
  "Markør navn:"

}

# menus.tcl
msgcat::mcmset da {

  "                                  Profiling Report Sorted By (%s)"
  "Profilering Rapport Sorteret efter (% s)"

  "About TKE"
  "Om TKE"

  "Align Cursors"
  "Juster markører"

  "All"
  "Alle"

  "Append Next Occurrence"
  "Føj næste forekomst"

  "Auto-Indent"
  "Automatisk indryk"

  "Check for Update"
  "Søg efter opdatering"

  "Clear All"
  "Ryd alt"

  "Close All"
  "Luk alle"

  "Close Current"
  "Luk strøm {0}"

  "Copy"
  "Kopier"

  "Create New..."
  "Opret ny"

  "Create at Current Line"
  "Oprette på nuværende linje"

  "Create..."
  "Opret"

  "Cut"
  "Klip"

  "Edit"
  "Rediger"

  "Edit Language"
  "Rediger sprog"

  "Edit Session - Global"
  "Redigere Session - globale"

  "Edit Session - Language"
  "Rediger Session - sprog"

  "Edit User"
  "Rediger bruger."

  "Edit User - Global"
  "Redigere bruger - globale"

  "Edit User - Language"
  "Redigere bruger - sprog"

  "Edit..."
  "Rediger..."

  "File"
  "Filer"

  "Find"
  "Søg"

  "Find In Files"
  "Find i filer..."

  "Find Matching Pair"
  "Finde matchende par"

  "Find and Replace"
  "Find og erstat"

  "Format Text"
  "Formatér tekst"

  "From Clipboard"
  "Fra klippebord"

  "Goto Last Tab"
  "Goto Last Tab"

  "Goto Next Tab"
  "Goto Next Tab"

  "Goto Other Pane"
  "Goto Anden Pane"

  "Goto Previous Tab"
  "Goto forrige fane"

  "Help"
  "Hjælp"

  "Hide Console"
  "Skjul Console"

  "Hide Line Numbers"
  "Skjul linjenumre"

  "Hide Meta Characters"
  "Skjule Meta tegn"

  "Hide Sidebar"
  "Skjul sidebjælke"

  "Hide Status Bar"
  "Skjul statuslinje"

  "Hide Tab Bar"
  "Skjul tab-linje"

  "Import TextMate Theme..."
  "Importere TextMate tema..."

  "Indent"
  "Indryk"

  "Indent Mode"
  "LED tilstand"

  "Indent Off"
  "LED slukket"

  "Insert Enumeration"
  "Indsæt optælling"

  "Insert Text"
  "Indsæt tekst"

  "Install..."
  "Installer"

  "Jump Backward"
  "Hoppe baglæns"

  "Jump Forward"
  "Spring frem"

  "Launcher"
  "Launcher"

  "Lock"
  "Lås"

  "Markers"
  "Markører"

  "Menu Bindings"
  "Menu Bindinger"

  "Menu Edit user snippets"
  "Menuen Rediger bruger snippets"

  "Menu: About TKE"
  "Menu: About TKE"

  "Menu: Align cursors"
  "Menu: Juster markører"

  "Menu: Append next occurrence"
  "Menu: Append næste forekomst"

  "Menu: Check for Update"
  "Menu: Søg efter opdatering"

  "Menu: Close all tabs"
  "Luk alle faneblade"

  "Menu: Close current session"
  "Menu: Luk aktuelle session"

  "Menu: Close current tab"
  "Luk dette faneblad"

  "Menu: Copy text"
  "Menu: Kopier tekst"

  "Menu: Create marker at current line"
  "Menu: Oprette markør på nuværende linje"

  "Menu: Create new plugin"
  "Menu: Opret ny plugin"

  "Menu: Create new theme"
  "Opret nyt tema..."

  "Menu: Cut text"
  "Menu: Cut tekst"

  "Menu: Delete session"
  "Menu: Slet session"

  "Menu: Disable Vim mode"
  "Menu: Disable Vim-tilstand"

  "Menu: Edit Tke theme"
  "Menu: Rediger Tke tema"

  "Menu: Edit language snippets"
  "Menu: Rediger sprog uddrag"

  "Menu: Edit session current language preferences"
  "Menu: Redigere session aktuelle sprogindstillinger"

  "Menu: Edit session global preferences"
  "Menu: Rediger globale sessionsindstillingerne"

  "Menu: Edit user current language preferences"
  "Menu: Redigere brugerens aktuelle sprogpræferencer"

  "Menu: Edit user global preferences"
  "Menu: Rediger globale brugerindstillinger"

  "Menu: Edit user menu bindings"
  "Menu: Rediger brugermenuskærmene bindinger"

  "Menu: Enable Vim mode"
  "Menu: Aktiver Vim-tilstand"

  "Menu: Favorite file"
  "Menu: Favorit fil"

  "Menu: Find"
  "Menu: Find"

  "Menu: Find and Replace"
  "Menu: Søg og erstat"

  "Menu: Find in files"
  "Find i filer"

  "Menu: Find matching character pair"
  "Menu: Find matchende tegn pair"

  "Menu: Find next occurrence"
  "Menu: Find næste forekomst"

  "Menu: Find previous occurrence"
  "Menu: Find forrige forekomst"

  "Menu: Format all text"
  "Menu: Formater al tekst"

  "Menu: Format selected text"
  "Menu: Format valgt tekst"

  "Menu: Goto last tab"
  "Menu: Goto sidste fane"

  "Menu: Goto next difference"
  "Menu: Goto næste forskellen"

  "Menu: Goto next tab"
  "Menu: Goto næste fane"

  "Menu: Goto other pane"
  "Menu: Goto anden rude"

  "Menu: Goto previous difference"
  "Menu: Goto tidligere forskel"

  "Menu: Goto previous tab"
  "Menu: Goto forrige fane"

  "Menu: Hide Line Numbers"
  "Menu: Skjul linjenumre"

  "Menu: Hide Tab Bar"
  "Menu: Hide Tab Bar"

  "Menu: Hide console"
  "Menu: Hide konsol"

  "Menu: Hide meta characters"
  "Menu: Skjule meta tegn"

  "Menu: Hide sidebar"
  "Menu: Hide sidebar"

  "Menu: Hide status bar"
  "Skjul statuslinje"

  "Menu: Import TextMate theme"
  "Menu: Import TextMate tema"

  "Menu: Indent selected text"
  "Menu: Led markeret tekst"

  "Menu: Insert enumeration"
  "Menu: Indsæt tælling"

  "Menu: Insert from clipboard"
  "Menu: Indsæt fra udklipsholder"

  "Menu: Insert snippet"
  "Menu: Indsæt kodestykke"

  "Menu: Install plugin"
  "Menu: Installer plugin"

  "Menu: Jump backward"
  "Menu: Hoppe baglæns"

  "Menu: Jump forward"
  "Menu: Hop fremad"

  "Menu: Lock file"
  "Menu: Lås fil"

  "Menu: Merge panes"
  "Menu: Flet ruder"

  "Menu: Move to other pane"
  "Menu: Flyt til en anden rude"

  "Menu: New file"
  "Menu: Ny fil"

  "Menu: Open Favorite"
  "Menu: Åben Favorit"

  "Menu: Open Recent"
  "Menu: Åbn nylige"

  "Menu: Open directory"
  "Menu: Åbn telefonbogen"

  "Menu: Open file"
  "Menu: Åbn fil"

  "Menu: Open session"
  "Menu: Åbn session"

  "Menu: Paste and format text from clipboard"
  "Menu: Indsæt og formatere tekst fra udklipsholder"

  "Menu: Paste text from clipboard"
  "Indsæt tekst fra udklipsholderen"

  "Menu: Quit application"
  "Menu: Afslut ansøgning"

  "Menu: Redo"
  "Menu: Redo"

  "Menu: Reload all plugins"
  "Menu: Opdater alle plugins"

  "Menu: Reload snippets"
  "Menu: Reload snippets"

  "Menu: Remove all markers"
  "Menu: Fjerne alle markører"

  "Menu: Remove marker from current line"
  "Menu: Fjerne markering fra aktuel linje"

  "Menu: Replace line with script"
  "Menu: Erstatningsslangen med script"

  "Menu: Restart tke"
  "Menu: Genstart tke"

  "Menu: Save all files"
  "Menu: Gem alle filer"

  "Menu: Save current session"
  "Gem nuværende session?"

  "Menu: Save file"
  "Menu: Gem filen"

  "Menu: Save file as"
  "Menu: Gem filen som"

  "Menu: Save sessions as"
  "Menu: Gem sessioner som"

  "Menu: Select all occurrences"
  "Menu: Vælg alle forekomster"

  "Menu: Select all text"
  "Markér al tekst"

  "Menu: Send Bug Report"
  "Menu: Send fejlrapport"

  "Menu: Send Feedback"
  "Menu: Send Feedback"

  "Menu: Set indent mode to IND"
  "Menu: Sæt led mode at IND"

  "Menu: Set indent mode to IND+"
  "Menu: Sæt led mode til IND +"

  "Menu: Set indent mode to OFF"
  "Menu: Sæt led mode til OFF"

  "Menu: Set user bindings to global bindings"
  "Menu: Indstil brugernes bindinger til globale bindinger"

  "Menu: Set user preferences to global preferences"
  "Menu: Indstil brugerindstillinger til globale præferencer"

  "Menu: Show Diagnostic Logfile"
  "Menu: Vis diagnostisk logfil"

  "Menu: Show Line Numbers"
  "Vis linjenumre"

  "Menu: Show Tab Bar"
  "Menu: Vis fanebladslinje"

  "Menu: Show console"
  "Menu: Vis konsol"

  "Menu: Show file difference"
  "Menu: Vis fil forskel"

  "Menu: Show last profiling report"
  "Menu: Vis seneste profilering rapport"

  "Menu: Show meta characters"
  "Menu: Vis meta tegn"

  "Menu: Show selected line change"
  "Menu: Vis valgt linje ændring"

  "Menu: Show sidebar"
  "Menu: Vis sidebjælke"

  "Menu: Show status bar"
  "Vis statuslinje"

  "Menu: Sort tabs"
  "Menu: Sorter faner"

  "Menu: Start profiling"
  "Menu: Start profilering"

  "Menu: Stop profiling"
  "Menu: Stop profilering"

  "Menu: Switch to session"
  "Menu: Skift til session"

  "Menu: Toggle comment"
  "Menu: Skift kommentar"

  "Menu: Toggle split view mode"
  "Menu: Skift split visningstilstand"

  "Menu: Undo"
  "Menu: Fortryd"

  "Menu: Unfavorite file"
  "Menu: Unfavorite fil"

  "Menu: Unindent selected text"
  "Menu: Afindryk markeret tekst"

  "Menu: Uninstall plugin"
  "Menu: Afinstaller plugin"

  "Menu: Unlock file"
  "Menu: Lås filen"

  "Menu: View User Guide"
  "Menu: Se brugervejledning"

  "Menu: View base preferences file"
  "Menu: Se base præferencer fil"

  "Menu: View global menu bindings"
  "Menu: Se globale menu bindinger"

  "Merge Panes"
  "Flette ruder"

  "Next Difference"
  "Næste forskel"

  "No files found in specified directories"
  "Ikke findes i angivne mapper filer"

  "Open Directory..."
  "Åbn mappe"

  "Open Favorite"
  "Åbent Favorit"

  "Open File..."
  "Åbn fil..."

  "Open Recent"
  "Åbn nylige"

  "Paste"
  "Sæt ind"

  "Paste and Format"
  "Indsæt og Format"

  "Plugins"
  "Plug-in"

  "Preferences"
  "Præferencer"

  "Previous Difference"
  "Forrige forskel"

  "Profiling started"
  "Profilering i gang"

  "Profiling stopped"
  "Profilering stoppet"

  "Quit"
  "Afslut"

  "Redo"
  "Annuller Fortryd"

  "Reload"
  "Opdater"

  "Remove All Markers"
  "Fjerne alle markører"

  "Remove From Current Line"
  "Fjern fra aktuel linje"

  "Replace Line With Script"
  "Erstatte linje med Script"

  "Reset User to Base"
  "Nulstille bruger til Base"

  "Restart TKE"
  "Genstart TKE"

  "Save All"
  "Gem alle"

  "Save As..."
  "Gem som"

  "Save Current"
  "Gem aktuel"

  "Select All"
  "Vælg alle"

  "Select All Occurrences"
  "Vælg alle forekomster"

  "Select Next Occurrence"
  "Vælg næste forekomst"

  "Select Previous Occurrence"
  "Vælg forrige forekomst"

  "Selected"
  "Valgt"

  "Send Bug Report"
  "Send fejlrapport."

  "Send Feedback"
  "Send Feedback"

  "Sessions"
  "Sessioner"

  "Set Syntax"
  "Set Syntaks"

  "Set Theme"
  "Set Theme"

  "Set User to Global"
  "Sæt brugeren til Global"

  "Show Console"
  "Vis Console"

  "Show Diagnostic Logfile"
  "Vis diagnostisk logfil"

  "Show File Difference"
  "Vis fil forskel"

  "Show Last Profiling Report"
  "Vis Seneste Profiling Report"

  "Show Line Numbers"
  "Vis linjenumre"

  "Show Meta Characters"
  "Vis Meta tegn"

  "Show Selected Line Change"
  "Vis valgte linje ændring"

  "Show Sidebar"
  "Vis sidebjælke"

  "Show Status Bar"
  "Vis statuslinje"

  "Show Tab Bar"
  "Vis tab-linje"

  "Show*Profiling*"
  "Vis * Profilering *"

  "Smart Indent"
  "Smart led"

  "Snippet"
  "Snippet"

  "Snippets"
  "Snippets"

  "Sort Tabs"
  "Sort Tabs"

  "Split View"
  "Opdel visning"

  "Start Profiling"
  "Start Profilering"

  "Stop Profiling"
  "Stop Profilering"

  "Switch To"
  "Skift til:"

  "Tabs"
  "Tab"

  "Text"
  "Tekst"

  "Theme Creator"
  "Tema Creator"

  "Toggle Comment"
  "Skift kommentar"

  "Tools"
  "Værktøjer"

  "Undo"
  "Fortryd"

  "Unindent"
  "Afindryk"

  "Uninstall..."
  "afinstallere"

  "Unlock"
  "Lås"

  "User Guide"
  "Brugsanvisning"

  "View"
  "Vis"

  "View Base"
  "Se Base"

  "View Global"
  "Se globale"

  "Vim Mode"
  "Vim-tilstand"

}

# plugins.tcl
msgcat::mcmset da {

  "ERROR (%s,%s): %s"
  "FEJL (%s, %s): %s"

  "ERROR:  Plugin name already exists"
  "FEJL: Plugin navn findes allerede"

  "ERROR:  Plugin name is not valid (only alphanumeric and underscores are allowed)"
  "FEJL: Plugin er ikke gyldigt (kun alfanumeriske og understregninger er tilladt)"

  "ERROR:  Unable to create plugin directory"
  "FEJL: Kan ikke oprette plugin mappe"

  "ERROR:  Unable to write plugin files"
  "FEJL: Kan ikke skrive plugin filer"

  "Enter plugin name"
  "Indtast plugin navn"

  "Plugin %s installed"
  "Plugin% s installeret"

  "Plugin %s uninstalled"
  "Plugin% s afinstalleret"

  "Plugin Errors"
  "Plugin fejl"

  "Plugins successfully reloaded"
  "Plugins held genindlæses"

  "Syntax errors found in selected plugins"
  "Syntaksfejl fundet i udvalgte plugins"

}

# sidebar.tcl
msgcat::mcmset da {

  "Add Parent Directory"
  "Moderkatalog"

  "Close Directory Files"
  "Luk Bliv Files"

  "Copy Pathname"
  "Kopiere stinavn"

  "Delete directory?"
  "Slet mappe?"

  "Delete file?"
  "Slet fil"

  "Directory Name:"
  "vejvisernavn"

  "Duplicate"
  "Dupliker"

  "File Name:"
  "Filnavn"

  "Folder Name:"
  "Mappenavn:"

  "Make Current Working Directory"
  "Gør aktuelle arbejdsmappe"

  "New Directory"
  "Nyt bibliotek"

  "Open Directory Files"
  "Open Directory filer"

  "Refresh Directory Files"
  "Refresh directory-filer"

  "Remove Parent from Sidebar"
  "Fjern Parent fra Sidebar"

  "Remove from Sidebar"
  "Fjern fra Sidebar"

  "Rename"
  "Omdøb"

  "Show Difference"
  "Vis forskellen"

}

# snippets.tcl
msgcat::mcmset da {

  "Snippet: *"
  "Uddragsvisning: *"

}

# syntax.tcl
msgcat::mcmset da {

  "Syntax error in %s.syntax file"
  "Syntaks fejl i% s.syntax fil"

  "Syntax:  %s"
  "Syntaks:% s"

  "Theme:  %s"
  "Tema:% s"

}

# themer.tcl
msgcat::mcmset da {

  "Create"
  "Opret"

  "Create New Theme"
  "Opret nyt tema..."

  "Create custom"
  "Opret brugerdefinerede"

  "ERROR:  Unable to read %s"
  "FEJL: Kunne ikke læse% s"

  "ERROR:  Unable to write %s"
  "FEJL: Kunne ikke skrive% s"

  "Edit theme"
  "Edit tema"

  "Enter theme name"
  "Indtast temanavn"

  "Error:  Theme is not a supported theme"
  "Fejl: tema er ikke en understøttet tema"

  "Import"
  "Import"

  "Import TextMate Theme"
  "Import TextMate Theme"

  "Name:"
  "Navn:"

  "OK"
  "OK"

  "Reset"
  "Nulstil"

  "Select theme"
  "Vælg temafil"

}

# tke.tcl
msgcat::mcmset da {

  "Edit theme?"
  "Rediger tema?"

  "Import TextMate theme?"
  "Importer TextMate tema?"

}

# vim.tcl
msgcat::mcmset da {

  "File %s successfully written"
  "Filen %s blev skrevet"

  "Filename %s already exists"
  "Filnavn %s findes allerede"

}

# General
msgcat::mcmset da {

  "Cancel"
  "Annuller"

  "Close"
  "Luk"

  "Delete"
  "Slet"

  "Favorite"
  "foretrukken"

  "Find:"
  "finde"

  "Move to Other Pane"
  "Flytter til andre Pane"

  "New File"
  "Ny fil"

  "Open"
  "Åben"

  "Replace:"
  "Erstat"

  "Save"
  "Gem"

  "Save As"
  "Gem som"

  "Unable to open %s for writing"
  "Kunne ikke åbne%1 til skrivning"

  "Unfavorite"
  "Unfavorite"

}

