# api.tcl
msgcat::mcmset da {

  "Argument list to api::add_file was not an even key/value pair"
  "Argument liste til api :: add_file ikke var en selv nøgle / værdi par"

  "Plugin"
  "Plugin"

}

# bgproc.tcl
msgcat::mcmset da {

  "Unable to run system command"
  "Stand til at køre system kommando"

}

# diff.tcl
msgcat::mcmset da {

  "    End: "
  "Slutning"

  "    Start: "
  "Start"

  "Enter difference command"
  "Angiv forskel kommando"

  "Enter starting file"
  "Indtast start fil"

  "Update"
  "Opdater"

}

# edit.tcl
msgcat::mcmset da {

  "File successfully written"
  "Filen blev skrevet"

  "Filename already exists"
  "Filnavnet findes allerede"

}

# embed_tke.tcl
msgcat::mcmset da {

  "Find:"
  "finde"

  "Replace:"
  "Erstat"

}

# gui.tcl
msgcat::mcmset da {

  "All"
  "Alle"

  "Case sensitivity"
  "Versalfølsom"

  "Close All Tabs"
  "Luk alle faneblade"

  "Close Other Tabs"
  "Luk de andre faneblade"

  "Close Other*"
  "Luk de andre faneblade"

  "Close Tab"
  "Luk faneblad"

  "Column"
  "Kolonne"

  "Copyright"
  "Copyright"

  "Delete tab?"
  "Slet fane?"

  "Developer"
  "Udvikler"

  "Email"
  "E-mail"

  "Error"
  "Fejl"

  "Favorited"
  "Favoriseret"

  "File already exists.  Use '!' to force an overwrite"
  "Filen findes allerede.  Brug '!' at tvinge en Overskriv"

  "File attribute does not exist"
  "Attribut til systemfil findes ikke"

  "File index is out of range"
  "File indeks er uden for rækkevidde"

  "Image displayed in fill-in forms which closes the form UI.  Used in forms such as search, search/replace, and find in files."
  "Billede, der vises i fill-in former, som lukker formularen UI. Bruges i former som søgning, søg / erstat, og finde i filer."

  "Image used in tab menus to indicate that the file is associated with a difference view."
  "Billede anvendt i fanen menuer for at indikere, at filen er forbundet med en forskel visning."

  "Image used in tab menus to indicate that the file is locked."
  "Billede anvendt i fanen menuer for at indikere, at filen er låst."

  "Image used in tab menus to indicate that the file is readonly."
  "Billede anvendes i fanen menuer for at indikere, at filen er skrivebeskyttet."

  "Image used in tab to indicate that the tab contains a difference view."
  "Billede anvendt i Tab for at indikere, at fanen indeholder en forskel visning."

  "Image used in tab to indicate that the tab's file is readonly."
  "Billede anvendes i Tab for at angive, at fanen sagsakter er skrivebeskyttet."

  "Image used in tab to indicate that the tab’s file is locked."
  "Billede anvendes i Tab for at indikere, at fanen sagsakter er låst."

  "Image used in tab which, when clicked, closes the tab."
  "Billede anvendes i fanen, der, når der klikkes, lukker fanen."

  "License"
  "Licens"

  "Line"
  "Linje"

  "Locked"
  "låst"

  "Move"
  "Flyt"

  "Must be in multicursor mode to insert numbers"
  "Skal være i multicursor tilstand at indsætte tal"

  "No write permissions.  Use '!' to force write."
  "Ingen skrivetilladelser.  Brug '!' at tvinge skrive."

  "Release Type"
  "Release Type"

  "Reload file?"
  "Genindlæs fil"

  "Replace"
  "Erstat"

  "Save request"
  "Spar anmodning"

  "Show in Sidebar"
  "Vis i Sidebar"

  "Starting number:"
  "Starttal"

  "Tcl/Tk Version"
  "Tcl/Tk Version"

  "Total Characters"
  "Samlede karakterer"

  "Total Lines"
  "Samlede linjer"

  "Unable to successfully parse number string"
  "Ikke kan med held parse nummer streng"

  "Unable to write file"
  "Kunne ikke skrive filen"

  "Version"
  "Version"

}

# markers.tcl
msgcat::mcmset da {

  "Marker name:"
  "Markør navn:"

}

# menus.tcl
msgcat::mcmset da {

  "About"
  "Um"

  "Absolute"
  "Absolut"

  "Absolute line numbering"
  "Absolut linjenummerering"

  "Align Cursors"
  "Juster markører"

  "Align cursors"
  "Juster markører"

  "All Levels"
  "ALLE NIVEAUER!"

  "Append Next Occurrence"
  "Føj næste forekomst"

  "Append next occurrence"
  "Føj næste forekomst"

  "Auto-Indent"
  "Automatisk indryk"

  "Bubble Down"
  "Boble ned"

  "Bubble Up"
  "Boble op"

  "Bubble lines down one line"
  "Boble linjer ned en linje"

  "Bubble lines up one line"
  "Boble linjer op én linje"

  "Change Working Directory"
  "Ændre arbejder Register"

  "Change working directory"
  "Ændring i orden bibliotek"

  "Character"
  "Karakter"

  "Check for Update"
  "Søg efter opdatering"

  "Check for update"
  "Kontroller for opdateringer"

  "Classic Mac"
  "Klassiske Mac"

  "Clear All"
  "Ryd alt"

  "Close All"
  "Luk alle"

  "Close All Folds"
  "Luk alle folder"

  "Close Current"
  "Luk strøm {0}"

  "Close Current Fold"
  "Lukke aktuelle Fold"

  "Close Selected Folds"
  "Luk valgt folder"

  "Close all folds"
  "Luk alle folder"

  "Close all tabs"
  "Luk alle faneblade"

  "Close current session"
  "Luk den aktuelle session."

  "Close current tab"
  "Luk dette faneblad"

  "Close fold at current line - all levels"
  "Luk klappen på nuværende linje - alle niveauer"

  "Close fold at current line - one level"
  "Luk klappen på nuværende linje - et niveau"

  "Close selected folds - all levels"
  "Luk valgte folder - alle niveauer"

  "Close selected folds - one level"
  "Luk valgte folder - et niveau"

  "Command"
  "Kommando:"

  "Command Result"
  "Kommandoen resultat"

  "Convert case to lower"
  "Konverter sagen til lavere"

  "Convert case to title"
  "Konverter sagen til titel"

  "Convert case to upper"
  "Konverter sagen til øverste"

  "Copy"
  "Kopier"

  "Copy text"
  "Kopieret tekst"

  "Create"
  "Opret"

  "Create Fold From Selection"
  "Opret fra markering"

  "Create at Current Line"
  "Oprette på nuværende linje"

  "Create fold from selection"
  "Opret fra markering"

  "Create marker at current line"
  "Oprette markør på nuværende linje"

  "Create new plugin"
  "Oprette nye plugin"

  "Current Line"
  "Aktuel linje:"

  "Current Number"
  "Dette rækkenummer"

  "Current Word"
  "Aktuelle ord"

  "Cursor"
  "Markør"

  "Cursor from Line Start"
  "Markøren fra linje Start"

  "Cursor to Line End"
  "Markøren til stregafslutning"

  "Cut"
  "Klip"

  "Cut text"
  "Klippe tekst"

  "Delete All Folds"
  "Slet alle folder"

  "Delete Current Fold"
  "Slet nuværende"

  "Delete Selected Folds"
  "Slet de valgte folder"

  "Delete all folds"
  "Slet alle folder"

  "Delete all selected folds"
  "Slet alle valgte folder"

  "Delete current file"
  "Slet nuværende"

  "Delete current line"
  "Slet nuværende"

  "Delete current word"
  "Slet nuværende"

  "Delete fold at current line"
  "Slette fold på nuværende linje"

  "Delete from cursor to end of line"
  "Slet fra markøren til ende af linjen"

  "Delete from start of line to cursor"
  "Slet fra starten af linjen til markør"

  "Delete session"
  "Slet session"

  "Delete template"
  "Slet skabelon"

  "Delete text between character"
  "Slet tekst mellem karakter"

  "Delete the current number"
  "Slet det aktuelle nummer"

  "Delete the whitespace to left of cursor"
  "Slet mellemrum til venstre for markøren"

  "Delete the whitespace to right of cursor"
  "Slet mellemrum til højre for markøren"

  "Disable Vim mode"
  "Deaktivere Vim tilstand"

  "Disable code folding"
  "Deaktivere kode foldning"

  "Display Text Info"
  "Vise teksten Info"

  "Display text information"
  "Viser tekstoplysninger"

  "Duplicate current file"
  "Dublerede aktuelle fil"

  "Edit"
  "Rediger"

  "Edit Custom Abbreviations"
  "Rediger brugerdefinerede forkortelser"

  "Edit Language"
  "Rediger sprog"

  "Edit Session"
  "Redigere Session"

  "Edit User"
  "Rediger bruger."

  "Edit custom Emmet abbreviations"
  "Rediger brugerdefinerede Emmet forkortelser"

  "Edit language snippets"
  "Redigere sprog uddrag"

  "Edit session current language preferences"
  "Redigere session aktuelle sprogindstillinger"

  "Edit session global preferences"
  "Redigere session globale indstillinger"

  "Edit template"
  "Redigér skabelon"

  "Edit user current language preferences"
  "Rediger brugerens aktuelle sprogpræferencer"

  "Edit user global preferences"
  "Rediger brugerens globale indstillinger"

  "Edit user menu bindings"
  "Rediger bruger menuen bindinger"

  "Edit user snippets"
  "Rediger bruger snippets"

  "Enable Code Folding"
  "Aktivere kode foldning"

  "Enable Vim mode"
  "Aktiver Vim tilstand"

  "Enable code folding"
  "Aktivere kode foldning"

  "Enumeration"
  "tælling af bakterier"

  "Expand Abbreviation"
  "Udvid forkortelser"

  "Expand Emmet abbreviation"
  "Udvid Emmet forkortelse"

  "Favorite file"
  "Favorit fil"

  "File"
  "Filer"

  "File Contents"
  "filindhold"

  "Find In Files"
  "Find i filer..."

  "Find Matching Pair"
  "Finde matchende par"

  "Find and Replace"
  "Find og erstat"

  "Find in files"
  "Find i filer..."

  "Find matching character pair"
  "Finde matchende par, karakter"

  "Find next occurrence"
  "Finde næste forekomst"

  "Find previous occurrence"
  "Find forrige forekomst"

  "Folding"
  "Fold"

  "Format Text"
  "Formatér tekst"

  "Format indentation for text"
  "Format indrykningen for teksten"

  "From Clipboard"
  "Fra klippebord"

  "Global"
  "Standard"

  "Goto Last Tab"
  "Goto Last Tab"

  "Goto Next Tab"
  "Goto Next Tab"

  "Goto Other Pane"
  "Goto Anden Pane"

  "Goto Previous Tab"
  "Goto forrige fane"

  "Goto last tab"
  "Goto sidste fane"

  "Goto next difference"
  "Goto næste forskellen"

  "Goto next tab"
  "Goto næste fane"

  "Goto other pane"
  "Goto anden rude"

  "Goto previous difference"
  "Forrige forskel"

  "Goto previous tab"
  "Foregående fane"

  "Help"
  "Hjælp"

  "Hide Console"
  "Skjul Console"

  "Hide Line Numbers"
  "Skjul linjenumre"

  "Hide Marker Map"
  "Skjul markør kort"

  "Hide Meta Characters"
  "Skjule Meta tegn"

  "Hide Sidebar"
  "Skjul sidebjælke"

  "Hide Status Bar"
  "Skjul statuslinje"

  "Hide Tab Bar"
  "Skjul tab-linje"

  "Hide console"
  "Skjule konsol"

  "Hide line numbers"
  "Skjul linjenumre"

  "Hide marker map"
  "Skjul markør kort"

  "Hide meta characters"
  "Skjule meta tegn"

  "Hide sidebar"
  "Skjul sidemenu"

  "Hide status bar"
  "Skjul statuslinje"

  "Hide tab bar"
  "Skjul tab-linje"

  "Indent"
  "Indryk"

  "Indent Off"
  "LED slukket"

  "Indent selected text"
  "LED markeret tekst"

  "Indentation"
  "gennemtryk"

  "Insert"
  "Indsæt"

  "Insert command result after current line"
  "Indsæt kommando resultatet efter den aktuelle linje"

  "Insert enumeration"
  "Indsæt optælling"

  "Insert file contents after current line"
  "Indsæt filindhold efter den aktuelle linje"

  "Insert from clipboard"
  "Indsætte fra Udklipsholder"

  "Insert line above current line"
  "Indsæt linje over nuværende linje"

  "Insert line below current line"
  "Indsæt linjen under aktuel linje"

  "Insert snippet"
  "Indsæt kodestykket"

  "Install"
  "Installer"

  "Install plugin"
  "Installere plugin"

  "Join Lines"
  "Forbind linjer"

  "Join lines"
  "Forbind linjer"

  "Jump Backward"
  "Hoppe baglæns"

  "Jump Forward"
  "Spring frem"

  "Jump To Line"
  "Gå til linje"

  "Jump backward"
  "Hoppe baglæns"

  "Jump forward"
  "Spring frem"

  "Jump to Next Fold Mark"
  "Hoppe til næste Fold Mark"

  "Jump to Previous Fold Mark"
  "Springe til forrige Fold Mark"

  "Jump to line"
  "Gå til linje"

  "Jump to the next fold indicator"
  "Springe til den næste fold indikator"

  "Jump to the previous fold indicator"
  "Springe til den forrige fold indikator"

  "Language"
  "Sprog"

  "Launcher"
  "Launcher"

  "Line Above Current"
  "Linje over nuværende"

  "Line Below Current"
  "Linjen under nuværende"

  "Line Ending"
  "Linje slutter"

  "Line Number"
  "linjenummer"

  "Line Numbering"
  "Linjenummerering"

  "Lock"
  "Lås"

  "Lock file"
  "Lock-fil"

  "Lower Case"
  "Små bogstaver"

  "Markers"
  "Markører"

  "Menu"
  "Menu"

  "Menu Bindings"
  "Menu Bindinger"

  "Merge Panes"
  "Flette ruder"

  "Merge panes"
  "Flette ruder"

  "Move Cursors Down"
  "Ytte markører"

  "Move Cursors Left"
  "Flytte markører venstre"

  "Move Cursors Right"
  "Flytte markører højre"

  "Move Cursors Up"
  "Flytte markører"

  "Move cursor to bottom of screen"
  "Flytte markøren til bunden af skærmen"

  "Move cursor to end of current line"
  "Flytte markøren til ende af linjen"

  "Move cursor to first line"
  "Flyt markøren til første linje"

  "Move cursor to last line"
  "Flyt markøren til sidste linje"

  "Move cursor to middle of screen"
  "Flyt markøren til midten af skærmen"

  "Move cursor to next page"
  "Flyt markøren til næste side"

  "Move cursor to next word"
  "Flytte markøren til næste ord"

  "Move cursor to previous page"
  "Flyt markøren til forrige side"

  "Move cursor to previous word"
  "Flytte markøren til forrige ord"

  "Move cursor to start of current line"
  "Flytte tekstmarkeringen til starten af linjen"

  "Move cursor to top of screen"
  "Flytte markøren til toppen af skærmen"

  "Move multicursors down one line"
  "Flyt multicursors ned en linje"

  "Move multicursors left one line"
  "Flyt multicursors venstre én linje"

  "Move multicursors right one line"
  "Flytte multicursors lige én linje"

  "Move multicursors up one line"
  "Flyt multicursors op én linje"

  "Move to First Line"
  "Flytte til første linje"

  "Move to Last Line"
  "Flyt til sidste linje"

  "Move to Line End"
  "Flytte til slutningen"

  "Move to Line Start"
  "Flytte til Line Start"

  "Move to Next Page"
  "Flytte til næste side"

  "Move to Next Word"
  "Flytte til næste ord"

  "Move to Previous Page"
  "Flytte til forrige side"

  "Move to Previous Word"
  "Flytte til forrige ord"

  "Move to Screen Bottom"
  "Flytte til skærmen bunden"

  "Move to Screen Middle"
  "Flytte til skærmen midten"

  "Move to Screen Top"
  "Flytte til skærmen Top"

  "Move to other pane"
  "Flytte til andre rude"

  "New From Template"
  "Ny fra skabelon"

  "New Window"
  "Nyt Vindue"

  "New file"
  "Ny fil..."

  "New file from template"
  "Ny fra skabelon"

  "New window"
  "Nyt vindue"

  "Next Difference"
  "Næste forskel"

  "One Level"
  "Ét niveau"

  "Open All Folds"
  "Åbn alle folderne"

  "Open Current Fold"
  "Åben nuværende Fold"

  "Open Directory"
  "Åbn mappe"

  "Open Favorite"
  "Åbent Favorit"

  "Open File"
  "Flyt fil"

  "Open Recent"
  "Åbn nylige"

  "Open Selected Folds"
  "Åbn valgt folder"

  "Open all folds"
  "Åbn alle folderne"

  "Open directory"
  "Åbn mappe"

  "Open file"
  "Åbn fil"

  "Open fold at current line - all levels"
  "Åben fold på nuværende linje - alle niveauer"

  "Open fold at current line - one level"
  "Åben fold på nuværende linje - et niveau"

  "Open folds to show cursor"
  "Åbne folderne til at vise markøren"

  "Open selected folds - all levels"
  "Åben udvalgte folder - alle niveauer"

  "Open selected folds - one level"
  "Åben udvalgte folder - et niveau"

  "Paste"
  "Sæt ind"

  "Paste and Format"
  "Indsæt og Format"

  "Paste and format text from clipboard"
  "Indsætte og formatere tekst fra Udklipsholder"

  "Paste text from clipboard"
  "Indsæt tekst fra udklipsholderen"

  "Plugins"
  "Plug-in"

  "Preferences"
  "Præferencer"

  "Previous Difference"
  "Forrige forskel"

  "Profiling Report Sorted By"
  "Profilering rapport sorteret efter"

  "Profiling started"
  "Profilering i gang"

  "Profiling stopped"
  "Profilering stoppet"

  "Quit"
  "Afslut"

  "Quit application"
  "Afslut program"

  "Redo"
  "Annuller Fortryd"

  "Relative"
  "Relativ"

  "Relative line numbering"
  "Relative linjenummerering"

  "Reload"
  "Opdater"

  "Reload all plugins"
  "Genindlæse alle plugins"

  "Reload snippets"
  "Genindlæse snippets"

  "Reload template information"
  "Genindlæse skabelonoplysninger"

  "Remove All Markers"
  "Fjerne alle markører"

  "Remove From Current Line"
  "Fjern fra aktuel linje"

  "Remove all markers"
  "Fjerne alle markører"

  "Remove marker from current line"
  "Fjern markering fra aktuel linje"

  "Rename current file"
  "Omdøbe aktuelle fil"

  "Reopen File"
  "Åbner filen igen"

  "Reopen current file"
  "Genåbne aktuelle fil"

  "Replace Line With Script"
  "Erstatte linje med Script"

  "Replace line with script"
  "Erstatte linje med script"

  "Reset User to Base"
  "Nulstille bruger til Base"

  "Restart"
  "Genstart"

  "Run"
  "Kør"

  "Run theme editor"
  "Køre tema editor"

  "Save All"
  "Gem alle"

  "Save As Template"
  "Gem som skabelon"

  "Save Current"
  "Gem aktuel"

  "Save Selection As"
  "Gem markering som"

  "Save all files"
  "Gemme alle filer"

  "Save current session"
  "Gem nuværende session?"

  "Save file"
  "Gem fil..."

  "Save file as"
  "Gem fil som..."

  "Save file as template"
  "Gem som skabelon"

  "Save selected lines"
  "Gem markerede linjer"

  "Save sessions as"
  "Gemme sessioner som"

  "Select All"
  "Vælg alle"

  "Select All Occurrences"
  "Vælg alle forekomster"

  "Select Next Occurrence"
  "Vælg næste forekomst"

  "Select Previous Occurrence"
  "Vælg forrige forekomst"

  "Select all occurrences"
  "Vælg alle forekomster"

  "Select all text"
  "Markér al tekst"

  "Send Bug Report"
  "Send fejlrapport."

  "Send Feedback"
  "Send Feedback"

  "Send bug report"
  "Send fejlrapport."

  "Send feedback"
  "Send feedback"

  "Sessions"
  "Sessioner"

  "Set Syntax"
  "Set Syntaks"

  "Set Theme"
  "Set Theme"

  "Set User to Global"
  "Sæt brugeren til Global"

  "Set current file line ending to CR for Classic Mac"
  "Angive aktuelle fil linje slutter til CR for klassiske Mac"

  "Set current file line ending to CRLF for Windows"
  "Angive aktuelle fil linje slutter CRLF til Windows"

  "Set current file line ending to LF for Unix"
  "Angive aktuelle fil linje slutter til LF for Unix"

  "Set indent mode to"
  "Sæt led mode til"

  "Set user bindings to global bindings"
  "Sæt brugeren bindinger til globale bindinger"

  "Set user preferences to global preferences"
  "Angive brugerindstillinger for globale indstillinger"

  "Show Console"
  "Vis Console"

  "Show Cursor"
  "Vis markøren"

  "Show Diagnostic Logfile"
  "Vis diagnostisk logfil"

  "Show File Difference"
  "Vis fil forskel"

  "Show Last Profiling Report"
  "Vis Seneste Profiling Report"

  "Show Line Numbers"
  "Vis linjenumre"

  "Show Marker Map"
  "Vis markør kort"

  "Show Meta Characters"
  "Vis Meta tegn"

  "Show Selected Line Change"
  "Vis valgte linje ændring"

  "Show Sidebar"
  "Vis sidebjælke"

  "Show Status Bar"
  "Vis statuslinje"

  "Show Tab Bar"
  "Vis tab-linje"

  "Show console"
  "Vis konsol"

  "Show diagnostic logfile"
  "Vis diagnostisk logfil"

  "Show file difference"
  "Vis fil forskel"

  "Show last profiling report"
  "Vis sidste profilering rapport"

  "Show line numbers"
  "Vis linjenumre"

  "Show marker map"
  "Vis markør kort"

  "Show meta characters"
  "Vis meta tegn"

  "Show selected line change"
  "Vis valgte linje ændring"

  "Show sidebar"
  "Vis sidebjælke"

  "Show status bar"
  "Vis statuslinje"

  "Show tab bar"
  "Vis tab-linje"

  "Smart Indent"
  "Smart led"

  "Snippet"
  "Snippet"

  "Snippets"
  "Snippets"

  "Sort Tabs"
  "Sort Tabs"

  "Sort tabs"
  "Sortere faneblade"

  "Start Profiling"
  "Start Profilering"

  "Start profiling"
  "Start profilering"

  "Stop Profiling"
  "Stop Profilering"

  "Stop profiling"
  "Stop profilering"

  "Switch To"
  "Skift til:"

  "Switch to session"
  "Skifte til session"

  "Tabs"
  "Tab"

  "Templates"
  "Skabeloner"

  "Text Between Character"
  "Tekst mellem karakter"

  "Tips & Tricks"
  "Tips & Tricks"

  "Title Case"
  "Titel versalisering"

  "Toggle Case"
  "Vend versalisering"

  "Toggle Comment"
  "Skift kommentar"

  "Toggle case of current character"
  "Skifte tilfælde af aktuelle karakter"

  "Toggle comment"
  "Skift kommentar"

  "Toggle split view mode"
  "Skifte split visningstilstand"

  "Tools"
  "Værktøjer"

  "Transform"
  "transformere, transformere"

  "Undo"
  "Fortryd"

  "Unfavorite file"
  "Unfavorite fil"

  "Unindent"
  "Afindryk"

  "Unindent selected text"
  "Unindent markeret tekst"

  "Uninstall"
  "Afinstallér"

  "Uninstall plugin"
  "Afinstallere plugin"

  "Unix"
  "UNIX"

  "Unlock"
  "Lås"

  "Unlock file"
  "Låse fil"

  "Upper Case"
  "Store bogstaver"

  "User Guide"
  "Brugsanvisning"

  "View"
  "Vis"

  "View Base"
  "Se Base"

  "View Global"
  "Se globale"

  "View base preferences file"
  "Se base præferencer fil"

  "View global menu bindings"
  "Se global menu bindinger"

  "View tips & tricks articles"
  "Se tips & tricks artikler"

  "View user guide"
  "Brugervejledning"

  "Vim Mode"
  "Vim-tilstand"

  "Whitespace Backward"
  "Whitespace bagud"

  "Whitespace Forward"
  "Mellemrum frem"

  "Windows"
  "Windows"

}

# plugins.tcl
msgcat::mcmset da {

  "Always grant from developer"
  "Altid give fra udvikleren"

  "ERROR"
  "FEJL"

  "ERROR:  Plugin name already exists"
  "FEJL: Plugin navn findes allerede"

  "ERROR:  Plugin name is not valid (only alphanumeric and underscores are allowed)"
  "FEJL: Plugin er ikke gyldigt (kun alfanumeriske og understregninger er tilladt)"

  "ERROR:  Unable to create plugin directory"
  "FEJL: Kan ikke oprette plugin mappe"

  "ERROR:  Unable to write plugin files"
  "FEJL: Kan ikke skrive plugin filer"

  "Enter plugin name"
  "Indtast plugin navn"

  "Grant"
  "Meddelelse af EF-sortsbeskyttelse"

  "Grant permission?"
  "Grant permission?"

  "OK"
  "OK"

  "Plugin Errors"
  "Plugin fejl"

  "Plugin Trust Requested"
  "Plugin Trust Anmodet"

  "Plugin installed"
  "Plugin installeret"

  "Plugin requires permission to view or modify your system."
  "Plugin kræver tilladelse til at se eller ændre dit system."

  "Plugin uninstalled"
  "Plugin afinstalleret"

  "Plugins successfully reloaded"
  "Plugins held genindlæses"

  "Reject"
  "Afvis"

  "Syntax errors found in selected plugins"
  "Syntaksfejl fundet i udvalgte plugins"

}

# search.tcl
msgcat::mcmset da {

  "No files found in specified directories"
  "Ikke findes i angivne mapper filer"

  "No search results found"
  "Ingen resultater matcher din søgning!"

  "Search wrapped to beginning of file"
  "Søg ombrydes til begyndelsen af filen"

  "Search wrapped to end of file"
  "Søg indpakket til slutningen af filen"

  "substitutions done"
  "erstatninger udført"

}

# sessions.tcl
msgcat::mcmset da {

  "Save session?"
  "Gem session?"

  "Session state will be lost if not saved"
  "Session stat vil gå tabt, hvis ikke gemt"

}

# sidebar.tcl
msgcat::mcmset da {

  "Add Parent Directory"
  "Moderkatalog"

  "Close Directory Files"
  "Luk Bliv Files"

  "Copy Pathname"
  "Kopiere stinavn"

  "Delete directories?"
  "Slette mapper?"

  "Delete directory?"
  "Slet mappe?"

  "Delete file?"
  "Slet fil"

  "Delete files?"
  "Slet filer"

  "Directory Name:"
  "vejvisernavn"

  "Folder Name:"
  "Mappenavn:"

  "Image displayed in sidebar to indicate that a file is currently opened in an editing buffer."
  "Billede, der vises i indholdsoversigten for at indikere, at en fil i øjeblikket er åbnet i en redigering buffer."

  "Make Current Working Directory"
  "Gør aktuelle arbejdsmappe"

  "New Directory"
  "Nyt bibliotek"

  "New File From Template"
  "Ny fra skabelon"

  "Open Directory Files"
  "Open Directory filer"

  "Refresh Directory Files"
  "Refresh directory-filer"

  "Remove Parent from Sidebar"
  "Fjern Parent fra Sidebar"

  "Remove from Sidebar"
  "Fjern fra Sidebar"

  "Show Difference"
  "Vis forskellen"

}

# snippets.tcl
msgcat::mcmset da {

  "Snippet: *"
  "Uddragsvisning: *"

}

# syntax.tcl
msgcat::mcmset da {

  "Syntax"
  "Syntaks"

  "Syntax error in syntax file"
  "Syntaksfejl i syntaks fil"

}

# templates.tcl
msgcat::mcmset da {

  "Delete template?"
  "Slette skabelonen?"

  "Template"
  "Skabelon"

  "Template Name"
  "Navn på Skabelon"

  "deleted"
  "Slettede"

  "saved"
  "gemt."

  "will be permanently deleted"
  "slettes permanent"

}

# theme.tcl
msgcat::mcmset da {

  "Background (trough) color used in the sidebar scrollbar."
  "Baggrund (trough) farve, der anvendes i indholdsoversigten rullebjælken."

  "Background (trough) color used in the text scrollbars."
  "Baggrund (trough) farve i teksten scrollbars."

  "Background color displayed in embedded language code."
  "Baggrundsfarve vises i integrerede sprogkode."

  "Background color for all sidebar items that are not selected."
  "Baggrundsfarve for alle sidebar elementer, der ikke er valgt."

  "Background color for all sidebar items that are selected."
  "Baggrundsfarve for alle sidebar elementer, der er valgt."

  "Background color in difference viewer that shows added lines."
  "Baggrundsfarve i forskel fremviser, der viser tilføjet linjer."

  "Background color in difference viewer that shows deleted lines."
  "Baggrundsfarve i forskel fremviser, der viser slettede linier."

  "Background color of insertion cursor and background marker colors."
  "Baggrundsfarve indsættelse markøren og baggrunden markør farver."

  "Background color of the editing buffer."
  "Baggrundsfarve redigering buffer."

  "Background color to display when a button-like ttk widget is pressed."
  "Baggrundsfarve skal vises, når der trykkes på en knap-lignende TTK widget."

  "Background color to use for selected text."
  "Baggrundsfarve til brug for markeret tekst."

  "Background color used for all other tabs that are not the current/active tab in the tabbar."
  "Baggrundsfarve anvendes til alle andre faneblade, som ikke er den aktuelle / aktive fane i fanebladslinjen."

  "Background color used for the current/active menu item."
  "Baggrundsfarve brugt til strøm / aktive menupunkt."

  "Background color used for the current/active tab in the tabbar."
  "Baggrundsfarve brugt til strøm / aktive fane i fanebladslinjen."

  "Background color used in highlighted text."
  "Baggrundsfarve brugt i markerede tekst."

  "Background color used in menus."
  "Baggrundsfarve brugt i menuer."

  "Background color used in the tabbar area."
  "Baggrundsfarve brugt i fanebladslinjen området."

  "Color of border drawn around active editing buffer."
  "Farve på kant trukket rundt aktiv redigering buffer."

  "Color of ttk entry widget text border when the entry has keyboard focus."
  "Farve på TTK post kontroltekst grænse, når posten har tastatur fokus."

  "Color used to draw the warning width line in the editing buffer (as well as the line separating the gutter from the editing buffer)."
  "Color bruges til at tegne advarslen bredde linje i redigeringen buffer (såvel som grænsen mellem renden fra redigeringen buffer)."

  "Default 'darkcolor' for all ttk widgets."
  "Standard &#39;darkcolor&#39; for alle TTK widgets."

  "Default background color to use for all ttk widgets that are in a disabled state."
  "Standard baggrundsfarve til brug for alle TTK widgets, der er i en deaktiveret tilstand."

  "Default background color to use for all ttk widgets when the mouse cursor hovers over the widget."
  "Standard baggrundsfarve til brug for alle TTK widgets når musemarkøren svæver over widget."

  "Default background color to use for all ttk widgets."
  "Standard baggrundsfarve til brug for alle TTK widgets."

  "Default border color for all ttk widgets."
  "Standard kantfarve for alle TTK widgets."

  "Default color for non-syntax highlighted text."
  "Standard farve for ikke-syntaks fremhævet tekst."

  "Default foreground text color to use for all ttk widgets that are in a disabled state."
  "Standard forgrunden tekst farve til brug for alle TTK widgets, der er i en deaktiveret tilstand."

  "Default foreground text color to use for all ttk widgets."
  "Standard forgrunden tekst farve til brug for alle TTK widgets."

  "Determines the number of grips strips to display in the grip area between resizable panes."
  "Bestemmer antallet af greb strimler at vise i grebet mellem resizable ruder."

  "Determines the thickness of the grip area between resizable panes."
  "Bestemmer tykkelsen af ​​grebet mellem resizable ruder."

  "ERROR:  Unable to read"
  "FEJL: Kan ikke læses"

  "Foreground (slider) color used in the sidebar scrollbar."
  "Forgrund (skyder) farve, der anvendes i indholdsoversigten rullebjælken."

  "Foreground (slider) color used in the text scrollbars."
  "Forgrund (skyder) farve i teksten scrollbars."

  "Foreground color used in menu items with checks or buttons."
  "Forgrundsfarven bruges menupunkter med checks eller knapper."

  "Foreground text color for strings."
  "Forgrunden tekstfarve for strygere."

  "Foreground text color to use for all miscellaneous1 labeled text."
  "Forgrund tekstfarve til brug for alle miscellaneous1 mærket tekst."

  "Foreground text color to use for all miscellaneous2 labeled text."
  "Forgrund tekstfarve til brug for alle miscellaneous2 mærket tekst."

  "Foreground text color to use for all miscellaneous3 labeled text."
  "Forgrund tekstfarve til brug for alle miscellaneous3 mærket tekst."

  "Foreground text color to use for comments."
  "Forgrund tekstfarve til brug for kommentarer."

  "Foreground text color to use for displaying line numbers."
  "Forgrund tekstfarve til at bruge til visning af linjenumre."

  "Foreground text color to use for displaying numbers."
  "Forgrund tekstfarve skal bruges til visning af tal."

  "Foreground text color to use for language-specific keywords."
  "Forgrund tekstfarve bruge til sprogspecifikke søgeord."

  "Foreground text color to use for language-specific punctuation."
  "Forgrund tekstfarve skal bruges til sprogspecifik tegnsætning."

  "Foreground text color to use for meta syntax."
  "Forgrund tekstfarve bruge til meta syntaks."

  "Foreground text color to use for precompiler syntax."
  "Forgrund tekstfarve bruge til præ-compileren syntaks."

  "Foreground text color to use for selected text."
  "Forgrund tekstfarve til at bruge den valgte tekst."

  "Foreground text color used for all other tabs that are not the current/active tab in the tabbar."
  "Forgrunden tekstfarve bruges til alle andre faner, der ikke er aktuelle/aktiv fane i tabbar."

  "Foreground text color used for menus item that are disabled."
  "Forgrunden tekstfarve bruges til menuer element, der er deaktiveret."

  "Foreground text color used for the current/active menu item."
  "Forgrunden tekstfarve bruges til strøm / aktive menupunkt."

  "Foreground text color used for the current/active tab in the tabbar."
  "Tekst forgrundsfarven bruges til den aktuelle/aktiv fane i tabbar."

  "Foreground text color used in menus."
  "Forgrunden tekstfarve anvendes i menuer."

  "Foreground text/image color used in tabbar and tabs."
  "Forgrund tekst / billede farve anvendes i fanebladslinjen og faner."

  "Images"
  "Billeder"

  "Maximum thickness of the text scrollbar when it is active."
  "Maksimale tykkelse af teksten rullebjælke, når den er aktiv."

  "Maximum thickness of the text scrollbars when they are active."
  "Maksimale tykkelse af teksten scrollbars, når de er aktive."

  "Menu Options"
  "Menupunkter"

  "Menu relief value."
  "Menu relief værdi."

  "Pixel height of the tabbar widget."
  "Pixel højde fanebladslinjen widget."

  "Relief used in drawing the tabs."
  "Relief anvendt i udarbejdelsen fanerne."

  "Relief value of the sidebar area."
  "Relief værdi indholdsoversigten området."

  "Sidebar Options"
  "Sidebar options"

  "Sidebar Scrollbar Options"
  "Sidebar Scrollbar Options"

  "Specifies the color to display around the sidebar when the sidebar does not have the focus."
  "Angiver farven til at vise rundt på sidelinjen, når sidebjælken ikke har fokus."

  "Specifies the color to display around the sidebar when the sidebar has the focus."
  "Angiver farven til at vise rundt på sidelinjen, når sidebjælken har fokus."

  "Specifies the default background color to use for text that is selected in a standard ttk widget (this does not include the editing buffer)."
  "Angiver standard baggrundsfarve til brug for tekst, der er valgt i en standard TTK widget (dette omfatter ikke redigering buffer)."

  "Specifies the default foreground text color to use for text that is selected in a standard ttk widget (this does not include the editing buffer)."
  "Angiver standard forgrunden tekst farve til brug for tekst, der er valgt i en standard TTK widget (dette omfatter ikke redigering buffer)."

  "Specifies the default relief to use when drawing ttk widgets."
  "Angiver standardindstillingen lettelse at bruge ved udarbejdelsen TTK widgets."

  "Specifies the disclosure image style to use in the sidebar."
  "Angiver videregivelse billedet stil at bruge i indholdsoversigten."

  "Specifies the pixel thickness of the highlight line."
  "Angiver pixel tykkelse højdepunktet linje."

  "Syntax Colors"
  "Syntaks Farver"

  "Tab Options"
  "Fanen Indstillinger"

  "Text Scrollbar Options"
  "Tekst rullebjælke Options"

  "Text color for all sidebar items that are not selected."
  "Tekst farve til alle sidebar elementer, der ikke er valgt."

  "Text color for all sidebar items that are selected."
  "Tekst farve til alle sidebar elementer, der er valgt."

  "ttk Widget Colors"
  "TTK Widget Farver"

}

# themer.tcl
msgcat::mcmset da {

  "   Show All"
  "Vis alle"

  "   Show Category"
  "Vis kategori"

  "   Show Color"
  "Vis Farve"

  "   Show Selected Option"
  "Vis valgte indstilling"

  "   Show Selected Value"
  "Valgt værdi"

  "Categories"
  "Bólkur"

  "Change Base Color"
  "Skift Base farve"

  "Choose Theme"
  "Elige un tema."

  "Custom Directory"
  "Brugervalgt katalog:"

  "Custom..."
  "Custom…"

  "Delete swatch?"
  "Slet farveprøve?"

  "Description"
  "Beskrivelse"

  "Details"
  "Detaljer"

  "Done"
  "Færdig"

  "Export"
  "Eksportér"

  "GIF Photo"
  "GIF Billeder"

  "Import"
  "Import"

  "Import BMP Data"
  "Import BMP data"

  "Import BMP Mask"
  "Import BMP Mask"

  "Import Error"
  "Import Fejl"

  "Import Theme File"
  "Import temafil"

  "Installation Directory"
  "Installation Vejviser"

  "Modifications"
  "ÆNDRINGER"

  "One-Color Bitmap"
  "One-farve bitmap"

  "Preview"
  "Forhåndsvis"

  "Relief: "
  "nødhjælp"

  "Save As:"
  "Gem som"

  "Save theme changes?"
  "Gem tema ændringer?"

  "Select Directory"
  "Vælg katalog"

  "Swatch"
  "finerprøve"

  "Swatch Colors"
  "Swatch Farver"

  "Table Filters"
  "Tabel Filtre"

  "The current theme has unsaved changes"
  "Den aktuelle tema har ikke-gemte ændringer"

  "Tree Style: "
  "Træ Stil:"

  "Two-Color Bitmap"
  "To-Color bitmap"

  "User Directory"
  "User Directory"

  "Value"
  "Værdi"

  "Value: "
  "Værdi:"

}

# themes.tcl
msgcat::mcmset da {

  "Theme"
  "Tema"

  "Theme:*"
  "Tema"

}

# tke.tcl
msgcat::mcmset da {

  "Import TKE theme?"
  "Importer TKE tema?"

  "Import TextMate theme?"
  "Importer TextMate tema?"

}

# tkedat.tcl
msgcat::mcmset da {

  "Unable to read"
  "Kan ikke læse fil."

}

# vim.tcl
msgcat::mcmset da {

  "File format unrecognized"
  "Filformatet blev ikke genkendt"

  "Filename directory does not exist"
  "Filnavn mappe findes ikke"

  "Folding method unrecognized"
  "Folde metode blev ikke genkendt"

  "Illegal modelines value"
  "Ulovlig modelines værdi"

  "Number width not a number"
  "Antal bredde ikke et nummer"

  "Shiftwidth value is not an integer"
  "Shiftwidth værdi er ikke et heltal"

  "Tabstop value is not an integer"
  "Tabulatorstop værdi er ikke et heltal"

  "Unrecognized vim option"
  "Ukendt vim mulighed"

}

# General
msgcat::mcmset da {

  "Cancel"
  "Annuller"

  "Close"
  "Luk"

  "Delete"
  "Slet"

  "Duplicate"
  "Dupliker"

  "Favorite"
  "foretrukken"

  "File Name:"
  "Filnavn"

  "Find"
  "Søg"

  "Move to Other Pane"
  "Flytter til andre Pane"

  "New File"
  "Ny fil"

  "None"
  "Ingen"

  "Open"
  "Åben"

  "Rename"
  "Omdøb"

  "Save"
  "Gem"

  "Save As"
  "Gem som"

  "Split View"
  "Opdel visning"

  "Theme Editor"
  "Tema Editor"

  "Unable to write"
  "Der kan ikke skrives"

  "Unfavorite"
  "Unfavorite"

}

