# api.tcl
msgcat::mcmset da {

  "Argument list to api::add_file was not an even key/value pair"
  "Argument liste til api :: add_file ikke var en selv nøgle / værdi par"

  "Argument list to api::add_file was not in the form 'filename [<option> <value>]*'"
  "Argument liste til api :: add_file ikke var i form &#39;filnavn [ <option><value> ] *"

  "get_home_directory can only be called within plugin code"
  "get_home_directory kan kun kaldes i plugin kode"

}

# bgproc.tcl
msgcat::mcmset da {

  "Unable to run system command (%s)"
  "Ikke køre systemet kommando (% s)"

}

# gui.tcl
msgcat::mcmset da {

  "%s, Line: %d, Column: %d"
  "% S, Line:% d, kolonne:% d"

  "Close All Tabs"
  "Luk alle faneblade"

  "Close Other Tab(s)"
  "Luk Other Tab (r)"

  "Close Other*"
  "Luk de andre faneblade"

  "Close Tab"
  "Luk faneblad"

  "Copyright %d-%d"
  "Copyright% d-% d"

  "Delete tab?"
  "Slet fane?"

  "Developer:"
  "Udvikler"

  "Email:"
  "E-mail:"

  "File attribute (%s) does not exist"
  "Filattribut (% s) eksisterer ikke"

  "File index is out of range"
  "File indeks er uden for rækkevidde"

  "Line: %d, Column: %d"
  "Line:% d, kolonne:% d"

  "Locked"
  "låst"

  "Move to Other Pane"
  "Flytter til andre Pane"

  "Move*"
  "bevæge"

  "Reload file?"
  "Genindlæs fil"

  "Save request"
  "Spar anmodning"

  "Total Lines: %d, Total Characters: %d"
  "Samlet Lines:% d, alt Tegn:% d"

  "Unable to find current file (tab: %s)"
  "Kunne ikke finde aktuelle fil (fane:% s)"

  "Untitled"
  "Untitled"

  "Version:"
  "Udgave:"

}

# markers.tcl
msgcat::mcmset da {

  "Marker name:"
  "Markør navn:"

}

# menus.tcl
msgcat::mcmset da {

  "                                  Profiling Report Sorted By (%s)"
  "Profilering Rapport Sorteret efter (% s)"

  "About TKE"
  "Om TKE"

  "Align cursors"
  "Juster markører"

  "All"
  "Alle"

  "Append next occurrence"
  "Vedhæft næste forekomst"

  "Clear All"
  "Ryd alt"

  "Close All"
  "Luk alle"

  "Comment"
  "Kommentar"

  "Copy"
  "Kopier"

  "Create new..."
  "Opret ny"

  "Create..."
  "Opret"

  "Cut"
  "Klip"

  "Edit"
  "Rediger"

  "Edit user"
  "Rediger bruger"

  "Edit..."
  "Rediger..."

  "File"
  "Filer"

  "Find"
  "Søg"

  "Find and Replace"
  "Find og erstat"

  "Find in files"
  "Find i filer..."

  "Find marker"
  "Find markør"

  "Find matching pair"
  "Find matchende par"

  "Format Text"
  "Formatér tekst"

  "Goto Last Tab"
  "Goto Last Tab"

  "Goto Next Tab"
  "Goto Next Tab"

  "Goto Other Pane"
  "Goto Anden Pane"

  "Goto Previous Tab"
  "Goto forrige fane"

  "Help"
  "Hjælp"

  "Hide Console"
  "Skjul Console"

  "Hide Sidebar"
  "Skjul sidebjælke"

  "Hide Status Bar"
  "Skjul statuslinje"

  "Hide Tab Bar"
  "Skjul tab-linje"

  "Import TextMate theme..."
  "Importer TextMate tema ..."

  "Indent"
  "Indryk"

  "Insert enumeration"
  "Indsæt tælling"

  "Install..."
  "Installer"

  "Launcher"
  "Launcher"

  "Lock"
  "Lås"

  "Menu Bindings"
  "Menu Bindinger"

  "Menu: About TKE"
  "Menu: About TKE"

  "Menu: Align cursors"
  "Menu: Juster markører"

  "Menu: Append next occurrence"
  "Menu: Append næste forekomst"

  "Menu: Close all tabs"
  "Luk alle faneblade"

  "Menu: Close current tab"
  "Luk dette faneblad"

  "Menu: Comment selected text"
  "Menu: Kommentar markeret tekst"

  "Menu: Copy selected text"
  "Menu: Kopiér markeret tekst"

  "Menu: Create new plugin"
  "Menu: Opret ny plugin"

  "Menu: Create new theme"
  "Opret nyt tema..."

  "Menu: Cut selected text"
  "Menu: Klip markeret tekst"

  "Menu: Disable Vim mode"
  "Menu: Disable Vim-tilstand"

  "Menu: Edit Tke theme"
  "Menu: Rediger Tke tema"

  "Menu: Edit snippets"
  "Menu: Rediger snippets"

  "Menu: Edit user menu bindings"
  "Menu: Rediger brugermenuskærmene bindinger"

  "Menu: Edit user preferences"
  "Menu: Rediger brugerindstillinger"

  "Menu: Enable Vim mode"
  "Menu: Aktiver Vim-tilstand"

  "Menu: Find"
  "Menu: Find"

  "Menu: Find and Replace"
  "Menu: Søg og erstat"

  "Menu: Find in files"
  "Find i filer"

  "Menu: Find matching character pair"
  "Menu: Find matchende tegn pair"

  "Menu: Find next occurrence"
  "Menu: Find næste forekomst"

  "Menu: Find previous occurrence"
  "Menu: Find forrige forekomst"

  "Menu: Goto last tab"
  "Menu: Goto sidste fane"

  "Menu: Goto next tab"
  "Menu: Goto næste fane"

  "Menu: Goto other pane"
  "Menu: Goto anden rude"

  "Menu: Goto previous tab"
  "Menu: Goto forrige fane"

  "Menu: Hide Tab Bar"
  "Menu: Hide Tab Bar"

  "Menu: Hide console"
  "Menu: Hide konsol"

  "Menu: Hide sidebar"
  "Menu: Hide sidebar"

  "Menu: Hide status bar"
  "Skjul statuslinje"

  "Menu: Import TextMate theme"
  "Menu: Import TextMate tema"

  "Menu: Indent selected text"
  "Menu: Led markeret tekst"

  "Menu: Insert enumeration"
  "Menu: Indsæt tælling"

  "Menu: Install plugin"
  "Menu: Installer plugin"

  "Menu: Lock file"
  "Menu: Lås fil"

  "Menu: Move to other pane"
  "Menu: Flyt til en anden rude"

  "Menu: New file"
  "Menu: Ny fil"

  "Menu: Open directory"
  "Menu: Åbn telefonbogen"

  "Menu: Open file"
  "Menu: Åbn fil"

  "Menu: Paste and format text from clipboard"
  "Menu: Indsæt og formatere tekst fra udklipsholder"

  "Menu: Paste text from clipboard"
  "Indsæt tekst fra udklipsholderen"

  "Menu: Quit application"
  "Menu: Afslut ansøgning"

  "Menu: Redo"
  "Menu: Redo"

  "Menu: Reload all plugins"
  "Menu: Opdater alle plugins"

  "Menu: Reload all snippets"
  "Menu: Opdater alle snippets"

  "Menu: Restart tke"
  "Menu: Genstart tke"

  "Menu: Save all files"
  "Menu: Gem alle filer"

  "Menu: Save file"
  "Menu: Gem filen"

  "Menu: Save file as"
  "Menu: Gem filen som"

  "Menu: Select all occurrences"
  "Menu: Vælg alle forekomster"

  "Menu: Select all text"
  "Markér al tekst"

  "Menu: Set user bindings to global bindings"
  "Menu: Indstil brugernes bindinger til globale bindinger"

  "Menu: Set user preferences to global preferences"
  "Menu: Indstil brugerindstillinger til globale præferencer"

  "Menu: Show Tab Bar"
  "Menu: Vis fanebladslinje"

  "Menu: Show console"
  "Menu: Vis konsol"

  "Menu: Show last profiling report"
  "Menu: Vis seneste profilering rapport"

  "Menu: Show sidebar"
  "Menu: Vis sidebjælke"

  "Menu: Show status bar"
  "Vis statuslinje"

  "Menu: Sort tabs"
  "Menu: Sorter faner"

  "Menu: Start profiling"
  "Menu: Start profilering"

  "Menu: Stop profiling"
  "Menu: Stop profilering"

  "Menu: Toggle split view mode"
  "Menu: Skift split visningstilstand"

  "Menu: Uncomment selected text"
  "Menu: Afkommentér markeret tekst"

  "Menu: Undo"
  "Menu: Fortryd"

  "Menu: Unindent selected text"
  "Menu: Afindryk markeret tekst"

  "Menu: Uninstall plugin"
  "Menu: Afinstaller plugin"

  "Menu: Unlock file"
  "Menu: Lås filen"

  "Menu: View User Guide"
  "Menu: Se brugervejledning"

  "Menu: View global menu bindings"
  "Menu: Se globale menu bindinger"

  "Menu: View global preferences"
  "Menu: Vis globale præferencer"

  "Move to other pane"
  "Flyt til en anden rude"

  "New"
  "Nyt"

  "Open Directory..."
  "Åbn mappe"

  "Open File..."
  "Åbn fil..."

  "Open Recent"
  "Åbn nylige"

  "Paste"
  "Sæt ind"

  "Paste and Format"
  "Indsæt og Format"

  "Plugins"
  "Plug-in"

  "Preferences"
  "Præferencer"

  "Profiling started"
  "Profilering i gang"

  "Profiling stopped"
  "Profilering stoppet"

  "Quit"
  "Afslut"

  "Redo"
  "Annuller Fortryd"

  "Reload"
  "Opdater"

  "Restart tke"
  "Genstart TKE"

  "Save All"
  "Gem alle"

  "Save As..."
  "Gem som"

  "Select All"
  "Vælg alle"

  "Select all occurrences"
  "Vælg alle forekomster"

  "Select next occurrence"
  "Vælg næste forekomst"

  "Select previous occurrence"
  "Vælg forrige forekomst"

  "Selected"
  "Valgt"

  "Set Syntax"
  "Set Syntaks"

  "Set Theme"
  "Set Theme"

  "Set user to global"
  "Indstil bruger til global"

  "Show Console"
  "Vis Console"

  "Show Last Profiling Report"
  "Vis Seneste Profiling Report"

  "Show Sidebar"
  "Vis sidebjælke"

  "Show Status Bar"
  "Vis statuslinje"

  "Show Tab Bar"
  "Vis tab-linje"

  "Show*Profiling*"
  "Vis * Profilering *"

  "Snippets"
  "Snippets"

  "Sort Tabs"
  "Sort Tabs"

  "Split view"
  "Delt visning"

  "Start Profiling"
  "Start Profilering"

  "Stop Profiling"
  "Stop Profilering"

  "Tabs"
  "Tab"

  "Text"
  "Tekst"

  "Theme Creator"
  "Tema Creator"

  "Tools"
  "Værktøjer"

  "Uncomment"
  "Afkommentér"

  "Undo"
  "Fortryd"

  "Unindent"
  "Afindryk"

  "Uninstall..."
  "afinstallere"

  "Unlock"
  "Lås"

  "User Guide"
  "Brugsanvisning"

  "View"
  "Vis"

  "View global"
  "Se global"

  "Vim Mode"
  "Vim-tilstand"

}

# plugins.tcl
msgcat::mcmset da {

  "ERROR:  Plugin name is not valid (only alphanumeric and underscores are allowed)"
  "FEJL: Plugin er ikke gyldigt (kun alfanumeriske og understregninger er tilladt)"

  "ERROR:  Unable to write plugin file"
  "FEJL: Kunne ikke skrive plugin fil"

  "Enter plugin name"
  "Indtast plugin navn"

  "Plugin %s installed"
  "Plugin% s installeret"

  "Plugin %s uninstalled"
  "Plugin% s afinstalleret"

  "Plugin Errors"
  "Plugin fejl"

  "Syntax errors found in selected plugins"
  "Syntaksfejl fundet i udvalgte plugins"

}

# sidebar.tcl
msgcat::mcmset da {

  "Add Parent Directory"
  "Moderkatalog"

  "Close Directory Files"
  "Luk Bliv Files"

  "Delete"
  "Slet"

  "Delete directory?"
  "Slet mappe?"

  "Delete file?"
  "Slet fil"

  "Duplicate"
  "Dupliker"

  "Make Current Working Directory"
  "Gør aktuelle arbejdsmappe"

  "New Directory"
  "Nyt bibliotek"

  "New File"
  "Ny fil"

  "Open"
  "Åben"

  "Refresh Directory Files"
  "Refresh directory-filer"

  "Remove Parent from Sidebar"
  "Fjern Parent fra Sidebar"

  "Remove from Sidebar"
  "Fjern fra Sidebar"

  "Rename"
  "Omdøb"

}

# snippets.tcl
msgcat::mcmset da {

  "Snippet: %s: %s"
  "Snippet:% s:% s"

  "Snippet: *"
  "Uddragsvisning: *"

}

# syntax.tcl
msgcat::mcmset da {

  "Syntax error in %s.syntax file"
  "Syntaks fejl i% s.syntax fil"

  "Syntax:  %s"
  "Syntaks:% s"

  "Theme:  %s"
  "Tema:% s"

}

# themer.tcl
msgcat::mcmset da {

  "Create"
  "Opret"

  "Create New Theme"
  "Opret nyt tema..."

  "Create custom"
  "Opret brugerdefinerede"

  "ERROR:  Unable to read %s"
  "FEJL: Kunne ikke læse% s"

  "ERROR:  Unable to write %s"
  "FEJL: Kunne ikke skrive% s"

  "Edit theme"
  "Edit tema"

  "Enter theme name"
  "Indtast temanavn"

  "Error:  Theme is not a supported theme"
  "Fejl: tema er ikke en understøttet tema"

  "Import"
  "Import"

  "Import TextMate Theme"
  "Import TextMate Theme"

  "Name:"
  "Navn:"

  "OK"
  "OK"

  "Reset"
  "Nulstil"

  "Select theme"
  "Vælg temafil"

}

# tke.tcl
msgcat::mcmset da {

  "ERROR:  %s"
  "FEJL:% s"

  "Edit theme?"
  "Rediger tema?"

  "Import TextMate theme?"
  "Importer TextMate tema?"

}

# tkedat.tcl
msgcat::mcmset da {

  "Unable to open %s for reading"
  "Kan ikke åbne%1 for læsning."

  "Unable to open %s for writing"
  "Kunne ikke åbne%1 til skrivning"

}

# General
msgcat::mcmset da {

  "Cancel"
  "Annuller"

  "Close"
  "Luk"

  "Find:"
  "finde"

  "Replace:"
  "Erstat"

  "Save"
  "Gem"

  "Save As"
  "Gem som"

}

