# api.tcl
msgcat::mcmset de {

  #"Argument list to api::add_file was not an even key/value pair"
  #"Argument-Liste für api::add_file war kein gültiges Key/Value Paar"

}

# bgproc.tcl
msgcat::mcmset de {

  "Unable to run system command"
  "Kann Systembefehl nicht ausführen"

}

# bitmap.tcl
msgcat::mcmset de {

  "Center image"
  "Bild zentrieren"

  "Flip image horizontally"
  "Bild horizontal spiegeln"

  "Flip image vertically"
  "Bild vertikal spiegeln"

  "Move image down"
  "Bild nach unten verschieben"

  "Move image left"
  "Bild nach links verschieben"

  "Move image right"
  "Bild nach rechts verschieben"

  "Move image up"
  "Bild nach oben verschieben"

  "Rotate image 90 degrees"
  "Bild um 90 Grad drehen"

  "Transform Tools"
  "Transformationswerkzeuge"

}

# diff.tcl
msgcat::mcmset de {

  "    End: "
  "    Ende: "

  "    Start: "
  "    Start: "

  "Enter difference command"
  "Anderen Befehl eingeben"

  "Enter starting file"
  "Startdatei angeben"

  "Update"
  "Aktualisieren"

}

# edit.tcl
msgcat::mcmset de {

  "File successfully written"
  "Datei erfolgreich geschrieben"

  "Filename already exists"
  "Dateiname ist bereits vorhanden"

  "Image URL"
  "Bild URL"

  "Link URL"
  "Link URL"

}

# emmet.tcl
msgcat::mcmset de {

  "Abbreviation"
  "Kurzbezeichnung"

  "Select File to Save"
  "Wählen Sie die zu speichernde Datei"

}

# files.tcl
msgcat::mcmset de {

  "Delete tab?"
  "Reiter löschen?"

  "Reload file?"
  "Datei neu laden?"

  "Unable to determine how to move to trash"
  "Kann Papierkorb-Funktion nicht ermitteln"

  "Unable to determine platform"
  "Kann Plattform nicht ermitteln"

  "Unable to write file"
  "Datei konnte nicht geschrieben werden"

  "Unable to write remote file"
  "Remote Datei konnte nicht geschrieben werden"

}

# gui.tcl
msgcat::mcmset de {

  "Case sensitivity"
  "Groß-und Kleinschreibung"

  "Close All Other Tabs"
  "Andere anderen Reiter schliessen"

  "Close All Tabs"
  "Alle Reiter schliessen"

  "Close All Tabs In Pane"
  "Alle Reiter im Bereich schliessen"

  "Close Other Tabs In Pane"
  "Alle anderen Reiter im Bereich schliessen"

  "Close Tab"
  "Reiter schliessen"

  "Column"
  "Spalte"

  "Copyright"
  "Copyright"

  "Credits"
  "Danksagungen"

  "Developer"
  "Entwickler"

  "Email"
  "Email"

  "Error"
  "Fehler"

  "Favorited"
  "Bevorzugt"

  "File already exists.  Use '!' to force an overwrite"
  "Datei existiert bereits.  Verwende '!' um zu überschreiben"

  "File index is out of range"
  "Datei-Index liegt außerhalb des Bereichs"

  "Hide Tab"
  "Reiter verbergen"

  "Image displayed in fill-in forms which closes the form UI.  Used in forms such as search, search/replace, and find in files."
  "Bild gefunden in Fill-in-Formulare, die die Form UI schließt. In Formen wie Suche verwendet, Suchen / Ersetzen, und finden in Dateien."

  "Image displayed in find field to search for next match."
  "Bild im Suchen-Feld zum nächsten Spiel suchen angezeigt."

  "Image displayed in find field to search for previous match."
  "Bild im Suchfeld nach vorherigen Übereinstimmung suchen angezeigt."

  "Image used in tab menus to indicate that the file is associated with a difference view."
  "Bild in Reiter Menüs verwendet, um anzuzeigen, dass die Datei mit einem Unterschied Ansicht zugeordnet."

  "Image used in tab menus to indicate that the file is locked."
  "Bild in Reiter Menüs verwendet werden, um anzugeben, dass die Datei gesperrt ist."

  "Image used in tab menus to indicate that the file is readonly."
  "Bild in Reiter Menüs verwendet, um anzuzeigen, dass die Datei schreibgeschützt."

  "Image used in tab to indicate that the tab contains a difference view."
  "Bild im Register verwendet werden, um anzuzeigen, dass das Register enthält einen Unterschied sehen."

  "Image used in tab to indicate that the tab's file is readonly."
  "Bild im Register verwendet, um anzuzeigen, dass die Akten der Reiter ist schreibgeschützt."

  "Image used in tab to indicate that the tab’s file is locked."
  "Bild in Reiter verwendet, um anzugeben, dass die Reiter Datei gesperrt ist."

  "Image used in tab which, when clicked, closes the tab."
  "Bild in Register, die, wenn geklickt wird, schließt das Register verwendet."

  "Image used in the preferences window in the Advanced tab."
  "Bild im Fenster"

  "Image used in the preferences window in the Appearance tab."
  "Bild im Fenster"

  "Image used in the preferences window in the Documentation tab."
  "Bild im Einstellungsfenster auf der Reiter"

  "Image used in the preferences window in the Editor tab."
  "Bild im Einstellungsfenster auf der Reiter"

  "Image used in the preferences window in the Emmet tab."
  "Bild im Einstellungsfenster auf der Reiter"

  "Image used in the preferences window in the Find tab."
  "Bild im Fenster"

  "Image used in the preferences window in the General tab."
  "Bild im Fenster"

  "Image used in the preferences window in the Plugins tab."
  "Bild im Einstellungsfenster auf der Reiter"

  "Image used in the preferences window in the Shortcuts tab."
  "Bild im Einstellungsfenster auf der Reiter"

  "Image used in the preferences window in the Sidebar tab."
  "Bild im Einstellungsfenster auf der Reiter"

  "Image used in the preferences window in the Snippets tab."
  "Bild im Einstellungsfenster auf der Reiter"

  "Image used in the preferences window in the View tab."
  "Bild im Fenster"

  "Image used in the preferences window to indicate that a table item is deselected."
  "Bild im Einstellungsfenster verwendet, um anzugeben, dass ein Tabellenelement deaktiviert ist."

  "Image used in the preferences window to indicate that a table item is selected."
  "Bild im Einstellungsfenster verwendet, um anzugeben, dass ein Tabellenelement ausgewählt ist."

  "Image used in the preferences window to indicate that something is true."
  "Bild im Einstellungsfenster verwendet, um anzuzeigen, dass etwas wahr ist."

  "Images used in tab which will be displayed when the mouse enters the close button area"
  "Bilder, die in der Reiter verwendet werden, die angezeigt wird, wenn die Maus in die Schaltfläche &quot;Schliessen&quot; gelangt"

  "In"
  "In"

  "License"
  "Lizenz"

  "Locked"
  "Lock"

  "Move"
  "Verschieben"

  "Must be in multicursor mode to insert numbers"
  "Muss im multicursor-Modus um Zahlen einzusetzen"

  "No write permissions.  Use '!' to force write."
  "Keine Schreibrechte.  Verwende '!' um das Schreiben zu erzwingen"

  "Release Type"
  "Releasetyp"

  "Replace"
  "Ersetzen"

  "Save request"
  "Anfrage speichern"

  "Starting number:"
  "Startnummer:"

  "Tcl/Tk Version"
  "Tcl/Tk-Version"

  "Total Characters"
  "Anzahl Zeichen"

  "Total Lines"
  "Anzahl Zeilen"

  "Unable to successfully parse number string"
  "Nummernfolge kann nicht analysiert werden"

  "for"
  "für"

}

# ipanel.tcl
msgcat::mcmset de {

  "Binary"
  "Binary"

  "Close Panel"
  "Panel schliessen"

  "Counts"
  "Anzahl"

  "Modified"
  "Verändert"

  "No"
  "Nein"

  "Read Time"
  "Lesezeit"

  "Update Info"
  "Informationen aktualisieren"

  "Yes"
  "Ja"

  "value copied to clipboard"
  "Wert in die Zwischenablage kopiert"

}

# markers.tcl
msgcat::mcmset de {

  "Marker name:"
  "Marker Namen:"

}

# menus.tcl
msgcat::mcmset de {

  "About"
  "Über"

  "Absolute"
  "Absolut"

  "Absolute line numbering"
  "Absolute Zeilennummerierung"

  "Add Next Line"
  "Nächste Zeile hinzufügen"

  "Add Previous Line"
  "Vorherige Zeile hinzufügen"

  "Add next line to selection"
  "Füge nächste Zeile zur Auswahl hinzu"

  "Add previous line to selection"
  "Vorherige Zeile zur Auswahl hinzufügen"

  "Align Cursors Only"
  "Cursor nur ausrichten"

  "Align Cursors and Text"
  "Cursor und Text ausrichten"

  "Align Panes"
  "Ausrichten der Scheiben"

  "Align current lines in both panes"
  "Stromleitungen in beide Bereiche ausrichten"

  "Align cursors and text"
  "Cursor und Text ausrichten"

  "Align cursors only"
  "Ausrichten der Cursor nur"

  "All Levels"
  "Alle Schwierigkeitsgrade"

  "All language-specific settings for the current session will be removed and the global settings will be applied for the specified language."
  "Alle Sprachen-spezifische Einstellungen für die aktuelle Session gelöscht werden und die globalen Einstellungen werden für die angegebene Sprache angewendet werden."

  "All language-specific settings will be removed and the global settings will be applied for the specified language."
  "Alle Sprachen-spezifische Einstellungen werden entfernt und die globalen Einstellungen werden für die angegebene Sprache angewendet werden."

  "Append current find text to selection"
  "Auswahl aktueller finden Sie Text hinzufügen"

  "Auto-Indent"
  "Auto-Einzug"

  "Balance Inward"
  "Bilanz nach innen"

  "Balance Outward"
  "Bilanz nach außen"

  "Balance tag pair moving inward"
  "Balance-Tag-paar nach innen verschieben"

  "Balance tag pair moving outward"
  "Balance-Tag-paar nach außen verschieben"

  "Bold"
  "Fett"

  "Bubble Down"
  "Blase nach unten"

  "Bubble Up"
  "Blase bis"

  "Bubble lines down one line"
  "Blase Linien eine Zeile nach unten"

  "Bubble lines up one line"
  "Blase-Linien eine Zeile nach oben"

  "Change Working Directory"
  "Arbeitsverzeichnis ändern"

  "Change working directory"
  "Arbeitsverzeichnis ändern"

  "Check for update"
  "Nach Update suchen"

  "Checkbox"
  "Checkbox"

  "Classic Mac"
  "Klassischer Mac"

  "Clear All"
  "Alle löschen"

  "Close All"
  "Alle schliessen"

  "Close All Folds"
  "Schliessen Sie alle Falten"

  "Close Current"
  "Schliesse aktuelle"

  "Close Current Fold"
  "Schliessen der aktuellen Fold"

  "Close Selected Folds"
  "Schliessen ausgewählt Falten"

  "Close all folds"
  "Schliessen Sie alle Falten"

  "Close all tabs"
  "Alle Reiter schliessen"

  "Close current session"
  "Aktuelle Session beenden"

  "Close current tab"
  "Aktuellen Reiter schliessen"

  "Close fold at current line - all levels"
  "Enge Falte an aktuelle Zeile - alle Stufen"

  "Close fold at current line - one level"
  "Enge Falte an aktuelle Zeile - eine Ebene"

  "Close selected folds - all levels"
  "Schliessen Sie ausgewählte Folds - alle Stufen"

  "Close selected folds - one level"
  "Ausgewählte Falten - eine Ebene zu schliessen"

  "Code"
  "Code"

  "Command"
  "Befehl"

  "Command Result"
  "Befehls-Ergebnis"

  "Convert case to lower"
  "Konvertieren Sie Fall zu niedrigeren"

  "Convert case to title"
  "Fall in Titel konvertieren"

  "Convert case to upper"
  "Oberen Fall umwandeln"

  "Copy text"
  "Text kopieren"

  "Create Fold From Selection"
  "Falten aus Auswahl erstellen"

  "Create at Current Line"
  "Zur aktuellen Zeile erstellen"

  "Create fold from selection"
  "Falten aus Auswahl erstellen"

  "Create marker at current line"
  "Markierung zur aktuellen Zeile erstellen"

  "Create new plugin"
  "Neues Plugin erstellen"

  "Current Bounded Text"
  "Aktuelle umrahmter Text"

  "Current Paragraph"
  "Aktueller Absatz"

  "Current Sentence"
  "Aktueller Satz"

  "Cut"
  "Ausschneiden"

  "Cut text"
  "Text ausschneiden"

  "Decrement by 0.1"
  "Verringern um 0,1"

  "Decrement by 1"
  "Verringern um 1"

  "Decrement by 10"
  "Verringern um 10"

  "Decrement number by 0.1"
  "Verringere Zahl um 0,1"

  "Decrement number by 1"
  "Verringere Zahl um 1"

  "Decrement number by 10"
  "Verringern Anzahl um 10"

  "Delete All Folds"
  "Löschen Sie alle Falten"

  "Delete Current Fold"
  "Löschen der aktuellen Fold"

  "Delete Selected Folds"
  "Ausgewählte Löschen Falten"

  "Delete Session"
  "Session löschen"

  "Delete User"
  "Nutzer löschen"

  "Delete all folds"
  "Löschen Sie alle Falten"

  "Delete all selected folds"
  "Löschen Sie alle ausgewählte Aufteilungen"

  "Delete current file"
  "Aktuelle Datei löschen"

  "Delete fold at current line"
  "Falte an aktuelle Zeile löschen"

  "Delete language preferences?"
  "Spracheinstellungen löschen?"

  "Delete session"
  "Session löschen"

  "Delete session language preferences?"
  "Spracheinstellungen der Session löschen?"

  "Delete template"
  "Vorlage löschen"

  "Disable Vim mode"
  "Vim-Modus deaktivieren"

  "Disable code folding"
  "Deaktivieren Sie die Code-Faltung"

  "Disable two-pane scrolling Synchronization"
  "Zwei-Fenster scrollen Synchronisation deaktivieren"

  "Display Text Info"
  "Text-Info anzeigen"

  "Display text information"
  "Textinformation anzeigen"

  "Duplicate current file"
  "Aktuelle Datei duplizieren"

  "Edit Custom Abbreviations"
  "Eigene Abkürzungen bearbeiten"

  "Edit Language"
  "Sprache bearbeiten"

  "Edit Session"
  "Session bearbeiten"

  "Edit User"
  "Benutzer bearbeiten"

  "Edit custom Emmet abbreviations"
  "Bearbeiten von benutzerdefinierten Emmet-Abkürzungen"

  "Edit language snippets"
  "Sprache-Schnipsel zu bearbeiten"

  "Edit session current language preferences"
  "Spracheinstellungen der aktuellen Session bearbeiten"

  "Edit session global preferences"
  "Globale Session Einstellungen bearbeiten"

  "Edit template"
  "Vorlage bearbeiten"

  "Edit user current language preferences"
  "Aktuelle Sprache Benutzereinstellungen bearbeiten"

  "Edit user global preferences"
  "Globale Voreinstellungen des Benutzers bearbeiten"

  "Edit user snippets"
  "Bearbeiten von Benutzer-Ausschnitte"

  "Enable Code Folding"
  "Aktivieren Code-Faltung"

  "Enable Synchronized Scrolling"
  "Synchrone Bildlauf aktivieren"

  "Enable Vim mode"
  "Vim-Modus aktivieren"

  "Enable two-pane scrolling synchronization"
  "Zwei-Fenster scrollen Synchronisierung aktivieren"

  "Encode/Decode Image to Data:URL"
  "Codieren/Decodieren Bild Daten: URL"

  "Encode/Decode image to data:URL"
  "Bild, Daten: URL Codieren/Decodieren"

  "Enter selection mode"
  "Auswahl-Modus wählen"

  "Enumeration"
  "Liste"

  "Evaluate Math Expression"
  "Auswerten von mathematischen Ausdrücken"

  "Evaluate the current math expression"
  "Bewerten Sie den aktuellen mathematischen Ausdruck"

  "Expand Abbreviation"
  "Erweitern Sie die Abkürzung"

  "Expand Emmet abbreviation"
  "Erweitern Sie Emmet Abkürzung"

  "Export As"
  "Exportieren als"

  "Export Custom Themes"
  "Exportieren von benutzerdefinierten Designs"

  "Export complete"
  "Export abgeschlossen"

  "Export file contents"
  "Dateiinhalte exportieren"

  "Favorite file"
  "Lieblings-file"

  "File Contents"
  "Dateiinhalte"

  "Find In Files"
  "In Dateien suchen"

  "Find Matching Bracket"
  "Passende Klammer suchen"

  "Find Next"
  "Weitersuchen"

  "Find Next Bracket Mismatch"
  "Finden Sie die nächste Klammer Mismatch"

  "Find Previous"
  "Vorheriges Vorkommen suchen"

  "Find Previous Bracket Mismatch"
  "Vorherige Klammer Missverhältnis zu finden"

  "Find and Replace"
  "Suchen und Ersetzen"

  "Find in files"
  "In Dateien suchen"

  "Find matching character pair"
  "Finden Sie passende paar Zeichen"

  "Find next mismatching bracket"
  "Nächste unpassende Klammer finden"

  "Find previous mismatching bracket"
  "Vorherigen unpassende Halterung zu finden"

  "Folding"
  "Folding"

  "Format"
  "Format"

  "Format Text"
  "Text formatieren"

  "Format indentation for text"
  "Format-Einzugs für text"

  "From Clipboard"
  "Aus Zwischenablage"

  "Global"
  "Global"

  "Go to Matching Pair"
  "Gehen Sie zu passenden paar"

  "Go to matching tag pair"
  "Gehen Sie auf passende Tag-paar"

  "Go to next edit point"
  "Gehen Sie zum nächsten Punkt bearbeiten"

  "Go to previous edit point"
  "Zum vorherigen Schnittpunkt gehen"

  "Goto Last Tab"
  "Goto Last Tab"

  "Goto Next Tab"
  "Goto Next Tab"

  "Goto Other Pane"
  "Goto Andere Pane"

  "Goto Previous Tab"
  "Zum vorherigen Tab"

  "Goto last tab"
  "Letzten Tab springen"

  "Goto next difference"
  "Nächster Unterschied springen"

  "Goto next tab"
  "Nächsten Tab springen"

  "Goto other pane"
  "GOTO andere Bereich"

  "Goto previous difference"
  "GOTO Vorheriger Unterschied"

  "Goto previous tab"
  "Voriger Tab"

  "Header"
  "Kopfzeile"

  "Help"
  "Hilfe"

  "Hide All Tabs"
  "Alle ausblenden"

  "Hide Current Tab"
  "Aktuelle Reiter ausblenden"

  "Hide Line Numbers"
  "Ausblenden von Zeilennummern"

  "Hide Marker Map"
  "Marker-Karte ausblenden"

  "Hide Meta Characters"
  "Meta-Zeichen ausblenden"

  "Hide Sidebar"
  "Navigationsbereich ausblenden"

  "Hide Status Bar"
  "Statusanzeige ausblenden"

  "Hide Tab Bar"
  "Ausblenden Tab Bar"

  "Hide Tcl Console"
  "Tcl Konsole ausblenden"

  "Hide Tcl console"
  "Tcl Konsole ausblenden"

  "Hide line numbers"
  "zeilennummern zeilen nummern"

  "Hide marker map"
  "Markierung Karte ausblenden"

  "Hide meta characters"
  "Meta-Zeichen ausblenden"

  "Hide sidebar"
  "Sidebar ausblenden"

  "Hide status bar"
  "Statusleiste"

  "Hide tab bar"
  "Tab-Leiste ausblenden"

  "Highlight"
  "Highlight"

  "Image"
  "Bild"

  "Increment by 0.1"
  "Schrittweite 0,1"

  "Increment by 1"
  "INCR"

  "Increment by 10"
  "INCR"

  "Increment number by 0.1"
  "Anzahl der Schrittweite von 0,1"

  "Increment number by 1"
  "Inkrement-Anzahl um 1"

  "Increment number by 10"
  "Inkrement Zahl durch 10"

  "Indent"
  "Einzug"

  "Indent Off"
  "Einzug ab"

  "Indent selected text"
  "Ausgewählten Text Einrücken"

  "Indentation"
  "Einrückung"

  "Insert bold formatting"
  "Einfügen, Fettformatierung"

  "Insert checklist formatting"
  "Checkliste Formatierung einfügen"

  "Insert code formatting"
  "Fügen Sie Codeformatierung"

  "Insert command result after current line"
  "Befehl nach der aktuellen Zeile einfügen"

  "Insert enumeration"
  "-Enumeration einfügen"

  "Insert file contents after current line"
  "Inhalt der Datei nach der aktuellen Zeile einfügen"

  "Insert from clipboard"
  "Aus Zwischenablage einfügen"

  "Insert header style"
  "Headerformat einfügen"

  "Insert highlight formatting"
  "Einfügen Formatierung markieren"

  "Insert image formatting"
  "Fügen Sie Bild formatieren"

  "Insert italics formatting"
  "Legen Sie kursiv formatieren"

  "Insert line above current line"
  "Zeile oberhalb der aktuellen Zeile einfügen"

  "Insert line below current line"
  "Fügen Sie die Zeile unterhalb der aktuellen Zeile"

  "Insert link formatting"
  "Legen Sie Linkformatierung"

  "Insert ordered list formatting"
  "Geordnete Liste Formatierung einfügen"

  "Insert snippet"
  "Ausschnitt einfügen"

  "Insert strikethrough formatting"
  "Legen Sie durchgestrichen formatieren"

  "Insert subscript formatting"
  "Tiefgestellten Formatierung einfügen"

  "Insert superscript formatting"
  "Hochgestellte Formatierung einfügen"

  "Insert underline formatting"
  "Legen Sie die Unterstreichung"

  "Insert unordered list formatting"
  "Ungeordnete Liste Formatierung einfügen"

  "Install"
  "Installieren"

  "Install plugin"
  "Plugin installieren"

  "Italics"
  "Kursiv "

  "Join Lines"
  "Zeilen verbinden"

  "Join lines"
  "Zeilen verbinden"

  "Jump Backward"
  "Rückwärts springen"

  "Jump Forward"
  "Vorwärts springen"

  "Jump To Line"
  "Wechseln in Zeile"

  "Jump backward"
  "Rückwärts springen"

  "Jump forward"
  "Vorwärts springen"

  "Jump to Next Fold Mark"
  "Springe zum nächsten Falte Mark"

  "Jump to Previous Fold Mark"
  "Springe zum vorherigen Fold-Mark"

  "Jump to line"
  "Wechseln in Zeile"

  "Jump to the next fold indicator"
  "Springen Sie zum nächsten Falte Indikator"

  "Jump to the previous fold indicator"
  "Springen Sie zum vorherigen Falte Indikator"

  "Line Above Current"
  "Linie über Strom"

  "Line Below Current"
  "Unter der aktuellen Zeile"

  "Line Ending"
  "Zeilenendetyp"

  "Line Number"
  "Zeilennummer"

  "Line Numbering"
  "Zeilennummerierung"

  "Line Wrapping"
  "Zeilenumbruch"

  "Link"
  "Link"

  "Lock"
  "Sperren"

  "Lock file"
  "Sperrdatei"

  "Lower Case"
  "Kleinb."

  "Markers"
  "Marker"

  "Menu"
  "Menü"

  "Merge Lines"
  "Zusammenführen von Linien"

  "Merge Panes"
  "Zusammenführen von Scheiben"

  "Merge panes"
  "Zusammenführen von Scheiben"

  "Move Cursors Down"
  "Cursor nach unten verschieben"

  "Move Cursors Left"
  "Cursor links verschieben"

  "Move Cursors Right"
  "Cursor rechts bewegen"

  "Move Cursors Up"
  "Cursor nach oben"

  "Move cursor to bottom of screen"
  "Cursor an den unteren Bildschirmrand"

  "Move cursor to end of current line"
  "Bewegen Sie Cursor am Ende der aktuellen Zeile"

  "Move cursor to first line"
  "Cursor zur ersten Zeile bewegen"

  "Move cursor to last line"
  "Cursor zur letzten Zeile bewegen"

  "Move cursor to middle of screen"
  "Cursor in der Mitte des Bildschirms"

  "Move cursor to next page"
  "Cursor an Nächste Seite"

  "Move cursor to next word"
  "Cursor an das nächste Wort"

  "Move cursor to previous page"
  "Cursor an vorherige Seite"

  "Move cursor to previous word"
  "Cursor an vorherigen Wort"

  "Move cursor to start of current line"
  "Bewegen Sie Cursor zum Beginn einer aktuellen Zeile"

  "Move cursor to top of screen"
  "Cursor an den oberen Bildschirmrand"

  "Move multicursors down one line"
  "Multicursors eine Zeile nach unten verschieben"

  "Move multicursors left one line"
  "Multicursors Links eine Zeile weiter"

  "Move multicursors right one line"
  "Multicursors rechts eine Zeile weiter"

  "Move multicursors up one line"
  "Multicursors eine Zeile nach oben verschieben"

  "Move to First Line"
  "Zur ersten Zeile bewegen"

  "Move to Last Line"
  "In letzter Linie verschieben"

  "Move to Line End"
  "Ende Zeile bewegen"

  "Move to Line Start"
  "Start Linie verschieben"

  "Move to Next Page"
  "Zur nächsten Seite wechseln"

  "Move to Next Word"
  "Wechseln zum nächsten Wort"

  "Move to Previous Page"
  "Zur vorherigen Seite wechseln"

  "Move to Previous Word"
  "Wechseln zum vorherigen Wort"

  "Move to Screen Bottom"
  "Auf dem unteren Bildschirm verschieben"

  "Move to Screen Middle"
  "In der Mitte des Bildschirms verschieben"

  "Move to Screen Top"
  "Auf dem oberen Bildschirm verschieben"

  "Move to other pane"
  "Wechseln zu anderen Bereich"

  "New From Template"
  "Neue Vorlage"

  "New Window"
  "Neues Fenster"

  "New file"
  "Neue Datei"

  "New file from template"
  "Neue Datei aus Vorlage"

  "New window"
  "Neues Fenster"

  "Next Difference"
  "Nächster Unterschied"

  "Next Edit Point"
  "Punkt bearbeiten"

  "One Level"
  "Eine Ebene"

  "Open All Folds"
  "Öffnen Sie alle Falten"

  "Open Current Fold"
  "Offenen aktuelle Fold"

  "Open Directory"
  "Verzeichnis öffnen"

  "Open Favorite"
  "Favorit öffnen"

  "Open File"
  "Datei öffnen"

  "Open Recent"
  "Zuletzt verwendet"

  "Open Remote"
  "Remote öffnen"

  "Open Selected Folds"
  "Open ausgewählt Falten"

  "Open all folds"
  "Öffnen Sie alle Falten"

  "Open directory"
  "Verzeichnis öffnen"

  "Open file"
  "Datei öffnen"

  "Open fold at current line - all levels"
  "Offene Klappe an aktuelle Zeile - alle Stufen"

  "Open fold at current line - one level"
  "Offene Klappe an aktuelle Zeile - eine Ebene"

  "Open folds to show cursor"
  "Offenen Falten Cursor zeigen"

  "Open remote file or directory"
  "Offenen remote-Datei oder ein Verzeichnis"

  "Open selected folds - all levels"
  "Offenen ausgewählten Folds - alle Stufen"

  "Open selected folds - one level"
  "Offenen ausgewählten Falten - eine Ebene"

  "Ordered Bullet"
  "Bestellten Bullet"

  "Panes"
  "Bereiche"

  "Paste"
  "Einfügen"

  "Paste and Format"
  "Einfügen und formatieren"

  "Paste and format text from clipboard"
  "Text aus der Zwischenablage einfügen und formatieren"

  "Paste text from clipboard"
  "Text aus der Zwischenablage einfügen"

  "Plugin Developer Guide"
  "Handbuch für Plugin-Entwickler"

  "Previous Difference"
  "Vorheriger Unterschied"

  "Previous Edit Point"
  "Vorherige Schnittmarke"

  "Profiling Report Sorted By"
  "Profiling Bericht sortiert"

  "Profiling started"
  "Profiling begonnen"

  "Profiling stopped"
  "Profiling gestoppt"

  "Quit"
  "Beenden"

  "Quit application"
  "Anwendung beenden"

  "Recent Directories"
  "Aktuelle Verzeichnisse"

  "Recent Files"
  "Aktuelle Dateien"

  "Redo"
  "Wiederholen"

  "Reflect CSS Value"
  "CSS-Werte"

  "Reflect current CSS value"
  "CSS-Stromwert zu reflektieren"

  "Relative"
  "Relativ"

  "Relative line numbering"
  "Relative Zeilennummerierung"

  "Reload"
  "Neu laden"

  "Reload all plugins"
  "Plugins neu laden"

  "Reload snippets"
  "Reload-Ausschnitte"

  "Reload template information"
  "Laden der Vorlageninformationen"

  "Remove All From Current Buffer"
  "Entfernen Sie alles aus aktuellen Puffer"

  "Remove All Markers"
  "Entfernen Sie alle Markierungen"

  "Remove Formatting"
  "Formatierung entfernen"

  "Remove From Current Line"
  "Entfernen Sie aus der aktuellen Zeile"

  "Remove Tag"
  "Schlagwort entfernen"

  "Remove all markers"
  "Alle Intervalle entfernen"

  "Remove all markers from current buffer"
  "Entfernen Sie alle Markierungen aus aktuellen Puffer"

  "Remove formatting from selected text"
  "Entfernen Sie aus ausgewählten Text Formatierung"

  "Remove marker from current line"
  "Markierung von aktuellen Zeile entfernen"

  "Remove tag"
  "Entferne Markierung"

  "Rename current file"
  "Benennen Sie die aktuelle Datei"

  "Reopen File"
  "Datei erneut laden"

  "Reopen current file"
  "Aktuelle Datei erneut laden"

  "Replace Line With Script"
  "Ersetze die Zeile mit Skript"

  "Replace line with script"
  "Ersetze die Zeile mit Skript"

  "Restart"
  "Neustart"

  "Run"
  "Durchlauf"

  "Run theme editor"
  "Motiv-Bearbeitung"

  "Save All"
  "Alle speichern"

  "Save As Remote"
  "Speichern (entfernt)"

  "Save As Template"
  "Als Vorlage speichern"

  "Save Current"
  "Aktuelle Oberfläche speichern"

  "Save Selection As"
  "Auswahl speichern"

  "Save all files"
  "Alle Dateien speichern"

  "Save current session"
  "Aktuelle Session speichern"

  "Save file"
  "Datei speichern"

  "Save file as"
  "Datei speichern unter"

  "Save file as remote file"
  "Datei speichern unter (entfernt)"

  "Save file as template"
  "Datei als Vorlage speichern"

  "Save selected lines"
  "Gewählte Zeilen speichern"

  "Save sessions as"
  "Sesion speichern unter"

  "Search References"
  "Referenzen durchsuchen"

  "Search language reference documentation"
  "Suche Sprache Referenzdokumentation"

  "Search reference documentation"
  "Suche Referenz-Dokumentation"

  "Select"
  "Auswählen"

  "Select All Matches"
  "Wählen Sie alle Spiele"

  "Select Current Match"
  "Wählen Sie aktuelle Match"

  "Select Mode"
  "Auswahlmodus"

  "Select Next Item"
  "Nächstes Element wählen"

  "Select Previous Item"
  "Voriges Element wählen"

  "Select all find matches"
  "Wählen Sie alle zu finden"

  "Select all text"
  "Ganzen Text wählen"

  "Select current bracketed text, strings or comment block"
  "Wählen Sie einen aktuellen Klammertext, Strings oder Kommentarblock aus"

  "Select current line"
  "Aktuelle Zeile auswählen"

  "Select current paragraph"
  "Wählen Sie den aktuellen Absatz aus"

  "Select current sentence"
  "Wählen Sie den aktuellen Satz aus"

  "Select current word"
  "Wählen Sie das aktuelle Wort aus"

  "Select next tag item"
  "Wählen Sie nächsten tag"

  "Select previous tag item"
  "Vorherigen Tag Element auswählen"

  "Send Bug Report"
  "Fehlerbericht senden"

  "Send Feedback"
  "Schicken Sie Feedback"

  "Send bug report"
  "Fehler Bericht"

  "Send feedback"
  "Feedback senden"

  "Set Syntax"
  "Stellen Syntax"

  "Set Theme"
  "Theme setzen"

  "Set current file line ending to CR for Classic Mac"
  "Festlegen der aktuellen Datei Zeilenende CR für Classic Mac"

  "Set current file line ending to CRLF for Windows"
  "Festlegen der aktuellen Datei Zeilenende CRLF für Windows"

  "Set current file line ending to LF for Unix"
  "Festlegen der aktuellen Datei Zeilenende zu LF für Unix"

  "Set indent mode to"
  "Gedankenstrich Modus"

  "Show All Tabs"
  "Alle Reiter zeigen"

  "Show Cursor"
  "Cursor anzeigen"

  "Show Diagnostic Logfile"
  "Diagnostische Logfile zeigen"

  "Show File Difference"
  "Karte Datei Unterschied"

  "Show Installed"
  "installiert"

  "Show Last Profiling Report"
  "Zeige die letzten Profiling melden"

  "Show Line Numbers"
  "Zeilennummern anzeigen"

  "Show Marker Map"
  "Marker anzeigen"

  "Show Meta Characters"
  "Meta-Zeichen anzeigen"

  "Show Selected Line Change"
  "Anzeigen der markierten Zeile ändern"

  "Show Sidebar"
  "Seitenleiste zeigen"

  "Show Status Bar"
  "Statuszeile zeigen"

  "Show Tab Bar"
  "Reiter zeigen"

  "Show Tcl Console"
  "Tcl Konsole zeigen"

  "Show Tcl console"
  "Tcl Konsole zeigen"

  "Show diagnostic logfile"
  "Diagnose Logfile zeigen"

  "Show file difference"
  "Zeige Dateiunterschiede"

  "Show installed plugins"
  "Installierte Plugins zeigen"

  "Show last profiling report"
  "Anzeigen der letzten profiling Bericht"

  "Show meta characters"
  "Meta-Zeichen anzeigen"

  "Show plugin developer guide"
  "Plugin-Entwickler Messeführer"

  "Show selected line change"
  "Anzeigen der markierten Zeile ändern"

  "Smart Indent"
  "Smart Gedankenstrich"

  "Sort Tabs"
  "Reiter sortieren"

  "Sort tabs"
  "Reiter sortieren"

  "Split/Join Tag"
  "Split/Join-Tag"

  "Split/Join tag"
  "Split/Join-tag"

  "Start Profiling"
  "Starten Profiling"

  "Start profiling"
  "Profilerstellung starten"

  "Stop Profiling"
  "Stoppen Profiling"

  "Stop profiling"
  "Profilerstellung beenden"

  "Strikethrough"
  "Durchstreichen"

  "Subscript"
  "Tiefstellen"

  "Superscript"
  "Hochstellen"

  "Switch To"
  "Wechseln zu"

  "Switch to session"
  "Wechsle zu Session"

  "Tabs"
  "Reiter"

  "Tips & Tricks"
  "Tipps & Tricks"

  "Title Case"
  "Titel-Fall"

  "Toggle Case"
  "Knebel-Fall"

  "Toggle Comment"
  "Knebel-Kommentar"

  "Toggle bird's eye view mode"
  "Vogels-Eye-View-Modus umschalten"

  "Toggle case of current character"
  "Knebel-Fall von aktuellen Zeichen"

  "Toggle comment"
  "Knebel-Kommentar"

  "Toggle split view mode"
  "Knebel geteilter Ansichtsmodus"

  "Toggle tag/rule comment"
  "Toggle Tag/Regel Kommentar"

  "Tools"
  "Werkzeug"

  "Transform"
  "Transformieren"

  "Unable to delete file"
  "Löschen nicht möglich"

  "Unable to write export file"
  "Datei konnte nicht geschrieben werden"

  "Underline"
  "Unterstrichen"

  "Undo"
  "Rückgängig"

  "Unfavorite file"
  "Unfavorite Datei"

  "Unindent"
  "Unindent"

  "Unindent selected text"
  "Markierten Text ausrücken"

  "Uninstall"
  "Deinstallieren"

  "Uninstall plugin"
  "Plugin entfernen"

  "Unix"
  "Unix"

  "Unlock"
  "Entsperren"

  "Unlock file"
  "Datei entsperren"

  "Unordered Bullet"
  "Ungeordnete Bullet"

  "Update Image Size"
  "Bild aktualisieren"

  "Update img tag width and height attributes"
  "Img-Tag Width und Height Attribute aktualisieren"

  "Upper Case"
  "Grossbuchstaben"

  "User Guide"
  "Benutzerhandbuch"

  "View"
  "Ansicht"

  "View tips & tricks articles"
  "Tipps & tricks Artikel anzeigen"

  "View user guide"
  "Benutzerhandbuch ansehen"

  "Vim Mode"
  "Vim-Modus"

  "Windows"
  "Windows"

  "Wrap With Abbreviation"
  "Wrap mit Abkürzung"

  "Wrap tag with Emmet abbreviation"
  "Verpacken Sie-Tag mit Emmet Abkürzung"

  "formatting"
  "Formatieren"

}

# plugins.tcl
msgcat::mcmset de {

  "Always grant from developer"
  "Immer vom Entwickler gewähren"

  "ERROR"
  "Fehler"

  "ERROR:  Plugin name already exists"
  "ERROR:  Plugin Namen ist bereits vorhanden"

  "ERROR:  Plugin name is not valid (only alphanumeric and underscores are allowed)"
  "ERROR:  Plugin Name ist nicht gültig (nur alphanumerische Zeichen und Unterstriche sind erlaubt)"

  "ERROR:  Unable to create plugin directory"
  "ERROR:  Unable to Plugin-Verzeichnis erstellen"

  "ERROR:  Unable to write plugin files"
  "ERROR:  Unable to Plugin-Dateien zu schreiben"

  "Enter plugin name"
  "Geben Sie Name des Plugins"

  "Grant"
  "Zustimmung"

  "Grant permission?"
  "Zustimmung erteilen?"

  "Plugin Errors"
  "Plugin Fehler"

  "Plugin Trust Requested"
  "Plugin Vertrauen gefragt"

  "Plugin installed"
  "Plugin installiert"

  "Plugin requires permission to view or modify your system."
  "Plugin benötigt die Berechtigung zum Anzeigen oder Ihr System zu ändern."

  "Plugin uninstalled"
  "Plugin deinstalliert"

  "Plugins successfully reloaded"
  "Plugins erfolgreich geladen"

  "Reject"
  "Ablehnen"

  "Syntax errors found in selected plugins"
  "Syntax Fehler in ausgewählten Plugins gefunden"

}

# pref_ui.tcl
msgcat::mcmset de {

  "Abbreviation Aliases"
  "Abkürzung-Aliase"

  "Add"
  "Hinzufügen"

  "Add Language Reference"
  "Sprachreferenz hinzufügen"

  "Additional space between lines"
  "Zusätzlicher Zeilenabstand"

  "Addons"
  "Erweiterungen"

  "Alias"
  "Alias"

  "Allow scrolling in tab bar"
  "Scrollen in der Tableiste zu ermöglichen"

  "Angled bracket"
  "Eckige Klammer"

  "Append characters to search string if entered within"
  "Fügen Sie Zeichen, um die Zeichenfolge zu suchen, wenn innerhalb von"

  "Auto-match Characters"
  "Auto-Spiel-Charaktere"

  "Automatically check for updates on start"
  "Suchen Sie automatisch nach Updates auf der Startseite"

  "Automatically highlight matching bracket"
  "Passenden Halter automatisch markieren"

  "Automatically highlight mismatching brackets"
  "Unpassende Klammern automatisch markieren"

  "Automatically insert vendor prefixes"
  "Einfügen Sie automatisch Anbieterpräfixe"

  "Automatically load last session on start"
  "Beim Start letzte Session automatisch laden"

  "Automatically set the current working directory to the current tabs directory"
  "Legen Sie automatisch das aktuelle Arbeitsverzeichnis in das aktuelle Verzeichnis der Reitern"

  "Backtick"
  "Backtick"

  "Base Directory"
  "Basis-Verzeichnis"

  "Behaviors"
  "Verhalten"

  "Bird's Eye View Font Size"
  "Schriftgröße der Vogelperspektive"

  "Bird's Eye View Width"
  "Breite der Vogelperspeltive"

  "Buffer"
  "Puffer"

  "Choose Color"
  "Farbe wählen"

  "Choose Logfile Directory"
  "Logfile Verzeichnis wählen"

  "Clear"
  "Löschen"

  "Clipboard"
  "Zwischenablage"

  "Clipboard History"
  "Verlauf der Zwischenablage"

  "Clipboard history depth"
  "Zwischenablage-Geschichte-Tiefe"

  "Closing"
  "Abschluss"

  "Color value case"
  "Farbe Wert Fall"

  "Command launcher entry"
  "Befehlseingabe launcher"

  "Command launcher preview"
  "Befehl-Launcher-Vorschau"

  "Convert to lowercase"
  "In Kleinbuchstaben wandeln"

  "Convert to uppercase"
  "In Großbuchstaben wandeln"

  "Creator"
  "Autor"

  "Curly bracket"
  "Geschweifte Klammer"

  "Current"
  "Aktuell"

  "Current Directory"
  "aktuelles Verzeichnis"

  "Current File Pathname"
  "Aktueller Datei-Pfad"

  "Current Filename"
  "Aktueller Dateiname"

  "Current Line Column"
  "Aktuellen Zeilenspalte"

  "Current Line Number"
  "Aktuellen Zeilennummer"

  "Current editing buffer directory"
  "Aktuelle Bearbeitung Puffer-Verzeichnis"

  "Current working directory"
  "Aktuelles Arbeitsverzeichnis"

  "Date"
  "Datum"

  "Default Markdown Export Extension"
  "Markdown Export Standarderweiterung"

  "Default Theme Export Directory"
  "Standard Theme Exportverzeichnis"

  "Default theme"
  "Standard Theme"

  "Default unit for floating point values"
  "Standardeinheit für Gleitkomma-Werte"

  "Default unit for integer values"
  "Standardeinheit für Integer-Werte"

  "Delete snippet"
  "Snippet löschen"

  "Delete user bindings and use default?"
  "Löschen Sie Benutzer Bindungen und verwenden Standard?"

  "Development"
  "Entwicklung"

  "Displayed Information"
  "Angezeigte Informationen"

  "Double-quote"
  "Doppelte Anführungszeichen"

  "Editor"
  "Editor"

  "Enable Vim Mode"
  "Vim-Modus aktivieren"

  "Enable auto-indentation"
  "Auto-Einzug aktivieren"

  "Enable development mode"
  "Entwicklungsmodus aktivieren"

  "Enable fuzzy search"
  "Aktivieren der Fuzzy-Suche"

  "Enable relative line numbering"
  "Relative Zeilennummerierung aktivieren"

  "Enabled"
  "Aktiviert"

  "End-of-line character when saving"
  "Zeilenende Zeichen beim Speichern"

  "Exit the application after the last tab is closed"
  "Beenden der Anwendung beim Schliessen des letzten Reiters"

  "Export Settings"
  "Einstellungen exportieren"

  "Extensions"
  "Erweiterungen"

  "Format snippet indentation after insert"
  "Format-Snippet Einzug nach einfügen"

  "General"
  "Allgemeines"

  "Get More Themes"
  "Weitere Themes erhalten"

  "Hide Patterns"
  "Muster verstecken"

  "Hide binary files"
  "Binäre Dateien ausblenden"

  "Hiding"
  "Ausblenden"

  "Host"
  "Server"

  "Imported"
  "Importiert"

  "Indentation spaces"
  "Einrückung Abstände"

  "Info Panel"
  "Info Panel"

  "Insert unsorted files at the top of a manually sorted directory"
  "Unsortierte Dateien am oberen Rand ein manuell sortierten Verzeichnis einfügen"

  "Insertion cursor width"
  "Einfügen-Cursor Breite"

  "Keep file information panel visible when sidebar doesn't have focus"
  "Bleiben Sie Datei-Info-Tafel sichtbar, wenn Seitenleiste nicht im Fokus"

  "Keyword"
  "Schlüsselwort"

  "Languages"
  "Sprachen"

  "Last"
  "Zuletzt"

  "Last accessed"
  "Letzter Zugriff"

  "Line Wrapping Default"
  "Zeilenumbruch Standard"

  "Line count to find Vim modeline information"
  "Anzahl der Zeilen, Vim Modeline Informationen finden"

  "Logfile Directory"
  "Logfile-Verzeichnis"

  "Manage Themes"
  "Themes verwalten"

  "Manage theme visibility"
  "Sichtbarkeit der Themes verwalten"

  "Maximum undo history (set to 0 for unlimited)"
  "Maximale rückgängig (eingestellt auf 0 für unbegrenzt)"

  "Menu Item"
  "Menü Element"

  "Menu bindings"
  "Menü Bindings"

  "Mounts"
  "Mounts"

  "Node Aliases"
  "Aliase"

  "Options"
  "Optionen"

  "Profiler Options"
  "Profiler-Optionen"

  "Prompt user to save preference changes in global or named session"
  "Anwender fragen, ob Einstellungen in der globalen oder der benannten Session gespeichert werden sollen"

  "Properties"
  "Werte"

  "Reading time words per minute"
  "Lesen von Zeitwörtern pro Minute"

  "Recently opened history depth"
  "Vor kurzem eröffnete Geschichte Tiefe"

  "Remember last position of command launcher"
  "Erinnere mich an letzte Position des Befehls launcher"

  "Remote Base Directory"
  "Remote-Basis-Verzeichnis"

  "Remove root directory after last sub-file is closed"
  "Root-Verzeichnis zu entfernen, nachdem letzte Sub-Datei geschlossen wird"

  "Remove trailing whitespace on save"
  "Nachgestellte Leerzeichen entfernen auf Speichern"

  "Report Options"
  "Report Optionen für Benutzer"

  "Retain case"
  "Fall zu behalten"

  "Return"
  "Zurück"

  "Ruler column"
  "Lineal-Spalte"

  "Save changes to current session?"
  "Änderungen in der aktuellen Session speichern?"

  "Save changes to global preferences?"
  "Speichern Änderungen an globalen Einstellungen?"

  "Search Shortcuts"
  "Nach Tastenkürzeln suchen"

  "Search Snippets"
  "Suche Auszüge (snippets)"

  "Select Settings Sharing Directory"
  "Wählen Sie Einstellungen teilen Verzeichnis"

  "Select a plugin"
  "Wähle eine Plugin"

  "Select default browsing directory"
  "Wählen Sie Standard-Verzeichnis durchsuchen"

  "Selected Text"
  "Ausgewählter Text"

  "Set"
  "Set"

  "Set Find in Files line context"
  "Suchen in Dateien Zeile Kontext gesetzt"

  "Set default open/save browsing directory to"
  "Stellen Sie Standard öffnen/speichern-Verzeichnis-browsing ein"

  "Set find history depth"
  "Geschichte Tiefe finden"

  "Set jump distance"
  "Eingestellten Sprungdistanz"

  "Sharing"
  "Teilen"

  "Sharing Items"
  "Freigabe von Elementen"

  "Shortcut"
  "Tastenkürzel"

  "Shortcuts"
  "Tastenkürzel"

  "Show 'Find in Files' result in other pane"
  "Zeigen Sie"

  "Show Move To Trash for local files/directories instead of Delete"
  "Zeige in Papierkorb verschieben für lokale Dateien/Verzeichnisse statt löschen"

  "Show Tcl console at startup"
  "Tcl Konsole beim Start anzeigen"

  "Show bird's eye view"
  "Vogelperspektive anzeigen"

  "Show diagnostic logfile at startup"
  "Diagnostischen Logfile beim Start anzeigen"

  "Show difference file in other pane than original"
  "Show-Unterschied-Datei im anderen Bereich als das original"

  "Show difference file version information"
  "Dateiversionsinformationen Unterschied zeigen"

  "Show folders at top"
  "Ordner zu Beginn anzeigen"

  "Show hidden files"
  "Versteckte Dateien anzeigen"

  "Show language submenu"
  "Sprach-Untermenü anzeigen"

  "Show menubar"
  "Menüleiste anzeigen"

  "Single-quote"
  "Einfaches Anführungszeichen"

  "Snippet Completion Characters"
  "Snippet Abschluss Zeichen"

  "Snippet Text"
  "Snippet Text"

  "Sort tabs alphabetically on open"
  "Reitern beim Öffnen alphabetisch sortieren"

  "Sorting Column"
  "Spalte sortieren"

  "Space"
  "Abstand"

  "Spaces per tab"
  "Abstand pro Reiter"

  "Square bracket"
  "Eckige Klammer"

  "Stable"
  "Stable"

  "Symbol between CSS property and value"
  "Symbol zwischen CSS-Eigenschaft und Wert"

  "Symbol placed at end of CSS property"
  "Symbol am Ende der CSS-Eigenschaft"

  "Syntax Coloring"
  "Syntax Einfärbung"

  "Tab"
  "Tab"

  "Tab Stop"
  "Tabstop"

  "This operation cannot be reversed."
  "Diese Änderung kann nicht ückgängig gemacht werden."

  "Time"
  "Zeit"

  "Update using release type"
  "Update mit Release Typ"

  "Updates"
  "Updates"

  "Use Default"
  "Standard verwenden"

  "Use appropriate EOL character on system"
  "Verwenden Sie geeignete EOL Charakter auf system"

  "Use carriate return linefeed sequence"
  "Verwenden Sie Carriate return Zeilenvorschub-Sequenz"

  "Use directory"
  "Verzeichnis verwenden"

  "Use linefeed character"
  "Zeilenvorschub-Zeichen verwenden"

  "Use original EOL character from file"
  "Verwenden Sie original EOL-Zeichen aus Datei"

  "Use shortened colors"
  "Verkürzte Farben verwenden"

  "Use single carriage return character"
  "Verwenden Sie einzelne Wagenrücklaufzeichen"

  "Variable"
  "Variable"

  "Variables"
  "Variablen"

  "Visible"
  "Sichtbar"

  "You have changed global preferences which will not be visible because you are currently within a named session."
  "Sie haben globale Einstellungen geändert, die nicht angezeigt werden, weil Sie derzeit innerhalb einer benannten Sitzung sind."

  "You have changed the current session's preferences which will not be applied globally"
  "Sie haben die aktuelle Sitzung Einstellungen geändert, die weltweit nicht angewendet werden"

  "milliseconds"
  "Millisekunden"

  "theme"
  "Theme"

}

# remote.tcl
msgcat::mcmset de {

  "Close Connection"
  "Verbindung trennen"

  "Connection failed"
  "Verbindung fehlgeschlagen"

  "Connection passed"
  "Verbindung übergeben"

  "Create New Folder"
  "Neues Verzeichnis erstellen"

  "Delete Connection"
  "Verbindungen löschen"

  "Delete Group"
  "Gruppe Löschen"

  "Delete connection?"
  "Verbindungen löschen?"

  "Delete group?"
  "Gruppe löschen?"

  "Edit Connection"
  "Verbindung bearbeiten"

  "Enter Password"
  "Passwort eingeben"

  "Folder Name"
  "Verzeichnisname"

  "Group"
  "Gruppe"

  "Group Name"
  "Gruppenname"

  "Group Name: "
  "Gruppenname: "

  "Image used in remote file selector for the history back button."
  "Bild im remote-Datei-Selektor für die Geschichte zurück-Schaltfläche verwendet."

  "Image used in remote file selector for the history forward button."
  "Bild im remote-Datei-Selektor für die Geschichte vorwärts-Taste verwendet."

  "Image used in remote file selector to indicate a file."
  "Bild in abgelegenen Dateiauswahl verwendet, um eine Datei anzugeben."

  "Image used in remote file selector to indicate a folder."
  "Bild in abgelegenen Dateiauswahl verwendet, um einen Ordner angeben."

  "Image used in remote file selector to indicate that a connection is being opened."
  "Bild in abgelegenen Dateiauswahl verwendet, um anzugeben, dass eine Verbindung geöffnet wird."

  "Image used in remote file selector to indicate that a connection is opened."
  "Bild in Remotedatei Selektor verwendet, um anzugeben, dass eine Verbindung hergestellt wird."

  "New Connection"
  "Neue Verbindung"

  "New Folder"
  "Neues Verzeichnis"

  "New Group"
  "Neue Gruppe"

  "Open Connection"
  "Offene Verbindung"

  "Open Remote File"
  "Remote Datei öffnen"

  "Optional"
  "Optional"

  "Password"
  "Passwort"

  "Password: "
  "Passwort: "

  "Port"
  "Port"

  "Remote Directory"
  "Remote-Site Verzeichnis"

  "Rename Group"
  "Gruppe umbenennen"

  "Save File Remotely"
  "Speichern Sie die Datei aus der Ferne"

  "Server"
  "Server"

  "Test Connection"
  "Verbindung testen"

  "Type"
  "Typ"

  "Unable to connect to"
  "Verbindungsaufbau zu dieser Seite nicht möglich"

  "Username"
  "Benutzername"

  "server"
  "Server"

}

# search.tcl
msgcat::mcmset de {

  "No files found in specified directories"
  "Keine Dateien in den angegebenen Verzeichnissen gefunden"

  "No search results found"
  "Keine Suchergebnisse gefunden"

  "Search wrapped to beginning of file"
  "Suche gewickelt an Anfang der Datei"

  "Search wrapped to end of file"
  "Suche gewickelt zum Ende der Datei"

  "substitutions done"
  "Ersetzungen ausgeführt"

}

# select.tcl
msgcat::mcmset de {

  "Add Selection Matches"
  "Treffer der Auswahl hinzufügen"

  "All To"
  "Alle zu"

  "Anchor"
  "Anker"

  "Angled Brackets"
  "Eckige Klammern"

  "Backticks"
  "Backticks"

  "Block"
  "Block"

  "Character"
  "Zeichen"

  "Child"
  "Kind"

  "Clear Selection"
  "Auswahl zurücksetzen"

  "Comment"
  "Kommentar"

  "Curly Brackets"
  "Geschweifte Klammern"

  "Delete Selected Text"
  "Textauswahl löschen"

  "Double Quotes"
  "Doppelte Anführungszeichen"

  "Down"
  "Nach unten"

  "Exit Selection Mode"
  "Auswahlmodus beenden"

  "Invert Selected Text"
  "Textauswahl umkehren"

  "Keep Selection"
  "Auswahl beibehalten"

  "Left"
  "Links"

  "Line To"
  "Zeile zu"

  "Miscellaneous"
  "Sonstiges"

  "Modes"
  "Modi"

  "Motions"
  "ANTRAGE:"

  "Next Sibling"
  "Nächsten Sibling"

  "Paragraph"
  "Absatz"

  "Parent"
  "Eltern"

  "Previous"
  "Vorher"

  "Previous Sibling"
  "Vorheriges gleichgeordnetes Element"

  "Right"
  "Rechts"

  "Selected"
  "Ausgewählt"

  "Selection Mode Command Help"
  "Auswahl-Modus Befehl Hilfe"

  "Sentence"
  "Meinung"

  "Shift Down"
  "Nach unten verschieben"

  "Shift Left"
  "Nach links schieben"

  "Shift Right"
  "Shift rechts"

  "Shift Up"
  "Shift Up"

  "Single Quotes"
  "Einfache Anführungszeichen"

  "Square Brackets"
  "eckige Klammern"

  "Swap Anchor"
  "Anker tauschen"

  "Toggle Help"
  "Hilfe umschalten"

  "Toggle Quote Inclusion"
  "Toggle Zitateinschluss"

  "Type '?' for help.  Hit the ESCAPE key to exit selection mode"
  "Tippe '?' für Hilfe.  Drücke die ESC-Taste um den Auswahlmodus zu verlassen"

  "Undo Last Change"
  "Letzte Änderung rückgängig machen"

  "Up"
  "Nach oben"

  "Word"
  "Wort"

  "matching instances"
  "passende Instanzen"

}

# sessions.tcl
msgcat::mcmset de {

  "Save session?"
  "Session speichern?"

  "Session state will be lost if not saved"
  "Der Stand der Session geht verloren, wird er nicht gespeichert"

}

# share.tcl
msgcat::mcmset de {

  "Emmet"
  "Emmet"

  "Export Settings Data"
  "Einstellungen exportieren"

  "Favorites"
  "Favoriten"

  "Remote Connections"
  "Remote-Verbindungen"

  "Settings to export"
  "Einstellungen exportieren"

  "Themes"
  "Themes"

}

# sidebar.tcl
msgcat::mcmset de {

  "Add Parent Directory"
  "Übergeordnetes Verzeichnis hinzufügen"

  "By Name"
  "Nach Name"

  "Close Directory Files"
  "Verzeichnisdateien löschen"

  "Copy Pathname"
  "Pfadname kopieren"

  "Decreasing"
  "Abnehmend"

  "Delete directories?"
  "Verzeichnisse löschen?"

  "Delete directory?"
  "Verzeichnis löschen?"

  "Delete file?"
  "Datei löschen?"

  "Delete files?"
  "Dateien löschen?"

  "Directory Name:"
  "Verzeichnisnamen:"

  "Disconnect From Server"
  "Serververbindung trennen"

  "Folder Name:"
  "Verzeichnisname"

  "Hide"
  "Verbergen"

  "Hide Directory Files"
  "Verzeichnisdateien ausblenden"

  "Image displayed in sidebar to indicate a directory that is collapsed"
  "Bild in der Seitenleiste auf ein Verzeichnis zeigen, die ausgeblendet ist"

  "Image displayed in sidebar to indicate a directory that is showing its contents"
  "Bild im Sidebar, um ein Verzeichnis angeben, das seinen Inhalt angezeigt wird angezeigt"

  "Image displayed in sidebar to indicate a file"
  "In der Seitenleiste, um eine Datei angezeigten Bild"

  "Image displayed in sidebar to indicate a selected directory that is collapsed"
  "Bild in der Seitenleiste auf ein ausgewählten Verzeichnis anzugeben, das ausgeblendet ist"

  "Image displayed in sidebar to indicate a selected directory that is expanded"
  "Bild im Sidebar an einem ausgewählten Verzeichnis, das erweitert wird angezeigt"

  "Image displayed in sidebar to indicate that a file is currently opened but hidden"
  "Bild in der Sidebar, um anzugeben, dass eine Datei gerade geöffnet aber versteckt ist"

  "Image displayed in sidebar to indicate that a file is currently opened in an editing buffer."
  "Bild in der Seitenleiste angezeigt, um anzugeben, dass eine Datei zur Zeit in einem Editierpuffer eröffnet."

  "Increasing"
  "Aufsteigend"

  "Make Current Working Directory"
  "Make Current Working Directory"

  "Manually"
  "Manuell"

  "New Directory"
  "Neues Verzeichnis"

  "New File From Template"
  "Neue Datei aus Vorlage"

  "Open Directory Files"
  "Verzeichnisdateien öffnen"

  "Refresh Directory Files"
  "Verzeichnisdateien aktualisieren"

  "Remove Parent from Sidebar"
  "Elternteil aus Sidebar entfernen"

  "Remove from Sidebar"
  "Aus Sidebar entfernen"

  "Show"
  "Zeigen"

  "Show Difference"
  "Unterschied zeigen"

  "Show Directory Files"
  "Verzeichnisdateien anzeigen"

  "Show Info"
  "Informationen anzeigen"

  "Sort"
  "Sortierung"

  "Unable to duplicate file"
  "Datei konnte nicht dupliziert werden"

}

# snippets.tcl
msgcat::mcmset de {

  "Snippet: *"
  "Snippet: *"

}

# startup.tcl
msgcat::mcmset de {

  "Change Directory"
  "Verzeichnis wechseln"

  "Copies settings data from an existing directory to your home directory."
  "Kopiert Einstellungsdaten aus einem vorhandenen Verzeichnis in Ihr Home-Verzeichnis."

  "Copy settings from directory"
  "Kopieret Einstellungen aus Verzeichnis"

  "Create settings locally"
  "Einstellungen vor Ort erstellen"

  "Creates new settings information and places it in your home directory"
  "Schafft neue Informationen über Einstellungen und legt sie in Ihrem home-Verzeichnis"

  "Finish"
  "Abschliessen"

  "If you need would like to change your sharing settings, you can do so within Preferences under the General/Sharing tab."
  "Benötigen Sie möchten Ihre Freigabeeinstellungen ändern Sie dazu in den Einstellungen unter der Reiter"

  "Items that are selected will be copied to your local home directory. Items that are not selected will be created in your home directory."
  "Ausgewählten Elemente werden auf Ihrem lokalen home-Verzeichnis kopiert. Elemente, die nicht ausgewählt sind werden in Ihrem home-Verzeichnis erstellt werden."

  "Items that are selected will be shared with other computers. Items that are not selected will be stored locally and will not be shared."
  "Ausgewählten Elemente werden mit anderen Computern geteilt werden. Elemente, die nicht ausgewählt sind werden lokal gespeichert und nicht weitergegeben."

  "Select Settings Directory"
  "Einstellungs-Verzeichnis wählen"

  "Settings"
  "Einstellungen"

  "Settings Options"
  "Einstellungsoptionen"

  "Setup Complete"
  "Setup abgeschlossen"

  "Share"
  "Teilen"

  "Shares settings data from a new or existing directory (ex., iCloud Drive, Google Drive, Dropbox, etc.).  Any changes made to settings data will be available to other sharers."
  "Teilt Einstellungsdaten aus einem neuen oder vorhandenen Verzeichnis (z. B. iCloud Laufwerk, Google, Dropbox, etc..).  Alle vorgenommenen Einstellungsdaten werden zu anderen Quellen."

  "Thanks for using TKE, the advanced programmer's editor.  Since this is a new installation of TKE, let's help you get things set up. \\n \\n Click 'Next' below to get things going."
  "Danke fuer die Benutzung TKE, den fortgeschrittenen Programmierer-Editor.  Da dies eine neue Installation von TKE ist, lassen Sie uns Ihnen helfen, Dinge eingerichtet. \\n \\n 'Weiter' klicken Sie unten um Dinge geht."

  "Use shared settings"
  "Gemeinsam genutzte Einstellungen verwenden"

  "Welcome"
  "Willkommen"

  "Welcome To"
  "Willkommen bei"

}

# syntax.tcl
msgcat::mcmset de {

  "Syntax"
  "syntax"

  "Syntax error in syntax file"
  "Syntax-Fehler in Syntaxdatei"

}

# templates.tcl
msgcat::mcmset de {

  "Delete template?"
  "Vorlage löschen?"

  "Template"
  "Vorlage"

  "Template Name"
  "Vorlagenname"

  "deleted"
  "gelöscht"

  "saved"
  "gespeichert"

  "will be permanently deleted"
  "wird dauerhaft gelöscht"

}

# theme.tcl
msgcat::mcmset de {

  "Amount of border to display around command launcher in pixels"
  "Höhe der Grenze um Befehl Launcher in Pixel anzeigen"

  "Background (trough) color used in a standard scrollbar."
  "Er war in einer Standardschriftart gedruckt."

  "Background (trough) color used in the sidebar scrollbar."
  "Hintergrund (Trog) Farbe in der Seitenleiste Bildlaufleiste verwendet wird."

  "Background (trough) color used in the text scrollbars."
  "Hintergrund (Trog) Farbe in den Textbildlaufleisten verwendet."

  "Background color displayed in embedded language code."
  "Hintergrundfarbe in eingebetteten Sprachcode angezeigt."

  "Background color for all sidebar items that are not selected."
  "Hintergrundfarbe für alle Sidebar Elemente, die nicht ausgewählt sind."

  "Background color for all sidebar items that are selected."
  "Hintergrundfarbe für alle Sidebar Elemente, die ausgewählt sind."

  "Background color for markers in the line gutter and scrollbar"
  "Hintergrundfarbe für Markierungen in der Linie Gosse und scrollbar"

  "Background color for matching search text"
  "Hintergrundfarbe für den Abgleich Suchtext"

  "Background color in difference viewer that shows added lines."
  "Hintergrundfarbe im Unterschied Viewer, der hinzugefügten Zeilen zeigt."

  "Background color in difference viewer that shows deleted lines."
  "Hintergrundfarbe im Unterschied Viewer, der gelöschten Zeilen zeigt."

  "Background color of insertion cursor and background marker colors."
  "Hintergrundfarbe des Einfügemarke und Hintermarkerfarben."

  "Background color of list items when not selected"
  "Hintergrundfarbe von Listenelementen wenn nicht ausgewählt"

  "Background color of move bar."
  "Hintergrundfarbe der Inaktivitätsstatus."

  "Background color of selection in command launcher"
  "Hintergrundfarbe der Auswahl im Befehl launcher"

  "Background color of textual display in command launcher"
  "Hintergrundfarbe der textuellen Anzeige im Befehl launcher"

  "Background color of the editing buffer."
  "Hintergrundfarbe des Bearbeitungspuffer."

  "Background color to display when a button-like ttk widget is pressed."
  "Hintergrundfarbe angezeigt, wenn eine knopfartige TTK Widget gedrückt wird."

  "Background color to use for active information values to indicate they are clickable."
  "Hintergrundfarbe für aktive Information Werte verwenden, um anzugeben, dass sie anklickbar sind."

  "Background color to use for displaying character information that requires the user's attention."
  "Hintergrundfarbe zu verwenden, zum Anzeigen von Charakterinformationen, die die Aufmerksamkeit des Benutzers erfordert."

  "Background color to use for selected text."
  "Hintergrundfarbe für ausgewählten Text zu verwenden."

  "Background color to use for the file information panel."
  "Hintergrundfarbe für die Datei-Informations-Panel verwenden."

  "Background color used for all other tabs that are not the current/active tab in the tabbar."
  "Hintergrundfarbe für alle anderen Reitern, die nicht die aktuelle / aktive Reiter in der Fensterleiste verwendet."

  "Background color used for the current/active menu item."
  "Hintergrundfarbe für die aktuelle / aktive Menüpunkt verwendet."

  "Background color used for the current/active tab in the tabbar."
  "Hintergrundfarbe für die aktuelle / aktive Reiter in der Fensterleiste verwendet."

  "Background color used in highlighted text."
  "Hintergrundfarbe in markierten Text verwendet werden."

  "Background color used in menus."
  "Hintergrundfarbe in Menüs verwendet."

  "Background color used in the tabbar area."
  "Hintergrundfarbe in der Fensterleiste Bereich verwendet."

  "Color of border around command launcher"
  "Farbe des Rahmens um Befehl launcher"

  "Color of border drawn around active editing buffer."
  "Farbe des Rahmens um aktive Bearbeitungspuffer gezeichnet."

  "Color of space between tabs."
  "Farbe der Raum zwischen den Tabs."

  "Color of the spacer between the command launcher entry field and the result list"
  "Farbe der Abstandhalter zwischen Feld Befehl Launcher und die Ergebnisliste"

  "Color of ttk entry widget text border when the entry has keyboard focus."
  "Farbe des TTK Eintrag Widget Text Grenze, wenn der Eintrag über den Tastaturfokus."

  "Color to use for highlighting closed folds in the line number gutter"
  "Farbe für die Hervorhebung geschlossene Falten in der Linie Nummer Gosse verwenden"

  "Color used to draw the warning width line in the editing buffer (as well as the line separating the gutter from the editing buffer)."
  "Farbe verwendet werden, um die Warnung Breitenlinie im Bearbeitungspuffer (wie auch die Trennlinie zwischen der Dachrinne von der Bearbeitungspuffer) zu zeichnen."

  "Command Launcher Options"
  "Launcher Befehlsoptionen"

  "Default 'darkcolor' for all ttk widgets."
  "Default &#39;darkcolor&#39; für alle TTK Widgets."

  "Default background color to use for all ttk widgets that are in a disabled state."
  "Standardhintergrundfarbe für alle TTK Widgets, die im deaktivierten Zustand verwenden."

  "Default background color to use for all ttk widgets when the mouse cursor hovers over the widget."
  "Standardhintergrundfarbe für alle TTK-Widgets verwenden, wenn der Mauszeiger über das Widget."

  "Default background color to use for all ttk widgets."
  "Standardhintergrundfarbe für alle TTK-Widgets verwenden."

  "Default border color for all ttk widgets."
  "Standard-Rahmenfarbe für alle TTK Widgets."

  "Default color for non-syntax highlighted text."
  "Standardfarbe für nicht-Syntax hervorgehobenen Text."

  "Default foreground text color to use for all ttk widgets that are in a disabled state."
  "Standardvordergrundtextfarbe für alle TTK Widgets, die im deaktivierten Zustand verwenden."

  "Default foreground text color to use for all ttk widgets."
  "Standardvordergrundtextfarbe für alle TTK-Widgets verwenden."

  "Determines the number of grips strips to display in the grip area between resizable panes."
  "Bestimmt die Anzahl der Griffstreifen in der Griffbereich zwischen resizable Scheiben anzuzeigen."

  "Determines the thickness of the grip area between resizable panes."
  "Bestimmt die Dicke der Griffbereich zwischen resizable Scheiben."

  "ERROR:  Unable to read"
  "Fehler: Datei kann Code Datei lesen"

  "Foreground (slider) color used in a standard scrollbar."
  "(Schieberegler) Vordergrundfarbe in eine standard-Bildlaufleiste verwendet."

  "Foreground (slider) color used in the sidebar scrollbar."
  "Vordergrund (Schieberegler) Farbe in der Seitenleiste Bildlaufleiste verwendet wird."

  "Foreground (slider) color used in the text scrollbars when pane synchronization is enabled."
  "(Schieberegler) Vordergrundfarbe in den Text Scrollbalken verwendet, wenn Bereich Synchronisierung aktiviert ist."

  "Foreground (slider) color used in the text scrollbars."
  "Vordergrund (Schieberegler) Farbe in den Textbildlaufleisten verwendet."

  "Foreground color for matching search text"
  "Vordergrundfarbe für passender Suchtext"

  "Foreground color of list items when not selected"
  "Vordergrundfarbe von Listenelementen wenn nicht ausgewählt"

  "Foreground color of move bar."
  "Vordergrundfarbe des Inaktivitätsstatus."

  "Foreground color of selection in command launcher"
  "Vordergrundfarbe Auswahl im Befehl launcher"

  "Foreground color of textual display in command launcher"
  "Vordergrundfarbe des textuellen Anzeige im Befehl launcher"

  "Foreground color to use for title text in the information panel."
  "Vordergrundfarbe für Titeltext im Informationsbereich zu verwenden."

  "Foreground color to use for value text in the information panel."
  "Vordergrundfarbe für Werttext im Informationsbereich."

  "Foreground color used in menu items with checks or buttons."
  "Vordergrundfarbe Menüpunkten mit Schecks oder Schaltflächen."

  "Foreground text color for strings."
  "Vordergrund Textfarbe für Streicher."

  "Foreground text color to use for all miscellaneous1 labeled text."
  "Vordergrund Textfarbe für alle miscellaneous1 markierten Text."

  "Foreground text color to use for all miscellaneous2 labeled text."
  "Vordergrund Textfarbe für alle miscellaneous2 markierten Text."

  "Foreground text color to use for all miscellaneous3 labeled text."
  "Vordergrund Textfarbe für alle miscellaneous3 markierten Text."

  "Foreground text color to use for comments."
  "Vordergrund Textfarbe für Kommentare zu verwenden."

  "Foreground text color to use for displaying line numbers."
  "Vordergrund Textfarbe für die Anzeige von Zeilennummern zu verwenden."

  "Foreground text color to use for displaying numbers."
  "Vordergrund Textfarbe für die Anzeige von Zahlen verwenden."

  "Foreground text color to use for language-specific keywords."
  "Vordergrund Textfarbe für sprachspezifische Keywords verwenden."

  "Foreground text color to use for language-specific punctuation."
  "Vordergrund Textfarbe für sprachspezifische Satzzeichen verwenden."

  "Foreground text color to use for meta syntax."
  "Vordergrund Textfarbe für die Meta-Syntax verwenden."

  "Foreground text color to use for precompiler syntax."
  "Vordergrund Textfarbe für Precompiler Syntax verwenden."

  "Foreground text color to use for readable meta syntax."
  "Vordergrundfarbe Text lesbar Meta-Syntax verwenden."

  "Foreground text color to use for selected text."
  "Vordergrund Textfarbe für ausgewählten Text zu verwenden."

  "Foreground text color used for all other tabs that are not the current/active tab in the tabbar."
  "Text Vordergrundfarbe für alle anderen Reitern, die nicht der Strom/aktiv-Reiter in der Tabbar sind."

  "Foreground text color used for menus item that are disabled."
  "Vordergrund Textfarbe für Menüpunkt, die deaktiviert sind, verwendet."

  "Foreground text color used for the current/active menu item."
  "Vordergrund Textfarbe für die aktuelle / aktive Menüpunkt verwendet."

  "Foreground text color used for the current/active tab in the tabbar."
  "Text Vordergrundfarbe in der Tabbar der Strom/aktiv-Reiter."

  "Foreground text color used in menus."
  "Vordergrund Textfarbe in Menüs verwendet."

  "Foreground text/image color used in tabbar and tabs."
  "Vordergrund Text / Bild Farbe in Fensterleiste und Tabs verwendet."

  "Images"
  "Bilder"

  "Maximum thickness of the command launcher scrollbar when it is active."
  "Maximale Dicke der Befehl Launcher Bildlaufleiste, wenn es aktiv ist."

  "Maximum thickness of the text scrollbar when it is active."
  "Maximale Dicke des Textbildlaufleiste, wenn es aktiv ist."

  "Maximum thickness of the text scrollbars when they are active."
  "Maximale Dicke der Textlaufleisten, wenn sie aktiv sind."

  "Menu Options"
  "Optionsmenü"

  "Menu relief value."
  "Menü Relief Wert."

  "Pixel height of the spacer between the command launcher entry field and the result list"
  "Höhe in Pixel der Abstandhalter zwischen Feld Befehl Launcher und die Ergebnisliste"

  "Pixel height of the tabbar widget."
  "Pixel Höhe der Fensterleiste Widget."

  "Relief used in drawing the tabs."
  "Relief in der Zeichnung die Reitern verwendet."

  "Relief value of the sidebar area."
  "Relief Wert der Sidebar-Bereich."

  "Scrollbar slider color used in the command launcher results list"
  "ScrollBar Slider Farbe in der Befehlsliste Launcher Ergebnisse"

  "Sidebar Info Panel Options"
  "Sidebar-Info-Panel-Optionen"

  "Sidebar Options"
  "Siebar Optionen"

  "Sidebar Scrollbar Options"
  "Sidebar Scrollbar Optionen"

  "Specifies background color of command launcher entry and list"
  "Gibt die Hintergrundfarbe der Befehlseingabe Launcher und Liste"

  "Specifies foreground color of command launcher entry and list"
  "Gibt die Vordergrundfarbe der Befehlseingabe Launcher und Liste"

  "Specifies the color drawn around the border of the sidebar when a dragged file is droppable"
  "Gibt die Farbe am Rand der Seitenleiste, wenn eine gezogene Datei dementsprechende ist gezogen"

  "Specifies the color to display around the sidebar when the sidebar does not have the focus."
  "Gibt die Farbe an, um rund um die Seitenleiste angezeigt werden, wenn die Seitenleiste nicht den Fokus."

  "Specifies the color to display around the sidebar when the sidebar has the focus."
  "Gibt die Farbe zum Anzeigen rund um die Seitenleiste, wenn der Seitenleiste den Fokus hat."

  "Specifies the default background color to use for text that is selected in a standard ttk widget (this does not include the editing buffer)."
  "Gibt die Standardhintergrundfarbe für den Text, der in einem Standard-TTK Widget ausgewählt ist, verwenden (dies beinhaltet nicht die Bearbeitungspuffer)."

  "Specifies the default foreground text color to use for text that is selected in a standard ttk widget (this does not include the editing buffer)."
  "Gibt die Standardvordergrundtextfarbe für Text, der in einem Standard-TTK Widget ausgewählt ist, verwenden (dies beinhaltet nicht die Bearbeitungspuffer)."

  "Specifies the default relief to use when drawing ttk widgets."
  "Gibt die standardmäßige Entlastung beim Zeichnen TTK-Widgets zu bedienen."

  "Specifies the pixel thickness of the highlight line."
  "Gibt das Pixeldicke der Highlight Linie."

  "Standard Scrollbars"
  "Standard Scrollbars"

  "Syntax Colors"
  "Syntax Farben"

  "Tab Options"
  "Reiter Optionen"

  "Text Scrollbar Options"
  "Text Scrollbar Optionen"

  "Text color for all sidebar items that are not selected."
  "Textfarbe für alle Sidebar Elemente, die nicht ausgewählt sind."

  "Text color for all sidebar items that are selected."
  "Textfarbe für alle Sidebar Elemente, die ausgewählt sind."

  "ttk Widget Colors"
  "TTK Widget Farben"

}

# themer.tcl
msgcat::mcmset de {

  "   Show Selected Option"
  "   Ausgewählte Option anzeigen"

  "   Show Selected Value"
  "   Ausgewählten Wert anzeigen"

  "Categories"
  "Kategorien"

  "Change Base Color"
  "Basisfarbe ändern"

  "Choose Theme"
  "Theme wählen"

  "Created By"
  "Erstellt von"

  "Custom Directory"
  "Eigenes Verzeichnis"

  "Custom..."
  "Benutzerdefiniert..."

  "Delete swatch?"
  "Farbfeld löschen?"

  "Description"
  "Beschreibung"

  "Details"
  "Details"

  "Done"
  "Fertig"

  "Enable Copy Mode"
  "Copy-Modus aktivieren"

  "Export BMP Data"
  "BMP-Daten exportieren"

  "Export BMP Mask"
  "BMP-Maske exportieren"

  "Export Bitmap Data"
  "Bitmap-Daten exportieren"

  "Export Theme As"
  "Export Theme unter"

  "GIF Photo"
  "GIF Foto"

  "Import"
  "Import"

  "Import BMP Data"
  "BMP Daten importieren"

  "Import BMP Mask"
  "Import BMP Mask"

  "Import Bitmap Data"
  "Bitmap-Daten importieren"

  "Import Error"
  "Importfehler"

  "Import Theme File"
  "Theme Datei importieren"

  "Installation Directory"
  "Installationsverzeichnis"

  "License File"
  "Lizenzdatei"

  "Modifications"
  "Änderungen"

  "One-Color Bitmap"
  "One-Color Bitmap"

  "Output Directory"
  "Ausgabeverzeichnis"

  "Paste Theme Items"
  "Theme Elemente einfügen"

  "Relief: "
  "Relief: "

  "Save As:"
  "Speichern unter:"

  "Save theme changes?"
  "Theme-Änderungen speichern?"

  "Select Directory"
  "Verzeichnis auswählen"

  "Show All"
  "Alle anzeigen"

  "Show Category"
  "Katagorie anzeigen"

  "Show Color"
  "Farbe anzeigen"

  "Show Selected Option"
  "Ausgewählte Option anzeigen"

  "Show Selected Value"
  "Ausgewählten Wert anzeigen"

  "Swatch"
  "Probe"

  "Swatch Colors"
  "Musterfarben"

  "Table Copy"
  "Tabelle kopieren"

  "Table Filters"
  "Tabellen Filter"

  "Table Search"
  "Tabellen Suche"

  "The current theme has unsaved changes"
  "Das aktuelle Theme hat nicht gespeicherte Änderungen"

  "Theme Name"
  "Theme Name"

  "Tree Style: "
  "Baum-Stil: "

  "Two-Color Bitmap"
  "Zwei-Farben Bitmap"

  "User Directory"
  "Nutzerverzeichnis"

  "Value: "
  "Wert: "

  "Website"
  "Webseite"

}

# themes.tcl
msgcat::mcmset de {

  "Batch custom theme export completed successfully"
  "Batch benutzerdefiniertes Design Export erfolgreich abgeschlossen"

  "Theme"
  "Theme"

  "Theme:*"
  "Theme:*"

}

# tke.tcl
msgcat::mcmset de {

  "Import TKE theme?"
  "TKE Theme importieren?"

  "Import TextMate theme?"
  "TextMate Thema importieren?"

}

# tkedat.tcl
msgcat::mcmset de {

  "Unable to read"
  "Datei kann nicht gelesen werden"

}

# vim.tcl
msgcat::mcmset de {

  "File format unrecognized"
  "Unbekanntes Dateiformat"

  "Filename directory does not exist"
  "Dateiname-Verzeichnis existiert nicht"

  "Folding method unrecognized"
  "Faltbare unbekannte Methode"

  "Illegal modelines value"
  "Illegale Modelines Wert"

  "Number width not a number"
  "Nummer Breite Nichtzahlen"

  "Selection value is unsupported"
  "Auswahlwert wird nicht unterstützt"

  "Shiftwidth value is not an integer"
  "Einrückungstiefe Wert ist keine Ganzzahl"

  "Tabstop value is not an integer"
  "TabStop-Wert ist keine Ganzzahl"

  "Unrecognized vim option"
  "Unbekannte Vim-Option"

}

# General
msgcat::mcmset de {

  "All"
  "Alle"

  "Attributes"
  "Attribute"

  "Back"
  "Zurück"

  "Bird's Eye View"
  "Vogelpersepktive"

  "Browse"
  "Durchsuchen"

  "Cancel"
  "Abbrechen"

  "Check for Update"
  "Nach Updates suchen"

  "Choose"
  "Wählen"

  "Close"
  "Schliessen"

  "Copy"
  "Kopieren"

  "Create"
  "Erstellen"

  "Current Line"
  "Aktuelle Zeile"

  "Current Word"
  "Aktuelles Wort"

  "Cursor"
  "Cursor"

  "Delete"
  "Löschen"

  "Directory"
  "Verzeichnis"

  "Duplicate"
  "Duplizieren"

  "Edit"
  "Bearbeiten"

  "Enable code folding"
  "Code-Faltung aktivieren"

  "Export"
  "Export"

  "Favorite"
  "Favorit"

  "File"
  "Datei"

  "File Name:"
  "Dateiname:"

  "Find"
  "Suchen"

  "Find next occurrence"
  "Nächstes Vorkommen finden"

  "Find previous occurrence"
  "Vorherige Vorkommen finden"

  "Image displayed in sidebar information panel for closing the panel"
  "Bild im Sidebar-Info-Tafel für das Schliessen des Panels angezeigt"

  "Image displayed in sidebar information panel for refreshing content"
  "Bild im Sidebar-Info-Tafel für erfrischende Inhalt angezeigt"

  "Image displayed in sidebar information panel for showing file in sidebar"
  "Im Sidebar-Informations-Panel zeigt Datei in Seitenleiste angezeigte Bild"

  "Insert"
  "Einfügen"

  "Language"
  "Sprache"

  "Language Documentation"
  "Sprachdokumentation"

  "Launcher"
  "Starter"

  "Line"
  "Zeile"

  "Move To Trash"
  "in den Papierkorb verschieben"

  "Move to Other Pane"
  "Verschieben in andere Pane"

  "Name"
  "Name"

  "New File"
  "Neue Datei"

  "Next"
  "Weiter"

  "Node"
  "Knoten"

  "None"
  "Ohne"

  "OK"
  "OK"

  "Open"
  "Öffnen"

  "Parenthesis"
  "Klammer"

  "Plugin"
  "Erweiterung"

  "Plugins"
  "Erweiterungen"

  "Preferences"
  "Einstellungen"

  "Preview"
  "Vorschau"

  "Rename"
  "Umbenennen"

  "Save"
  "Speichern"

  "Save As"
  "Speichern unter"

  "Search"
  "Suchen"

  "Sessions"
  "Sessions"

  "Show in Sidebar"
  "In Sidebar anzeigen"

  "Show line numbers"
  "Zeilennummern anzeigen"

  "Show marker map"
  "Marker anzeigen"

  "Show sidebar"
  "Sidebar anzeigen"

  "Show status bar"
  "Statusleiste anzeigen"

  "Show tab bar"
  "Reiterleiste anzeigen"

  "Snippet"
  "Snippet"

  "Snippets"
  "Snippets"

  "Split View"
  "Ansicht teilen"

  "TKE Updater"
  "TKE Updater"

  "Templates"
  "Vorlagen"

  "Test"
  "Prüfen"

  "Theme Editor"
  "Theme Editor"

  "Unable to rename file"
  "Datei kann nicht umbenannt werden"

  "Unable to write"
  "Datei kann nicht geschrieben werden"

  "Unfavorite"
  "Unfavorite"

  "Value"
  "Wert"

  "Version"
  "Version"

}

