# api.tcl
msgcat::mcmset de {

  "Argument list to api::add_file was not an even key/value pair"
  "Argument Liste api::add_file war nicht ein noch Schlüssel / Wert-Paar"

  "Plugin"
  "Plugin"

}

# bgproc.tcl
msgcat::mcmset de {

  "Unable to run system command"
  "Keine Systembefehl ausführen"

}

# diff.tcl
msgcat::mcmset de {

  "    End: "
  "Ende:"

  "    Start: "
  "Beginn:"

  "Enter difference command"
  "Geben Sie Befehl difference"

  "Enter starting file"
  "Geben Sie die Startdatei"

  "Update"
  "Aktualisieren"

}

# embed_tke.tcl
msgcat::mcmset de {

  "Find:"
  "Suchen nach:"

  "Replace:"
  "Ersetzen:"

}

# gui.tcl
msgcat::mcmset de {

  "Case sensitivity"
  "Groß-und Kleinschreibung"

  "Close All Tabs"
  "Close All Tabs"

  "Close Other Tabs"
  "Andere Tabs schließen"

  "Close Other*"
  "Andere Unterfenster schließen"

  "Close Tab"
  "Tab schließen"

  "Column"
  "Spalte"

  "Copyright"
  "Copyright"

  "Delete tab?"
  "Löschen Registerkarte?"

  "Developer"
  "Entwickler"

  "Email"
  "E-Mail"

  "Error"
  "Fehler"

  "Favorited"
  "Favorit"

  "File already exists.  Use '!' to force an overwrite"
  "Datei existiert bereits.  Verwendung '!' eine Überschreibung zu erzwingen"

  "File attribute does not exist"
  "Dateiattribut ist nicht vorhanden."

  "File index is out of range"
  "Datei-Index außerhalb des zulässigen Bereichs"

  "Image displayed in fill-in forms which closes the form UI.  Used in forms such as search, search/replace, and find in files."
  "Bild gefunden in Fill-in-Formulare, die die Form UI schließt. In Formen wie Suche verwendet, Suchen / Ersetzen, und finden in Dateien."

  "Image used in tab menus to indicate that the file is associated with a difference view."
  "Bild in Registerkarte Menüs verwendet, um anzuzeigen, dass die Datei mit einem Unterschied Ansicht zugeordnet."

  "Image used in tab menus to indicate that the file is locked."
  "Bild in Registerkarte Menüs verwendet werden, um anzugeben, dass die Datei gesperrt ist."

  "Image used in tab menus to indicate that the file is readonly."
  "Bild in Registerkarte Menüs verwendet, um anzuzeigen, dass die Datei schreibgeschützt."

  "Image used in tab to indicate that the tab contains a difference view."
  "Bild im Register verwendet werden, um anzuzeigen, dass das Register enthält einen Unterschied sehen."

  "Image used in tab to indicate that the tab's file is readonly."
  "Bild im Register verwendet, um anzuzeigen, dass die Akten der Registerkarte ist schreibgeschützt."

  "Image used in tab to indicate that the tab’s file is locked."
  "Bild im Register verwendet, um anzuzeigen, dass die Akten der Registerkarte gesperrt ist."

  "Image used in tab which, when clicked, closes the tab."
  "Bild in Register, die, wenn geklickt wird, schließt das Register verwendet."

  "License"
  "Lizenze"

  "Line"
  "Linie"

  "Locked"
  "Lock"

  "Move"
  "Verschieben"

  "Must be in multicursor mode to insert numbers"
  "Muss im multicursor-Modus um Zahlen einzusetzen sein."

  "No write permissions.  Use '!' to force write."
  "Keine Schreibrechte.  Verwendung '!' schreiben zu erzwingen."

  "Release Type"
  "Releasetyp"

  "Reload file?"
  "Datei erneut laden"

  "Replace"
  "Ersetzen"

  "Save request"
  "Speichern Anfrage"

  "Show in Sidebar"
  "Show in Sidebar"

  "Starting number:"
  "Startnummer:"

  "Tcl/Tk Version"
  "Tcl/Tk-Version"

  "Total Characters"
  "Gesamt-Zeichen"

  "Total Lines"
  "Summenzeilen"

  "Unable to find current file"
  "Aktuelle Datei gefunden"

  "Unable to successfully parse number string"
  "Nicht in der Lage, Anzahl Zeichenfolge erfolgreich analysiert"

  "Unable to write file"
  "Datei konnte nicht geschrieben werden"

  "Version"
  "Neue Font-Awesome-Version aktivieren"

  "tab"
  "Tabulator"

}

# markers.tcl
msgcat::mcmset de {

  "Marker name:"
  "Marker Namen:"

}

# menus.tcl
msgcat::mcmset de {

  "About TKE"
  "Über TKE"

  "Align Cursors"
  "Ausrichten von Cursorn"

  "Append Next Occurrence"
  "Suchbegriffes anfügen"

  "Auto-Indent"
  "Auto-Einzug"

  "Check for Update"
  "Nach Update suchen"

  "Clear All"
  "Alles löschen"

  "Close All"
  "Alle schließen"

  "Close Current"
  "Strom zu schließen"

  "Copy"
  "Kopieren"

  "Create at Current Line"
  "Zur aktuellen Zeile erstellen"

  "Create..."
  "Erstellen..."

  "Cut"
  "Schneiden"

  "Edit"
  "Bearbeiten"

  "Edit Language"
  "Sprachen bearbeiten"

  "Edit Menu Edit user snippets"
  "Bearbeiten Sie im Menü Bearbeiten von Benutzer-Ausschnitte"

  "Edit Menu: Copy text"
  "Im Bearbeitungsmenü: Text kopieren"

  "Edit Menu: Cut text"
  "Im Bearbeitungsmenü: Text Ausschneiden"

  "Edit Menu: Edit language snippets"
  "Bearbeitungsmenü: Bearbeiten-Sprache-Ausschnitte"

  "Edit Menu: Edit session current language preferences"
  "Bearbeitungsmenü: Aktuellen Spracheinstellungen bearbeiten-Sitzung"

  "Edit Menu: Edit session global preferences"
  "Im Bearbeitungsmenü: Sitzung globale Einstellungen bearbeiten"

  "Edit Menu: Edit user current language preferences"
  "Bearbeitungsmenü: Aktuellen Spracheinstellungen bearbeiten-Benutzer"

  "Edit Menu: Edit user global preferences"
  "Im Bearbeitungsmenü: Benutzer globale Einstellungen bearbeiten"

  "Edit Menu: Edit user menu bindings"
  "Im Bearbeitungsmenü: Bearbeiten Sie Benutzer-Menü-Bindungen"

  "Edit Menu: Format all text"
  "Im Bearbeitungsmenü: Alle Text formatieren"

  "Edit Menu: Format selected text"
  "Im Bearbeitungsmenü: Ausgewählten Text formatieren"

  "Edit Menu: Insert from clipboard"
  "Im Bearbeitungsmenü: Fügen Sie aus Zwischenablage ein"

  "Edit Menu: Insert snippet"
  "Im Bearbeitungsmenü: Einfügen-Ausschnitt"

  "Edit Menu: Paste and format text from clipboard"
  "Im Bearbeitungsmenü: Einfügen und das Format Text aus Zwischenablage"

  "Edit Menu: Paste text from clipboard"
  "Im Bearbeitungsmenü: Text aus Zwischenablage einfügen"

  "Edit Menu: Redo"
  "Menü Bearbeiten: wiederholen"

  "Edit Menu: Reload snippets"
  "Im Bearbeitungsmenü: Reload-Ausschnitte"

  "Edit Menu: Select all text"
  "Im Bearbeitungsmenü: Markieren des gesamten Texts"

  "Edit Menu: Set indent mode to IND"
  "Im Bearbeitungsmenü: Gedankenstrich-Modus auf IND festgelegt"

  "Edit Menu: Set indent mode to IND+"
  "Im Bearbeitungsmenü: Set Einzug Modus IND +"

  "Edit Menu: Set indent mode to OFF"
  "Im Bearbeitungsmenü: Gedankenstrich-Modus auf OFF festgelegt."

  "Edit Menu: Set user bindings to global bindings"
  "Im Bearbeitungsmenü: Legen Sie Benutzer-Bindungen auf globale Bindungen"

  "Edit Menu: Set user preferences to global preferences"
  "Im Bearbeitungsmenü: Legen Sie Benutzereinstellungen auf globale Einstellungen"

  "Edit Menu: Undo"
  "Menü Bearbeiten: rückgängig machen"

  "Edit Menu: View base preferences file"
  "Im Bearbeitungsmenü: Basis-Einstellungen-Datei anzeigen"

  "Edit Menu: View global menu bindings"
  "Bearbeitungsmenü: Ansicht-Menü \"

  "Edit Session - Global"
  "Session - Global bearbeiten"

  "Edit Session - Language"
  "Session - Sprache bearbeiten"

  "Edit User"
  "Benutzer bearbeiten"

  "Edit User - Global"
  "Bearbeiten von Benutzer - Global"

  "Edit User - Language"
  "Bearbeiten von Benutzer - Sprache"

  "File"
  "Feile"

  "File Menu: Close all tabs"
  "Im Dateimenü: Alle Tabs schließen"

  "File Menu: Close current tab"
  "Im Dateimenü: Aktuellen Tab schließen"

  "File Menu: Favorite file"
  "Im Dateimenü: Favorit-Datei"

  "File Menu: Lock file"
  "Im Dateimenü: Lock-Datei"

  "File Menu: New file"
  "Im Dateimenü: Neue Datei"

  "File Menu: Open Favorite"
  "Im Dateimenü: Offene Favorit"

  "File Menu: Open Recent"
  "Im Dateimenü: Öffnen Sie den letzten"

  "File Menu: Open directory"
  "Im Dateimenü: Open directory"

  "File Menu: Open file"
  "Dateimenü: Datei öffnen"

  "File Menu: Quit application"
  "Im Dateimenü: Programm beenden"

  "File Menu: Save all files"
  "Im Dateimenü: Speichern Sie alle Dateien"

  "File Menu: Save file"
  "Dateimenü: Datei speichern"

  "File Menu: Save file as"
  "Im Dateimenü: Speichern Sie als Datei"

  "File Menu: Show file difference"
  "Im Dateimenü: Karte Datei Unterschied"

  "File Menu: Unfavorite file"
  "Im Dateimenü: Unfavorite Datei"

  "File Menu: Unlock file"
  "Im Dateimenü: Unlock Datei"

  "Find In Files"
  "In Dateien suchen"

  "Find Matching Pair"
  "Passende paar zu finden"

  "Find Menu: Append next occurrence"
  "Im Menü suchen: Append Suchbegriffes"

  "Find Menu: Create marker at current line"
  "Im Menü suchen: Markierung zur aktuellen Zeile erstellen"

  "Find Menu: Find"
  "Im Menü finden: finden"

  "Find Menu: Find and Replace"
  "Im Menü suchen: Suchen und ersetzen"

  "Find Menu: Find in files"
  "Im Menü suchen: Suchen in Dateien"

  "Find Menu: Find matching character pair"
  "Im Menü suchen: Finden Sie passende paar Zeichen"

  "Find Menu: Find next occurrence"
  "Im Menü suchen: Findet das nächste Vorkommen"

  "Find Menu: Find previous occurrence"
  "Im Menü suchen: Findet das vorherige Vorkommen"

  "Find Menu: Goto next difference"
  "Im Menü suchen: Goto weiter Unterschied"

  "Find Menu: Goto previous difference"
  "Im Menü suchen: Goto Vorheriger Unterschied"

  "Find Menu: Jump backward"
  "Im Menü suchen: Rückwärts springen"

  "Find Menu: Jump forward"
  "Im Menü suchen: Sprung nach vorn"

  "Find Menu: Remove all markers"
  "Im Menü suchen: Entfernen Sie alle Markierungen"

  "Find Menu: Remove marker from current line"
  "Im Menü suchen: Markierung aus der aktuellen Zeile entfernen"

  "Find Menu: Select all occurrences"
  "Im Menü suchen: Wählen Sie alle Vorkommen"

  "Find Menu: Show selected line change"
  "Im Menü suchen: Karte ausgewählte Zeile ändern"

  "Find and Replace"
  "Suchen und Ersetzen"

  "Format Text"
  "Formatieren von Text"

  "From Clipboard"
  "Aus Zwischenablage"

  "Goto Last Tab"
  "Goto Last Tab"

  "Goto Next Tab"
  "Goto Next Tab"

  "Goto Other Pane"
  "Goto Andere Pane"

  "Goto Previous Tab"
  "Zum vorherigen Tab"

  "Help"
  "Hilfe"

  "Help Menu: About TKE"
  "Hilfe-Menü: Über TKE"

  "Help Menu: Check for update"
  "Menü \"

  "Help Menu: Send bug report"
  "Menü \"

  "Help Menu: Send feedback"
  "Menü \"

  "Help Menu: View user guide"
  "Hilfe-Menü: Ansicht-Benutzerhandbuch"

  "Hide Console"
  "Ausblenden Console"

  "Hide Line Numbers"
  "Ausblenden von Zeilennummern"

  "Hide Marker Map"
  "Marker-Karte ausblenden"

  "Hide Meta Characters"
  "Meta-Zeichen ausblenden"

  "Hide Sidebar"
  "Navigationsbereich ausblenden"

  "Hide Status Bar"
  "Statusanzeige ausblenden"

  "Hide Tab Bar"
  "Ausblenden Tab Bar"

  "Indent"
  "Einzug"

  "Indent Mode"
  "Gedankenstrich-Modus"

  "Indent Off"
  "Einzug ab"

  "Insert Enumeration"
  "Einfügen-Enumeration"

  "Insert Text"
  "Seite einfügen"

  "Install..."
  "installieren"

  "Jump Backward"
  "Rückwärts springen"

  "Jump Forward"
  "Vorwärts springen"

  "Launcher"
  "Launcher"

  "Lock"
  "Sperren"

  "Markers"
  "Marker"

  "Menu Bindings"
  "Menü Bindungen"

  "Menus: About TKE"
  "Menüs: Über TKE"

  "Merge Panes"
  "Zusammenführen von Scheiben"

  "Next Difference"
  "Nächster Unterschied"

  "Open Directory..."
  "Verzeichnis öffnen..."

  "Open Favorite"
  "Öffnen Lieblings"

  "Open File..."
  "Datei öffnen..."

  "Open Recent"
  "Öffnen Sie den letzten"

  "Paste"
  "Einfügen"

  "Paste and Format"
  "Einfügen und Format"

  "Plugins"
  "Plugins"

  "Plugins Menu: Create new plugin"
  "Plugins-Menü: Neues Plugin erstellen"

  "Plugins Menu: Install plugin"
  "Plugins-Menü: Install plugin"

  "Plugins Menu: Reload all plugins"
  "Plugins-Menü: Reload alle plugins"

  "Plugins Menu: Uninstall plugin"
  "Plugins-Menü: Uninstall plugin"

  "Preferences"
  "Präferenzen"

  "Previous Difference"
  "Vorheriger Unterschied"

  "Profiling Report Sorted By"
  "Profiling Bericht sortiert"

  "Profiling started"
  "Profiling begonnen"

  "Profiling stopped"
  "Profiling gestoppt"

  "Quit"
  "Beenden"

  "Redo"
  "Redo"

  "Reload"
  "Neu laden"

  "Remove All Markers"
  "Entfernen Sie alle Markierungen"

  "Remove From Current Line"
  "Entfernen Sie aus der aktuellen Zeile"

  "Replace Line With Script"
  "Ersetze die Zeile mit Skript"

  "Reset User to Base"
  "Benutzer auf Basis zurücksetzen"

  "Restart TKE"
  "Starten Sie TKE"

  "Save All"
  "Alle speichern"

  "Save As..."
  "Speichern unter..."

  "Save Current"
  "Aktuelle Oberfläche speichern"

  "Select All"
  "Alle auswählen"

  "Select All Occurrences"
  "Wählen Sie alle Vorkommen"

  "Select Next Occurrence"
  "Wählen Sie die nächstes vorkommen"

  "Select Previous Occurrence"
  "Wählen Sie vorherige Vorkommen"

  "Selected"
  "Ausgewählt"

  "Send Bug Report"
  "Fehlerbericht senden"

  "Send Feedback"
  "Schicken Sie Feedback"

  "Sessions"
  "zur Verfügung steht."

  "Sessions Menu: Close current session"
  "Sessions-Menü: Aktuelle Sitzung schließen"

  "Sessions Menu: Delete session"
  "Sessions-Menü: Delete-Sitzung"

  "Sessions Menu: Open session"
  "Sessions-Menü: Offene Sitzung"

  "Sessions Menu: Save current session"
  "Sessions-Menü: Speichern Sie aktuelle Sitzung"

  "Sessions Menu: Save sessions as"
  "Sessions-Menü: Speichern Sie Sitzungen als"

  "Sessions Menu: Switch to session"
  "Sessions-Menü: Wechseln Sie zur Sitzung"

  "Set Syntax"
  "Stellen Syntax"

  "Set Theme"
  "Stellen Theme"

  "Set User to Global"
  "Set User an globale"

  "Show Console"
  "Konsole einblenden"

  "Show Diagnostic Logfile"
  "Diagnostische Logfile zeigen"

  "Show File Difference"
  "Karte Datei Unterschied"

  "Show Last Profiling Report"
  "Zeige die letzten Profiling melden"

  "Show Line Numbers"
  "Zeilennummern anzeigen"

  "Show Marker Map"
  "Marker anzeigen"

  "Show Meta Characters"
  "Meta-Zeichen anzeigen"

  "Show Selected Line Change"
  "Anzeigen der markierten Zeile ändern"

  "Show Sidebar"
  "Seitenleiste anzeigen"

  "Show Status Bar"
  "Status einblenden"

  "Show Tab Bar"
  "Zeige Tab Bar"

  "Smart Indent"
  "Smart Gedankenstrich"

  "Snippet"
  "Snippet"

  "Snippets"
  "Snippet"

  "Sort Tabs"
  "Tabs sortieren"

  "Start Profiling"
  "Starten Profiling"

  "Stop Profiling"
  "Stoppen Profiling"

  "Switch To"
  "Wechseln Sie zur"

  "Tabs"
  "TAB"

  "Text"
  "Text"

  "Text Menu: Align cursors"
  "Text-Menü: Ausrichten Cursor"

  "Text Menu: Indent selected text"
  "Text-Menü: Ausgewählten Text Einrücken"

  "Text Menu: Insert enumeration"
  "Text-Menü: Einfügen-enumeration"

  "Text Menu: Replace line with script"
  "Text-Menü: Ersetze Zeile mit Skript"

  "Text Menu: Toggle comment"
  "Text-Menü: Toggle Kommentar"

  "Text Menu: Unindent selected text"
  "Text-Menü: Unindent markierten text"

  "Toggle Comment"
  "Knebel-Kommentar"

  "Tools"
  "Instrument"

  "Tools Menu: Disable Vim mode"
  "Extras: Vim-Modus deaktivieren"

  "Tools Menu: Enable Vim mode"
  "Extras: Vim-Modus aktivieren"

  "Tools Menu: Restart TKE"
  "Extras: Neustart TKE"

  "Tools Menu: Run theme editor"
  "Werkzeuge Menü: Führen Theme Editor"

  "Tools Menu: Show diagnostic logfile"
  "Extras: Show diagnostische logfile"

  "Tools Menu: Show last profiling report"
  "Extras: Show letzten profiling Bericht"

  "Tools Menu: Start profiling"
  "Extras: Profilerstellung starten."

  "Tools Menu: Stop profiling"
  "Extras: Profilerstellung beenden"

  "Undo"
  "Rückgängig"

  "Unindent"
  "Unindent"

  "Uninstall..."
  "Entfernen"

  "Unlock"
  "Schalte"

  "User Guide"
  "Benutzerhandbuch"

  "View"
  "Blick"

  "View Base"
  "Ansicht Base"

  "View Global"
  "Ansicht Global"

  "View Menu: Goto last tab"
  "Im Ansichtsmenü: Goto letzten tab"

  "View Menu: Goto next tab"
  "Im Ansichtsmenü: Goto nächste Registerkarte"

  "View Menu: Goto other pane"
  "Menü \"

  "View Menu: Goto previous tab"
  "Im Ansichtsmenü: Goto vorherigen Registerkarte"

  "View Menu: Hide console"
  "Im Ansichtsmenü: Ausblenden-Konsole"

  "View Menu: Hide line numbers"
  "Im Ansichtsmenü: Ausblenden von Zeilennummern"

  "View Menu: Hide marker map"
  "Im Ansichtsmenü: Ausblenden Sie Markierung anzeigen"

  "View Menu: Hide meta characters"
  "Im Ansichtsmenü: Ausblenden von Meta-Zeichen"

  "View Menu: Hide sidebar"
  "Im Ansichtsmenü: Hide sidebar"

  "View Menu: Hide status bar"
  "Im Ansichtsmenü: Ausblenden Sie Statusleiste"

  "View Menu: Hide tab bar"
  "Im Ansichtsmenü: Hide Tab-Leiste"

  "View Menu: Merge panes"
  ": Ansicht Merge Menüleisten"

  "View Menu: Move to other pane"
  "Menü \"

  "View Menu: Show console"
  "Im Ansichtsmenü: Show-Konsole"

  "View Menu: Show line numbers"
  "Menü \"

  "View Menu: Show marker map"
  "Im Ansichtsmenü: Karte Markierung anzeigen"

  "View Menu: Show meta characters"
  "Im Ansichtsmenü: Meta-Zeichen anzeigen"

  "View Menu: Show sidebar"
  "Im Ansichtsmenü: Karte Seitenleiste"

  "View Menu: Show status bar"
  "Im Ansichtsmenü: Statusleiste anzeigen"

  "View Menu: Show tab bar"
  "Im Ansichtsmenü: Karte-Tab-Leiste"

  "View Menu: Sort tabs"
  "Im Ansichtsmenü: Sort tabs"

  "View Menu: Toggle split view mode"
  "Im Ansichtsmenü: Toggle geteilter Ansichtsmodus"

  "Vim Mode"
  "Vim-Modus"

}

# plugins.tcl
msgcat::mcmset de {

  "ERROR"
  "Fehler"

  "ERROR:  Plugin name already exists"
  "ERROR: Plugin Namen ist bereits vorhanden"

  "ERROR:  Plugin name is not valid (only alphanumeric and underscores are allowed)"
  "ERROR: Plugin Name ist nicht gültig (nur alphanumerische Zeichen und Unterstriche sind erlaubt)"

  "ERROR:  Unable to create plugin directory"
  "ERROR: Unable to Plugin-Verzeichnis erstellen"

  "ERROR:  Unable to write plugin files"
  "ERROR: Unable to Plugin-Dateien zu schreiben"

  "Enter plugin name"
  "Geben Sie Name des Plugins"

  "Plugin Errors"
  "Plugin Fehler"

  "Plugin installed"
  "Plugin installiert"

  "Plugin uninstalled"
  "Plugin deinstalliert"

  "Plugins successfully reloaded"
  "Plugins erfolgreich geladen"

  "Syntax errors found in selected plugins"
  "Syntax Fehler in ausgewählten Plugins gefunden"

}

# search.tcl
msgcat::mcmset de {

  "No files found in specified directories"
  "Keine Dateien in den angegebenen Verzeichnissen gefunden"

  "No search results found"
  "Keine Suchergebnisse gefunden"

  "Search wrapped to beginning of file"
  "Suche gewickelt an Anfang der Datei"

  "Search wrapped to end of file"
  "Suche gewickelt zum Ende der Datei"

  "substitutions done"
  "Substitutionen durchgeführt"

}

# sessions.tcl
msgcat::mcmset de {

  "Save session?"
  "Sitzung speichern Zugangsdaten?"

  "Session state will be lost if not saved"
  "Sitzungszustand verloren gehen, wenn nicht gespeichert werden"

}

# sidebar.tcl
msgcat::mcmset de {

  "Add Parent Directory"
  "Übergeordnetes Verzeichnis"

  "Close Directory Files"
  "Schließen Verzeichnis Files"

  "Copy Pathname"
  "Pfadnamen kopieren"

  "Delete directories?"
  "Löschen Sie die Verzeichnisse?"

  "Delete directory?"
  "Verzeichnis löschen?"

  "Delete file?"
  "Datei löschen"

  "Delete files?"
  "Alle Dateien löschen"

  "Directory Name:"
  "Verzeichnisnamen:"

  "Duplicate"
  "Duplikation"

  "File Name:"
  "ファイル名"

  "Folder Name:"
  "Ordnername"

  "Image displayed in sidebar to indicate that a file is currently opened in an editing buffer."
  "Bild in der Seitenleiste angezeigt, um anzugeben, dass eine Datei zur Zeit in einem Editierpuffer eröffnet."

  "Make Current Working Directory"
  "Make Current Working Directory"

  "New Directory"
  "Neues Verzeichnis"

  "Open Directory Files"
  "Open Directory-Dateien"

  "Refresh Directory Files"
  "Aktualisieren Verzeichnis Files"

  "Remove Parent from Sidebar"
  "Entfernen Elternteil von Sidebar"

  "Remove from Sidebar"
  "Entfernen Sidebar"

  "Rename"
  "Benennen"

  "Show Difference"
  "Unterschied zu zeigen"

}

# snippets.tcl
msgcat::mcmset de {

  "Snippet: *"
  "Snippet"

}

# syntax.tcl
msgcat::mcmset de {

  "Syntax"
  "syntax"

  "Syntax error in syntax file"
  "Syntax-Fehler in Syntaxdatei"

}

# theme.tcl
msgcat::mcmset de {

  "Background (trough) color used in the sidebar scrollbar."
  "Hintergrund (Trog) Farbe in der Seitenleiste Bildlaufleiste verwendet wird."

  "Background (trough) color used in the text scrollbars."
  "Hintergrund (Trog) Farbe in den Textbildlaufleisten verwendet."

  "Background color for all sidebar items that are not selected."
  "Hintergrundfarbe für alle Sidebar Elemente, die nicht ausgewählt sind."

  "Background color for all sidebar items that are selected."
  "Hintergrundfarbe für alle Sidebar Elemente, die ausgewählt sind."

  "Background color in difference viewer that shows added lines."
  "Hintergrundfarbe im Unterschied Viewer, der hinzugefügten Zeilen zeigt."

  "Background color in difference viewer that shows deleted lines."
  "Hintergrundfarbe im Unterschied Viewer, der gelöschten Zeilen zeigt."

  "Background color of insertion cursor and background marker colors."
  "Hintergrundfarbe des Einfügemarke und Hintermarkerfarben."

  "Background color of the editing buffer."
  "Hintergrundfarbe des Bearbeitungspuffer."

  "Background color to display when a button-like ttk widget is pressed."
  "Hintergrundfarbe angezeigt, wenn eine knopfartige TTK Widget gedrückt wird."

  "Background color to use for selected text."
  "Hintergrundfarbe für ausgewählten Text zu verwenden."

  "Background color used for all other tabs that are not the current/active tab in the tabbar."
  "Hintergrundfarbe für alle anderen Registerkarten, die nicht die aktuelle / aktive Registerkarte in der Fensterleiste verwendet."

  "Background color used for the current/active menu item."
  "Hintergrundfarbe für die aktuelle / aktive Menüpunkt verwendet."

  "Background color used for the current/active tab in the tabbar."
  "Hintergrundfarbe für die aktuelle / aktive Registerkarte in der Fensterleiste verwendet."

  "Background color used in highlighted text."
  "Hintergrundfarbe in markierten Text verwendet werden."

  "Background color used in menus."
  "Hintergrundfarbe in Menüs verwendet."

  "Background color used in the tabbar area."
  "Hintergrundfarbe in der Fensterleiste Bereich verwendet."

  "Color of border drawn around active editing buffer."
  "Farbe des Rahmens um aktive Bearbeitungspuffer gezeichnet."

  "Color of ttk entry widget text border when the entry has keyboard focus."
  "Farbe des TTK Eintrag Widget Text Grenze, wenn der Eintrag über den Tastaturfokus."

  "Color used to draw the warning width line in the editing buffer (as well as the line separating the gutter from the editing buffer)."
  "Farbe verwendet werden, um die Warnung Breitenlinie im Bearbeitungspuffer (wie auch die Trennlinie zwischen der Dachrinne von der Bearbeitungspuffer) zu zeichnen."

  "Default 'darkcolor' for all ttk widgets."
  "Default &#39;darkcolor&#39; für alle TTK Widgets."

  "Default background color to use for all ttk widgets that are in a disabled state."
  "Standardhintergrundfarbe für alle TTK Widgets, die im deaktivierten Zustand verwenden."

  "Default background color to use for all ttk widgets when the mouse cursor hovers over the widget."
  "Standardhintergrundfarbe für alle TTK-Widgets verwenden, wenn der Mauszeiger über das Widget."

  "Default background color to use for all ttk widgets."
  "Standardhintergrundfarbe für alle TTK-Widgets verwenden."

  "Default border color for all ttk widgets."
  "Standard-Rahmenfarbe für alle TTK Widgets."

  "Default color for non-syntax highlighted text."
  "Standardfarbe für nicht-Syntax hervorgehobenen Text."

  "Default foreground text color to use for all ttk widgets that are in a disabled state."
  "Standardvordergrundtextfarbe für alle TTK Widgets, die im deaktivierten Zustand verwenden."

  "Default foreground text color to use for all ttk widgets."
  "Standardvordergrundtextfarbe für alle TTK-Widgets verwenden."

  "Determines the number of grips strips to display in the grip area between resizable panes."
  "Bestimmt die Anzahl der Griffstreifen in der Griffbereich zwischen resizable Scheiben anzuzeigen."

  "Determines the thickness of the grip area between resizable panes."
  "Bestimmt die Dicke der Griffbereich zwischen resizable Scheiben."

  "ERROR:  Unable to read"
  "Fehler: Datei kann Code Datei lesen"

  "Foreground (slider) color used in the sidebar scrollbar."
  "Vordergrund (Schieberegler) Farbe in der Seitenleiste Bildlaufleiste verwendet wird."

  "Foreground (slider) color used in the text scrollbars."
  "Vordergrund (Schieberegler) Farbe in den Textbildlaufleisten verwendet."

  "Foreground text color for strings."
  "Vordergrund Textfarbe für Streicher."

  "Foreground text color to use for all miscellaneous1 labeled text."
  "Vordergrund Textfarbe für alle miscellaneous1 markierten Text."

  "Foreground text color to use for all miscellaneous2 labeled text."
  "Vordergrund Textfarbe für alle miscellaneous2 markierten Text."

  "Foreground text color to use for all miscellaneous3 labeled text."
  "Vordergrund Textfarbe für alle miscellaneous3 markierten Text."

  "Foreground text color to use for comments."
  "Vordergrund Textfarbe für Kommentare zu verwenden."

  "Foreground text color to use for displaying line numbers."
  "Vordergrund Textfarbe für die Anzeige von Zeilennummern zu verwenden."

  "Foreground text color to use for displaying numbers."
  "Vordergrund Textfarbe für die Anzeige von Zahlen verwenden."

  "Foreground text color to use for language-specific keywords."
  "Vordergrund Textfarbe für sprachspezifische Keywords verwenden."

  "Foreground text color to use for language-specific punctuation."
  "Vordergrund Textfarbe für sprachspezifische Satzzeichen verwenden."

  "Foreground text color to use for meta syntax."
  "Vordergrund Textfarbe für die Meta-Syntax verwenden."

  "Foreground text color to use for precompiler syntax."
  "Vordergrund Textfarbe für Precompiler Syntax verwenden."

  "Foreground text color to use for selected text."
  "Vordergrund Textfarbe für ausgewählten Text zu verwenden."

  "Foreground text color used for menus item that are disabled."
  "Vordergrund Textfarbe für Menüpunkt, die deaktiviert sind, verwendet."

  "Foreground text color used for the current/active menu item."
  "Vordergrund Textfarbe für die aktuelle / aktive Menüpunkt verwendet."

  "Foreground text color used in menus."
  "Vordergrund Textfarbe in Menüs verwendet."

  "Foreground text/image color used in tabbar and tabs."
  "Vordergrund Text / Bild Farbe in Fensterleiste und Tabs verwendet."

  "Images"
  "Bilder"

  "Maximum thickness of the text scrollbar when it is active."
  "Maximale Dicke des Textbildlaufleiste, wenn es aktiv ist."

  "Maximum thickness of the text scrollbars when they are active."
  "Maximale Dicke der Textlaufleisten, wenn sie aktiv sind."

  "Menu Options"
  "Sprungmenü"

  "Menu relief value."
  "Menu Entlastungswert."

  "Pixel height of the tabbar widget."
  "Pixel Höhe der Fensterleiste Widget."

  "Relief used in drawing the tabs."
  "Relief in der Zeichnung die Registerkarten verwendet."

  "Relief value of the sidebar area."
  "Relief Wert der Sidebar-Bereich."

  "Sidebar Options"
  "Siebar Optionen"

  "Sidebar Scrollbar Options"
  "Sidebar Scrollbar Optionen"

  "Specifies the color to display around the sidebar when the sidebar does not have the focus."
  "Gibt die Farbe an, um rund um die Seitenleiste angezeigt werden, wenn die Seitenleiste nicht den Fokus."

  "Specifies the color to display around the sidebar when the sidebar has the focus."
  "Gibt die Farbe zum Anzeigen rund um die Seitenleiste, wenn der Seitenleiste den Fokus hat."

  "Specifies the default background color to use for text that is selected in a standard ttk widget (this does not include the editing buffer)."
  "Gibt die Standardhintergrundfarbe für den Text, der in einem Standard-TTK Widget ausgewählt ist, verwenden (dies beinhaltet nicht die Bearbeitungspuffer)."

  "Specifies the default foreground text color to use for text that is selected in a standard ttk widget (this does not include the editing buffer)."
  "Gibt die Standardvordergrundtextfarbe für Text, der in einem Standard-TTK Widget ausgewählt ist, verwenden (dies beinhaltet nicht die Bearbeitungspuffer)."

  "Specifies the default relief to use when drawing ttk widgets."
  "Gibt die standardmäßige Entlastung beim Zeichnen TTK-Widgets zu bedienen."

  "Specifies the disclosure image style to use in the sidebar."
  "Gibt die Weitergabe-Stil Bild, um in der Seitenleiste zu verwenden."

  "Specifies the pixel thickness of the highlight line."
  "Gibt das Pixeldicke der Highlight Linie."

  "Syntax Colors"
  "Syntax Farben"

  "Tab Options"
  "Registerkarte Optionen"

  "Text Scrollbar Options"
  "Text Scrollbar Optionen"

  "Text color for all sidebar items that are not selected."
  "Textfarbe für alle Sidebar Elemente, die nicht ausgewählt sind."

  "Text color for all sidebar items that are selected."
  "Textfarbe für alle Sidebar Elemente, die ausgewählt sind."

  "ttk Widget Colors"
  "TTK Widget Farben"

}

# themer.tcl
msgcat::mcmset de {

  "   Show All"
  "Alle anzeigen"

  "   Show Category"
  "Kategorie anzeigen"

  "   Show Color"
  "Zeige Farbe"

  "   Show Selected Option"
  "Ausgewählte Option anzeigen"

  "   Show Selected Value"
  "Ausgewählter Wert"

  "Categories"
  "Kategorien"

  "Change Base Color"
  "Farbe ändern"

  "Choose Theme"
  "Theme auswählen"

  "Custom Directory"
  "Benutzerverzeichnis"

  "Custom..."
  "Benutzerdefiniert..."

  "Delete swatch?"
  "Farbfeld löschen?"

  "Description"
  "Beschreibung"

  "Details"
  "<span style=\"

  "Done"
  "Fertig"

  "Export"
  "Exportieren"

  "GIF Photo"
  "GIF Foto"

  "Import"
  "Import"

  "Import BMP Data"
  "Daten importieren"

  "Import BMP Mask"
  "Import BMP Mask"

  "Import Error"
  "Importfehler"

  "Import Theme File"
  "Import Theme Datei"

  "Installation Directory"
  "Installationsverzeichnis"

  "Modifications"
  "Änderungen"

  "None"
  "Ohne"

  "One-Color Bitmap"
  "One-Color Bitmap"

  "Preview"
  "Vorschau"

  "Relief: "
  "Entlastung:"

  "Save As:"
  "Speichern als"

  "Save theme changes?"
  "Speichere das Thema Veränderungen?"

  "Select Directory"
  "Verzeichnis auswählen"

  "Swatch"
  "Probe:"

  "Swatch Colors"
  "Swatch Farben"

  "Table Filters"
  "Tabelle Filter"

  "The current theme has unsaved changes"
  "Das aktuelle Thema hat nicht gespeicherte Änderungen"

  "Tree Style: "
  "Baum-Stil:"

  "Two-Color Bitmap"
  "Zwei-Farben-Bitmap"

  "User Directory"
  "Benutzerverzeichnis"

  "Value"
  "Wert"

  "Value: "
  "Wert:"

}

# themes.tcl
msgcat::mcmset de {

  "Theme"
  "﻿Theme"

  "Theme:*"
  "﻿Theme"

}

# tke.tcl
msgcat::mcmset de {

  "Import TKE theme?"
  "Import TKE Thema?"

  "Import TextMate theme?"
  "Importieren TextMate Thema?"

}

# tkedat.tcl
msgcat::mcmset de {

  "Unable to read"
  "Datei kann nicht gelesen werden"

}

# vim.tcl
msgcat::mcmset de {

  "File successfully written"
  "Datei erfolgreich geschrieben"

  "Filename already exists"
  "Dateiname ist bereits vorhanden."

}

# General
msgcat::mcmset de {

  "All"
  "Alle"

  "Cancel"
  "Abbrechen"

  "Close"
  "schließen"

  "Delete"
  "Löschen"

  "Favorite"
  "Bevorzugte"

  "Find"
  "Finden"

  "Move to Other Pane"
  "Verschieben in andere Pane"

  "New File"
  "Neue Datei"

  "Open"
  "Geöffnet"

  "Save"
  "Speichern"

  "Save As"
  "Speichern unter"

  "Split View"
  "Split anzeigen"

  "Theme Editor"
  "Motiv-Bearbeitung"

  "Unable to write"
  "Datei konnte nicht geschrieben werden"

  "Unfavorite"
  "Unfavorite"

}

