# api.tcl
msgcat::mcmset de {

  "Argument list to api::add_file was not an even key/value pair"
  "Argument Liste api::add_file war nicht ein noch Schlüssel / Wert-Paar"

}

# bgproc.tcl
msgcat::mcmset de {

  "Unable to run system command (%s)"
  "Kann System Befehl ausführen (%s)"

}

# diff.tcl
msgcat::mcmset de {

  "    End: "
  "Ende:"

  "    Start: "
  "Beginn:"

  "Enter difference command"
  "Geben Sie Befehl difference"

  "Enter starting file"
  "Geben Sie die Startdatei"

  "Update"
  "Aktualisieren"

}

# gui.tcl
msgcat::mcmset de {

  "%s, Line: %d, Column: %d"
  "% S, Zeile:% d, Spalte:% d"

  "Case sensitivity"
  "Groß-und Kleinschreibung"

  "Close All Tabs"
  "Close All Tabs"

  "Close Other Tab(s)"
  "Schließen Andere Tab(s)"

  "Close Other*"
  "Andere Unterfenster schließen"

  "Close Tab"
  "Tab schließen"

  "Copyright %d-%d"
  "Urheber% d% d-"

  "Delete tab?"
  "Löschen Registerkarte?"

  "Developer:"
  "Entwickler:"

  "Email:"
  "E-Mail:"

  "Error"
  "Fehler"

  "Favorited"
  "Favorit"

  "File already exists.  Use '!' to force an overwrite"
  "Datei existiert bereits.  Verwendung '!' eine Überschreibung zu erzwingen"

  "File attribute (%s) does not exist"
  "Datei-Attribut (%s) existiert nicht"

  "File index is out of range"
  "Datei-Index außerhalb des zulässigen Bereichs"

  "License:"
  "Lizenz:"

  "Line: %d, Column: %d"
  "Zeile: %d, Spalte: %d"

  "Locked"
  "Lock"

  "Move*"
  "Move"

  "Must be in multicursor mode to insert numbers"
  "Muss im multicursor-Modus um Zahlen einzusetzen sein."

  "No write permissions.  Use '!' to force write."
  "Keine Schreibrechte.  Verwendung '!' schreiben zu erzwingen."

  "Release Type:"
  "Release-Typ:"

  "Reload file?"
  "Datei erneut laden"

  "Save request"
  "Speichern Anfrage"

  "Show in Sidebar"
  "Show in Sidebar"

  "Starting number:"
  "Startnummer:"

  "Tcl/Tk Version:"
  "Tcl/Tk-Version:"

  "Total Lines: %d, Total Characters: %d"
  "TOTAL Lines:% d, Gesamt Zeichen:% d"

  "Unable to find current file (tab: %s)"
  "Kann nicht aktuellen Datei (tab:% s)"

  "Unable to successfully parse number string"
  "Nicht in der Lage, Anzahl Zeichenfolge erfolgreich analysiert"

  "Unable to write file"
  "Datei konnte nicht geschrieben werden"

  "Untitled"
  "Untitled"

  "Version:"
  "Version:"

}

# markers.tcl
msgcat::mcmset de {

  "Marker name:"
  "Marker Namen:"

}

# menus.tcl
msgcat::mcmset de {

  "                                  Profiling Report Sorted By (%s)"
  "                                Profiling melden Sortiert nach (%s)"

  "About TKE"
  "Über TKE"

  "Align Cursors"
  "Ausrichten von Cursorn"

  "Append Next Occurrence"
  "Suchbegriffes anfügen"

  "Auto-Indent"
  "Auto-Einzug"

  "Check for Update"
  "Nach Update suchen"

  "Clear All"
  "Alles löschen"

  "Close All"
  "Alle schließen"

  "Close Current"
  "Strom zu schließen"

  "Copy"
  "Kopieren"

  "Create New..."
  "Neu erstellen"

  "Create at Current Line"
  "Zur aktuellen Zeile erstellen"

  "Create..."
  "Erstellen..."

  "Cut"
  "Schneiden"

  "Edit"
  "Bearbeiten"

  "Edit Language"
  "Sprachen bearbeiten"

  "Edit Session - Global"
  "Session - Global bearbeiten"

  "Edit Session - Language"
  "Session - Sprache bearbeiten"

  "Edit User"
  "Benutzer bearbeiten"

  "Edit User - Global"
  "Bearbeiten von Benutzer - Global"

  "Edit User - Language"
  "Bearbeiten von Benutzer - Sprache"

  "Edit..."
  "Bearbeiten"

  "File"
  "Feile"

  "Find"
  "Finden"

  "Find In Files"
  "In Dateien suchen"

  "Find Matching Pair"
  "Passende paar zu finden"

  "Find and Replace"
  "Suchen und Ersetzen"

  "Format Text"
  "Formatieren von Text"

  "From Clipboard"
  "Aus Zwischenablage"

  "Goto Last Tab"
  "Goto Last Tab"

  "Goto Next Tab"
  "Goto Next Tab"

  "Goto Other Pane"
  "Goto Andere Pane"

  "Goto Previous Tab"
  "Zum vorherigen Tab"

  "Help"
  "Hilfe"

  "Hide Console"
  "Ausblenden Console"

  "Hide Line Numbers"
  "Ausblenden von Zeilennummern"

  "Hide Meta Characters"
  "Meta-Zeichen ausblenden"

  "Hide Sidebar"
  "Navigationsbereich ausblenden"

  "Hide Status Bar"
  "Statusanzeige ausblenden"

  "Hide Tab Bar"
  "Ausblenden Tab Bar"

  "Import TextMate Theme..."
  "Importieren Sie TextMate Theme..."

  "Indent"
  "Einzug"

  "Indent Mode"
  "Gedankenstrich-Modus"

  "Indent Off"
  "Einzug ab"

  "Insert Enumeration"
  "Einfügen-Enumeration"

  "Insert Text"
  "Seite einfügen"

  "Install..."
  "installieren"

  "Jump Backward"
  "Rückwärts springen"

  "Jump Forward"
  "Vorwärts springen"

  "Launcher"
  "Launcher"

  "Lock"
  "Sperren"

  "Markers"
  "Marker"

  "Menu Bindings"
  "Menü Bindungen"

  "Menu Edit user snippets"
  "Menü Bearbeiten Benutzer Ausschnitte"

  "Menu: About TKE"
  "Menü: Über TKE"

  "Menu: Align cursors"
  "Menü: Richten Cursor"

  "Menu: Append next occurrence"
  "Menü: anhängen nächste Vorkommen"

  "Menu: Check for Update"
  "Nach Update suchen"

  "Menu: Close all tabs"
  "Alle Tabs schließen"

  "Menu: Close current session"
  "Menü: Aktuelle Sitzung, schließen"

  "Menu: Close current tab"
  "Aktuelles Unterfenster schließen"

  "Menu: Copy text"
  "Menü: Text kopieren"

  "Menu: Create marker at current line"
  "Menü: Marker zur aktuellen Zeile erstellen"

  "Menu: Create new plugin"
  "Menü: Neues Plugin"

  "Menu: Create new theme"
  "Neues Design erstellen..."

  "Menu: Cut text"
  ": Menütext Cut"

  "Menu: Delete session"
  "Menü: Delete-Sitzung"

  "Menu: Disable Vim mode"
  "Menü: Deaktivieren Vim-Modus"

  "Menu: Edit Tke theme"
  "Menü: Bearbeiten Tke Thema"

  "Menu: Edit language snippets"
  "Menü: Bearbeiten-Sprache-Ausschnitte"

  "Menu: Edit session current language preferences"
  "Menü: Bearbeiten Sie Sitzung aktuellen Spracheinstellungen"

  "Menu: Edit session global preferences"
  "Menü: Bearbeiten Sie globale Sitzungseinstellungen"

  "Menu: Edit user current language preferences"
  "Menü: Bearbeiten Sie aktuelle Sprache Benutzereinstellungen."

  "Menu: Edit user global preferences"
  "Menü: Bearbeiten Sie Benutzer globale Voreinstellungen"

  "Menu: Edit user menu bindings"
  "Menü: Bearbeiten Benutzermenü Bindungen"

  "Menu: Enable Vim mode"
  "Menü: Aktivieren Vim-Modus"

  "Menu: Favorite file"
  "Menü: Lieblings Datei"

  "Menu: Find"
  "Menü: Finden"

  "Menu: Find and Replace"
  "Suchen und Ersetzen"

  "Menu: Find in files"
  "Menü: Suche in Dateien"

  "Menu: Find matching character pair"
  "Menü: Finden Sie passende Charakter Paar"

  "Menu: Find next occurrence"
  "Menü: Nächstes Vorkommen"

  "Menu: Find previous occurrence"
  "Menü: Finden vorherige Vorkommen"

  "Menu: Format all text"
  "Menü: Formatieren Sie den gesamten Text"

  "Menu: Format selected text"
  "Menü: Format markierten Text"

  "Menu: Goto last tab"
  "Menü: Springen letzten Reiter"

  "Menu: Goto next difference"
  "Menü: Goto weiter Unterschied"

  "Menu: Goto next tab"
  "Menü: Gehe nächste Register"

  "Menu: Goto other pane"
  "Menü: Springen anderen Fensterbereich"

  "Menu: Goto previous difference"
  "Menü: Goto Vorheriger Unterschied"

  "Menu: Goto previous tab"
  "Menü: Springen vorherigen Registerkarte"

  "Menu: Hide Line Numbers"
  "Menü: Ausblenden Zeilennummern"

  "Menu: Hide Tab Bar"
  "Menü: Hide Tab Bar"

  "Menu: Hide console"
  "Menü: Konsole ausblenden"

  "Menu: Hide meta characters"
  "Menü: Ausblenden von Meta-Zeichen"

  "Menu: Hide sidebar"
  "Menü: Sidebar ausblenden"

  "Menu: Hide status bar"
  "Statusanzeige ausblenden"

  "Menu: Import TextMate theme"
  "Menü: Import TextMate Thema"

  "Menu: Indent selected text"
  "Menü: Text einzurücken ausgewählt"

  "Menu: Insert enumeration"
  "Menü: Legen Aufzählung"

  "Menu: Insert from clipboard"
  "Einfügen per Zwischenablage"

  "Menu: Insert snippet"
  "Menü: Einfügen Snippet"

  "Menu: Install plugin"
  "Menü: Plugin installieren"

  "Menu: Jump backward"
  "Menü: Rückwärts springen"

  "Menu: Jump forward"
  "Menü: Sprung nach vorn"

  "Menu: Lock file"
  "Menü: Lock-Datei"

  "Menu: Merge panes"
  ": Menüleisten Merge"

  "Menu: Move to other pane"
  "Menü: auf andere Fenster verschieben"

  "Menu: New file"
  "Menü: Neue Datei"

  "Menu: Open Favorite"
  "Menü: Open Lieblings"

  "Menu: Open Recent"
  "Menü: Öffnen zuletzt"

  "Menu: Open directory"
  "Menü: Öffnen eines Verzeichnis-"

  "Menu: Open file"
  "Menü: Öffnen Sie die Datei"

  "Menu: Open session"
  "Menü: Offene Sitzung"

  "Menu: Paste and format text from clipboard"
  "Menü: Einfügen und Formatieren von Text aus der Zwischenablage"

  "Menu: Paste text from clipboard"
  "Text aus Zwischenablage einfügen"

  "Menu: Quit application"
  "Menü: Quit Anwendung"

  "Menu: Redo"
  "Menü: Redo"

  "Menu: Reload all plugins"
  "Menü: alle Plugins neu laden"

  "Menu: Reload snippets"
  "Menü: Reload Ausschnitte"

  "Menu: Remove all markers"
  "Menü: Entfernen Sie alle Markierungen"

  "Menu: Remove marker from current line"
  "Menü: Aktuelle Zeile Marker entfernen"

  "Menu: Replace line with script"
  "Menü: Ersetze Zeile mit Skript"

  "Menu: Restart tke"
  "Menü: Starten tke"

  "Menu: Save all files"
  "Menü: Speichern Sie alle Dateien"

  "Menu: Save current session"
  "Menü: Speichern Sie aktuelle Sitzung"

  "Menu: Save file"
  "Menü: Datei speichern"

  "Menu: Save file as"
  "Menü: Datei speichern"

  "Menu: Save sessions as"
  "Menü: Speichern Sie Sitzungen als"

  "Menu: Select all occurrences"
  "Menü: Wählen Sie alle Vorkommen"

  "Menu: Select all text"
  "Gesamten Text auswählen"

  "Menu: Send Bug Report"
  "Menü: Send-Bug-Report"

  "Menu: Send Feedback"
  "Menü: Feedback senden"

  "Menu: Set indent mode to IND"
  "Menü: IND Gedankenstrich-Modus gesetzt."

  "Menu: Set indent mode to IND+"
  "Menü: Gedankenstrich-Modus auf IND + festgelegt."

  "Menu: Set indent mode to OFF"
  "Menü: Gedankenstrich-Modus auf OFF festgelegt."

  "Menu: Set user bindings to global bindings"
  "Menü: Einrichten von Benutzer Bindungen zu globalen Bindungen"

  "Menu: Set user preferences to global preferences"
  "Menü: Legen Sie die Benutzereinstellungen zu globalen Einstellungen"

  "Menu: Show Diagnostic Logfile"
  "Menü: Show Diagnose Logfile"

  "Menu: Show Line Numbers"
  "Menü: Zeilennummern anzeigen"

  "Menu: Show Tab Bar"
  "Menü: Show Tab Bar"

  "Menu: Show console"
  "Menü: Show-Konsole"

  "Menu: Show file difference"
  "Menü: Karte Datei Unterschied"

  "Menu: Show last profiling report"
  "Menü: anzeigen Profilierung letzten Bericht"

  "Menu: Show meta characters"
  "Menü: Meta-Zeichen anzeigen"

  "Menu: Show selected line change"
  "Menü: Anzeigen aktiviert Zeile ändern"

  "Menu: Show sidebar"
  "Menü: Seitenleiste anzeigen"

  "Menu: Show status bar"
  "Status einblenden"

  "Menu: Sort tabs"
  "Menü: Sortieren Registerkarten"

  "Menu: Start profiling"
  "Menü: Start-Profiling"

  "Menu: Stop profiling"
  "Menü: Stop-Profiling"

  "Menu: Switch to session"
  "Menü: Switch-Sitzung"

  "Menu: Toggle comment"
  "Menü: Toggle Kommentar"

  "Menu: Toggle split view mode"
  "Menü: Toggle-Split-Ansicht-Modus"

  "Menu: Undo"
  "Menü: Rückgängig"

  "Menu: Unfavorite file"
  "Menü: Datei Unfavorite"

  "Menu: Unindent selected text"
  "Menü: Unindent ausgewählten Text"

  "Menu: Uninstall plugin"
  "Menü: Uninstall plugin"

  "Menu: Unlock file"
  "Menü: Datei entsperren"

  "Menu: View User Guide"
  "Menü: Ansicht Benutzerhandbuch"

  "Menu: View base preferences file"
  "Menü: Ansicht-Basis-Voreinstellungsdatei"

  "Menu: View global menu bindings"
  "Menü: Globale Menü Bindungen"

  "Merge Panes"
  "Zusammenführen von Scheiben"

  "Next Difference"
  "Nächster Unterschied"

  "Open Directory..."
  "Verzeichnis öffnen..."

  "Open Favorite"
  "Öffnen Lieblings"

  "Open File..."
  "Datei öffnen..."

  "Open Recent"
  "Öffnen Sie den letzten"

  "Paste"
  "Einfügen"

  "Paste and Format"
  "Einfügen und Format"

  "Plugins"
  "Plugins"

  "Preferences"
  "Präferenzen"

  "Previous Difference"
  "Vorheriger Unterschied"

  "Profiling started"
  "Profiling begonnen"

  "Profiling stopped"
  "Profiling gestoppt"

  "Quit"
  "Beenden"

  "Redo"
  "Redo"

  "Reload"
  "Neu laden"

  "Remove All Markers"
  "Entfernen Sie alle Markierungen"

  "Remove From Current Line"
  "Entfernen Sie aus der aktuellen Zeile"

  "Replace Line With Script"
  "Ersetze die Zeile mit Skript"

  "Reset User to Base"
  "Benutzer auf Basis zurücksetzen"

  "Restart TKE"
  "Starten Sie TKE"

  "Save All"
  "Alle speichern"

  "Save As..."
  "Speichern unter..."

  "Save Current"
  "Aktuelle Oberfläche speichern"

  "Select All"
  "Alle auswählen"

  "Select All Occurrences"
  "Wählen Sie alle Vorkommen"

  "Select Next Occurrence"
  "Wählen Sie die nächstes vorkommen"

  "Select Previous Occurrence"
  "Wählen Sie vorherige Vorkommen"

  "Selected"
  "Ausgewählt"

  "Send Bug Report"
  "Fehlerbericht senden"

  "Send Feedback"
  "Schicken Sie Feedback"

  "Sessions"
  "zur Verfügung steht."

  "Set Syntax"
  "Stellen Syntax"

  "Set Theme"
  "Stellen Theme"

  "Set User to Global"
  "Set User an globale"

  "Show Console"
  "Konsole einblenden"

  "Show Diagnostic Logfile"
  "Diagnostische Logfile zeigen"

  "Show File Difference"
  "Karte Datei Unterschied"

  "Show Last Profiling Report"
  "Zeige die letzten Profiling melden"

  "Show Line Numbers"
  "Zeilennummern anzeigen"

  "Show Meta Characters"
  "Meta-Zeichen anzeigen"

  "Show Selected Line Change"
  "Anzeigen der markierten Zeile ändern"

  "Show Sidebar"
  "Seitenleiste anzeigen"

  "Show Status Bar"
  "Status einblenden"

  "Show Tab Bar"
  "Zeige Tab Bar"

  "Show*Profiling*"
  "Zeige*Profiling*"

  "Smart Indent"
  "Smart Gedankenstrich"

  "Snippet"
  "Snippet"

  "Snippets"
  "Snippet"

  "Sort Tabs"
  "Tabs sortieren"

  "Split View"
  "Split anzeigen"

  "Start Profiling"
  "Starten Profiling"

  "Stop Profiling"
  "Stoppen Profiling"

  "Switch To"
  "Wechseln Sie zur"

  "Tabs"
  "TAB"

  "Text"
  "Text"

  "Theme Creator"
  "Theme Creator"

  "Toggle Comment"
  "Knebel-Kommentar"

  "Tools"
  "Instrument"

  "Undo"
  "Rückgängig"

  "Unindent"
  "Unindent"

  "Uninstall..."
  "Entfernen"

  "Unlock"
  "Schalte"

  "User Guide"
  "Benutzerhandbuch"

  "View"
  "Blick"

  "View Base"
  "Ansicht Base"

  "View Global"
  "Ansicht Global"

  "Vim Mode"
  "Vim-Modus"

}

# plugins.tcl
msgcat::mcmset de {

  "ERROR (%s,%s): %s"
  "Fehler (%s, %s): %s"

  "ERROR:  Plugin name already exists"
  "ERROR: Plugin Namen ist bereits vorhanden"

  "ERROR:  Plugin name is not valid (only alphanumeric and underscores are allowed)"
  "ERROR: Plugin Name ist nicht gültig (nur alphanumerische Zeichen und Unterstriche sind erlaubt)"

  "ERROR:  Unable to create plugin directory"
  "ERROR: Unable to Plugin-Verzeichnis erstellen"

  "ERROR:  Unable to write plugin files"
  "ERROR: Unable to Plugin-Dateien zu schreiben"

  "Enter plugin name"
  "Geben Sie Name des Plugins"

  "Plugin %s installed"
  "Plugin %s installiert"

  "Plugin %s uninstalled"
  "Plugin %s deinstalliert"

  "Plugin Errors"
  "Plugin Fehler"

  "Plugins successfully reloaded"
  "Plugins erfolgreich geladen"

  "Syntax errors found in selected plugins"
  "Syntax Fehler in ausgewählten Plugins gefunden"

}

# search.tcl
msgcat::mcmset de {

  "%d substitutions done"
  "%d Ersetzungen durchgeführt"

  "No files found in specified directories"
  "Keine Dateien in den angegebenen Verzeichnissen gefunden"

  "No search results found"
  "Keine Suchergebnisse gefunden"

  "Search wrapped to beginning of file"
  "Suche gewickelt an Anfang der Datei"

  "Search wrapped to end of file"
  "Suche gewickelt zum Ende der Datei"

}

# sidebar.tcl
msgcat::mcmset de {

  "Add Parent Directory"
  "Übergeordnetes Verzeichnis"

  "Close Directory Files"
  "Schließen Verzeichnis Files"

  "Copy Pathname"
  "Pfadnamen kopieren"

  "Delete directory?"
  "Verzeichnis löschen?"

  "Delete file?"
  "Datei löschen"

  "Directory Name:"
  "Verzeichnisnamen:"

  "Duplicate"
  "Duplikation"

  "File Name:"
  "ファイル名"

  "Folder Name:"
  "Ordnername"

  "Make Current Working Directory"
  "Make Current Working Directory"

  "New Directory"
  "Neues Verzeichnis"

  "Open Directory Files"
  "Open Directory-Dateien"

  "Refresh Directory Files"
  "Aktualisieren Verzeichnis Files"

  "Remove Parent from Sidebar"
  "Entfernen Elternteil von Sidebar"

  "Remove from Sidebar"
  "Entfernen Sidebar"

  "Rename"
  "Benennen"

  "Show Difference"
  "Unterschied zu zeigen"

}

# snippets.tcl
msgcat::mcmset de {

  "Snippet: *"
  "Snippet"

}

# syntax.tcl
msgcat::mcmset de {

  "Syntax error in %s.syntax file"
  "Syntax-Fehler in %s.syntax Datei"

  "Syntax:  %s"
  "Syntax: %s"

  "Theme:  %s"
  "Theme: %s"

}

# themer.tcl
msgcat::mcmset de {

  "Create"
  "Erstellen"

  "Create New Theme"
  "Neues Design erstellen..."

  "Create custom"
  "Erstellen von benutzerdefinierten"

  "ERROR:  Unable to read %s"
  "FEHLER: %s lesen"

  "ERROR:  Unable to write %s"
  "FEHLER: %s schreiben"

  "Edit theme"
  "Thema bearbeiten"

  "Enter theme name"
  "Geben Thema Namen"

  "Error:  Theme is not a supported theme"
  "Fehler: Theme wird nicht unterstützt Thema"

  "Import"
  "Import"

  "Import TextMate Theme"
  "Importieren TextMate Theme"

  "Name:"
  "Name:"

  "OK"
  "OK"

  "Reset"
  "Reset"

  "Select theme"
  "Designdatei auswählen"

}

# tke.tcl
msgcat::mcmset de {

  "Edit theme?"
  "Thema bearbeiten?"

  "Import TextMate theme?"
  "Importieren TextMate Thema?"

}

# vim.tcl
msgcat::mcmset de {

  "File %s successfully written"
  "Datei> %s erfolgreich geschrieben!"

  "Filename %s already exists"
  "Dateinamen %s ist bereits vorhanden."

}

# General
msgcat::mcmset de {

  "All"
  "Alle"

  "Cancel"
  "Abbrechen"

  "Close"
  "schließen"

  "Delete"
  "Löschen"

  "Favorite"
  "Bevorzugte"

  "Find:"
  "Suchen nach:"

  "Move to Other Pane"
  "Verschieben in andere Pane"

  "New File"
  "Neue Datei"

  "Open"
  "Geöffnet"

  "Replace:"
  "Ersetzen:"

  "Save"
  "Speichern"

  "Save As"
  "Speichern unter"

  "Unable to open %s for writing"
  "Kein Schreibzugriff auf Datei (%s)"

  "Unfavorite"
  "Unfavorite"

}

