# api.tcl
msgcat::mcmset el {

  "Argument list to api::add_file was not an even key/value pair"
  "Κατάλογος των argument στο api :: add_file δεν ήταν ακόμη ζεύγος κλειδιού / τιμής"

  "Plugin-%s: %s"
  "Η έκδοση του Σερβοβόσνιου στρατιωτικού ηγέτη εν καιρώ πολέμου, Ράτκο Μλάντιτς, παραμένει « βασικότερος όρος », δήλωσε ο Λιάιτς, προειδοποιώντας ότι η έλλειψη πλήρους συνεργασίας με το ICTY μπορεί να ριψοκινδυνεύσει τη διαδικασία Ευρω- Ατλαντικής ενσωμάτωσης της Σερβίας- Μαυροβουνίου."

}

# bgproc.tcl
msgcat::mcmset el {

  "Unable to run system command (%s)"
  "Ανίκανος να τρέχει εντολή του συστήματος (% s)"

}

# diff.tcl
msgcat::mcmset el {

  "    End: "
  "ΤΕΛΟΣ"

  "    Start: "
  "Έναρξη"

  "Enter difference command"
  "Εισάγετε την εντολή διαφορά"

  "Enter starting file"
  "Εισαγάγετε το αρχείο εκκίνησης"

  "Update"
  "Ενημέρωση"

}

# gui.tcl
msgcat::mcmset el {

  "%s, Line: %d, Column: %d"
  "% S, γραμμή:% d, Στήλη:% d"

  "Case sensitivity"
  "αναζήτηση βάσει πλήρους αντιστοίχισης"

  "Close All Tabs"
  "Κλείσιμο όλων των ετικετών"

  "Close Other Tab(s)"
  "Κλείσιμο Άλλα Tab (s)"

  "Close Other*"
  "Κλείσιμο των άλλων καρτελών"

  "Close Tab"
  "Κλείσιμο καρτέλας"

  "Copyright %d-%d"
  "Copyright% d-% d"

  "Delete tab?"
  "Διαγραφή καρτέλας;"

  "Developer:"
  "Προγραμματιστής:"

  "Email:"
  "Email:"

  "Error"
  "Σφάλμα!"

  "Favorited"
  "Αγαπημένο"

  "File already exists.  Use '!' to force an overwrite"
  "Το αρχείο υπάρχει ήδη.  Χρήση «!» να αναγκάσει την επανεγγραφή του τομέα"

  "File attribute (%s) does not exist"
  "Χαρακτηριστικό αρχείου (% s) δεν υπάρχει"

  "File index is out of range"
  "Δείκτης αρχείου είναι εκτός ορίων"

  "License:"
  "?????:"

  "Line: %d, Column: %d"
  "Γραμμή:% d, Στήλη:% d"

  "Locked"
  "κλειδωμένος"

  "Move*"
  "Μετακίνηση *"

  "Must be in multicursor mode to insert numbers"
  "Πρέπει να είναι σε multicursor κατάσταση λειτουργίας για να εισάγετε αριθμούς"

  "No write permissions.  Use '!' to force write."
  "Δεν δικαιώματα εγγραφής.  Χρήση «!» να αναγκάσει εγγραφής."

  "Release Type:"
  "ΔΕΛΤΙΟ ΤΥΠΟΥ:"

  "Reload file?"
  "Επαναφόρτωση αρχείου"

  "Save request"
  "Αποθηκεύστε το αίτημα"

  "Show in Sidebar"
  "Εμφάνιση στο Sidebar"

  "Starting number:"
  "Αρχικό αριθμό:"

  "Tcl/Tk Version:"
  "Έκδοση Tcl/Tk:"

  "Total Lines: %d, Total Characters: %d"
  "Σύνολο Lines:% d, Σύνολο Χαρακτήρες:% d"

  "Unable to find current file (tab: %s)"
  "Ανίκανος να βρει το τρέχον αρχείο (καρτέλα:% s)"

  "Unable to successfully parse number string"
  "Δυνατό να αναλύσει με επιτυχία αριθμός συμβολοσειρά"

  "Unable to write file"
  "Δεν είναι δυνατή η εγγραφή αρχείου"

  "Version:"
  "Έκδοση"

}

# markers.tcl
msgcat::mcmset el {

  "Marker name:"
  "Όνομα Marker:"

}

# menus.tcl
msgcat::mcmset el {

  "                                  Profiling Report Sorted By (%s)"
  "Έκθεση Profiling Ταξινόμηση Με (% s)"

  "About TKE"
  "Σχετικά με ΤΚΕ"

  "Align Cursors"
  "???????? ???????"

  "Append Next Occurrence"
  "?????????? ?µ??????"

  "Auto-Indent"
  "Αυτο-εντομή"

  "Check for Update"
  "Έλεγχος για ενημέρωση"

  "Clear All"
  "Καθαρισμός όλων"

  "Close All"
  "Κλείσιμο όλων"

  "Close Current"
  "??????? ?? ?????"

  "Copy"
  "Αντιγραφή"

  "Create at Current Line"
  "???????????? ???? ???????? ??????"

  "Create..."
  "Δημιουργία"

  "Cut"
  "Αποκοπή"

  "Edit"
  "Επεξεργασία"

  "Edit Language"
  "Επεξεργασία Γλώσσας"

  "Edit Menu Edit user snippets"
  "Επεξεργαστείτε το μενού Επεξεργασία χρήστη αποσπάσματα"

  "Edit Menu: Copy text"
  "Μενού \"

  "Edit Menu: Cut text"
  "Μενού \"

  "Edit Menu: Edit language snippets"
  "Μενού \"

  "Edit Menu: Edit session current language preferences"
  "Μενού \"

  "Edit Menu: Edit session global preferences"
  "Μενού \"

  "Edit Menu: Edit user current language preferences"
  "Μενού \"

  "Edit Menu: Edit user global preferences"
  "Μενού \"

  "Edit Menu: Edit user menu bindings"
  "Μενού \"

  "Edit Menu: Format all text"
  "Μενού \"

  "Edit Menu: Format selected text"
  "Μενού \"

  "Edit Menu: Insert from clipboard"
  "Μενού \"

  "Edit Menu: Insert snippet"
  "Μενού \"

  "Edit Menu: Paste and format text from clipboard"
  "Μενού \"

  "Edit Menu: Paste text from clipboard"
  "Μενού \"

  "Edit Menu: Redo"
  "Επεξεργαστείτε τα μενού: Ακύρωση αναίρεσης"

  "Edit Menu: Reload snippets"
  "Μενού \"

  "Edit Menu: Select all text"
  "Μενού \"

  "Edit Menu: Set indent mode to IND"
  "Μενού \"

  "Edit Menu: Set indent mode to IND+"
  "Μενού \"

  "Edit Menu: Set indent mode to OFF"
  "Μενού \"

  "Edit Menu: Set user bindings to global bindings"
  "Μενού \"

  "Edit Menu: Set user preferences to global preferences"
  "Μενού \"

  "Edit Menu: Undo"
  "Επεξεργαστείτε τα μενού: αναίρεση"

  "Edit Menu: View base preferences file"
  "Μενού \"

  "Edit Menu: View global menu bindings"
  "Μενού \"

  "Edit Session - Global"
  "?????????????? ???????? - ?????????"

  "Edit Session - Language"
  "???????? - ???????????? ?? ??????"

  "Edit User"
  "Επεξεργασία χρήστη"

  "Edit User - Global"
  "?????????????? ?? ?????? - ?????????"

  "Edit User - Language"
  "?????? - ???????????? ?? ??????"

  "File"
  "Αρχείο"

  "File Menu: Close all tabs"
  "Μενού αρχείο: Κλείσιμο όλων των καρτελών"

  "File Menu: Close current tab"
  "Μενού αρχείο: Κλείνω τρέχων ετικέτα"

  "File Menu: Favorite file"
  "Μενού αρχείου: Αγαπημένο αρχείο"

  "File Menu: Lock file"
  "Μενού αρχείο: Αρχείο κλείδωμα"

  "File Menu: New file"
  "Μενού αρχείο: Νέο αρχείο"

  "File Menu: Open Favorite"
  "Μενού αρχείο: Ανοικτή αγαπημένο"

  "File Menu: Open Recent"
  "Μενού αρχείο: Άνοιγμα πρόσφατες"

  "File Menu: Open directory"
  "Μενού αρχείο: Open directory"

  "File Menu: Open file"
  "Μενού αρχείο: Ανοίξτε το αρχείο"

  "File Menu: Quit application"
  "Μενού αρχείο: Κλείστε την εφαρμογή"

  "File Menu: Save all files"
  "Μενού αρχείο: Αποθηκεύσετε όλα τα αρχεία"

  "File Menu: Save file"
  "Μενού αρχείο: Αποθήκευση αρχείου"

  "File Menu: Save file as"
  "Μενού αρχείο: Αποθηκεύστε το αρχείο ως"

  "File Menu: Show file difference"
  "Μενού αρχείο: Εμφάνιση αρχείο διαφορά"

  "File Menu: Unfavorite file"
  "Μενού αρχείο: Αρχείο Unfavorite"

  "File Menu: Unlock file"
  "Μενού αρχείο: Ξεκλειδώσετε αρχείο"

  "Find"
  "Find"

  "Find In Files"
  "?????? ??? ??????"

  "Find Matching Pair"
  "?????? ?????????? ??????"

  "Find Menu: Append next occurrence"
  "Find μενού: Προσάρτηση εµφάνιση"

  "Find Menu: Create marker at current line"
  "Find μενού: Δημιουργία δείκτη στην τρέχουσα γραμμή"

  "Find Menu: Find"
  "Βρείτε το μενού: βρείτε"

  "Find Menu: Find and Replace"
  "Find μενού: Εύρεση και αντικατάσταση"

  "Find Menu: Find in files"
  "Find μενού: Βρείτε στα αρχεία"

  "Find Menu: Find matching character pair"
  "Find μενού: Βρείτε ταιριάζουν ζεύγος χαρακτήρα"

  "Find Menu: Find next occurrence"
  "Find μενού: Βρείτε την επόμενη εμφάνιση"

  "Find Menu: Find previous occurrence"
  "Find μενού: Βρείτε την προηγούμενη εμφάνιση"

  "Find Menu: Goto next difference"
  "Find μενού: Goto επόμενο διαφορά"

  "Find Menu: Goto previous difference"
  "Μενού Εύρεση: Προηγούμενη διαφορά Goto"

  "Find Menu: Jump backward"
  "Find μενού: Άλμα προς τα πίσω"

  "Find Menu: Jump forward"
  "Find μενού: Άλμα προς τα εμπρός"

  "Find Menu: Remove all markers"
  "Find μενού: Αφαιρέσετε όλα δείκτες"

  "Find Menu: Remove marker from current line"
  "Find μενού: Δείκτη κατάργηση από την τρέχουσα γραμμή"

  "Find Menu: Select all occurrences"
  "Find μενού: Επιλέξτε όλες τις εμφανίσεις"

  "Find Menu: Show selected line change"
  "Find μενού: Αλλαγή γραμμής εμφάνιση επιλεγεί"

  "Find and Replace"
  "Εύρεση και αντικατάσταση"

  "Format Text"
  "Μορφή κειμένου"

  "From Clipboard"
  "Από το πρόχειρο"

  "Goto Last Tab"
  "Μετάβαση Last Tab"

  "Goto Next Tab"
  "Μετάβαση Next Tab"

  "Goto Other Pane"
  "Μετάβαση Άλλα Παράθυρο"

  "Goto Previous Tab"
  "Μετάβαση Προηγούμενη Tab"

  "Help"
  "Βοήθεια"

  "Help Menu: About TKE"
  "Μενού βοήθειας: Για την ΤΚΕ"

  "Help Menu: Check for update"
  "Μενού \"

  "Help Menu: Send bug report"
  "Μενού \"

  "Help Menu: Send feedback"
  "Μενού \"

  "Help Menu: View user guide"
  "Μενού \"

  "Hide Console"
  "Απόκρυψη Console"

  "Hide Line Numbers"
  "Απόκρυψη αριθμών γραμμών"

  "Hide Meta Characters"
  "???????? ???? ??????????"

  "Hide Sidebar"
  "Απόκρυψη πλευρικής μπάρας"

  "Hide Status Bar"
  "Απόκρυψη Status Bar"

  "Hide Tab Bar"
  "Απόκρυψη Tab Bar"

  "Indent"
  "Εσοχή"

  "Indent Mode"
  "Εντομή μοντέλο"

  "Indent Off"
  "Εσοχή από"

  "Insert Enumeration"
  "???????? ???????????"

  "Insert Text"
  "Εισαγωγή ευρετηρίου"

  "Install..."
  "εγκαθιστώ"

  "Jump Backward"
  "???? ???? ?? ????"

  "Jump Forward"
  "???? ???? ?? ??????"

  "Launcher"
  "Προωθητής"

  "Lock"
  "Κλείδωμα"

  "Markers"
  "Σημεία"

  "Menu Bindings"
  "Δέστρες Μενού"

  "Menus: About TKE"
  "Μενού: Σχετικά με την ΤΚΕ"

  "Merge Panes"
  "?????????? ???????? ?????????"

  "Next Difference"
  "??????? ???????"

  "Open Directory..."
  "Άνοιγμα καταλόγου"

  "Open Favorite"
  "Open Αγαπημένα"

  "Open File..."
  "Άνοιγμα αρχείου..."

  "Open Recent"
  "Άνοιγμα πρόσφατου"

  "Paste"
  "Επικόλληση"

  "Paste and Format"
  "Επικόλληση και Format"

  "Plugins"
  "Plug-in"

  "Plugins Menu: Create new plugin"
  "Plugins μενού: Δημιουργήστε νέο plugin"

  "Plugins Menu: Install plugin"
  "Μενού plugins: Εγκατάσταση plugin"

  "Plugins Menu: Reload all plugins"
  "Plugins μενού: Φορτώσετε εκ νέου όλα τα plugins"

  "Plugins Menu: Uninstall plugin"
  "Plugins μενού: Απεγκατάσταση plugin"

  "Preferences"
  "Προτιμήσεις"

  "Previous Difference"
  "??????????? ???????"

  "Profiling started"
  "Profiling ξεκίνησε"

  "Profiling stopped"
  "Profiling σταματήσει"

  "Quit"
  "έξοδος"

  "Redo"
  "Επανάληψη"

  "Reload"
  "Επαναφόρτωση"

  "Remove All Markers"
  "????????? ??? ???????"

  "Remove From Current Line"
  "????????? ??? ??? ???????? ??????"

  "Replace Line With Script"
  "?????????????? ??? ?????? ?? ???????"

  "Reset User to Base"
  "Ξαναρυθμίζω χρήστη στη βάση"

  "Restart TKE"
  "???????????? ???"

  "Save All"
  "Αποθήκευση όλων"

  "Save As..."
  "Αποθήκευση ως"

  "Save Current"
  "???????????? ?? ?????"

  "Select All"
  "Επιλογή όλων"

  "Select All Occurrences"
  "???????? ???? ??? ??????????"

  "Select Next Occurrence"
  "???????? ?µ??????"

  "Select Previous Occurrence"
  "???????? ??? ??????????? ????????"

  "Selected"
  "Επιλεγμ."

  "Send Bug Report"
  "Στείλτε την αναφορά σφαλμάτων"

  "Send Feedback"
  "Αποστολή Σχολίων"

  "Sessions"
  "?????????"

  "Sessions Menu: Close current session"
  "Συνεδρίες μενού: Κλείσετε την τρέχουσα περίοδο λειτουργίας"

  "Sessions Menu: Delete session"
  "Συνεδρίες μενού: Συνεδρία διαγραφή"

  "Sessions Menu: Open session"
  "Συνεδρίες μενού: Ανοικτή συνεδρία"

  "Sessions Menu: Save current session"
  "Συνεδρίες μενού: Αποθηκεύσετε την τρέχουσα περίοδο λειτουργίας"

  "Sessions Menu: Save sessions as"
  "Συνεδρίες μενού: Σώσει συνεδρίες ως"

  "Sessions Menu: Switch to session"
  "Συνεδρίες μενού: Μετάβαση σε συνεδρία"

  "Set Syntax"
  "Ορισμός Σύνταξη"

  "Set Theme"
  "Ορισμός Θέμα"

  "Set User to Global"
  "Χρήστη που ορίζεται στην παγκόσμια"

  "Show Console"
  "Εμφάνιση Console"

  "Show Diagnostic Logfile"
  "Εμφάνιση διαγνωστικό Logfile"

  "Show File Difference"
  "Εμφάνιση αρχείου διαφορά"

  "Show Last Profiling Report"
  "Εμφάνιση Τελευταία Έκθεση Profiling"

  "Show Line Numbers"
  "Εμφάνιση αριθμών γραμμών"

  "Show Meta Characters"
  "???? ?????????? ????????"

  "Show Selected Line Change"
  "???????????? ?????????? ?????? ??????"

  "Show Sidebar"
  "Εμφάνιση πλευρικής μπάρας"

  "Show Status Bar"
  "Γραμμή κατάστασης"

  "Show Tab Bar"
  "Γραμμή καρτελών"

  "Smart Indent"
  "Έξυπνες περίπτωση"

  "Snippet"
  "Απόσπασμα"

  "Snippets"
  "Αποσπάσματα"

  "Sort Tabs"
  "Sort Tabs"

  "Start Profiling"
  "Ξεκινήστε Profiling"

  "Stop Profiling"
  "Σταματήστε Profiling"

  "Switch To"
  "????????? ??"

  "Tabs"
  "Δισκία"

  "Text"
  "Κείμενο"

  "Text Menu: Align cursors"
  "Μενού κείμενο: Στοίχιση δρομείς"

  "Text Menu: Indent selected text"
  "Κείμενο μενού: Εσοχή επιλεγμένου κειμένου"

  "Text Menu: Insert enumeration"
  "Κείμενο μενού: Εισαγωγή καταμέτρηση"

  "Text Menu: Replace line with script"
  "Κείμενο μενού: Αντικαταστήστε την γραμμή με σενάριο"

  "Text Menu: Toggle comment"
  "Κείμενο μενού: Εναλλαγή σχόλιο"

  "Text Menu: Unindent selected text"
  "Κείμενο μενού: Κατάργηση εσοχής του επιλεγμένου κειμένου"

  "Toggle Comment"
  "???????? ??????"

  "Tools"
  "Μέσα δράσης"

  "Tools Menu: Disable Vim mode"
  "Μενού Εργαλεία: Απενεργοποίηση λειτουργίας Vim"

  "Tools Menu: Enable Vim mode"
  "Εργαλεία μενού: Ενεργοποίηση της λειτουργίας Vim"

  "Tools Menu: Restart TKE"
  "Μενού Εργαλεία: Επανεκκίνηση ΤΚΕ"

  "Tools Menu: Run theme editor"
  "Εργαλεία Μενού: Εκτέλεση editor θέμα"

  "Tools Menu: Show diagnostic logfile"
  "Μενού Εργαλεία: Διαγνωστικά logfile Εμφάνιση"

  "Tools Menu: Show last profiling report"
  "Μενού Εργαλεία: Εμφάνιση τελευταία έκθεση προφίλ"

  "Tools Menu: Start profiling"
  "Μενού Εργαλεία: Έναρξη δημιουργίας προφίλ"

  "Tools Menu: Stop profiling"
  "Μενού Εργαλεία: Σταματήσει προφίλ"

  "Undo"
  "Αναίρεση"

  "Unindent"
  "Κατάργηση εσοχής"

  "Uninstall..."
  "κατάργηση εγκατάστασης"

  "Unlock"
  "Ξεκλείδωμα"

  "User Guide"
  "Οδηγός χρήστη"

  "View"
  "Προβολή"

  "View Base"
  "Προβολή βάσης"

  "View Global"
  "Παγκόσμια προβολή"

  "View Menu: Goto last tab"
  "Μενού Προβολή: Goto τελευταία καρτέλα"

  "View Menu: Goto next tab"
  "Μενού Προβολή: Επόμενη καρτέλα Goto"

  "View Menu: Goto other pane"
  "Μενού Προβολή: Goto άλλο παράθυρο"

  "View Menu: Goto previous tab"
  "Μενού Προβολή: Προηγούμενη καρτέλα Goto"

  "View Menu: Hide console"
  "Μενού \"

  "View Menu: Hide line numbers"
  "Μενού \"

  "View Menu: Hide meta characters"
  "Μενού \"

  "View Menu: Hide sidebar"
  "Μενού \"

  "View Menu: Hide status bar"
  "Μενού \"

  "View Menu: Hide tab bar"
  "Μενού \"

  "View Menu: Merge panes"
  "Μενού \"

  "View Menu: Move to other pane"
  "Μενού \"

  "View Menu: Show console"
  "Μενού \"

  "View Menu: Show line numbers"
  "Μενού \"

  "View Menu: Show meta characters"
  "Μενού \"

  "View Menu: Show sidebar"
  "Μενού \"

  "View Menu: Show status bar"
  "Μενού \"

  "View Menu: Show tab bar"
  "Μενού \"

  "View Menu: Sort tabs"
  "Μενού \"

  "View Menu: Toggle split view mode"
  "Μενού \"

  "Vim Mode"
  "Λειτουργία Vim"

}

# plugins.tcl
msgcat::mcmset el {

  "ERROR (%s,%s): %s"
  "ΣΦΆΛΜΑ (%s %s): %s"

  "ERROR:  Plugin name already exists"
  "ΣΦΑΛΜΑ: Plugin όνομα υπάρχει ήδη"

  "ERROR:  Plugin name is not valid (only alphanumeric and underscores are allowed)"
  "ΣΦΑΛΜΑ: Plugin όνομα δεν είναι έγκυρο (μόνο αλφαριθμητικά και οι κάτω παύλες)"

  "ERROR:  Unable to create plugin directory"
  "ΣΦΑΛΜΑ: Δεν είναι δυνατή η δημιουργία του καταλόγου plugin"

  "ERROR:  Unable to write plugin files"
  "ΣΦΑΛΜΑ: Δεν είναι για να γράψει plugin αρχεία"

  "Enter plugin name"
  "Πληκτρολογήστε το όνομα του plugin"

  "Plugin %s installed"
  "Plugin% s εγκαταστάθηκε"

  "Plugin %s uninstalled"
  "Plugin% s απεγκατασταθεί"

  "Plugin Errors"
  "Plugin Λάθη"

  "Plugins successfully reloaded"
  "Plugins reloaded με επιτυχία"

  "Syntax errors found in selected plugins"
  "Συντακτικά λάθη τα βρείτε σε επιλεγμένα plugins"

}

# search.tcl
msgcat::mcmset el {

  "%d substitutions done"
  "%d αντικαταστάσεις κάνει"

  "No files found in specified directories"
  "Δεν βρέθηκαν σε καθορισμένους καταλόγους αρχεία"

  "No search results found"
  "Δε βρέθηκαν αποτελέσματα αναζήτησης"

  "Search wrapped to beginning of file"
  "Αναζήτηση τυλιγμένο στην αρχή του αρχείου"

  "Search wrapped to end of file"
  "Αναζήτηση τυλιγμένο στο τέλος του αρχείου"

}

# sidebar.tcl
msgcat::mcmset el {

  "Add Parent Directory"
  "Μητρικός Κατάλογος"

  "Close Directory Files"
  "Κλείσιμο Κατάλογος αρχείων"

  "Copy Pathname"
  "?????????? ?? ????? ?????????"

  "Delete directory?"
  "Διαγραφή κατάλογο;"

  "Delete file?"
  "Διαγραφή αρχείου"

  "Directory Name:"
  "Όνομα καταλόγου:"

  "Duplicate"
  "Αναπαραγωγή"

  "File Name:"
  "Όνομα αρχείου:"

  "Folder Name:"
  "????? ???????:"

  "Make Current Working Directory"
  "Κάντε τρέχων κατάλογος εργασίας"

  "New Directory"
  "Νέα Directory"

  "Open Directory Files"
  "Αρχεία Open Directory"

  "Refresh Directory Files"
  "Ανανέωση Κατάλογος αρχείων"

  "Remove Parent from Sidebar"
  "Κατάργηση της Μητρικής από το Sidebar"

  "Remove from Sidebar"
  "Αφαιρέστε από το Sidebar"

  "Rename"
  "Μετονομασία"

  "Show Difference"
  "Εμφάνιση διαφορά"

}

# snippets.tcl
msgcat::mcmset el {

  "Snippet: *"
  "Απόσπασμα: *"

}

# syntax.tcl
msgcat::mcmset el {

  "Syntax error in %s.syntax file"
  "Συντακτικό σφάλμα στο αρχείο% s.syntax"

  "Syntax: %s"
  "Σύνταξη: %s"

}

# theme.tcl
msgcat::mcmset el {

  "ERROR:  Unable to read %s"
  "ΣΦΑΛΜΑ: Αδύνατη η ανάγνωση του% s"

  "Images"
  "Εικόνες"

  "Menu Options"
  "Επιλογές Μενού"

  "Sidebar Options"
  "Sidebar Επιλογές"

  "Sidebar Scrollbar Options"
  "Sidebar Επιλογές κύλισης"

  "Syntax Colors"
  "Σύνταξη Χρώματα"

  "Tab Options"
  "Καρτέλα Επιλογές"

  "Text Scrollbar Options"
  "Κείμενο Επιλογές κύλισης"

  "ttk Widget Colors"
  "TTK Widget Χρώματα"

}

# themer.tcl
msgcat::mcmset el {

  "   Show All"
  "E"

  "   Show Category"
  "Εμφάνιση Κατηγορίας"

  "   Show Color"
  "Εμφάνιση Χρώματος Φόντου"

  "   Show Selected Option"
  "Εμφάνιση επιλεγμένων Επιλογή"

  "   Show Selected Value"
  "Εμφάνιση επιλεγμένη τιμή"

  "Categories"
  "Κατηγορίες"

  "Change Base Color"
  "Αλλαγή χρώματος βάσης"

  "Choose Theme"
  "Επιλέξτε θέμα εμφάνισης"

  "Custom Directory"
  "Προσαρμοσμένο Κατάλογο"

  "Custom..."
  "Προσαρμοσμένο"

  "Delete swatch?"
  "Διαγραφή Swatch;"

  "Description"
  "Περιγραφή"

  "Details"
  "Λεπτομέρειες"

  "Done"
  "Ολοκληρώθηκε"

  "Export"
  "Εξαγωγή"

  "GIF Photo"
  "GIF Φωτογραφία"

  "Import"
  "Εισαγωγή"

  "Import BMP Data"
  "Εισαγωγή BMP Δεδομένων"

  "Import BMP Mask"
  "Εισαγωγή BMP Μάσκα"

  "Import Error"
  "Σφάλμα εισαγωγής"

  "Import Theme File"
  "Εισαγωγή Θέμα αρχείου"

  "Installation Directory"
  "Κατάλογος εγκατάστασης"

  "Modifications"
  "Τροποποιήσεις"

  "None"
  "Κανένα"

  "One-Color Bitmap"
  "Ένα-Color Bitmap"

  "Preview"
  "Προεπισκόπιση"

  "Relief: "
  "συναισθηματικη εκτονωση"

  "Save As:"
  "Αποθήκευση ως:"

  "Save theme changes?"
  "Αποθηκεύστε τις αλλαγές θέμα;"

  "Select Directory"
  "Επιλογή καταλόγου"

  "Swatch"
  "Δείγμα υφάσματος"

  "Swatch Colors"
  "Swatch Χρώματα"

  "Table Filters"
  "Φίλτρα Πίνακας"

  "The current theme has unsaved changes"
  "Το σημερινό θέμα έχει μη αποθηκευμένες αλλαγές"

  "Theme Editor %s %s"
  "Θέμα Εκδότης% s% s"

  "Tree Style: "
  "Δέντρο Στυλ:"

  "Two-Color Bitmap"
  "Δύο-χρώμα Bitmap"

  "User Directory"
  "Χρήστης Κατάλογος"

  "Value"
  "Τιμή"

  "Value: "
  "Τιμή:"

}

# themes.tcl
msgcat::mcmset el {

  "Theme:  %s"
  "Θέμα:% s"

  "Theme:*"
  "Θέμα"

}

# tke.tcl
msgcat::mcmset el {

  "Import TKE theme?"
  "Θέμα Εισαγωγή ΤΚΕ;"

  "Import TextMate theme?"
  "Εισαγωγή TextMate θέμα;"

}

# tkedat.tcl
msgcat::mcmset el {

  "Unable to open %s for reading"
  "Ανίκανος να ανοίξει %s για ανάγνωση"

}

# vim.tcl
msgcat::mcmset el {

  "File %s successfully written"
  "Το αρχείο %s με επιτυχία γραπτές"

  "Filename %s already exists"
  "Υπάρχει ήδη το όνομα του αρχείου %s"

}

# General
msgcat::mcmset el {

  "All"
  "All"

  "Cancel"
  "Ακύρωση"

  "Close"
  "Κλείσιμο"

  "Delete"
  "Διαγραφή"

  "Favorite"
  "Αγαπημένο"

  "Find:"
  "Find"

  "Move to Other Pane"
  "Μετακίνηση σε άλλες Παράθυρο"

  "New File"
  "Νέο αρχείο"

  "Open"
  "Ανοιχτό"

  "Replace:"
  "Το κάτωθι:"

  "Save"
  "Αποθήκευση"

  "Save As"
  "Αποθήκευση ως"

  "Split View"
  "?????????? ???????"

  "Theme Editor"
  "Θέμα Εκδότης"

  "Unable to open %s for writing"
  "Αδύνατο το άνοιγμα του%1 για εγγραφή"

  "Unfavorite"
  "Μη αγαπημένα"

}

