# api.tcl
msgcat::mcmset el {

  "Argument list to api::add_file was not an even key/value pair"
  "Κατάλογος των argument στο api :: add_file δεν ήταν ακόμη ζεύγος κλειδιού / τιμής"

  "Plugin"
  "Πρόσθετο"

}

# bgproc.tcl
msgcat::mcmset el {

  "Unable to run system command"
  "Δεν είναι δυνατή η εκτέλεση εντολής συστήματος"

}

# diff.tcl
msgcat::mcmset el {

  "    End: "
  "ΤΕΛΟΣ"

  "    Start: "
  "Έναρξη"

  "Enter difference command"
  "Εισάγετε την εντολή διαφορά"

  "Enter starting file"
  "Εισαγάγετε το αρχείο εκκίνησης"

  "Update"
  "Ενημέρωση"

}

# edit.tcl
msgcat::mcmset el {

  "File successfully written"
  "Αρχείο γραμμένο με επιτυχία"

  "Filename already exists"
  "Όνομα αρχείου που υπάρχει ήδη"

}

# embed_tke.tcl
msgcat::mcmset el {

  "Find:"
  "Find"

  "Replace:"
  "Το κάτωθι:"

}

# gui.tcl
msgcat::mcmset el {

  "All"
  "All"

  "Case sensitivity"
  "αναζήτηση βάσει πλήρους αντιστοίχισης"

  "Close All Tabs"
  "Κλείσιμο όλων των ετικετών"

  "Close Other Tabs"
  "Κλείσιμο άλλων καρτελών"

  "Close Other*"
  "Κλείσιμο των άλλων καρτελών"

  "Close Tab"
  "Κλείσιμο καρτέλας"

  "Column"
  "Στήλη"

  "Copyright"
  "Πνευματικά Δικαιώματα"

  "Delete tab?"
  "Διαγραφή καρτέλας;"

  "Developer"
  "Προγραμματιστή"

  "Email"
  "Email"

  "Error"
  "Σφάλμα!"

  "Favorited"
  "Αγαπημένο"

  "File already exists.  Use '!' to force an overwrite"
  "Το αρχείο υπάρχει ήδη.  Χρήση «!» να αναγκάσει την επανεγγραφή του τομέα"

  "File attribute does not exist"
  "Δεν υπάρχει χαρακτηριστικό αρχείου"

  "File index is out of range"
  "Δείκτης αρχείου είναι εκτός ορίων"

  "Image displayed in fill-in forms which closes the form UI.  Used in forms such as search, search/replace, and find in files."
  "Εικόνα εμφανίζεται σε μορφές γεμίσματος που κλείνει τη φόρμα UI. Χρησιμοποιείται σε μορφές όπως η αναζήτηση, αναζήτηση / αντικατάσταση, και να βρείτε στα αρχεία."

  "Image used in tab menus to indicate that the file is associated with a difference view."
  "Εικόνας που χρησιμοποιείται στα μενού tab για να υποδείξει ότι το αρχείο συνδέεται με μια άποψη διαφορά."

  "Image used in tab menus to indicate that the file is locked."
  "Εικόνα που χρησιμοποιείται στα μενού καρτέλα για να υποδείξει ότι το αρχείο είναι κλειδωμένο."

  "Image used in tab menus to indicate that the file is readonly."
  "Εικόνα που χρησιμοποιείται στα μενού καρτέλα για να υποδείξει ότι το αρχείο είναι μόνο για ανάγνωση."

  "Image used in tab to indicate that the tab contains a difference view."
  "Εικόνας που χρησιμοποιείται στην καρτέλα για να δείξει ότι η καρτέλα περιέχει μια άποψη διαφορά."

  "Image used in tab to indicate that the tab's file is readonly."
  "Εικόνας που χρησιμοποιείται στην καρτέλα για να υποδείξει ότι το αρχείο της καρτέλας είναι μόνο για ανάγνωση."

  "Image used in tab to indicate that the tab’s file is locked."
  "Εικόνας που χρησιμοποιείται στην καρτέλα για να υποδείξει ότι το αρχείο της καρτέλας είναι κλειδωμένο."

  "Image used in tab which, when clicked, closes the tab."
  "Εικόνα που χρησιμοποιούνται στην καρτέλα που, όταν πατηθεί, κλείνει την καρτέλα."

  "License"
  "Άδεια"

  "Line"
  "Γραμμή"

  "Locked"
  "κλειδωμένος"

  "Move"
  "Κίνηση"

  "Must be in multicursor mode to insert numbers"
  "Πρέπει να είναι σε multicursor κατάσταση λειτουργίας για να εισάγετε αριθμούς"

  "No write permissions.  Use '!' to force write."
  "Δεν δικαιώματα εγγραφής.  Χρήση «!» να αναγκάσει εγγραφής."

  "Release Type"
  "ΔΕΛΤΙΟ ΤΥΠΟΥ"

  "Reload file?"
  "Επαναφόρτωση αρχείου"

  "Replace"
  "Αντικαταστήστε"

  "Save request"
  "Αποθηκεύστε το αίτημα"

  "Show in Sidebar"
  "Εμφάνιση στο Sidebar"

  "Starting number:"
  "Αρχικό αριθμό:"

  "Tcl/Tk Version"
  "Έκδοση Tcl/Tk"

  "Total Characters"
  "Σύνολο χαρακτήρων"

  "Total Lines"
  "Σύνολο γραμμών"

  "Unable to successfully parse number string"
  "Δυνατό να αναλύσει με επιτυχία αριθμός συμβολοσειρά"

  "Unable to write file"
  "Δεν είναι δυνατή η εγγραφή αρχείου"

  "Version"
  "Έκδοση"

}

# markers.tcl
msgcat::mcmset el {

  "Marker name:"
  "Όνομα Marker:"

}

# menus.tcl
msgcat::mcmset el {

  "About TKE"
  "Σχετικά με ΤΚΕ"

  "Absolute"
  "Απόλυτος"

  "Align Cursors"
  "???????? ???????"

  "Append Next Occurrence"
  "?????????? ?µ??????"

  "Auto-Indent"
  "Αυτο-εντομή"

  "Bubble Down"
  "Φούσκα κάτω"

  "Bubble Up"
  "Φούσκα"

  "Change Working Directory"
  "Αλλαγή Κατάλογος εργασίας"

  "Character"
  "Χαρακτήρας"

  "Check for Update"
  "Έλεγχος για ενημέρωση"

  "Classic Mac"
  "Κλασικό Mac"

  "Clear All"
  "Καθαρισμός όλων"

  "Close All"
  "Κλείσιμο όλων"

  "Close Current"
  "??????? ?? ?????"

  "Command"
  "Εντολή"

  "Command Result"
  "Εντολή αποτέλεσμα"

  "Copy"
  "Αντιγραφή"

  "Create"
  "Δημιουργία"

  "Create at Current Line"
  "???????????? ???? ???????? ??????"

  "Current Line"
  "Τρέχουσα γραμμή"

  "Current Number"
  "Τρέχων αριθμός"

  "Current Word"
  "Τρέχουσας λέξης"

  "Cursor"
  "Δρομέα"

  "Cursor from Line Start"
  "Δρομέα από την αρχή γραμμής"

  "Cursor to Line End"
  "Δρομέα να άκρο της γραμμής"

  "Cut"
  "Αποκοπή"

  "Display Text Info"
  "Εμφανίζει τις πληροφορίες κείμενο"

  "Edit"
  "Επεξεργασία"

  "Edit Language"
  "Επεξεργασία Γλώσσας"

  "Edit Menu Edit user snippets"
  "Επεξεργαστείτε το μενού Επεξεργασία χρήστη αποσπάσματα"

  "Edit Menu: Align cursors"
  "Μενού \"

  "Edit Menu: Bubble lines down one line"
  "Μενού \"

  "Edit Menu: Bubble lines up one line"
  "Μενού \"

  "Edit Menu: Convert case to lower"
  "Μενού \"

  "Edit Menu: Convert case to title"
  "Μενού \"

  "Edit Menu: Convert case to upper"
  "Μενού \"

  "Edit Menu: Copy text"
  "Μενού \"

  "Edit Menu: Cut text"
  "Μενού \"

  "Edit Menu: Delete current line"
  "Μενού \"

  "Edit Menu: Delete current word"
  "Μενού \"

  "Edit Menu: Delete from cursor to end of line"
  "Μενού \"

  "Edit Menu: Delete from start of line to cursor"
  "Μενού \"

  "Edit Menu: Delete template"
  "Μενού \"

  "Edit Menu: Delete text between character"
  "Μενού \"

  "Edit Menu: Delete the current number"
  "Μενού \"

  "Edit Menu: Delete the whitespace to left of cursor"
  "Μενού \"

  "Edit Menu: Delete the whitespace to right of cursor"
  "Μενού \"

  "Edit Menu: Edit language snippets"
  "Μενού \"

  "Edit Menu: Edit session current language preferences"
  "Μενού \"

  "Edit Menu: Edit session global preferences"
  "Μενού \"

  "Edit Menu: Edit template"
  "Μενού \"

  "Edit Menu: Edit user current language preferences"
  "Μενού \"

  "Edit Menu: Edit user global preferences"
  "Μενού \"

  "Edit Menu: Edit user menu bindings"
  "Μενού \"

  "Edit Menu: Format indentation for text"
  "Μενού \"

  "Edit Menu: Indent selected text"
  "Μενού \"

  "Edit Menu: Insert command result after current line"
  "Μενού \"

  "Edit Menu: Insert file contents after current line"
  "Μενού \"

  "Edit Menu: Insert from clipboard"
  "Μενού \"

  "Edit Menu: Insert line above current line"
  "Μενού \"

  "Edit Menu: Insert line below current line"
  "Μενού \"

  "Edit Menu: Insert snippet"
  "Μενού \"

  "Edit Menu: Join lines"
  "Μενού \"

  "Edit Menu: Move cursor to bottom of screen"
  "Μενού \"

  "Edit Menu: Move cursor to end of current line"
  "Μενού \"

  "Edit Menu: Move cursor to first line"
  "Μενού \"

  "Edit Menu: Move cursor to last line"
  "Μενού \"

  "Edit Menu: Move cursor to middle of screen"
  "Μενού \"

  "Edit Menu: Move cursor to next page"
  "Μενού \"

  "Edit Menu: Move cursor to next word"
  "Μενού \"

  "Edit Menu: Move cursor to previous page"
  "Μενού \"

  "Edit Menu: Move cursor to previous word"
  "Μενού \"

  "Edit Menu: Move cursor to start of current line"
  "Μενού \"

  "Edit Menu: Move cursor to top of screen"
  "Μενού \"

  "Edit Menu: Move multicursors down one line"
  "Μενού \"

  "Edit Menu: Move multicursors left one line"
  "Μενού \"

  "Edit Menu: Move multicursors right one line"
  "Μενού \"

  "Edit Menu: Move multicursors up one line"
  "Μενού \"

  "Edit Menu: Paste and format text from clipboard"
  "Μενού \"

  "Edit Menu: Paste text from clipboard"
  "Μενού \"

  "Edit Menu: Redo"
  "Επεξεργαστείτε τα μενού: Ακύρωση αναίρεσης"

  "Edit Menu: Reload snippets"
  "Μενού \"

  "Edit Menu: Reload template information"
  "Μενού \"

  "Edit Menu: Replace line with script"
  "Μενού \"

  "Edit Menu: Select all text"
  "Μενού \"

  "Edit Menu: Set indent mode to IND"
  "Μενού \"

  "Edit Menu: Set indent mode to IND+"
  "Μενού \"

  "Edit Menu: Set indent mode to OFF"
  "Μενού \"

  "Edit Menu: Set user bindings to global bindings"
  "Μενού \"

  "Edit Menu: Set user preferences to global preferences"
  "Μενού \"

  "Edit Menu: Toggle case of current character"
  "Μενού Επεξεργασία: ΕΝΑΛΛΑΓΗ πεζών-ΚΕΦΑΛΑΙΩΝ τρέχουσα χαρακτήρα"

  "Edit Menu: Toggle comment"
  "Μενού \"

  "Edit Menu: Undo"
  "Επεξεργαστείτε τα μενού: αναίρεση"

  "Edit Menu: Unindent selected text"
  "Μενού \"

  "Edit Menu: View base preferences file"
  "Μενού \"

  "Edit Menu: View global menu bindings"
  "Μενού \"

  "Edit Session - Global"
  "?????????????? ???????? - ?????????"

  "Edit Session - Language"
  "???????? - ???????????? ?? ??????"

  "Edit User"
  "Επεξεργασία χρήστη"

  "Edit User - Global"
  "?????????????? ?? ?????? - ?????????"

  "Edit User - Language"
  "?????? - ???????????? ?? ??????"

  "Enumeration"
  "Καταμέτρηση"

  "File"
  "Αρχείο"

  "File Contents"
  "Περιεχόμενα του αρχείου"

  "File Menu: Change working directory"
  "Μενού αρχείο: Αλλάξετε κατάλογο εργασίας"

  "File Menu: Close all tabs"
  "Μενού αρχείο: Κλείσιμο όλων των καρτελών"

  "File Menu: Close current tab"
  "Μενού αρχείο: Κλείνω τρέχων ετικέτα"

  "File Menu: Delete current file"
  "Μενού αρχείο: Διαγραφή τρέχοντος αρχείου"

  "File Menu: Duplicate current file"
  "Μενού αρχείο: Αντίγραφο τρέχοντος αρχείου"

  "File Menu: Favorite file"
  "Μενού αρχείου: Αγαπημένο αρχείο"

  "File Menu: Lock file"
  "Μενού αρχείο: Αρχείο κλείδωμα"

  "File Menu: New file"
  "Μενού αρχείο: Νέο αρχείο"

  "File Menu: New file from template"
  "Μενού αρχείο: Νέο αρχείο από πρότυπο"

  "File Menu: New window"
  "Μενού αρχείο: Νέο παράθυρο"

  "File Menu: Open Favorite"
  "Μενού αρχείο: Ανοικτή αγαπημένο"

  "File Menu: Open Recent"
  "Μενού αρχείο: Άνοιγμα πρόσφατες"

  "File Menu: Open directory"
  "Μενού αρχείο: Open directory"

  "File Menu: Open file"
  "Μενού αρχείο: Ανοίξτε το αρχείο"

  "File Menu: Quit application"
  "Μενού αρχείο: Κλείστε την εφαρμογή"

  "File Menu: Rename current file"
  "Μενού αρχείο: Μετονομάστε το τρέχον αρχείο"

  "File Menu: Reopen current file"
  "Μενού αρχείο: Ξανά το τρέχον αρχείο"

  "File Menu: Save all files"
  "Μενού αρχείο: Αποθηκεύσετε όλα τα αρχεία"

  "File Menu: Save file"
  "Μενού αρχείο: Αποθήκευση αρχείου"

  "File Menu: Save file as"
  "Μενού αρχείο: Αποθηκεύστε το αρχείο ως"

  "File Menu: Save file as template"
  "Μενού αρχείο: Αποθήκευση αρχείου ως προτύπου"

  "File Menu: Save selected lines"
  "Μενού αρχείο: Αποθηκεύσετε τις επιλεγμένες γραμμές"

  "File Menu: Set current file line ending to CR for Classic Mac"
  "Μενού \"

  "File Menu: Set current file line ending to CRLF for Windows"
  "Μενού \"

  "File Menu: Set current file line ending to LF for Unix"
  "Μενού \"

  "File Menu: Show file difference"
  "Μενού αρχείο: Εμφάνιση αρχείο διαφορά"

  "File Menu: Unfavorite file"
  "Μενού αρχείο: Αρχείο Unfavorite"

  "File Menu: Unlock file"
  "Μενού αρχείο: Ξεκλειδώσετε αρχείο"

  "Find In Files"
  "?????? ??? ??????"

  "Find Matching Pair"
  "?????? ?????????? ??????"

  "Find Menu: Append next occurrence"
  "Find μενού: Προσάρτηση εµφάνιση"

  "Find Menu: Create marker at current line"
  "Find μενού: Δημιουργία δείκτη στην τρέχουσα γραμμή"

  "Find Menu: Find"
  "Βρείτε το μενού: βρείτε"

  "Find Menu: Find and Replace"
  "Find μενού: Εύρεση και αντικατάσταση"

  "Find Menu: Find in files"
  "Find μενού: Βρείτε στα αρχεία"

  "Find Menu: Find matching character pair"
  "Find μενού: Βρείτε ταιριάζουν ζεύγος χαρακτήρα"

  "Find Menu: Find next occurrence"
  "Find μενού: Βρείτε την επόμενη εμφάνιση"

  "Find Menu: Find previous occurrence"
  "Find μενού: Βρείτε την προηγούμενη εμφάνιση"

  "Find Menu: Goto next difference"
  "Find μενού: Goto επόμενο διαφορά"

  "Find Menu: Goto previous difference"
  "Μενού Εύρεση: Προηγούμενη διαφορά Goto"

  "Find Menu: Jump backward"
  "Find μενού: Άλμα προς τα πίσω"

  "Find Menu: Jump forward"
  "Find μενού: Άλμα προς τα εμπρός"

  "Find Menu: Jump to line"
  "Find μενού: Μεταβείτε σε γραμμής"

  "Find Menu: Remove all markers"
  "Find μενού: Αφαιρέσετε όλα δείκτες"

  "Find Menu: Remove marker from current line"
  "Find μενού: Δείκτη κατάργηση από την τρέχουσα γραμμή"

  "Find Menu: Select all occurrences"
  "Find μενού: Επιλέξτε όλες τις εμφανίσεις"

  "Find Menu: Show selected line change"
  "Find μενού: Αλλαγή γραμμής εμφάνιση επιλεγεί"

  "Find and Replace"
  "Εύρεση και αντικατάσταση"

  "Format Text"
  "Μορφή κειμένου"

  "From Clipboard"
  "Από το πρόχειρο"

  "Goto Last Tab"
  "Μετάβαση Last Tab"

  "Goto Next Tab"
  "Μετάβαση Next Tab"

  "Goto Other Pane"
  "Μετάβαση Άλλα Παράθυρο"

  "Goto Previous Tab"
  "Μετάβαση Προηγούμενη Tab"

  "Help"
  "Βοήθεια"

  "Help Menu: About TKE"
  "Μενού βοήθειας: Για την ΤΚΕ"

  "Help Menu: Check for update"
  "Μενού \"

  "Help Menu: Send bug report"
  "Μενού \"

  "Help Menu: Send feedback"
  "Μενού \"

  "Help Menu: View user guide"
  "Μενού \"

  "Hide Console"
  "Απόκρυψη Console"

  "Hide Line Numbers"
  "Απόκρυψη αριθμών γραμμών"

  "Hide Marker Map"
  "Απόκρυψη δείκτη χάρτη"

  "Hide Meta Characters"
  "???????? ???? ??????????"

  "Hide Sidebar"
  "Απόκρυψη πλευρικής μπάρας"

  "Hide Status Bar"
  "Απόκρυψη Status Bar"

  "Hide Tab Bar"
  "Απόκρυψη Tab Bar"

  "Indent"
  "Εσοχή"

  "Indent Off"
  "Εσοχή από"

  "Indentation"
  "κόλπωση"

  "Insert"
  "Εισαγωγή"

  "Install"
  "Εγκατάσταση"

  "Join Lines"
  "Ενώνουν γραμμές"

  "Jump Backward"
  "???? ???? ?? ????"

  "Jump Forward"
  "???? ???? ?? ??????"

  "Jump To Line"
  "Μεταβείτε σε γραμμής"

  "Launcher"
  "Προωθητής"

  "Line Above Current"
  "Γραμμή πάνω από το ρεύμα"

  "Line Below Current"
  "Γραμμή κάτω από το ρεύμα"

  "Line Ending"
  "Τέλος γραμμής"

  "Line Number"
  "Αριθμός γραμμής"

  "Line Numbering"
  "Αρίθμηση γραμμών"

  "Lock"
  "Κλείδωμα"

  "Lower Case"
  "Πεζά"

  "Markers"
  "Σημεία"

  "Menu Bindings"
  "Δέστρες Μενού"

  "Menus: About TKE"
  "Μενού: Σχετικά με την ΤΚΕ"

  "Merge Panes"
  "?????????? ???????? ?????????"

  "Move Cursors Down"
  "Δρομείς κίνηση προς τα κάτω"

  "Move Cursors Left"
  "Μετακίνηση αριστερά κατά δρομείς"

  "Move Cursors Right"
  "Μετακίνηση δεξιά δρομείς"

  "Move Cursors Up"
  "Ανεβάσουμε δρομείς"

  "Move to First Line"
  "Μετακίνηση στην πρώτη γραμμή"

  "Move to Last Line"
  "Μετάβαση στο τελευταίο γραμμή"

  "Move to Line End"
  "Μετακίνηση σε γραμμή τέλος"

  "Move to Line Start"
  "Κινηθεί για την γραμμή εκκίνησης"

  "Move to Next Page"
  "Μετακίνηση στην επόμενη σελίδα"

  "Move to Next Word"
  "Μετακίνηση στην επόμενη λέξη"

  "Move to Previous Page"
  "Μετακίνηση στην προηγούμενη σελίδα"

  "Move to Previous Word"
  "Μετακίνηση στην προηγούμενη λέξη"

  "Move to Screen Bottom"
  "Προχωρήσουμε στην οθόνη κάτω"

  "Move to Screen Middle"
  "Προχωρήσουμε στην οθόνη μέση"

  "Move to Screen Top"
  "Προχωρήσουμε στην οθόνη κορυφή"

  "New From Template"
  "Νέα από το πρότυπο"

  "New Window"
  "Νέο παράθυρο"

  "Next Difference"
  "??????? ???????"

  "Open Directory"
  "Open Directory"

  "Open Favorite"
  "Open Αγαπημένα"

  "Open File"
  "Άνοιγμα αρχείου"

  "Open Recent"
  "Άνοιγμα πρόσφατου"

  "Paste"
  "Επικόλληση"

  "Paste and Format"
  "Επικόλληση και Format"

  "Plugins"
  "Plug-in"

  "Plugins Menu: Create new plugin"
  "Plugins μενού: Δημιουργήστε νέο plugin"

  "Plugins Menu: Install plugin"
  "Μενού plugins: Εγκατάσταση plugin"

  "Plugins Menu: Reload all plugins"
  "Plugins μενού: Φορτώσετε εκ νέου όλα τα plugins"

  "Plugins Menu: Uninstall plugin"
  "Plugins μενού: Απεγκατάσταση plugin"

  "Preferences"
  "Προτιμήσεις"

  "Previous Difference"
  "??????????? ???????"

  "Profiling Report Sorted By"
  "Σκιαγράφηση έκθεση ταξινομημένες κατά"

  "Profiling started"
  "Profiling ξεκίνησε"

  "Profiling stopped"
  "Profiling σταματήσει"

  "Quit"
  "έξοδος"

  "Redo"
  "Επανάληψη"

  "Relative"
  "Σχετική"

  "Reload"
  "Επαναφόρτωση"

  "Remove All Markers"
  "????????? ??? ???????"

  "Remove From Current Line"
  "????????? ??? ??? ???????? ??????"

  "Reopen File"
  "Ξανά αρχείο"

  "Replace Line With Script"
  "?????????????? ??? ?????? ?? ???????"

  "Reset User to Base"
  "Ξαναρυθμίζω χρήστη στη βάση"

  "Restart TKE"
  "???????????? ???"

  "Run BIST"
  "Εκτελέστε BIST"

  "Save All"
  "Αποθήκευση όλων"

  "Save As Template"
  "Αποθήκευση Προτύπου"

  "Save Current"
  "???????????? ?? ?????"

  "Save Selection As"
  "Αποθήκευση επιλογής ως"

  "Select All"
  "Επιλογή όλων"

  "Select All Occurrences"
  "???????? ???? ??? ??????????"

  "Select Next Occurrence"
  "???????? ?µ??????"

  "Select Previous Occurrence"
  "???????? ??? ??????????? ????????"

  "Send Bug Report"
  "Στείλτε την αναφορά σφαλμάτων"

  "Send Feedback"
  "Αποστολή Σχολίων"

  "Sessions"
  "?????????"

  "Sessions Menu: Close current session"
  "Συνεδρίες μενού: Κλείσετε την τρέχουσα περίοδο λειτουργίας"

  "Sessions Menu: Delete session"
  "Συνεδρίες μενού: Συνεδρία διαγραφή"

  "Sessions Menu: Save current session"
  "Συνεδρίες μενού: Αποθηκεύσετε την τρέχουσα περίοδο λειτουργίας"

  "Sessions Menu: Save sessions as"
  "Συνεδρίες μενού: Σώσει συνεδρίες ως"

  "Sessions Menu: Switch to session"
  "Συνεδρίες μενού: Μετάβαση σε συνεδρία"

  "Set Syntax"
  "Ορισμός Σύνταξη"

  "Set Theme"
  "Ορισμός Θέμα"

  "Set User to Global"
  "Χρήστη που ορίζεται στην παγκόσμια"

  "Show Console"
  "Εμφάνιση Console"

  "Show Diagnostic Logfile"
  "Εμφάνιση διαγνωστικό Logfile"

  "Show File Difference"
  "Εμφάνιση αρχείου διαφορά"

  "Show Last Profiling Report"
  "Εμφάνιση Τελευταία Έκθεση Profiling"

  "Show Line Numbers"
  "Εμφάνιση αριθμών γραμμών"

  "Show Marker Map"
  "Δείκτη Εμφάνιση χάρτη"

  "Show Meta Characters"
  "???? ?????????? ????????"

  "Show Selected Line Change"
  "???????????? ?????????? ?????? ??????"

  "Show Sidebar"
  "Εμφάνιση πλευρικής μπάρας"

  "Show Status Bar"
  "Γραμμή κατάστασης"

  "Show Tab Bar"
  "Γραμμή καρτελών"

  "Smart Indent"
  "Έξυπνες περίπτωση"

  "Snippet"
  "Απόσπασμα"

  "Snippets"
  "Αποσπάσματα"

  "Sort Tabs"
  "Sort Tabs"

  "Start Profiling"
  "Ξεκινήστε Profiling"

  "Stop Profiling"
  "Σταματήστε Profiling"

  "Switch To"
  "????????? ??"

  "Tabs"
  "Δισκία"

  "Templates"
  "Πρότυπα"

  "Text Between Character"
  "Κείμενο μεταξύ χαρακτήρα"

  "Text Menu: Insert enumeration"
  "Κείμενο μενού: Εισαγωγή καταμέτρηση"

  "Title Case"
  "Υπόθεση τίτλος"

  "Toggle Case"
  "ΕΝΑΛΛΑΓΗ πεζών-ΚΕΦΑΛΑΙΩΝ"

  "Toggle Comment"
  "???????? ??????"

  "Tools"
  "Μέσα δράσης"

  "Tools Menu: Disable Vim mode"
  "Μενού Εργαλεία: Απενεργοποίηση λειτουργίας Vim"

  "Tools Menu: Enable Vim mode"
  "Εργαλεία μενού: Ενεργοποίηση της λειτουργίας Vim"

  "Tools Menu: Restart TKE"
  "Μενού Εργαλεία: Επανεκκίνηση ΤΚΕ"

  "Tools Menu: Run BIST"
  "Μενού Εργαλεία: Τρέχει BIST"

  "Tools Menu: Run theme editor"
  "Εργαλεία Μενού: Εκτέλεση editor θέμα"

  "Tools Menu: Show diagnostic logfile"
  "Μενού Εργαλεία: Διαγνωστικά logfile Εμφάνιση"

  "Tools Menu: Show last profiling report"
  "Μενού Εργαλεία: Εμφάνιση τελευταία έκθεση προφίλ"

  "Tools Menu: Start profiling"
  "Μενού Εργαλεία: Έναρξη δημιουργίας προφίλ"

  "Tools Menu: Stop profiling"
  "Μενού Εργαλεία: Σταματήσει προφίλ"

  "Transform"
  "Μετασχηματισμός"

  "Undo"
  "Αναίρεση"

  "Unindent"
  "Κατάργηση εσοχής"

  "Uninstall"
  "Απεγκατάσταση"

  "Unix"
  "Unix"

  "Unlock"
  "Ξεκλείδωμα"

  "Upper Case"
  "Γραφή με κεφαλαία γράμματα"

  "User Guide"
  "Οδηγός χρήστη"

  "View"
  "Προβολή"

  "View Base"
  "Προβολή βάσης"

  "View Global"
  "Παγκόσμια προβολή"

  "View Menu: Absolute line numbering"
  "Μενού Προβολή: Αρίθμηση απόλυτη γραμμή"

  "View Menu: Display text information"
  "Μενού \"

  "View Menu: Goto last tab"
  "Μενού Προβολή: Goto τελευταία καρτέλα"

  "View Menu: Goto next tab"
  "Μενού Προβολή: Επόμενη καρτέλα Goto"

  "View Menu: Goto other pane"
  "Μενού Προβολή: Goto άλλο παράθυρο"

  "View Menu: Goto previous tab"
  "Μενού Προβολή: Προηγούμενη καρτέλα Goto"

  "View Menu: Hide console"
  "Μενού \"

  "View Menu: Hide line numbers"
  "Μενού \"

  "View Menu: Hide marker map"
  "Μενού \"

  "View Menu: Hide meta characters"
  "Μενού \"

  "View Menu: Hide sidebar"
  "Μενού \"

  "View Menu: Hide status bar"
  "Μενού \"

  "View Menu: Hide tab bar"
  "Μενού \"

  "View Menu: Merge panes"
  "Μενού \"

  "View Menu: Move to other pane"
  "Μενού \"

  "View Menu: Relative line numbering"
  "Μενού Προβολή: Αρίθμηση σχετική γραμμή"

  "View Menu: Show console"
  "Μενού \"

  "View Menu: Show line numbers"
  "Μενού \"

  "View Menu: Show marker map"
  "Μενού \"

  "View Menu: Show meta characters"
  "Μενού \"

  "View Menu: Show sidebar"
  "Μενού \"

  "View Menu: Show status bar"
  "Μενού \"

  "View Menu: Show tab bar"
  "Μενού \"

  "View Menu: Sort tabs"
  "Μενού \"

  "View Menu: Toggle split view mode"
  "Μενού \"

  "Vim Mode"
  "Λειτουργία Vim"

  "Whitespace Backward"
  "Whitespace προς τα πίσω"

  "Whitespace Forward"
  "Whitespace προς τα εμπρός"

  "Windows"
  "Παράθυρα"

}

# plugins.tcl
msgcat::mcmset el {

  "Always grant from developer"
  "Πάντα χορηγεί από τον προγραμματιστή"

  "ERROR"
  "Σφάλμα"

  "ERROR:  Plugin name already exists"
  "ΣΦΑΛΜΑ: Plugin όνομα υπάρχει ήδη"

  "ERROR:  Plugin name is not valid (only alphanumeric and underscores are allowed)"
  "ΣΦΑΛΜΑ: Plugin όνομα δεν είναι έγκυρο (μόνο αλφαριθμητικά και οι κάτω παύλες)"

  "ERROR:  Unable to create plugin directory"
  "ΣΦΑΛΜΑ: Δεν είναι δυνατή η δημιουργία του καταλόγου plugin"

  "ERROR:  Unable to write plugin files"
  "ΣΦΑΛΜΑ: Δεν είναι για να γράψει plugin αρχεία"

  "Enter plugin name"
  "Πληκτρολογήστε το όνομα του plugin"

  "Grant"
  "Χορήγηση"

  "Grant permssion?"
  "Επιχορήγηση permssion;"

  "OK"
  "ΟΚ"

  "Plugin Errors"
  "Plugin Λάθη"

  "Plugin Trust Requested"
  "Plugin Εμπιστοσύνη Αιτήματα"

  "Plugin installed"
  "Plugin εγκατεστημένο"

  "Plugin requires permission to view or modify your system."
  "Plugin απαιτείται άδεια για να προβάλετε ή να τροποποιήσετε το σύστημά σας."

  "Plugin uninstalled"
  "Απεγκατασταθεί το plugin"

  "Plugins successfully reloaded"
  "Plugins reloaded με επιτυχία"

  "Reject"
  "απορρίψετε"

  "Syntax errors found in selected plugins"
  "Συντακτικά λάθη τα βρείτε σε επιλεγμένα plugins"

}

# search.tcl
msgcat::mcmset el {

  "No files found in specified directories"
  "Δεν βρέθηκαν σε καθορισμένους καταλόγους αρχεία"

  "No search results found"
  "Δε βρέθηκαν αποτελέσματα αναζήτησης"

  "Search wrapped to beginning of file"
  "Αναζήτηση τυλιγμένο στην αρχή του αρχείου"

  "Search wrapped to end of file"
  "Αναζήτηση τυλιγμένο στο τέλος του αρχείου"

  "substitutions done"
  "αντικαταστάσεις γίνει"

}

# sessions.tcl
msgcat::mcmset el {

  "Save session?"
  "Αποθήκευση Αντιπαραβολής"

  "Session state will be lost if not saved"
  "Κατάσταση περιόδου θα χαθούν αν δεν αποθηκεύονται"

}

# sidebar.tcl
msgcat::mcmset el {

  "Add Parent Directory"
  "Μητρικός Κατάλογος"

  "Close Directory Files"
  "Κλείσιμο Κατάλογος αρχείων"

  "Copy Pathname"
  "?????????? ?? ????? ?????????"

  "Delete directories?"
  "Διαγραφή καταλόγους;"

  "Delete directory?"
  "Διαγραφή κατάλογο;"

  "Delete file?"
  "Διαγραφή αρχείου"

  "Delete files?"
  "Διαγραφή αρχείων;"

  "Directory Name:"
  "Όνομα καταλόγου:"

  "Folder Name:"
  "????? ???????:"

  "Image displayed in sidebar to indicate that a file is currently opened in an editing buffer."
  "Εικόνα που εμφανίζεται στην πλαϊνή γραμμή για να δείξει ότι ένα αρχείο που έχετε ανοίξει σε ένα ρυθμιστικό μοντάζ."

  "Make Current Working Directory"
  "Κάντε τρέχων κατάλογος εργασίας"

  "New Directory"
  "Νέα Directory"

  "Open Directory Files"
  "Αρχεία Open Directory"

  "Refresh Directory Files"
  "Ανανέωση Κατάλογος αρχείων"

  "Remove Parent from Sidebar"
  "Κατάργηση της Μητρικής από το Sidebar"

  "Remove from Sidebar"
  "Αφαιρέστε από το Sidebar"

  "Show Difference"
  "Εμφάνιση διαφορά"

}

# snippets.tcl
msgcat::mcmset el {

  "Snippet: *"
  "Απόσπασμα: *"

}

# syntax.tcl
msgcat::mcmset el {

  "Syntax"
  "Σύνταξη"

  "Syntax error in syntax file"
  "Συντακτικό σφάλμα στο αρχείο σύνταξη"

}

# templates.tcl
msgcat::mcmset el {

  "Template"
  "Πρότυπο"

  "Template Name"
  "Όνομα πρότυπου"

  "deleted"
  "διαγράφηκε"

  "saved"
  "Αποθηκεύτηκε!"

}

# theme.tcl
msgcat::mcmset el {

  "Background (trough) color used in the sidebar scrollbar."
  "Ιστορικό (trough) χρωμάτων που χρησιμοποιείται στην πλαϊνή μπάρα κύλισης."

  "Background (trough) color used in the text scrollbars."
  "Ιστορικό (trough) χρώμα που χρησιμοποιείται στο κείμενο κύλισης."

  "Background color for all sidebar items that are not selected."
  "Χρώμα φόντου για όλα τα στοιχεία sidebar που δεν έχουν επιλεγεί."

  "Background color for all sidebar items that are selected."
  "Χρώμα φόντου για όλα τα στοιχεία sidebar που έχουν επιλεγεί."

  "Background color in difference viewer that shows added lines."
  "Χρώμα φόντου στη διαφορά θεατή που δείχνει πρόσθεσε γραμμές."

  "Background color in difference viewer that shows deleted lines."
  "Χρώμα φόντου στη διαφορά θεατή που δείχνει τα διαγραμμένα γραμμές."

  "Background color of insertion cursor and background marker colors."
  "Χρώμα φόντου του δείκτη και του δείκτη εισαγωγής χρώματα φόντου."

  "Background color of the editing buffer."
  "Χρώμα φόντου του ρυθμιστικού μοντάζ."

  "Background color to display when a button-like ttk widget is pressed."
  "Χρώμα φόντου στην οθόνη όταν ένα κουμπί, όπως το widget TTK πιέζεται."

  "Background color to use for selected text."
  "Χρώμα φόντου που θα χρησιμοποιηθεί για το επιλεγμένο κείμενο."

  "Background color used for all other tabs that are not the current/active tab in the tabbar."
  "Χρώμα φόντου που χρησιμοποιείται για όλες τις άλλες καρτέλες που δεν είναι η τρέχουσα / ενεργή καρτέλα στο tabbar."

  "Background color used for the current/active menu item."
  "Χρώμα φόντου που χρησιμοποιείται για την τρέχουσα / ενεργό στοιχείο του μενού."

  "Background color used for the current/active tab in the tabbar."
  "Χρώμα φόντου που χρησιμοποιείται για την τρέχουσα / ενεργή καρτέλα στο tabbar."

  "Background color used in highlighted text."
  "Χρώμα φόντου που χρησιμοποιείται στο επισημασμένο κείμενο."

  "Background color used in menus."
  "Χρώμα φόντου που χρησιμοποιείται στα μενού."

  "Background color used in the tabbar area."
  "Χρώμα φόντου που χρησιμοποιείται στην περιοχή tabbar."

  "Color of border drawn around active editing buffer."
  "Χρώμα των συνοριακών που γύρω ενεργό ρυθμιστικό μοντάζ."

  "Color of ttk entry widget text border when the entry has keyboard focus."
  "Χρώμα εισόδου TTK συνόρων κειμένου του widget όταν η είσοδος έχει εστίαση πληκτρολογίου."

  "Color used to draw the warning width line in the editing buffer (as well as the line separating the gutter from the editing buffer)."
  "Χρώμα που χρησιμοποιείται για να επιστήσει την γραμμή πλάτους προειδοποίηση στο ρυθμιστικό μοντάζ (καθώς και η γραμμή που χωρίζει την υδρορροή από το ρυθμιστικό μοντάζ)."

  "Default 'darkcolor' for all ttk widgets."
  "Προεπιλογή «darkcolor» για όλες τις TTK widgets."

  "Default background color to use for all ttk widgets that are in a disabled state."
  "Προεπιλεγμένο χρώμα φόντου για να χρησιμοποιήσετε για όλες τις TTK widgets που βρίσκονται σε κατάσταση απενεργοποίησης."

  "Default background color to use for all ttk widgets when the mouse cursor hovers over the widget."
  "Προεπιλεγμένο χρώμα φόντου για να χρησιμοποιήσετε για όλες τις TTK widgets όταν ο κέρσορας του ποντικιού περάσει πάνω από το widget."

  "Default background color to use for all ttk widgets."
  "Προεπιλεγμένο χρώμα φόντου για να χρησιμοποιήσετε για όλες τις TTK widgets."

  "Default border color for all ttk widgets."
  "Προεπιλεγμένο χρώμα των συνόρων για όλους τους TTK widgets."

  "Default color for non-syntax highlighted text."
  "Προκαθορισμένο χρώμα για τη μη σύνταξη επισημασμένο κείμενο."

  "Default foreground text color to use for all ttk widgets that are in a disabled state."
  "Προεπιλογή χρώμα κειμένου στο προσκήνιο στη χρήση για όλους TTK widgets που βρίσκονται σε κατάσταση απενεργοποίησης."

  "Default foreground text color to use for all ttk widgets."
  "Προεπιλογή χρώμα κειμένου στο προσκήνιο στη χρήση για όλους TTK widgets."

  "Determines the number of grips strips to display in the grip area between resizable panes."
  "Καθορίζει τον αριθμό των λωρίδων λαβές για να εμφανιστεί στην περιοχή λαβής αλλαγής μεγέθους μεταξύ των υαλοπινάκων."

  "Determines the thickness of the grip area between resizable panes."
  "Καθορίζει το πάχος της ζώνης λαβή αλλαγής μεγέθους μεταξύ των υαλοπινάκων."

  "ERROR:  Unable to read"
  "ΣΦΆΛΜΑ: Δεν είναι δυνατή η ανάγνωση"

  "Foreground (slider) color used in the sidebar scrollbar."
  "Προσκήνιο (slider) χρωμάτων που χρησιμοποιείται στην πλαϊνή μπάρα κύλισης."

  "Foreground (slider) color used in the text scrollbars."
  "Προσκήνιο (slider) χρώμα που χρησιμοποιείται στο κείμενο κύλισης."

  "Foreground color used in menu items with checks or buttons."
  "Χρώμα προσκηνίου που χρησιμοποιείται σε αντικείμενα μενού με ελέγχους ή κουμπιά."

  "Foreground text color for strings."
  "Χρώμα κειμένου στο προσκήνιο για έγχορδα."

  "Foreground text color to use for all miscellaneous1 labeled text."
  "Χρώμα κειμένου στο προσκήνιο να χρησιμοποιήσετε για όλα τα miscellaneous1 επισημασμένο κείμενο."

  "Foreground text color to use for all miscellaneous2 labeled text."
  "Χρώμα κειμένου στο προσκήνιο να χρησιμοποιήσετε για όλα τα miscellaneous2 επισημασμένο κείμενο."

  "Foreground text color to use for all miscellaneous3 labeled text."
  "Χρώμα κειμένου στο προσκήνιο να χρησιμοποιήσετε για όλα τα miscellaneous3 επισημασμένο κείμενο."

  "Foreground text color to use for comments."
  "Χρώμα κειμένου στο προσκήνιο να χρησιμοποιήσετε για σχόλια."

  "Foreground text color to use for displaying line numbers."
  "Χρώμα κειμένου στο προσκήνιο να χρησιμοποιήσετε για την προβολή τους αριθμούς γραμμών."

  "Foreground text color to use for displaying numbers."
  "Χρώμα κειμένου στο προσκήνιο για να χρησιμοποιήσει για την εμφάνιση αριθμών."

  "Foreground text color to use for language-specific keywords."
  "Χρώμα κειμένου στο προσκήνιο να χρησιμοποιούν για τη γλώσσα-συγκεκριμένες λέξεις-κλειδιά."

  "Foreground text color to use for language-specific punctuation."
  "Χρώμα κειμένου στο προσκήνιο να χρησιμοποιήσετε για συγκεκριμένη γλώσσα στίξης."

  "Foreground text color to use for meta syntax."
  "Χρώμα κειμένου στο προσκήνιο να χρησιμοποιήσετε για μετα σύνταξη."

  "Foreground text color to use for precompiler syntax."
  "Χρώμα κειμένου στο προσκήνιο να χρησιμοποιήσετε για precompiler σύνταξη."

  "Foreground text color to use for selected text."
  "Χρώμα κειμένου στο προσκήνιο για να χρησιμοποιήσετε για το επιλεγμένο κείμενο."

  "Foreground text color used for all other tabs that are not the current/active tab in the tabbar."
  "Χρώμα προσκηνίου κείμενο χρησιμοποιείται για όλες τις άλλες καρτέλες που δεν είναι καρτέλα ρεύμα/ενεργό στην το tabbar."

  "Foreground text color used for menus item that are disabled."
  "Χρώμα προσκηνίου κείμενο που χρησιμοποιείται για τα μενού στοιχείο που είναι άτομα με ειδικές ανάγκες."

  "Foreground text color used for the current/active menu item."
  "Χρώμα προσκηνίου κείμενο που χρησιμοποιείται για την τρέχουσα / ενεργό στοιχείο του μενού."

  "Foreground text color used for the current/active tab in the tabbar."
  "Χρησιμοποιείται για το ρεύμα/ενεργή καρτέλα tabbar το χρώμα κειμένου προσκηνίου."

  "Foreground text color used in menus."
  "Χρώμα κειμένου στο προσκήνιο χρησιμοποιείται στα μενού."

  "Foreground text/image color used in tabbar and tabs."
  "Χρώμα κειμένου στο προσκήνιο / εικόνας που χρησιμοποιείται σε tabbar και τις καρτέλες."

  "Images"
  "Εικόνες"

  "Maximum thickness of the text scrollbar when it is active."
  "Μέγιστο πάχος της γραμμής κύλισης κειμένου όταν είναι ενεργός."

  "Maximum thickness of the text scrollbars when they are active."
  "Μέγιστο πάχος των γραμμών κύλισης κειμένου όταν είναι ενεργό."

  "Menu Options"
  "Επιλογές Μενού"

  "Menu relief value."
  "Μενού αξία ανακούφιση."

  "Pixel height of the tabbar widget."
  "Pixel ύψος του widget tabbar."

  "Relief used in drawing the tabs."
  "Ανακούφιση που χρησιμοποιούνται για την κατάρτιση των καρτελών."

  "Relief value of the sidebar area."
  "Αξία ανάγλυφο της περιοχής sidebar."

  "Sidebar Options"
  "Sidebar Επιλογές"

  "Sidebar Scrollbar Options"
  "Sidebar Επιλογές κύλισης"

  "Specifies the color to display around the sidebar when the sidebar does not have the focus."
  "Καθορίζει το χρώμα για να εμφανιστεί γύρω από την πλαϊνή μπάρα, όταν η πλαϊνή γραμμή δεν έχει την εστίαση."

  "Specifies the color to display around the sidebar when the sidebar has the focus."
  "Καθορίζει το χρώμα για να εμφανιστεί γύρω από την πλαϊνή μπάρα, όταν η πλευρική γραμμή έχει την εστίαση."

  "Specifies the default background color to use for text that is selected in a standard ttk widget (this does not include the editing buffer)."
  "Καθορίζει το προεπιλεγμένο χρώμα φόντου που θα χρησιμοποιηθεί για το κείμενο που έχει επιλεγεί σε ένα πρότυπο widget TTK (αυτό δεν περιλαμβάνει το ρυθμιστικό μοντάζ)."

  "Specifies the default foreground text color to use for text that is selected in a standard ttk widget (this does not include the editing buffer)."
  "Καθορίζει το προεπιλεγμένο χρώμα του κειμένου προσκηνίου να χρησιμοποιηθεί για το κείμενο που έχει επιλεγεί σε ένα πρότυπο widget TTK (αυτό δεν περιλαμβάνει το ρυθμιστικό μοντάζ)."

  "Specifies the default relief to use when drawing ttk widgets."
  "Καθορίζει την προεπιλεγμένη ανακούφιση που θα χρησιμοποιηθεί κατά την κατάρτιση TTK widgets."

  "Specifies the disclosure image style to use in the sidebar."
  "Καθορίζει το στυλ εικόνα δημοσιοποίησης, να χρησιμοποιούν στην πλαϊνή γραμμή."

  "Specifies the pixel thickness of the highlight line."
  "Καθορίζει το πάχος pixel της γραμμής αποκορύφωμα."

  "Syntax Colors"
  "Σύνταξη Χρώματα"

  "Tab Options"
  "Καρτέλα Επιλογές"

  "Text Scrollbar Options"
  "Κείμενο Επιλογές κύλισης"

  "Text color for all sidebar items that are not selected."
  "Χρώμα κειμένου για όλα τα στοιχεία sidebar που δεν έχουν επιλεγεί."

  "Text color for all sidebar items that are selected."
  "Χρώμα κειμένου για όλα τα στοιχεία sidebar που έχουν επιλεγεί."

  "ttk Widget Colors"
  "TTK Widget Χρώματα"

}

# themer.tcl
msgcat::mcmset el {

  "   Show All"
  "E"

  "   Show Category"
  "Εμφάνιση Κατηγορίας"

  "   Show Color"
  "Εμφάνιση Χρώματος Φόντου"

  "   Show Selected Option"
  "Εμφάνιση επιλεγμένων Επιλογή"

  "   Show Selected Value"
  "Εμφάνιση επιλεγμένη τιμή"

  "Categories"
  "Κατηγορίες"

  "Change Base Color"
  "Αλλαγή χρώματος βάσης"

  "Choose Theme"
  "Επιλέξτε θέμα εμφάνισης"

  "Custom Directory"
  "Προσαρμοσμένο Κατάλογο"

  "Custom..."
  "Προσαρμοσμένο"

  "Delete swatch?"
  "Διαγραφή Swatch;"

  "Description"
  "Περιγραφή"

  "Details"
  "Λεπτομέρειες"

  "Done"
  "Ολοκληρώθηκε"

  "Export"
  "Εξαγωγή"

  "GIF Photo"
  "GIF Φωτογραφία"

  "Import"
  "Εισαγωγή"

  "Import BMP Data"
  "Εισαγωγή BMP Δεδομένων"

  "Import BMP Mask"
  "Εισαγωγή BMP Μάσκα"

  "Import Error"
  "Σφάλμα εισαγωγής"

  "Import Theme File"
  "Εισαγωγή Θέμα αρχείου"

  "Installation Directory"
  "Κατάλογος εγκατάστασης"

  "Modifications"
  "Τροποποιήσεις"

  "One-Color Bitmap"
  "Ένα-Color Bitmap"

  "Preview"
  "Προεπισκόπιση"

  "Relief: "
  "συναισθηματικη εκτονωση"

  "Save As:"
  "Αποθήκευση ως:"

  "Save theme changes?"
  "Αποθηκεύστε τις αλλαγές θέμα;"

  "Select Directory"
  "Επιλογή καταλόγου"

  "Swatch"
  "Δείγμα υφάσματος"

  "Swatch Colors"
  "Swatch Χρώματα"

  "Table Filters"
  "Φίλτρα Πίνακας"

  "The current theme has unsaved changes"
  "Το σημερινό θέμα έχει μη αποθηκευμένες αλλαγές"

  "Tree Style: "
  "Δέντρο Στυλ:"

  "Two-Color Bitmap"
  "Δύο-χρώμα Bitmap"

  "User Directory"
  "Χρήστης Κατάλογος"

  "Value"
  "Τιμή"

  "Value: "
  "Τιμή:"

}

# themes.tcl
msgcat::mcmset el {

  "Theme"
  "Θέμα"

  "Theme:*"
  "Θέμα"

}

# tke.tcl
msgcat::mcmset el {

  "Import TKE theme?"
  "Θέμα Εισαγωγή ΤΚΕ;"

  "Import TextMate theme?"
  "Εισαγωγή TextMate θέμα;"

}

# tkedat.tcl
msgcat::mcmset el {

  "Unable to read"
  "Δεν είναι δυνατή η ανάγνωση"

}

# vim.tcl
msgcat::mcmset el {

  "File format unrecognized"
  "Μη αναγνωρίσιμη μορφή αρχείου"

  "Filename directory does not exist"
  "Δεν υπάρχει κατάλογος όνομα_αρχείου"

  "Illegal modelines value"
  "Παράνομη modelines αξία"

  "Shiftwidth value is not an integer"
  "Shiftwidth τιμή δεν είναι ακέραιος"

  "Tabstop value is not an integer"
  "TabStop τιμή δεν είναι ακέραιος"

}

# General
msgcat::mcmset el {

  "Cancel"
  "Ακύρωση"

  "Close"
  "Κλείσιμο"

  "Delete"
  "Διαγραφή"

  "Duplicate"
  "Αναπαραγωγή"

  "Favorite"
  "Αγαπημένο"

  "File Name:"
  "Όνομα αρχείου:"

  "Find"
  "Find"

  "Move to Other Pane"
  "Μετακίνηση σε άλλες Παράθυρο"

  "New File"
  "Νέο αρχείο"

  "None"
  "Κανένα"

  "Open"
  "Ανοιχτό"

  "Rename"
  "Μετονομασία"

  "Save"
  "Αποθήκευση"

  "Save As"
  "Αποθήκευση ως"

  "Split View"
  "?????????? ???????"

  "Theme Editor"
  "Θέμα Εκδότης"

  "Unable to write"
  "Αδύνατη η εγγραφή"

  "Unfavorite"
  "Μη αγαπημένα"

}

