# api.tcl
msgcat::mcmset es {

  "Argument list to api::add_file was not an even key/value pair"
  "Lista de argumentos para api::add_file no era un par aun clave/valor"

}

# bgproc.tcl
msgcat::mcmset es {

  "Unable to run system command (%s)"
  "No se puede ejecutar comandos del sistema (%s)"

}

# diff.tcl
msgcat::mcmset es {

  "    End: "
  "Remata:"

  "    Start: "
  "Comienzo:"

  "Enter difference command"
  "Introduzca el comando diferencia"

  "Enter starting file"
  "Entrar a partir del archivo"

  "Update"
  "Actualizar"

}

# gui.tcl
msgcat::mcmset es {

  "%d substitutions done"
  "sustituciones %d hechos"

  "%s, Line: %d, Column: %d"
  "% S, línea:% d, columna% d"

  "Close All Tabs"
  "¿Cerramos todas las pestañas?"

  "Close Other Tab(s)"
  "Cerrar Other Tab(s)"

  "Close Other*"
  "Cerrar Other*"

  "Close Tab"
  "Close Tab"

  "Copyright %d-%d"
  "Derechos Reservados% d-% d"

  "Delete tab?"
  "Eliminar ficha?"

  "Developer:"
  "Desarrollador:"

  "Email:"
  "Correo electrónico:"

  "Error"
  "Error"

  "Favorited"
  "Los favoritos"

  "File attribute (%s) does not exist"
  "Atributo de archivo (%s) no existe"

  "File index is out of range"
  "Índice del archivo está fuera de rango"

  "License:"
  "Licencia:"

  "Line: %d, Column: %d"
  "Line: %d, Columna: %d"

  "Locked"
  "Bloqueado"

  "Move*"
  "Mover*"

  "Must be in multicursor mode to insert numbers"
  "Debe estar en modo multicursor para insertar números"

  "No search results found"
  "No se encontraron resultados búsqueda"

  "Release Type:"
  "Tipo de liberación:"

  "Reload file?"
  "Recargar archivo"

  "Save request"
  "Memorizar encargo"

  "Search wrapped to beginning of file"
  "Búsqueda envuelto al principio del archivo"

  "Search wrapped to end of file"
  "Búsqueda envuelto al final del archivo"

  "Show in Sidebar"
  "Mostrar en Sidebar"

  "Starting number:"
  "Número inicial:"

  "Tcl/Tk Version:"
  "Versión de Tcl/Tk:"

  "Total Lines: %d, Total Characters: %d"
  "Líneas totales:% d, Personajes totales:% d"

  "Twitter:"
  "Twitter:"

  "Unable to find current file (tab: %s)"
  "No se puede encontrar el archivo actual (pestaña:% s)"

  "Unable to successfully parse number string"
  "No se puede analizar correctamente la cadena número"

  "Unable to write file"
  "No se puede escribir el archivo"

  "Untitled"
  "Intitulado"

  "Version:"
  "Versión:"

}

# markers.tcl
msgcat::mcmset es {

  "Marker name:"
  "Nombre del marcador:"

}

# menus.tcl
msgcat::mcmset es {

  "                                  Profiling Report Sorted By (%s)"
  "                                    Informe Perfiles Site (%s)"

  "About TKE"
  "Acerca de TKE"

  "Align Cursors"
  "Alinee los cursores"

  "All"
  "Todo"

  "Append Next Occurrence"
  "Anexar la siguiente ocurrencia"

  "Auto-Indent"
  "Sangrado automático"

  "Check for Update"
  "Buscar actualización"

  "Clear All"
  "Limpiar todo"

  "Close All"
  "Cerrar todo"

  "Close Current"
  "Cerrar vista actual"

  "Copy"
  "Copia"

  "Create New..."
  "Crear nuevo"

  "Create at Current Line"
  "Crear en línea actual"

  "Create..."
  "Crear..."

  "Cut"
  "Cortar"

  "Edit"
  "Edición"

  "Edit Language"
  "Editar Idioma"

  "Edit Session - Global"
  "Editar período de sesiones - Global"

  "Edit Session - Language"
  "Editar período de sesiones - lengua"

  "Edit User"
  "Editar usuario"

  "Edit User - Global"
  "Editar usuario - Global"

  "Edit User - Language"
  "Editar usuario - lengua"

  "Edit..."
  "Edición..."

  "File"
  "Expediente"

  "Find"
  "Búsqueda"

  "Find In Files"
  "Buscar en los Archivos..."

  "Find Matching Pair"
  "Encontrar pareja"

  "Find and Replace"
  "Buscar y reemplazar"

  "Format Text"
  "Formato de texto"

  "From Clipboard"
  "Desde el portapapeles"

  "Goto Last Tab"
  "Goto Última Tab"

  "Goto Next Tab"
  "Ir a la siguiente pestaña"

  "Goto Other Pane"
  "Goto Otro panel"

  "Goto Previous Tab"
  "Ir a la pestaña anterior"

  "Help"
  "Help!"

  "Hide Console"
  "Hide Console"

  "Hide Line Numbers"
  "Ocultar los números de línea"

  "Hide Meta Characters"
  "Ocultar caracteres Meta"

  "Hide Sidebar"
  "Ocultar barra lateral"

  "Hide Status Bar"
  "Barra de estado"

  "Hide Tab Bar"
  "Hide Tab Bar"

  "Import TextMate Theme..."
  "Importación TextMate Theme..."

  "Indent"
  "Indentar"

  "Indent Mode"
  "Modo de guión"

  "Indent Off"
  "Guión de"

  "Insert Enumeration"
  "Insertar (enumeración)"

  "Insert Text"
  "Insertar texto"

  "Install..."
  "Instalar..."

  "Jump Backward"
  "Salto hacia atrás"

  "Jump Forward"
  "Saltar hacia adelante"

  "Launcher"
  "Lanzador"

  "Lock"
  "Bloquear"

  "Markers"
  "Marcadores"

  "Menu Bindings"
  "Vinculaciones Menú"

  "Menu Edit user snippets"
  "Fragmentos de menú Editar usuario"

  "Menu: About TKE"
  "Menú: Acerca de TKE"

  "Menu: Align cursors"
  "Menú: Alinear cursores"

  "Menu: Append next occurrence"
  "Menú: Anexar siguiente aparición"

  "Menu: Check for Update"
  "Buscar actualización"

  "Menu: Close all tabs"
  "¿Cerramos todas las pestañas?"

  "Menu: Close current session"
  "Menú: Cerrar sesión actual"

  "Menu: Close current tab"
  "Menú: Cerrar pestaña actual"

  "Menu: Copy text"
  "Menú: Texto copia"

  "Menu: Create marker at current line"
  "Menú: Crear marcador en línea actual"

  "Menu: Create new plugin"
  "Menú: Crear nuevo plugin"

  "Menu: Create new theme"
  "Crear nuevo tema..."

  "Menu: Cut text"
  "Menú: Cortar texto"

  "Menu: Delete session"
  "Menú: Sesión de borrar"

  "Menu: Disable Vim mode"
  "Menú: Desactive el modo Vim"

  "Menu: Edit Tke theme"
  "Menú: Editar Tke tema"

  "Menu: Edit language snippets"
  "Menú: Fragmentos de idioma editar"

  "Menu: Edit session current language preferences"
  "Menú: Editar preferencias de idioma actual período de sesiones"

  "Menu: Edit session global preferences"
  "Menú: Editar preferencias globales del período de sesiones"

  "Menu: Edit user current language preferences"
  "Menú: Editar preferencias de idioma actual del usuario"

  "Menu: Edit user global preferences"
  "Menú: Editar preferencias globales"

  "Menu: Edit user menu bindings"
  "Enlaces del menú Editar usuario: Menu"

  "Menu: Enable Vim mode"
  "Menú: Habilitar el modo Vim"

  "Menu: Favorite file"
  "Menú: Archivo favorito"

  "Menu: Find"
  "Menú: Buscar"

  "Menu: Find and Replace"
  "Buscar y reemplazar"

  "Menu: Find in files"
  "Menú: Buscar en los archivos"

  "Menu: Find matching character pair"
  "Menú: Encuentra pares de caracteres coincidente"

  "Menu: Find next occurrence"
  "Menú: Buscar la siguiente aparición"

  "Menu: Find previous occurrence"
  "Menú: Buscar aparición anterior"

  "Menu: Format all text"
  "Menú: Formato todo el texto"

  "Menu: Format selected text"
  "Menú: Formato de texto seleccionado"

  "Menu: Goto last tab"
  "Menú: Ir a la última pestaña"

  "Menu: Goto next difference"
  "Menú: Diferencia siguiente Goto"

  "Menu: Goto next tab"
  "Menú: Ir a la siguiente pestaña"

  "Menu: Goto other pane"
  "Menú: Ir a otro panel"

  "Menu: Goto previous difference"
  "Menú: Diferencia anterior Goto"

  "Menu: Goto previous tab"
  "Menú: Ir a la pestaña anterior"

  "Menu: Hide Line Numbers"
  "Menú: Ocultar los números de línea"

  "Menu: Hide Tab Bar"
  "Menú: Hide Tab Bar"

  "Menu: Hide console"
  "Menú: Ocultar la consola"

  "Menu: Hide meta characters"
  "MENU: Ocultar meta caracteres"

  "Menu: Hide sidebar"
  "Menú: Ocultar barra lateral"

  "Menu: Hide status bar"
  "Menú: Ocultar barra de estado"

  "Menu: Import TextMate theme"
  "Menú: Import tema TextMate"

  "Menu: Indent selected text"
  "Menú: sangría del texto seleccionado"

  "Menu: Insert enumeration"
  "Menú: Insertar enumeración"

  "Menu: Insert from clipboard"
  "Insertar mediante el Portapapeles"

  "Menu: Insert snippet"
  "Menú: Insertar fragmento"

  "Menu: Install plugin"
  "Menú: Instalar Plugin"

  "Menu: Jump backward"
  "Menú: Saltar hacia atrás"

  "Menu: Jump forward"
  "Menú: Salto hacia delante"

  "Menu: Lock file"
  "Bloqueo de archivos: Menu"

  "Menu: Merge panes"
  "Menú: Recuadros fusión"

  "Menu: Move to other pane"
  "Menú: Mover a otro panel"

  "Menu: New file"
  "Menú: Nuevo archivo"

  "Menu: Open Favorite"
  "Menú: Abrir favorita"

  "Menu: Open Recent"
  "Menú: Abrir reciente"

  "Menu: Open directory"
  "Menú: Abrir el listín telefónico"

  "Menu: Open file"
  "Menú: Abrir el archivo"

  "Menu: Open session"
  "Menú: Sesión abierta"

  "Menu: Paste and format text from clipboard"
  "Menú: Pasta y formato de texto desde el portapapeles"

  "Menu: Paste text from clipboard"
  "Pegar texto desde el portapapeles"

  "Menu: Quit application"
  "Menú: Salir de la aplicación"

  "Menu: Redo"
  "Menú: Redo"

  "Menu: Reload all plugins"
  "Menú: Actualizar todos los plugins"

  "Menu: Reload snippets"
  "Menú: Fragmentos de recarga"

  "Menu: Remove all markers"
  "Menú: Eliminar todos los marcadores"

  "Menu: Remove marker from current line"
  "Menú: Quitar marcador de línea actual"

  "Menu: Replace line with script"
  "Menú: Reemplazar la línea con guión"

  "Menu: Restart tke"
  "Menú: Reinicie tke"

  "Menu: Save all files"
  "Menú: Guarde todos los archivos"

  "Menu: Save current session"
  "¿Guardar la sesión actual?"

  "Menu: Save file"
  "Menú: Guardar el archivo"

  "Menu: Save file as"
  "Menú: Guardar archivo como"

  "Menu: Save sessions as"
  "Menú: Guardar sesiones como"

  "Menu: Select all occurrences"
  "Menú: seleccione todas las ocurrencias"

  "Menu: Select all text"
  "Seleccionar todo el texto"

  "Menu: Send Bug Report"
  "Menú: Enviar informe de errores"

  "Menu: Send Feedback"
  "Menú: Enviar comentarios"

  "Menu: Set indent mode to IND"
  "Menu: Configurar modo de guión a IND"

  "Menu: Set indent mode to IND+"
  "Menú: En el modo guión IND +"

  "Menu: Set indent mode to OFF"
  "Menú: El guión modo OFF"

  "Menu: Set user bindings to global bindings"
  "Menú: Establezca usuario enlaces a enlaces globales"

  "Menu: Set user preferences to global preferences"
  "Menú: Establezca las preferencias del usuario en las preferencias globales"

  "Menu: Show Diagnostic Logfile"
  "Menu: Mostrar diagnóstico Logfile"

  "Menu: Show Line Numbers"
  "Mostar número de lineas"

  "Menu: Show Tab Bar"
  "Menú: Mostrar barra de pestañas"

  "Menu: Show console"
  "Menú: Mostrar consola"

  "Menu: Show file difference"
  "Menú: Diferencia ver archivo"

  "Menu: Show last profiling report"
  "Menú: Mostrar último informe perfiles"

  "Menu: Show meta characters"
  "Menú: Mostrar caracteres meta"

  "Menu: Show selected line change"
  "Menú: Línea cambio Show seleccionada"

  "Menu: Show sidebar"
  "Menú: Mostrar barra lateral"

  "Menu: Show status bar"
  "Menú: Mostrar barra de estado"

  "Menu: Sort tabs"
  "Menú: Ordenar pestañas"

  "Menu: Start profiling"
  "Menú: perfiles inicio"

  "Menu: Stop profiling"
  "Menú: perfilación"

  "Menu: Switch to session"
  "Menú: Interruptor a período de sesiones"

  "Menu: Toggle comment"
  "Menú: Comentario de cambiar"

  "Menu: Toggle split view mode"
  "Menú: Cambiar el modo de vista dividida"

  "Menu: Undo"
  "Menú: Deshacer"

  "Menu: Unfavorite file"
  "Menú: archivo unfavorite"

  "Menu: Unindent selected text"
  "Menú: texto seleccionado Unindent"

  "Menu: Uninstall plugin"
  "Menú: Programas Desinstalar"

  "Menu: Unlock file"
  "Desbloquear archivo: Menú"

  "Menu: View User Guide"
  "Ver Guía del usuario"

  "Menu: View base preferences file"
  "Menú: Ver base preferencias archivo"

  "Menu: View global menu bindings"
  "Menú: Ver enlaces de menú globales"

  "Merge Panes"
  "Unir paneles"

  "Next Difference"
  "Siguiente diferencia"

  "No files found in specified directories"
  "No hay archivos en directorios especificados"

  "Open Directory..."
  "Abra Directorio ..."

  "Open Favorite"
  "Abrir favorita"

  "Open File..."
  "Columna abierta..."

  "Open Recent"
  "Abrir reciente"

  "Paste"
  "Pegar"

  "Paste and Format"
  "Pega y Formato"

  "Plugins"
  "Complemento"

  "Preferences"
  "Preferencias"

  "Previous Difference"
  "Anterior diferencia"

  "Profiling started"
  "Profiling comenzó"

  "Profiling stopped"
  "Profiling detuvo"

  "Quit"
  "Dejar de"

  "Redo"
  "Rehacer"

  "Reload"
  "Reload"

  "Remove All Markers"
  "Eliminar todos los marcadores"

  "Remove From Current Line"
  "Retire de la línea actual"

  "Replace Line With Script"
  "Reemplazar línea con Script"

  "Reset User to Base"
  "Restablecer el usuario a la Base"

  "Restart TKE"
  "Reiniciar TKE"

  "Save All"
  "Guardar todo"

  "Save As..."
  "Guardar como ..."

  "Save Current"
  "Guardar la corriente"

  "Select All"
  "Seleccionar todo"

  "Select All Occurrences"
  "Seleccione todas las ocurrencias"

  "Select Next Occurrence"
  "Seleccione la siguiente ocurrencia"

  "Select Previous Occurrence"
  "Seleccionar anterior aparición"

  "Selected"
  "Seleccionado"

  "Send Bug Report"
  "Enviar el informe de fallos."

  "Send Feedback"
  "Contáctenos"

  "Sessions"
  "Sesiones"

  "Set Syntax"
  "Establecer Sintaxis"

  "Set Theme"
  "Establecer tema"

  "Set User to Global"
  "Usuario Set Global"

  "Show Console"
  "Mostrar consola"

  "Show Diagnostic Logfile"
  "Logfile diagnóstico Mostrar"

  "Show File Difference"
  "Mostrar archivo diferencia"

  "Show Last Profiling Report"
  "Mostrar último informe Profiling"

  "Show Line Numbers"
  "Mostar número de lineas"

  "Show Meta Characters"
  "Mostrar caracteres de Meta"

  "Show Selected Line Change"
  "Cambio de línea seleccionada"

  "Show Sidebar"
  "Mostrar barra lateral"

  "Show Status Bar"
  "Barra de estado"

  "Show Tab Bar"
  "Barra de solapas"

  "Show*Profiling*"
  "Mostrar*Profiling*"

  "Smart Indent"
  "Guión inteligente"

  "Snippet"
  "De fragmentos"

  "Snippets"
  "Fragmentos"

  "Sort Tabs"
  "Sort Tabs"

  "Split View"
  "Dividir la vista"

  "Start Profiling"
  "Comience perfiles"

  "Stop Profiling"
  "Detener perfiles"

  "Switch To"
  "Vaya a"

  "Tabs"
  "Tablas"

  "Text"
  "Text"

  "Theme Creator"
  "Theme Creator"

  "Toggle Comment"
  "Comentario de palanca"

  "Tools"
  "Herramientas"

  "Undo"
  "Deshacer"

  "Unindent"
  "Unindent"

  "Uninstall..."
  "desinstalar"

  "Unlock"
  "Descubrir"

  "User Guide"
  "Guía del usuario"

  "View"
  "Vista"

  "View Base"
  "Ver Base"

  "View Global"
  "Vista Global"

  "Vim Mode"
  "Modo de Vim"

}

# plugins.tcl
msgcat::mcmset es {

  "ERROR (%s,%s): %s"
  "ERROR (%s, %s): %s"

  "ERROR:  Plugin name already exists"
  "ERROR: nombre Plugin ya existe"

  "ERROR:  Plugin name is not valid (only alphanumeric and underscores are allowed)"
  "ERROR: Nombre del Plugin no es válido (sólo caracteres alfanuméricos y guiones están permitidos)"

  "ERROR:  Unable to create plugin directory"
  "ERROR: No se puede crear el directorio de plugins"

  "ERROR:  Unable to write plugin files"
  "ERROR: No se puede escribir archivos de plugin"

  "Enter plugin name"
  "Ingrese nombre del plugin"

  "Plugin %s installed"
  "Plugin %s instalado"

  "Plugin %s uninstalled"
  "Plugin %s desinstalado"

  "Plugin Errors"
  "Errores Plugin"

  "Plugins successfully reloaded"
  "Plugins recargado con éxito"

  "Syntax errors found in selected plugins"
  "Los errores de sintaxis encontrados en plugins seleccionados"

}

# sidebar.tcl
msgcat::mcmset es {

  "Add Parent Directory"
  "Añadir Parent Directory"

  "Close Directory Files"
  "Cerrar archivos de directorio"

  "Copy Pathname"
  "Copiar ruta de acceso"

  "Delete directory?"
  "Eliminar directorio?"

  "Delete file?"
  "Eliminar archivo"

  "Directory Name:"
  "nombre de guía"

  "Duplicate"
  "Duplicar"

  "File Name:"
  "Nombre del archivo:"

  "Folder Name:"
  "Nombre de la carpeta:"

  "Make Current Working Directory"
  "Haga directorio de trabajo actual"

  "New Directory"
  "Nuevo directorio"

  "Open Directory Files"
  "Abrir archivos Directorio"

  "Refresh Directory Files"
  "Actualizar los archivos de directorio"

  "Remove Parent from Sidebar"
  "Retire los Padres de Sidebar"

  "Remove from Sidebar"
  "Eliminar de la barra lateral"

  "Rename"
  "Cambiar nombre"

  "Show Difference"
  "Mostrar diferencia"

}

# snippets.tcl
msgcat::mcmset es {

  "Snippet: *"
  "Fragmento: *"

}

# syntax.tcl
msgcat::mcmset es {

  "Syntax error in %s.syntax file"
  "Error de sintaxis en el archivo %s.syntax"

  "Syntax:  %s"
  "Sintaxis: %s"

  "Theme:  %s"
  "Tema: %s"

}

# themer.tcl
msgcat::mcmset es {

  "Create"
  "Crear"

  "Create New Theme"
  "Crear nuevo tema..."

  "Create custom"
  "Crear formulario personalizado"

  "ERROR:  Unable to read %s"
  "ERROR: No se puede leer %s"

  "ERROR:  Unable to write %s"
  "ERROR: No se puede escribir %s"

  "Edit theme"
  "Editar tema"

  "Enter theme name"
  "Ingrese nombre del tema"

  "Error:  Theme is not a supported theme"
  "Error: Tema no es un tema con el apoyo"

  "Import"
  "Importar"

  "Import TextMate Theme"
  "Importar TextMate Tema"

  "Name:"
  "Nombre:"

  "OK"
  "OK"

  "Reset"
  "Reajustar"

  "Select theme"
  "Seleccione un tema"

}

# tke.tcl
msgcat::mcmset es {

  "Edit theme?"
  "Editar tema?"

  "Import TextMate theme?"
  "Importar tema TextMate?"

}

# vim.tcl
msgcat::mcmset es {

  "File %s successfully written"
  "Archivo %s que se ha escrito"

  "Filename %s already exists"
  "Nombre del archivo %s ya existe."

}

# General
msgcat::mcmset es {

  "Cancel"
  "Cancelar"

  "Close"
  "Cerrar"

  "Delete"
  "Eliminar"

  "Favorite"
  "Favorito"

  "Find:"
  "Encontrar:"

  "Move to Other Pane"
  "Mover a otro panel"

  "New File"
  "Nuevo archivo"

  "Open"
  "Abierto"

  "Replace:"
  "Reemplazar:"

  "Save"
  "Guardar"

  "Save As"
  "Guardar como"

  "Unable to open %s for writing"
  "No se puede abrir %s para escritura"

  "Unfavorite"
  "Unfavorite"

}

