# api.tcl
msgcat::mcmset es {

  "Argument list to api::add_file was not an even key/value pair"
  "Lista de argumentos para api::add_file no era un par aun clave/valor"

  "Plugin"
  "Plugin"

}

# bgproc.tcl
msgcat::mcmset es {

  "Unable to run system command"
  "No se puede ejecutar el comando del sistema"

}

# diff.tcl
msgcat::mcmset es {

  "    End: "
  "Remata:"

  "    Start: "
  "Comienzo:"

  "Enter difference command"
  "Introduzca el comando diferencia"

  "Enter starting file"
  "Entrar a partir del archivo"

  "Update"
  "Actualizar"

}

# edit.tcl
msgcat::mcmset es {

  "File successfully written"
  "Archivo que se ha escrito"

  "Filename already exists"
  "Nombre de archivo ya existe"

}

# embed_tke.tcl
msgcat::mcmset es {

  "Find:"
  "Encontrar:"

  "Replace:"
  "Reemplazar:"

}

# gui.tcl
msgcat::mcmset es {

  "All"
  "Todo"

  "Case sensitivity"
  "Case sensitive"

  "Close All Tabs"
  "¿Cerramos todas las pestañas?"

  "Close Other Tabs"
  "Cerrar otras pestañas"

  "Close Other*"
  "Cerrar Other*"

  "Close Tab"
  "Close Tab"

  "Column"
  "Columna"

  "Copyright"
  "Copyright"

  "Delete tab?"
  "Eliminar ficha?"

  "Developer"
  "Desarrollador"

  "Email"
  "el correo electrónico"

  "Error"
  "Error"

  "Favorited"
  "Los favoritos"

  "File already exists.  Use '!' to force an overwrite"
  "Ya existe el archivo.  Uso '!' para forzar una sobreescritura"

  "File attribute does not exist"
  "El atributo de archivo no existe"

  "File index is out of range"
  "Índice del archivo está fuera de rango"

  "Image displayed in fill-in forms which closes the form UI.  Used in forms such as search, search/replace, and find in files."
  "Imagen visualizada en forma de relleno en el que se cierra el formulario de la interfaz de usuario. Se utiliza en formas tales como búsqueda, búsqueda / reemplazo, y encontrar en los archivos."

  "Image used in tab menus to indicate that the file is associated with a difference view."
  "Image utilizado en los menús de la ficha para indicar que el archivo está asociado con una vista diferencia."

  "Image used in tab menus to indicate that the file is locked."
  "La imagen usada en los menús de la ficha para indicar que el archivo está bloqueado."

  "Image used in tab menus to indicate that the file is readonly."
  "La imagen usada en los menús de la ficha para indicar que el archivo es de sólo lectura."

  "Image used in tab to indicate that the tab contains a difference view."
  "La imagen usada en la pestaña para indicar que la ficha contiene una vista de diferencia."

  "Image used in tab to indicate that the tab's file is readonly."
  "La imagen usada en la pestaña para indicar que el archivo de la ficha es de sólo lectura."

  "Image used in tab to indicate that the tab’s file is locked."
  "La imagen usada en la pestaña para indicar que el archivo de la ficha está bloqueado."

  "Image used in tab which, when clicked, closes the tab."
  "Imagen utilizada en la pestaña que, cuando se hace clic, se cierra la pestaña."

  "License"
  "Licencia"

  "Line"
  "Línea"

  "Locked"
  "Bloqueado"

  "Move"
  "Mover"

  "Must be in multicursor mode to insert numbers"
  "Debe estar en modo multicursor para insertar números"

  "No write permissions.  Use '!' to force write."
  "No hay permisos de escritura.  Uso '!' para forzar la escritura."

  "Release Type"
  "Tipo de versión"

  "Reload file?"
  "Recargar archivo"

  "Replace"
  "Reemplazar"

  "Save request"
  "Memorizar encargo"

  "Show in Sidebar"
  "Mostrar en Sidebar"

  "Starting number:"
  "Número inicial:"

  "Tcl/Tk Version"
  "Versión de Tcl/Tk"

  "Total Characters"
  "Total caracteres"

  "Total Lines"
  "Total líneas"

  "Unable to successfully parse number string"
  "No se puede analizar correctamente la cadena número"

  "Unable to write file"
  "No se puede escribir el archivo"

  "Version"
  "Versión"

}

# markers.tcl
msgcat::mcmset es {

  "Marker name:"
  "Nombre del marcador:"

}

# menus.tcl
msgcat::mcmset es {

  "About"
  "Acerca"

  "Absolute"
  "Absoluta"

  "Absolute line numbering"
  "Numeración de líneas absolutas"

  "Align Cursors"
  "Alinee los cursores"

  "Align cursors"
  "Alinee los cursores"

  "All Levels"
  "Todos los niveles de acceso"

  "Append Next Occurrence"
  "Anexar la siguiente ocurrencia"

  "Append next occurrence"
  "Anexar la siguiente ocurrencia"

  "Auto-Indent"
  "Sangrado automático"

  "Bubble Down"
  "La burbuja abajo"

  "Bubble Up"
  "Burbuja para arriba"

  "Bubble lines down one line"
  "Líneas abajo una línea de la burbuja"

  "Bubble lines up one line"
  "Líneas de burbujas encima de una línea"

  "Change Working Directory"
  "Cambiar directorio de trabajo"

  "Change working directory"
  "Cambiar directorio de trabajo"

  "Character"
  "Carácter"

  "Check for Update"
  "Buscar actualización"

  "Check for update"
  "Comprobar se hay actualizaciones"

  "Classic Mac"
  "Mac Classic"

  "Clear All"
  "Limpiar todo"

  "Close All"
  "Cerrar todo"

  "Close All Folds"
  "Cerrar todos los pliegues"

  "Close Current"
  "Cerrar vista actual"

  "Close Current Fold"
  "Cierre tapa corriente"

  "Close Selected Folds"
  "Cierre seleccionado pliegues"

  "Close all folds"
  "Cerrar todos los pliegues"

  "Close all tabs"
  "¿Cerramos todas las pestañas?"

  "Close current session"
  "Cierra la pestaña actual y la sesión que contiene."

  "Close current tab"
  "Cerrar la pestaña actual"

  "Close fold at current line - all levels"
  "Doble cierre en línea actual - todos los niveles"

  "Close fold at current line - one level"
  "Doble cierre en línea actual - un nivel"

  "Close selected folds - all levels"
  "Cerrar las dobleces - todos los niveles"

  "Close selected folds - one level"
  "Cerrar las dobleces - uno nivel"

  "Command"
  "Comando"

  "Command Result"
  "Resultado del comando"

  "Convert case to lower"
  "Convertir el caso para bajar"

  "Convert case to title"
  "Convertir caso a título"

  "Convert case to upper"
  "Convertir caso en parte superior"

  "Copy"
  "Copia"

  "Copy text"
  "Copiar el texto"

  "Create"
  "Crear"

  "Create Fold From Selection"
  "Crear desde la selección"

  "Create at Current Line"
  "Crear en línea actual"

  "Create fold from selection"
  "Crear desde la selección"

  "Create marker at current line"
  "Crear marcador en línea actual"

  "Create new plugin"
  "Crear nuevo plugin"

  "Current Line"
  "Línea actual:"

  "Current Number"
  "Número de página corriente"

  "Current Word"
  "Palabra actual"

  "Cursor"
  "Cursor"

  "Cursor from Line Start"
  "Cursor desde principio de línea"

  "Cursor to Line End"
  "Cursor al final de línea"

  "Cut"
  "Cortar"

  "Cut text"
  "Cortar texto"

  "Delete All Folds"
  "Eliminar todos los pliegues"

  "Delete Current Fold"
  "Eliminar la actual"

  "Delete Selected Folds"
  "Eliminar seleccionado pliegues"

  "Delete all folds"
  "Eliminar todos los pliegues"

  "Delete all selected folds"
  "Eliminar todas las dobleces"

  "Delete current file"
  "Eliminar la actual"

  "Delete current line"
  "Eliminar la actual"

  "Delete current word"
  "Eliminar la actual"

  "Delete fold at current line"
  "Eliminar el pliegue en la línea actual"

  "Delete from cursor to end of line"
  "Borrar desde cursor a fin de línea"

  "Delete from start of line to cursor"
  "Borrar desde principio de línea hasta el cursor"

  "Delete session"
  "¿Eliminar sesión?"

  "Delete template"
  "Eliminar plantilla"

  "Delete text between character"
  "Elimine el texto entre el carácter"

  "Delete the current number"
  "Eliminar el número actual"

  "Delete the whitespace to left of cursor"
  "Eliminar el espacio en blanco a la izquierda del cursor"

  "Delete the whitespace to right of cursor"
  "Eliminar el espacio en blanco a la derecha del cursor"

  "Disable Vim mode"
  "Desactivar el modo de Vim"

  "Display Text Info"
  "Visualizar texto"

  "Display text information"
  "Información en pantalla."

  "Duplicate current file"
  "Archivo actual duplicado"

  "Edit"
  "Edición"

  "Edit Custom Abbreviations"
  "Editar abreviaturas personalizadas"

  "Edit Language"
  "Editar Idioma"

  "Edit Session"
  "Editar Sesión"

  "Edit User"
  "Editar usuario"

  "Edit custom Emmet abbreviations"
  "Edición personalizadas abreviaturas de Emmet"

  "Edit language snippets"
  "Editar fragmentos de lenguaje"

  "Edit session current language preferences"
  "Editar preferencias de idioma actual período de sesiones"

  "Edit session global preferences"
  "Editar preferencias globales del período de sesiones"

  "Edit template"
  "Editar plantilla"

  "Edit user current language preferences"
  "Editar preferencias de idioma actual del usuario"

  "Edit user global preferences"
  "Editar las preferencias del usuario global"

  "Edit user menu bindings"
  "Editar enlaces del menú de usuario"

  "Edit user snippets"
  "Editar fragmentos de código de usuario"

  "Enable Vim mode"
  "Activar el modo de Vim"

  "Enumeration"
  "Enumeración"

  "Expand Abbreviation"
  "Ampliar la abreviatura"

  "Expand Emmet abbreviation"
  "Ampliar la abreviatura de Emmet"

  "Favorite file"
  "Archivo de favoritos"

  "File"
  "Expediente"

  "File Contents"
  "contenido de fichero"

  "Find In Files"
  "Buscar en los Archivos..."

  "Find Matching Pair"
  "Encontrar pareja"

  "Find and Replace"
  "Buscar y reemplazar"

  "Find in files"
  "Buscar en los Archivos..."

  "Find matching character pair"
  "Encontrar el correspondiente par de carácter"

  "Find next occurrence"
  "Buscar la siguiente aparición"

  "Find previous occurrence"
  "Buscar anterior aparición"

  "Fold Method"
  "Método de doblez"

  "Folding"
  "reunido"

  "Format Text"
  "Formato de texto"

  "Format indentation for text"
  "Formato de sangría de texto"

  "From Clipboard"
  "Desde el portapapeles"

  "Global"
  "Global"

  "Goto Last Tab"
  "Ir a la última pestaña"

  "Goto Next Tab"
  "Ir a la siguiente pestaña"

  "Goto Other Pane"
  "Goto Otro panel"

  "Goto Previous Tab"
  "Ir a la pestaña anterior"

  "Goto last tab"
  "Ir a la última pestañ"

  "Goto next difference"
  "Goto siguiente diferencia"

  "Goto next tab"
  "Goto siguiente pestaña"

  "Goto other pane"
  "Goto otro panel"

  "Goto previous difference"
  "Anterior diferencia"

  "Goto previous tab"
  "Pestaña anterior"

  "Help"
  "Help!"

  "Hide Console"
  "Hide Console"

  "Hide Line Numbers"
  "Ocultar los números de línea"

  "Hide Marker Map"
  "Ocultar mapa de marcador"

  "Hide Meta Characters"
  "Ocultar caracteres Meta"

  "Hide Sidebar"
  "Ocultar barra lateral"

  "Hide Status Bar"
  "Barra de estado"

  "Hide Tab Bar"
  "Hide Tab Bar"

  "Hide console"
  "Ocultar consola"

  "Hide line numbers"
  "Ocultar Lineas"

  "Hide marker map"
  "Ocultar mapa de marcador"

  "Hide meta characters"
  "Ocultar caracteres de meta"

  "Hide sidebar"
  "Ocultar Barra Lateral"

  "Hide status bar"
  "Barra de estado"

  "Hide tab bar"
  "Ocultar la barra de pestañas"

  "Indent"
  "Indentar"

  "Indent Off"
  "Guión de"

  "Indent selected text"
  "Aplicar sangría al texto seleccionado"

  "Indentation"
  "Sangría"

  "Insert"
  "Insertar"

  "Insert command result after current line"
  "Inserte el resultado del comando después de la línea actual"

  "Insert enumeration"
  "Insertar (enumeración)"

  "Insert file contents after current line"
  "Introduzca el contenido del archivo después de la línea actual"

  "Insert from clipboard"
  "Insertar mediante el Portapapeles"

  "Insert line above current line"
  "Insertar línea por encima de la línea actual"

  "Insert line below current line"
  "Insertar línea por debajo de la línea actual"

  "Insert snippet"
  "Insertar fragmento de código"

  "Install"
  "Instalar"

  "Install plugin"
  "Instalar complemento"

  "Join Lines"
  "Unir líneas"

  "Join lines"
  "Unir líneas"

  "Jump Backward"
  "Salto hacia atrás"

  "Jump Forward"
  "Saltar hacia adelante"

  "Jump To Line"
  "Saltar a la línea"

  "Jump backward"
  "Salto hacia atrás"

  "Jump forward"
  "Saltar hacia adelante"

  "Jump to Next Fold Mark"
  "Saltar a la siguiente marca de doblez"

  "Jump to Previous Fold Mark"
  "Saltar a la anterior marca de doblez"

  "Jump to line"
  "Saltar a la línea"

  "Jump to the next fold indicator"
  "Saltar al siguiente indicador doble"

  "Jump to the previous fold indicator"
  "Salta al anterior indicador doble"

  "Language"
  "Idioma"

  "Launcher"
  "Lanzador"

  "Line Above Current"
  "Línea de sobre corriente"

  "Line Below Current"
  "Línea por debajo de la corriente"

  "Line Ending"
  "Final de línea"

  "Line Number"
  "Número de línea"

  "Line Numbering"
  "Numeración de líneas"

  "Lock"
  "Bloquear"

  "Lock file"
  "Archivo de bloqueo"

  "Lower Case"
  "Minúsculas"

  "Manual"
  "Manual"

  "Markers"
  "Marcadores"

  "Menu"
  "Menú"

  "Menu Bindings"
  "Vinculaciones Menú"

  "Merge Panes"
  "Unir paneles"

  "Merge panes"
  "Unir paneles"

  "Move Cursors Down"
  "Bajar cursores"

  "Move Cursors Left"
  "Mover Cursores izquierda"

  "Move Cursors Right"
  "Mover hacia la derecha de los cursores"

  "Move Cursors Up"
  "Mover cursores"

  "Move cursor to bottom of screen"
  "Mover el cursor a la parte inferior de la pantalla"

  "Move cursor to end of current line"
  "Desplace el cursor a final de línea actual"

  "Move cursor to first line"
  "Mover el cursor a la primera línea"

  "Move cursor to last line"
  "Mover el cursor a la última línea"

  "Move cursor to middle of screen"
  "Mover el cursor al centro de la pantalla"

  "Move cursor to next page"
  "Mover el cursor a la siguiente página"

  "Move cursor to next word"
  "Mover el cursor a la siguiente palabra"

  "Move cursor to previous page"
  "Mover el cursor a la página anterior"

  "Move cursor to previous word"
  "Mover el cursor a la palabra anterior"

  "Move cursor to start of current line"
  "Mover el cursor al inicio de la línea actual"

  "Move cursor to top of screen"
  "Mover el cursor a la parte superior de pantalla"

  "Move multicursors down one line"
  "Bajar multicursors de una línea"

  "Move multicursors left one line"
  "Mover una línea de izquierda multicursors"

  "Move multicursors right one line"
  "Mover derecha una línea de multicursors"

  "Move multicursors up one line"
  "Mover multicursors hasta una línea"

  "Move to First Line"
  "Pasar a primera línea"

  "Move to Last Line"
  "Mueve a última línea"

  "Move to Line End"
  "Mover a la línea final"

  "Move to Line Start"
  "Mover a la línea de inicio"

  "Move to Next Page"
  "Mover a página siguiente"

  "Move to Next Word"
  "Pasar a la siguiente palabra"

  "Move to Previous Page"
  "Mover a página anterior"

  "Move to Previous Word"
  "Mover a la palabra anterior"

  "Move to Screen Bottom"
  "Mover a la parte inferior de la pantalla"

  "Move to Screen Middle"
  "Hacia mitad de la pantalla"

  "Move to Screen Top"
  "Mover a la parte superior de la pantalla"

  "Move to other pane"
  "Mover al otro panel"

  "New From Template"
  "Nuevo desde Plantilla"

  "New Window"
  "Nueva ventana"

  "New file"
  "Nuevo Archivo"

  "New file from template"
  "Nuevo archivo de plantilla"

  "New window"
  "Nueva ventana"

  "Next Difference"
  "Siguiente diferencia"

  "One Level"
  "Subir un nivel"

  "Open All Folds"
  "Abrir los pliegues"

  "Open Current Fold"
  "Doble actual abierto"

  "Open Directory"
  "Abrir un directorio"

  "Open Favorite"
  "Abrir favorita"

  "Open File"
  "Abrir archivo"

  "Open Recent"
  "Abrir reciente"

  "Open Selected Folds"
  "Abierto selecciona los pliegues"

  "Open all folds"
  "Abrir los pliegues"

  "Open directory"
  "Abrir un directorio"

  "Open file"
  "Abrir archivo"

  "Open fold at current line - all levels"
  "Doble abierto en línea actual - todos los niveles"

  "Open fold at current line - one level"
  "Doble abierto en línea actual - un nivel"

  "Open folds to show cursor"
  "Pliegues abiertos para mostrar cursor"

  "Open selected folds - all levels"
  "Abierto las dobleces - todos los niveles"

  "Open selected folds - one level"
  "Abierto las dobleces - un nivel"

  "Paste"
  "Pegar"

  "Paste and Format"
  "Pega y Formato"

  "Paste and format text from clipboard"
  "Formato y pegar texto del portapapeles"

  "Paste text from clipboard"
  "Pegar texto del portapapeles"

  "Plugins"
  "Complemento"

  "Preferences"
  "Preferencias"

  "Previous Difference"
  "Anterior diferencia"

  "Profiling Report Sorted By"
  "Informe perfiles ordenado por"

  "Profiling started"
  "Profiling comenzó"

  "Profiling stopped"
  "Profiling detuvo"

  "Quit"
  "Dejar de"

  "Quit application"
  "Salir de la aplicación"

  "Redo"
  "Rehacer"

  "Relative"
  "Relativa"

  "Relative line numbering"
  "Numeración de línea relativa"

  "Reload"
  "Reload"

  "Reload all plugins"
  "Volver a cargar complementos"

  "Reload snippets"
  "Fragmentos de recarga"

  "Reload template information"
  "Cargar información de la plantilla"

  "Remove All Markers"
  "Eliminar todos los marcadores"

  "Remove From Current Line"
  "Retire de la línea actual"

  "Remove all markers"
  "Eliminar todos los marcadores"

  "Remove marker from current line"
  "Eliminar marcador de línea actual"

  "Rename current file"
  "Cambiar el nombre de archivo actual"

  "Reopen File"
  "Abrir archivo"

  "Reopen current file"
  "Abrir archivo actual"

  "Replace Line With Script"
  "Reemplazar línea con Script"

  "Replace line with script"
  "Reemplazar línea con script"

  "Reset User to Base"
  "Restablecer el usuario a la Base"

  "Restart"
  "Reiniciar"

  "Run"
  "Ejecutar"

  "Run theme editor"
  "Ejecutar el editor de temas"

  "Save All"
  "Guardar todo"

  "Save As Template"
  "Guardar como plantilla"

  "Save Current"
  "Guardar la corriente"

  "Save Selection As"
  "Guardar selección como"

  "Save all files"
  "Guarde todos los archivos"

  "Save current session"
  "Guardar sesión actual"

  "Save file"
  "Partida guardada"

  "Save file as"
  "Guardar archivo como..."

  "Save file as template"
  "Guardar como plantilla"

  "Save selected lines"
  "Guardar las líneas seleccionadas"

  "Save sessions as"
  "Guardar sesiones como"

  "Select All"
  "Seleccionar todo"

  "Select All Occurrences"
  "Seleccione todas las ocurrencias"

  "Select Next Occurrence"
  "Seleccione la siguiente ocurrencia"

  "Select Previous Occurrence"
  "Seleccionar anterior aparición"

  "Select all occurrences"
  "Seleccionar todas las apariciones"

  "Select all text"
  "Seleccionar todo el texto"

  "Send Bug Report"
  "Enviar el informe de fallos."

  "Send Feedback"
  "Contáctenos"

  "Send bug report"
  "Enviar el informe de fallos."

  "Send feedback"
  "Enviar comentarios"

  "Sessions"
  "Sesiones"

  "Set Syntax"
  "Establecer Sintaxis"

  "Set Theme"
  "Establecer tema"

  "Set User to Global"
  "Usuario Set Global"

  "Set current file line ending to CR for Classic Mac"
  "Actual línea de archivo final a CR para Mac Classic"

  "Set current file line ending to CRLF for Windows"
  "Conjunto de actual archivo línea conclusión de CRLF para Windows"

  "Set current file line ending to LF for Unix"
  "Actual línea de archivo final LF para Unix"

  "Set folding method to manual"
  "Establecer método manual plegable"

  "Set folding method to none"
  "Conjunto plegable método a ninguno"

  "Set folding method to syntax"
  "Establecer método para sintaxis plegable"

  "Set indent mode to"
  "Ajuste modo de guión a"

  "Set user bindings to global bindings"
  "Establecer enlaces de usuario a los enlaces globales"

  "Set user preferences to global preferences"
  "Definir las preferencias de usuario a las preferencias globales"

  "Show Console"
  "Mostrar consola"

  "Show Cursor"
  "Mostrar cursor"

  "Show Diagnostic Logfile"
  "Logfile diagnóstico Mostrar"

  "Show File Difference"
  "Mostrar archivo diferencia"

  "Show Last Profiling Report"
  "Mostrar último informe Profiling"

  "Show Line Numbers"
  "Mostar número de lineas"

  "Show Marker Map"
  "Mostrar marcador"

  "Show Meta Characters"
  "Mostrar caracteres de Meta"

  "Show Selected Line Change"
  "Cambio de línea seleccionada"

  "Show Sidebar"
  "Mostrar barra lateral"

  "Show Status Bar"
  "Barra de estado"

  "Show Tab Bar"
  "Barra de solapas"

  "Show console"
  "Mostrar consola"

  "Show diagnostic logfile"
  "Mostrar archivo de registro de diagnóstico"

  "Show file difference"
  "Mostrar diferencia de archivo"

  "Show last profiling report"
  "Mostrar el último informe de generación de perfiles"

  "Show line numbers"
  "Mostrar Lineas:"

  "Show marker map"
  "Mostrar marcador"

  "Show meta characters"
  "Mostrar caracteres de meta"

  "Show selected line change"
  "Cambio de línea seleccionada"

  "Show sidebar"
  "Mostrar barra lateral"

  "Show status bar"
  "Mostrar la barra de estado"

  "Show tab bar"
  "Barra de solapas"

  "Smart Indent"
  "Guión inteligente"

  "Snippet"
  "De fragmentos"

  "Snippets"
  "Fragmentos"

  "Sort Tabs"
  "Sort Tabs"

  "Sort tabs"
  "Fichas de clase"

  "Start Profiling"
  "Comience perfiles"

  "Start profiling"
  "Iniciar generación de perfiles"

  "Stop Profiling"
  "Detener perfiles"

  "Stop profiling"
  "Dejar de perfiles"

  "Switch To"
  "Vaya a"

  "Switch to session"
  "Cambiar a la sesión"

  "Tabs"
  "Tablas"

  "Templates"
  "Plantillas"

  "Text Between Character"
  "Texto entre el carácter"

  "Title Case"
  "Mayús/minús de título"

  "Toggle Case"
  "Intercambiar mayús/minús"

  "Toggle Comment"
  "Comentario de palanca"

  "Toggle case of current character"
  "Caso de la palanca del carácter actual"

  "Toggle comment"
  "Comentario de palanca"

  "Toggle split view mode"
  "Cambiar split modo de vista"

  "Tools"
  "Herramientas"

  "Transform"
  "Transformar"

  "Undo"
  "Deshacer"

  "Unfavorite file"
  "Archivo unfavorite"

  "Unindent"
  "Unindent"

  "Unindent selected text"
  "No sangría de texto seleccionado"

  "Uninstall"
  "Desinstalar"

  "Uninstall plugin"
  "Desinstalar plugin"

  "Unix"
  "Unix"

  "Unlock"
  "Descubrir"

  "Unlock file"
  "Desbloquear archivo"

  "Upper Case"
  "Mayúsculas"

  "User Guide"
  "Guía del usuario"

  "View"
  "Vista"

  "View Base"
  "Ver Base"

  "View Global"
  "Vista Global"

  "View base preferences file"
  "Ver archivo de preferencias de base"

  "View global menu bindings"
  "Ver enlaces de menú global"

  "View user guide"
  "Ver Guía del usuario"

  "Vim Mode"
  "Modo de Vim"

  "Whitespace Backward"
  "Espacio en blanco al revés"

  "Whitespace Forward"
  "Espacio en blanco adelante"

  "Windows"
  "Ventanas"

}

# plugins.tcl
msgcat::mcmset es {

  "Always grant from developer"
  "Siempre conceder contenido del programador"

  "ERROR"
  "ERROR"

  "ERROR:  Plugin name already exists"
  "ERROR: nombre Plugin ya existe"

  "ERROR:  Plugin name is not valid (only alphanumeric and underscores are allowed)"
  "ERROR: Nombre del Plugin no es válido (sólo caracteres alfanuméricos y guiones están permitidos)"

  "ERROR:  Unable to create plugin directory"
  "ERROR: No se puede crear el directorio de plugins"

  "ERROR:  Unable to write plugin files"
  "ERROR: No se puede escribir archivos de plugin"

  "Enter plugin name"
  "Ingrese nombre del plugin"

  "Grant"
  "Otorgar"

  "Grant permission?"
  "Grant permission?"

  "OK"
  "Aceptar"

  "Plugin Errors"
  "Errores Plugin"

  "Plugin Trust Requested"
  "Plugin de confianza solicitada"

  "Plugin installed"
  "Instalado el plugin"

  "Plugin requires permission to view or modify your system."
  "Plugin requiere permiso para ver o modificar su sistema."

  "Plugin uninstalled"
  "Desinstalar plugin"

  "Plugins successfully reloaded"
  "Plugins recargado con éxito"

  "Reject"
  "Rechazar"

  "Syntax errors found in selected plugins"
  "Los errores de sintaxis encontrados en plugins seleccionados"

}

# search.tcl
msgcat::mcmset es {

  "No files found in specified directories"
  "No hay archivos en directorios especificados"

  "No search results found"
  "No se encontraron resultados búsqueda"

  "Search wrapped to beginning of file"
  "Búsqueda envuelto al principio del archivo"

  "Search wrapped to end of file"
  "Búsqueda envuelto al final del archivo"

  "substitutions done"
  "hecha las sustituciones"

}

# sessions.tcl
msgcat::mcmset es {

  "Save session?"
  "¿Guardar sesión?"

  "Session state will be lost if not saved"
  "El estado de sesión se perderá si no se guardan"

}

# sidebar.tcl
msgcat::mcmset es {

  "Add Parent Directory"
  "Añadir Parent Directory"

  "Close Directory Files"
  "Cerrar archivos de directorio"

  "Copy Pathname"
  "Copiar ruta de acceso"

  "Delete directories?"
  "¿Borrar directorios?"

  "Delete directory?"
  "Eliminar directorio?"

  "Delete file?"
  "Eliminar archivo"

  "Delete files?"
  "Eliminar archivos"

  "Directory Name:"
  "nombre de guía"

  "Folder Name:"
  "Nombre de la carpeta:"

  "Image displayed in sidebar to indicate that a file is currently opened in an editing buffer."
  "Imagen que se muestra en la barra lateral para indicar que un archivo está actualmente abierto en un buffer de edición."

  "Make Current Working Directory"
  "Haga directorio de trabajo actual"

  "New Directory"
  "Nuevo directorio"

  "New File From Template"
  "Nuevo archivo de plantilla"

  "Open Directory Files"
  "Abrir archivos Directorio"

  "Refresh Directory Files"
  "Actualizar los archivos de directorio"

  "Remove Parent from Sidebar"
  "Retire los Padres de Sidebar"

  "Remove from Sidebar"
  "Eliminar de la barra lateral"

  "Show Difference"
  "Mostrar diferencia"

}

# snippets.tcl
msgcat::mcmset es {

  "Snippet: *"
  "Fragmento: *"

}

# syntax.tcl
msgcat::mcmset es {

  "Syntax error in syntax file"
  "Error de sintaxis en el archivo de sintaxis"

}

# templates.tcl
msgcat::mcmset es {

  "Delete template?"
  "Eliminar plantilla"

  "Template"
  "Plantilla"

  "Template Name"
  "Nombre de la plantilla"

  "deleted"
  "Eliminado"

  "saved"
  "guardado"

  "will be permanently deleted"
  "se eliminará permanentemente"

}

# theme.tcl
msgcat::mcmset es {

  "Background (trough) color used in the sidebar scrollbar."
  "Antecedentes (valle) de color utilizado en la barra de desplazamiento de la barra lateral."

  "Background (trough) color used in the text scrollbars."
  "Antecedentes (valle) de color utilizado en las barras de desplazamiento de texto."

  "Background color displayed in embedded language code."
  "Fondo de color que se muestra en el código de lenguaje integrado."

  "Background color for all sidebar items that are not selected."
  "Color de fondo para todos los elementos de la barra lateral que no están seleccionados."

  "Background color for all sidebar items that are selected."
  "Color de fondo para todos los elementos de la barra lateral que se seleccionan."

  "Background color in difference viewer that shows added lines."
  "El color de fondo en el visor de la diferencia que muestra líneas añadidas."

  "Background color in difference viewer that shows deleted lines."
  "El color de fondo en el visor de la diferencia que muestra líneas borrados."

  "Background color of insertion cursor and background marker colors."
  "Color de fondo del cursor de inserción y el fondo de marcadores colores."

  "Background color of the editing buffer."
  "Color de fondo del buffer de edición."

  "Background color to display when a button-like ttk widget is pressed."
  "Color de fondo para mostrar cuando se pulsa un widget ttk forma de botón."

  "Background color to use for selected text."
  "El color de fondo que se utilizará para el texto seleccionado."

  "Background color used for all other tabs that are not the current/active tab in the tabbar."
  "El color de fondo se utiliza para todas las otras fichas que no son la ficha actual / activo en la barra de pestañas."

  "Background color used for the current/active menu item."
  "Color de fondo utilizado para el elemento de menú actual / activo."

  "Background color used for the current/active tab in the tabbar."
  "Color de fondo utilizado para la ficha actual / activo en la barra de pestañas."

  "Background color used in highlighted text."
  "Color de fondo utilizado en el texto resaltado."

  "Background color used in menus."
  "Color de fondo utilizado en los menús."

  "Background color used in the tabbar area."
  "Color de fondo utilizado en el área de barra de pestañas."

  "Color of border drawn around active editing buffer."
  "El color de la frontera dibujada alrededor de buffer de edición activa."

  "Color of ttk entry widget text border when the entry has keyboard focus."
  "El color de la entrada ttk texto del widget frontera cuando la entrada tiene el foco del teclado."

  "Color used to draw the warning width line in the editing buffer (as well as the line separating the gutter from the editing buffer)."
  "Color utilizado para dibujar la línea de ancho de advertencia en el buffer de edición (así como la línea que separa la cuneta de la memoria intermedia de edición)."

  "Default 'darkcolor' for all ttk widgets."
  "Default 'darkcolor' para todos los widgets ttk."

  "Default background color to use for all ttk widgets that are in a disabled state."
  "Color de fondo por defecto que se utilizará para todos los widgets ttk que se encuentran en un estado deshabilitado."

  "Default background color to use for all ttk widgets when the mouse cursor hovers over the widget."
  "Color de fondo por defecto que se utilizará para todos los widgets ttk cuando el cursor del ratón sobre el widget."

  "Default background color to use for all ttk widgets."
  "Color de fondo por defecto que se utilizará para todos los widgets ttk."

  "Default border color for all ttk widgets."
  "Color del borde por defecto para todos los widgets ttk."

  "Default color for non-syntax highlighted text."
  "El color del defecto por falta de sintaxis resaltado de texto."

  "Default foreground text color to use for all ttk widgets that are in a disabled state."
  "Por defecto primer plano el color del texto que se utilizará para todos los widgets ttk que se encuentran en un estado deshabilitado."

  "Default foreground text color to use for all ttk widgets."
  "Por defecto primer plano el color del texto que se utilizará para todos los widgets ttk."

  "Determines the number of grips strips to display in the grip area between resizable panes."
  "Determina el número de apretones de tiras que se mostrará en la zona de agarre entre los paneles de tamaño variable."

  "Determines the thickness of the grip area between resizable panes."
  "Determina el espesor de la zona de agarre entre los paneles de tamaño variable."

  "ERROR:  Unable to read"
  "ERROR: No se puede leer"

  "Foreground (slider) color used in the sidebar scrollbar."
  "Primer Plano (slider) de color utilizado en la barra de desplazamiento de la barra lateral."

  "Foreground (slider) color used in the text scrollbars."
  "Primer Plano (slider) de color utilizado en las barras de desplazamiento de texto."

  "Foreground color used in menu items with checks or buttons."
  "Color de primer plano utilizado en elementos de menú con botones o controles."

  "Foreground text color for strings."
  "Color del texto primer plano de cuerdas."

  "Foreground text color to use for all miscellaneous1 labeled text."
  "Color del texto primer plano de usar para todo el texto miscellaneous1 etiquetado."

  "Foreground text color to use for all miscellaneous2 labeled text."
  "Color del texto primer plano de usar para todo el texto miscellaneous2 etiquetado."

  "Foreground text color to use for all miscellaneous3 labeled text."
  "Color del texto primer plano de usar para todo el texto miscellaneous3 etiquetado."

  "Foreground text color to use for comments."
  "Color del texto primer plano que se utilizará para los comentarios."

  "Foreground text color to use for displaying line numbers."
  "Color del texto primer plano que se utilizará para mostrar los números de línea."

  "Foreground text color to use for displaying numbers."
  "Color del texto primer plano a utilizar para la visualización de los números."

  "Foreground text color to use for language-specific keywords."
  "Color del texto primer plano a utilizar para palabras clave específicas del idioma."

  "Foreground text color to use for language-specific punctuation."
  "Color del texto primer plano a utilizar para puntuacion específica del idioma."

  "Foreground text color to use for meta syntax."
  "Color del texto primer plano que se utilizará para la sintaxis de meta."

  "Foreground text color to use for precompiler syntax."
  "Color del texto primer plano que se utilizará para la sintaxis precompilador."

  "Foreground text color to use for selected text."
  "Color del texto primer plano a utilizar para el texto seleccionado."

  "Foreground text color used for all other tabs that are not the current/active tab in the tabbar."
  "Color de texto de primer plano utilizado para todas las otras fichas que no son la ficha de corriente/activo en el tabbar."

  "Foreground text color used for menus item that are disabled."
  "Primer plano el color del texto utilizado para los menús elemento que son discapacitados."

  "Foreground text color used for the current/active menu item."
  "Primer plano el color del texto utilizado para el elemento de menú actual / activo."

  "Foreground text color used for the current/active tab in the tabbar."
  "Color de texto de primer plano utilizado para la ficha de corriente/activo en el tabbar."

  "Foreground text color used in menus."
  "Primer plano el color del texto utilizado en los menús."

  "Foreground text/image color used in tabbar and tabs."
  "Primer plano el color del texto / imagen utilizada en la barra de pestañas y pestañas."

  "Images"
  "Imágenes"

  "Maximum thickness of the text scrollbar when it is active."
  "El espesor máximo de la barra de desplazamiento de texto cuando está activo."

  "Maximum thickness of the text scrollbars when they are active."
  "El espesor máximo de las barras de desplazamiento de texto cuando están activos."

  "Menu Options"
  "Opciones de Menú"

  "Menu relief value."
  "Valor alivio Menú."

  "Pixel height of the tabbar widget."
  "Altura del pixel del widget barra de pestañas."

  "Relief used in drawing the tabs."
  "Alivio utiliza en la elaboración de las fichas."

  "Relief value of the sidebar area."
  "Valor Alivio de la zona de la barra lateral."

  "Sidebar Options"
  "Opciones de Columna"

  "Sidebar Scrollbar Options"
  "Sidebar Opciones Scrollbar"

  "Specifies the color to display around the sidebar when the sidebar does not have the focus."
  "Especifica el color para mostrar alrededor de la barra lateral cuando la barra lateral no tiene el foco."

  "Specifies the color to display around the sidebar when the sidebar has the focus."
  "Especifica el color para mostrar alrededor de la barra lateral cuando la barra lateral tiene el foco."

  "Specifies the default background color to use for text that is selected in a standard ttk widget (this does not include the editing buffer)."
  "Especifica el color de fondo predeterminado para el texto que se selecciona en un widget ttk estándar (esto no incluye el buffer de edición)."

  "Specifies the default foreground text color to use for text that is selected in a standard ttk widget (this does not include the editing buffer)."
  "Especifica el valor por defecto el color del texto de primer plano a utilizar para el texto que se selecciona en un widget ttk estándar (esto no incluye el buffer de edición)."

  "Specifies the default relief to use when drawing ttk widgets."
  "Especifica el alivio defecto para utilizar en la elaboración de los widgets ttk."

  "Specifies the disclosure image style to use in the sidebar."
  "Especifica el estilo de la imagen de divulgación para su uso en la barra lateral."

  "Specifies the pixel thickness of the highlight line."
  "Especifica el grosor de píxeles de la línea culminante."

  "Syntax Colors"
  "Sintaxis Colores"

  "Tab Options"
  "Opciones de la ficha"

  "Text Scrollbar Options"
  "Texto Opciones Scrollbar"

  "Text color for all sidebar items that are not selected."
  "Color de texto para todos los elementos de la barra lateral que no están seleccionados."

  "Text color for all sidebar items that are selected."
  "Color de texto para todos los elementos de la barra lateral que se seleccionan."

  "ttk Widget Colors"
  "TTK Widget Colores"

}

# themer.tcl
msgcat::mcmset es {

  "   Show All"
  "Mostrar todo"

  "   Show Category"
  "Mostrar Categoría"

  "   Show Color"
  "Ver color de Fondo"

  "   Show Selected Option"
  "Mostrar opción seleccionada"

  "   Show Selected Value"
  "Mostrar valor seleccionado"

  "Categories"
  "Categorías"

  "Change Base Color"
  "Cambiar color"

  "Choose Theme"
  "Elige un tema"

  "Custom Directory"
  "Directorio personalizada"

  "Custom..."
  "Personalizado..."

  "Delete swatch?"
  "Eliminar muestra?"

  "Description"
  "Descripción"

  "Details"
  "Datos"

  "Done"
  "Hecho"

  "Export"
  "Exportar"

  "GIF Photo"
  "GIF fotos"

  "Import"
  "Importar"

  "Import BMP Data"
  "Importar datos..."

  "Import BMP Mask"
  "Máscara de importación BMP"

  "Import Error"
  "Import Error!"

  "Import Theme File"
  "Importar archivo de tema"

  "Installation Directory"
  "Directorio de instalación"

  "Modifications"
  "Modificaciones"

  "One-Color Bitmap"
  "Bitmap Uno-Color"

  "Preview"
  "Vista previa"

  "Relief: "
  "Alivio"

  "Save As:"
  "Guardar como:"

  "Save theme changes?"
  "Guardar cambios temáticos?"

  "Select Directory"
  "Seleccionar el anuncio"

  "Swatch"
  "proyecto de conservación de los humedales del río Sile"

  "Swatch Colors"
  "Colores Swatch"

  "Table Filters"
  "Tabla Filtros"

  "The current theme has unsaved changes"
  "El tema actual tiene cambios sin guardar"

  "Tree Style: "
  "Estilo del árbol:"

  "Two-Color Bitmap"
  "Bitmap de dos colores"

  "User Directory"
  "Directorio de usuarios"

  "Value"
  "Valor"

  "Value: "
  "Valor:"

}

# themes.tcl
msgcat::mcmset es {

  "Theme"
  "Tema"

  "Theme:*"
  "Tema"

}

# tke.tcl
msgcat::mcmset es {

  "Import TKE theme?"
  "Tema Importación TKE?"

  "Import TextMate theme?"
  "Importar tema TextMate?"

}

# tkedat.tcl
msgcat::mcmset es {

  "Unable to read"
  "No se puede leer la información."

}

# vim.tcl
msgcat::mcmset es {

  "File format unrecognized"
  "Formato de archivo desconocido"

  "Filename directory does not exist"
  "Nombre de archivo directorio no existe"

  "Folding method unrecognized"
  "Método desconocido plegable"

  "Illegal modelines value"
  "Valor de modos ilegales"

  "Number width not a number"
  "Número ancho no es un número"

  "Shiftwidth value is not an integer"
  "Valor especificado tabulación no es un entero"

  "Tabstop value is not an integer"
  "Valor de punto de tabulación no es un entero"

  "Unrecognized vim option"
  "Opción no reconocida vim"

}

# General
msgcat::mcmset es {

  "Cancel"
  "Cancelar"

  "Close"
  "Cerrar"

  "Delete"
  "Eliminar"

  "Duplicate"
  "Duplicar"

  "Favorite"
  "Favorito"

  "File Name:"
  "Nombre del archivo:"

  "Find"
  "Búsqueda"

  "Move to Other Pane"
  "Mover a otro panel"

  "New File"
  "Nuevo archivo"

  "None"
  "Ninguno"

  "Open"
  "Abierto"

  "Rename"
  "Cambiar nombre"

  "Save"
  "Guardar"

  "Save As"
  "Guardar como"

  "Split View"
  "Dividir la vista"

  "Syntax"
  "Sintaxis"

  "Theme Editor"
  "Editor de temas"

  "Unable to write"
  "No se puede escribir"

  "Unfavorite"
  "Unfavorite"

}

