# api.tcl
msgcat::mcmset es {

  "Argument list to api::add_file was not an even key/value pair"
  "Lista de argumentos para api::add_file no era un par aun clave/valor"

  "Argument list to api::add_file was not in the form 'filename [<option> <value>]*'"
  "Lista de argumentos para api::add_file no estaba en la forma 'nombre de archivo [<option> <value>]*'"

  "get_home_directory can only be called within plugin code"
  "get_home_directory sólo se puede llamar al código Plugin"

}

# bgproc.tcl
msgcat::mcmset es {

  "Unable to run system command (%s)"
  "No se puede ejecutar comandos del sistema (%s)"

}

# bindings.tcl
msgcat::mcmset es {

  "Menu Bindings: Edit user menu bindings"
  "Fijaciones Menú: Editar usuarios enlaces del menú"

  "Menu Bindings: Reload menu bindings"
  "Vinculaciones Menú: enlaces del menú Actualizar"

  "Menu Bindings: Use default menu bindings"
  "Vinculaciones Menú: usan enlaces de menú predeterminados"

  "Menu Bindings: View global menu bindings"
  "Vinculaciones Menú: Ver enlaces de menú globales"

}

# gui.tcl
msgcat::mcmset es {

  "Close All Tabs"
  "¿Cerramos todas las pestañas?"

  "Close Other Tab(s)"
  "Cerrar Other Tab(s)"

  "Close Other*"
  "Cerrar Other*"

  "Close Tab"
  "Close Tab"

  "Copyright %d-%d"
  "Derechos Reservados% d-% d"

  "Delete tab?"
  "Eliminar ficha?"

  "Developer:"
  "Desarrollador:"

  "Email:"
  "Correo electrónico:"

  "File attribute (%s) does not exist"
  "Atributo de archivo (%s) no existe"

  "File index is out of range"
  "Índice del archivo está fuera de rango"

  "Find:"
  "Encontrar:"

  "Line: %d, Column: %d"
  "Line: %d, Columna: %d"

  "Line: %d, Column: %d, Total Lines: %d, Total Characters: %d"
  "Línea:% d, columna% d, Líneas totales:% d, Personajes totales:% d"

  "Locked"
  "Bloqueado"

  "Move to Other Pane"
  "Mover a otro panel"

  "Move*"
  "Mover*"

  "Reload file?"
  "Recargar archivo"

  "Replace:"
  "Reemplazar:"

  "Save request"
  "Memorizar encargo"

  "Unable to find current file (tab: %s)"
  "No se puede encontrar el archivo actual (pestaña:% s)"

  "Untitled"
  "Intitulado"

  "Version:"
  "Versión:"

}

# markers.tcl
msgcat::mcmset es {

  "Marker name:"
  "Nombre del marcador:"

}

# menus.tcl
msgcat::mcmset es {

  "                                  Profiling Report Sorted By (%s)"
  "                                    Informe Perfiles Site (%s)"

  "About Tke"
  "Acerca Tke"

  "About tke"
  "Acerca tke"

  "Align cursors"
  "Alinear los cursores"

  "All"
  "Todo"

  "Append next occurrence"
  "Anexar siguiente aparición"

  "Clear All"
  "Limpiar todo"

  "Close All"
  "Cerrar todo"

  "Comment"
  "Comentario"

  "Copy"
  "Copia"

  "Create new..."
  "Crear una nueva ..."

  "Create..."
  "Crear..."

  "Cut"
  "Cortar"

  "Edit"
  "Edición"

  "Edit..."
  "Edición..."

  "FOOBAR"
  "Foo"

  "File"
  "Expediente"

  "Find"
  "Búsqueda"

  "Find and Replace"
  "Buscar y reemplazar"

  "Find in files"
  "Buscar en archivos..."

  "Find marker"
  "Marcador"

  "Find matching pair"
  "Encuentra pares"

  "Format Text"
  "Formato de texto"

  "Goto Last Tab"
  "Goto Última Tab"

  "Goto Next Tab"
  "Ir a la siguiente pestaña"

  "Goto Other Pane"
  "Goto Otro panel"

  "Goto Previous Tab"
  "Ir a la pestaña anterior"

  "Help"
  "Help!"

  "Import TextMate theme..."
  "Importar tema TextMate..."

  "Indent"
  "Indentar"

  "Insert enumeration"
  "Inserte enumeración"

  "Install..."
  "Instalar..."

  "Launcher"
  "Lanzador"

  "Lock"
  "Bloquear"

  "Menu: About tke"
  "Menú: Acerca tke"

  "Menu: Align cursors"
  "Menú: Alinear cursores"

  "Menu: Append next occurrence"
  "Menú: Anexar siguiente aparición"

  "Menu: Close all tabs"
  "¿Cerramos todas las pestañas?"

  "Menu: Close current tab"
  "Menú: Cerrar pestaña actual"

  "Menu: Comment selected text"
  "Menú: Comentario de texto seleccionado"

  "Menu: Copy selected text"
  "Menú: Copia el texto seleccionado"

  "Menu: Create new plugin"
  "Menú: Crear nuevo plugin"

  "Menu: Create new theme"
  "Crear nuevo tema..."

  "Menu: Cut selected text"
  "Menú: Cortar el texto seleccionado"

  "Menu: Disable Vim mode"
  "Menú: Desactive el modo Vim"

  "Menu: Edit Tke theme"
  "Menú: Editar Tke tema"

  "Menu: Enable Vim mode"
  "Menú: Habilitar el modo Vim"

  "Menu: Find"
  "Menú: Buscar"

  "Menu: Find and Replace"
  "Buscar y reemplazar"

  "Menu: Find in files"
  "Menú: Buscar en los archivos"

  "Menu: Find matching character pair"
  "Menú: Encuentra pares de caracteres coincidente"

  "Menu: Find next occurrence"
  "Menú: Buscar la siguiente aparición"

  "Menu: Find previous occurrence"
  "Menú: Buscar aparición anterior"

  "Menu: Goto last tab"
  "Menú: Ir a la última pestaña"

  "Menu: Goto next tab"
  "Menú: Ir a la siguiente pestaña"

  "Menu: Goto other pane"
  "Menú: Ir a otro panel"

  "Menu: Goto previous tab"
  "Menú: Ir a la pestaña anterior"

  "Menu: Hide console"
  "Menú: Ocultar la consola"

  "Menu: Hide sidebar"
  "Menú: Ocultar barra lateral"

  "Menu: Hide status bar"
  "Menú: Ocultar barra de estado"

  "Menu: Import TextMate theme"
  "Menú: Import tema TextMate"

  "Menu: Indent selected text"
  "Menú: sangría del texto seleccionado"

  "Menu: Insert enumeration"
  "Menú: Insertar enumeración"

  "Menu: Install plugin"
  "Menú: Instalar Plugin"

  "Menu: Lock file"
  "Bloqueo de archivos: Menu"

  "Menu: New file"
  "Menú: Nuevo archivo"

  "Menu: Open directory"
  "Menú: Abrir el listín telefónico"

  "Menu: Open file"
  "Menú: Abrir el archivo"

  "Menu: Paste and format text from clipboard"
  "Menú: Pasta y formato de texto desde el portapapeles"

  "Menu: Paste text from clipboard"
  "Pegar texto desde el portapapeles"

  "Menu: Quit application"
  "Menú: Salir de la aplicación"

  "Menu: Redo"
  "Menú: Redo"

  "Menu: Reload all plugins"
  "Menú: Actualizar todos los plugins"

  "Menu: Restart tke"
  "Menú: Reinicie tke"

  "Menu: Save all files"
  "Menú: Guarde todos los archivos"

  "Menu: Save file"
  "Menú: Guardar el archivo"

  "Menu: Save file as"
  "Menú: Guardar archivo como"

  "Menu: Select all occurrences"
  "Menú: seleccione todas las ocurrencias"

  "Menu: Show console"
  "Menú: Mostrar consola"

  "Menu: Show last profiling report"
  "Menú: Mostrar último informe perfiles"

  "Menu: Show sidebar"
  "Menú: Mostrar barra lateral"

  "Menu: Show status bar"
  "Menú: Mostrar barra de estado"

  "Menu: Sort tabs"
  "Menú: Ordenar pestañas"

  "Menu: Start profiling"
  "Menú: perfiles inicio"

  "Menu: Stop profiling"
  "Menú: perfilación"

  "Menu: Toggle split pane"
  "Menú: SplitPane Toggle"

  "Menu: Uncomment selected text"
  "Menú: Elimine el texto seleccionado"

  "Menu: Undo"
  "Menú: Deshacer"

  "Menu: Unindent selected text"
  "Menú: texto seleccionado Unindent"

  "Menu: Uninstall plugin"
  "Menú: Programas Desinstalar"

  "Menu: Unlock file"
  "Desbloquear archivo: Menú"

  "New"
  "Nuevo"

  "Open Directory..."
  "Abra Directorio ..."

  "Open File..."
  "Columna abierta..."

  "Open Recent"
  "Abrir reciente"

  "Paste"
  "Pegar"

  "Paste and Format"
  "Pega y Formato"

  "Plugins"
  "Complemento"

  "Preferences..."
  "Opciones..."

  "Profiling started"
  "Profiling comenzó"

  "Profiling stopped"
  "Profiling detuvo"

  "Quit"
  "Dejar de"

  "Redo"
  "Rehacer"

  "Reload"
  "Reload"

  "Restart tke"
  "Reiniciar tke"

  "Save All"
  "Guardar todo"

  "Save As..."
  "Guardar como ..."

  "Select all occurrences"
  "Seleccione todas las ocurrencias"

  "Select next occurrence"
  "Seleccionar siguiente aparición"

  "Select previous occurrence"
  "Seleccione aparición anterior"

  "Selected"
  "Seleccionado"

  "Set Syntax"
  "Establecer Sintaxis"

  "Show Last Profiling Report"
  "Mostrar último informe Profiling"

  "Show split pane"
  "Mostrar panel de división"

  "Show*Profiling*"
  "Mostrar*Profiling*"

  "Sort Tabs"
  "Sort Tabs"

  "Start Profiling"
  "Comience perfiles"

  "Stop Profiling"
  "Detener perfiles"

  "Tabs"
  "Tablas"

  "Text"
  "Text"

  "Theme Creator"
  "Theme Creator"

  "Tools"
  "Herramientas"

  "Uncomment"
  "Elimine el comentario"

  "Undo"
  "Deshacer"

  "Unindent"
  "Unindent"

  "Uninstall..."
  "desinstalar"

  "Unlock"
  "Descubrir"

  "View"
  "Vista"

  "View Console"
  "Consola"

  "View Sidebar"
  "Vista Sidebar"

  "View Status Bar"
  "Ver - Barra de estado"

  "Vim Mode"
  "Modo de Vim"

}

# plugins.tcl
msgcat::mcmset es {

  "ERROR:  Plugin name is not valid (only alphanumeric and underscores are allowed)"
  "ERROR: Nombre del Plugin no es válido (sólo caracteres alfanuméricos y guiones están permitidos)"

  "ERROR:  Unable to write plugin file"
  "ERROR: No se puede escribir archivo plugin"

  "Enter plugin name"
  "Ingrese nombre del plugin"

  "Plugin %s installed"
  "Plugin %s instalado"

  "Plugin %s uninstalled"
  "Plugin %s desinstalado"

  "Plugin Errors"
  "Errores Plugin"

  "Syntax errors found in selected plugins"
  "Los errores de sintaxis encontrados en plugins seleccionados"

}

# preferences.tcl
msgcat::mcmset es {

  "Preferences: Edit user preferences"
  "Preferencias: Editar las preferencias del usuario"

  "Preferences: Reload preferences"
  "Preferencias: preferencias Actualizar"

  "Preferences: Use default preferences"
  "Preferencias: Utilice las preferencias predeterminadas"

  "Preferences: View global preferences"
  "Preferencias: Ver preferencias globales"

}

# sidebar.tcl
msgcat::mcmset es {

  "Add Parent Directory"
  "Añadir Parent Directory"

  "Close Directory Files"
  "Cerrar archivos de directorio"

  "Delete"
  "Eliminar"

  "Delete directory?"
  "Eliminar directorio?"

  "Delete file?"
  "Eliminar archivo"

  "Duplicate"
  "Duplicar"

  "Make Current Working Directory"
  "Haga directorio de trabajo actual"

  "New Directory"
  "Nuevo directorio"

  "New File"
  "Nuevo archivo"

  "Open"
  "Abierto"

  "Refresh Directory Files"
  "Actualizar los archivos de directorio"

  "Remove Parent from Sidebar"
  "Retire los Padres de Sidebar"

  "Remove from Sidebar"
  "Eliminar de la barra lateral"

  "Rename"
  "Cambiar nombre"

}

# snippets.tcl
msgcat::mcmset es {

  "Snippet: %s: %s"
  "Fragmento: %s: %s"

  "Snippet: *"
  "Fragmento: *"

  "Snippets: Add snippet"
  "Fragmentos: Añadir snippet"

  "Snippets: Reload all snippets"
  "Fragmentos: cargar todos los fragmentos"

}

# syntax.tcl
msgcat::mcmset es {

  "Syntax error in %s.syntax file"
  "Error de sintaxis en el archivo %s.syntax"

  "Syntax:  %s"
  "Sintaxis: %s"

  "Theme:  %s"
  "Tema: %s"

}

# themer.tcl
msgcat::mcmset es {

  "Create"
  "Crear"

  "Create New Theme"
  "Crear nuevo tema..."

  "Create custom"
  "Crear formulario personalizado"

  "ERROR:  Unable to read %s"
  "ERROR: No se puede leer %s"

  "ERROR:  Unable to write %s"
  "ERROR: No se puede escribir %s"

  "Edit theme"
  "Editar tema"

  "Enter theme name"
  "Ingrese nombre del tema"

  "Error:  Theme is not a supported theme"
  "Error: Tema no es un tema con el apoyo"

  "Import"
  "Importar"

  "Import TextMate Theme"
  "Importar TextMate Tema"

  "Name:"
  "Nombre:"

  "OK"
  "OK"

  "Reset"
  "Reajustar"

  "Select theme"
  "Seleccione un tema"

}

# tke.tcl
msgcat::mcmset es {

  "ERROR:  %s"
  "ERROR: %s"

  "Edit theme?"
  "Editar tema?"

  "Import TextMate theme?"
  "Importar tema TextMate?"

}

# tkedat.tcl
msgcat::mcmset es {

  "Unable to open %s for reading"
  "No se puede abrir el archivo %s para lectura."

  "Unable to open %s for writing"
  "No se puede abrir %s para escritura"

}

# General
msgcat::mcmset es {

  "Cancel"
  "Cancelar"

  "Close"
  "Cerrar"

  "Save"
  "Guardar"

  "Save As"
  "Guardar como"

}

