# api.tcl
msgcat::mcmset fr {

  "Argument list to api::add_file was not an even key/value pair"
  "Argument list d'api::add_file n'était pas une paire même clé/valeur"

  "Plugin"
  "Extension"

}

# bgproc.tcl
msgcat::mcmset fr {

  "Unable to run system command"
  "Impossible d'exécuter la commande du système"

}

# diff.tcl
msgcat::mcmset fr {

  "    End: "
  "Fin:"

  "    Start: "
  "Début:"

  "Enter difference command"
  "Entrez la commande difference"

  "Enter starting file"
  "Entrer dans le fichier de départ"

  "Update"
  "Mis à jour"

}

# edit.tcl
msgcat::mcmset fr {

  "File successfully written"
  "Fichier écrit correctement"

  "Filename already exists"
  "Nom de fichier existe déjà"

}

# embed_tke.tcl
msgcat::mcmset fr {

  "Find:"
  "Find:"

  "Replace:"
  "remplacer le point:"

}

# gui.tcl
msgcat::mcmset fr {

  "All"
  "Toutes"

  "Case sensitivity"
  "Sensibilité à la casse"

  "Close All Tabs"
  "Fermer tous les onglets"

  "Close Other Tabs"
  "Fermer les autres onglets"

  "Close Other*"
  "Fermer onglet*"

  "Close Tab"
  "Fermer l'onglet"

  "Column"
  "Colonne"

  "Copyright"
  "Droit d’auteur"

  "Delete tab?"
  "Supprimer onglet?"

  "Developer"
  "Développeur"

  "Email"
  "Email"

  "Error"
  "Erreur"

  "Favorited"
  "Ajouté aux favoris"

  "File already exists.  Use '!' to force an overwrite"
  "Le fichier existe déjà.  Utilisation '!' pour forcer un écrasement"

  "File attribute does not exist"
  "Attribut de fichier n'existe pas"

  "File index is out of range"
  "index du fichier est hors de portée"

  "Image displayed in fill-in forms which closes the form UI.  Used in forms such as search, search/replace, and find in files."
  "Image affichée dans les formes de remplissage-in qui ferme le formulaire UI. Utilisé dans des formes telles que la recherche, recherche / remplacement, et de trouver dans les fichiers."

  "Image used in tab menus to indicate that the file is associated with a difference view."
  "Image utilisée dans les menus de l&#39;onglet pour indiquer que le fichier est associé à une vue de différence."

  "Image used in tab menus to indicate that the file is locked."
  "Image utilisée dans les menus de l&#39;onglet pour indiquer que le fichier est verrouillé."

  "Image used in tab menus to indicate that the file is readonly."
  "Image utilisée dans les menus de l&#39;onglet pour indiquer que le fichier est en lecture seule."

  "Image used in tab to indicate that the tab contains a difference view."
  "Image utilisée dans l&#39;onglet pour indiquer que l&#39;onglet contient une vue de différence."

  "Image used in tab to indicate that the tab's file is readonly."
  "Image utilisée dans l&#39;onglet pour indiquer que le dossier de l&#39;onglet est en lecture seule."

  "Image used in tab to indicate that the tab’s file is locked."
  "Image utilisée dans l&#39;onglet pour indiquer que le dossier de l&#39;onglet est verrouillé."

  "Image used in tab which, when clicked, closes the tab."
  "Image utilisée dans l&#39;onglet qui, lorsqu&#39;on clique dessus, ferme l&#39;onglet."

  "License"
  "Licence"

  "Line"
  "Ligne"

  "Locked"
  "Lock"

  "Move"
  "déménagement"

  "Must be in multicursor mode to insert numbers"
  "Doit être en mode multicursor pour insérer des numéros de"

  "No write permissions.  Use '!' to force write."
  "Aucune autorisation d'écriture.  Utilisation '!' pour forcer l'écriture."

  "Release Type"
  "Type de sortie"

  "Reload file?"
  "Recharger le fichier"

  "Replace"
  "Remplacer"

  "Save request"
  "Enregistrer la demande"

  "Show in Sidebar"
  "Afficher dans la barre latérale"

  "Starting number:"
  "Changer le numéro de page de démarrage :"

  "Tcl/Tk Version"
  "Version de Tcl/Tk"

  "Total Characters"
  "Total des caractères"

  "Total Lines"
  "Total des lignes"

  "Unable to successfully parse number string"
  "Impossible d'analyser correctement la chaîne numérique"

  "Unable to write file"
  "Impossible d'écrire fichier"

  "Version"
  "Version"

}

# markers.tcl
msgcat::mcmset fr {

  "Marker name:"
  "nom de marqueur:"

}

# menus.tcl
msgcat::mcmset fr {

  "About TKE"
  "À propos de TKE"

  "Absolute"
  "Absolu"

  "Align Cursors"
  "Aligner les curseurs"

  "Append Next Occurrence"
  "Ajouter l'Occurrence suivante"

  "Auto-Indent"
  "Indentation automatique"

  "Bubble Down"
  "Des bulles vers le bas"

  "Bubble Up"
  "Bouillonnent"

  "Change Working Directory"
  "Changer le répertoire de travail"

  "Character"
  "Personnage"

  "Check for Update"
  "Vérifier les mises à jour"

  "Classic Mac"
  "Classic Mac"

  "Clear All"
  "Effacer tout"

  "Close All"
  "Tout fermer"

  "Close Current"
  "Fermer la vue en cours"

  "Command"
  "Commande"

  "Command Result"
  "Résultat de la commande"

  "Copy"
  "Copie"

  "Create"
  "Créer"

  "Create at Current Line"
  "Créer à la ligne courante"

  "Current Line"
  "Ligne courante"

  "Current Number"
  "Numéro de page actuel"

  "Current Word"
  "Mot courant"

  "Cursor"
  "curseur"

  "Cursor from Line Start"
  "Curseur du début de la ligne"

  "Cursor to Line End"
  "Curseur à la fin de la ligne"

  "Cut"
  "CUT"

  "Display Text Info"
  "Texte à afficher"

  "Edit"
  "Modification"

  "Edit Language"
  "Modifier la langue"

  "Edit Menu Edit user snippets"
  "Modifier le Menu éditer des extraits de code utilisateur"

  "Edit Menu: Align cursors"
  "Menu Edition : Aligner les curseurs"

  "Edit Menu: Bubble lines down one line"
  "Menu Edition : Lignes bulle vers le bas de ligne"

  "Edit Menu: Bubble lines up one line"
  "Menu Edition : Bulle s'aligne une seule ligne"

  "Edit Menu: Convert case to lower"
  "Menu Edition : Convertir cas d'abaisser"

  "Edit Menu: Convert case to title"
  "Menu Edition : Convertir le cas à titre"

  "Edit Menu: Convert case to upper"
  "Menu Edition : Convertir le cas à tige"

  "Edit Menu: Copy text"
  "Menu Edition : Copier le texte"

  "Edit Menu: Cut text"
  "Menu Edition : Couper le texte"

  "Edit Menu: Delete current line"
  "Menu Edition : Supprimer la ligne courante"

  "Edit Menu: Delete current word"
  "Menu Edition : Supprimer mot courant"

  "Edit Menu: Delete from cursor to end of line"
  "Menu Edition : Supprimez du curseur à la fin de ligne"

  "Edit Menu: Delete from start of line to cursor"
  "Menu Edition : Suppression du début de la ligne jusqu'au curseur"

  "Edit Menu: Delete template"
  "Menu Edition : Modèle Delete"

  "Edit Menu: Delete text between character"
  "Menu Edition : Supprimer le texte entre les caractères"

  "Edit Menu: Delete the current number"
  "Menu Edition : Supprimer le numéro actuel"

  "Edit Menu: Delete the whitespace to left of cursor"
  "Menu Edition : Supprimer les espaces à gauche du curseur"

  "Edit Menu: Delete the whitespace to right of cursor"
  "Menu Edition : Supprimer les espaces à droite du curseur"

  "Edit Menu: Edit language snippets"
  "Menu Edition : Extraits de langue Edit"

  "Edit Menu: Edit session current language preferences"
  "Menu Edition : Modifier les préférences de langue actuel session"

  "Edit Menu: Edit session global preferences"
  "Menu Edition : Modifier les préférences globales session"

  "Edit Menu: Edit template"
  "Menu Edition : Modèle modification"

  "Edit Menu: Edit user current language preferences"
  "Menu Edition : Modifier les préférences de langue actuel utilisateur"

  "Edit Menu: Edit user global preferences"
  "Menu Edition : Modifier les préférences globales de l'utilisateur"

  "Edit Menu: Edit user menu bindings"
  "Menu Edition : Modifier les liaisons de menu utilisateur"

  "Edit Menu: Format indentation for text"
  "Menu Edition : Mise en retrait Format texte"

  "Edit Menu: Indent selected text"
  "Menu Edition : Tiret texte sélectionné"

  "Edit Menu: Insert command result after current line"
  "Menu Edition : Insérer le résultat de la commande après la ligne courante"

  "Edit Menu: Insert file contents after current line"
  "Menu Edition : Insérer le contenu du fichier après la ligne courante"

  "Edit Menu: Insert from clipboard"
  "Menu Edition : Insérer depuis le presse-papiers"

  "Edit Menu: Insert line above current line"
  "Menu Edition : Insérer la ligne située au-dessus de la ligne courante"

  "Edit Menu: Insert line below current line"
  "Menu Edition : Insérer la ligne située au-dessous de la ligne courante"

  "Edit Menu: Insert snippet"
  "Menu Edition : Extrait d'insérer"

  "Edit Menu: Join lines"
  "Menu Edition : Lignes de jointure"

  "Edit Menu: Move cursor to bottom of screen"
  "Menu Edition : Déplacez le curseur vers le bas de l'écran"

  "Edit Menu: Move cursor to end of current line"
  "Menu Edition : Déplacez le curseur à la fin de la ligne courante"

  "Edit Menu: Move cursor to first line"
  "Menu Edition : Déplacez le curseur à la première ligne"

  "Edit Menu: Move cursor to last line"
  "Menu Edition : Déplacez le curseur à la dernière ligne"

  "Edit Menu: Move cursor to middle of screen"
  "Menu Edition : Déplacer le curseur au milieu de l'écran"

  "Edit Menu: Move cursor to next page"
  "Menu Edition : Déplacez le curseur sur la page suivante"

  "Edit Menu: Move cursor to next word"
  "Menu Edition : Déplacer le curseur au mot suivant"

  "Edit Menu: Move cursor to previous page"
  "Menu Edition : Déplacez le curseur à la page précédente"

  "Edit Menu: Move cursor to previous word"
  "Menu Edition : Déplacer le curseur au mot précédent"

  "Edit Menu: Move cursor to start of current line"
  "Menu Edition : Déplacer le curseur au début de la ligne courante"

  "Edit Menu: Move cursor to top of screen"
  "Menu Edition : Déplacez le curseur en haut de l'écran"

  "Edit Menu: Move multicursors down one line"
  "Menu Edition : Descendre une seule ligne, multicursors"

  "Edit Menu: Move multicursors left one line"
  "Menu Edition : Déplacer multicursors gauche monotube"

  "Edit Menu: Move multicursors right one line"
  "Menu Edition : Move multicursors droit monotube"

  "Edit Menu: Move multicursors up one line"
  "Menu Edition : Déplacer multicursors une ligne"

  "Edit Menu: Paste and format text from clipboard"
  "Menu Edition : Pâte et format texte du presse-papiers"

  "Edit Menu: Paste text from clipboard"
  "Menu Edition : Coller le texte du presse-papiers"

  "Edit Menu: Redo"
  "Menu Edition : refaire"

  "Edit Menu: Reload snippets"
  "Menu Edition : Extraits de Reload"

  "Edit Menu: Reload template information"
  "Menu Edition : Recharger les informations de modèle"

  "Edit Menu: Replace line with script"
  "Menu Edition : Remplacer la ligne par script"

  "Edit Menu: Select all text"
  "Menu Edition : Sélectionnez tout le texte"

  "Edit Menu: Set indent mode to IND"
  "Menu Edition : La valeur mode tiret IND"

  "Edit Menu: Set indent mode to IND+"
  "Menu Edition : Paramétrage mode tiret IND +"

  "Edit Menu: Set indent mode to OFF"
  "Menu Edition : Définir tiret mode OFF"

  "Edit Menu: Set user bindings to global bindings"
  "Menu Edition : Définir des liaisons de l'utilisateur aux liaisons mondiales"

  "Edit Menu: Set user preferences to global preferences"
  "Menu Edition : Définir les préférences utilisateur de préférences globales"

  "Edit Menu: Toggle case of current character"
  "Menu Edition : Activer/désactiver le cas du caractère courant"

  "Edit Menu: Toggle comment"
  "Menu Edition : Commentaire activer/désactiver"

  "Edit Menu: Undo"
  "Menu Edition : annuler"

  "Edit Menu: Unindent selected text"
  "Menu Edition : Unindent texte sélectionné"

  "Edit Menu: View base preferences file"
  "Menu Edition : Fichier de préférences de base de vue"

  "Edit Menu: View global menu bindings"
  "Menu Edition : Liaisons de menu global View"

  "Edit Session - Global"
  "Edit Session - Global"

  "Edit Session - Language"
  "Edit Session - langue"

  "Edit User"
  "Modifier l'Utilisateur"

  "Edit User - Global"
  "Modifier utilisateur - Global"

  "Edit User - Language"
  "Modifier utilisateur - langue"

  "Enumeration"
  "énumération"

  "File"
  "Fichier"

  "File Contents"
  "contenu du fichier"

  "File Menu: Change working directory"
  "Menu fichier : Changer le répertoire de travail"

  "File Menu: Close all tabs"
  "Menu fichier : Fermer tous les onglets"

  "File Menu: Close current tab"
  "Menu fichier : Fermer l'onglet courant"

  "File Menu: Delete current file"
  "Menu fichier : Supprimer le fichier en cours"

  "File Menu: Duplicate current file"
  "Menu fichier : Dupliquer le fichier actuel"

  "File Menu: Favorite file"
  "Menu fichier : Fichier de favoris"

  "File Menu: Lock file"
  "Menu fichier : Fichier de verrouillage"

  "File Menu: New file"
  "Menu fichier : Nouveau fichier"

  "File Menu: New file from template"
  "Menu fichier : Le nouveau fichier de modèle"

  "File Menu: New window"
  "Menu fichier : Nouvelle fenêtre"

  "File Menu: Open Favorite"
  "Menu fichier : Ouvert favori"

  "File Menu: Open Recent"
  "Fichier Récemment ouvert(s)"

  "File Menu: Open directory"
  "Menu fichier : Open directory"

  "File Menu: Open file"
  "Menu fichier : Ouvrir le fichier"

  "File Menu: Quit application"
  "Menu fichier : Quitter application"

  "File Menu: Rename current file"
  "Menu fichier : Renommer le fichier en cours"

  "File Menu: Reopen current file"
  "Menu fichier : Rouvrir le dossier actuel"

  "File Menu: Save all files"
  "Menu fichier : Enregistrer tous les fichiers"

  "File Menu: Save file"
  "Menu fichier : Enregistrer le fichier"

  "File Menu: Save file as"
  "Menu fichier : Enregistrez le fichier sous"

  "File Menu: Save file as template"
  "Menu fichier : Enregistrer le fichier en tant que modèle"

  "File Menu: Save selected lines"
  "Menu fichier : Enregistrer les lignes sélectionnées"

  "File Menu: Set current file line ending to CR for Classic Mac"
  "Menu fichier : Valeur actuelle ligne de fichier se terminant à CR pour Mac Classic"

  "File Menu: Set current file line ending to CRLF for Windows"
  "Menu fichier : Set actuel fichier fin de ligne CRLF pour Windows"

  "File Menu: Set current file line ending to LF for Unix"
  "Menu fichier : Valeur actuelle ligne de fichier se terminant à LF pour Unix"

  "File Menu: Show file difference"
  "Menu fichier : Voir la différence de fichier"

  "File Menu: Unfavorite file"
  "Menu fichier : Fichier Unfavorite"

  "File Menu: Unlock file"
  "Menu fichier : Déverrouiller le fichier"

  "Find In Files"
  "Rechercher dans les fichiers"

  "Find Matching Pair"
  "Trouver la paire de jumelage"

  "Find Menu: Append next occurrence"
  "Menu de recherche : Append occurrence suivante"

  "Find Menu: Create marker at current line"
  "Menu de recherche : Créer un marqueur à la ligne courante"

  "Find Menu: Find"
  "Trouver le Menu : trouver"

  "Find Menu: Find and Replace"
  "Menu de recherche : Rechercher et remplacer"

  "Find Menu: Find in files"
  "Menu de recherche : Rechercher dans les fichiers"

  "Find Menu: Find matching character pair"
  "Menu de recherche : Trouver la paire de caractères correspondante"

  "Find Menu: Find next occurrence"
  "Menu de recherche : Trouver la prochaine occurrence"

  "Find Menu: Find previous occurrence"
  "Menu de recherche : Trouver occurrence précédente"

  "Find Menu: Goto next difference"
  "Menu recherche : Différence suivante Goto"

  "Find Menu: Goto previous difference"
  "Menu recherche : Différence précédente Goto"

  "Find Menu: Jump backward"
  "Menu de recherche : Saut en arrière"

  "Find Menu: Jump forward"
  "Menu de recherche : Bond en avant"

  "Find Menu: Jump to line"
  "Menu de recherche : Saut de ligne"

  "Find Menu: Remove all markers"
  "Menu de recherche : Supprimer tous les marqueurs"

  "Find Menu: Remove marker from current line"
  "Menu de recherche : Enlever marqueur de ligne actuel"

  "Find Menu: Select all occurrences"
  "Menu de recherche : Sélectionner toutes les occurrences"

  "Find Menu: Show selected line change"
  "Menu de recherche : Changement de ligne pour le spectacle sélectionné"

  "Find and Replace"
  "Rechercher et remplacer"

  "Format Text"
  "Format texte"

  "From Clipboard"
  "Correctif pour le presse-papiers"

  "Goto Last Tab"
  "Goto dernier onglet"

  "Goto Next Tab"
  "Aller à l&#39;onglet suivant"

  "Goto Other Pane"
  "Aller Autre volet"

  "Goto Previous Tab"
  "Aller à l&#39;onglet précédent"

  "Help"
  "Aide"

  "Help Menu: About TKE"
  "Menu aide : Sujet TKE"

  "Help Menu: Check for update"
  "Menu aide : Contrôler mise à niveau"

  "Help Menu: Send bug report"
  "Menu aide : Envoyer le rapport de bogue"

  "Help Menu: Send feedback"
  "Menu aide : Envoyer des commentaires"

  "Help Menu: View user guide"
  "Menu aide : Guide de l'utilisateur pour le mode"

  "Hide Console"
  "Cachez Console"

  "Hide Line Numbers"
  "Masquer les numéros de ligne"

  "Hide Marker Map"
  "Masquer la carte repère"

  "Hide Meta Characters"
  "Masquer les méta-caractères"

  "Hide Sidebar"
  "Cacher la barre latérale"

  "Hide Status Bar"
  "Masquer la barre d’état"

  "Hide Tab Bar"
  "Masquer la barre d&#39;onglets"

  "Indent"
  "Retrait"

  "Indent Off"
  "Tiret hors"

  "Indentation"
  "Encoches"

  "Insert"
  "Insérer"

  "Install"
  "Installer"

  "Join Lines"
  "Fusionner les lignes"

  "Jump Backward"
  "Saut vers l'arrière"

  "Jump Forward"
  "Aller de l&#39;avant"

  "Jump To Line"
  "Saut de ligne"

  "Launcher"
  "Lance"

  "Line Above Current"
  "Ligne supérieure courant"

  "Line Below Current"
  "Ligne sous courant"

  "Line Ending"
  "Fin de ligne"

  "Line Number"
  "Numéro de ligne"

  "Line Numbering"
  "Numérotation des lignes"

  "Lock"
  "Verrouiller"

  "Lower Case"
  "lettre du bas de casse"

  "Markers"
  "Marqueur"

  "Menu Bindings"
  "Couverture du menu"

  "Menus: About TKE"
  "Menus: À propos de TKE"

  "Merge Panes"
  "Fusionner les volets"

  "Move Cursors Down"
  "Déplacez les curseurs vers le bas"

  "Move Cursors Left"
  "Déplacez les curseurs de gauche"

  "Move Cursors Right"
  "Déplacez les curseurs droite"

  "Move Cursors Up"
  "Déplacez les curseurs vers le haut"

  "Move to First Line"
  "Déplacer vers la première ligne"

  "Move to Last Line"
  "Passer à la dernière ligne"

  "Move to Line End"
  "Déplacer vers la fin de la ligne"

  "Move to Line Start"
  "Passer à la ligne de départ"

  "Move to Next Page"
  "Aller à Page suivante"

  "Move to Next Word"
  "Passer au mot suivant"

  "Move to Previous Page"
  "Aller à la Page précédente"

  "Move to Previous Word"
  "Passer au mot précédent"

  "Move to Screen Bottom"
  "Déplacer vers le bas de l'écran"

  "Move to Screen Middle"
  "Passer au milieu de l'écran"

  "Move to Screen Top"
  "Déplacer vers le haut de l'écran"

  "New From Template"
  "Nouveau à partir d'un modèle"

  "New Window"
  "Nouvelle fenêtre"

  "Next Difference"
  "Différence suivante"

  "Open Directory"
  "Dossier principal :"

  "Open Favorite"
  "Ouvrir favoris"

  "Open File"
  "Ouvrir le fichier"

  "Open Recent"
  "Ouvrez récente"

  "Paste"
  "Coller"

  "Paste and Format"
  "Colle et Format"

  "Plugins"
  "Plugin"

  "Plugins Menu: Create new plugin"
  "plugins Menu : Créer nouveau plugin"

  "Plugins Menu: Install plugin"
  "plugins Menu : Installer le plugin"

  "Plugins Menu: Reload all plugins"
  "plugins Menu : Recharger tous les plugins"

  "Plugins Menu: Uninstall plugin"
  "plugins Menu : Désinstaller le plugin"

  "Preferences"
  "Préférences"

  "Previous Difference"
  "Différence précédente"

  "Profiling Report Sorted By"
  "Rapport de profilage trié par"

  "Profiling started"
  "Profilage a commencé"

  "Profiling stopped"
  "Profilage arrêté"

  "Quit"
  "Quitter"

  "Redo"
  "Rétablir"

  "Relative"
  "Relative"

  "Reload"
  "Recharger"

  "Remove All Markers"
  "Supprimer tous les marqueurs"

  "Remove From Current Line"
  "Retirer de la ligne courante"

  "Reopen File"
  "Rouvrir le dossier"

  "Replace Line With Script"
  "Remplacer la ligne par Script"

  "Reset User to Base"
  "Réinitialiser utilisateur à Base"

  "Restart TKE"
  "Redémarrez TKE"

  "Run BIST"
  "Exécutez BIST"

  "Save All"
  "Enregistrer tout"

  "Save As Template"
  "Sauvegarder le modèle"

  "Save Current"
  "Enregistrer Actuel:"

  "Save Selection As"
  "Enregistrer la sélection sous"

  "Select All"
  "Tout sélectionner"

  "Select All Occurrences"
  "Sélectionner toutes les Occurrences"

  "Select Next Occurrence"
  "Sélectionnez l'Occurrence suivante"

  "Select Previous Occurrence"
  "Sélectionnez l'Occurrence précédente"

  "Send Bug Report"
  "Envoyer un rapport de bogue."

  "Send Feedback"
  "Envoyer les retours"

  "Sessions"
  "Sessions"

  "Sessions Menu: Close current session"
  "Menu de sessions : Fermer la session en cours"

  "Sessions Menu: Delete session"
  "Menu sessions : Session de Delete"

  "Sessions Menu: Save current session"
  "Menu de sessions : Enregistrer la session actuelle"

  "Sessions Menu: Save sessions as"
  "Menu de sessions : Enregistrer des sessions en tant que"

  "Sessions Menu: Switch to session"
  "Menu de sessions : Passer à la session"

  "Set Syntax"
  "SET Syntaxe"

  "Set Theme"
  "Réglez Thème"

  "Set User to Global"
  "Réglage utilisateur au niveau mondial"

  "Show Console"
  "Afficher la console"

  "Show Diagnostic Logfile"
  "Voir la Diagnostic Logfile"

  "Show File Difference"
  "Voir la différence de fichier"

  "Show Last Profiling Report"
  "Afficher la dernière Profiling Report"

  "Show Line Numbers"
  "Afficher les numéros de ligne"

  "Show Marker Map"
  "Voir la carte de marqueur"

  "Show Meta Characters"
  "Afficher les caractères de Meta"

  "Show Selected Line Change"
  "Montrer le changement de la ligne sélectionnée"

  "Show Sidebar"
  "Afficher la barre latérale"

  "Show Status Bar"
  "Barre d'état"

  "Show Tab Bar"
  "Barre d'onglets"

  "Smart Indent"
  "Smart tiret"

  "Snippet"
  "Snippet"

  "Snippets"
  "Snippets"

  "Sort Tabs"
  "Trier les onglets"

  "Start Profiling"
  "Démarrer le profilage"

  "Stop Profiling"
  "Arrêtez le profilage"

  "Switch To"
  "Passer à ..."

  "Tabs"
  "Tab"

  "Templates"
  "Modèles HTML"

  "Text Between Character"
  "Texte entre les caractères"

  "Text Menu: Insert enumeration"
  "Menu texte : Énumération insérer"

  "Title Case"
  "Casse de titre"

  "Toggle Case"
  "Inverser la casse"

  "Toggle Comment"
  "Commentaire de bascule"

  "Tools"
  "اين الحارس"

  "Tools Menu: Disable Vim mode"
  "Menu Outils : Désactiver le mode Vim"

  "Tools Menu: Enable Vim mode"
  "Menu Outils : Activer le mode Vim"

  "Tools Menu: Restart TKE"
  "Menu Outils : Redémarrage TKE"

  "Tools Menu: Run BIST"
  "Menu Outils : Exécution BIST"

  "Tools Menu: Run theme editor"
  "Menu Outils: Exécutez l&#39;éditeur de thème"

  "Tools Menu: Show diagnostic logfile"
  "Menu Outils : Voir la diagnostic logfile"

  "Tools Menu: Show last profiling report"
  "Menu Outils : Montrer le dernier rapport de profilage"

  "Tools Menu: Start profiling"
  "Menu Outils : Démarrer le profilage"

  "Tools Menu: Stop profiling"
  "Menu Outils : Arrêter le profilage"

  "Transform"
  "Transformer"

  "Undo"
  "Annuler"

  "Unindent"
  "Unindent"

  "Uninstall"
  "Désinstaller"

  "Unix"
  "UNIX"

  "Unlock"
  "Déverrouiller"

  "Upper Case"
  "lettre haut-de-casse"

  "User Guide"
  "Guide de l'utilisateur"

  "View"
  "Affichage"

  "View Base"
  "Vue Base"

  "View Global"
  "Vue globale"

  "View Menu: Absolute line numbering"
  "Menu d'affichage : Numérotation de ligne absolue"

  "View Menu: Display text information"
  "Menu d'affichage : Afficher des informations textuelles"

  "View Menu: Goto last tab"
  ": Vue Goto dernier onglet du Menu"

  "View Menu: Goto next tab"
  ": Vue Goto prochain onglet du Menu"

  "View Menu: Goto other pane"
  "Menu d'affichage : Goto autre volet"

  "View Menu: Goto previous tab"
  "Voir Menu : Goto onglet précédent"

  "View Menu: Hide console"
  "Menu affichage : Console de Hide"

  "View Menu: Hide line numbers"
  "Menu d'affichage : Masquer les numéros de ligne"

  "View Menu: Hide marker map"
  "Menu d'affichage : Masquer carte de marqueur"

  "View Menu: Hide meta characters"
  "Menu d'affichage : Masquer les méta-caractères"

  "View Menu: Hide sidebar"
  "Menu affichage : Sidebar Hide"

  "View Menu: Hide status bar"
  "Menu d'affichage : Masquer la barre d'État"

  "View Menu: Hide tab bar"
  "Menu d'affichage : Masquer la barre d'onglets"

  "View Menu: Merge panes"
  "Menu affichage : Les volets de fusion"

  "View Menu: Move to other pane"
  "Menu d'affichage : Passer à l'autre volet"

  "View Menu: Relative line numbering"
  "Menu d'affichage : Numérotation de ligne Relative"

  "View Menu: Show console"
  "Menu affichage : Console spectacle"

  "View Menu: Show line numbers"
  "Menu d'affichage : Afficher les numéros de ligne"

  "View Menu: Show marker map"
  "Menu d'affichage : Voir la carte de marqueur"

  "View Menu: Show meta characters"
  "Menu d'affichage : Afficher les méta-caractères"

  "View Menu: Show sidebar"
  "AffichageAfficher l'en-tête"

  "View Menu: Show status bar"
  "Menu d'affichage : Afficher la barre d'État"

  "View Menu: Show tab bar"
  "Menu d'affichage : Afficher la barre d'onglet"

  "View Menu: Sort tabs"
  "Menu d'affichage : Onglets de sorte"

  "View Menu: Toggle split view mode"
  "Menu d'affichage : Activer/désactiver split mode d'affichage"

  "Vim Mode"
  "Vim mode"

  "Whitespace Backward"
  "Espace blanc vers l'arrière"

  "Whitespace Forward"
  "Espace blanc avant"

  "Windows"
  "Fenêtres"

}

# plugins.tcl
msgcat::mcmset fr {

  "Always grant from developer"
  "Toujours accorder du développeur"

  "ERROR"
  "ERREUR"

  "ERROR:  Plugin name already exists"
  "ERREUR: Plugin nom existe déjà"

  "ERROR:  Plugin name is not valid (only alphanumeric and underscores are allowed)"
  "ERREUR: Nom du plugin n'est pas valide (uniquement des caractères alphanumériques et des tirets sont autorisés)"

  "ERROR:  Unable to create plugin directory"
  "Erreur: Impossible de créer le répertoire de plug-in"

  "ERROR:  Unable to write plugin files"
  "ERREUR: impossible d&#39;écrire des fichiers plugins"

  "Enter plugin name"
  "Entrez le nom du plug-in"

  "Grant"
  "Grant"

  "Grant permssion?"
  "Grant permssion?"

  "OK"
  "Ok"

  "Plugin Errors"
  "Erreurs de plugins"

  "Plugin Trust Requested"
  "Plugin fiducie demandé"

  "Plugin installed"
  "Extension installé !"

  "Plugin requires permission to view or modify your system."
  "Plugin nécessite l&#39;autorisation d&#39;afficher ou de modifier votre système."

  "Plugin uninstalled"
  "Plugin désinstallé"

  "Plugins successfully reloaded"
  "Plugins rechargé avec succès"

  "Reject"
  "Refuser"

  "Syntax errors found in selected plugins"
  "Les erreurs de syntaxe trouvées dans les plugins sélectionnés"

}

# search.tcl
msgcat::mcmset fr {

  "No files found in specified directories"
  "Aucun fichier trouvé dans les répertoires spécifiés"

  "No search results found"
  "Résultats de la recherche\:"

  "Search wrapped to beginning of file"
  "Rechercher enveloppé au début du fichier"

  "Search wrapped to end of file"
  "Rechercher enveloppé à la fin du fichier"

  "substitutions done"
  "fait des substitutions"

}

# sessions.tcl
msgcat::mcmset fr {

  "Save session?"
  "Enregistrer la session ?"

  "Session state will be lost if not saved"
  "L&#39;état de session sera perdu si pas enregistré"

}

# sidebar.tcl
msgcat::mcmset fr {

  "Add Parent Directory"
  "Dossier parent"

  "Close Directory Files"
  "Fermer Les fichiers Directory"

  "Copy Pathname"
  "Copiez le chemin d'accès"

  "Delete directories?"
  "Supprimez les répertoires ?"

  "Delete directory?"
  "Supprimer répertoire?"

  "Delete file?"
  "Supprimer le fichier"

  "Delete files?"
  "Supprimez les fichiers ?"

  "Directory Name:"
  "Nom du dossier"

  "Folder Name:"
  "Nom du dossier :"

  "Image displayed in sidebar to indicate that a file is currently opened in an editing buffer."
  "Image affichée dans la barre latérale pour indiquer qu&#39;un fichier est actuellement ouvert dans un tampon d&#39;édition."

  "Make Current Working Directory"
  "Assurez-répertoire de travail courant"

  "New Directory"
  "Nouveau répertoire"

  "New File From Template"
  "Nouveau fichier de Template"

  "Open Directory Files"
  "Open Files Annuaire"

  "Refresh Directory Files"
  "Actualiser fichiers d'un répertoire"

  "Remove Parent from Sidebar"
  "Retirer Parent de Sidebar"

  "Remove from Sidebar"
  "Retirer du Sidebar"

  "Show Difference"
  "Voir la différence"

}

# snippets.tcl
msgcat::mcmset fr {

  "Snippet: *"
  "Snippet: *"

}

# syntax.tcl
msgcat::mcmset fr {

  "Syntax"
  "Syntaxe"

  "Syntax error in syntax file"
  "Erreur de syntaxe dans le fichier de syntaxe"

}

# templates.tcl
msgcat::mcmset fr {

  "Template"
  "Modèle"

  "Template Name"
  "Nom du modèle"

  "deleted"
  "Supprimé"

  "saved"
  "Sauvé"

}

# theme.tcl
msgcat::mcmset fr {

  "Background (trough) color used in the sidebar scrollbar."
  "Contexte (creux) couleur utilisée dans la barre de défilement de la barre latérale."

  "Background (trough) color used in the text scrollbars."
  "Contexte (creux) couleur utilisée dans les barres de défilement de texte."

  "Background color for all sidebar items that are not selected."
  "La couleur de fond pour tous les éléments de la barre latérale qui ne sont pas sélectionnés."

  "Background color for all sidebar items that are selected."
  "La couleur de fond pour tous les éléments de la barre latérale qui sont sélectionnés."

  "Background color in difference viewer that shows added lines."
  "La couleur de fond dans la différence spectateur qui montre lignes ajoutées."

  "Background color in difference viewer that shows deleted lines."
  "La couleur de fond dans la différence spectateur qui montre lignes supprimées."

  "Background color of insertion cursor and background marker colors."
  "La couleur de fond du curseur d&#39;insertion et de marqueurs de couleurs de fond."

  "Background color of the editing buffer."
  "La couleur de fond de la mémoire tampon d&#39;édition."

  "Background color to display when a button-like ttk widget is pressed."
  "La couleur de fond à afficher lorsque un widget ttk type bouton est pressé."

  "Background color to use for selected text."
  "Couleur de fond à utiliser pour le texte sélectionné."

  "Background color used for all other tabs that are not the current/active tab in the tabbar."
  "La couleur de fond utilisée pour tous les autres onglets qui ne sont pas l&#39;onglet en cours / actif dans la barre d&#39;onglets."

  "Background color used for the current/active menu item."
  "La couleur de fond utilisée pour l&#39;élément de menu en cours / actif."

  "Background color used for the current/active tab in the tabbar."
  "La couleur de fond utilisée pour l&#39;onglet actif / actif dans la barre d&#39;onglets."

  "Background color used in highlighted text."
  "La couleur de fond utilisée dans le texte en surbrillance."

  "Background color used in menus."
  "La couleur de fond utilisée dans les menus."

  "Background color used in the tabbar area."
  "La couleur de fond utilisée dans la zone de barre d&#39;onglets."

  "Color of border drawn around active editing buffer."
  "Couleur de la frontière tracée autour tampon d&#39;édition active."

  "Color of ttk entry widget text border when the entry has keyboard focus."
  "Couleur de la saisie de texte ttk widget frontière lorsque l&#39;entrée a le focus clavier."

  "Color used to draw the warning width line in the editing buffer (as well as the line separating the gutter from the editing buffer)."
  "Couleur utilisée pour tracer la ligne de largeur d&#39;avertissement dans le tampon d&#39;édition (ainsi que la ligne qui sépare la gouttière de la mémoire tampon d&#39;édition)."

  "Default 'darkcolor' for all ttk widgets."
  "Par défaut &#39;darkcolor »pour tous les widgets TTK."

  "Default background color to use for all ttk widgets that are in a disabled state."
  "Couleur de fond par défaut à utiliser pour tous les widgets TTK qui sont dans un état désactivé."

  "Default background color to use for all ttk widgets when the mouse cursor hovers over the widget."
  "Couleur de fond par défaut à utiliser pour tous les widgets TTK lorsque le curseur de la souris survole le widget."

  "Default background color to use for all ttk widgets."
  "Couleur de fond par défaut à utiliser pour tous les widgets TTK."

  "Default border color for all ttk widgets."
  "Couleur de la bordure par défaut pour tous les widgets TTK."

  "Default color for non-syntax highlighted text."
  "La couleur par défaut pour non-syntaxe texte en surbrillance."

  "Default foreground text color to use for all ttk widgets that are in a disabled state."
  "Par défaut avant-plan la couleur du texte à utiliser pour tous les widgets TTK qui sont dans un état désactivé."

  "Default foreground text color to use for all ttk widgets."
  "Par défaut avant-plan la couleur du texte à utiliser pour tous les widgets TTK."

  "Determines the number of grips strips to display in the grip area between resizable panes."
  "Détermine le nombre de poignées bandes à afficher dans la zone de préhension entre les volets redimensionnables."

  "Determines the thickness of the grip area between resizable panes."
  "Détermine l&#39;épaisseur de la zone de préhension entre les volets redimensionnables."

  "ERROR:  Unable to read"
  "ERREUR : Impossible de lire"

  "Foreground (slider) color used in the sidebar scrollbar."
  "Premier plan (curseur) couleur utilisée dans la barre de défilement de la barre latérale."

  "Foreground (slider) color used in the text scrollbars."
  "Premier plan (curseur) couleur utilisée dans les barres de défilement de texte."

  "Foreground color used in menu items with checks or buttons."
  "Couleur de premier plan utilisée dans les menus des contrôles ou des boutons."

  "Foreground text color for strings."
  "Premier plan couleur du texte pour les chaînes."

  "Foreground text color to use for all miscellaneous1 labeled text."
  "Premier plan couleur du texte à utiliser pour tous miscellaneous1 marqué texte."

  "Foreground text color to use for all miscellaneous2 labeled text."
  "Premier plan couleur du texte à utiliser pour tous miscellaneous2 marqué texte."

  "Foreground text color to use for all miscellaneous3 labeled text."
  "Premier plan couleur du texte à utiliser pour tous miscellaneous3 marqué texte."

  "Foreground text color to use for comments."
  "Couleur de premier plan de texte à utiliser pour les commentaires."

  "Foreground text color to use for displaying line numbers."
  "Couleur de premier plan de texte à utiliser pour l&#39;affichage des numéros de ligne."

  "Foreground text color to use for displaying numbers."
  "Premier plan couleur du texte à utiliser pour l&#39;affichage des nombres."

  "Foreground text color to use for language-specific keywords."
  "Couleur de premier plan de texte à utiliser pour les mots clés spécifiques à la langue."

  "Foreground text color to use for language-specific punctuation."
  "Couleur de premier plan de texte à utiliser pour la ponctuation spécifique à la langue."

  "Foreground text color to use for meta syntax."
  "Couleur de premier plan de texte à utiliser pour la syntaxe méta."

  "Foreground text color to use for precompiler syntax."
  "Couleur de premier plan de texte à utiliser pour la syntaxe précompilateur."

  "Foreground text color to use for selected text."
  "Couleur de premier plan de texte à utiliser pour le texte sélectionné."

  "Foreground text color used for all other tabs that are not the current/active tab in the tabbar."
  "Couleur du texte de premier plan utilisé pour tous les autres onglets qui ne sont pas l'onglet courant/actif dans le tabbar."

  "Foreground text color used for menus item that are disabled."
  "Premier plan couleur du texte utilisé pour les menus poste qui sont handicapés."

  "Foreground text color used for the current/active menu item."
  "Premier plan couleur du texte utilisée pour l&#39;élément de menu en cours / actif."

  "Foreground text color used for the current/active tab in the tabbar."
  "Couleur du texte de premier plan utilisé pour l'onglet courant/actif dans le tabbar."

  "Foreground text color used in menus."
  "Premier plan couleur du texte utilisée dans les menus."

  "Foreground text/image color used in tabbar and tabs."
  "Couleur de premier plan du texte / image utilisée dans barre d&#39;onglets et les onglets."

  "Images"
  "Images"

  "Maximum thickness of the text scrollbar when it is active."
  "Épaisseur maximale de la barre de défilement de texte quand il est actif."

  "Maximum thickness of the text scrollbars when they are active."
  "L&#39;épaisseur maximale des barres de défilement de texte quand ils sont actifs."

  "Menu Options"
  "Options du menu"

  "Menu relief value."
  "La valeur de l&#39;allégement de Menu."

  "Pixel height of the tabbar widget."
  "Hauteur de Pixel du widget de barre d&#39;onglets."

  "Relief used in drawing the tabs."
  "Relief utilisé dans l&#39;élaboration des onglets."

  "Relief value of the sidebar area."
  "Valeur de secours de la zone de la barre latérale."

  "Sidebar Options"
  "options du menu"

  "Sidebar Scrollbar Options"
  "Sidebar Options de barre de défilement"

  "Specifies the color to display around the sidebar when the sidebar does not have the focus."
  "Indique la couleur pour afficher autour de la barre latérale lorsque la barre latérale n&#39;a pas le focus."

  "Specifies the color to display around the sidebar when the sidebar has the focus."
  "Indique la couleur pour afficher autour de la barre latérale lorsque la barre latérale a le focus."

  "Specifies the default background color to use for text that is selected in a standard ttk widget (this does not include the editing buffer)."
  "Indique la couleur de fond par défaut à utiliser pour le texte qui est sélectionné dans un widget ttk standard (cela ne comprend pas le tampon d&#39;édition)."

  "Specifies the default foreground text color to use for text that is selected in a standard ttk widget (this does not include the editing buffer)."
  "Indique la couleur du texte de l&#39;avant-plan par défaut à utiliser pour le texte qui est sélectionné dans un widget ttk standard (cela ne comprend pas le tampon d&#39;édition)."

  "Specifies the default relief to use when drawing ttk widgets."
  "Indique le relief par défaut à utiliser lors de l&#39;élaboration des widgets TTK."

  "Specifies the disclosure image style to use in the sidebar."
  "Indique la divulgation image de style à utiliser dans la barre latérale."

  "Specifies the pixel thickness of the highlight line."
  "Indique l&#39;épaisseur de pixel de la ligne de surbrillance."

  "Syntax Colors"
  "Syntaxe Couleurs"

  "Tab Options"
  "Options de l&#39;onglet"

  "Text Scrollbar Options"
  "Options de texte Barre de défilement"

  "Text color for all sidebar items that are not selected."
  "Couleur du texte pour tous les éléments de la barre latérale qui ne sont pas sélectionnés."

  "Text color for all sidebar items that are selected."
  "Couleur du texte pour tous les éléments de la barre latérale qui sont sélectionnés."

  "ttk Widget Colors"
  "Couleurs du widget"

}

# themer.tcl
msgcat::mcmset fr {

  "   Show All"
  "Toutes les préstations"

  "   Show Category"
  "Afficher Catégorie"

  "   Show Color"
  "Afficher la couleur"

  "   Show Selected Option"
  "Option choisie"

  "   Show Selected Value"
  "Valeur sélectionnée"

  "Categories"
  "Jobs"

  "Change Base Color"
  "Changer la couleur"

  "Choose Theme"
  "Choisir un thème"

  "Custom Directory"
  "Répertoire personnalisé"

  "Custom..."
  "Personnalisé"

  "Delete swatch?"
  "Supprimer Swatch?"

  "Description"
  "Description"

  "Details"
  "Détails"

  "Done"
  "Effectué"

  "Export"
  "Exporter"

  "GIF Photo"
  "GIF photo"

  "Import"
  "Importer"

  "Import BMP Data"
  "Importer les données"

  "Import BMP Mask"
  "Importer BMP Masque"

  "Import Error"
  "Erreur à l'importation"

  "Import Theme File"
  "Thème Importer un fichier"

  "Installation Directory"
  "répertoire d'installation"

  "Modifications"
  "Modifications"

  "One-Color Bitmap"
  "Bitmap une couleur"

  "Preview"
  "Aperçu"

  "Relief: "
  "Relief"

  "Save As:"
  "Enregistrer sous :"

  "Save theme changes?"
  "Enregistrer les modifications de thème?"

  "Select Directory"
  "Sélectionner un répertoire"

  "Swatch"
  "Swatch"

  "Swatch Colors"
  "Couleurs Swatch"

  "Table Filters"
  "Tableau Filtres"

  "The current theme has unsaved changes"
  "Le thème actuel des modifications non enregistrées"

  "Tree Style: "
  "Style Arbre:"

  "Two-Color Bitmap"
  "Bitmap Deux-Color"

  "User Directory"
  "Répertoire d&apos;utilisateur"

  "Value"
  "Valeur"

  "Value: "
  "Valeur :"

}

# themes.tcl
msgcat::mcmset fr {

  "Theme"
  "Thème"

  "Theme:*"
  "Thème"

}

# tke.tcl
msgcat::mcmset fr {

  "Import TKE theme?"
  "Importer TKE thème?"

  "Import TextMate theme?"
  "Importer thème de TextMate?"

}

# tkedat.tcl
msgcat::mcmset fr {

  "Unable to read"
  "Impossible de lire le fichier."

}

# vim.tcl
msgcat::mcmset fr {

  "File format unrecognized"
  "Format de fichier non reconnu"

  "Filename directory does not exist"
  "Nom du fichier répertoire n'existe pas"

  "Illegal modelines value"
  "Valeur des modelines illégale"

  "Shiftwidth value is not an integer"
  "Valeur n’est pas un nombre entier."

  "Tabstop value is not an integer"
  "Valeur n’est pas un nombre entier."

}

# General
msgcat::mcmset fr {

  "Cancel"
  "Résilier"

  "Close"
  "Fermer"

  "Delete"
  "Supprimer"

  "Duplicate"
  "Dupliquer"

  "Favorite"
  "Favori"

  "File Name:"
  "Nom du fichier :"

  "Find"
  "Trouvez"

  "Move to Other Pane"
  "Déplacer vers d'autres Pane"

  "New File"
  "Nouveau fichier"

  "None"
  "Aucun"

  "Open"
  "Ouvrir"

  "Rename"
  "Renommer"

  "Save"
  "Enregistrer"

  "Save As"
  "Enregistrer sous"

  "Split View"
  "Scinder la vue"

  "Theme Editor"
  "éditeur de thèmes"

  "Unable to write"
  "Impossible d'écrire fichier"

  "Unfavorite"
  "Unfavorite"

}

