# api.tcl
msgcat::mcmset fr {

  "Argument list to api::add_file was not an even key/value pair"
  "Argument list d'api::add_file n'était pas une paire même clé/valeur"

}

# bgproc.tcl
msgcat::mcmset fr {

  "Unable to run system command (%s)"
  "Impossible d'exécuter la commande du système (%s)"

}

# gui.tcl
msgcat::mcmset fr {

  "%s, Line: %d, Column: %d"
  "% S, ligne% d, colonne% d"

  "Close All Tabs"
  "Fermer tous les onglets"

  "Close Other Tab(s)"
  "Fermer onglet Autre (s)"

  "Close Other*"
  "Fermer onglet*"

  "Close Tab"
  "Fermer l'onglet"

  "Copyright %d-%d"
  "Droits d&#39;auteur% d-% d"

  "Delete tab?"
  "Supprimer onglet?"

  "Developer:"
  "Partenaires:"

  "Email:"
  "Adresse électronique:"

  "Favorited"
  "Ajouté aux favoris"

  "File attribute (%s) does not exist"
  "attribut du fichier (%s) n'existe pas"

  "File index is out of range"
  "index du fichier est hors de portée"

  "Line: %d, Column: %d"
  "Ligne: %d, Colonne: %d"

  "Locked"
  "Lock"

  "Move to Other Pane"
  "Déplacer vers d'autres Pane"

  "Move*"
  "Déplacer*"

  "Reload file?"
  "Recharger le fichier"

  "Save request"
  "Enregistrer la demande"

  "Show in Sidebar"
  "Afficher dans la barre latérale"

  "Total Lines: %d, Total Characters: %d"
  "Nombre de lignes:% d, Nombre de caractères:% d"

  "Unable to find current file (tab: %s)"
  "Impossible de trouver le fichier actuel (onglet:% s)"

  "Untitled"
  "Untitled"

  "Version:"
  "Version:"

}

# markers.tcl
msgcat::mcmset fr {

  "Marker name:"
  "nom de marqueur:"

}

# menus.tcl
msgcat::mcmset fr {

  "                                  Profiling Report Sorted By (%s)"
  "                              Rapport sur le profilage Trié par (% s)"

  "About TKE"
  "À propos de TKE"

  "Align cursors"
  "Aligner les curseurs"

  "All"
  "Toutes"

  "Append next occurrence"
  "Ajouter occurrence suivante"

  "Check for Update"
  "Vérifier les mises à jour"

  "Clear All"
  "Effacer tout"

  "Close All"
  "Tout fermer"

  "Comment"
  "Remarques"

  "Copy"
  "Copie"

  "Create new..."
  "Créer un nouveau ..."

  "Create..."
  "Créer..."

  "Cut"
  "CUT"

  "Edit"
  "Modification"

  "Edit current"
  "Modifier l'actuelle..."

  "Edit user"
  "Modifier l’utilisateur"

  "Edit..."
  "Modification"

  "File"
  "Fichier"

  "Find"
  "Trouvez"

  "Find and Replace"
  "Rechercher et remplacer"

  "Find in files"
  "Rechercher dans les fichiers"

  "Find marker"
  "Trouver marqueur"

  "Find matching pair"
  "Trouvez paire correspondante"

  "Format Text"
  "Format texte"

  "From Clipboard"
  "Correctif pour le presse-papiers"

  "Goto Last Tab"
  "Goto dernier onglet"

  "Goto Next Tab"
  "Aller à l&#39;onglet suivant"

  "Goto Other Pane"
  "Aller Autre volet"

  "Goto Previous Tab"
  "Aller à l&#39;onglet précédent"

  "Help"
  "Aide"

  "Hide Console"
  "Cachez Console"

  "Hide Sidebar"
  "Cacher la barre latérale"

  "Hide Status Bar"
  "Masquer la barre d’état"

  "Hide Tab Bar"
  "Masquer la barre d&#39;onglets"

  "Import TextMate theme..."
  "Importer thème TextMate..."

  "Indent"
  "Retrait"

  "Insert Text"
  "insertion de texte"

  "Insert enumeration"
  "Insérez énumération"

  "Install..."
  "Installation..."

  "Launcher"
  "Lance"

  "Lock"
  "Verrouiller"

  "Menu Bindings"
  "Couverture du menu"

  "Menu: About TKE"
  "Menu: A propos de TKE"

  "Menu: Align cursors"
  "Menu: Aligner les curseurs"

  "Menu: Append next occurrence"
  "Menu: Ajoute occurrence suivante"

  "Menu: Check for Update"
  "Vérifier les mises à jour"

  "Menu: Close all tabs"
  "Menu: Fermez tous les onglets"

  "Menu: Close current tab"
  "Fermer l'onglet actuel"

  "Menu: Comment selected text"
  "Menu: Commentaire texte sélectionné"

  "Menu: Copy selected text"
  "Menu: copier le texte sélectionné"

  "Menu: Create new plugin"
  "Menu: Créer un nouveau plug-in"

  "Menu: Create new theme"
  "Créer un nouveau thème..."

  "Menu: Cut selected text"
  "Menu: Couper le texte sélectionné"

  "Menu: Disable Vim mode"
  "Menu: Désactiver le mode Vim"

  "Menu: Edit Tke theme"
  "Menu: thème Modifier Tke"

  "Menu: Edit current snippets"
  "Menu: Modifier extraits actuelles"

  "Menu: Edit user menu bindings"
  "fixations du menu utilisateur Edition: Menu"

  "Menu: Edit user preferences"
  "Modification des préférences utilisateur: Menu"

  "Menu: Enable Vim mode"
  "Menu: Activer le mode Vim"

  "Menu: Favorite file"
  "Menu: Fichier favoris"

  "Menu: Find"
  "Menu: Trouvez"

  "Menu: Find and Replace"
  "Rechercher et remplacer"

  "Menu: Find in files"
  "Menu: Trouver des fichiers"

  "Menu: Find matching character pair"
  "Menu: Trouvez paire assortie de caractère"

  "Menu: Find next occurrence"
  "Menu: Trouvez occurrence suivante"

  "Menu: Find previous occurrence"
  "Menu: Trouvez occurrence précédente"

  "Menu: Format all text"
  "Menu: Format tout le texte"

  "Menu: Format selected text"
  "Menu: Format texte sélectionné"

  "Menu: Goto last tab"
  "Menu: dernier onglet Goto"

  "Menu: Goto next tab"
  "Menu: onglet suivant Aller"

  "Menu: Goto other pane"
  "Menu: Goto autre volet"

  "Menu: Goto previous tab"
  "Menu: onglet précédent Goto"

  "Menu: Hide Tab Bar"
  "Menu: Masquer la barre d&#39;onglets"

  "Menu: Hide console"
  "Menu: Masquer console"

  "Menu: Hide sidebar"
  "Menu: Cacher la barre latérale"

  "Menu: Hide status bar"
  "Masquer la barre d’état"

  "Menu: Import TextMate theme"
  "Menu: thème de TextMate d&#39;importation"

  "Menu: Indent selected text"
  "Menu: indent texte sélectionné"

  "Menu: Insert enumeration"
  "Menu: Insérez énumération"

  "Menu: Insert from clipboard"
  "Insérer depuis le presse-papiers"

  "Menu: Insert snippet"
  "Menu: Insérer extrait"

  "Menu: Install plugin"
  "Menu: Installer l&#39;extension"

  "Menu: Lock file"
  "fichier Lock: Menu"

  "Menu: Move to other pane"
  "Menu: Passez à autre volet"

  "Menu: New file"
  "Menu: Nouveau fichier"

  "Menu: Open Favorite"
  "Menu: Open favoris"

  "Menu: Open Recent"
  "Menu: Ouvrir récent"

  "Menu: Open directory"
  "Menu: Ouvert répertoire"

  "Menu: Open file"
  "Menu: ouvrir le fichier"

  "Menu: Paste and format text from clipboard"
  "Menu: Pâte et formater le texte du presse-papiers"

  "Menu: Paste text from clipboard"
  "Coller le texte contenu dans le presse-papier"

  "Menu: Quit application"
  "Menu: application Quit"

  "Menu: Redo"
  "Menu: Rétablir"

  "Menu: Reload all plugins"
  "Menu: Recharger tous les plugins"

  "Menu: Reload current snippets"
  "Menu: Recharger extraits actuelles"

  "Menu: Restart tke"
  "Menu: Redémarrez TKE"

  "Menu: Save all files"
  "Menu: Enregistrez tous les fichiers"

  "Menu: Save file"
  "Menu: Enregistrer le fichier"

  "Menu: Save file as"
  "Menu: Enregistrer sous"

  "Menu: Select all occurrences"
  "Menu: Sélectionner toutes les occurrences"

  "Menu: Select all text"
  "Sélectionner tout le texte"

  "Menu: Set user bindings to global bindings"
  "Menu: Réglez utilisateur liaisons à des liaisons mondiales"

  "Menu: Set user preferences to global preferences"
  "Menu: Définir les préférences utilisateur à des préférences globales"

  "Menu: Show Tab Bar"
  "Menu: Afficher la barre d&#39;onglets"

  "Menu: Show console"
  "Menu: Afficher console"

  "Menu: Show last profiling report"
  "Menu: Afficher le dernier rapport de profilage"

  "Menu: Show sidebar"
  "Menu: Afficher la barre latérale"

  "Menu: Show status bar"
  "Barre d'état"

  "Menu: Sort tabs"
  "Menu: Trier onglets"

  "Menu: Start profiling"
  "Menu: profilage de départ"

  "Menu: Stop profiling"
  "Menu: Arrêtez le profilage"

  "Menu: Toggle split view mode"
  "Menu: Basculer en mode split view"

  "Menu: Uncomment selected text"
  "Menu: Supprimez le texte sélectionné"

  "Menu: Undo"
  "Menu: Annuler"

  "Menu: Unfavorite file"
  "Menu: fichier Unfavorite"

  "Menu: Unindent selected text"
  "Menu: Unindent texte sélectionné"

  "Menu: Uninstall plugin"
  "Menu: plugin Désinstaller"

  "Menu: Unlock file"
  "fichier de déverrouillage: Menu"

  "Menu: View User Guide"
  "Menu: Voir Guide de l&#39;utilisateur"

  "Menu: View global menu bindings"
  "Menu: Voir fixations de menu mondiaux"

  "Menu: View global preferences"
  "Menu: préférences globales Voir"

  "Move to other pane"
  "Déplacer vers un autre volet"

  "New"
  "Nouveau"

  "Open Directory..."
  "Dossier principal..."

  "Open Favorite"
  "Ouvrir favoris"

  "Open File..."
  "Ouvrir un fichier..."

  "Open Recent"
  "Ouvrez récente"

  "Paste"
  "Coller"

  "Paste and Format"
  "Colle et Format"

  "Plugins"
  "Plugin"

  "Preferences"
  "Préférences"

  "Profiling started"
  "Profilage a commencé"

  "Profiling stopped"
  "Profilage arrêté"

  "Quit"
  "Quitter"

  "Redo"
  "Rétablir"

  "Reload"
  "Recharger"

  "Reload current"
  "Recharger courant"

  "Reset user to base"
  "Réinitialiser utilisateur de fonder"

  "Restart tke"
  "Redémarrez TKE"

  "Save All"
  "Enregistrer tout"

  "Save As..."
  "Enregistrer sous..."

  "Select All"
  "Tout sélectionner"

  "Select all occurrences"
  "Sélectionner toutes les occurrences"

  "Select next occurrence"
  "Sélectionnez occurrence suivante"

  "Select previous occurrence"
  "Sélectionnez occurrence précédente"

  "Selected"
  "Sélectionné"

  "Set Syntax"
  "SET Syntaxe"

  "Set Theme"
  "Réglez Thème"

  "Set user to global"
  "Réglez utilisateur mondial"

  "Show Console"
  "Afficher la console"

  "Show Last Profiling Report"
  "Afficher la dernière Profiling Report"

  "Show Sidebar"
  "Afficher la barre latérale"

  "Show Status Bar"
  "Barre d'état"

  "Show Tab Bar"
  "Barre d'onglets"

  "Show*Profiling*"
  "Afficher*Profiling*"

  "Snippet"
  "Snippet"

  "Snippets"
  "Snippets"

  "Sort Tabs"
  "Trier les onglets"

  "Split view"
  "Affichage séparé"

  "Start Profiling"
  "Démarrer le profilage"

  "Stop Profiling"
  "Arrêtez le profilage"

  "Tabs"
  "Tab"

  "Text"
  "Texte"

  "Theme Creator"
  "Theme Creator"

  "Tools"
  "اين الحارس"

  "Uncomment"
  "Supprimez"

  "Undo"
  "Annuler"

  "Unindent"
  "Unindent"

  "Uninstall..."
  "Désinstaller"

  "Unlock"
  "Déverrouiller"

  "User Guide"
  "Guide de l'utilisateur"

  "View"
  "Affichage"

  "View base"
  "Voir la base"

  "View global"
  "Voir mondial"

  "Vim Mode"
  "Vim mode"

}

# plugins.tcl
msgcat::mcmset fr {

  "ERROR:  Plugin name already exists"
  "ERREUR: Plugin nom existe déjà"

  "ERROR:  Plugin name is not valid (only alphanumeric and underscores are allowed)"
  "ERREUR: Nom du plugin n'est pas valide (uniquement des caractères alphanumériques et des tirets sont autorisés)"

  "ERROR:  Unable to create plugin directory"
  "Erreur: Impossible de créer le répertoire de plug-in"

  "ERROR:  Unable to write plugin files"
  "ERREUR: impossible d&#39;écrire des fichiers plugins"

  "Enter plugin name"
  "Entrez le nom du plug-in"

  "Plugin %s installed"
  "Plugin %s installé"

  "Plugin %s uninstalled"
  "Plugin %s désinstallé"

  "Plugin Errors"
  "Erreurs de plugins"

  "Plugins successfully reloaded"
  "Plugins rechargé avec succès"

  "Syntax errors found in selected plugins"
  "Les erreurs de syntaxe trouvées dans les plugins sélectionnés"

}

# sidebar.tcl
msgcat::mcmset fr {

  "Add Parent Directory"
  "Dossier parent"

  "Close Directory Files"
  "Fermer Les fichiers Directory"

  "Delete"
  "Supprimer"

  "Delete directory?"
  "Supprimer répertoire?"

  "Delete file?"
  "Supprimer le fichier"

  "Duplicate"
  "Dupliquer"

  "Make Current Working Directory"
  "Assurez-répertoire de travail courant"

  "New Directory"
  "Nouveau répertoire"

  "New File"
  "Nouveau fichier"

  "Open"
  "Ouvrir"

  "Open Directory Files"
  "Open Files Annuaire"

  "Refresh Directory Files"
  "Actualiser fichiers d'un répertoire"

  "Remove Parent from Sidebar"
  "Retirer Parent de Sidebar"

  "Remove from Sidebar"
  "Retirer du Sidebar"

  "Rename"
  "Renommer"

}

# snippets.tcl
msgcat::mcmset fr {

  "Snippet: %s: %s"
  "Snippet: %s: %s"

  "Snippet: *"
  "Snippet: *"

}

# syntax.tcl
msgcat::mcmset fr {

  "Syntax error in %s.syntax file"
  "Erreur de syntaxe dans le fichier de %s.syntax"

  "Syntax:  %s"
  "Syntaxe: %s"

  "Theme:  %s"
  "Thème: %s"

}

# themer.tcl
msgcat::mcmset fr {

  "Create"
  "Créer..."

  "Create New Theme"
  "Créer un nouveau thème"

  "Create custom"
  "Créer des"

  "ERROR:  Unable to read %s"
  "ERREUR: Impossible de lire %s"

  "ERROR:  Unable to write %s"
  "ERREUR: Impossible d'écrire %s"

  "Edit theme"
  "Modifier thème"

  "Enter theme name"
  "Entrez thème"

  "Error:  Theme is not a supported theme"
  "Erreur: thème n'est pas un thème soutenu"

  "Import"
  "Importer"

  "Import TextMate Theme"
  "Importer TextMate Thème"

  "Name:"
  "Nom:"

  "OK"
  "OK"

  "Reset"
  "Réinitialiser"

  "Select theme"
  "Sélectionner un fichier de thème"

}

# tke.tcl
msgcat::mcmset fr {

  "ERROR:  %s"
  "ERREUR: %s"

  "Edit theme?"
  "Modifier thème?"

  "Import TextMate theme?"
  "Importer thème de TextMate?"

}

# tkedat.tcl
msgcat::mcmset fr {

  "Unable to open %s for reading"
  "Impossible d'ouvrir %s pour le lire."

  "Unable to open %s for writing"
  "Impossible d'ouvrir %s en écriture"

}

# General
msgcat::mcmset fr {

  "Cancel"
  "Résilier"

  "Close"
  "Fermer"

  "Favorite"
  "Favori"

  "Find:"
  "Find:"

  "Replace:"
  "remplacer le point:"

  "Save"
  "Enregistrer"

  "Save As"
  "Enregistrer sous"

  "Unfavorite"
  "Unfavorite"

}

