# api.tcl
msgcat::mcmset he {

  "Argument list to api::add_file was not an even key/value pair"
  "רשימת כדי api::add_file לא היה זוג ואפילו מפתח/ערך"

}

# bgproc.tcl
msgcat::mcmset he {

  "Unable to run system command (%s)"
  "אין אפשרות להפעיל מערכת הפיקוד (%s)"

}

# gui.tcl
msgcat::mcmset he {

  "%s, Line: %d, Column: %d"
  "%s, קו: %d, עמודה: %d"

  "Close All Tabs"
  "לסגור את כל הכרטיסיות"

  "Close Other Tab(s)"
  "לסגור את Tab(s) אחרים"

  "Close Other*"
  "לסגור את השני *"

  "Close Tab"
  "סגור טאב"

  "Copyright %d-%d"
  "זכויות יוצרים %d %d-"

  "Delete tab?"
  "למחוק טאב?"

  "Developer:"
  "מפתח:"

  "Email:"
  "דוא\"

  "Favorited"
  "שורי"

  "File attribute (%s) does not exist"
  "תכונת הקובץ (%s) לא קיים"

  "File index is out of range"
  "קובץ אינדקס נמצא מחוץ לטווח"

  "Line: %d, Column: %d"
  "קו: %d, עמודה: %d"

  "Locked"
  "נעול"

  "Move to Other Pane"
  "לעבור לחלונית אחרת"

  "Move*"
  "תנועה"

  "Release Type:"
  "סוג פרסום:"

  "Reload file?"
  "טען מחדש קובץ?"

  "Save request"
  "להציל את הבקשה"

  "Show in Sidebar"
  "הצג בסרגל הצידי"

  "Total Lines: %d, Total Characters: %d"
  "שורות סכום כולל: %d, סה כ תווים: %d"

  "Unable to find current file (tab: %s)"
  "אין אפשרות למצוא את הקובץ הנוכחי (הכרטיסיה: %s)"

  "Untitled"
  "ללא כותרת"

  "Version:"
  "גרסה:"

}

# markers.tcl
msgcat::mcmset he {

  "Marker name:"
  "סמן שם:"

}

# menus.tcl
msgcat::mcmset he {

  "                                  Profiling Report Sorted By (%s)"
  "פרופיל ח ממוין לפי (%s)"

  "About TKE"
  "לגבי בבית"

  "Align cursors"
  "ליישר סמנים"

  "All"
  "כל"

  "Append next occurrence"
  "צרף המופע הבא"

  "Check for Update"
  "הסימון עבור עדכון"

  "Clear All"
  "לנקות את כל"

  "Close All"
  "לסגור את כל"

  "Comment"
  "תגובה"

  "Copy"
  "להעתיק"

  "Create new..."
  "יצירת חדש..."

  "Create..."
  "ליצור"

  "Cut"
  "לחתוך"

  "Edit"
  "עריכה"

  "Edit current"
  "עריכת הנוכחי"

  "Edit user"
  "ערוך משתמש"

  "Edit..."
  "עריכה..."

  "File"
  "קובץ"

  "Find"
  "לימצו (limtzo)"

  "Find and Replace"
  "והחלפה"

  "Find in files"
  "למצוא קבצים"

  "Find marker"
  "למצוא את סמן"

  "Find matching pair"
  "למצוא זוג תואם"

  "Format Text"
  "עיצוב טקסט"

  "From Clipboard"
  "מהלוח"

  "Goto Last Tab"
  "הכרטיסיה האחרונה גוטו"

  "Goto Next Tab"
  "הכרטיסייה הבא Goto"

  "Goto Other Pane"
  "Goto חלונית אחרת"

  "Goto Previous Tab"
  "הכרטיסיה הקודמת גוטו"

  "Help"
  "עזרה"

  "Hide Console"
  "להסתיר את המסוף"

  "Hide Sidebar"
  "להסתיר את הסרגל הצידי"

  "Hide Status Bar"
  "הסתר שורת מצב"

  "Hide Tab Bar"
  "הסתר סרגל הלשוניות"

  "Import TextMate theme..."
  "ייבוא TextMate נושא..."

  "Indent"
  "כניסה"

  "Insert Text"
  "הוספת טקסט"

  "Insert enumeration"
  "הוספת ספירה"

  "Install..."
  "להתקין..."

  "Launcher"
  "משגר"

  "Lock"
  "מנעול"

  "Menu Bindings"
  "תפריט איגודי"

  "Menu: About TKE"
  "תפריט: על בבית"

  "Menu: Align cursors"
  "תפריט: ליישר סמנים"

  "Menu: Append next occurrence"
  "תפריט: הוספה המופע הבא"

  "Menu: Check for Update"
  "תפריט: בדוק אם יש עדכון"

  "Menu: Close all tabs"
  "תפריט: לסגור את כל הכרטיסיות"

  "Menu: Close current tab"
  "תפריט: הכרטיסיה הנוכחית סגור"

  "Menu: Comment selected text"
  "תפריט: טקסט ההערה שנבחרה"

  "Menu: Copy selected text"
  "תפריט: העתק טקסט נבחר"

  "Menu: Create new plugin"
  "תפריט: ליצור תוסף חדש"

  "Menu: Create new theme"
  "תפריט: ליצור נושא חדש"

  "Menu: Cut selected text"
  "תפריט: גזור טקסט נבחר"

  "Menu: Disable Vim mode"
  "תפריט: בטל את מצב Vim"

  "Menu: Edit Tke theme"
  "תפריט: עריכה בבית השעשועים"

  "Menu: Edit current snippets"
  "תפריט: עריכה מקטעי הנוכחי"

  "Menu: Edit user menu bindings"
  "תפריט: עריכת האיגודים תפריט משתמש"

  "Menu: Edit user preferences"
  "תפריט: עריכת העדפות משתמש"

  "Menu: Enable Vim mode"
  "תפריט: הפעלת מצב Vim"

  "Menu: Favorite file"
  "תפריט: קובץ מועדפים"

  "Menu: Find"
  "תפריט: למצוא"

  "Menu: Find and Replace"
  "תפריט: חיפוש והחלפה"

  "Menu: Find in files"
  "תפריט: למצוא קבצים"

  "Menu: Find matching character pair"
  "תפריט: למצוא זוג תואם תו"

  "Menu: Find next occurrence"
  "תפריט: המופע הבא של למצוא"

  "Menu: Find previous occurrence"
  "תפריט: חיפוש המופע הקודם"

  "Menu: Format all text"
  "תפריט: לעצב כל הטקסט"

  "Menu: Format selected text"
  "תפריט: לעצב טקסט שנבחר"

  "Menu: Goto last tab"
  "תפריט: Goto הכרטיסיה האחרונה"

  "Menu: Goto next tab"
  "תפריט: הכרטיסייה הבא Goto"

  "Menu: Goto other pane"
  "תפריט: Goto חלונית אחרת"

  "Menu: Goto previous tab"
  "תפריט: Goto הכרטיסיה הקודמת"

  "Menu: Hide Tab Bar"
  "תפריט: הסתר סרגל הלשוניות"

  "Menu: Hide console"
  "תפריט: מסוף הסתר"

  "Menu: Hide sidebar"
  "תפריט: הסרגל הצידי של הסתר"

  "Menu: Hide status bar"
  "תפריט: שורת מצב של הסתר"

  "Menu: Import TextMate theme"
  "התפריט: נושא הייבוא TextMate"

  "Menu: Indent selected text"
  "תפריט: כניסה לטקסט שנבחר"

  "Menu: Insert enumeration"
  "תפריט: הוספה ספירה"

  "Menu: Insert from clipboard"
  "תפריט: הוספה מהלוח"

  "Menu: Insert snippet"
  "תפריט: הוספה גזיר"

  "Menu: Install plugin"
  "תפריט: להתקין תוסף"

  "Menu: Lock file"
  "תפריט: הקובץ הנעול"

  "Menu: Move to other pane"
  "תפריט: לעבור לחלונית אחרת"

  "Menu: New file"
  "תפריט: קובץ חדש"

  "Menu: Open Favorite"
  "תפריט: פתוח האהוב"

  "Menu: Open Recent"
  "תפריט: פתח לאחרונה"

  "Menu: Open directory"
  "תפריט: המדריך הפתוח"

  "Menu: Open file"
  "תפריט: פתח קובץ"

  "Menu: Paste and format text from clipboard"
  "תפריט: להדביק ולעצב טקסט מהלוח"

  "Menu: Paste text from clipboard"
  "תפריט: הדבקת טקסט מהלוח"

  "Menu: Quit application"
  "תפריט: לצאת מהיישום"

  "Menu: Redo"
  "תפריט: בצע שוב"

  "Menu: Reload all plugins"
  "תפריט: רענן כל התוספים"

  "Menu: Reload current snippets"
  "תפריט: רענן מקטעי הנוכחי"

  "Menu: Restart tke"
  "תפריט: הפעלה מחדש בבית"

  "Menu: Save all files"
  "תפריט: לשמור את כל הקבצים"

  "Menu: Save file"
  "תפריט: שמירת קובץ"

  "Menu: Save file as"
  "תפריט: שמירת הקובץ כקובץ"

  "Menu: Select all occurrences"
  "תפריט: בחר כל המופעים"

  "Menu: Select all text"
  "תפריט: בחר את כל הטקסט"

  "Menu: Set user bindings to global bindings"
  "תפריט: מוגדר משתמש איגודי איגודי גלובלית"

  "Menu: Set user preferences to global preferences"
  "תפריט: להגדיר העדפות המשתמש העדפות גלובלית"

  "Menu: Show Tab Bar"
  "תפריט: הצג סרגל הלשוניות"

  "Menu: Show console"
  "תפריט: מסוף הצג"

  "Menu: Show last profiling report"
  "תפריט: הצג פרופיל הדיווח האחרון"

  "Menu: Show sidebar"
  "תפריט: הצג סרגל צידי"

  "Menu: Show status bar"
  "תפריט: הצג שורת מצב"

  "Menu: Sort tabs"
  "תפריט: מיון כרטיסיות"

  "Menu: Start profiling"
  "תפריט: התחל ליצור פרופיל"

  "Menu: Stop profiling"
  "תפריט: להפסיק. עם הפרופיל"

  "Menu: Toggle split view mode"
  "תפריט: דו-מצבי תצוגת מצב מפוצל"

  "Menu: Uncomment selected text"
  "תפריט: ההערה הטקסט הנבחר"

  "Menu: Undo"
  "תפריט: לבטל"

  "Menu: Unfavorite file"
  "תפריט: קובץ Unfavorite"

  "Menu: Unindent selected text"
  "תפריט: הקטנת כניסת הטקסט הנבחר"

  "Menu: Uninstall plugin"
  "תפריט: להסיר את ההתקנה של תוסף"

  "Menu: Unlock file"
  "תפריט: לפתוח את הקובץ"

  "Menu: View User Guide"
  "תפריט: מדריך למשתמש תצוגת"

  "Menu: View global menu bindings"
  "תפריט: הצג את התפריטים הכללית איגודי"

  "Menu: View global preferences"
  "תפריט: העדפות גלובלית"

  "Move to other pane"
  "לעבור לחלונית אחרת"

  "New"
  "חדש"

  "Open Directory..."
  "המדריך הפתוח..."

  "Open Favorite"
  "מועדפים פתוח"

  "Open File..."
  "פתיחת קובץ..."

  "Open Recent"
  "פתח לאחרונה"

  "Paste"
  "הדבק"

  "Paste and Format"
  "הדבקה ועיצוב"

  "Plugins"
  "פלאג אין"

  "Preferences"
  "אפשרויות קבועות"

  "Profiling started"
  "פרופיל התחיל"

  "Profiling stopped"
  "פרופיל עצר"

  "Quit"
  ". תפסיק"

  "Redo"
  "בצע שוב"

  "Reload"
  "טען מחדש"

  "Reload current"
  "רענן זרם"

  "Reset user to base"
  "איפוס משתמש לבסיס"

  "Restart tke"
  "הפעל מחדש בבית"

  "Save All"
  "להציל את כולם"

  "Save As..."
  "שמירה בשם..."

  "Select All"
  "בחר את כל"

  "Select all occurrences"
  "בחר כל המופעים"

  "Select next occurrence"
  "בחר את המופע הבא"

  "Select previous occurrence"
  "בחר את המופע הקודם"

  "Selected"
  "נבחרת"

  "Set Syntax"
  "תחביר קבע"

  "Set Theme"
  "ערכת נושא"

  "Set user to global"
  "הגדרת משתמש גלובלי"

  "Show Console"
  "הצג המסוף"

  "Show Last Profiling Report"
  "הצג דו\"

  "Show Sidebar"
  "הצג תיבה צידית"

  "Show Status Bar"
  "הצג שורת מצב"

  "Show Tab Bar"
  "הצג סרגל הלשוניות"

  "Show*Profiling*"
  "הצג * פרופיל *"

  "Snippet"
  "גזיר"

  "Snippets"
  "גזירים"

  "Sort Tabs"
  "מיון כרטיסיות"

  "Split view"
  "תצוגת פיצול"

  "Start Profiling"
  "התחל ליצור פרופיל"

  "Stop Profiling"
  "להפסיק. עם הפרופיל"

  "Tabs"
  "טאב"

  "Text"
  "Text"

  "Theme Creator"
  "דירוג הבורא"

  "Tools"
  "כלי"

  "Uncomment"
  "ההערה"

  "Undo"
  "בטל"

  "Unindent"
  "הקטנת כניסת"

  "Uninstall..."
  "להסיר..."

  "Unlock"
  "לבטל את הנעילה"

  "User Guide"
  "מדריך למשתמש"

  "View"
  "תצוגה"

  "View base"
  "תצוגת הבסיס"

  "View global"
  "תצוגה גלובלית"

  "Vim Mode"
  "מצב vim"

}

# plugins.tcl
msgcat::mcmset he {

  "ERROR:  Plugin name already exists"
  "שגיאה: שם התוסף כבר קיים"

  "ERROR:  Plugin name is not valid (only alphanumeric and underscores are allowed)"
  "שגיאה: שם התוסף אינו חוקי (רק אלפאנומרי מקפים תחתונים המותר)"

  "ERROR:  Unable to create plugin directory"
  "שגיאה: אין אפשרות ליצור ספריית התוספים"

  "ERROR:  Unable to write plugin files"
  "שגיאה: אין אפשרות לכתוב קבצים תוסף"

  "Enter plugin name"
  "הזן שם התוסף"

  "Plugin %s installed"
  "ההרחבה %s מותקן"

  "Plugin %s uninstalled"
  "תוסף להסיר את %s"

  "Plugin Errors"
  "תוסף שגיאות"

  "Plugins successfully reloaded"
  "תוספים בהצלחה-נטען מחדש"

  "Syntax errors found in selected plugins"
  "שגיאות תחביר נמצאו הפלאגאינים שנבחרו"

}

# sidebar.tcl
msgcat::mcmset he {

  "Add Parent Directory"
  "הוסף ספריית האב"

  "Close Directory Files"
  "קבצי הספריה קרוב"

  "Delete"
  "מחק"

  "Delete directory?"
  "האם למחוק את הספריה?"

  "Delete file?"
  "האם למחוק את הקובץ?"

  "Duplicate"
  "שכפל"

  "Make Current Working Directory"
  "להפוך את הזרם ספריית עבודה"

  "New Directory"
  "ספריה חדשה"

  "New File"
  "קובץ חדש"

  "Open"
  "Open"

  "Open Directory Files"
  "קבצי הספריה פתוחה"

  "Refresh Directory Files"
  "רענון קבצי הספריה"

  "Remove Parent from Sidebar"
  "להסיר את האב מהסרגל הצידי"

  "Remove from Sidebar"
  "להסיר את הסרגל הצידי"

  "Rename"
  "שינוי שם"

}

# snippets.tcl
msgcat::mcmset he {

  "Snippet: %s: %s"
  "מקטע: % s: %s"

  "Snippet: *"
  "מקטע: *"

}

# syntax.tcl
msgcat::mcmset he {

  "Syntax error in %s.syntax file"
  "שגיאת תחביר בקובץ %s.syntax"

  "Syntax:  %s"
  "תחביר: %s"

  "Theme:  %s"
  "נושא: %s"

}

# themer.tcl
msgcat::mcmset he {

  "Create"
  "ליצור"

  "Create New Theme"
  "יצירת נושא חדש"

  "Create custom"
  "ליצור מותאם אישית"

  "ERROR:  Unable to read %s"
  "שגיאה: אין אפשרות לקרוא את %s"

  "ERROR:  Unable to write %s"
  "שגיאה: אין אפשרות לכתוב את %s"

  "Edit theme"
  "עריכת ערכת נושא"

  "Enter theme name"
  "הזן נושא שם"

  "Error:  Theme is not a supported theme"
  "שגיאה: נושא זה לא נושא נתמך"

  "Import"
  "ייבוא"

  "Import TextMate Theme"
  "ייבוא TextMate דירוג"

  "Name:"
  "שם:"

  "OK"
  "אוקיי"

  "Reset"
  "Reset"

  "Select theme"
  "בחר נושא"

}

# tke.tcl
msgcat::mcmset he {

  "ERROR:  %s"
  "שגיאה: %s"

  "Edit theme?"
  "לערוך דירוג?"

  "Import TextMate theme?"
  "לייבא TextMate נושא?"

}

# tkedat.tcl
msgcat::mcmset he {

  "Unable to open %s for reading"
  "אין אפשרות לפתוח את %s עבור קריאה"

  "Unable to open %s for writing"
  "אין אפשרות לפתוח את %s עבור כתיבה"

}

# General
msgcat::mcmset he {

  "Cancel"
  "ביטול"

  "Close"
  "סגור"

  "Favorite"
  "מועדף"

  "Find:"
  "לימצו (limtzo)"

  "Replace:"
  "חיפוש והחלפה:"

  "Save"
  "שמור"

  "Save As"
  "שמירה בשם"

  "Unfavorite"
  "Unfavorite"

}

