# api.tcl
msgcat::mcmset he {

  "Argument list to api::add_file was not an even key/value pair"
  "רשימת כדי api::add_file לא היה זוג ואפילו מפתח/ערך"

}

# bgproc.tcl
msgcat::mcmset he {

  "Unable to run system command (%s)"
  "אין אפשרות להפעיל מערכת הפיקוד (%s)"

}

# diff.tcl
msgcat::mcmset he {

  "    End: "
  "סיים"

  "    Start: "
  "התחל"

  "Enter difference command"
  "הזן הפרש הפקודה"

  "Enter starting file"
  "הזן קובץ ההתחלה"

  "Update"
  "עדכן"

}

# gui.tcl
msgcat::mcmset he {

  "%s, Line: %d, Column: %d"
  "%s, קו: %d, עמודה: %d"

  "Case sensitivity"
  "תלות ברישיות"

  "Close All Tabs"
  "לסגור את כל הכרטיסיות"

  "Close Other Tab(s)"
  "לסגור את Tab(s) אחרים"

  "Close Other*"
  "לסגור את השני *"

  "Close Tab"
  "סגור טאב"

  "Copyright %d-%d"
  "זכויות יוצרים %d %d-"

  "Delete tab?"
  "למחוק טאב?"

  "Developer:"
  "מפתח:"

  "Email:"
  "דוא\"

  "Error"
  "שגיאה"

  "Favorited"
  "שורי"

  "File already exists.  Use '!' to force an overwrite"
  "הקובץ כבר קיים.  שימוש '!' לכפות על החלף"

  "File attribute (%s) does not exist"
  "תכונת הקובץ (%s) לא קיים"

  "File index is out of range"
  "קובץ אינדקס נמצא מחוץ לטווח"

  "License:"
  "??????"

  "Line: %d, Column: %d"
  "קו: %d, עמודה: %d"

  "Locked"
  "נעול"

  "Move*"
  "תנועה"

  "Must be in multicursor mode to insert numbers"
  "חייב להיות במצב multicursor כדי להוסיף מספרים"

  "No write permissions.  Use '!' to force write."
  "אין הרשאות כתיבה.  שימוש '!' לכפות כתיבה."

  "Release Type:"
  "סוג פרסום:"

  "Reload file?"
  "טען מחדש קובץ?"

  "Save request"
  "להציל את הבקשה"

  "Show in Sidebar"
  "הצג בסרגל הצידי"

  "Starting number:"
  "המספר ההתחלתי:"

  "Tcl/Tk Version:"
  "Tcl/Tk גרסה:"

  "Total Lines: %d, Total Characters: %d"
  "שורות סכום כולל: %d, סה כ תווים: %d"

  "Unable to find current file (tab: %s)"
  "אין אפשרות למצוא את הקובץ הנוכחי (הכרטיסיה: %s)"

  "Unable to successfully parse number string"
  "אין אפשרות לנתח בהצלחה מספר מיתרים"

  "Unable to write file"
  "אין אפשרות לכתוב את הקובץ"

  "Version:"
  "גרסה:"

}

# markers.tcl
msgcat::mcmset he {

  "Marker name:"
  "סמן שם:"

}

# menus.tcl
msgcat::mcmset he {

  "                                  Profiling Report Sorted By (%s)"
  "פרופיל ח ממוין לפי (%s)"

  "About TKE"
  "לגבי בבית"

  "Align Cursors"
  "????? ?????"

  "Append Next Occurrence"
  "??? ????? ???"

  "Auto-Indent"
  "כניסה אוטומטית"

  "Check for Update"
  "הסימון עבור עדכון"

  "Clear All"
  "לנקות את כל"

  "Close All"
  "לסגור את כל"

  "Close Current"
  "???? ?? ??????"

  "Copy"
  "להעתיק"

  "Create New..."
  "??? ???"

  "Create at Current Line"
  "????? ??? ??????"

  "Create..."
  "ליצור"

  "Cut"
  "לחתוך"

  "Edit"
  "עריכה"

  "Edit Language"
  "עריכת שפה"

  "Edit Menu Edit user snippets"
  "ערוך תפריט עריכת קטעי משתמש"

  "Edit Menu: Copy text"
  "תפריט עריכה: העתק טקסט"

  "Edit Menu: Cut text"
  "תפריט עריכה: גזור טקסט"

  "Edit Menu: Edit language snippets"
  "תפריט עריכה: לערוך קטעי שפה"

  "Edit Menu: Edit session current language preferences"
  "תפריט עריכה: עריכה הפעלה העדפות השפה הנוכחית"

  "Edit Menu: Edit session global preferences"
  "תפריט עריכה: עריכת העדפות הכללית הפעלה"

  "Edit Menu: Edit user current language preferences"
  "תפריט עריכה: עריכת העדפות השפה הנוכחית של משתמשים"

  "Edit Menu: Edit user global preferences"
  "תפריט עריכה: עריכת העדפות משתמש גלובלי"

  "Edit Menu: Edit user menu bindings"
  "תפריט עריכה: עריכת האיגודים תפריט משתמש"

  "Edit Menu: Format all text"
  "תפריט עריכה: לעצב כל הטקסט"

  "Edit Menu: Format selected text"
  "תפריט עריכה: לעצב טקסט שנבחר"

  "Edit Menu: Insert from clipboard"
  "תפריט עריכה: הוספת מהלוח"

  "Edit Menu: Insert snippet"
  "תפריט עריכה: הוספת מקטע"

  "Edit Menu: Paste and format text from clipboard"
  "תפריט עריכה: הדבקה ועיצוב טקסט מהלוח"

  "Edit Menu: Paste text from clipboard"
  "תפריט עריכה: הדבקת טקסט מהלוח"

  "Edit Menu: Redo"
  "לתפריט עריכה: בצע שוב"

  "Edit Menu: Reload snippets"
  "בתפריט עריכה: גזירים רענן"

  "Edit Menu: Select all text"
  "תפריט עריכה: בחר את כל הטקסט"

  "Edit Menu: Set indent mode to IND"
  "תפריט עריכה: מוגדר מצב כניסה IND"

  "Edit Menu: Set indent mode to IND+"
  "תפריט עריכה: להגדיר מצב כניסה כ IND +"

  "Edit Menu: Set indent mode to OFF"
  "תפריט עריכה: הגדר כניסה למצב כבוי"

  "Edit Menu: Set user bindings to global bindings"
  "תפריט עריכה: מוגדר משתמש איגודי איגודי גלובלית"

  "Edit Menu: Set user preferences to global preferences"
  "תפריט עריכה: להגדיר העדפות המשתמש העדפות גלובלית"

  "Edit Menu: Undo"
  "לתפריט עריכה: לבטל"

  "Edit Menu: View base preferences file"
  "תפריט עריכה: קובץ ההעדפות הבסיס של תצוגת"

  "Edit Menu: View global menu bindings"
  "תפריט עריכה: הצג את התפריטים הכללית איגודי"

  "Edit Session - Global"
  "????? - ????"

  "Edit Session - Language"
  "????? - ???"

  "Edit User"
  "ערוך משתמש"

  "Edit User - Global"
  "???? ????? - ????"

  "Edit User - Language"
  "???? ????? - ???"

  "Edit..."
  "עריכה..."

  "File"
  "קובץ"

  "File Menu: Close all tabs"
  "תפריט קובץ: לסגור את כל הכרטיסיות"

  "File Menu: Close current tab"
  "תפריט קובץ: סגור לשונית נוכחית"

  "File Menu: Favorite file"
  "בתפריט קובץ: קובץ המועדפים"

  "File Menu: Lock file"
  "בתפריט קובץ: הקובץ הנעול"

  "File Menu: New file"
  "בתפריט קובץ: קובץ חדש"

  "File Menu: Open Favorite"
  "בתפריט קובץ: האהוב פתח"

  "File Menu: Open Recent"
  "תפריט קובץ: פתח לאחרונה"

  "File Menu: Open directory"
  "בתפריט קובץ: מדריך פתח"

  "File Menu: Open file"
  "תפריט קובץ: פתח קובץ"

  "File Menu: Quit application"
  "תפריט קובץ: לצאת מהיישום"

  "File Menu: Save all files"
  "תפריט קובץ: לשמור את כל הקבצים"

  "File Menu: Save file"
  "תפריט קובץ: שמירת קובץ"

  "File Menu: Save file as"
  "תפריט קובץ: שמירת הקובץ כקובץ"

  "File Menu: Show file difference"
  "תפריט קובץ: להראות ההבדל קובץ"

  "File Menu: Unfavorite file"
  "קובץ תפריט: קובץ Unfavorite"

  "File Menu: Unlock file"
  "תפריט קובץ: לפתוח את הקובץ"

  "Find"
  "לימצו (limtzo)"

  "Find In Files"
  "????? ?????"

  "Find Matching Pair"
  "????? ?? ????? ???"

  "Find Menu: Append next occurrence"
  "למצוא תפריט: הוספה המופע הבא"

  "Find Menu: Create marker at current line"
  "למצוא תפריט: ליצור סמן בקו הנוכחי"

  "Find Menu: Find"
  "למצוא בתפריט: למצוא"

  "Find Menu: Find and Replace"
  "תפריט חיפוש: חיפוש והחלפה"

  "Find Menu: Find in files"
  "למצוא תפריט: למצוא קבצים"

  "Find Menu: Find matching character pair"
  "למצוא תפריט: למצוא זוג תואם תו"

  "Find Menu: Find next occurrence"
  "למצוא תפריט: למצוא את המופע הבא"

  "Find Menu: Find previous occurrence"
  "למצוא תפריט: למצוא את המופע הקודם"

  "Find Menu: Goto next difference"
  "למצוא תפריט: ההבדל הבא Goto"

  "Find Menu: Goto previous difference"
  "למצוא תפריט: ההבדל הקודם של גוטו"

  "Find Menu: Jump backward"
  "למצוא תפריט: לקפוץ אחורה"

  "Find Menu: Jump forward"
  "למצוא תפריט: לקפוץ קדימה"

  "Find Menu: Remove all markers"
  "למצוא תפריט: להסיר את כל הסמנים"

  "Find Menu: Remove marker from current line"
  "למצוא תפריט: הסר סמן השורה הנוכחית"

  "Find Menu: Select all occurrences"
  "למצוא תפריט: בחר כל המופעים"

  "Find Menu: Show selected line change"
  "למצוא תפריט: שינוי קו הצג שנבחרו"

  "Find and Replace"
  "והחלפה"

  "Format Text"
  "עיצוב טקסט"

  "From Clipboard"
  "מהלוח"

  "Goto Last Tab"
  "הכרטיסיה האחרונה גוטו"

  "Goto Next Tab"
  "הכרטיסייה הבא Goto"

  "Goto Other Pane"
  "Goto חלונית אחרת"

  "Goto Previous Tab"
  "הכרטיסיה הקודמת גוטו"

  "Help"
  "עזרה"

  "Help Menu: About TKE"
  ": תפריט עזרה אודות בבית"

  "Help Menu: Check for update"
  "בתפריט עזרה: בדוק אם יש עדכון"

  "Help Menu: Send bug report"
  "בתפריט עזרה: לשלוח דיווח הבאג"

  "Help Menu: Send feedback"
  "בתפריט עזרה: שלח משוב"

  "Help Menu: View user guide"
  "תפריט העזרה: מדריך למשתמש של תצוגת"

  "Hide Console"
  "להסתיר את המסוף"

  "Hide Line Numbers"
  "הסתר מספרי שורות"

  "Hide Meta Characters"
  "?????? ???-?????"

  "Hide Sidebar"
  "להסתיר את הסרגל הצידי"

  "Hide Status Bar"
  "הסתר שורת מצב"

  "Hide Tab Bar"
  "הסתר סרגל הלשוניות"

  "Import TextMate Theme..."
  "????? TextMate ????..."

  "Indent"
  "כניסה"

  "Indent Mode"
  "כניסה למצב"

  "Indent Off"
  "כניסה."

  "Insert Enumeration"
  "????? ?????"

  "Insert Text"
  "הוספת טקסט"

  "Install..."
  "להתקין..."

  "Jump Backward"
  "????? ?????"

  "Jump Forward"
  "????? ?????"

  "Launcher"
  "משגר"

  "Lock"
  "מנעול"

  "Markers"
  "סמנים"

  "Menu Bindings"
  "תפריט איגודי"

  "Menus: About TKE"
  "תפריטים: על בבית"

  "Merge Panes"
  "????? ???????"

  "Next Difference"
  "????? ???"

  "Open Directory..."
  "המדריך הפתוח..."

  "Open Favorite"
  "מועדפים פתוח"

  "Open File..."
  "פתיחת קובץ..."

  "Open Recent"
  "פתח לאחרונה"

  "Paste"
  "הדבק"

  "Paste and Format"
  "הדבקה ועיצוב"

  "Plugins"
  "פלאג אין"

  "Plugins Menu: Create new plugin"
  "תפריט תוספים: ליצור תוסף חדש"

  "Plugins Menu: Install plugin"
  "תפריט תוספים: להתקין תוסף"

  "Plugins Menu: Reload all plugins"
  "תפריט תוספים: רענן כל התוספים"

  "Plugins Menu: Uninstall plugin"
  "תפריט תוספים: להסיר את ההתקנה של תוסף"

  "Preferences"
  "אפשרויות קבועות"

  "Previous Difference"
  "????? ?????"

  "Profiling started"
  "פרופיל התחיל"

  "Profiling stopped"
  "פרופיל עצר"

  "Quit"
  ". תפסיק"

  "Redo"
  "בצע שוב"

  "Reload"
  "טען מחדש"

  "Remove All Markers"
  "????? ?? ?? ??????"

  "Remove From Current Line"
  "????? ?? ????? ???????"

  "Replace Line With Script"
  "?????? ???? ?????"

  "Reset User to Base"
  "איפוס משתמש לבסיס"

  "Restart TKE"
  "???? ????"

  "Save All"
  "להציל את כולם"

  "Save As..."
  "שמירה בשם..."

  "Save Current"
  "????? ?? ??????"

  "Select All"
  "בחר את כל"

  "Select All Occurrences"
  "??? ?? ???????"

  "Select Next Occurrence"
  "??? ?? ????? ???"

  "Select Previous Occurrence"
  "??? ?? ????? ?????"

  "Selected"
  "נבחרת"

  "Send Bug Report"
  "לשלוח דיווח הבאג"

  "Send Feedback"
  "שלח משוב"

  "Sessions"
  "??????"

  "Sessions Menu: Close current session"
  "תפריט הפעלות: לסגור את ההפעלה הנוכחית"

  "Sessions Menu: Delete session"
  "תפריט הפעלות: ההפעלה Delete"

  "Sessions Menu: Open session"
  "תפריט הפעלות: מפגש פתוח"

  "Sessions Menu: Save current session"
  "תפריט הפעלות: להציל את ההפעלה הנוכחית"

  "Sessions Menu: Save sessions as"
  "תפריט הפעלות: לשמור הפעלות כמו"

  "Sessions Menu: Switch to session"
  "תפריט הפעלות: מתג הפעלה"

  "Set Syntax"
  "תחביר קבע"

  "Set Theme"
  "ערכת נושא"

  "Set User to Global"
  "הגדרת משתמש גלובלי"

  "Show Console"
  "הצג המסוף"

  "Show Diagnostic Logfile"
  "הצג יומן האבחון"

  "Show File Difference"
  "הצג קובץ ההבדל"

  "Show Last Profiling Report"
  "הצג דו\"

  "Show Line Numbers"
  "הצג מספרי שורות"

  "Show Meta Characters"
  "??? ???-?????"

  "Show Selected Line Change"
  "?????? ????? ??? ?????"

  "Show Sidebar"
  "הצג תיבה צידית"

  "Show Status Bar"
  "הצג שורת מצב"

  "Show Tab Bar"
  "הצג סרגל הלשוניות"

  "Smart Indent"
  "כניסה חכמה"

  "Snippet"
  "גזיר"

  "Snippets"
  "גזירים"

  "Sort Tabs"
  "מיון כרטיסיות"

  "Split View"
  "????? ?????"

  "Start Profiling"
  "התחל ליצור פרופיל"

  "Stop Profiling"
  "להפסיק. עם הפרופיל"

  "Switch To"
  "?????"

  "Tabs"
  "טאב"

  "Text"
  "Text"

  "Text Menu: Align cursors"
  "טקסט תפריט: ליישר סמנים"

  "Text Menu: Indent selected text"
  "טקסט תפריט: כניסה לטקסט שנבחר"

  "Text Menu: Insert enumeration"
  "טקסט תפריט: הוספה ספירה"

  "Text Menu: Replace line with script"
  "טקסט תפריט: להחליף שורת תסריט"

  "Text Menu: Toggle comment"
  "טקסט תפריט: תגובה דו-מצבי"

  "Text Menu: Unindent selected text"
  "טקסט תפריט: הקטנת כניסת הטקסט הנבחר"

  "Theme Creator"
  "דירוג הבורא"

  "Toggle Comment"
  "????? ??-????"

  "Tools"
  "כלי"

  "Tools Menu: Create new theme"
  "תפריט כלים: ליצור נושא חדש"

  "Tools Menu: Disable Vim mode"
  "תפריט כלים: בטל את מצב Vim"

  "Tools Menu: Edit TKE theme"
  "תפריט כלים: לערוך דירוג בבית"

  "Tools Menu: Enable Vim mode"
  "תפריט כלים: הפעלת מצב Vim"

  "Tools Menu: Import TextMate theme"
  "תפריט כלים: הנושא ייבוא TextMate"

  "Tools Menu: Restart TKE"
  "תפריט כלים: הפעלה מחדש בבית"

  "Tools Menu: Show diagnostic logfile"
  "תפריט כלים: הצג יומן האבחון"

  "Tools Menu: Show last profiling report"
  "תפריט כלים: הצג פרופיל הדיווח האחרון"

  "Tools Menu: Start profiling"
  "תפריט כלים: התחל ליצור פרופיל"

  "Tools Menu: Stop profiling"
  "תפריט כלים: להפסיק. עם הפרופיל"

  "Undo"
  "בטל"

  "Unindent"
  "הקטנת כניסת"

  "Uninstall..."
  "להסיר..."

  "Unlock"
  "לבטל את הנעילה"

  "User Guide"
  "מדריך למשתמש"

  "View"
  "תצוגה"

  "View Base"
  "תצוגת הבסיס"

  "View Global"
  "תצוגה גלובלית"

  "View Menu: Goto last tab"
  "בתפריט תצוגה: הכרטיסיה האחרונה Goto"

  "View Menu: Goto next tab"
  "בתפריט תצוגה: הכרטיסייה הבא Goto"

  "View Menu: Goto other pane"
  "תפריט תצוגה: Goto חלונית אחרת"

  "View Menu: Goto previous tab"
  "בתפריט תצוגה: הכרטיסיה הקודמת של גוטו"

  "View Menu: Hide console"
  "בתפריט תצוגה: מסוף הסתר"

  "View Menu: Hide line numbers"
  "בתפריט תצוגה: מספרי שורות הסתר"

  "View Menu: Hide meta characters"
  "תפריט תצוגה: להסתיר מטא-תווים"

  "View Menu: Hide sidebar"
  "בתפריט תצוגה: הסרגל הצידי של הסתרה"

  "View Menu: Hide status bar"
  "בתפריט תצוגה: שורת המצב של הסתרה"

  "View Menu: Hide tab bar"
  "בתפריט תצוגה: סרגל הלשוניות הסתר"

  "View Menu: Merge panes"
  "תפריט תצוגה: מיזוג חלוניות"

  "View Menu: Move to other pane"
  "תפריט תצוגה: לעבור לחלונית אחרת"

  "View Menu: Show console"
  "בתפריט תצוגה: מסוף הצג"

  "View Menu: Show line numbers"
  "בתפריט תצוגה: מספרי שורות הצג"

  "View Menu: Show meta characters"
  "תפריט תצוגה: הצג מטא-תווים"

  "View Menu: Show sidebar"
  "בתפריט תצוגה: הסרגל הצידי של הצג"

  "View Menu: Show status bar"
  "בתפריט תצוגה: שורת המצב של הצג"

  "View Menu: Show tab bar"
  "בתפריט תצוגה: סרגל הלשוניות הצג"

  "View Menu: Sort tabs"
  "תפריט תצוגה: מיון כרטיסיות"

  "View Menu: Toggle split view mode"
  "תפריט תצוגה: דו-מצבי תצוגת מצב מפוצל"

  "Vim Mode"
  "מצב vim"

}

# plugins.tcl
msgcat::mcmset he {

  "ERROR (%s,%s): %s"
  "שגיאה (%s, %s): %s"

  "ERROR:  Plugin name already exists"
  "שגיאה: שם התוסף כבר קיים"

  "ERROR:  Plugin name is not valid (only alphanumeric and underscores are allowed)"
  "שגיאה: שם התוסף אינו חוקי (רק אלפאנומרי מקפים תחתונים המותר)"

  "ERROR:  Unable to create plugin directory"
  "שגיאה: אין אפשרות ליצור ספריית התוספים"

  "ERROR:  Unable to write plugin files"
  "שגיאה: אין אפשרות לכתוב קבצים תוסף"

  "Enter plugin name"
  "הזן שם התוסף"

  "Plugin %s installed"
  "ההרחבה %s מותקן"

  "Plugin %s uninstalled"
  "תוסף להסיר את %s"

  "Plugin Errors"
  "תוסף שגיאות"

  "Plugins successfully reloaded"
  "תוספים בהצלחה-נטען מחדש"

  "Syntax errors found in selected plugins"
  "שגיאות תחביר נמצאו הפלאגאינים שנבחרו"

}

# search.tcl
msgcat::mcmset he {

  "%d substitutions done"
  "%d החלפות עשה"

  "No files found in specified directories"
  "לא נמצאו בספריות שצוין קבצים"

  "No search results found"
  "תוצאות חיפוש נמצאו"

  "Search wrapped to beginning of file"
  "חיפוש עטוף לתחילת הקובץ"

  "Search wrapped to end of file"
  "חיפוש עטוף כדי בסוף הקובץ"

}

# sidebar.tcl
msgcat::mcmset he {

  "Add Parent Directory"
  "הוסף ספריית האב"

  "Close Directory Files"
  "קבצי הספריה קרוב"

  "Copy Pathname"
  "????? ????"

  "Delete directory?"
  "האם למחוק את הספריה?"

  "Delete file?"
  "האם למחוק את הקובץ?"

  "Directory Name:"
  "שם הספריה:"

  "Duplicate"
  "שכפל"

  "File Name:"
  "שם קובץ"

  "Folder Name:"
  "?? ?????:"

  "Make Current Working Directory"
  "להפוך את הזרם ספריית עבודה"

  "New Directory"
  "ספריה חדשה"

  "Open Directory Files"
  "קבצי הספריה פתוחה"

  "Refresh Directory Files"
  "רענון קבצי הספריה"

  "Remove Parent from Sidebar"
  "להסיר את האב מהסרגל הצידי"

  "Remove from Sidebar"
  "להסיר את הסרגל הצידי"

  "Rename"
  "שינוי שם"

  "Show Difference"
  "להראות ההבדל"

}

# snippets.tcl
msgcat::mcmset he {

  "Snippet: *"
  "מקטע: *"

}

# syntax.tcl
msgcat::mcmset he {

  "Syntax error in %s.syntax file"
  "שגיאת תחביר בקובץ %s.syntax"

  "Syntax:  %s"
  "תחביר: %s"

  "Theme:  %s"
  "נושא: %s"

}

# themer.tcl
msgcat::mcmset he {

  "Create"
  "ליצור"

  "Create New Theme"
  "יצירת נושא חדש"

  "Create custom"
  "ליצור מותאם אישית"

  "ERROR:  Unable to read %s"
  "שגיאה: אין אפשרות לקרוא את %s"

  "ERROR:  Unable to write %s"
  "שגיאה: אין אפשרות לכתוב את %s"

  "Edit theme"
  "עריכת ערכת נושא"

  "Enter theme name"
  "הזן נושא שם"

  "Error:  Theme is not a supported theme"
  "שגיאה: נושא זה לא נושא נתמך"

  "Import"
  "ייבוא"

  "Import TextMate Theme"
  "ייבוא TextMate דירוג"

  "Name:"
  "שם:"

  "OK"
  "אוקיי"

  "Reset"
  "Reset"

  "Select theme"
  "בחר נושא"

}

# tke.tcl
msgcat::mcmset he {

  "Edit theme?"
  "לערוך דירוג?"

  "Import TextMate theme?"
  "לייבא TextMate נושא?"

}

# tkedat.tcl
msgcat::mcmset he {

  "Unable to open %s for reading"
  "אין אפשרות לפתוח את %s עבור קריאה"

}

# vim.tcl
msgcat::mcmset he {

  "File %s successfully written"
  "הקובץ %s בהצלחה נכתב"

  "Filename %s already exists"
  "שם הקובץ %s כבר קיים"

}

# General
msgcat::mcmset he {

  "All"
  "כל"

  "Cancel"
  "ביטול"

  "Close"
  "סגור"

  "Delete"
  "מחק"

  "Favorite"
  "מועדף"

  "Find:"
  "לימצו (limtzo)"

  "Move to Other Pane"
  "לעבור לחלונית אחרת"

  "New File"
  "קובץ חדש"

  "Open"
  "Open"

  "Replace:"
  "חיפוש והחלפה:"

  "Save"
  "שמור"

  "Save As"
  "שמירה בשם"

  "Unable to open %s for writing"
  "אין אפשרות לפתוח את %s עבור כתיבה"

  "Unfavorite"
  "Unfavorite"

}

