# api.tcl
msgcat::mcmset he {

  "Argument list to api::add_file was not an even key/value pair"
  "רשימת כדי api::add_file לא היה זוג ואפילו מפתח/ערך"

  "Argument list to api::add_file was not in the form 'filename [<option> <value>]*'"
  "רשימת כדי api::add_file לא היה בדמות ' [שם קובץ<option><value>]*'</value>"

  "get_home_directory can only be called within plugin code"
  "get_home_directory יכול להיקרא רק בתוך תוסף קוד"

}

# bgproc.tcl
msgcat::mcmset he {

  "Unable to run system command (%s)"
  "אין אפשרות להפעיל מערכת הפיקוד (%s)"

}

# bindings.tcl
msgcat::mcmset he {

  "Menu Bindings: Edit user menu bindings"
  "איגודי תפריט: עריכת האיגודים תפריט משתמש"

  "Menu Bindings: Reload menu bindings"
  "תפריט איגודי: רענן בתפריט איגודי"

  "Menu Bindings: Use default menu bindings"
  "תפריט איגודי: להשתמש איגודי תפריט ברירת המחדל"

  "Menu Bindings: View global menu bindings"
  "תפריט איגודי: הצג את התפריטים הכללית איגודי"

}

# gui.tcl
msgcat::mcmset he {

  "Close All Tabs"
  "לסגור את כל הכרטיסיות"

  "Close Other Tab(s)"
  "לסגור את Tab(s) אחרים"

  "Close Other*"
  "לסגור את השני *"

  "Close Tab"
  "סגור טאב"

  "Copyright %d-%d"
  "זכויות יוצרים %d %d-"

  "Delete tab?"
  "למחוק טאב?"

  "Developer:"
  "מפתח:"

  "Email:"
  "דוא\"

  "File attribute (%s) does not exist"
  "תכונת הקובץ (%s) לא קיים"

  "File index is out of range"
  "קובץ אינדקס נמצא מחוץ לטווח"

  "Find:"
  "לימצו (limtzo)"

  "Line: %d, Column: %d"
  "קו: %d, עמודה: %d"

  "Line: %d, Column: %d, Total Lines: %d, Total Characters: %d"
  "קו: %d, עמודה: %d, הכולל קווים: %d, סה כ תווים: %d"

  "Locked"
  "נעול"

  "Move to Other Pane"
  "לעבור לחלונית אחרת"

  "Move*"
  "תנועה"

  "Reload file?"
  "טען מחדש קובץ?"

  "Replace:"
  "חיפוש והחלפה:"

  "Save request"
  "להציל את הבקשה"

  "Unable to find current file (tab: %s)"
  "אין אפשרות למצוא את הקובץ הנוכחי (הכרטיסיה: %s)"

  "Untitled"
  "ללא כותרת"

  "Version:"
  "גרסה:"

}

# markers.tcl
msgcat::mcmset he {

  "Marker name:"
  "סמן שם:"

}

# menus.tcl
msgcat::mcmset he {

  "                                  Profiling Report Sorted By (%s)"
  "פרופיל ח ממוין לפי (%s)"

  "About Tke"
  "לגבי בבית"

  "About tke"
  "לגבי בבית"

  "Align cursors"
  "ליישר סמנים"

  "All"
  "כל"

  "Append next occurrence"
  "צרף המופע הבא"

  "Clear All"
  "לנקות את כל"

  "Close All"
  "לסגור את כל"

  "Comment"
  "תגובה"

  "Copy"
  "להעתיק"

  "Create new..."
  "יצירת חדש..."

  "Create..."
  "ליצור"

  "Cut"
  "לחתוך"

  "Edit"
  "עריכה"

  "Edit..."
  "עריכה..."

  "FOOBAR"
  "FOOBAR"

  "File"
  "קובץ"

  "Find"
  "לימצו (limtzo)"

  "Find and Replace"
  "והחלפה"

  "Find in files"
  "למצוא קבצים"

  "Find marker"
  "למצוא את סמן"

  "Find matching pair"
  "למצוא זוג תואם"

  "Format Text"
  "עיצוב טקסט"

  "Goto Last Tab"
  "הכרטיסיה האחרונה גוטו"

  "Goto Next Tab"
  "הכרטיסייה הבא Goto"

  "Goto Other Pane"
  "Goto חלונית אחרת"

  "Goto Previous Tab"
  "הכרטיסיה הקודמת גוטו"

  "Help"
  "עזרה"

  "Import TextMate theme..."
  "ייבוא TextMate נושא..."

  "Indent"
  "כניסה"

  "Insert enumeration"
  "הוספת ספירה"

  "Install..."
  "להתקין..."

  "Launcher"
  "משגר"

  "Lock"
  "מנעול"

  "Menu: About tke"
  "תפריט: על בבית"

  "Menu: Align cursors"
  "תפריט: ליישר סמנים"

  "Menu: Append next occurrence"
  "תפריט: הוספה המופע הבא"

  "Menu: Close all tabs"
  "תפריט: לסגור את כל הכרטיסיות"

  "Menu: Close current tab"
  "תפריט: הכרטיסיה הנוכחית סגור"

  "Menu: Comment selected text"
  "תפריט: טקסט ההערה שנבחרה"

  "Menu: Copy selected text"
  "תפריט: העתק טקסט נבחר"

  "Menu: Create new plugin"
  "תפריט: ליצור תוסף חדש"

  "Menu: Create new theme"
  "תפריט: ליצור נושא חדש"

  "Menu: Cut selected text"
  "תפריט: גזור טקסט נבחר"

  "Menu: Disable Vim mode"
  "תפריט: בטל את מצב Vim"

  "Menu: Edit Tke theme"
  "תפריט: עריכה בבית השעשועים"

  "Menu: Enable Vim mode"
  "תפריט: הפעלת מצב Vim"

  "Menu: Find"
  "תפריט: למצוא"

  "Menu: Find and Replace"
  "תפריט: חיפוש והחלפה"

  "Menu: Find in files"
  "תפריט: למצוא קבצים"

  "Menu: Find matching character pair"
  "תפריט: למצוא זוג תואם תו"

  "Menu: Find next occurrence"
  "תפריט: המופע הבא של למצוא"

  "Menu: Find previous occurrence"
  "תפריט: חיפוש המופע הקודם"

  "Menu: Goto last tab"
  "תפריט: Goto הכרטיסיה האחרונה"

  "Menu: Goto next tab"
  "תפריט: הכרטיסייה הבא Goto"

  "Menu: Goto other pane"
  "תפריט: Goto חלונית אחרת"

  "Menu: Goto previous tab"
  "תפריט: Goto הכרטיסיה הקודמת"

  "Menu: Hide console"
  "תפריט: מסוף הסתר"

  "Menu: Hide sidebar"
  "תפריט: הסרגל הצידי של הסתר"

  "Menu: Hide status bar"
  "תפריט: שורת מצב של הסתר"

  "Menu: Import TextMate theme"
  "התפריט: נושא הייבוא TextMate"

  "Menu: Indent selected text"
  "תפריט: כניסה לטקסט שנבחר"

  "Menu: Insert enumeration"
  "תפריט: הוספה ספירה"

  "Menu: Install plugin"
  "תפריט: להתקין תוסף"

  "Menu: Lock file"
  "תפריט: הקובץ הנעול"

  "Menu: New file"
  "תפריט: קובץ חדש"

  "Menu: Open directory"
  "תפריט: המדריך הפתוח"

  "Menu: Open file"
  "תפריט: פתח קובץ"

  "Menu: Paste and format text from clipboard"
  "תפריט: להדביק ולעצב טקסט מהלוח"

  "Menu: Paste text from clipboard"
  "תפריט: הדבקת טקסט מהלוח"

  "Menu: Quit application"
  "תפריט: לצאת מהיישום"

  "Menu: Redo"
  "תפריט: בצע שוב"

  "Menu: Reload all plugins"
  "תפריט: רענן כל התוספים"

  "Menu: Restart tke"
  "תפריט: הפעלה מחדש בבית"

  "Menu: Save all files"
  "תפריט: לשמור את כל הקבצים"

  "Menu: Save file"
  "תפריט: שמירת קובץ"

  "Menu: Save file as"
  "תפריט: שמירת הקובץ כקובץ"

  "Menu: Select all occurrences"
  "תפריט: בחר כל המופעים"

  "Menu: Show console"
  "תפריט: מסוף הצג"

  "Menu: Show last profiling report"
  "תפריט: הצג פרופיל הדיווח האחרון"

  "Menu: Show sidebar"
  "תפריט: הצג סרגל צידי"

  "Menu: Show status bar"
  "תפריט: הצג שורת מצב"

  "Menu: Sort tabs"
  "תפריט: מיון כרטיסיות"

  "Menu: Start profiling"
  "תפריט: התחל ליצור פרופיל"

  "Menu: Stop profiling"
  "תפריט: להפסיק. עם הפרופיל"

  "Menu: Toggle split pane"
  "תפריט: חלונית מפוצל דו-מצבי"

  "Menu: Uncomment selected text"
  "תפריט: ההערה הטקסט הנבחר"

  "Menu: Undo"
  "תפריט: לבטל"

  "Menu: Unindent selected text"
  "תפריט: הקטנת כניסת הטקסט הנבחר"

  "Menu: Uninstall plugin"
  "תפריט: להסיר את ההתקנה של תוסף"

  "Menu: Unlock file"
  "תפריט: לפתוח את הקובץ"

  "New"
  "חדש"

  "Open Directory..."
  "המדריך הפתוח..."

  "Open File..."
  "פתיחת קובץ..."

  "Open Recent"
  "פתח לאחרונה"

  "Paste"
  "הדבק"

  "Paste and Format"
  "הדבקה ועיצוב"

  "Plugins"
  "פלאג אין"

  "Preferences..."
  "אפשרויות קבועות"

  "Profiling started"
  "פרופיל התחיל"

  "Profiling stopped"
  "פרופיל עצר"

  "Quit"
  ". תפסיק"

  "Redo"
  "בצע שוב"

  "Reload"
  "טען מחדש"

  "Restart tke"
  "הפעל מחדש בבית"

  "Save All"
  "להציל את כולם"

  "Save As..."
  "שמירה בשם..."

  "Select all occurrences"
  "בחר כל המופעים"

  "Select next occurrence"
  "בחר את המופע הבא"

  "Select previous occurrence"
  "בחר את המופע הקודם"

  "Selected"
  "נבחרת"

  "Set Syntax"
  "תחביר קבע"

  "Show Last Profiling Report"
  "הצג דו\"

  "Show split pane"
  "הצג חלונית מפוצל"

  "Show*Profiling*"
  "הצג * פרופיל *"

  "Sort Tabs"
  "מיון כרטיסיות"

  "Start Profiling"
  "התחל ליצור פרופיל"

  "Stop Profiling"
  "להפסיק. עם הפרופיל"

  "Tabs"
  "טאב"

  "Text"
  "Text"

  "Theme Creator"
  "דירוג הבורא"

  "Tools"
  "כלי"

  "Uncomment"
  "ההערה"

  "Undo"
  "בטל"

  "Unindent"
  "הקטנת כניסת"

  "Uninstall..."
  "להסיר..."

  "Unlock"
  "לבטל את הנעילה"

  "View"
  "תצוגה"

  "View Console"
  "תצוגת המסוף"

  "View Sidebar"
  "הסרגל הצידי בתצוגה"

  "View Status Bar"
  "תצוגה בשורת המצב"

  "Vim Mode"
  "מצב vim"

}

# plugins.tcl
msgcat::mcmset he {

  "ERROR:  Plugin name is not valid (only alphanumeric and underscores are allowed)"
  "שגיאה: שם התוסף אינו חוקי (רק אלפאנומרי מקפים תחתונים המותר)"

  "ERROR:  Unable to write plugin file"
  "שגיאה: אין אפשרות לכתוב את הקובץ תוסף"

  "Enter plugin name"
  "הזן שם התוסף"

  "Plugin %s installed"
  "ההרחבה %s מותקן"

  "Plugin %s uninstalled"
  "תוסף להסיר את %s"

  "Plugin Errors"
  "תוסף שגיאות"

  "Syntax errors found in selected plugins"
  "שגיאות תחביר נמצאו הפלאגאינים שנבחרו"

}

# preferences.tcl
msgcat::mcmset he {

  "Preferences: Edit user preferences"
  "העדפות: עריכת העדפות משתמש"

  "Preferences: Reload preferences"
  "העדפות: רענן העדפות"

  "Preferences: Use default preferences"
  "העדפות: להשתמש העדפות ברירת המחדל"

  "Preferences: View global preferences"
  "העדפות: תצוגת ההעדפות הכללית"

}

# sidebar.tcl
msgcat::mcmset he {

  "Add Parent Directory"
  "הוסף ספריית האב"

  "Close Directory Files"
  "קבצי הספריה קרוב"

  "Delete"
  "מחק"

  "Delete directory?"
  "האם למחוק את הספריה?"

  "Delete file?"
  "האם למחוק את הקובץ?"

  "Duplicate"
  "שכפל"

  "Make Current Working Directory"
  "להפוך את הזרם ספריית עבודה"

  "New Directory"
  "ספריה חדשה"

  "New File"
  "קובץ חדש"

  "Open"
  "Open"

  "Refresh Directory Files"
  "רענון קבצי הספריה"

  "Remove Parent from Sidebar"
  "להסיר את האב מהסרגל הצידי"

  "Remove from Sidebar"
  "להסיר את הסרגל הצידי"

  "Rename"
  "שינוי שם"

}

# snippets.tcl
msgcat::mcmset he {

  "Snippet: %s: %s"
  "מקטע: % s: %s"

  "Snippet: *"
  "מקטע: *"

  "Snippets: Add snippet"
  "גזירים: הוספת מקטע"

  "Snippets: Reload all snippets"
  "גזירים: רענן כל מקטעי"

}

# syntax.tcl
msgcat::mcmset he {

  "Syntax error in %s.syntax file"
  "שגיאת תחביר בקובץ %s.syntax"

  "Syntax:  %s"
  "תחביר: %s"

  "Theme:  %s"
  "נושא: %s"

}

# themer.tcl
msgcat::mcmset he {

  "Create"
  "ליצור"

  "Create New Theme"
  "יצירת נושא חדש"

  "Create custom"
  "ליצור מותאם אישית"

  "ERROR:  Unable to read %s"
  "שגיאה: אין אפשרות לקרוא את %s"

  "ERROR:  Unable to write %s"
  "שגיאה: אין אפשרות לכתוב את %s"

  "Edit theme"
  "עריכת ערכת נושא"

  "Enter theme name"
  "הזן נושא שם"

  "Error:  Theme is not a supported theme"
  "שגיאה: נושא זה לא נושא נתמך"

  "Import"
  "ייבוא"

  "Import TextMate Theme"
  "ייבוא TextMate דירוג"

  "Name:"
  "שם:"

  "OK"
  "אוקיי"

  "Reset"
  "Reset"

  "Select theme"
  "בחר נושא"

}

# tke.tcl
msgcat::mcmset he {

  "ERROR:  %s"
  "שגיאה: %s"

  "Edit theme?"
  "לערוך דירוג?"

  "Import TextMate theme?"
  "לייבא TextMate נושא?"

}

# tkedat.tcl
msgcat::mcmset he {

  "Unable to open %s for reading"
  "אין אפשרות לפתוח את %s עבור קריאה"

  "Unable to open %s for writing"
  "אין אפשרות לפתוח את %s עבור כתיבה"

}

# General
msgcat::mcmset he {

  "Cancel"
  "ביטול"

  "Close"
  "סגור"

  "Save"
  "שמור"

  "Save As"
  "שמירה בשם"

}

