# api.tcl
msgcat::mcmset hu {

  "Argument list to api::add_file was not an even key/value pair"
  "Argumentumlista API :: add_file nem volt még kulcs / érték párt"

  "Plugin"
  "Bővítmény"

}

# bgproc.tcl
msgcat::mcmset hu {

  "Unable to run system command"
  "Képtelen-hoz fuss követel rendszer"

}

# diff.tcl
msgcat::mcmset hu {

  "    End: "
  "Vége:"

  "    Start: "
  "Kezdete:"

  "Enter difference command"
  "Adja meg a differencia parancs"

  "Enter starting file"
  "Adja meg a kezdő fájl"

  "Update"
  "Frissítés"

}

# edit.tcl
msgcat::mcmset hu {

  "File successfully written"
  "Fájl írása sikeresen"

  "Filename already exists"
  "Fájlnév már létezik"

}

# embed_tke.tcl
msgcat::mcmset hu {

  "Find:"
  "felfedez"

  "Replace:"
  "Csere:"

}

# gui.tcl
msgcat::mcmset hu {

  "All"
  "Minden"

  "Case sensitivity"
  "Kisbetű-nagybetű érzékenység"

  "Close All Tabs"
  "Összes fül bezárása"

  "Close Other Tabs"
  "A többi lap bezárása"

  "Close Other*"
  "A többi lap bezárása"

  "Close Tab"
  "A lap bezárása"

  "Column"
  "Oszlop"

  "Copyright"
  "Szerzői jogok"

  "Delete tab?"
  "Törlés lap?"

  "Developer"
  "Fejlesztő"

  "Email"
  "E-mail cím"

  "Error"
  "Hiba"

  "Favorited"
  "Kedvencek"

  "File already exists.  Use '!' to force an overwrite"
  "A fájl már létezik. Használja a '!' kényszeríteni felülíró"

  "File attribute does not exist"
  "Attribútum nem létezik"

  "File index is out of range"
  "Fájl index tartományon kívül"

  "Image displayed in fill-in forms which closes the form UI.  Used in forms such as search, search/replace, and find in files."
  "A kép megjelenik a nyomtatványok, amely lezárja a formában UI. Használt formák, mint a keresés, keresés / csere, és megtalálni a fájlokat."

  "Image used in tab menus to indicate that the file is associated with a difference view."
  "Kép használt lap menük, jelezve, hogy a fájl társítva van különbség kilátás."

  "Image used in tab menus to indicate that the file is locked."
  "Kép használt lap menük, jelezve, hogy a fájl zárolva van."

  "Image used in tab menus to indicate that the file is readonly."
  "Kép használt lap menük, jelezve, hogy a fájl csak olvasható."

  "Image used in tab to indicate that the tab contains a difference view."
  "Kép használt lapon jelzi, hogy a lapon található különbség kilátás."

  "Image used in tab to indicate that the tab's file is readonly."
  "Kép használt lap, jelezve, hogy a lap a fájl csak olvasható."

  "Image used in tab to indicate that the tab’s file is locked."
  "Kép használt lap, jelezve, hogy a lap fájl zárolva van."

  "Image used in tab which, when clicked, closes the tab."
  "Kép használt lap, amely, ha rákattintunk, bezárja a lapot."

  "License"
  "Licenc"

  "Line"
  "Vonal"

  "Locked"
  "Zárolt"

  "Move"
  "Mozgatás"

  "Must be in multicursor mode to insert numbers"
  "Számok be multicursor üzemmódban kell lennie"

  "No write permissions.  Use '!' to force write."
  "Nincs írási jogosultsága. Használja a '!' kényszeríteni írni."

  "Release Type"
  "Kiadás típusa"

  "Reload file?"
  "A fájl újratöltése"

  "Replace"
  "Csere"

  "Save request"
  "Mentés kérése"

  "Show in Sidebar"
  "Show Sidebar"

  "Starting number:"
  "A kezdő dia száma:"

  "Tcl/Tk Version"
  "Tcl/Tk változat"

  "Total Characters"
  "Teljes karakter"

  "Total Lines"
  "Teljes sorok"

  "Unable to successfully parse number string"
  "Nem lehet elemezni a biztonsági szám karakterlánc"

  "Unable to write file"
  "Nem lehet írni a fájlt"

  "Version"
  "Verzió"

}

# markers.tcl
msgcat::mcmset hu {

  "Marker name:"
  "Marker neve:"

}

# menus.tcl
msgcat::mcmset hu {

  "About"
  "Névjegy"

  "Absolute"
  "Abszolút"

  "Absolute line numbering"
  "Abszolút sorszámozás"

  "Align Cursors"
  "Igazítás kurzorok"

  "Align cursors"
  "Igazítás kurzorok"

  "Append Next Occurrence"
  "Ráakaszt a következ? alkalom emlékeztet?je"

  "Append next occurrence"
  "Ráakaszt a következő alkalom emlékeztetője"

  "Auto-Indent"
  "Automatikus behúzás"

  "Bubble Down"
  "Buborék le"

  "Bubble Up"
  "Buborék fel"

  "Bubble lines down one line"
  "Buborék vonalak egy sorral lefelé"

  "Bubble lines up one line"
  "Buborék vonalak felfelé egy sornyit"

  "Change Working Directory"
  "Munkakönyvtár megváltoztatása"

  "Change working directory"
  "Változás működő címtár"

  "Character"
  "Karakter"

  "Check for Update"
  "Ellenőrizze a Frissítés"

  "Check for update"
  "Frissítések keresése most"

  "Classic Mac"
  "Klasszikus Mac"

  "Clear All"
  "Minden törlése"

  "Close All"
  "Az összes ablak bezárása"

  "Close Current"
  "Az aktuális lap bezárása"

  "Close all tabs"
  "Összes fül bezárása"

  "Close current session"
  "Az aktív munkafolyamat nevének megváltoztatása"

  "Close current tab"
  "Az aktuális lap bezárása"

  "Command"
  "Parancs"

  "Command Result"
  "A parancs eredménye"

  "Convert case to lower"
  "Megtérít eset, hogy az alacsonyabb"

  "Convert case to title"
  "Megtérít eset, cím"

  "Convert case to upper"
  "Megtérít eset, felső"

  "Copy"
  "Másolás"

  "Copy text"
  "A szöveg másolása"

  "Create"
  "Létrehozás"

  "Create at Current Line"
  "Az aktuális sor létrehozása"

  "Create marker at current line"
  "Marker létrehozása az aktuális sorhoz"

  "Create new plugin"
  "Hozzon létre új plugin"

  "Current Line"
  "Az aktuális sor:"

  "Current Number"
  "Az aktuális sor száma"

  "Current Word"
  "Aktuális szó"

  "Cursor"
  "Kurzor"

  "Cursor from Line Start"
  "A kurzort az elejétől sor"

  "Cursor to Line End"
  "Kurzort a vonal végét"

  "Cut"
  "Kivágás"

  "Cut text"
  "Vágott szöveg"

  "Delete current file"
  "Az aktuális törlése"

  "Delete current line"
  "Az aktuális törlése"

  "Delete current word"
  "Az aktuális törlése"

  "Delete from cursor to end of line"
  "Törli a kurzor, hogy vessen véget a sor"

  "Delete from start of line to cursor"
  "Törlés a sor elejére kurzor"

  "Delete session"
  "Munkamenetek törlése"

  "Delete template"
  "Sablon törlése"

  "Delete text between character"
  "Szöveg közötti karakter törlése"

  "Delete the current number"
  "Törli az aktuális száma"

  "Delete the whitespace to left of cursor"
  "A kurzor balra szóközt törölni"

  "Delete the whitespace to right of cursor"
  "A whitespace-a kurzor jobbra törlése"

  "Disable Vim mode"
  "Vim mód letiltása"

  "Display Text Info"
  "Szöveg adatainak megjelenítése"

  "Display text information"
  "Megjeleníti a szöveges információk"

  "Duplicate current file"
  "Ismétlődő aktuális fájl"

  "Edit"
  "Szerkesztés"

  "Edit Custom Abbreviations"
  "Egyéni rövidítések szerkesztése"

  "Edit Language"
  "Nyelvre"

  "Edit Session"
  "Élő munkamenet szerkesztése"

  "Edit User"
  "Felhasználó szerkesztése"

  "Edit custom Emmet abbreviations"
  "Egyéni Emmet rövidítések szerkesztése"

  "Edit language snippets"
  "Sajtó alá helyez a nyelvi mozaik"

  "Edit session current language preferences"
  "Munkamenet aktuális nyelvi beállítások szerkesztése"

  "Edit session global preferences"
  "Munkamenet globális beállítások szerkesztése"

  "Edit template"
  "Sablon szerkesztése"

  "Edit user current language preferences"
  "Szerkesztheti a felhasználó aktuális nyelvi beállításai"

  "Edit user global preferences"
  "Felhasználói globális beállítások szerkesztése"

  "Edit user menu bindings"
  "Felhasználó menü kötések szerkesztése"

  "Edit user snippets"
  "Kódrészletek felhasználó szerkesztése"

  "Enable Vim mode"
  "Vim-üzemmód engedélyezése"

  "Enumeration"
  "számláló"

  "Expand Abbreviation"
  "A rövidítések kibontása"

  "Expand Emmet abbreviation"
  "Bontsa ki a Emmet rövidítése"

  "Favorite file"
  "Kedvenc"

  "File"
  "Fájl"

  "File Contents"
  "Fájl tartalma"

  "Find In Files"
  "Keresés fájlokban"

  "Find Matching Pair"
  "Keressük meg a megfelel? pár"

  "Find and Replace"
  "Keresés és csere"

  "Find in files"
  "Keresés fájlokban"

  "Find matching character pair"
  "Találni párja karakter"

  "Find next occurrence"
  "Talál a következő alkalom emlékeztetője"

  "Find previous occurrence"
  "Még a korábbi előfordulása"

  "Fold All"
  "Fold minden"

  "Fold Method"
  "Hajtsa be a módszer"

  "Fold Selected"
  "Hajtsa be a kiválasztott"

  "Fold all"
  "Fold minden"

  "Fold selected code"
  "Hajtsa be a kiválasztott kód"

  "Folding"
  "Összecsukható"

  "Format Text"
  "Szöveg formázása"

  "Format indentation for text"
  "Formátum a behúzás a szöveg"

  "From Clipboard"
  "A vágólapról"

  "Global"
  "Összes"

  "Goto Last Tab"
  "Ugrás az utolsó lap"

  "Goto Next Tab"
  "Ugrás a következő lap"

  "Goto Other Pane"
  "Goto Egyéb panel"

  "Goto Previous Tab"
  "Ugrás az előző lap"

  "Goto last tab"
  "Goto utolsó pánt"

  "Goto next difference"
  "Goto következő különbség"

  "Goto next tab"
  "Ugrás a következő lapra"

  "Goto other pane"
  "Ugrás másik ablaktábla"

  "Goto previous difference"
  "Az előző eltérés"

  "Goto previous tab"
  "﻿Előző lap"

  "Help"
  "Segítség"

  "Hide Console"
  "Elrejtése Console"

  "Hide Line Numbers"
  "Sorszámok elrejtése"

  "Hide Marker Map"
  "Elrejtése jelölőtérkép"

  "Hide Meta Characters"
  "Meta-karakterek elrejtése"

  "Hide Sidebar"
  "Az oldalsáv elrejtése"

  "Hide Status Bar"
  "Az állapotsor elrejtése"

  "Hide Tab Bar"
  "A fülek elrejtése"

  "Hide console"
  "Konzol elrejtése"

  "Hide line numbers"
  "Sorszámok elrejtése"

  "Hide marker map"
  "Elrejtése jelölőtérkép"

  "Hide meta characters"
  "Meta-karakterek elrejtése"

  "Hide sidebar"
  "Az oldalsáv elrejtése"

  "Hide status bar"
  "Az állapotsor elrejtése"

  "Hide tab bar"
  "A fülek elrejtése"

  "Indent"
  "Behúzás"

  "Indent Off"
  "Francia le"

  "Indent selected text"
  "Kijelölt szöveg behúzása"

  "Indentation"
  "benyomódás"

  "Insert"
  "Beillesztés"

  "Insert command result after current line"
  "Aktuális sor után helyezze be a parancs eredménye"

  "Insert enumeration"
  "Helyezze be a számbavétel"

  "Insert file contents after current line"
  "Aktuális sor után helyezze be a fájl tartalma"

  "Insert from clipboard"
  "Beszúrás a vágólapról"

  "Insert line above current line"
  "Aktuális sor fölött sor beszúrása"

  "Insert line below current line"
  "Helyezze be a sorral lejjebb a sort"

  "Insert snippet"
  "Kódrészlet beszúrása"

  "Install"
  "Telepítés"

  "Install plugin"
  "A plugin telepítése"

  "Join Lines"
  "Sorok összevonása"

  "Join lines"
  "Sorok összevonása"

  "Jump Backward"
  "Ugrás hátra"

  "Jump Forward"
  "Ugrás elõre"

  "Jump To Line"
  "Ugrás a sor"

  "Jump backward"
  "Ugrás hátra"

  "Jump forward"
  "Ugrás elõre"

  "Jump to line"
  "Ugrás a sor"

  "Language"
  "Nyelv"

  "Launcher"
  "Rakétaindító állvány"

  "Line Above Current"
  "Folyó feletti line"

  "Line Below Current"
  "Vonal alatt folyó"

  "Line Ending"
  "Vonal vége"

  "Line Number"
  "Sor száma"

  "Line Numbering"
  "Sorszámozás"

  "Lock"
  "Zárolás"

  "Lock file"
  "Zároló fájl"

  "Lower Case"
  "Alsó-ügy"

  "Manual"
  "Használati útmutató"

  "Markers"
  "Markerek"

  "Menu"
  "Menü"

  "Menu Bindings"
  "Menü Bindings"

  "Merge Panes"
  "Összeolvad ablaktáblát"

  "Merge panes"
  "Összeolvad ablaktáblát"

  "Move Cursors Down"
  "Kurzorok lejjebb"

  "Move Cursors Left"
  "Kurzor balra"

  "Move Cursors Right"
  "Kurzorok jobbra"

  "Move Cursors Up"
  "Kurzorok feljebb"

  "Move cursor to bottom of screen"
  "Mozgassa a kurzort a képernyő alsó részén"

  "Move cursor to end of current line"
  "Mozgassa a kurzort a végéig az aktuális sorhoz"

  "Move cursor to first line"
  "Vigye a kurzort az első sorban"

  "Move cursor to last line"
  "Mozog kurzor-hoz utolsó vonal"

  "Move cursor to middle of screen"
  "Mozgassa a kurzort a képernyő közepén"

  "Move cursor to next page"
  "Mozog kurzor-hoz következő oldal"

  "Move cursor to next word"
  "Kurzor áthelyezése a következő szó"

  "Move cursor to previous page"
  "Kurzor mozgatása az előző oldalra"

  "Move cursor to previous word"
  "Kurzor áthelyezése az előző szó"

  "Move cursor to start of current line"
  "Mozgassa a kurzort a jelenlegi sor elejére"

  "Move cursor to top of screen"
  "Mozgassa a kurzort a képernyő felső részén"

  "Move multicursors down one line"
  "Multicursors lefelé lépés egy sorral"

  "Move multicursors left one line"
  "Multicursors balra egy sor mozgatása"

  "Move multicursors right one line"
  "Multicursors jobb egy sor mozgatása"

  "Move multicursors up one line"
  "Áthelyezés multicursors felfelé egy sornyit"

  "Move to First Line"
  "Első sorban áthelyezése"

  "Move to Last Line"
  "Mozog-hoz utolsó vonal"

  "Move to Line End"
  "Áthelyezése a vonal végén"

  "Move to Line Start"
  "Mozog-hoz elkezd vonal"

  "Move to Next Page"
  "Mozog-hoz következő oldal"

  "Move to Next Word"
  "Áthelyezése a következő szó"

  "Move to Previous Page"
  "Mozog-hoz előző oldal"

  "Move to Previous Word"
  "Mozog-hoz előző szó"

  "Move to Screen Bottom"
  "Mozgassa a képernyő alján"

  "Move to Screen Middle"
  "Mozgassa a képernyő közepén"

  "Move to Screen Top"
  "Mozgatni a képernyőn tetején"

  "Move to other pane"
  "Áthelyezése másik ablaktábla"

  "New From Template"
  "Új sablonból"

  "New Window"
  "Új ablak"

  "New file"
  "Új fájl"

  "New file from template"
  "Új sablonból"

  "New window"
  "Új ablakban"

  "Next Difference"
  "A következ? eltérés"

  "Open Directory"
  "Felső szintű könyvtár"

  "Open Favorite"
  "Nyílt Favorite"

  "Open File"
  "Fájl megnyitása"

  "Open Recent"
  "Legutóbbi megnyitása"

  "Open directory"
  "Felső szintű könyvtár"

  "Open file"
  "Fájl megnyitása"

  "Paste"
  "Beillesztés"

  "Paste and Format"
  "Paste és formátum"

  "Paste and format text from clipboard"
  "Beillesztés és a formátum a vágólapon levő szöveget"

  "Paste text from clipboard"
  "Szöveg beillesztése a vágólapról"

  "Plugins"
  "Pluginek"

  "Preferences"
  "Preferencia"

  "Previous Difference"
  "Előző különbség"

  "Profiling Report Sorted By"
  "Profilkészítés jelentés szerint rendezve"

  "Profiling started"
  "Profilozási kezdődött"

  "Profiling stopped"
  "Profilozási megállt"

  "Quit"
  "Kilépés"

  "Quit application"
  "Kilépés az alkalmazásból"

  "Redo"
  "Ismét"

  "Relative"
  "Átlagos"

  "Relative line numbering"
  "Relatív sorszámozás"

  "Reload"
  "Újratölt"

  "Reload all plugins"
  "Újratöltése minden dugó"

  "Reload snippets"
  "Reload-töredék"

  "Reload template information"
  "Reload információjához"

  "Remove All Markers"
  "Összes jelöl?jének eltávolítása"

  "Remove Fold"
  "Távolítsa el a Fold"

  "Remove From Current Line"
  "Távolítsa el az aktuális sorból"

  "Remove all markers"
  "Összes jelölőjének eltávolítása"

  "Remove fold on current line"
  "Távolítsa el a fold az aktuális sorban"

  "Remove marker from current line"
  "Jelölő eltávolítása az aktuális sorhoz"

  "Rename current file"
  "Aktuális fájl átnevezése"

  "Reopen File"
  "Nyissa meg a fájlt"

  "Reopen current file"
  "Nyissa meg az aktuális fájl"

  "Replace Line With Script"
  "Helyettesít a vonal kézírás"

  "Replace line with script"
  "Helyettesít a vonal kézírás"

  "Reset User to Base"
  "Reset a felhasználói bázis"

  "Restart"
  "Újraindítás"

  "Run"
  "Futtatás"

  "Run theme editor"
  "Fuss téma szerkesztő"

  "Save All"
  "Az összes dokumentum mentése"

  "Save As Template"
  "A sablon mentése"

  "Save Current"
  "Aktuális mentése"

  "Save Selection As"
  "Save kiválasztás"

  "Save all files"
  "Minden fájl mentése"

  "Save current session"
  "El szeretné menteni az aktuális munkamenetet?"

  "Save file"
  "Fájl mentése"

  "Save file as"
  "Mentés másként"

  "Save file as template"
  "A fájl mentése sablonként"

  "Save selected lines"
  "Kijelölt sorok mentése"

  "Save sessions as"
  "Megment a gyűlés mint"

  "Select All"
  "Összes kijelölése"

  "Select All Occurrences"
  "Válassza ki az összes el?fordulás"

  "Select Next Occurrence"
  "Válassza ki a következ? alkalom emlékeztet?je"

  "Select Previous Occurrence"
  "Jelölje be az el?z?t"

  "Select all occurrences"
  "Válassza ki az összes előfordulás"

  "Select all text"
  "Az összes szöveg kijelölése"

  "Send Bug Report"
  "Hibajelentés küldése."

  "Send Feedback"
  "Visszajelzés küldése"

  "Send bug report"
  "Hibajelentés küldése."

  "Send feedback"
  "Visszajelzés küldése"

  "Sessions"
  "Ülések"

  "Set Syntax"
  "Beállítása Syntax"

  "Set Theme"
  "Állítsa téma"

  "Set User to Global"
  "Állítsa be a felhasználó, a globális"

  "Set current file line ending to CR for Classic Mac"
  "Állítsa be az aktuális fájl vonal megszüntetése a CR klasszikus Mac"

  "Set current file line ending to CRLF for Windows"
  "Állítsa be az aktuális fájl sorvégi CRLF for Windows"

  "Set current file line ending to LF for Unix"
  "Állítsa be az aktuális fájl vonal megszüntetése az LF UNIX"

  "Set folding method to manual"
  "Kézi módszer összecsukható készlet"

  "Set folding method to none"
  "Hajtogatás nincs mód beállítása"

  "Set folding method to syntax"
  "Módszer a mondattan összecsukható készlet"

  "Set indent mode to"
  "Rovátka mód beállítása"

  "Set user bindings to global bindings"
  "Állítsa be a felhasználó kötések globális kötések"

  "Set user preferences to global preferences"
  "Állítsa be a felhasználói beállítások a globális beállítások"

  "Show Console"
  "Megjelenítése Console"

  "Show Diagnostic Logfile"
  "Diagnosztikai naplófájl megjelenítése"

  "Show File Difference"
  "Térkép fájl különbség"

  "Show Last Profiling Report"
  "Az utolsó Profiling jelentés"

  "Show Line Numbers"
  "A sorszámok megjelenítése"

  "Show Marker Map"
  "Jelölős Térkép megjelenítése"

  "Show Meta Characters"
  "Meta-karakterek megjelenítése"

  "Show Selected Line Change"
  "Megjelenítése a kijelölt sor módosítása"

  "Show Sidebar"
  "Az oldalpanel megjelenítése"

  "Show Status Bar"
  "Az állapotsor megjelenítése"

  "Show Tab Bar"
  "A fülek megjelenítése"

  "Show console"
  "Térkép-konzol"

  "Show diagnostic logfile"
  "Diagnosztikai naplófájl megjelenítése"

  "Show file difference"
  "Térkép fájl különbség"

  "Show last profiling report"
  "Utolsó profil jelentés megjelenítése"

  "Show line numbers"
  "A sorszámok megjelenítése"

  "Show marker map"
  "Jelölős Térkép megjelenítése"

  "Show meta characters"
  "Meta-karakterek megjelenítése"

  "Show selected line change"
  "Megjelenítése a kijelölt sor módosítása"

  "Show sidebar"
  "Oldalsáv megjelenítése?"

  "Show status bar"
  "Az állapotsor megjelenítése"

  "Show tab bar"
  "A fülek megjelenítése"

  "Smart Indent"
  "Intelligens francia"

  "Snippet"
  "Töredék"

  "Snippets"
  "Snippets"

  "Sort Tabs"
  "Sort Tabs"

  "Sort tabs"
  "Lapok rendezése"

  "Start Profiling"
  "Kezdje Profiling"

  "Start profiling"
  "Profilkészítés indítása"

  "Stop Profiling"
  "Állítsa Profiling"

  "Stop profiling"
  "Profilkészítés leállítása"

  "Switch To"
  "Kapcsol-hoz"

  "Switch to session"
  "Kapcsol-hoz gyűlés"

  "Tabs"
  "Lapfülek"

  "Templates"
  "Sablonok"

  "Text Between Character"
  "Karakter közé szöveget helyezünk"

  "Title Case"
  "Szókezdő nagybetű"

  "Toggle Case"
  "Kisbetű-nagybetű váltás"

  "Toggle Comment"
  "Toggle megjegyzés"

  "Toggle case of current character"
  "Váltás az aktuális karakter"

  "Toggle comment"
  "Toggle megjegyzés"

  "Toggle split view mode"
  "Toggle osztott nézetben"

  "Tools"
  "Eszközök"

  "Transform"
  "transzformáció"

  "Undo"
  "Visszavonás"

  "Unfavorite file"
  "Unfavorite fájl"

  "Unfold All"
  "Bontakozik ki, minden"

  "Unfold all"
  "Bontakozik ki, minden"

  "Unindent"
  "Behúzásának megszüntetése"

  "Unindent selected text"
  "A kijelölt szöveg kiengedése"

  "Uninstall"
  "Eltávolítás"

  "Uninstall plugin"
  "Távolítsa el a plugin"

  "Unix"
  "Unix"

  "Unlock"
  "Kinyit"

  "Unlock file"
  "Fájl kinyit"

  "Upper Case"
  "Nagybetű"

  "User Guide"
  "Jogi keret"

  "View"
  "Megjelenítés"

  "View Base"
  "Alap nézet"

  "View Global"
  "Globális nézet"

  "View base preferences file"
  "Nézetfájl alap beállítások"

  "View global menu bindings"
  "Nézd globális menü kötések"

  "View user guide"
  "Használati útmutató"

  "Vim Mode"
  "Vim Mode"

  "Whitespace Backward"
  "Szóköz visszafelé"

  "Whitespace Forward"
  "Szóköz-előre"

  "Windows"
  "Windows"

}

# plugins.tcl
msgcat::mcmset hu {

  "Always grant from developer"
  "Mindig megadja a fejlesztőtől"

  "ERROR"
  "HIB"

  "ERROR:  Plugin name already exists"
  "HIBA: Plugin már létezik"

  "ERROR:  Plugin name is not valid (only alphanumeric and underscores are allowed)"
  "HIBA: Plugin neve nem érvényes (csak alfanumerikus és aláhúzás megengedett)"

  "ERROR:  Unable to create plugin directory"
  "HIBA: Nem sikerült létrehozni a plugin könyvtárban"

  "ERROR:  Unable to write plugin files"
  "HIBA: Nem lehet írni a plugin fájlok"

  "Enter plugin name"
  "Adja meg a bővítmény név"

  "Grant"
  "Az oltalom megadása"

  "Grant permission?"
  "Engedélyt adhat?"

  "OK"
  "OK"

  "Plugin Errors"
  "Plugin hibák"

  "Plugin Trust Requested"
  "Plugin Trust Kért"

  "Plugin installed"
  "Plugin telepítve"

  "Plugin requires permission to view or modify your system."
  "Plugin engedélye szükséges megtekintheti és módosíthatja a rendszer."

  "Plugin uninstalled"
  "Eltávolította a plugin"

  "Plugins successfully reloaded"
  "Plugins sikeresen reloaded"

  "Reject"
  "Elutasítás"

  "Syntax errors found in selected plugins"
  "Syntax hibát talált a kiválasztott plugins"

}

# search.tcl
msgcat::mcmset hu {

  "No files found in specified directories"
  "Nem található a megadott könyvtárak fájl"

  "No search results found"
  "Nincs találat"

  "Search wrapped to beginning of file"
  "Keresés becsomagolt fájl elejére"

  "Search wrapped to end of file"
  "Keresés csomagolva, hogy a fájl vége"

  "substitutions done"
  "helyettesítések tenni"

}

# sessions.tcl
msgcat::mcmset hu {

  "Save session?"
  "A munkamenet mentése"

  "Session state will be lost if not saved"
  "Sessionnel elvész, ha nem mentette"

}

# sidebar.tcl
msgcat::mcmset hu {

  "Add Parent Directory"
  "Szülő mappa"

  "Close Directory Files"
  "Bezárása Directory fájlok"

  "Copy Pathname"
  "Elérési út másolása"

  "Delete directories?"
  "Törli a könyvtárakat?"

  "Delete directory?"
  "Könyvtár törlése?"

  "Delete file?"
  "A fájl törlése"

  "Delete files?"
  "A fájlok törlése"

  "Directory Name:"
  "Könyvtár neve:"

  "Folder Name:"
  "Mappa"

  "Image displayed in sidebar to indicate that a file is currently opened in an editing buffer."
  "A kép megjelenik a sidebar, jelezve, hogy a fájl jelenleg megnyitott egy szerkesztési puffer."

  "Make Current Working Directory"
  "Legyen aktuális könyvtár"

  "New Directory"
  "Új könyvtár"

  "New File From Template"
  "Új sablonból"

  "Open Directory Files"
  "Open Directory fájlok"

  "Refresh Directory Files"
  "Frissítés Directory fájlok"

  "Remove Parent from Sidebar"
  "Vegye szülőnek Sidebar"

  "Remove from Sidebar"
  "Eltávolítás a Sidebar"

  "Show Difference"
  "Különbség Térkép"

}

# snippets.tcl
msgcat::mcmset hu {

  "Snippet: *"
  "Töredék: *"

}

# syntax.tcl
msgcat::mcmset hu {

  "Syntax error in syntax file"
  "Szintaktikai hiba a fájl szintaxisa"

}

# templates.tcl
msgcat::mcmset hu {

  "Delete template?"
  "Sablon törlése?"

  "Template"
  "Sablon"

  "Template Name"
  "Sablon neve"

  "deleted"
  "törölve"

  "saved"
  "Mentve."

  "will be permanently deleted"
  "véglegesen törlődnek"

}

# theme.tcl
msgcat::mcmset hu {

  "Background (trough) color used in the sidebar scrollbar."
  "Háttér (maradék) használt szín a tálaló görgetősáv."

  "Background (trough) color used in the text scrollbars."
  "Háttér (maradék) használt szín a szövegben gördítősávját."

  "Background color for all sidebar items that are not selected."
  "Háttérszíne minden sidebar elem, hogy nem választott."

  "Background color for all sidebar items that are selected."
  "Háttérszíne minden oldalsáv elemek vannak jelölve."

  "Background color in difference viewer that shows added lines."
  "Háttérszíne különbség nézőt, amely megmutatja hozzáadott sorokat."

  "Background color in difference viewer that shows deleted lines."
  "Háttérszíne különbség nézőt, amely azt mutatja törölt sor."

  "Background color of insertion cursor and background marker colors."
  "Háttérszíne behelyezés kurzor és a háttér marker színek."

  "Background color of the editing buffer."
  "Háttérszíne szerkesztési puffer."

  "Background color to display when a button-like ttk widget is pressed."
  "Háttérszínt jelenik meg, amikor egy gomb-szerű TTK widgetet van nyomva."

  "Background color to use for selected text."
  "Háttérszínt használja a kiválasztott szöveget."

  "Background color used for all other tabs that are not the current/active tab in the tabbar."
  "Háttér színe mint az összes többi fülek, amelyek nem a jelenlegi / aktív lap tabbar."

  "Background color used for the current/active menu item."
  "Háttérszínt használják a jelenlegi / aktív menüpontot."

  "Background color used for the current/active tab in the tabbar."
  "Háttérszínt használják a jelenlegi / aktív lap tabbar."

  "Background color used in highlighted text."
  "Háttérszínt használják kijelölt szöveget."

  "Background color used in menus."
  "Háttér színe a menükben alkalmazott."

  "Background color used in the tabbar area."
  "Háttérszínt használt tabbar területen."

  "Color of border drawn around active editing buffer."
  "Színe határ köré rajzolt aktív szerkesztési puffer."

  "Color of ttk entry widget text border when the entry has keyboard focus."
  "Színe TTK beviteli dobozon szöveget határt, amikor a bejegyzésnek a fókuszt."

  "Color used to draw the warning width line in the editing buffer (as well as the line separating the gutter from the editing buffer)."
  "Színes hívják fel a figyelmeztető széles vonal a szerkesztési puffer (valamint az elválasztó vonal az ereszcsatorna a szerkesztési puffer)."

  "Default 'darkcolor' for all ttk widgets."
  "Alapértelmezett &quot;darkcolor&quot; minden TTK kütyü."

  "Default background color to use for all ttk widgets that are in a disabled state."
  "Alapértelmezett háttérszín használható minden TTK widgeteket letiltott állapotú."

  "Default background color to use for all ttk widgets when the mouse cursor hovers over the widget."
  "Alapértelmezett háttérszín használható minden TTK kütyü, amikor a egérkurzora a widget."

  "Default background color to use for all ttk widgets."
  "Alapértelmezett háttérszín használható minden TTK kütyü."

  "Default border color for all ttk widgets."
  "Alapértelmezett keret színe minden TTK kütyü."

  "Default color for non-syntax highlighted text."
  "Alapértelmezett színe nem szintaxis kijelölt szöveget."

  "Default foreground text color to use for all ttk widgets that are in a disabled state."
  "Alapértelmezett előtérben szöveg színe használható minden TTK widgeteket letiltott állapotú."

  "Default foreground text color to use for all ttk widgets."
  "Alapértelmezett előtérben szöveg színe használható minden TTK kütyü."

  "Determines the number of grips strips to display in the grip area between resizable panes."
  "Meghatározza száma markolatok csíkok jelennek meg a markolat között átméretezhető táblát."

  "Determines the thickness of the grip area between resizable panes."
  "Meghatározza a vastagsága a markolat között átméretezhető táblát."

  "ERROR:  Unable to read"
  "HIBA: Nem lehet olvasni"

  "Foreground (slider) color used in the sidebar scrollbar."
  "Előtér (slider) használt szín a tálaló görgetősáv."

  "Foreground (slider) color used in the text scrollbars."
  "Előtér (slider) használt szín a szövegben gördítősávját."

  "Foreground color used in menu items with checks or buttons."
  "A festőszín használt menüpontok ellenőrzéseket és a gombok."

  "Foreground text color for strings."
  "Előtérben szövegszínt szálakat."

  "Foreground text color to use for all miscellaneous1 labeled text."
  "Előtér szöveg színe használható minden miscellaneous1 jelölt szöveget."

  "Foreground text color to use for all miscellaneous2 labeled text."
  "Előtér szöveg színe használható minden miscellaneous2 jelölt szöveget."

  "Foreground text color to use for all miscellaneous3 labeled text."
  "Előtér szöveg színe használható minden miscellaneous3 jelölt szöveget."

  "Foreground text color to use for comments."
  "Előtér szöveg színe használni véleményezésre."

  "Foreground text color to use for displaying line numbers."
  "Előtér szöveget használandó színt megjelenítő sorszámok."

  "Foreground text color to use for displaying numbers."
  "Előtér szöveget használandó színt megjelenítő számokat."

  "Foreground text color to use for language-specific keywords."
  "Előtér szöveg színe használni nyelv-specifikus kulcsszavakat."

  "Foreground text color to use for language-specific punctuation."
  "Előtér szöveg színe használni nyelvspecifikus írásjelek."

  "Foreground text color to use for meta syntax."
  "Előtér szöveg színe használni meta szintaxist."

  "Foreground text color to use for precompiler syntax."
  "Előtér szöveg színe használni előfordítóra szintaxist."

  "Foreground text color to use for selected text."
  "Előtér szöveg színe használni a kiválasztott szöveget."

  "Foreground text color used for all other tabs that are not the current/active tab in the tabbar."
  "Előtérben lévő szöveg színe más lapok, amelyek nem az aktuális aktív lap kalanderez."

  "Foreground text color used for menus item that are disabled."
  "Előtérben szöveg színe használt menük elem, hogy le van tiltva."

  "Foreground text color used for the current/active menu item."
  "Előtérben szöveg színét használják az aktuális / aktív menüpontot."

  "Foreground text color used for the current/active tab in the tabbar."
  "Előtérben az aktuális aktív lap kalanderez használt szövegszín."

  "Foreground text color used in menus."
  "Előtérben szöveg színe a menükben alkalmazott."

  "Foreground text/image color used in tabbar and tabs."
  "Előtérben a szöveg / kép használt szín a tabbar és a lapok."

  "Images"
  "Képek"

  "Maximum thickness of the text scrollbar when it is active."
  "Maximális vastagsága a szöveg görgetősávot amikor aktív."

  "Maximum thickness of the text scrollbars when they are active."
  "Maximális vastagsága a szöveg görgetősávok, amikor azok aktívak."

  "Menu Options"
  "Menü beállítások"

  "Menu relief value."
  "Menü megkönnyebbülés értéket."

  "Pixel height of the tabbar widget."
  "Pixel magassága tabbar widget."

  "Relief used in drawing the tabs."
  "Relief a rajzoláshoz a lapok."

  "Relief value of the sidebar area."
  "Relief értéke az oldalsáv terület."

  "Sidebar Options"
  "Oldalsáv beállítások"

  "Sidebar Scrollbar Options"
  "Sidebar Scrollbar opciók"

  "Specifies the color to display around the sidebar when the sidebar does not have the focus."
  "Meghatározza a színt megjeleníteni körül a tálaló, amikor a oldalsáv nem rendelkezik a hangsúly."

  "Specifies the color to display around the sidebar when the sidebar has the focus."
  "Meghatározza a színt megjeleníteni körül a tálaló, amikor a oldalsáv a hangsúly."

  "Specifies the default background color to use for text that is selected in a standard ttk widget (this does not include the editing buffer)."
  "Megadja az alapértelmezett háttérszínt használja a szöveges kiválasztott szabványos TTK widgetet (ez nem tartalmazza a szerkesztési puffer)."

  "Specifies the default foreground text color to use for text that is selected in a standard ttk widget (this does not include the editing buffer)."
  "Megadja az alapértelmezett előtér szöveget használandó színt szöveget kiválasztott szabványos TTK widgetet (ez nem tartalmazza a szerkesztési puffer)."

  "Specifies the default relief to use when drawing ttk widgets."
  "Megadja az alapértelmezett megkönnyebbülés használni, ha rajz TTK kütyü."

  "Specifies the disclosure image style to use in the sidebar."
  "Megadja a nyilvánosságra hozatal kép stílust használni az oldalsávon."

  "Specifies the pixel thickness of the highlight line."
  "Meghatározza a pixel vastagságú fénypontja sor."

  "Syntax Colors"
  "Syntax színek"

  "Tab Options"
  "Alap profilbeállítások"

  "Text Scrollbar Options"
  "Szöveg Scrollbar opciók"

  "Text color for all sidebar items that are not selected."
  "Szöveg színe minden sidebar elem, hogy nem választott."

  "Text color for all sidebar items that are selected."
  "Szöveg színe minden oldalsáv elemek vannak jelölve."

  "ttk Widget Colors"
  "TTK Widget színek"

}

# themer.tcl
msgcat::mcmset hu {

  "   Show All"
  "Az összes mutatása"

  "   Show Category"
  "~Kategória megjelenítése"

  "   Show Color"
  "Mutass Szín"

  "   Show Selected Option"
  "Mutasd a kiválasztott opció"

  "   Show Selected Value"
  "Mutasd a kiválasztott érték"

  "Categories"
  "Kategóriák"

  "Change Base Color"
  "Változás alapszín"

  "Choose Theme"
  "Válasszon téma"

  "Custom Directory"
  "más könyvtárból:"

  "Custom..."
  "Egyedi…"

  "Delete swatch?"
  "Törlés Swatch?"

  "Description"
  "Leírás"

  "Details"
  "Részletek"

  "Done"
  "Kész"

  "Export"
  "Exportálás"

  "GIF Photo"
  "GIF Fotó"

  "Import"
  "Import"

  "Import BMP Data"
  "Import BMP adatok"

  "Import BMP Mask"
  "Import BMP Mask"

  "Import Error"
  "Import Error"

  "Import Theme File"
  "Import témafájlt"

  "Installation Directory"
  "Telepítési könyvtár"

  "Modifications"
  "Módosítások"

  "One-Color Bitmap"
  "Egy-Color Bitmap"

  "Preview"
  "Előnézet"

  "Relief: "
  "Megkönnyebbülés"

  "Save As:"
  "Mentés másként"

  "Save theme changes?"
  "Mentsd téma változik?"

  "Select Directory"
  "Válasszon ki egy könyvtárat"

  "Swatch"
  "Mintadarab"

  "Swatch Colors"
  "Swatch színek"

  "Table Filters"
  "Táblázat szűrők"

  "The current theme has unsaved changes"
  "Az aktuális téma nem mentett módosításokat tartalmaz"

  "Tree Style: "
  "Fa Stílus:"

  "Two-Color Bitmap"
  "Két-Color Bitmap"

  "User Directory"
  "Saját könyvtár"

  "Value"
  "Érték"

  "Value: "
  "Érték:"

}

# themes.tcl
msgcat::mcmset hu {

  "Theme"
  "Sablon"

  "Theme:*"
  "Sablon*"

}

# tke.tcl
msgcat::mcmset hu {

  "Import TKE theme?"
  "Import TKE témát?"

  "Import TextMate theme?"
  "Import TextMate témát?"

}

# tkedat.tcl
msgcat::mcmset hu {

  "Unable to read"
  "A fájl beolvasása nem sikerült."

}

# vim.tcl
msgcat::mcmset hu {

  "File format unrecognized"
  "Ismeretlen fájlformátum"

  "Filename directory does not exist"
  "Fájlnév könyvtár nem létezik"

  "Folding method unrecognized"
  "Ismeretlen módszer összecsukható"

  "Illegal modelines value"
  "Illegális hardverednek érték"

  "Number width not a number"
  "Szám szélessége nem szám"

  "Shiftwidth value is not an integer"
  "Shiftwidth értéke nem egész szám"

  "Tabstop value is not an integer"
  "TabStop értéke nem egész szám"

  "Unrecognized vim option"
  "Ismeretlen vim lehetőség"

}

# General
msgcat::mcmset hu {

  "Cancel"
  "Mégsem"

  "Close"
  "Bezárás"

  "Delete"
  "Törlés"

  "Duplicate"
  "Megkettőzés"

  "Favorite"
  "Kedvenc"

  "File Name:"
  "A fájlnév"

  "Find"
  "Keresés"

  "Move to Other Pane"
  "Áthelyezni más ablak"

  "New File"
  "Új fájl"

  "None"
  "Egysem"

  "Open"
  "Nyissa"

  "Rename"
  "Átnevezés"

  "Save"
  "Mentés"

  "Save As"
  "Mentés másként"

  "Split View"
  "Osztott nézet"

  "Syntax"
  "Szintaxis"

  "Theme Editor"
  "Témaszerkesztő"

  "Unable to write"
  "Nem lehet írni"

  "Unfavorite"
  "Nem kedvenc"

}

