# api.tcl
msgcat::mcmset hu {

  "Argument list to api::add_file was not an even key/value pair"
  "Argumentumlista API :: add_file nem volt még kulcs / érték párt"

  "Plugin"
  "Bővítmény"

}

# bgproc.tcl
msgcat::mcmset hu {

  "Unable to run system command"
  "Képtelen-hoz fuss követel rendszer"

}

# diff.tcl
msgcat::mcmset hu {

  "    End: "
  "Vége:"

  "    Start: "
  "Kezdete:"

  "Enter difference command"
  "Adja meg a differencia parancs"

  "Enter starting file"
  "Adja meg a kezdő fájl"

  "Update"
  "Frissítés"

}

# edit.tcl
msgcat::mcmset hu {

  "File successfully written"
  "Fájl írása sikeresen"

  "Filename already exists"
  "Fájlnév már létezik"

}

# embed_tke.tcl
msgcat::mcmset hu {

  "Find:"
  "felfedez"

  "Replace:"
  "Csere:"

}

# gui.tcl
msgcat::mcmset hu {

  "All"
  "Minden"

  "Case sensitivity"
  "Kisbetű-nagybetű érzékenység"

  "Close All Tabs"
  "Összes fül bezárása"

  "Close Other Tabs"
  "A többi lap bezárása"

  "Close Other*"
  "A többi lap bezárása"

  "Close Tab"
  "A lap bezárása"

  "Column"
  "Oszlop"

  "Copyright"
  "Szerzői jogok"

  "Credits"
  "Jóváírások"

  "Delete tab?"
  "Törlés lap?"

  "Developer"
  "Fejlesztő"

  "Email"
  "E-mail cím"

  "Error"
  "Hiba"

  "Favorited"
  "Kedvencek"

  "File already exists.  Use '!' to force an overwrite"
  "A fájl már létezik. Használja a '!' kényszeríteni felülíró"

  "File attribute does not exist"
  "Attribútum nem létezik"

  "File index is out of range"
  "Fájl index tartományon kívül"

  "Hide Tab"
  "Fül elrejtése"

  "Image displayed in fill-in forms which closes the form UI.  Used in forms such as search, search/replace, and find in files."
  "A kép megjelenik a nyomtatványok, amely lezárja a formában UI. Használt formák, mint a keresés, keresés / csere, és megtalálni a fájlokat."

  "Image used in tab menus to indicate that the file is associated with a difference view."
  "Kép használt lap menük, jelezve, hogy a fájl társítva van különbség kilátás."

  "Image used in tab menus to indicate that the file is locked."
  "Kép használt lap menük, jelezve, hogy a fájl zárolva van."

  "Image used in tab menus to indicate that the file is readonly."
  "Kép használt lap menük, jelezve, hogy a fájl csak olvasható."

  "Image used in tab to indicate that the tab contains a difference view."
  "Kép használt lapon jelzi, hogy a lapon található különbség kilátás."

  "Image used in tab to indicate that the tab's file is readonly."
  "Kép használt lap, jelezve, hogy a lap a fájl csak olvasható."

  "Image used in tab to indicate that the tab’s file is locked."
  "Kép használt lap, jelezve, hogy a lap fájl zárolva van."

  "Image used in tab which, when clicked, closes the tab."
  "Kép használt lap, amely, ha rákattintunk, bezárja a lapot."

  "Image used in the preferences window in the Advanced tab."
  "A Speciális lapon a beállítások ablakban használt kép."

  "Image used in the preferences window in the Appearance tab."
  "A megjelenés lapon a beállítások ablakban használt kép."

  "Image used in the preferences window in the Editor tab."
  "Az Editor fülön a beállítások ablakban használt kép."

  "Image used in the preferences window in the Emmet tab."
  "A Emmet lapon a beállítások ablakban használt kép."

  "Image used in the preferences window in the Find tab."
  "A keresés lapon a beállítások ablakban használt kép."

  "Image used in the preferences window in the General tab."
  "Az Általános lapon a beállítások ablakban használt kép."

  "Image used in the preferences window in the Sidebar tab."
  "A beállítások ablakban a tálaló lapon használt kép."

  "Image used in the preferences window in the Snippets tab."
  "A kódtöredékek fülre a beállítások ablakban használt kép."

  "Image used in the preferences window in the View tab."
  "A Nézet lapon a beállítások ablakban használt kép."

  "Image used in the preferences window to indicate that a table item is deselected."
  "Jelzi, hogy egy elem nincs bejelölve a beállítások ablakban használt kép."

  "Image used in the preferences window to indicate that a table item is selected."
  "Jelzi, hogy a tábla elem van-e jelölve a beállítások ablakban használt kép."

  "Image used in the shortcuts window in the Shortcuts tab."
  "A parancsikonok ablakban a hivatkozások lapon használt kép."

  "License"
  "Licenc"

  "Line"
  "Vonal"

  "Locked"
  "Zárolt"

  "Move"
  "Mozgatás"

  "Must be in multicursor mode to insert numbers"
  "Számok be multicursor üzemmódban kell lennie"

  "No write permissions.  Use '!' to force write."
  "Nincs írási jogosultsága. Használja a '!' kényszeríteni írni."

  "Release Type"
  "Kiadás típusa"

  "Reload file?"
  "A fájl újratöltése"

  "Replace"
  "Csere"

  "Save request"
  "Mentés kérése"

  "Show in Sidebar"
  "Show Sidebar"

  "Starting number:"
  "A kezdő dia száma:"

  "Tcl/Tk Version"
  "Tcl/Tk változat"

  "Total Characters"
  "Teljes karakter"

  "Total Lines"
  "Teljes sorok"

  "Unable to successfully parse number string"
  "Nem lehet elemezni a biztonsági szám karakterlánc"

  "Unable to write file"
  "Nem lehet írni a fájlt"

  "Unable to write remote file"
  "Nem lehet írni a távoli fájl"

  "Version"
  "Verzió"

}

# markers.tcl
msgcat::mcmset hu {

  "Marker name:"
  "Marker neve:"

}

# menus.tcl
msgcat::mcmset hu {

  "About"
  "Névjegy"

  "Absolute"
  "Abszolút"

  "Absolute line numbering"
  "Abszolút sorszámozás"

  "Align Cursors"
  "Igazítás kurzorok"

  "Align Panes"
  "Összehangolják az üvegtáblák"

  "Align current lines in both panes"
  "Mindkét aktuális sorok igazítása"

  "Align cursors"
  "Igazítás kurzorok"

  "All Levels"
  "Minden szint"

  "Append Next Occurrence"
  "Ráakaszt a következ? alkalom emlékeztet?je"

  "Append next occurrence"
  "Ráakaszt a következő alkalom emlékeztetője"

  "Auto-Indent"
  "Automatikus behúzás"

  "Bubble Down"
  "Buborék le"

  "Bubble Up"
  "Buborék fel"

  "Bubble lines down one line"
  "Buborék vonalak egy sorral lefelé"

  "Bubble lines up one line"
  "Buborék vonalak felfelé egy sornyit"

  "Change Working Directory"
  "Munkakönyvtár megváltoztatása"

  "Change working directory"
  "Változás működő címtár"

  "Character"
  "Karakter"

  "Check for update"
  "Frissítések keresése most"

  "Classic Mac"
  "Klasszikus Mac"

  "Clear All"
  "Minden törlése"

  "Close All"
  "Az összes ablak bezárása"

  "Close All Folds"
  "Zárja be az összes redők"

  "Close Current"
  "Az aktuális lap bezárása"

  "Close Current Fold"
  "Zárja be a jelenlegi szeres"

  "Close Selected Folds"
  "Bezárás kiválasztott redők"

  "Close all folds"
  "Zárja be az összes redők"

  "Close all tabs"
  "Összes fül bezárása"

  "Close current session"
  "Az aktív munkafolyamat nevének megváltoztatása"

  "Close current tab"
  "Az aktuális lap bezárása"

  "Close fold at current line - all levels"
  "Aktuális sor - minden szinten szoros szeres"

  "Close fold at current line - one level"
  "Szoros szeres aktuális sor - egy szinttel"

  "Close selected folds - all levels"
  "Zárja be a kijelölt ráncok - minden szinten"

  "Close selected folds - one level"
  "Zárja be a kijelölt ráncok - egy szinttel"

  "Command"
  "Parancs"

  "Command Result"
  "A parancs eredménye"

  "Convert case to lower"
  "Megtérít eset, hogy az alacsonyabb"

  "Convert case to title"
  "Megtérít eset, cím"

  "Convert case to upper"
  "Megtérít eset, felső"

  "Copy text"
  "A szöveg másolása"

  "Create Fold From Selection"
  "A kijelölt képrész megtartása"

  "Create at Current Line"
  "Az aktuális sor létrehozása"

  "Create fold from selection"
  "A kijelölt képrész megtartása"

  "Create marker at current line"
  "Marker létrehozása az aktuális sorhoz"

  "Create new plugin"
  "Hozzon létre új plugin"

  "Current Number"
  "Az aktuális sor száma"

  "Cursor from Line Start"
  "A kurzort az elejétől sor"

  "Cursor to Line End"
  "Kurzort a vonal végét"

  "Cut"
  "Kivágás"

  "Cut text"
  "Vágott szöveg"

  "Delete All Folds"
  "Törölje az összes redők"

  "Delete Current Fold"
  "Az aktuális törlése"

  "Delete Selected Folds"
  "Törli a kijelölt redők"

  "Delete all folds"
  "Törölje az összes redők"

  "Delete all selected folds"
  "Töröl minden kijelölt redők"

  "Delete current file"
  "Az aktuális törlése"

  "Delete current line"
  "Az aktuális törlése"

  "Delete current word"
  "Az aktuális törlése"

  "Delete fold at current line"
  "Szeres aktuális sor törlése"

  "Delete from cursor to end of line"
  "Törli a kurzor, hogy vessen véget a sor"

  "Delete from start of line to cursor"
  "Törlés a sor elejére kurzor"

  "Delete session"
  "Munkamenetek törlése"

  "Delete template"
  "Sablon törlése"

  "Delete text between character"
  "Szöveg közötti karakter törlése"

  "Delete the current number"
  "Törli az aktuális száma"

  "Delete the whitespace to left of cursor"
  "A kurzor balra szóközt törölni"

  "Delete the whitespace to right of cursor"
  "A whitespace-a kurzor jobbra törlése"

  "Disable Vim mode"
  "Vim mód letiltása"

  "Disable code folding"
  "Megbénít kód összecsukható"

  "Disable two-pane scrolling Synchronization"
  "Két ablaktáblából tekerő-szinkronizálás"

  "Display Text Info"
  "Szöveg adatainak megjelenítése"

  "Display text information"
  "Megjeleníti a szöveges információk"

  "Duplicate current file"
  "Ismétlődő aktuális fájl"

  "Edit"
  "Szerkesztés"

  "Edit Custom Abbreviations"
  "Egyéni rövidítések szerkesztése"

  "Edit Language"
  "Nyelvre"

  "Edit Session"
  "Élő munkamenet szerkesztése"

  "Edit User"
  "Felhasználó szerkesztése"

  "Edit custom Emmet abbreviations"
  "Egyéni Emmet rövidítések szerkesztése"

  "Edit language snippets"
  "Sajtó alá helyez a nyelvi mozaik"

  "Edit session current language preferences"
  "Munkamenet aktuális nyelvi beállítások szerkesztése"

  "Edit session global preferences"
  "Munkamenet globális beállítások szerkesztése"

  "Edit settings sharing preferences"
  "Megosztási beállítások-beállítások szerkesztése"

  "Edit template"
  "Sablon szerkesztése"

  "Edit user current language preferences"
  "Szerkesztheti a felhasználó aktuális nyelvi beállításai"

  "Edit user global preferences"
  "Felhasználói globális beállítások szerkesztése"

  "Edit user menu bindings"
  "Felhasználó menü kötések szerkesztése"

  "Edit user snippets"
  "Kódrészletek felhasználó szerkesztése"

  "Enable Code Folding"
  "Engedélyezi a kód összecsukható"

  "Enable Synchronized Scrolling"
  "Engedélyezi a szinkronizált görgetés"

  "Enable Vim mode"
  "Vim-üzemmód engedélyezése"

  "Enable two-pane scrolling synchronization"
  "Két ablaktáblából görgetés szinkronizálásának engedélyezése"

  "Enumeration"
  "számláló"

  "Expand Abbreviation"
  "A rövidítések kibontása"

  "Expand Emmet abbreviation"
  "Bontsa ki a Emmet rövidítése"

  "Export As"
  "Exportálás mint"

  "Export Settings"
  "Beállítások exportálása"

  "Export complete"
  "Az exportálás befejeződött."

  "Export file contents"
  "Export fájl tartalma"

  "Export settings data"
  "BEÁLLÍTÁSOK EXPORTÁLÁSA"

  "Favorite file"
  "Kedvenc"

  "File Contents"
  "Fájl tartalma"

  "Find In Files"
  "Keresés fájlokban"

  "Find Matching Bracket"
  "Zárójel párjának keresése"

  "Find Next Bracket Mismatch"
  "Talál a következő zárójeles eltérés"

  "Find Previous Bracket Mismatch"
  "Még előző zárójel eltérés"

  "Find and Replace"
  "Keresés és csere"

  "Find in files"
  "Keresés fájlokban"

  "Find matching character pair"
  "Találni párja karakter"

  "Find next mismatching bracket"
  "Még a következő nem megfelelő zárójel"

  "Find next occurrence"
  "Talál a következő alkalom emlékeztetője"

  "Find previous mismatching bracket"
  "Még a korábbi hibás konzol"

  "Find previous occurrence"
  "Még a korábbi előfordulása"

  "Folding"
  "Összecsukható"

  "Format Text"
  "Szöveg formázása"

  "Format indentation for text"
  "Formátum a behúzás a szöveg"

  "From Clipboard"
  "A vágólapról"

  "Global"
  "Összes"

  "Goto Last Tab"
  "Ugrás az utolsó lap"

  "Goto Next Tab"
  "Ugrás a következő lap"

  "Goto Other Pane"
  "Goto Egyéb panel"

  "Goto Previous Tab"
  "Ugrás az előző lap"

  "Goto last tab"
  "Goto utolsó pánt"

  "Goto next difference"
  "Goto következő különbség"

  "Goto next tab"
  "Ugrás a következő lapra"

  "Goto other pane"
  "Ugrás másik ablaktábla"

  "Goto previous difference"
  "Az előző eltérés"

  "Goto previous tab"
  "﻿Előző lap"

  "Help"
  "Segítség"

  "Hide All Tabs"
  "Minden fül elrejtése"

  "Hide Console"
  "Elrejtése Console"

  "Hide Current Tab"
  "Aktuális fül"

  "Hide Line Numbers"
  "Sorszámok elrejtése"

  "Hide Marker Map"
  "Elrejtése jelölőtérkép"

  "Hide Meta Characters"
  "Meta-karakterek elrejtése"

  "Hide Sidebar"
  "Az oldalsáv elrejtése"

  "Hide Status Bar"
  "Az állapotsor elrejtése"

  "Hide Tab Bar"
  "A fülek elrejtése"

  "Hide console"
  "Konzol elrejtése"

  "Hide line numbers"
  "Sorszámok elrejtése"

  "Hide marker map"
  "Elrejtése jelölőtérkép"

  "Hide meta characters"
  "Meta-karakterek elrejtése"

  "Hide sidebar"
  "Az oldalsáv elrejtése"

  "Hide status bar"
  "Az állapotsor elrejtése"

  "Hide tab bar"
  "A fülek elrejtése"

  "Indent"
  "Behúzás"

  "Indent Off"
  "Francia le"

  "Indent selected text"
  "Kijelölt szöveg behúzása"

  "Indentation"
  "benyomódás"

  "Insert command result after current line"
  "Aktuális sor után helyezze be a parancs eredménye"

  "Insert enumeration"
  "Helyezze be a számbavétel"

  "Insert file contents after current line"
  "Aktuális sor után helyezze be a fájl tartalma"

  "Insert from clipboard"
  "Beszúrás a vágólapról"

  "Insert line above current line"
  "Aktuális sor fölött sor beszúrása"

  "Insert line below current line"
  "Helyezze be a sorral lejjebb a sort"

  "Insert snippet"
  "Kódrészlet beszúrása"

  "Install"
  "Telepítés"

  "Install plugin"
  "A plugin telepítése"

  "Join Lines"
  "Sorok összevonása"

  "Join lines"
  "Sorok összevonása"

  "Jump Backward"
  "Ugrás hátra"

  "Jump Forward"
  "Ugrás elõre"

  "Jump To Line"
  "Ugrás a sor"

  "Jump backward"
  "Ugrás hátra"

  "Jump forward"
  "Ugrás elõre"

  "Jump to Next Fold Mark"
  "Ugrás a következő Fold Mark"

  "Jump to Previous Fold Mark"
  "Ugrás az előző Fold Mark"

  "Jump to line"
  "Ugrás a sor"

  "Jump to the next fold indicator"
  "Ugrás a következő fold-jelző"

  "Jump to the previous fold indicator"
  "Ugrás az előző fold-jelző"

  "Line Above Current"
  "Folyó feletti line"

  "Line Below Current"
  "Vonal alatt folyó"

  "Line Ending"
  "Vonal vége"

  "Line Number"
  "Sor száma"

  "Line Numbering"
  "Sorszámozás"

  "Lock"
  "Zárolás"

  "Lock file"
  "Zároló fájl"

  "Lower Case"
  "Alsó-ügy"

  "Markers"
  "Markerek"

  "Menu"
  "Menü"

  "Menu Bindings"
  "Menü Bindings"

  "Merge Panes"
  "Összeolvad ablaktáblát"

  "Merge panes"
  "Összeolvad ablaktáblát"

  "Move Cursors Down"
  "Kurzorok lejjebb"

  "Move Cursors Left"
  "Kurzor balra"

  "Move Cursors Right"
  "Kurzorok jobbra"

  "Move Cursors Up"
  "Kurzorok feljebb"

  "Move cursor to bottom of screen"
  "Mozgassa a kurzort a képernyő alsó részén"

  "Move cursor to end of current line"
  "Mozgassa a kurzort a végéig az aktuális sorhoz"

  "Move cursor to first line"
  "Vigye a kurzort az első sorban"

  "Move cursor to last line"
  "Mozog kurzor-hoz utolsó vonal"

  "Move cursor to middle of screen"
  "Mozgassa a kurzort a képernyő közepén"

  "Move cursor to next page"
  "Mozog kurzor-hoz következő oldal"

  "Move cursor to next word"
  "Kurzor áthelyezése a következő szó"

  "Move cursor to previous page"
  "Kurzor mozgatása az előző oldalra"

  "Move cursor to previous word"
  "Kurzor áthelyezése az előző szó"

  "Move cursor to start of current line"
  "Mozgassa a kurzort a jelenlegi sor elejére"

  "Move cursor to top of screen"
  "Mozgassa a kurzort a képernyő felső részén"

  "Move multicursors down one line"
  "Multicursors lefelé lépés egy sorral"

  "Move multicursors left one line"
  "Multicursors balra egy sor mozgatása"

  "Move multicursors right one line"
  "Multicursors jobb egy sor mozgatása"

  "Move multicursors up one line"
  "Áthelyezés multicursors felfelé egy sornyit"

  "Move to First Line"
  "Első sorban áthelyezése"

  "Move to Last Line"
  "Mozog-hoz utolsó vonal"

  "Move to Line End"
  "Áthelyezése a vonal végén"

  "Move to Line Start"
  "Mozog-hoz elkezd vonal"

  "Move to Next Page"
  "Mozog-hoz következő oldal"

  "Move to Next Word"
  "Áthelyezése a következő szó"

  "Move to Previous Page"
  "Mozog-hoz előző oldal"

  "Move to Previous Word"
  "Mozog-hoz előző szó"

  "Move to Screen Bottom"
  "Mozgassa a képernyő alján"

  "Move to Screen Middle"
  "Mozgassa a képernyő közepén"

  "Move to Screen Top"
  "Mozgatni a képernyőn tetején"

  "Move to other pane"
  "Áthelyezése másik ablaktábla"

  "New From Template"
  "Új sablonból"

  "New Window"
  "Új ablak"

  "New file"
  "Új fájl"

  "New file from template"
  "Új sablonból"

  "New window"
  "Új ablakban"

  "Next Difference"
  "A következ? eltérés"

  "One Level"
  "Egy szinttel"

  "Open All Folds"
  "Nyissa meg az összes kiszáll"

  "Open Current Fold"
  "Nyitott aktuális Fold"

  "Open Directory"
  "Felső szintű könyvtár"

  "Open Favorite"
  "Nyílt Favorite"

  "Open File"
  "Fájl megnyitása"

  "Open Recent"
  "Legutóbbi megnyitása"

  "Open Remote"
  "Nyissa meg a távoli"

  "Open Selected Folds"
  "Nyissa meg a kiválasztott redők"

  "Open all folds"
  "Nyissa meg az összes kiszáll"

  "Open directory"
  "Felső szintű könyvtár"

  "Open file"
  "Fájl megnyitása"

  "Open fold at current line - all levels"
  "Aktuális sor - minden szinten nyitott szeres"

  "Open fold at current line - one level"
  "Nyitott szeres aktuális sor - egy szinttel"

  "Open folds to show cursor"
  "Nyitott redők kurzor megjelenítése"

  "Open remote file or directory"
  "Nyissa meg a távoli fájl vagy könyvtár"

  "Open selected folds - all levels"
  "Nyitott kijelölt ráncok - minden szinten"

  "Open selected folds - one level"
  "Nyitott kijelölt ráncok - egy szinttel"

  "Panes"
  "Panelek"

  "Paste"
  "Beillesztés"

  "Paste and Format"
  "Paste és formátum"

  "Paste and format text from clipboard"
  "Beillesztés és a formátum a vágólapon levő szöveget"

  "Paste text from clipboard"
  "Szöveg beillesztése a vágólapról"

  "Previous Difference"
  "Előző különbség"

  "Profiling Report Sorted By"
  "Profilkészítés jelentés szerint rendezve"

  "Profiling started"
  "Profilozási kezdődött"

  "Profiling stopped"
  "Profilozási megállt"

  "Quit"
  "Kilépés"

  "Quit application"
  "Kilépés az alkalmazásból"

  "Recent Directories"
  "Legutóbbi könyvtárak"

  "Recent Files"
  "Legutóbbi fájlok"

  "Redo"
  "Ismét"

  "Relative"
  "Átlagos"

  "Relative line numbering"
  "Relatív sorszámozás"

  "Reload"
  "Újratölt"

  "Reload all plugins"
  "Újratöltése minden dugó"

  "Reload snippets"
  "Reload-töredék"

  "Reload template information"
  "Reload információjához"

  "Remove All Markers"
  "Összes jelöl?jének eltávolítása"

  "Remove From Current Line"
  "Távolítsa el az aktuális sorból"

  "Remove all markers"
  "Összes jelölőjének eltávolítása"

  "Remove marker from current line"
  "Jelölő eltávolítása az aktuális sorhoz"

  "Rename current file"
  "Aktuális fájl átnevezése"

  "Reopen File"
  "Nyissa meg a fájlt"

  "Reopen current file"
  "Nyissa meg az aktuális fájl"

  "Replace Line With Script"
  "Helyettesít a vonal kézírás"

  "Replace line with script"
  "Helyettesít a vonal kézírás"

  "Reset User to Base"
  "Reset a felhasználói bázis"

  "Restart"
  "Újraindítás"

  "Run"
  "Futtatás"

  "Run theme editor"
  "Fuss téma szerkesztő"

  "Save All"
  "Az összes dokumentum mentése"

  "Save As Remote"
  "Távoli mentése"

  "Save As Template"
  "A sablon mentése"

  "Save Current"
  "Aktuális mentése"

  "Save Selection As"
  "Save kiválasztás"

  "Save all files"
  "Minden fájl mentése"

  "Save current session"
  "El szeretné menteni az aktuális munkamenetet?"

  "Save file"
  "Fájl mentése"

  "Save file as"
  "Mentés másként"

  "Save file as remote file"
  "Fájl mentése a távoli fájl"

  "Save file as template"
  "A fájl mentése sablonként"

  "Save selected lines"
  "Kijelölt sorok mentése"

  "Save sessions as"
  "Megment a gyűlés mint"

  "Select All"
  "Összes kijelölése"

  "Select All Occurrences"
  "Válassza ki az összes el?fordulás"

  "Select Next Occurrence"
  "Válassza ki a következ? alkalom emlékeztet?je"

  "Select Previous Occurrence"
  "Jelölje be az el?z?t"

  "Select all occurrences"
  "Válassza ki az összes előfordulás"

  "Select all text"
  "Az összes szöveg kijelölése"

  "Send Bug Report"
  "Hibajelentés küldése."

  "Send Feedback"
  "Visszajelzés küldése"

  "Send bug report"
  "Hibajelentés küldése."

  "Send feedback"
  "Visszajelzés küldése"

  "Set Syntax"
  "Beállítása Syntax"

  "Set Theme"
  "Állítsa téma"

  "Set User to Global"
  "Állítsa be a felhasználó, a globális"

  "Set current file line ending to CR for Classic Mac"
  "Állítsa be az aktuális fájl vonal megszüntetése a CR klasszikus Mac"

  "Set current file line ending to CRLF for Windows"
  "Állítsa be az aktuális fájl sorvégi CRLF for Windows"

  "Set current file line ending to LF for Unix"
  "Állítsa be az aktuális fájl vonal megszüntetése az LF UNIX"

  "Set indent mode to"
  "Rovátka mód beállítása"

  "Set user bindings to global bindings"
  "Állítsa be a felhasználó kötések globális kötések"

  "Set user preferences to global preferences"
  "Állítsa be a felhasználói beállítások a globális beállítások"

  "Show All Tabs"
  "Minden lapfülek megjelenítése"

  "Show Console"
  "Megjelenítése Console"

  "Show Cursor"
  "Kurzor megjelenítése"

  "Show Diagnostic Logfile"
  "Diagnosztikai naplófájl megjelenítése"

  "Show File Difference"
  "Térkép fájl különbség"

  "Show Last Profiling Report"
  "Az utolsó Profiling jelentés"

  "Show Line Numbers"
  "A sorszámok megjelenítése"

  "Show Marker Map"
  "Jelölős Térkép megjelenítése"

  "Show Meta Characters"
  "Meta-karakterek megjelenítése"

  "Show Selected Line Change"
  "Megjelenítése a kijelölt sor módosítása"

  "Show Sidebar"
  "Az oldalpanel megjelenítése"

  "Show Status Bar"
  "Az állapotsor megjelenítése"

  "Show Tab Bar"
  "A fülek megjelenítése"

  "Show diagnostic logfile"
  "Diagnosztikai naplófájl megjelenítése"

  "Show file difference"
  "Térkép fájl különbség"

  "Show last profiling report"
  "Utolsó profil jelentés megjelenítése"

  "Show meta characters"
  "Meta-karakterek megjelenítése"

  "Show selected line change"
  "Megjelenítése a kijelölt sor módosítása"

  "Smart Indent"
  "Intelligens francia"

  "Snippet"
  "Töredék"

  "Sort Tabs"
  "Sort Tabs"

  "Sort tabs"
  "Lapok rendezése"

  "Start Profiling"
  "Kezdje Profiling"

  "Start profiling"
  "Profilkészítés indítása"

  "Stop Profiling"
  "Állítsa Profiling"

  "Stop profiling"
  "Profilkészítés leállítása"

  "Switch To"
  "Kapcsol-hoz"

  "Switch to session"
  "Kapcsol-hoz gyűlés"

  "Tabs"
  "Lapfülek"

  "Text Between Character"
  "Karakter közé szöveget helyezünk"

  "Tips & Tricks"
  "Tippek és trükkök"

  "Title Case"
  "Szókezdő nagybetű"

  "Toggle Case"
  "Kisbetű-nagybetű váltás"

  "Toggle Comment"
  "Toggle megjegyzés"

  "Toggle case of current character"
  "Váltás az aktuális karakter"

  "Toggle comment"
  "Toggle megjegyzés"

  "Toggle split view mode"
  "Toggle osztott nézetben"

  "Tools"
  "Eszközök"

  "Transform"
  "transzformáció"

  "Unable to write export file"
  "Nem lehet írni az exportfájl"

  "Undo"
  "Visszavonás"

  "Unfavorite file"
  "Unfavorite fájl"

  "Unindent"
  "Behúzásának megszüntetése"

  "Unindent selected text"
  "A kijelölt szöveg kiengedése"

  "Uninstall"
  "Eltávolítás"

  "Uninstall plugin"
  "Távolítsa el a plugin"

  "Unix"
  "Unix"

  "Unlock"
  "Kinyit"

  "Unlock file"
  "Fájl kinyit"

  "Upper Case"
  "Nagybetű"

  "User Guide"
  "Jogi keret"

  "View"
  "Megjelenítés"

  "View Base"
  "Alap nézet"

  "View Global"
  "Globális nézet"

  "View base preferences file"
  "Nézetfájl alap beállítások"

  "View global menu bindings"
  "Nézd globális menü kötések"

  "View tips & tricks articles"
  "Kilátás porkoláb & trükkök cikkek"

  "View user guide"
  "Használati útmutató"

  "Vim Mode"
  "Vim Mode"

  "Whitespace Backward"
  "Szóköz visszafelé"

  "Whitespace Forward"
  "Szóköz-előre"

  "Windows"
  "Windows"

}

# plugins.tcl
msgcat::mcmset hu {

  "Always grant from developer"
  "Mindig megadja a fejlesztőtől"

  "ERROR"
  "HIB"

  "ERROR:  Plugin name already exists"
  "HIBA: Plugin már létezik"

  "ERROR:  Plugin name is not valid (only alphanumeric and underscores are allowed)"
  "HIBA: Plugin neve nem érvényes (csak alfanumerikus és aláhúzás megengedett)"

  "ERROR:  Unable to create plugin directory"
  "HIBA: Nem sikerült létrehozni a plugin könyvtárban"

  "ERROR:  Unable to write plugin files"
  "HIBA: Nem lehet írni a plugin fájlok"

  "Enter plugin name"
  "Adja meg a bővítmény név"

  "Grant"
  "Az oltalom megadása"

  "Grant permission?"
  "Engedélyt adhat?"

  "Plugin Errors"
  "Plugin hibák"

  "Plugin Trust Requested"
  "Plugin Trust Kért"

  "Plugin installed"
  "Plugin telepítve"

  "Plugin requires permission to view or modify your system."
  "Plugin engedélye szükséges megtekintheti és módosíthatja a rendszer."

  "Plugin uninstalled"
  "Eltávolította a plugin"

  "Plugins successfully reloaded"
  "Plugins sikeresen reloaded"

  "Reject"
  "Elutasítás"

  "Syntax errors found in selected plugins"
  "Syntax hibát talált a kiválasztott plugins"

}

# pref_ui.tcl
msgcat::mcmset hu {

  "Abbreviation Aliases"
  "Aliasok rövidítése"

  "Add"
  "Hozzáadás"

  "Addons"
  "Kiegészítők"

  "Allow scrolling in tab bar"
  "Lehetővé teszi, hogy görgetés a fülsávon"

  "Angled bracket"
  "Szögletes zárójel"

  "Auto-match Characters"
  "Auto-mérkőzés karakter"

  "Automatically check for updates on start"
  "Gépiesen ellenőriz részére korszerűsít-ra elkezd"

  "Automatically highlight matching bracket"
  "Automatikusan kiemelhetők a megfelelő zárójel"

  "Automatically highlight mismatching brackets"
  "Automatikusan kiemelhetők eldobhatja zárójelben"

  "Automatically insert vendor prefixes"
  "Automatikusan illessze be a szállító előtagok"

  "Automatically load last session on start"
  "Automatikusan betölti a legutóbbi ülésén a start"

  "Automatically set the current working directory to the current tabs directory"
  "Automatikusan beállítja az aktuális munkakönyvtár az aktuális fülek könyvtár"

  "Backtick"
  "Végrehajtó"

  "Base Directory"
  "Alapkönyvtára"

  "Behaviors"
  "Viselkedés"

  "Buffer"
  "Buffer"

  "Choose"
  "Kiválasztás"

  "Choose Logfile Directory"
  "Válassza ki a Logfile könyvtár"

  "Clear"
  "Törlés"

  "Clipboard"
  "Vágólap"

  "Clipboard history depth"
  "Csipeszes írótábla történelem mélység"

  "Color value case"
  "Szín érték esetén"

  "Command launcher entry"
  "Parancs launcher bejegyzés"

  "Command launcher preview"
  "Parancs launcher előnézet"

  "Convert to lowercase"
  "Konvertálása kisbetűs"

  "Convert to uppercase"
  "Konvertálása nagybetűs"

  "Curly bracket"
  "Kapcsos zárójel hozzáadása"

  "Current"
  "Aktuális"

  "Current Directory"
  "aktuális könyvtár"

  "Current File Pathname"
  "Aktuális fájl útneve"

  "Current Filename"
  "Jelenlegi fájlnév"

  "Current Line Column"
  "Aktuális sor-oszlop"

  "Current Line Number"
  "Aktuális sor száma"

  "Current editing buffer directory"
  "Aktuális szerkesztési puffer könyvtár"

  "Current working directory"
  "Időszerű működő címtár"

  "Date"
  "Dátum"

  "Default Markdown Export Extension"
  "Markdown Export árbevétel"

  "Default unit for floating point values"
  "Alapértelmezett egység a lebegőpontos értékek"

  "Default unit for integer values"
  "Alapértelmezett egység egészszám-értékek"

  "Delete snippet"
  "Részlet törlése"

  "Development"
  "Fejlesztés"

  "Double-quote"
  "Idézőjel"

  "Edit preferences using GUI"
  "Használ GUI beállítások szerkesztése"

  "Editor"
  "Szerkesztő"

  "Enable Vim Mode"
  "Vim-üzemmód engedélyezése"

  "Enable auto-indentation"
  "Automatikus kiegészítés engedélyezése"

  "Enable development mode"
  "Fejlesztési-üzemmód engedélyezése"

  "Enable fuzzy search"
  "Engedélyezi a fuzzy keresési"

  "Enable relative line numbering"
  "Engedélyezi a relatív sorszámozás"

  "End-of-line character when saving"
  "A sor végén karakter mentésekor"

  "Exit the application after the last tab is closed"
  "Az alkalmazás bezárásáig, az utolsó lap bezárása után"

  "Format snippet indentation after insert"
  "Formátum részlet behúzás után beszúrása"

  "General"
  "Általános"

  "Hide Patterns"
  "Mintáinak elrejtéséhez"

  "Hide binary files"
  "Bináris fájlok elrejtése"

  "Hiding"
  "Elrejtése"

  "Host"
  "Munkaállomás"

  "Indentation Spaces"
  "Szóközök behúzása"

  "Keyword"
  "Kulcsszó"

  "Languages"
  "Nyelvek"

  "Last"
  "Utolsó"

  "Last accessed"
  "Utolsó hozzáférés:"

  "Line count to find for Vim modeline information"
  "Sorok száma Vim modeline információk kereséséhez"

  "Logfile Directory"
  "Logfile-könyvtár"

  "Maximum undo history (set to 0 for unlimited)"
  "Maximális visszavonás történelem (készlet-hoz 0 részére határtalan)"

  "Menu bindings"
  "Menü kötések"

  "Mounts"
  "Tartók"

  "Node Aliases"
  "Csomópont-aliasok"

  "Parenthesis"
  "Zárójel"

  "Profiler Options"
  "A profilozó beállításai:"

  "Properties"
  "Ingatlanok"

  "Recently opened history depth"
  "A közelmúltban megnyílt történelem mélység"

  "Remember last position of command launcher"
  "Ne feledje, utolsó pozícióban parancs Launcher"

  "Remote Base Directory"
  "Távoli alapkönyvtára"

  "Remove root directory after last sub-file is closed"
  "Távolítsa el a gyökér könyvtárban, utolsó Al fájl bezárása után"

  "Remove trailing whitespace on save"
  "Távolítsa el a záró szóköz a Mentés"

  "Report Options"
  "A jelentés beállításai"

  "Retain case"
  "Esetben megtartása"

  "Return"
  "Visszaút"

  "Ruler column"
  "Vonalzó oszlop"

  "Search Shortcuts"
  "Keresés parancsikonok"

  "Search Snippets"
  "Keresés töredék"

  "Select Settings Sharing Directory"
  "Válassza a beállítások könyvtár megosztása"

  "Select default browsing directory"
  "Válassza ki az alapértelmezett könyvtár böngészés"

  "Selected Text"
  "A kijelölt szöveg"

  "Set"
  "Beállítás"

  "Set Find History Depth"
  "Keresés történelem mélység beállítása"

  "Set Find in Files Line Context"
  "Set talál fájlok vonal összefüggésben"

  "Set Jump Distance"
  "Állítsa ugrás távolság"

  "Set default open/save browsing directory to"
  "Állítsa be az alapértelmezett nyit/megment böngészés a könyvtárban"

  "Sharing Items"
  "Megosztása tételek"

  "Shortcut"
  "Gyorsbillentyű"

  "Shortcuts"
  "Billentyűparancsok"

  "Show 'Find in Files' result in other pane"
  "\"

  "Show diagnostic logfile at startup"
  "Diagnosztikai naplófájl megjelenítése indításkor"

  "Show difference file in other pane than original"
  "Különbség fájlra mutat a másik ablaktábla, mint eredeti"

  "Show difference file version information"
  "Különbség a fájl verzióadatok megjelenítése"

  "Show folders at top"
  "Térkép-mappák tetején"

  "Show menubar"
  "A menüsáv megjelenítése"

  "Single-quote"
  "Idézőjel"

  "Snippet Completion Characters"
  "Részlet befejezése karakterek"

  "Snippet Text"
  "Kódtöredék szövege"

  "Sort tabs alphabetically on open"
  "Rendezés lapok ABC sorrendben a nyílt"

  "Sorting Column"
  "Rendezési oszlop"

  "Space"
  "Hely"

  "Spaces per tab"
  "Laponkénti terek"

  "Square bracket"
  "Szögletes zárójel hozzáadása"

  "Stable"
  "Stabil"

  "Symbol between CSS property and value"
  "CSS-tulajdonság és az érték közötti szimbólum"

  "Symbol placed at end of CSS property"
  "Jel végére CSS tulajdonság"

  "Syntax Coloring"
  "Szintaxis színezés"

  "Tab"
  "Fül"

  "Tab Stop"
  "Tabulátor"

  "Time"
  "Idő"

  "Update using release type"
  "Frissítse a kiadás típusú"

  "Updates"
  "Frissítések"

  "Use appropriate EOL character on system"
  "Használja a megfelelő EOL karakter a rendszer"

  "Use carriate return linefeed sequence"
  "Carriate vissza-soremelés sorrendet alkalmazni"

  "Use directory"
  "Használja directory"

  "Use linefeed character"
  "Soremelés karaktert"

  "Use original EOL character from file"
  "Használja az eredeti EOL karakter fájlból"

  "Use shortened colors"
  "Rövidített színek"

  "Use single carriage return character"
  "Használ egy kocsivissza karakternek"

  "User guide format"
  "Az útmutató formátuma"

  "Variables"
  "Változók"

}

# remote.tcl
msgcat::mcmset hu {

  "Close Connection"
  "A kapcsolat bezárása"

  "Create New Folder"
  "Új könyvtár létrehozása"

  "Delete Connection"
  "Csatlakozás törlése"

  "Delete Group"
  "Csoport törlése"

  "Delete connection?"
  "Csatlakozás törlése"

  "Delete group?"
  "Csoport törlése"

  "Edit Connection"
  "Kapcsolat szerkesztése"

  "Enter Password"
  "Adja meg a jelszót"

  "Folder Name"
  "Mappa"

  "Group"
  "Csoport"

  "Group Name"
  "Csoport neve"

  "Group Name: "
  "Csoport neve"

  "Image used in remote file selector to indicate a file."
  "A kép a távoli fájl választóval hozzászokott jelez egy fájl."

  "Image used in remote file selector to indicate a folder."
  "A kép a távoli fájl kiválasztó egy mappában jelzésére használható."

  "Image used in remote file selector to indicate that a connection is being opened."
  "Kép használt távoli fájl választóval annak jelzésére, hogy egy kapcsolat nyitotta meg."

  "Image used in remote file selector to indicate that a connection is opened."
  "Megjelenítéséhez használt kép a távoli fájl kiválasztó jelezze, hogy a kapcsolat meg van nyitva."

  "Name"
  "Név"

  "New Connection"
  "Új kapcsolat"

  "New Folder"
  "gyöngyike"

  "New Group"
  "Új csoport"

  "Open Connection"
  "Kapcsolat"

  "Open Remote File"
  "Távoli fájl megnyitása"

  "Optional"
  "Nem kötelező."

  "Password"
  "Jelszó"

  "Password: "
  "Jelszó:"

  "Port"
  "Port"

  "Remote Directory"
  "Távoli könyvtár"

  "Rename Group"
  "Csoport átnevezése"

  "Save File Remotely"
  "Mentse a fájlt távolról"

  "Server"
  "Szerver"

  "Test"
  "Teszt"

  "Test Connection"
  "Kapcsolat ellenőrzése"

  "Type"
  "Típus"

  "Unable to connect to"
  "Nem lehet csatlakozni"

  "Username"
  "Felhasználónév"

  "server"
  "szerver"

}

# search.tcl
msgcat::mcmset hu {

  "No files found in specified directories"
  "Nem található a megadott könyvtárak fájl"

  "No search results found"
  "Nincs találat"

  "Search wrapped to beginning of file"
  "Keresés becsomagolt fájl elejére"

  "Search wrapped to end of file"
  "Keresés csomagolva, hogy a fájl vége"

  "substitutions done"
  "helyettesítések tenni"

}

# sessions.tcl
msgcat::mcmset hu {

  "Save session?"
  "A munkamenet mentése"

  "Session state will be lost if not saved"
  "Sessionnel elvész, ha nem mentette"

}

# share.tcl
msgcat::mcmset hu {

  "Emmet"
  "hangya"

  "Export Settings Data"
  "BEÁLLÍTÁSOK EXPORTÁLÁSA"

  "Favorites"
  "Extrák"

  "Remote Connections"
  "Távoli kapcsolatok"

  "Settings to export"
  "Beállítások exportálása"

  "Sharing Setup"
  "Telepítési megosztás"

  "Themes"
  "Sablonok"

}

# sidebar.tcl
msgcat::mcmset hu {

  "Add Parent Directory"
  "Szülő mappa"

  "Close Directory Files"
  "Bezárása Directory fájlok"

  "Copy Pathname"
  "Elérési út másolása"

  "Delete directories?"
  "Törli a könyvtárakat?"

  "Delete directory?"
  "Könyvtár törlése?"

  "Delete file?"
  "A fájl törlése"

  "Delete files?"
  "A fájlok törlése"

  "Directory Name:"
  "Könyvtár neve:"

  "Disconnect From Server"
  "Bontása a szerver"

  "Folder Name:"
  "Mappa"

  "Hide"
  "Elrejt"

  "Hide Directory Files"
  "Elrejteni fájlokat címtár"

  "Image displayed in sidebar to indicate a directory that is collapsed"
  "Kép bemutatás-ban tálaló jelzi, egy könyvtár, amely össze van csukva"

  "Image displayed in sidebar to indicate a directory that is showing its contents"
  "Kép bemutatás-ban tálaló-hoz egy címtár amit van bemutatás a tartalom jelzésére"

  "Image displayed in sidebar to indicate a file"
  "Kép bemutatás-ban tálaló jelzi, a fájl"

  "Image displayed in sidebar to indicate a selected directory that is collapsed"
  "Kép bemutatás-ban tálaló jelzi a kijelölt könyvtár, hogy összeomlott"

  "Image displayed in sidebar to indicate a selected directory that is expanded"
  "Kép bemutatás-ban tálaló jelzi a kijelölt könyvtár van bontva"

  "Image displayed in sidebar to indicate that a file is currently opened but hidden"
  "Jelzi, hogy a fájl jelenleg nyitott, de rejtett tálaló megjelenő kép"

  "Image displayed in sidebar to indicate that a file is currently opened in an editing buffer."
  "A kép megjelenik a sidebar, jelezve, hogy a fájl jelenleg megnyitott egy szerkesztési puffer."

  "Make Current Working Directory"
  "Legyen aktuális könyvtár"

  "New Directory"
  "Új könyvtár"

  "New File From Template"
  "Új sablonból"

  "Open Directory Files"
  "Open Directory fájlok"

  "Refresh Directory Files"
  "Frissítés Directory fájlok"

  "Remove Parent from Sidebar"
  "Vegye szülőnek Sidebar"

  "Remove from Sidebar"
  "Eltávolítás a Sidebar"

  "Show"
  "Mutasd"

  "Show Difference"
  "Különbség Térkép"

  "Show Directory Files"
  "Könyvtár-fájlok megjelenítése"

}

# snippets.tcl
msgcat::mcmset hu {

  "Snippet: *"
  "Töredék: *"

}

# startup.tcl
msgcat::mcmset hu {

  "Change Directory"
  "Cd"

  "Copies settings data from an existing directory to your home directory.  Click 'Customize Settings' below to customize which settings data will be copied."
  "Másolatok beállítások adatokat egy létező könyvtár a haza címtár.  Kattintson 'Beállítások testreszabása' az alábbi szabni, hogy mely beállítások adat másolódik."

  "Copy settings from directory"
  "Beállítások másolása könyvtárba"

  "Create settings locally"
  "Helyben-beállítások létrehozása"

  "Creates new settings information and places it in your home directory"
  "Hozza létre az új beállításokra vonatkozó adatok, és elhelyezi a saját könyvtárában"

  "Finish"
  "Kész"

  "If you need would like to change your settings location and/or data, you can do so within the Edit/Sharing/Edit... menu."
  "Ha módosítani szeretné a beállítások helye és/vagy az adatok, akkor erre belül a Szerkesztés/megosztás/engedélybejegyzések menü."

  "Items that are selected will be copied to your local home directory. Items that are not selected will be created in your home directory."
  "A kijelölt elem bekerül a helyi kezdőkönyvtárat. Nem kijelölt elem jön létre a saját könyvtáradba."

  "Items that are selected will be shared with other computers. Items that are not selected will be stored locally and will not be shared."
  "A kijelölt elem lesz osztva más számítógépekkel. Nem kijelölt elem helyileg tárolni, és nem lesz megosztva."

  "Next"
  "Következő"

  "Select Settings Directory"
  "Válassza ki Settings könyvtárában"

  "Settings"
  "Beállítások"

  "Settings Options"
  "A beállításokhoz"

  "Setup Complete"
  "TelepφtΘs befejezΘse"

  "Share"
  "Megosztás"

  "Shares settings data from a new or existing directory (ex., iCloud Drive, Google Drive, Dropbox, etc.).  Any changes made to settings data will be available to other sharers.  Click 'Customize Settings' below to customize which settings data will be shared."
  "Megosztja a beállítások adatait új vagy meglévő könyvtárból (ex., iCloud Drive, a Google-meghajtó, Dropbox, stb.).  Adatok beállításainak módosításai más osztozik elérhető lesz.  Kattintson 'Beállítások testreszabása' az alábbi szabni, hogy mely beállítások adatokat meg kell osztani."

  "Thanks for using TKE, the advanced programmer's editor.  Since this is a new installation of TKE, let's help you get things set up. \\n \\n Click 'Next' below to get things going."
  "Köszönjük, hogy használta a TKE, a speciális programmer's szerkesztő.  Mivel ez egy új bevezetés-ból TKE, segítsünk Önnek a dolgokat létrehozni. \\n \\n Kattintsona 'Next' alatt, hogy mennek a dolgok."

  "Use shared settings"
  "Megosztott beállításokkal"

  "Welcome"
  "Üdvözölünk"

  "Welcome To"
  "Üdvözlet kedves"

}

# syntax.tcl
msgcat::mcmset hu {

  "Syntax"
  "Szintaxis"

  "Syntax error in syntax file"
  "Szintaktikai hiba a fájl szintaxisa"

}

# templates.tcl
msgcat::mcmset hu {

  "Delete template?"
  "Sablon törlése?"

  "Template"
  "Sablon"

  "Template Name"
  "Sablon neve"

  "deleted"
  "törölve"

  "saved"
  "Mentve."

  "will be permanently deleted"
  "véglegesen törlődnek"

}

# theme.tcl
msgcat::mcmset hu {

  "Background (trough) color used in the sidebar scrollbar."
  "Háttér (maradék) használt szín a tálaló görgetősáv."

  "Background (trough) color used in the text scrollbars."
  "Háttér (maradék) használt szín a szövegben gördítősávját."

  "Background color displayed in embedded language code."
  "Háttérszín jelenik meg a beágyazott nyelvkódot."

  "Background color for all sidebar items that are not selected."
  "Háttérszíne minden sidebar elem, hogy nem választott."

  "Background color for all sidebar items that are selected."
  "Háttérszíne minden oldalsáv elemek vannak jelölve."

  "Background color in difference viewer that shows added lines."
  "Háttérszíne különbség nézőt, amely megmutatja hozzáadott sorokat."

  "Background color in difference viewer that shows deleted lines."
  "Háttérszíne különbség nézőt, amely azt mutatja törölt sor."

  "Background color of insertion cursor and background marker colors."
  "Háttérszíne behelyezés kurzor és a háttér marker színek."

  "Background color of the editing buffer."
  "Háttérszíne szerkesztési puffer."

  "Background color to display when a button-like ttk widget is pressed."
  "Háttérszínt jelenik meg, amikor egy gomb-szerű TTK widgetet van nyomva."

  "Background color to use for displaying character information that requires the user's attention."
  "Jellegű információt, a felhasználó a figyelmet igénylő megjelenítésére használt háttérszín."

  "Background color to use for selected text."
  "Háttérszínt használja a kiválasztott szöveget."

  "Background color used for all other tabs that are not the current/active tab in the tabbar."
  "Háttér színe mint az összes többi fülek, amelyek nem a jelenlegi / aktív lap tabbar."

  "Background color used for the current/active menu item."
  "Háttérszínt használják a jelenlegi / aktív menüpontot."

  "Background color used for the current/active tab in the tabbar."
  "Háttérszínt használják a jelenlegi / aktív lap tabbar."

  "Background color used in highlighted text."
  "Háttérszínt használják kijelölt szöveget."

  "Background color used in menus."
  "Háttér színe a menükben alkalmazott."

  "Background color used in the tabbar area."
  "Háttérszínt használt tabbar területen."

  "Color of border drawn around active editing buffer."
  "Színe határ köré rajzolt aktív szerkesztési puffer."

  "Color of ttk entry widget text border when the entry has keyboard focus."
  "Színe TTK beviteli dobozon szöveget határt, amikor a bejegyzésnek a fókuszt."

  "Color used to draw the warning width line in the editing buffer (as well as the line separating the gutter from the editing buffer)."
  "Színes hívják fel a figyelmeztető széles vonal a szerkesztési puffer (valamint az elválasztó vonal az ereszcsatorna a szerkesztési puffer)."

  "Default 'darkcolor' for all ttk widgets."
  "Alapértelmezett &quot;darkcolor&quot; minden TTK kütyü."

  "Default background color to use for all ttk widgets that are in a disabled state."
  "Alapértelmezett háttérszín használható minden TTK widgeteket letiltott állapotú."

  "Default background color to use for all ttk widgets when the mouse cursor hovers over the widget."
  "Alapértelmezett háttérszín használható minden TTK kütyü, amikor a egérkurzora a widget."

  "Default background color to use for all ttk widgets."
  "Alapértelmezett háttérszín használható minden TTK kütyü."

  "Default border color for all ttk widgets."
  "Alapértelmezett keret színe minden TTK kütyü."

  "Default color for non-syntax highlighted text."
  "Alapértelmezett színe nem szintaxis kijelölt szöveget."

  "Default foreground text color to use for all ttk widgets that are in a disabled state."
  "Alapértelmezett előtérben szöveg színe használható minden TTK widgeteket letiltott állapotú."

  "Default foreground text color to use for all ttk widgets."
  "Alapértelmezett előtérben szöveg színe használható minden TTK kütyü."

  "Determines the number of grips strips to display in the grip area between resizable panes."
  "Meghatározza száma markolatok csíkok jelennek meg a markolat között átméretezhető táblát."

  "Determines the thickness of the grip area between resizable panes."
  "Meghatározza a vastagsága a markolat között átméretezhető táblát."

  "ERROR:  Unable to read"
  "HIBA: Nem lehet olvasni"

  "Foreground (slider) color used in the sidebar scrollbar."
  "Előtér (slider) használt szín a tálaló görgetősáv."

  "Foreground (slider) color used in the text scrollbars when pane synchronization is enabled."
  "(Csúszka) előtérszíne használt a szöveg scrollbars, ha engedélyezve van a szinkronizálási ablaktáblán."

  "Foreground (slider) color used in the text scrollbars."
  "Előtér (slider) használt szín a szövegben gördítősávját."

  "Foreground color used in menu items with checks or buttons."
  "A festőszín használt menüpontok ellenőrzéseket és a gombok."

  "Foreground text color for strings."
  "Előtérben szövegszínt szálakat."

  "Foreground text color to use for all miscellaneous1 labeled text."
  "Előtér szöveg színe használható minden miscellaneous1 jelölt szöveget."

  "Foreground text color to use for all miscellaneous2 labeled text."
  "Előtér szöveg színe használható minden miscellaneous2 jelölt szöveget."

  "Foreground text color to use for all miscellaneous3 labeled text."
  "Előtér szöveg színe használható minden miscellaneous3 jelölt szöveget."

  "Foreground text color to use for comments."
  "Előtér szöveg színe használni véleményezésre."

  "Foreground text color to use for displaying line numbers."
  "Előtér szöveget használandó színt megjelenítő sorszámok."

  "Foreground text color to use for displaying numbers."
  "Előtér szöveget használandó színt megjelenítő számokat."

  "Foreground text color to use for language-specific keywords."
  "Előtér szöveg színe használni nyelv-specifikus kulcsszavakat."

  "Foreground text color to use for language-specific punctuation."
  "Előtér szöveg színe használni nyelvspecifikus írásjelek."

  "Foreground text color to use for meta syntax."
  "Előtér szöveg színe használni meta szintaxist."

  "Foreground text color to use for precompiler syntax."
  "Előtér szöveg színe használni előfordítóra szintaxist."

  "Foreground text color to use for selected text."
  "Előtér szöveg színe használni a kiválasztott szöveget."

  "Foreground text color used for all other tabs that are not the current/active tab in the tabbar."
  "Előtérben lévő szöveg színe más lapok, amelyek nem az aktuális aktív lap kalanderez."

  "Foreground text color used for menus item that are disabled."
  "Előtérben szöveg színe használt menük elem, hogy le van tiltva."

  "Foreground text color used for the current/active menu item."
  "Előtérben szöveg színét használják az aktuális / aktív menüpontot."

  "Foreground text color used for the current/active tab in the tabbar."
  "Előtérben az aktuális aktív lap kalanderez használt szövegszín."

  "Foreground text color used in menus."
  "Előtérben szöveg színe a menükben alkalmazott."

  "Foreground text/image color used in tabbar and tabs."
  "Előtérben a szöveg / kép használt szín a tabbar és a lapok."

  "Images"
  "Képek"

  "Maximum thickness of the text scrollbar when it is active."
  "Maximális vastagsága a szöveg görgetősávot amikor aktív."

  "Maximum thickness of the text scrollbars when they are active."
  "Maximális vastagsága a szöveg görgetősávok, amikor azok aktívak."

  "Menu Options"
  "Menü beállítások"

  "Menu relief value."
  "Menü megkönnyebbülés értéket."

  "Pixel height of the tabbar widget."
  "Pixel magassága tabbar widget."

  "Relief used in drawing the tabs."
  "Relief a rajzoláshoz a lapok."

  "Relief value of the sidebar area."
  "Relief értéke az oldalsáv terület."

  "Sidebar Options"
  "Oldalsáv beállítások"

  "Sidebar Scrollbar Options"
  "Sidebar Scrollbar opciók"

  "Specifies the color to display around the sidebar when the sidebar does not have the focus."
  "Meghatározza a színt megjeleníteni körül a tálaló, amikor a oldalsáv nem rendelkezik a hangsúly."

  "Specifies the color to display around the sidebar when the sidebar has the focus."
  "Meghatározza a színt megjeleníteni körül a tálaló, amikor a oldalsáv a hangsúly."

  "Specifies the default background color to use for text that is selected in a standard ttk widget (this does not include the editing buffer)."
  "Megadja az alapértelmezett háttérszínt használja a szöveges kiválasztott szabványos TTK widgetet (ez nem tartalmazza a szerkesztési puffer)."

  "Specifies the default foreground text color to use for text that is selected in a standard ttk widget (this does not include the editing buffer)."
  "Megadja az alapértelmezett előtér szöveget használandó színt szöveget kiválasztott szabványos TTK widgetet (ez nem tartalmazza a szerkesztési puffer)."

  "Specifies the default relief to use when drawing ttk widgets."
  "Megadja az alapértelmezett megkönnyebbülés használni, ha rajz TTK kütyü."

  "Specifies the pixel thickness of the highlight line."
  "Meghatározza a pixel vastagságú fénypontja sor."

  "Syntax Colors"
  "Syntax színek"

  "Tab Options"
  "Alap profilbeállítások"

  "Text Scrollbar Options"
  "Szöveg Scrollbar opciók"

  "Text color for all sidebar items that are not selected."
  "Szöveg színe minden sidebar elem, hogy nem választott."

  "Text color for all sidebar items that are selected."
  "Szöveg színe minden oldalsáv elemek vannak jelölve."

  "ttk Widget Colors"
  "TTK Widget színek"

}

# themer.tcl
msgcat::mcmset hu {

  "   Show Selected Option"
  "Mutasd a kiválasztott opció"

  "   Show Selected Value"
  "Mutasd a kiválasztott érték"

  "Categories"
  "Kategóriák"

  "Change Base Color"
  "Változás alapszín"

  "Choose Theme"
  "Válasszon téma"

  "Custom Directory"
  "más könyvtárból:"

  "Custom..."
  "Egyedi…"

  "Delete swatch?"
  "Törlés Swatch?"

  "Description"
  "Leírás"

  "Details"
  "Részletek"

  "Done"
  "Kész"

  "Enable Copy Mode"
  "Másolási üzemmód engedélyezése"

  "GIF Photo"
  "GIF Fotó"

  "Import"
  "Import"

  "Import BMP Data"
  "Import BMP adatok"

  "Import BMP Mask"
  "Import BMP Mask"

  "Import Error"
  "Import Error"

  "Import Theme File"
  "Import témafájlt"

  "Installation Directory"
  "Telepítési könyvtár"

  "Modifications"
  "Módosítások"

  "One-Color Bitmap"
  "Egy-Color Bitmap"

  "Paste Theme Items"
  "Téma elemek beillesztése"

  "Relief: "
  "Megkönnyebbülés"

  "Save As:"
  "Mentés másként"

  "Save theme changes?"
  "Mentsd téma változik?"

  "Search"
  "Keresés"

  "Select Directory"
  "Válasszon ki egy könyvtárat"

  "Show All"
  "Mindent mutat"

  "Show Category"
  "~Kategória megjelenítése"

  "Show Color"
  "A következő szálláshely színe"

  "Show Selected Option"
  "Térkép-beállítást"

  "Show Selected Value"
  "A kiválasztott érték megjelenítése"

  "Swatch"
  "Mintadarab"

  "Swatch Colors"
  "Swatch színek"

  "Table Copy"
  "Táblázat másolása"

  "Table Filters"
  "Táblázat szűrők"

  "Table Search"
  "Táblázat-keresés"

  "The current theme has unsaved changes"
  "Az aktuális téma nem mentett módosításokat tartalmaz"

  "Tree Style: "
  "Fa Stílus:"

  "Two-Color Bitmap"
  "Két-Color Bitmap"

  "User Directory"
  "Saját könyvtár"

  "Value"
  "Érték"

  "Value: "
  "Érték:"

}

# themes.tcl
msgcat::mcmset hu {

  "Theme:*"
  "Sablon*"

}

# tke.tcl
msgcat::mcmset hu {

  "Import TKE theme?"
  "Import TKE témát?"

  "Import TextMate theme?"
  "Import TextMate témát?"

}

# tkedat.tcl
msgcat::mcmset hu {

  "Unable to read"
  "A fájl beolvasása nem sikerült."

}

# vim.tcl
msgcat::mcmset hu {

  "File format unrecognized"
  "Ismeretlen fájlformátum"

  "Filename directory does not exist"
  "Fájlnév könyvtár nem létezik"

  "Folding method unrecognized"
  "Ismeretlen módszer összecsukható"

  "Illegal modelines value"
  "Illegális hardverednek érték"

  "Number width not a number"
  "Szám szélessége nem szám"

  "Shiftwidth value is not an integer"
  "Shiftwidth értéke nem egész szám"

  "Tabstop value is not an integer"
  "TabStop értéke nem egész szám"

  "Unrecognized vim option"
  "Ismeretlen vim lehetőség"

}

# General
msgcat::mcmset hu {

  "Back"
  "Vissza"

  "Browse"
  "Böngészés"

  "Cancel"
  "Mégsem"

  "Check for Update"
  "Ellenőrizze a Frissítés"

  "Close"
  "Bezárás"

  "Copy"
  "Másolás"

  "Create"
  "Létrehozás"

  "Current Line"
  "Az aktuális sor:"

  "Current Word"
  "Aktuális szó"

  "Cursor"
  "Kurzor"

  "Delete"
  "Törlés"

  "Directory"
  "Cégjegyzék"

  "Duplicate"
  "Megkettőzés"

  "Enable code folding"
  "Engedélyezi a kód összecsukható"

  "Export"
  "Exportálás"

  "Favorite"
  "Kedvenc"

  "File"
  "Fájl"

  "File Name:"
  "A fájlnév"

  "Find"
  "Keresés"

  "Insert"
  "Beillesztés"

  "Language"
  "Nyelv"

  "Launcher"
  "Rakétaindító állvány"

  "Move to Other Pane"
  "Áthelyezni más ablak"

  "New File"
  "Új fájl"

  "None"
  "Egysem"

  "OK"
  "OK"

  "Open"
  "Nyissa"

  "Plugins"
  "Pluginek"

  "Preferences"
  "Preferencia"

  "Preview"
  "Előnézet"

  "Rename"
  "Átnevezés"

  "Save"
  "Mentés"

  "Save As"
  "Mentés másként"

  "Sessions"
  "Ülések"

  "Sharing"
  "Megosztás"

  "Show console"
  "Térkép-konzol"

  "Show line numbers"
  "A sorszámok megjelenítése"

  "Show marker map"
  "Jelölős Térkép megjelenítése"

  "Show sidebar"
  "Oldalsáv megjelenítése?"

  "Show status bar"
  "Az állapotsor megjelenítése"

  "Show tab bar"
  "A fülek megjelenítése"

  "Snippets"
  "Snippets"

  "Split View"
  "Osztott nézet"

  "Templates"
  "Sablonok"

  "Theme"
  "Sablon"

  "Theme Editor"
  "Témaszerkesztő"

  "Unable to write"
  "Nem lehet írni"

  "Unfavorite"
  "Nem kedvenc"

}

