# api.tcl
msgcat::mcmset it {

  "Argument list to api::add_file was not an even key/value pair"
  "Elenco di argomenti di api :: add_file non era una coppia ancor chiave / valore"

  "Argument list to api::add_file was not in the form 'filename [<option> <value>]*'"
  "Elenco di argomenti di api :: add_file non era in forma &#39;filename [ <option><value> ] * &#39;"

  "get_home_directory can only be called within plugin code"
  "get_home_directory possono essere chiamati solo all&#39;interno di codice del plugin"

}

# bgproc.tcl
msgcat::mcmset it {

  "Unable to run system command (%s)"
  "Impossibile eseguire il comando di sistema (% s)"

}

# bindings.tcl
msgcat::mcmset it {

  "Menu Bindings: Edit user menu bindings"
  "Attacchi Menu: attacchi di menu Modifica utente"

  "Menu Bindings: Reload menu bindings"
  "Attacchi Menu: Ricarica associazioni di menu"

  "Menu Bindings: Use default menu bindings"
  "Attacchi Menu: attacchi Uso del menu di default"

  "Menu Bindings: View global menu bindings"
  "Attacchi Menu: Visualizza attacchi dei menu globale"

}

# gui.tcl
msgcat::mcmset it {

  "Close All Tabs"
  "Chiudi tutte le linguette"

  "Close Other Tab(s)"
  "Chiudi Other Tab (s)"

  "Close Other*"
  "Chiudi un altro"

  "Close Tab"
  "Chiudi scheda"

  "Copyright %d"
  "Copyright% d"

  "Delete tab?"
  "Elimina scheda"

  "Developer:"
  "Sviluppatore:"

  "Email:"
  "E-mail:"

  "File attribute (%s) does not exist"
  "Attributo di file (% s) non esiste"

  "File index is out of range"
  "Indice non compreso nell'intervallo."

  "Find:"
  "Trova:"

  "Global"
  "Globale"

  "Line: %d, Column: %d"
  "Line:% d, colonna:% d"

  "Locked"
  "Bloccato"

  "Move to Other Pane"
  "Spostarsi Altro Pane"

  "Move*"
  "Sposta"

  "Reload file?"
  "Ricarica file"

  "Replace:"
  "Sostituisci"

  "Save request"
  "Salva richiesta"

  "Unable to find current file (pane: %s, tab: %s)"
  "Impossibile trovare il file corrente (riquadro:% s, scheda:% s)"

  "Untitled"
  "Untitled"

  "Version:"
  "Versione:"

}

# markers.tcl
msgcat::mcmset it {

  "Marker name:"
  "Nome Marker:"

}

# menus.tcl
msgcat::mcmset it {

  "                                  Profiling Report Sorted By (%s)"
  "Profiling Rapporto Ordinati per (% s)"

  "About Tke"
  "Chi Tke"

  "About tke"
  "Chi TKE"

  "Align cursors"
  "Allineare i cursori"

  "All"
  "Tutti"

  "Append next occurrence"
  "Aggiunge ricorrenza successiva"

  "Clear All"
  "Deseleziona tutto"

  "Close All"
  "Chiudi tutto"

  "Comment"
  "Commento"

  "Copy"
  "Copia"

  "Create new..."
  "Creare nuovo"

  "Create..."
  "Crea"

  "Cut"
  "Taglia"

  "Edit"
  "Modifica"

  "Edit..."
  "Modifica..."

  "FOOBAR"
  "Foo"

  "File"
  "File"

  "Find"
  "Find"

  "Find and Replace"
  "Trova e sostituisci"

  "Find in files"
  "Cerca nei file@action:inmenu"

  "Find matching pair"
  "Trova pair corrispondenti"

  "Format Text"
  "Formato testo"

  "Help"
  "Aiuto"

  "Import TextMate theme..."
  "Import tema TextMate ..."

  "Indent"
  "Indenta"

  "Insert enumeration"
  "Inserisci enumerazione"

  "Install..."
  "Installa"

  "Launcher"
  "Utilità di avvio"

  "Lock"
  "Lucchetto"

  "Menu: About tke"
  "Menu: TKE"

  "Menu: Align cursors"
  "Menu: Allineare i cursori"

  "Menu: Append next occurrence"
  "Menu: Aggiungere ricorrenza successiva"

  "Menu: Close all tabs"
  "Menu: Chiudere tutte le schede"

  "Menu: Close current tab"
  "Menu: Chiudi scheda corrente"

  "Menu: Comment selected text"
  "Menu: Commento testo selezionato"

  "Menu: Copy selected text"
  "Menu: Copia testo selezionato"

  "Menu: Create new plugin"
  "Menu: Creare nuovo plugin"

  "Menu: Create new theme"
  "Crea nuovo tema..."

  "Menu: Cut selected text"
  "Menu: Tagliare il testo selezionato"

  "Menu: Disable Vim mode"
  "Menu: Modalità Disable Vim"

  "Menu: Edit Tke theme"
  "Menu: Modifica Tke tema"

  "Menu: Enable Vim mode"
  "Menu: Attivare la modalità Vim"

  "Menu: Find"
  "Menu: Trova"

  "Menu: Find and Replace"
  "Menu: Trova e sostituisci"

  "Menu: Find in files"
  "Menu: Trova nei file"

  "Menu: Find matching character pair"
  "Menu: trovare corrispondenza coppia di caratteri"

  "Menu: Find next occurrence"
  "Menu: Trova l&#39;occorrenza successiva"

  "Menu: Find previous occurrence"
  "Menu: Trova occorrenza precedente"

  "Menu: Hide console"
  "Menu: Hide console"

  "Menu: Hide sidebar"
  "Menu: Hide sidebar"

  "Menu: Hide status bar"
  "Nascondi barra di stato"

  "Menu: Import TextMate theme"
  "Menu: Import TextMate tema"

  "Menu: Indent selected text"
  "Menu: Rientro testo selezionato"

  "Menu: Insert enumeration"
  "Menu: Inserire enumerazione"

  "Menu: Install plugin"
  "Menu: installare plug-"

  "Menu: Lock file"
  "Menu: file di blocco"

  "Menu: New file"
  "Menu: Nuovo file"

  "Menu: Open directory"
  "Menu: directory aperta"

  "Menu: Open file"
  "Menu: Aprire il file"

  "Menu: Paste and format text from clipboard"
  "Menu: Pasta e formato di testo dal clipboard"

  "Menu: Paste text from clipboard"
  "Incolla testo dagli appunti"

  "Menu: Quit application"
  "Menu: Uscire applicazione"

  "Menu: Redo"
  "Menu: Redo"

  "Menu: Reload all plugins"
  "Menu: Ricarica tutti i plugin"

  "Menu: Restart tke"
  "Menu: Restart TKE"

  "Menu: Save all files"
  "Menu: Salvare tutti i file"

  "Menu: Save file"
  "Menu: Salva file"

  "Menu: Save file as"
  "Menu: Salva file come"

  "Menu: Select all occurrences"
  "Menu: Selezionare tutte le occorrenze"

  "Menu: Show console"
  "Menu: Mostra console"

  "Menu: Show last profiling report"
  "Menu: Mostra ultimo rapporto profiling"

  "Menu: Show sidebar"
  "Menu: Visualizza sidebar"

  "Menu: Show status bar"
  "Menu: Mostra barra di stato"

  "Menu: Start profiling"
  "Menu: Start profiling"

  "Menu: Stop profiling"
  "Menu: Stop profiling"

  "Menu: Uncomment selected text"
  "Menu: testo Uncomment selezionato"

  "Menu: Undo"
  "Menu: Annulla"

  "Menu: Unindent selected text"
  "Menu: testo Unindent selezionato"

  "Menu: Uninstall plugin"
  "Menu: Uninstall plugin di"

  "Menu: Unlock file"
  "Menu: Sblocca il file"

  "New"
  "NEW"

  "Open Directory..."
  "Apri cartella"

  "Open File..."
  "Apri file..."

  "Open Recent"
  "Apri recenti"

  "Paste"
  "Pasta"

  "Paste and Format"
  "Incolla formato"

  "Plugins"
  "Plugin"

  "Preferences..."
  "Preferenze..."

  "Profiling started"
  "Profiling non avviato."

  "Profiling stopped"
  "Profiling non fermato."

  "Quit"
  "Esci"

  "Redo"
  "Ripeti"

  "Reload"
  "Reload"

  "Restart tke"
  "Restart TKE"

  "Save All"
  "Salva tutto"

  "Save As..."
  "Salva con nome..."

  "Select all occurrences"
  "Seleziona tutte le occorrenze"

  "Select next occurrence"
  "Selezionare ricorrenza successiva"

  "Select previous occurrence"
  "Selezionare occorrenza precedente"

  "Selected"
  "Selezionato"

  "Set Syntax"
  "Impostare Sintassi"

  "Show Last Profiling Report"
  "Mostra ultimo rapporto Profiling"

  "Show*Profiling*"
  "Show * Profiling *"

  "Start Profiling"
  "Inizia Profiling"

  "Stop Profiling"
  "Smettere di Profiling"

  "Text"
  "Testo"

  "Theme Creator"
  "Theme Creator"

  "Tools"
  "Strumenti"

  "Uncomment"
  "Rimuovi commento"

  "Undo"
  "Undo"

  "Unindent"
  "Annulla Rientro"

  "Uninstall..."
  "Disinstalla"

  "Unlock"
  "Sblocca"

  "View"
  "Visualizza"

  "View Console"
  "Vista Console"

  "View Sidebar"
  "Barra laterale"

  "View Status Bar"
  "Visualizza barra di stato"

  "Vim Mode"
  "Modalità di Vim"

}

# plugins.tcl
msgcat::mcmset it {

  "ERROR:  Plugin name is not valid (only alphanumeric and underscores are allowed)"
  "ERRORE: Plugin nome non è valido (solo caratteri alfanumerici e di sottolineatura sono ammessi)"

  "ERROR:  Unable to write plugin file"
  "ERRORE: Impossibile scrivere il file plug-in"

  "Enter plugin name"
  "Immettere il nome del plug-in."

  "Plugin %s installed"
  "Plugin% s installato"

  "Plugin %s uninstalled"
  "Plugin% s disinstallato"

  "Plugin Errors"
  "Errori di plug-in"

  "Syntax errors found in selected plugins"
  "Gli errori di sintassi trovati in estensioni selezionate"

}

# preferences.tcl
msgcat::mcmset it {

  "Preferences: Edit user preferences"
  "Modificare le preferenze dell&#39;utente: Preferenze"

  "Preferences: Reload preferences"
  "Preferenze: Ricarica preferenze"

  "Preferences: Use default preferences"
  "Preferenze: utilizzare le preferenze predefinite"

  "Preferences: View global preferences"
  "Preferenze: Mostra preferenze globali"

}

# sidebar.tcl
msgcat::mcmset it {

  "Add Parent Directory"
  "indirizzario parent"

  "Close Directory Files"
  "Chiudi Directory Files"

  "Delete"
  "Elimina"

  "Delete directory?"
  "(elimina directory)"

  "Delete file?"
  "Elimina file"

  "Duplicate"
  "Duplica"

  "Make Current Working Directory"
  "Directory di lavoro corrente"

  "New Directory"
  "Nuova directory"

  "New File"
  "Nuovo file"

  "Open"
  "Aprire il regalo"

  "Refresh Directory Files"
  "Aggiorna Directory Files"

  "Remove Parent from Sidebar"
  "Rimuovere Parent da Sidebar"

  "Remove from Sidebar"
  "Rimuovi dal Sidebar"

  "Rename"
  "Rinomina"

}

# snippets.tcl
msgcat::mcmset it {

  "Snippet: %s: %s"
  "Snippet:% s:% s"

  "Snippet: *"
  "Snippets"

  "Snippets: Add snippet"
  "Frammenti: Aggiungi snippet"

  "Snippets: Reload all snippets"
  "Frammenti: Ricarica tutti i frammenti"

}

# syntax.tcl
msgcat::mcmset it {

  "Syntax error in %s.syntax file"
  "Errore di sintassi nel file di s.syntax%"

  "Syntax:  %s"
  "Sintassi:% s"

  "Theme:  %s"
  "Tema: %s"

}

# themer.tcl
msgcat::mcmset it {

  "Create"
  "Crea"

  "Create New Theme"
  "Crea nuovo tema..."

  "Create custom"
  "Personalizza"

  "ERROR:  Unable to read %s"
  "ERRORE: Impossibile leggere% s"

  "ERROR:  Unable to write %s"
  "ERRORE: Impossibile scrivere% s"

  "Edit theme"
  "Modifica tema"

  "Enter theme name"
  "Inserire il nome del tema"

  "Error:  Theme is not a supported theme"
  "Errore: Tema non è un tema supportato"

  "Import"
  "Importazione"

  "Import TextMate Theme"
  "Import TextMate Theme"

  "Name:"
  "Nome:"

  "OK"
  "Ok"

  "Reset"
  "invia"

  "Select theme"
  "Seleziona tema"

}

# tke.tcl
msgcat::mcmset it {

  "ERROR:  %s"
  "Errore: %s"

  "Edit theme?"
  "Modifica tema"

  "Import TextMate theme?"
  "Importare TextMate tema?"

}

# tkedat.tcl
msgcat::mcmset it {

  "Unable to open %s for reading"
  "Impossibile aprire il file%1 in lettura."

  "Unable to open %s for writing"
  "Non è possibile aprire%1 in scrittura"

}

# General
msgcat::mcmset it {

  "Cancel"
  "Cancella"

  "Close"
  "Chiudi"

  "Save"
  "Salva"

  "Save As"
  "Salva con nome"

}

