# api.tcl
msgcat::mcmset it {

  "Argument list to api::add_file was not an even key/value pair"
  "Elenco di argomenti di api :: add_file non era una coppia ancor chiave / valore"

}

# bgproc.tcl
msgcat::mcmset it {

  "Unable to run system command"
  "Impossibile eseguire il comando di sistema"

}

# bist.tcl (In development mode -- selectable in the Advanced preferences section -- select "Tools / Run BIST")
msgcat::mcmset it {

  "Built-In Self Test"
  "Built-in self-test (autoverifica integrata)."

  "Decrementing order"
  "Decremento dell&#39;ordine"

  "Edit Test"
  "Modifica test"

  "Edit Test File"
  "Modifica file di prova"

  "FAILED"
  "NEGATIVO"

  "Fail"
  "Fallire"

  "Fail Count"
  "Conteggio fallito"

  "Failed"
  "Fallito"

  "Filter"
  "Filtro"

  "Incrementing order"
  "Ordine incrementativo"

  "Iteration"
  "Iterazione"

  "Iteration count"
  "Conteggio iterazioni"

  "Loop"
  "Ripeti"

  "Loop count"
  "Numero dei passaggi"

  "Loop type"
  "Tipo di Loop"

  "New Test"
  "Nuova provaNew"

  "New Test File"
  "Nuovo file di test"

  "New Test Name"
  "Nome del test"

  "Output"
  "Uscita"

  "PASSED"
  "POSITIVO"

  "Pass"
  "Passato"

  "Pass Count"
  "Passaggi"

  "Passed"
  "Superati"

  "RUNNING BIST"
  "Corsa"

  "Random"
  "Casuale"

  "Refresh"
  "Scegli se gli agenti devono visualizzarsi in modo casuale al refresh della pagina."

  "Results"
  "Risultati"

  "Run Count"
  "Conteggio esecuzioni attività"

  "Run iterations"
  "Iterazioni"

  "Run loops"
  "Cicli"

  "Running"
  "Corsa"

  "Runtime"
  "Durata"

  "Selection method"
  "Metodo di selezione"

  "Setup"
  "Impostare"

  "Total"
  "Totale"

  "hours"
  "ore"

  "minutes"
  "minuti"

  "seconds"
  "secondi"

}

# bitmap.tcl (Strings are found in the theme editor for a bitmapped image)
msgcat::mcmset it {

  "Center image"
  "Centrare immagine"

  "Flip image horizontally"
  "Rifletti l'immagine orizzontalmente"

  "Flip image vertically"
  "Rifletti l'immagine verticalmente"

  "Move image down"
  "Immagine in giù"

  "Move image left"
  "Immagine a sinistra"

  "Move image right"
  "Immagine a destra"

  "Move image up"
  "Immagine in su"

  "Rotate image 90 degrees"
  "Ruota l&apos; immagine di 90 gradi"

  "Transform Tools"
  "Strumenti di trasformazione"

}

# diff.tcl (Go to File menu and select "Show File Differences".  Strings are shown at bottom of editor.)
msgcat::mcmset it {

  "    End: "
  "Fine:"

  "    Start: "
  "Inizio:"

  "Enter difference command"
  "Immettere il comando di differenza"

  "Enter starting file"
  "Inserire il file di partenza"

}

# edit.tcl
msgcat::mcmset it {

  "File successfully written"
  "File scritto correttamente"

  "Filename already exists"
  "Nome file esiste già"

  "Image URL"
  "URL immagine"

  "Link URL"
  "URL del Collegamento"

}

# emmet.tcl
msgcat::mcmset it {

  "Abbreviation"
  "Abbreviazione"

  "Select File to Save"
  "Selezionare il File da salvare"

}

# files.tcl
msgcat::mcmset it {

  "Delete tab?"
  "Elimina scheda"

  "Reload file?"
  "Ricarica file"

  "Unable to determine how to move to trash"
  "Impossibile determinare come spostare nel cestino"

  "Unable to determine platform"
  "Impossibile determinare la piattaforma"

  "Unable to write file"
  "Impossibile scrivere sul file"

  "Unable to write remote file"
  "Impossibile scrivere il file remoto"

}

# gui.tcl
msgcat::mcmset it {

  "Case sensitivity"
  "Sensibile alle maiuscole"

  "Close All Other Tabs"
  "Chiudi le altre schede"

  "Close All Tabs"
  "Chiudi tutte le linguette"

  "Close All Tabs In Pane"
  "Chiudere tutte le schede nel riquadro"

  "Close Other Tabs In Pane"
  "Close Other Tabs In riquadro"

  "Close Tab"
  "Chiudi scheda"

  "Column"
  "Colonna"

  "Copyright"
  "Contattaci"

  "Credits"
  "Crediti"

  "Developer"
  "Sviluppatore"

  "Email"
  "E-mail"

  "Error"
  "Errore"

  "Exact"
  "Esatta"

  "Favorited"
  "Favorito"

  "File already exists.  Use '!' to force an overwrite"
  "File già esistente.  Uso '!' per forzare una sovrascrittura"

  "File index is out of range"
  "Indice non compreso nell'intervallo."

  "Glob"
  "Globale"

  "Hide Tab"
  "Nascondere la scheda"

  "Image displayed in fill-in forms which closes the form UI.  Used in forms such as search, search/replace, and find in files."
  "Immagine visualizzata in forme fill-in che chiude l&#39;interfaccia utente modulo. Utilizzato in forme quali la ricerca, ricerca / sostituzione, e trovare nei file."

  "Image displayed in find field to search for next match."
  "Immagine visualizzata nel campo di ricerca per cercare la corrispondenza successiva."

  "Image displayed in find field to search for previous match."
  "Immagine visualizzata nel campo di ricerca per cercare la corrispondenza precedente."

  "Image used in tab menus to indicate that the file is associated with a difference view."
  "Immagine utilizzata nei menu scheda per indicare che il file è associato con una vista differenza."

  "Image used in tab menus to indicate that the file is locked."
  "Immagine utilizzata nei menu scheda per indicare che il file è bloccato."

  "Image used in tab menus to indicate that the file is readonly."
  "Immagine utilizzata nei menu scheda per indicare che il file è in sola lettura."

  "Image used in tab to indicate that the tab contains a difference view."
  "Immagine utilizzata in tab per indicare che la scheda contiene una vista differenza."

  "Image used in tab to indicate that the tab's file is readonly."
  "Immagine utilizzata in scheda per indicare che il file è in sola lettura della scheda."

  "Image used in tab to indicate that the tab’s file is locked."
  "Immagine utilizzata in scheda per indicare che il file della scheda è bloccata."

  "Image used in tab which, when clicked, closes the tab."
  "Immagine utilizzata in scheda che, se cliccato, chiude la scheda."

  "Image used in the preferences window in the Advanced tab."
  "Immagine utilizzata nella finestra Preferenze nella scheda Avanzate."

  "Image used in the preferences window in the Appearance tab."
  "Immagine utilizzata nella finestra Preferenze nella scheda aspetto."

  "Image used in the preferences window in the Documentation tab."
  "Immagine utilizzata nella finestra Preferenze nella scheda documentazione."

  "Image used in the preferences window in the Editor tab."
  "Immagine utilizzata nella finestra Preferenze nella scheda Editor."

  "Image used in the preferences window in the Emmet tab."
  "Immagine utilizzata nella finestra Preferenze nella scheda Emmet."

  "Image used in the preferences window in the Find tab."
  "Immagine utilizzata nella finestra Preferenze nella scheda trova."

  "Image used in the preferences window in the General tab."
  "Immagine utilizzata nella finestra Preferenze nella scheda generale."

  "Image used in the preferences window in the Plugins tab."
  "Immagine utilizzata nella finestra Preferenze nella scheda plugin."

  "Image used in the preferences window in the Shortcuts tab."
  "Immagine utilizzata nella finestra Preferenze nella scheda collegamenti."

  "Image used in the preferences window in the Sidebar tab."
  "Immagine utilizzata nella finestra Preferenze nella scheda Sidebar."

  "Image used in the preferences window in the Snippets tab."
  "Immagine utilizzata nella finestra Preferenze nella scheda frammenti."

  "Image used in the preferences window in the View tab."
  "Immagine utilizzata nella finestra Preferenze nella scheda visualizzazione."

  "Image used in the preferences window to indicate that a table item is deselected."
  "Immagine utilizzata nella finestra Preferenze per indicare che un elemento della tabella viene deselezionato."

  "Image used in the preferences window to indicate that a table item is selected."
  "Immagine utilizzata nella finestra Preferenze per indicare che è selezionato un elemento della tabella."

  "Image used in the preferences window to indicate that something is true."
  "Immagine utilizzata nella finestra Preferenze per indicare che c'è qualcosa di vero."

  "Images used in tab which will be displayed when the mouse enters the close button area"
  "Immagini utilizzate nella scheda che verranno visualizzate quando il mouse entra nell&#39;area del pulsante di chiusura"

  "In"
  "Oltre"

  "License"
  "Lidcenza"

  "Locked"
  "Bloccato"

  "Move"
  "Muovi"

  "Must be in multicursor mode to insert numbers"
  "Deve essere in modalità multicursor per inserire numeri"

  "No write permissions.  Use '!' to force write."
  "Senza autorizzazioni di scrittura.  Uso '!' per forzare la scrittura."

  "Regexp"
  "Espressione regolare"

  "Release Type"
  "Tipo di rilascio"

  "Replace"
  "Sostituisci"

  "Replace All"
  "Sostituisci tutto"

  "Save request"
  "Salva richiesta"

  "Save this search"
  "Salva ricerca"

  "Starting number:"
  "Primo numero"

  "Tcl/Tk Version"
  "Versione Tcl/Tk"

  "Total Characters"
  "Caratteri totali"

  "Total Lines"
  "Totale linee"

  "Unable to successfully parse number string"
  "Grado di analizzare correttamente la stringa numerica"

  "for"
  "per"

}

# indent.tcl
msgcat::mcmset it {

  "No Indent"
  "Nessun trattino"

}

# ipanel.tcl (Information panel displayed in the sidebar)
msgcat::mcmset it {

  "Binary"
  "Binario"

  "Close Panel"
  "Chiudere il pannello"

  "Counts"
  "Conte"

  "Modified"
  "Modificato"

  "No"
  "Numero"

  "Read Time"
  "Tempo di lettura"

  "Update Info"
  "Aggiorna le Informazioni"

  "Yes"
  "Si"

  "value copied to clipboard"
  "valore copiato negli Appunti"

}

# markers.tcl
msgcat::mcmset it {

  "Marker name:"
  "Nome Marker:"

}

# menus.tcl
msgcat::mcmset it {

  "About"
  "Chi siamo"

  "Absolute"
  "Assoluta"

  "Absolute line numbering"
  "Numerazione di riga assoluta"

  "Add Next Line"
  "Riga successiva"

  "Add Previous Line"
  "Riga precedete&#x0D;"

  "Add next line to selection"
  "Aggiungere la riga successiva alla selezione"

  "Add previous line to selection"
  "Aggiungere la riga precedente alla selezione"

  "Align Cursors Only"
  "Allineare i cursori solo"

  "Align Cursors and Text"
  "Allineare i cursori e testo"

  "Align Panes"
  "Allineare i riquadri"

  "Align current lines in both panes"
  "Allineare le linee di corrente in entrambi i riquadri"

  "Align cursors and text"
  "Allineare i cursori e testo"

  "Align cursors only"
  "Allineare i cursori solo"

  "All Levels"
  "Tutti i Livelli"

  "All language-specific settings for the current session will be removed and the global settings will be applied for the specified language."
  "Tutte le impostazioni specifiche della lingua per la sessione corrente verranno rimosso e applicherà le impostazioni globali per la lingua specificata."

  "All language-specific settings will be removed and the global settings will be applied for the specified language."
  "Verranno rimosse tutte le impostazioni specifiche della lingua e le impostazioni globali si applicherà per la lingua specificata."

  "Append current find text to selection"
  "Aggiungere testo trovare corrente alla selezione"

  "Balance Inward"
  "Equilibrio verso l'interno"

  "Balance Outward"
  "Equilibrio verso l'esterno"

  "Balance tag pair moving inward"
  "Coppia di tag di equilibrio in movimento verso l'interno"

  "Balance tag pair moving outward"
  "Coppia di tag di equilibrio in movimento verso l'esterno"

  "Bold"
  "Grassetto"

  "Bubble Down"
  "Bolla giù"

  "Bubble Up"
  "Proporzione"

  "Bubble lines down one line"
  "Linee di basso di una riga di bolla"

  "Bubble lines up one line"
  "Linee di bolla alto di una riga"

  "Change Working Directory"
  "Cambia la cartella di lavoro"

  "Change working directory"
  "Cambia la cartella di lavoro"

  "Check for update"
  "Controlla aggiornamenti"

  "Checkbox"
  "casella di controllo"

  "Classic Mac"
  "Mac Classic"

  "Clear All"
  "Deseleziona tutto"

  "Close All"
  "Chiudi tutto"

  "Close All Folds"
  "Chiudere tutte le pieghe"

  "Close Current"
  "Chiudi Attuale:"

  "Close Current Fold"
  "Chiudi Attuale:"

  "Close Selected Folds"
  "Vicino selezionata pieghe"

  "Close all folds"
  "Chiudere tutte le pieghe"

  "Close all tabs"
  "Chiudi tutte le schede"

  "Close current session"
  "Chiusura della sessione corrente"

  "Close current tab"
  "Chiudi la scheda attuale"

  "Close fold at current line - all levels"
  "Vicino piega nella riga corrente - tutti i livelli"

  "Close fold at current line - one level"
  "Vicino piega nella riga corrente - un livello"

  "Close selected folds - all levels"
  "Chiudere le pieghe selezionati - tutti i livelli"

  "Close selected folds - one level"
  "Chiudere le pieghe selezionati - un livello"

  "Code"
  "Codice"

  "Command"
  "Comando"

  "Command Result"
  "Risultato del comando"

  "Convert case to lower"
  "Convertire caso per abbassare"

  "Convert case to title"
  "Convertire il caso a titolo"

  "Convert case to upper"
  "Convertire caso superiore"

  "Copy text"
  "Copia (CTRL+C)"

  "Create Fold From Selection"
  "Crea dalla selezione"

  "Create at Current Line"
  "Creare riga corrente"

  "Create fold from selection"
  "Crea dalla selezione"

  "Create marker at current line"
  "Creare indicatore nella riga corrente"

  "Create new plugin"
  "Creare nuovo plugin"

  "Current Bounded Text"
  "Testo limitato corrente"

  "Current Paragraph"
  "Paragrafo corrente"

  "Current Sentence"
  "Configurazione di Festival & Lite (flite)"

  "Cut"
  "Taglia"

  "Cut text"
  "Taglia (CTRL+X)"

  "Decrement by 0.1"
  "Decremento di 0,1"

  "Decrement by 1"
  "diminuisci di"

  "Decrement by 10"
  "diminuisci di"

  "Decrement number by 0.1"
  "Decrementa il numero di 0,1"

  "Decrement number by 1"
  "Diminuire il numero di 1"

  "Decrement number by 10"
  "Decrementa il numero di 10"

  "Delete All Folds"
  "Eliminare tutte le pieghe"

  "Delete Current Fold"
  "Cancella corrente"

  "Delete Selected Folds"
  "Elimina selezionati pieghe"

  "Delete Session"
  "Eliminare Session"

  "Delete User"
  "Cancella utente"

  "Delete all folds"
  "Eliminare tutte le pieghe"

  "Delete all selected folds"
  "Eliminare tutte le pieghe selezionate"

  "Delete current file"
  "Cancella corrente"

  "Delete fold at current line"
  "Eliminare la piega nella riga corrente"

  "Delete language preferences?"
  "Eliminare le preferenze di lingua?"

  "Delete session"
  "Elimina sessione"

  "Delete session language preferences?"
  "Eliminare le preferenze di lingua di sessione?"

  "Delete template"
  "Elimina modello"

  "Disable Vim mode"
  "Disattivare la modalità di Vim"

  "Disable code folding"
  "Disattivare il raggruppamento del codice"

  "Disable two-pane scrolling Synchronization"
  "Disabilitare la sincronizzazione scorrimento due riquadri"

  "Display Text Info"
  "Visualizza testo"

  "Display text information"
  "Visualizzare informazioni di testo"

  "Duplicate current file"
  "Duplicate file corrente"

  "Edit Custom Abbreviations"
  "Modificare abbreviazioni personalizzate"

  "Edit Language"
  "Modificare la lingua"

  "Edit Session"
  "sessione di redazione"

  "Edit User"
  "Modifica Utente"

  "Edit custom Emmet abbreviations"
  "Modificare le abbreviazioni personalizzate di Emmet"

  "Edit language snippets"
  "Modificare i frammenti di lingua"

  "Edit session current language preferences"
  "Modificare le preferenze di lingua corrente sessione"

  "Edit session global preferences"
  "Modificare le preferenze di sessione globale"

  "Edit template"
  "Modifica modello"

  "Edit user current language preferences"
  "Modificare le preferenze utente corrente lingua"

  "Edit user global preferences"
  "Modificare le preferenze dell'utente globale"

  "Edit user snippets"
  "Modificare i frammenti di utente"

  "Enable Code Folding"
  "Attivare codice pieghevole"

  "Enable Synchronized Scrolling"
  "Attivare lo scorrimento sincronizzato"

  "Enable Vim mode"
  "Attivare la modalità di Vim"

  "Enable two-pane scrolling synchronization"
  "Abilitare la sincronizzazione di scorrimento di due riquadri"

  "Encode/Decode Image to Data:URL"
  "Immagine di codificare/decodificare dati: URL"

  "Encode/Decode image to data:URL"
  "Immagine di codificare/decodificare dati: URL"

  "Enter selection mode"
  "Attivare la modalità di selezione"

  "Enumeration"
  "Enumerazione"

  "Evaluate Math Expression"
  "Valutare l'espressione matematica"

  "Evaluate the current math expression"
  "Valutare l'attuale espressione matematica"

  "Expand Abbreviation"
  "Abbreviazione di espandere"

  "Expand Emmet abbreviation"
  "Espandere un'abbreviazione di Emmet"

  "Export As"
  "Esporta come"

  "Export Custom Themes"
  "Temi personalizzati di esportazione"

  "Export complete"
  "Esportazione completata."

  "Export current plugin"
  "Esportare l'attuale plugin"

  "Export file contents"
  "Contenuto del file di esportazione"

  "Favorite file"
  "File Preferiti"

  "File Contents"
  "contenuto di file"

  "Find In Files"
  "Trova nei file"

  "Find Matching Bracket"
  "Trovare corrispondenza staffa"

  "Find Next"
  "Trova successivo"

  "Find Next Bracket Mismatch"
  "Trovare il prossimo staffa Mismatch"

  "Find Previous"
  "Trova precedente"

  "Find Previous Bracket Mismatch"
  "Trova precedente staffa Mismatch"

  "Find and Replace"
  "Trova e sostituisci"

  "Find in files"
  "Cerca nei file@action:inmenu"

  "Find matching character pair"
  "Trovare corrispondenza coppia di caratteri"

  "Find next mismatching bracket"
  "Trovare la staffa non corrisponde a quella successiva"

  "Find previous mismatching bracket"
  "Trovare la staffa non corrisponde a quella precedente"

  "Folding"
  "Piegatura"

  "Format"
  "Formato"

  "Format Text"
  "Formato testo"

  "Format indentation for text"
  "Rientro di formato per il testo"

  "From Clipboard"
  "Copia dagli appunti"

  "Global"
  "a livello mondiale"

  "Go to Matching Pair"
  "Vai al corrispondente coppia"

  "Go to matching tag pair"
  "Vai alla coppia di tag di corrispondenza"

  "Go to next edit point"
  "Vai a punto di montaggio successivo"

  "Go to previous edit point"
  "Andare al punto di montaggio precedente"

  "Goto Last Tab"
  "Vai all&#39;ultima scheda"

  "Goto Next Tab"
  "Goto Tab Avanti"

  "Goto Other Pane"
  "Goto Altro Pane"

  "Goto Previous Tab"
  "Vai a scheda precedente"

  "Goto last tab"
  "GOTO ultima scheda"

  "Goto next difference"
  "Differenza successiva goto"

  "Goto next tab"
  "Scheda successiva goto"

  "Goto other pane"
  "GOTO altro riquadro"

  "Goto previous difference"
  "Differenza precedente"

  "Goto previous tab"
  "Scheda Precedente"

  "Header"
  "Intestazione"

  "Help"
  "Aiuto"

  "Hide All Tabs"
  "Nascondere tutti"

  "Hide Current Tab"
  "Scheda Corrente"

  "Hide Line Numbers"
  "Mostra i numeri di riga"

  "Hide Marker Map"
  "Nascondi mappa marcatore"

  "Hide Meta Characters"
  "Nascondi caratteri"

  "Hide Sidebar"
  "Nascondi barra laterale"

  "Hide Status Bar"
  "Nascondi barra di stato"

  "Hide Tab Bar"
  "Nascondi barra delle linguette"

  "Hide Tcl Console"
  "Nascondere la Console di Tcl"

  "Hide Tcl console"
  "Nascondere la console di Tcl"

  "Hide line numbers"
  "Mostra i numeri di riga"

  "Hide marker map"
  "Nascondi mappa marcatore"

  "Hide meta characters"
  "Nascondi caratteri"

  "Hide sidebar"
  "Nascondi barra laterale"

  "Hide status bar"
  "Nascondi barra di stato"

  "Hide tab bar"
  "Nascondere la barra delle schede"

  "Highlight"
  "Evidenziare"

  "Image"
  "Immagine"

  "Import plugin bundle"
  "Bundle di plugin di importazione"

  "Increment by 0.1"
  "Aumenta di"

  "Increment by 1"
  "Aumenta di"

  "Increment by 10"
  "Aumenta di"

  "Increment number by 0.1"
  "Numero di incremento di 0.1"

  "Increment number by 1"
  "Numero di incremento di 1"

  "Increment number by 10"
  "Numero di incremento di 10"

  "Indent"
  "Indenta"

  "Indent Off"
  "Trattino fuori"

  "Indent selected text"
  "Rientrare il testo selezionato"

  "Indentation"
  "Rientro"

  "Insert bold formatting"
  "Inserire la formattazione in grassetto"

  "Insert checklist formatting"
  "Inserire l'elenco di controllo di formattazione"

  "Insert code formatting"
  "Inserire il codice di formattazione"

  "Insert command result after current line"
  "Inserisci il risultato del comando dopo la riga corrente"

  "Insert enumeration"
  "Inserire enumerazione"

  "Insert file contents after current line"
  "Inserire il contenuto del file dopo la riga corrente"

  "Insert from clipboard"
  "Incolla mediante gli Appunti"

  "Insert header style"
  "Inserire lo stile dell'intestazione"

  "Insert highlight formatting"
  "Inserire la formattazione del testo evidenziato"

  "Insert image formatting"
  "Inserire immagine formattazione"

  "Insert italics formatting"
  "Inserire formattazione corsivo"

  "Insert line above current line"
  "Inserisci riga sopra la riga corrente"

  "Insert line below current line"
  "Inserire la riga sotto la riga corrente"

  "Insert link formatting"
  "Inserire link formattazione"

  "Insert ordered list formatting"
  "Inserire formattazione di elenco ordinato"

  "Insert snippet"
  "Inserisci frammento"

  "Insert strikethrough formatting"
  "Inserire la formattazione in barrato"

  "Insert subscript formatting"
  "Inserire il pedice"

  "Insert superscript formatting"
  "Inserire la formattazione in apice"

  "Insert underline formatting"
  "Inserire la formattazione di sottolineatura"

  "Insert unordered list formatting"
  "Inserire formattazione di elenco non ordinato"

  "Install"
  "Installa"

  "Install plugin"
  "Installa il plugin"

  "Italics"
  "Corsivo"

  "Join Lines"
  "Unisci righe"

  "Join lines"
  "Unisci righe"

  "Jump Backward"
  "Salto indietro"

  "Jump Forward"
  "Salto in avanti"

  "Jump To Line"
  "Passare alla riga"

  "Jump backward"
  "Salto indietro"

  "Jump forward"
  "Salto in avanti"

  "Jump to Next Fold Mark"
  "Saltare al prossimo Fold contrassegno"

  "Jump to Previous Fold Mark"
  "Passare a marchio piega precedente"

  "Jump to line"
  "Passare alla riga"

  "Jump to the next fold indicator"
  "Saltare il prossimo indicatore di piega"

  "Jump to the previous fold indicator"
  "Saltare per l'indicatore di piega precedente"

  "Line Above Current"
  "Linea sopra corrente"

  "Line Below Current"
  "Riga sotto corrente"

  "Line Ending"
  "Fine linea"

  "Line Number"
  "Numero linea"

  "Line Numbering"
  "Numerazione riga"

  "Line Wrapping"
  "Wrap della linea"

  "Link"
  "Collegamento"

  "Lock"
  "Lucchetto"

  "Lock file"
  "File di blocco"

  "Lower Case"
  "minuscolo"

  "Markers"
  "marcatori"

  "Menu"
  "Menù"

  "Merge Lines"
  "Linee di Unione"

  "Merge Panes"
  "Unire i riquadri"

  "Merge panes"
  "Unire i riquadri"

  "Move Cursors Down"
  "Spostare i cursori verso il basso"

  "Move Cursors Left"
  "Sposta i cursori a sinistra"

  "Move Cursors Right"
  "Spostare i cursori a destra"

  "Move Cursors Up"
  "Spostare i cursori"

  "Move cursor to bottom of screen"
  "Spostare il cursore verso il basso dello schermo"

  "Move cursor to end of current line"
  "Spostare il cursore alla fine della riga corrente"

  "Move cursor to first line"
  "Spostare il cursore alla prima linea"

  "Move cursor to last line"
  "Spostare il cursore all'ultima riga"

  "Move cursor to middle of screen"
  "Spostare il cursore al centro dello schermo"

  "Move cursor to next page"
  "Spostare il cursore alla pagina successiva"

  "Move cursor to next word"
  "Spostare il cursore alla parola successiva"

  "Move cursor to previous page"
  "Spostare il cursore alla pagina precedente"

  "Move cursor to previous word"
  "Spostare il cursore alla parola precedente"

  "Move cursor to start of current line"
  "Spostare il cursore all'inizio della riga corrente"

  "Move cursor to top of screen"
  "Spostare il cursore verso l'alto dello schermo"

  "Move multicursors down one line"
  "Spostare multicursors basso di una riga"

  "Move multicursors left one line"
  "Spostare multicursors sinistra una riga"

  "Move multicursors right one line"
  "Spostare multicursors destra di una riga"

  "Move multicursors up one line"
  "Spostare multicursors alto di una riga"

  "Move to First Line"
  "Spostare in prima linea"

  "Move to Last Line"
  "Passare all'ultima riga"

  "Move to Line End"
  "Passare alla linea fine"

  "Move to Line Start"
  "Passare alla linea Start"

  "Move to Next Page"
  "Passare alla pagina successiva"

  "Move to Next Word"
  "Passare alla parola successiva"

  "Move to Previous Page"
  "Passare alla pagina precedente"

  "Move to Previous Word"
  "Passare alla parola precedente"

  "Move to Screen Bottom"
  "Passare alla schermata inferiore"

  "Move to Screen Middle"
  "Spostare a schermo medio"

  "Move to Screen Top"
  "Spostare in cima a schermo"

  "Move to other pane"
  "Spostare in un altro riquadro"

  "New From Template"
  "Nuovo da modello"

  "New Window"
  "Nuova Finestra"

  "New file"
  "Nuovo file"

  "New file from template"
  "Nuovo file da modello"

  "New window"
  "Nuova finestra"

  "Next Difference"
  "Differenza successiva"

  "Next Edit Point"
  "Punto di montaggio successivo"

  "One Level"
  "Un livello"

  "Open All Folds"
  "Aprire tutte le pieghe"

  "Open Current Fold"
  "Aperto corrente Fold"

  "Open Directory"
  "Apri cartella"

  "Open Favorite"
  "Aperto Favorite"

  "Open File"
  "Apri File"

  "Open Recent"
  "Apri recenti"

  "Open Remote"
  "Apre il file remoto"

  "Open Selected Folds"
  "Selezionata l'opzione Apri pieghe"

  "Open all folds"
  "Aprire tutte le pieghe"

  "Open directory"
  "Apri cartella"

  "Open file"
  "Apri file"

  "Open fold at current line - all levels"
  "Aperto piega nella riga corrente - tutti i livelli"

  "Open fold at current line - one level"
  "Aperto piega nella riga corrente - un livello"

  "Open folds to show cursor"
  "Pieghe aperti per mostrare il cursore"

  "Open remote file or directory"
  "Apri file remoto o una directory"

  "Open selected folds - all levels"
  "Aperti selezionati pieghe - tutti i livelli"

  "Open selected folds - one level"
  "Selezionata l'opzione aprire piega - un livello"

  "Ordered Bullet"
  "Punto elenco ordinato"

  "Panes"
  "Riquadri"

  "Paste"
  "Pasta"

  "Paste and Format"
  "Incolla formato"

  "Paste and format text from clipboard"
  "Incolla e formattare il testo dagli Appunti"

  "Paste text from clipboard"
  "Incolla il testo dagli appunti"

  "Plugin Developer Guide"
  "Guida per sviluppatori di plugin"

  "Previous Difference"
  "Differenza precedente"

  "Previous Edit Point"
  "Punto di montaggio precedente"

  "Profiling Report Sorted By"
  "Profilatura Report ordinati per"

  "Profiling started"
  "Profiling non avviato."

  "Profiling stopped"
  "Profiling non fermato."

  "Quit"
  "Esci"

  "Quit application"
  "Esci dall'applicazione"

  "Recent Directories"
  "Directory recenti"

  "Recent Files"
  "File recenti"

  "Redo"
  "Ripeti"

  "Reflect CSS Value"
  "Riflettere il valore CSS"

  "Reflect current CSS value"
  "Riflettere il valore corrente di CSS"

  "Relative"
  "Relativo"

  "Relative line numbering"
  "Numerazione di riga relativa"

  "Reload"
  "Ricaricare"

  "Reload all plugins"
  "Ricarica i plugin"

  "Reload snippets"
  "Frammenti di ricarica"

  "Reload template information"
  "Informazioni sul modello di ricarica"

  "Remove All From Current Buffer"
  "Rimuovere tutto da Buffer corrente"

  "Remove All Markers"
  "Rimuovere tutti i marcatori"

  "Remove Formatting"
  "Rimuovi formattazione"

  "Remove From Current Line"
  "Rimuovere dalla riga corrente"

  "Remove Tag"
  "Rimuovi tag"

  "Remove all markers"
  "Rimuovere tutti i marcatori"

  "Remove all markers from current buffer"
  "Rimuovere tutti i marcatori da buffer corrente"

  "Remove formatting from selected text"
  "Rimuovere la formattazione dal testo selezionato"

  "Remove marker from current line"
  "Rimuovere il marcatore da riga corrente"

  "Remove tag"
  "Rimuovi il tag"

  "Rename current file"
  "Rinominare il file corrente"

  "Reopen File"
  "Riaprire il File"

  "Reopen current file"
  "Riaprire il file corrente"

  "Replace Line With Script"
  "Sostituire la riga con Script"

  "Replace line with script"
  "Sostituire la riga con script"

  "Restart"
  "Riavviare"

  "Run theme editor"
  "Eseguire l'editor tema"

  "Save All"
  "Salva tutto"

  "Save As Remote"
  "Salvare come telecomando"

  "Save As Template"
  "Salva come modello"

  "Save Current"
  "Risparmiare corrente"

  "Save Selection As"
  "Salva selezione con"

  "Save all files"
  "Salvare tutti i file"

  "Save current session"
  "Salvare la sessione corrente?"

  "Save file"
  "Salvataggio"

  "Save file as"
  "Salva come..."

  "Save file as remote file"
  "Salvare il file come file remoto"

  "Save file as template"
  "Salvare il file come modello"

  "Save selected lines"
  "Salvare le righe selezionate"

  "Save sessions as"
  "Salvare le sessioni come"

  "Search References"
  "Cerca referenze"

  "Search language reference documentation"
  "Documentazione di riferimento del linguaggio di ricerca"

  "Search reference documentation"
  "Documentazione di riferimento di ricerca"

  "Select"
  "Seleziona"

  "Select All Matches"
  "Selezionare tutte le partite"

  "Select Current Match"
  "Selezionare la partita corrente"

  "Select Mode"
  "Modalità di _selezione"

  "Select Next Item"
  "Selezionare l'elemento successivo"

  "Select Previous Item"
  "Selezionare l'elemento precedente"

  "Select all find matches"
  "Seleziona tutto trova corrispondenze"

  "Select all text"
  "Seleziona tutto il testo"

  "Select current bracketed text, strings or comment block"
  "Seleziona il testo corrente a bracket, le stringhe o il blocco di commento"

  "Select current line"
  "- Seleziona corrente"

  "Select current paragraph"
  "Seleziona il paragrafo corrente"

  "Select current sentence"
  "Seleziona la frase corrente"

  "Select current word"
  "Parola corrente"

  "Select next tag item"
  "Selezionare l'elemento successivo tag"

  "Select previous tag item"
  "Selezionare l'elemento precedente tag"

  "Send Bug Report"
  "Spedisci la segnalazione di bug."

  "Send Feedback"
  "Invia feedback"

  "Send bug report"
  "Spedisci la segnalazione di bug."

  "Send feedback"
  "Invia un'opinione"

  "Set Syntax"
  "Impostare Sintassi"

  "Set Theme"
  "Imposta il tema"

  "Set current file line ending to CR for Classic Mac"
  "Impostare la riga corrente di file che termina a CR per Mac Classic"

  "Set current file line ending to CRLF for Windows"
  "Impostare la riga corrente del file finale per CRLF per Windows"

  "Set current file line ending to LF for Unix"
  "Impostare la riga corrente del file terminando al LF per Unix"

  "Set indent mode to"
  "Impostare modalità di rientro"

  "Show All Tabs"
  "Mostra tutte le schede"

  "Show Cursor"
  "Mostra cursore"

  "Show Diagnostic Logfile"
  "File di registro Diagnostica;"

  "Show File Difference"
  "Visualizza File differenza"

  "Show Installed"
  "Installato"

  "Show Last Profiling Report"
  "Mostra ultimo rapporto Profiling"

  "Show Line Numbers"
  "Mostra i numeri di riga"

  "Show Marker Map"
  "Indicatore Visualizza mappa"

  "Show Meta Characters"
  "Visualizza caratteri Meta"

  "Show Selected Line Change"
  "Mostrare il cambiamento di linea selezionata"

  "Show Sidebar"
  "Mostra barra laterale"

  "Show Status Bar"
  "Mostra barra di stato"

  "Show Tab Bar"
  "Mostra barra delle schede@info:whatsthis"

  "Show Tcl Console"
  "Visualizza Tcl Console"

  "Show Tcl console"
  "Visualizza Tcl console"

  "Show diagnostic logfile"
  "File di registro Diagnostica;"

  "Show file difference"
  "Visualizza file differenza"

  "Show installed plugins"
  "Plugin installati"

  "Show last profiling report"
  "Visualizza ultimo rapporto di profilatura"

  "Show meta characters"
  "Visualizza caratteri meta"

  "Show plugin developer guide"
  "Visualizza la guida per sviluppatori di plugin"

  "Show plugin source directory in sidebar"
  "Visualizza plugin directory di origine nella barra laterale"

  "Show plugins directory in sidebar"
  "Visualizza directory plugins nella barra laterale"

  "Show selected line change"
  "Mostrare il cambiamento di linea selezionata"

  "Sort Tabs"
  "Ordinare Tabs"

  "Sort tabs"
  "Schede di sorta"

  "Split/Join Tag"
  "Tag: dividere/unire"

  "Split/Join tag"
  "Tag: dividere/unire"

  "Start Profiling"
  "Inizia Profiling"

  "Start profiling"
  "Avviare l'analisi"

  "Stop Profiling"
  "Smettere di Profiling"

  "Stop profiling"
  "Interrompere la profilatura"

  "Strikethrough"
  "Barrato"

  "Subscript"
  "pedice"

  "Superscript"
  "apice"

  "Switch To"
  "Passa a"

  "Switch to session"
  "Passa alla sessione%1@title:menu"

  "Tabs"
  "Tabelle"

  "Tips & Tricks"
  "Suggerimenti e trucchi"

  "Title Case"
  "Tutte Iniziali Maiuscole"

  "Toggle Case"
  "Inverti maiuscole/minuscole"

  "Toggle Comment"
  "Commento di Toggle"

  "Toggle bird's eye view mode"
  "Attivare o disattivare la modalità di visualizzazione dell'occhio dell'uccello"

  "Toggle case of current character"
  "Attiva/disattiva caso del carattere corrente"

  "Toggle comment"
  "Commento di Toggle"

  "Toggle split view mode"
  "Attiva/disattiva visualizzazione modalità split"

  "Toggle tag/rule comment"
  "Commento tag/regola Toggle"

  "Transform"
  "Trasforma"

  "Unable to delete file"
  "Impossibile eliminare il file."

  "Unable to write export file"
  "Impossibile scrivere il file di esportazione"

  "Underline"
  "Sottolineato"

  "Undo"
  "Annulla"

  "Unfavorite file"
  "File sfavorito"

  "Unindent"
  "Annulla Rientro"

  "Unindent selected text"
  "Riduci rientro testo selezionato"

  "Uninstall"
  "Disinstalla"

  "Uninstall plugin"
  "Disinstalla plugin"

  "Unix"
  "Unix"

  "Unlock"
  "Sblocca"

  "Unlock file"
  "Sbloccare file"

  "Unordered Bullet"
  "Punto elenco non ordinato"

  "Update Image Size"
  "Aggiorna immagine"

  "Update img tag width and height attributes"
  "Aggiornare gli attributi width e height di tag img"

  "Upper Case"
  "MAIUSCOLO"

  "User Guide"
  "Guida utente"

  "View Emmet Reference Guide"
  "Visualizza la guida di riferimento Emmet"

  "View the Emmet reference guide"
  "Visualizza la guida di riferimento Emmet"

  "View tips & tricks articles"
  "Visualizza suggerimenti & trucchi articoli"

  "View user guide"
  "MANUALE D'USO"

  "Vim Mode"
  "Modalità di Vim"

  "Windows"
  "Finestre"

  "Wrap With Abbreviation"
  "Avvolgere con abbreviazione"

  "Wrap tag with Emmet abbreviation"
  "Capo tag con un'abbreviazione di Emmet"

  "formatting"
  "formattazione"

}

# plugins.tcl
msgcat::mcmset it {

  "Always grant from developer"
  "Garantire sempre dallo sviluppatore"

  "ERROR"
  "ERRORE"

  "ERROR:  Plugin name already exists"
  "ERRORE: esiste già il nome Plugin"

  "ERROR:  Plugin name is not valid (only alphanumeric and underscores are allowed)"
  "ERRORE: Plugin nome non è valido (solo caratteri alfanumerici e di sottolineatura sono ammessi)"

  "ERROR:  Unable to create plugin directory"
  "ERRORE: Impossibile creare la directory dei plugin"

  "ERROR:  Unable to write plugin files"
  "ERRORE: Impossibile scrivere file dei plugin"

  "Editing"
  "Modifica"

  "Enter plugin name"
  "Immettere il nome del plug-in."

  "Grant"
  "Concessione"

  "Grant permission?"
  "Concedere permission?"

  "Plugin Errors"
  "Errori di plug-in"

  "Plugin Trust Requested"
  "Plugin fiducia desiderata"

  "Plugin export completed successfully"
  "Esportazione completata."

  "Plugin import completed successfully"
  "Prenotazione Completata!"

  "Plugin installed"
  "Plugin installato"

  "Plugin requires permission to view or modify your system."
  "Plugin richiede l&#39;autorizzazione per visualizzare o modificare il sistema."

  "Plugin uninstalled"
  "Plugin disinstallato"

  "Plugins successfully reloaded"
  "PLUGINS ricaricato con successo"

  "Reject"
  "Assente"

  "Syntax errors found in selected plugins"
  "Gli errori di sintassi trovati in estensioni selezionate"

  "Unable to unzip plugin"
  "Impossibile decomprimere il plugin"

  "Unable to zip plugin"
  "Grado di zip plugin"

  "Version Control"
  "Controllo Versione"

}

# plugmgr.tcl
msgcat::mcmset it {

  "Export Plugin"
  "Plugin di esportazione"

  "Markdown"
  "Markdown"

  "Plugin Manager"
  "Gestore plugin"

  "Release Notes"
  "Note di rilascio"

}

# pref_ui.tcl
msgcat::mcmset it {

  "Abbreviation Aliases"
  "Alias di abbreviazione"

  "Add"
  "Aggiungi"

  "Add Language Reference"
  "Aggiungere il riferimento al linguaggio"

  "Additional space between lines"
  "Spazio aggiuntivo tra le linee"

  "Addons"
  "Componenti aggiuntivi"

  "Advanced"
  "Avanzato"

  "Alias"
  "Pseudonimo"

  "Allow scrolling in tab bar"
  "Consentire lo scorrimento nella barra delle schede"

  "Angled bracket"
  "Staffa ad angolo"

  "Appearance"
  "Aspetto"

  "Append characters to search string if entered within"
  "Aggiungere i caratteri per la stringa di ricerca se inserito all'interno di"

  "Auto-match Characters"
  "Auto-match caratteri"

  "Automatically check for updates on start"
  "Controlla automaticamente gli aggiornamenti su start"

  "Automatically highlight matching bracket"
  "Evidenziate automaticamente corrispondente parentesi"

  "Automatically highlight mismatching brackets"
  "Evidenziate automaticamente disadattamento staffe"

  "Automatically insert vendor prefixes"
  "Inserire automaticamente i prefissi fornitore"

  "Automatically load last session on start"
  "Caricare automaticamente l'ultima sessione su start"

  "Automatically set the current working directory to the current tabs directory"
  "Impostare automaticamente la directory di lavoro corrente nella directory corrente di schede"

  "Backtick"
  "backtick"

  "Base Directory"
  "Cartella di base:"

  "Behaviors"
  "Comportamento"

  "Bird's Eye View Font Size"
  "Occhio Visualizza dimensione carattere dell'uccello"

  "Bird's Eye View Width"
  "Larghezza di vista dell'occhio dell'uccello"

  "Buffer"
  "Buffer"

  "Choose Color"
  "Scegli colore"

  "Choose Logfile Directory"
  "Scegliere la Directory di file di log"

  "Clear"
  "Cancella"

  "Clipboard"
  "Supporti rigidi per fogli (appunti)"

  "Clipboard History"
  "Dimensione della cronologia degli appunti"

  "Clipboard history depth"
  "Profondità della cronologia degli Appunti"

  "Closing"
  "Fase di"

  "Color value case"
  "Valore colore:"

  "Command launcher entry"
  "Voce di comando di avvio"

  "Command launcher preview"
  "Anteprima di comando di avvio"

  "Convert to lowercase"
  "Converte in minuscolo"

  "Convert to uppercase"
  "Converte in maiuscolo"

  "Creator"
  "Creatore"

  "Curly bracket"
  "parentesi graffa"

  "Current"
  "Corrente"

  "Current Directory"
  "Directory corrente"

  "Current File Pathname"
  "Percorso del File corrente"

  "Current Filename"
  "Nome del file corrente"

  "Current Line Column"
  "Colonna corrente"

  "Current Line Number"
  "Numero di riga corrente"

  "Current editing buffer directory"
  "Directory corrente di buffer editing"

  "Current working directory"
  "Directory di lavoro corrente"

  "Date"
  "Data"

  "Default Find in Files search method"
  "Trovare predefinito nel metodo di ricerca di file"

  "Default Find search method"
  "Metodo di ricerca di ricerca predefinito"

  "Default Markdown Export Extension"
  "Estensione predefinita Markdown esportazione"

  "Default Plugin Export Directory"
  "directory di esportazione predefinita"

  "Default Theme Export Directory"
  "directory di esportazione predefinita"

  "Default sidebar width on startup"
  "Larghezza della barra laterale predefinita all&#39;avvio"

  "Default theme"
  "Tema predefinito"

  "Default unit for floating point values"
  "Unità per valori a virgola mobile di default"

  "Default unit for integer values"
  "Unità di misura predefinita per i valori integer"

  "Delete snippet"
  "Eliminare il frammento"

  "Delete user bindings and use default?"
  "Eliminare le associazioni utente e utilizzare predefinito?"

  "Development"
  "Sviluppo"

  "Displayed Information"
  "Informazioni visualizzate"

  "Double-quote"
  "Virgolette"

  "Editor"
  "Editore"

  "Enable Vim Mode"
  "Attivare la modalità di Vim"

  "Enable auto-indentation"
  "Attivare auto-indentazione"

  "Enable development mode"
  "Attivare la modalità di sviluppo"

  "Enable fuzzy search"
  "Attivare la ricerca fuzzy"

  "Enable relative line numbering"
  "Attivare la numerazione di riga relativa"

  "Enabled"
  "Abilitato"

  "End-of-line character when saving"
  "Carattere End-of-line durante il salvataggio"

  "Exit the application after the last tab is closed"
  "Uscire dall'applicazione dopo aver chiuso l'ultima scheda"

  "Export Settings"
  "Impostazioni d’esportazione"

  "Extensions"
  "Estensioni"

  "Fonts"
  "Caratteri"

  "Format snippet indentation after insert"
  "Formato frammento rientro dopo insert"

  "General"
  "Generale"

  "Get More Themes"
  "Più Temi"

  "Hide Patterns"
  "Nascondere i modelli"

  "Hide binary files"
  "File binari"

  "Hiding"
  "occultamento"

  "Host"
  "Host"

  "Imported"
  "Importazione completa"

  "Indentation spaces"
  "Indentazione con spazi"

  "Info Panel"
  "Pannello Info"

  "Insert unsorted files at the top of a manually sorted directory"
  "Inserire file indifferenziati nella parte superiore di una directory manualmente ordinata"

  "Insertion cursor width"
  "Larghezza del cursore di inserimento"

  "Keep information panel visible when sidebar doesn't have focus"
  "Mantieni il pannello delle informazioni visibile quando la barra laterale non ha la messa a fuoco"

  "Keyword"
  "Parola chiave"

  "Languages"
  "Lingue"

  "Last"
  "Ultimo"

  "Last accessed"
  "Data ultimo accesso"

  "Line Wrapping Default"
  "Linea confezionamento predefinito"

  "Line count to find Vim modeline information"
  "Conteggio delle righe per trovare informazioni modeline Vim"

  "Line number alignment"
  "Allineamento numero"

  "Logfile Directory"
  "Directory del file di log"

  "Manage Themes"
  "Gestione temi"

  "Manage theme visibility"
  "Gestire la visibilità di tema"

  "Maximum undo history (set to 0 for unlimited)"
  "Cronologia annullamenti massimo (impostato su 0 per illimitato)"

  "Menu Item"
  "Menu Elemento"

  "Menu bindings"
  "Associazioni al menu"

  "Mounts"
  "MONTAGGI"

  "Node Aliases"
  "Alias"

  "Profiler Options"
  "Opzioni del profiler:"

  "Prompt user to save preference changes in global or named session"
  "Richiedi all'utente di salvare le modifiche di preferenza in sessione globale o denominata"

  "Properties"
  "Proprietà"

  "Reading time words per minute"
  "Lettura delle parole del tempo al minuto"

  "Recently opened history depth"
  "Recentemente aperto profondità di storia"

  "Remember last position of command launcher"
  "Ricorda l'ultima posizione del lanciatore di comandi"

  "Remote Base Directory"
  "Directory remota Base"

  "Remove root directory after last sub-file is closed"
  "Rimuovere la directory principale dopo ultimo sub-file è chiuso"

  "Remove trailing whitespace on save"
  "Rimuovere gli spazi vuoti finali su Salva"

  "Report Options"
  "Opzioni di report"

  "Retain case"
  "Mantenere il caso"

  "Return"
  "Ritorna"

  "Ruler column"
  "Colonna di righello"

  "Save changes to current session?"
  "Salvare le modifiche alla sessione corrente?"

  "Save changes to global preferences?"
  "Salvare le modifiche alle preferenze globali?"

  "Search Shortcuts"
  "Cerca scorciatoie"

  "Search Snippets"
  "Cerca snippet"

  "Select Command Launcher Entry Font"
  "Seleziona il carattere della voce di avvio del comando"

  "Select Command Launcher Preview Font"
  "Seleziona Command Launcher Preview Font"

  "Select Editor Font"
  "Seleziona carattere per l'editor"

  "Select Settings Sharing Directory"
  "Selezionare Impostazioni condivisione Directory"

  "Select a plugin"
  "Selezionare un plugin"

  "Select default browsing directory"
  "Selezionare predefinito, esplorazione directory"

  "Selected Text"
  "Testo selezionato"

  "Session"
  "Sessione"

  "Set"
  "Imposta"

  "Set Find in Files line context"
  "Set di trovare nel file linea contesto"

  "Set default open/save browsing directory to"
  "Impostare predefinito Apri/Salva esplorazione directory per"

  "Set find history depth"
  "Insieme trovare profondità di storia"

  "Set jump distance"
  "Set di saltare distanza"

  "Sharing"
  "Condivisione"

  "Sharing Items"
  "Condivisione elementi"

  "Shortcut"
  "Scorciatoia da tastiera"

  "Shortcuts"
  "Scelte rapide..."

  "Show 'Find in Files' result in other pane"
  "Visualizza risultato 'Cerca nei file' in altro riquadro"

  "Show Move To Trash for local files/directories instead of Delete"
  "Visualizza sposta nel cestino per file/directory locali anziché Elimina"

  "Show Tcl console at startup"
  "Visualizza Tcl console all'avvio"

  "Show bird's eye view"
  "angolazione a volo d'uccello; angolazione dall'alto"

  "Show diagnostic logfile at startup"
  "Visualizza file di log diagnostici all'avvio"

  "Show difference file in other pane than original"
  "Visualizza file di differenze in altro riquadro quello originale"

  "Show difference file version information"
  "Visualizza informazioni sulla versione di file di differenza"

  "Show folders at top"
  "Mostra cartelle nella superiore"

  "Show hidden files"
  "Mostrare i file nascosti"

  "Show language submenu"
  "Sottomenu Lingua italiana"

  "Show menubar"
  "Mostra barra dei menu"

  "Single-quote"
  "Apice"

  "Snippet Completion Characters"
  "Caratteri di completamento del frammento"

  "Snippet Text"
  "Testo frammento:"

  "Sort tabs alphabetically on open"
  "Schede di sorta in ordine alfabetico su Apri"

  "Sorting Column"
  "L'ordinamento di colonna"

  "Space"
  "Spazio"

  "Spaces per tab"
  "Spazi per ogni scheda"

  "Square bracket"
  "Parentesi"

  "Stable"
  "stabile"

  "Symbol between CSS property and value"
  "Simbolo tra CSS Proprietà e valore"

  "Symbol placed at end of CSS property"
  "Simbolo posto all'estremità della proprietà CSS"

  "Syntax Coloring"
  "Colorazione della sintassi"

  "Tab"
  "Tab"

  "Tab Stop"
  "Seleziona con tabulazione"

  "This operation cannot be reversed."
  "Questa operazione non può essere annullata."

  "Time"
  "Ora"

  "Unknown"
  "Sconosciuto"

  "Update information panel whenever the sidebar selection changes"
  "Aggiorna il riquadro delle informazioni ogni volta che cambia la barra laterale"

  "Update using release type"
  "Aggiornare utilizzando il tipo di rilascio"

  "Updates"
  "Aggiornamenti"

  "Use Default"
  "Usa di Default"

  "Use appropriate EOL character on system"
  "Utilizzare caratteri EOL appropriato sul sistema"

  "Use carriate return linefeed sequence"
  "Utilizzare la sequenza di avanzamento riga ritorno carriate"

  "Use current width"
  "Larghezza corrente:"

  "Use directory"
  "Utilizzare la directory:"

  "Use linefeed character"
  "Utilizzare il carattere di avanzamento riga"

  "Use original EOL character from file"
  "Utilizzare il carattere EOL originale da file"

  "Use shortened colors"
  "Utilizzare colori accorciati"

  "Use single carriage return character"
  "Utilizzare il carattere singolo di ritorno"

  "Variable"
  "Variabile"

  "Variables"
  "Variabili"

  "Visible"
  "Visibile"

  "You have changed global preferences which will not be visible because you are currently within a named session."
  "Hai cambiato le preferenze globali che non sarà visibile perché sei attualmente all'interno di una sessione denominata."

  "You have changed the current session's preferences which will not be applied globally."
  "Hai cambiato le preferenze della sessione corrente che non verranno applicate globalmente."

  "milliseconds"
  "millesimi di secondo"

  "pixels"
  "pixels"

  "theme"
  "tema"

}

# remote.tcl
msgcat::mcmset it {

  "Close Connection"
  "Chiudi connessione"

  "Connection does not exist"
  "La connessione non esiste"

  "Connection failed"
  "Connessione non riuscita"

  "Connection passed"
  "Connessione passato"

  "Connections"
  "Allacciamenti"

  "Create New Folder"
  "Crea nuova cartella"

  "Delete Connection"
  "Elimina connessione"

  "Delete Group"
  "Cancella gruppo"

  "Delete connection?"
  "Elimina connessione"

  "Delete group?"
  "Cancella il gruppo"

  "Edit Connection"
  "Modifica connessione"

  "Enter Password"
  "Inserisci la password"

  "Folder Name"
  "Nome cartella"

  "Group"
  "Gruppo"

  "Group Name"
  "Nome gruppo"

  "Group Name: "
  "Nome Gruppo”"

  "Image used in remote file selector for the history back button."
  "Immagine utilizzata nel selettore di file remoto per il pulsante indietro di storia."

  "Image used in remote file selector for the history forward button."
  "Immagine utilizzata nel selettore di file remoto per il pulsante avanti di storia."

  "Image used in remote file selector to indicate a file."
  "Immagine utilizzata nel selettore di file remoto per indicare un file."

  "Image used in remote file selector to indicate a folder."
  "Immagine utilizzata nel selettore di file remoto per indicare una cartella."

  "Image used in remote file selector to indicate that a connection is being opened."
  "Immagine utilizzata nel selettore di file remoto per indicare che una connessione viene aperto."

  "Image used in remote file selector to indicate that a connection is opened."
  "Immagine utilizzata nel selettore di file remoto per indicare che una connessione è aperta."

  "New Connection"
  "Nuova connessione"

  "New Folder"
  "Nuova cartella"

  "New Group"
  "Nuovo gruppo"

  "Open Connection"
  "Connessione aperta"

  "Open Remote File"
  "Apre il file remoto"

  "Optional"
  "Facoltativo"

  "Password"
  "Password"

  "Password: "
  "Password:"

  "Port"
  "Porta"

  "Remote Directory"
  "Directory remota %0."

  "Rename Group"
  "Rinomina gruppo"

  "Save File Remotely"
  "Salvare il File in modalità remota"

  "Server"
  "Server"

  "Test Connection"
  "Test di connessione"

  "Type"
  "Tipologia"

  "Unable to connect to"
  "Impossibile connettersi a"

  "Unable to read remote directory contents."
  "Impossibile leggere il contenuto della directory remota."

  "Username"
  "Nome utente"

  "server"
  "Server"

}

# search.tcl
msgcat::mcmset it {

  "No files found in specified directories"
  "Nessun file trovato nelle directory specificate"

  "No search results found"
  "Non è stato trovato alcun risultato."

  "Search wrapped to beginning of file"
  "Ricerca avvolto all'inizio del file."

  "Search wrapped to end of file"
  "Ricerca a capo alla fine del file"

  "substitutions done"
  "sostituzioni di fatto"

}

# select.tcl (Go to Edit menu, select "Select Mode" and hit the '?' key to view strings.)
msgcat::mcmset it {

  "Add Selection Matches"
  "Aggiungi partite di selezione"

  "All To"
  "Tutto a"

  "Anchor"
  "Ancora"

  "Angled Brackets"
  "Supporti"

  "Backticks"
  "Accento grave"

  "Block"
  "Blocco"

  "Character"
  "Carattere"

  "Child"
  "Chid"

  "Clear Selection"
  "Cancella selezione"

  "Comment"
  "Commento"

  "Curly Brackets"
  "Parentesi"

  "Delete Selected Text"
  "Rimuovere riga(e) selezionata(e)"

  "Double Quotes"
  "Doppi apici"

  "Down"
  "Giù di morale"

  "Exit Selection Mode"
  "Esce dalla modalità selezione"

  "Invert Selected Text"
  "Inverti il ​​testo selezionato"

  "Keep Selection"
  "Mantieni la selezione"

  "Left"
  "Sinistra"

  "Line To"
  "Linea a"

  "Modes"
  "Modi"

  "Motions"
  "Moto"

  "Next Sibling"
  "Fratello o Sorella"

  "Paragraph"
  "Paragrafo"

  "Parent"
  "Genitore"

  "Previous"
  "Precedente"

  "Previous Sibling"
  "Di pari livello precedente"

  "Right"
  "Destra"

  "Selection Mode Command Help"
  "Selezione modalità comando Help"

  "Sentence"
  "Pen."

  "Shift Down"
  "Scorri verso il basso"

  "Shift Left"
  "Scorri verso sinistra"

  "Shift Right"
  "Scorri verso destra"

  "Shift Up"
  "Scorri verso l'alto"

  "Single Quotes"
  "Singoli apici"

  "Square Brackets"
  "Parentesi quadre"

  "Swap Anchor"
  "Scambia punto di aggancio"

  "Toggle Help"
  "Seleziona"

  "Toggle Quote Inclusion"
  "Toggle Inclusion inclusione"

  "Type '?' for help.  Hit the ESCAPE key to exit selection mode"
  "Tipo '?' per aiuto.  Premere il tasto ESC per uscire dalla modalità di selezione"

  "Undo Last Change"
  "Annulla l'ultima modifica"

  "Up"
  "Su"

  "Word"
  "Parola"

  "matching instances"
  "istanze di corrispondenza"

}

# sessions.tcl
msgcat::mcmset it {

  "Save session?"
  "Salva sessione"

  "Session state will be lost if not saved"
  "Lo stato di sessione andranno persi se non è stato salvato"

}

# share.tcl
msgcat::mcmset it {

  "Export Settings Data"
  "Esportare i dati delle impostazioni"

  "Favorites"
  "Preferiti"

  "Remote Connections"
  "Connessioni remote"

  "Settings to export"
  "Impostazioni da esportare"

  "Themes"
  "temi"

}

# sidebar.tcl
msgcat::mcmset it {

  "Add Parent Directory"
  "indirizzario parent"

  "By Name"
  "Nome*"

  "Close Directory Files"
  "Chiudi Directory Files"

  "Copy Pathname"
  "Copiare il percorso"

  "Decreasing"
  "Discendente"

  "Delete directories?"
  "Eliminare le directory?"

  "Delete directory?"
  "(elimina directory)"

  "Delete file?"
  "Elimina file"

  "Delete files?"
  "Elimina file"

  "Directory Name:"
  "Nome cartella:"

  "Disconnect From Server"
  "Disconnetti dal server"

  "Folder Name:"
  "Nome cartella:"

  "Hide"
  "Nascondi"

  "Hide Directory Files"
  "File indirizzario"

  "Image displayed in sidebar to indicate a directory that is collapsed"
  "Immagine visualizzata nella barra laterale per indicare una directory che è compresso"

  "Image displayed in sidebar to indicate a directory that is showing its contents"
  "Immagine visualizzata nella barra laterale per indicare una directory che sta mostrando il suo contenuto"

  "Image displayed in sidebar to indicate a file"
  "Immagine visualizzata nella barra laterale per indicare un file"

  "Image displayed in sidebar to indicate a selected directory that is collapsed"
  "Immagine visualizzata nella barra laterale per indicare una directory selezionata che è crollata"

  "Image displayed in sidebar to indicate a selected directory that is expanded"
  "Immagine visualizzata nella barra laterale per indicare una directory selezionata che si espande"

  "Image displayed in sidebar to indicate that a file is currently opened but hidden"
  "Immagine visualizzata nella barra laterale per indicare che un file è attualmente aperto ma nascosto"

  "Image displayed in sidebar to indicate that a file is currently opened in an editing buffer."
  "Immagine visualizzata nella barra laterale per indicare che un file è attualmente aperto in un buffer di modifica."

  "Increasing"
  "Crescente"

  "Make Current Working Directory"
  "Directory di lavoro corrente"

  "Manually"
  "Manuale"

  "New Directory"
  "Nuova directory"

  "New File From Template"
  "Nuovo File da modello"

  "Open Directory Files"
  "File indirizzario"

  "Refresh Directory Files"
  "Aggiorna Directory Files"

  "Remove Parent from Sidebar"
  "Rimuovere Parent da Sidebar"

  "Remove from Sidebar"
  "Rimuovi dal Sidebar"

  "Show"
  "Mostra"

  "Show Difference"
  "Mostrare la differenza"

  "Show Directory Files"
  "File indirizzario"

  "Show Info"
  "Mostra info"

  "Sort"
  "Ordina"

  "Unable to duplicate file"
  "Grado di file duplicati"

}

# snippets.tcl
msgcat::mcmset it {

  "Snippet: *"
  "Snippets"

}

# startup.tcl
msgcat::mcmset it {

  "Change Directory"
  "Cambia cartella"

  "Copies settings data from an existing directory to your home directory."
  "Copia i dati delle impostazioni da una directory esistente alla tua home directory."

  "Copy settings from directory"
  "Copiare le impostazioni dalla directory"

  "Create settings locally"
  "Creare impostazioni localmente"

  "Creates new settings information and places it in your home directory"
  "Crea nuove informazioni sulle impostazioni e lo colloca nella vostra home directory"

  "Finish"
  "Finitura"

  "If you need would like to change your sharing settings, you can do so within Preferences under the General/Sharing tab."
  "Se avete bisogno se volete cambiare le impostazioni di condivisione, è possibile farlo all'interno di preferenze nella scheda generale/condivisione."

  "Items that are selected will be copied to your local home directory. Items that are not selected will be created in your home directory."
  "Gli elementi selezionati verranno copiati alla tua home directory locale. Gli elementi selezionati non verranno creati nella vostra home directory."

  "Items that are selected will be shared with other computers. Items that are not selected will be stored locally and will not be shared."
  "Gli elementi selezionati saranno condivisi con altri computer. Gli elementi non selezionati verranno archiviati localmente e non saranno condivisi."

  "Select Settings Directory"
  "Selezionare impostazioni Directory"

  "Settings"
  "Impostazioni"

  "Settings Options"
  "Opzioni di configurazione"

  "Setup Complete"
  "Configurazione completata"

  "Share"
  "Condividi"

  "Shares settings data from a new or existing directory (ex., iCloud Drive, Google Drive, Dropbox, etc.).  Any changes made to settings data will be available to other sharers."
  "Condivide i dati delle impostazioni da una directory nuova o esistente (es., iCloud Drive, Google Drive, Dropbox, ecc.).  Le modifiche apportate ai dati delle impostazioni sarà disponibile per altri partecipi."

  "Thanks for using TKE, the advanced programmer's editor.  Since this is a new installation of TKE, let's help you get things set up. \\n \\n Click 'Next' below to get things going."
  "Grazie per aver utilizzato TKE, editor del programmatore avanzato.  Poiché si tratta di una nuova installazione di TKE, Let's aiutarti a impostare le cose. \\n \\n fare clic su 'Avanti' sotto per ottenere le cose."

  "Use shared settings"
  "Impostazioni condivise"

  "Welcome"
  "Benvenuto"

  "Welcome To"
  "Benvenuto a"

}

# syntax.tcl
msgcat::mcmset it {

  "Syntax error in syntax file"
  "Errore di sintassi nel file di sintassi"

}

# templates.tcl
msgcat::mcmset it {

  "Delete template?"
  "Elimina modello"

  "Template"
  "Modello"

  "Template Name"
  "Nome modello"

  "deleted"
  "eliminato"

  "saved"
  "salvato"

  "will be permanently deleted"
  "L'elenco verrà eliminato definitivamente."

}

# theme.tcl
msgcat::mcmset it {

  "Amount of border to display around command launcher in pixels"
  "Spessore del bordo da visualizzare intorno lanciatore di comandi in pixel"

  "Background (trough) color used in a standard scrollbar."
  "Colore di sfondo (depressione) utilizzato in una barra di scorrimento standard."

  "Background (trough) color used in the sidebar scrollbar."
  "Contesto (depressione) colore utilizzato nella barra di scorrimento barra laterale."

  "Background (trough) color used in the text scrollbars."
  "Contesto (depressione) colore utilizzato nelle barre di scorrimento del testo."

  "Background color displayed in embedded language code."
  "Colore di sfondo visualizzato nel codice embedded language."

  "Background color for all sidebar items that are not selected."
  "Colore di sfondo per tutte le voci della barra laterale non selezionate."

  "Background color for all sidebar items that are selected."
  "Colore di sfondo per tutti gli elementi della barra laterale che vengono selezionati."

  "Background color for markers in the line gutter and scrollbar"
  "Colore di sfondo per i marcatori nella grondaia di linea e barra di scorrimento"

  "Background color for matching search text"
  "Colore di sfondo per corrispondenza con il testo di ricerca"

  "Background color in difference viewer that shows added lines."
  "Colore di sfondo in visualizzatore differenza che mostra linee aggiunte."

  "Background color in difference viewer that shows deleted lines."
  "Colore di sfondo in visualizzatore differenza che mostra le linee cancellate."

  "Background color of insertion cursor and background marker colors."
  "Il colore di sfondo di inserimento del cursore e lo sfondo marcatori colori."

  "Background color of linemap area."
  "Colore di sfondo dell&#39;area della linemap."

  "Background color of list items when not selected"
  "Colore di sfondo degli elementi di elenco quando non selezionata"

  "Background color of move bar."
  "Colore di sfondo della barra di spostamento."

  "Background color of selection in command launcher"
  "Colore di sfondo della selezione nella schermata di avvio comando"

  "Background color of textual display in command launcher"
  "Colore di sfondo del display testuale nel lanciatore di comandi"

  "Background color of the editing buffer."
  "Colore di sfondo del buffer di modifica."

  "Background color to display when a button-like ttk widget is pressed."
  "Colore di sfondo da visualizzare quando viene premuto un tasto widget di TTK-like."

  "Background color to use for active information values to indicate they are clickable."
  "Colore di sfondo da utilizzare per i valori di informazione attiva per indicare che sono cliccabili."

  "Background color to use for displaying character information that requires the user's attention."
  "Colore di sfondo da utilizzare per la visualizzazione di informazioni di carattere che richiede l'attenzione dell'utente."

  "Background color to use for selected text."
  "Colore di sfondo da utilizzare per il testo selezionato."

  "Background color to use for the file information panel."
  "Colore di sfondo da utilizzare per il pannello di informazioni del file."

  "Background color used for all other tabs that are not the current/active tab in the tabbar."
  "Colore di sfondo utilizzato per tutte le altre schede che non sono la scheda corrente / attiva nella barra delle linguette."

  "Background color used for the current/active menu item."
  "Colore di sfondo utilizzato per la voce di menu corrente / attiva."

  "Background color used for the current/active tab in the tabbar."
  "Colore di sfondo utilizzato per la scheda corrente / attiva nella barra delle linguette."

  "Background color used in highlighted text."
  "Colore di sfondo utilizzato nel testo evidenziato."

  "Background color used in menus."
  "Colore di sfondo usato nei menu."

  "Background color used in the tabbar area."
  "Colore di sfondo utilizzato nella zona barra delle linguette."

  "Color of border around command launcher"
  "Colore del bordo intorno lanciatore di comandi"

  "Color of border drawn around active editing buffer."
  "Colore del bordo disegnato intorno a tampone editing attiva."

  "Color of space between tabs."
  "Colore dello spazio tra le schede."

  "Color of the spacer between the command launcher entry field and the result list"
  "Colore del distanziatore tra il campo di immissione del lanciatore di comando e l'elenco dei risultati"

  "Color of ttk entry widget text border when the entry has keyboard focus."
  "Colore di entrata ttk confine widget di testo quando la voce viene attivato mediante tastiera."

  "Color to use for highlighting closed folds in the line number gutter"
  "Colore da utilizzare per evidenziare chiusi pieghe nella grondaia numero linea"

  "Color used to draw the line which separates the linemap from the text area."
  "Colore usato per disegnare la linea che separa la linemap dall&#39;area di testo."

  "Color used to draw the warning width line in the editing buffer (as well as the line separating the gutter from the editing buffer)."
  "Colore usato per disegnare la linea larghezza avviso nel buffer di modifica (come pure la linea che separa la grondaia dal buffer di modifica)."

  "Command Launcher Options"
  "Opzioni di comando di avvio"

  "Default 'darkcolor' for all ttk widgets."
  "Default &#39;darkcolor&#39; per tutti i widget TTK."

  "Default background color to use for all ttk widgets that are in a disabled state."
  "Colore di sfondo predefinito da utilizzare per tutti i widget TTK che si trovano in uno stato disabilitato."

  "Default background color to use for all ttk widgets when the mouse cursor hovers over the widget."
  "Colore di sfondo predefinito da utilizzare per tutti i widget TTK quando il cursore del mouse passa sopra il widget."

  "Default background color to use for all ttk widgets."
  "Colore di sfondo predefinito da utilizzare per tutti i widget TTK."

  "Default border color for all ttk widgets."
  "Colore del bordo di default per tutti i widget TTK."

  "Default color for non-syntax highlighted text."
  "Colore predefinito per non sintassi testo evidenziato."

  "Default foreground text color to use for all ttk widgets that are in a disabled state."
  "Predefinito colore di testo in primo piano da utilizzare per tutti i widget TTK che si trovano in uno stato disabilitato."

  "Default foreground text color to use for all ttk widgets."
  "Predefinito colore di testo in primo piano da utilizzare per tutti i widget TTK."

  "Determines the number of grips strips to display in the grip area between resizable panes."
  "Determina il numero di grip strisce da visualizzare nella zona di presa tra i riquadri ridimensionabili."

  "Determines the thickness of the grip area between resizable panes."
  "Determina lo spessore della zona di presa tra i riquadri ridimensionabili."

  "ERROR:  Unable to read"
  "ERRORE: Impossibile leggere"

  "Foreground (slider) color used in a standard scrollbar."
  "Colore di primo piano (a scorrimento) utilizzato in una barra di scorrimento standard."

  "Foreground (slider) color used in the sidebar scrollbar."
  "Primo piano (slider) colore utilizzato nella barra di scorrimento barra laterale."

  "Foreground (slider) color used in the text scrollbars when pane synchronization is enabled."
  "Colore di primo piano (a scorrimento) utilizzato nelle barre di scorrimento del testo quando è attivata la sincronizzazione del riquadro."

  "Foreground (slider) color used in the text scrollbars."
  "Primo piano (slider) colore utilizzato nelle barre di scorrimento del testo."

  "Foreground color for matching search text"
  "Colore di primo piano per corrispondenza con il testo di ricerca"

  "Foreground color of list items when not selected"
  "Colore di primo piano degli elementi di elenco quando non selezionata"

  "Foreground color of move bar."
  "Colore di primo piano della barra di spostamento."

  "Foreground color of selection in command launcher"
  "Colore di primo piano della selezione nella schermata di avvio comando"

  "Foreground color of textual display in command launcher"
  "Colore di primo piano del display testuale nel lanciatore di comandi"

  "Foreground color to use for title text in the information panel."
  "Colore di primo piano da utilizzare per il testo del titolo nel riquadro informazioni."

  "Foreground color to use for value text in the information panel."
  "Colore di primo piano da utilizzare per il testo di valore nel pannello informazioni."

  "Foreground color used in menu items with checks or buttons."
  "Colore di primo piano utilizzato nelle voci di menu con pulsanti o controlli."

  "Foreground text color for strings."
  "Colore del testo di primo piano per le stringhe."

  "Foreground text color to use for all miscellaneous1 labeled text."
  "Colore del testo di primo piano da utilizzare per tutte le miscellaneous1 etichettati testo."

  "Foreground text color to use for all miscellaneous2 labeled text."
  "Colore del testo di primo piano da utilizzare per tutte le miscellaneous2 etichettati testo."

  "Foreground text color to use for all miscellaneous3 labeled text."
  "Colore del testo di primo piano da utilizzare per tutte le miscellaneous3 etichettati testo."

  "Foreground text color to use for comments."
  "Colore del testo di primo piano da utilizzare per i commenti."

  "Foreground text color to use for displaying line numbers."
  "Colore testo in primo piano da utilizzare per la visualizzazione dei numeri di riga."

  "Foreground text color to use for displaying numbers."
  "Colore testo in primo piano da utilizzare per la visualizzazione dei numeri."

  "Foreground text color to use for function calls."
  "Colore del testo in primo piano da utilizzare per chiamate di funzione."

  "Foreground text color to use for language-specific keywords."
  "Colore del testo di primo piano da utilizzare per le parole chiave specifiche della lingua."

  "Foreground text color to use for language-specific punctuation."
  "Colore testo in primo piano da utilizzare per la punteggiatura specifiche della lingua."

  "Foreground text color to use for meta syntax."
  "Colore del testo di primo piano da utilizzare per la sintassi meta."

  "Foreground text color to use for precompiler syntax."
  "Colore del testo di primo piano da utilizzare per la sintassi di precompilazione."

  "Foreground text color to use for readable meta syntax."
  "Colore del testo in primo piano da utilizzare per leggibile sintassi di meta."

  "Foreground text color to use for selected text."
  "Colore testo in primo piano da utilizzare per il testo selezionato."

  "Foreground text color to use for variables."
  "Colore del testo in primo piano da utilizzare per le variabili."

  "Foreground text color used for all other tabs that are not the current/active tab in the tabbar."
  "Colore del testo in primo piano utilizzato per tutte le altre schede che non sono nella scheda corrente/attivo nella tabbar."

  "Foreground text color used for menus item that are disabled."
  "Colore del testo di primo piano utilizzato per la voce di menu che sono disabilitati."

  "Foreground text color used for the current/active menu item."
  "Colore del testo di primo piano utilizzato per la voce di menu corrente / attiva."

  "Foreground text color used for the current/active tab in the tabbar."
  "Colore del testo in primo piano utilizzato per la scheda corrente/attivo nella tabbar."

  "Foreground text color used in menus."
  "Colore del testo di primo piano utilizzata nei menu."

  "Foreground text/image color used in tabbar and tabs."
  "Primo piano colore del testo / immagine utilizzato in barra delle linguette e le schede."

  "Images"
  "Immagini"

  "Maximum thickness of the command launcher scrollbar when it is active."
  "Spessore massimo della barra di scorrimento di lanciatore di comando quando è attivo."

  "Maximum thickness of the text scrollbar when it is active."
  "Spessore massimo della barra di scorrimento del testo quando è attivo."

  "Maximum thickness of the text scrollbars when they are active."
  "Spessore massimo delle barre di scorrimento del testo quando sono attivi."

  "Menu Options"
  "Opzioni del menu"

  "Menu relief value."
  "Valore sollievo menu."

  "Pixel height of the spacer between the command launcher entry field and the result list"
  "Altezza in pixel del distanziatore tra il campo di immissione del lanciatore di comando e l'elenco dei risultati"

  "Pixel height of the tabbar widget."
  "Altezza Pixel del widget barra delle linguette."

  "Relief used in drawing the tabs."
  "Sollievo utilizzato nella redazione delle schede."

  "Relief value of the sidebar area."
  "Valore rilievo della zona barra laterale."

  "Scrollbar slider color used in the command launcher results list"
  "Colore del dispositivo di scorrimento ScrollBar utilizzato nell'elenco dei risultati di comando di avvio"

  "Sidebar Info Panel Options"
  "Opzioni del pannello Info Sidebar"

  "Sidebar Options"
  "Opzioni Sidebar"

  "Sidebar Scrollbar Options"
  "Sidebar Opzioni Scrollbar"

  "Specifies background color of command launcher entry and list"
  "Specifica il colore di sfondo della voce di avvio di command ed elenco"

  "Specifies foreground color of command launcher entry and list"
  "Specifica il colore di primo piano della voce di avvio di command ed elenco"

  "Specifies the color drawn around the border of the sidebar when a dragged file is droppable"
  "Specifica il colore disegnato intorno al bordo della barra laterale quando un file trascinato è trovabile"

  "Specifies the color to display around the sidebar when the sidebar does not have the focus."
  "Specifica il colore per visualizzare tutto il sidebar quando la barra laterale non ha la messa a fuoco."

  "Specifies the color to display around the sidebar when the sidebar has the focus."
  "Specifica il colore per visualizzare tutto il sidebar quando la barra laterale ha il focus."

  "Specifies the default background color to use for text that is selected in a standard ttk widget (this does not include the editing buffer)."
  "Specifica il colore di sfondo predefinito da utilizzare per il testo selezionato in un widget TTK standard (questo non include il buffer di modifica)."

  "Specifies the default foreground text color to use for text that is selected in a standard ttk widget (this does not include the editing buffer)."
  "Specifica il colore di testo in primo piano predefinito da utilizzare per il testo selezionato in un widget TTK standard (questo non include il buffer di modifica)."

  "Specifies the default relief to use when drawing ttk widgets."
  "Specifica il sollievo predefinito da utilizzare quando si disegna widget TTK."

  "Specifies the pixel thickness of the highlight line."
  "Specifica lo spessore dei pixel della linea di evidenziazione."

  "Standard Scrollbars"
  "Barre di scorrimento standard"

  "Syntax Colors"
  "Colori sintassi"

  "Tab Options"
  "Scheda Opzioni"

  "Text Scrollbar Options"
  "Opzioni di testo Scrollbar"

  "Text color for all sidebar items that are not selected."
  "Colore del testo per tutti gli elementi della barra laterale non selezionate."

  "Text color for all sidebar items that are selected."
  "Colore del testo per tutti gli elementi della barra laterale che vengono selezionati."

  "ttk Widget Colors"
  "Colori degli oggetti"

}

# themer.tcl (Select "Tools / Theme Editor" to view window containing these strings)
msgcat::mcmset it {

  "   Show Selected Option"
  "Mostra Opzione selezionata"

  "   Show Selected Value"
  "Mostra valore selezionato"

  "By"
  "A cura di"

  "Categories"
  "﻿Categorie"

  "Change Base Color"
  "Cambia colore"

  "Choose Theme"
  "Seleziona tema"

  "Created By"
  "Creato da"

  "Custom Directory"
  "Elenco Personalizzato"

  "Custom..."
  "Personalizzato"

  "Delete swatch?"
  "Elimina campione?"

  "Description"
  "Descrizione"

  "Details"
  "Dettagli"

  "Done"
  "Completato"

  "Enable Copy Mode"
  "Attivare la modalità di copia"

  "Export BMP Data"
  "Esporta i dati BMP"

  "Export BMP Mask"
  "Esportazione maschera BMP"

  "Export Bitmap Data"
  "Esportare i dati bitmap"

  "Export Theme As"
  "Tema di esportazione come"

  "GIF Photo"
  "Foto GIF"

  "Import BMP Data"
  "Importa dati"

  "Import BMP Mask"
  "Maschera Importa BMP"

  "Import Bitmap Data"
  "Importare i dati bitmap"

  "Import Error"
  "Errore di importazione"

  "Import Theme File"
  "Importa file Theme"

  "Installation Directory"
  "Cartella di installazione"

  "License File"
  "License File (File licenza)"

  "Modifications"
  "Modifica"

  "One-Color Bitmap"
  "Bitmap One-Color"

  "Paste Theme Items"
  "Incollare gli elementi del tema"

  "Relief: "
  "Rilievo:"

  "Save As:"
  "Salva con nome:"

  "Save error"
  "Errore di salvataggio"

  "Save theme changes?"
  "Salvare le modifiche a tema?"

  "Select Directory"
  "Seleziona directory"

  "Show All"
  "Mostra Tutto"

  "Show Category"
  "Mostra categoria"

  "Show Color"
  "Visualizzare il colore?"

  "Show Selected Option"
  "Visualizza opzione selezionata"

  "Show Selected Value"
  "Valore selezionato"

  "Swatch"
  "Swatch"

  "Swatch Colors"
  "Colori Swatch"

  "Table Copy"
  "Copia della tabella"

  "Table Filters"
  "Filtri Tabella"

  "Table Search"
  "Tabella ricerca"

  "The current theme has unsaved changes."
  "Il tema corrente presenta modifiche non salvate."

  "Theme Name"
  "Nome del Tema"

  "Tree Style: "
  "Albero Stile:"

  "Two-Color Bitmap"
  "Bitmap due colori"

  "Unknown color value format"
  "Formato del valore di colore sconosciuto"

  "User Directory"
  "Cartella utente"

  "Value: "
  "Valore:"

  "Website"
  "Sito Web"

}

# themes.tcl
msgcat::mcmset it {

  "Batch custom theme export completed successfully"
  "Esportazione di tema personalizzato batch completato con successo"

  "Theme"
  "Tema"

  "Theme:*"
  "theme"

}

# tke.tcl
msgcat::mcmset it {

  "Import TKE plugin?"
  "Importazione TKE plugin?"

  "Import TKE theme?"
  "Tema Import TKE?"

  "Import TextMate theme?"
  "Importare TextMate tema?"

}

# tkedat.tcl
msgcat::mcmset it {

  "Unable to read"
  "Impossibile leggere"

}

# vim.tcl
msgcat::mcmset it {

  "COMMAND MODE"
  "modo comando"

  "File format unrecognized"
  "Formato non riconosciuto di file"

  "Filename directory does not exist"
  "Nome del file directory non esiste"

  "Folding method unrecognized"
  "Pieghevole metodo non riconosciuto"

  "INSERT MODE"
  "Modo inserisci"

  "Illegal modelines value"
  "Valore di modelines illegale"

  "MULTIMOVE MODE"
  "MODALITÀ MULTIMOVE"

  "Number width not a number"
  "Numero larghezza non è un numero"

  "Selection value is unsupported"
  "Valore di selezione non è supportato"

  "Shiftwidth value is not an integer"
  "Il valore non è un Intero."

  "Tabstop value is not an integer"
  "Il valore non è un Intero."

  "Unrecognized vim option"
  "Opzione non riconosciuta vim"

  "VISUAL BLOCK MODE"
  "MODALITÀ VISUAL BLOCK"

  "VISUAL LINE MODE"
  "MODALITÀ VISUAL LINE"

  "VISUAL MODE"
  "Visuale"

}

# General
msgcat::mcmset it {

  "All"
  "Tutti"

  "Attributes"
  "Attributi"

  "Auto-Indent"
  "Rientro automatico"

  "Back"
  "Indietro"

  "Bird's Eye View"
  "angolazione a volo d'uccello; angolazione dall'alto"

  "Browse"
  "Naviga"

  "Cancel"
  "Cancella"

  "Check for Update"
  "Ricerca aggiornamenti"

  "Choose"
  "Scegli"

  "Close"
  "Chiudi"

  "Copy"
  "Copia"

  "Create"
  "Crea"

  "Current Line"
  "Riga corrente"

  "Current Word"
  "Parola corrente"

  "Cursor"
  "Cursore"

  "Delete"
  "Elimina"

  "Directory"
  "Directory"

  "Documentation"
  "Documentazione"

  "Duplicate"
  "Duplica"

  "Edit"
  "Modifica"

  "Emmet"
  "Emmet"

  "Enable code folding"
  "Attivare codice pieghevole"

  "Encoding"
  "Codifica"

  "Export"
  "Esporta"

  "Favorite"
  "Favorito"

  "File"
  "File"

  "File Name:"
  "Nome File:"

  "File System"
  "File system"

  "Find"
  "Cerca"

  "Find next occurrence"
  "Trovare l'occorrenza successiva"

  "Find previous occurrence"
  "Trovare l'occorrenza precedente"

  "Image displayed in sidebar information panel for closing the panel"
  "Immagine visualizzata nel pannello informazioni sidebar per il pannello di chiusura"

  "Image displayed in sidebar information panel for refreshing content"
  "Immagine visualizzata nel pannello informazioni sidebar per l'aggiornamento di contenuto"

  "Image displayed in sidebar information panel for showing file in sidebar"
  "Immagine visualizzata nel pannello informazioni sidebar per file che mostra nella barra laterale"

  "Import"
  "Importazione"

  "Insert"
  "Inserisci"

  "Language"
  "Lingua"

  "Language Documentation"
  "Documentazione in lingua"

  "Launcher"
  "Utilità di avvio"

  "Line"
  "Linea"

  "Miscellaneous"
  "Varie"

  "Move To Trash"
  "Sposta nel cestino@action:inmenu"

  "Move to Other Pane"
  "Spostarsi Altro Pane"

  "Name"
  "Nome"

  "New File"
  "Nuovo file"

  "Next"
  "Successivo"

  "Node"
  "Nodo"

  "None"
  "Nessuno"

  "OK"
  "Ok"

  "Open"
  "Aprire il regalo"

  "Options"
  "Opzioni"

  "Output Directory"
  "Cartella di output"

  "Parenthesis"
  "Parentesi"

  "Plugin"
  "Plugin"

  "Plugins"
  "Plugin"

  "Preferences"
  "Preferenze"

  "Preview"
  "Anteprima"

  "Rename"
  "Rinomina"

  "Run"
  "Esegui"

  "Save"
  "Salva"

  "Save As"
  "Salva con nome"

  "Search"
  "Cerca"

  "Selected"
  "Selezionato"

  "Sessions"
  "Sessioni"

  "Show in Sidebar"
  "Mostra in Sidebar"

  "Show line numbers"
  "Mostra i numeri di riga"

  "Show marker map"
  "Indicatore Visualizza mappa"

  "Show sidebar"
  "Mostra sidebar?"

  "Show status bar"
  "Barra di stato"

  "Show tab bar"
  "Mostra barra delle schede@info:whatsthis"

  "Sidebar"
  "Barra laterale"

  "Smart Indent"
  "Trattino intelligente"

  "Snippet"
  "Frammento"

  "Snippets"
  "Snippet"

  "Split View"
  "Dividi la vista"

  "Syntax"
  "Sintassi"

  "TKE Updater"
  "Aggiorna Cestino"

  "Templates"
  "Modelli"

  "Test"
  "Casella di testo"

  "Theme Editor"
  "Editor tema"

  "Tools"
  "Strumenti"

  "Unable to rename file"
  "Impossibile rinominare"

  "Unable to write"
  "Impossibile scrivereQNativeSocketEngine"

  "Unfavorite"
  "Elimina dai preferiti"

  "Update"
  "Aggiorna"

  "Value"
  "Valore"

  "Version"
  "Versione"

  "View"
  "Visualizza"

}

