# api.tcl
msgcat::mcmset it {

  "Argument list to api::add_file was not an even key/value pair"
  "Elenco di argomenti di api :: add_file non era una coppia ancor chiave / valore"

  "Argument list to api::add_file was not in the form 'filename [<option> <value>]*'"
  "Elenco di argomenti di api :: add_file non era in forma &#39;filename [ <option><value> ] * &#39;"

  "get_home_directory can only be called within plugin code"
  "get_home_directory possono essere chiamati solo all&#39;interno di codice del plugin"

}

# bgproc.tcl
msgcat::mcmset it {

  "Unable to run system command (%s)"
  "Impossibile eseguire il comando di sistema (% s)"

}

# gui.tcl
msgcat::mcmset it {

  "%s, Line: %d, Column: %d"
  "% S, riga% d, colonna:% d"

  "Close All Tabs"
  "Chiudi tutte le linguette"

  "Close Other Tab(s)"
  "Chiudi Other Tab (s)"

  "Close Other*"
  "Chiudi un altro"

  "Close Tab"
  "Chiudi scheda"

  "Copyright %d-%d"
  "Copyright% d,% d"

  "Delete tab?"
  "Elimina scheda"

  "Developer:"
  "Sviluppatore:"

  "Email:"
  "E-mail:"

  "File attribute (%s) does not exist"
  "Attributo di file (% s) non esiste"

  "File index is out of range"
  "Indice non compreso nell'intervallo."

  "Line: %d, Column: %d"
  "Line:% d, colonna:% d"

  "Locked"
  "Bloccato"

  "Move to Other Pane"
  "Spostarsi Altro Pane"

  "Move*"
  "Sposta"

  "Reload file?"
  "Ricarica file"

  "Save request"
  "Salva richiesta"

  "Total Lines: %d, Total Characters: %d"
  "Totale Lines:% d, totale Personaggi:% d"

  "Unable to find current file (tab: %s)"
  "Impossibile trovare il file corrente (scheda:% s)"

  "Untitled"
  "Untitled"

  "Version:"
  "Versione:"

}

# markers.tcl
msgcat::mcmset it {

  "Marker name:"
  "Nome Marker:"

}

# menus.tcl
msgcat::mcmset it {

  "                                  Profiling Report Sorted By (%s)"
  "Profiling Rapporto Ordinati per (% s)"

  "About TKE"
  "Chi TKE"

  "Align cursors"
  "Allineare i cursori"

  "All"
  "Tutti"

  "Append next occurrence"
  "Aggiunge ricorrenza successiva"

  "Clear All"
  "Deseleziona tutto"

  "Close All"
  "Chiudi tutto"

  "Comment"
  "Commento"

  "Copy"
  "Copia"

  "Create new..."
  "Creare nuovo"

  "Create..."
  "Crea"

  "Cut"
  "Taglia"

  "Edit"
  "Modifica"

  "Edit user"
  "Modifica utente"

  "Edit..."
  "Modifica..."

  "File"
  "File"

  "Find"
  "Find"

  "Find and Replace"
  "Trova e sostituisci"

  "Find in files"
  "Cerca nei file@action:inmenu"

  "Find marker"
  "EVIDENZIATORI"

  "Find matching pair"
  "Trova pair corrispondenti"

  "Format Text"
  "Formato testo"

  "Goto Last Tab"
  "Goto Last Tab"

  "Goto Next Tab"
  "Goto Tab Avanti"

  "Goto Other Pane"
  "Goto Altro Pane"

  "Goto Previous Tab"
  "Vai a scheda precedente"

  "Help"
  "Aiuto"

  "Hide Console"
  "Hide Console"

  "Hide Sidebar"
  "Nascondi barra laterale"

  "Hide Status Bar"
  "Nascondi barra di stato"

  "Hide Tab Bar"
  "Hide Tab Bar"

  "Import TextMate theme..."
  "Import tema TextMate ..."

  "Indent"
  "Indenta"

  "Insert enumeration"
  "Inserisci enumerazione"

  "Install..."
  "Installa"

  "Launcher"
  "Utilità di avvio"

  "Lock"
  "Lucchetto"

  "Menu Bindings"
  "Associazioni al menu"

  "Menu: About TKE"
  "Menu: TKE"

  "Menu: Align cursors"
  "Menu: Allineare i cursori"

  "Menu: Append next occurrence"
  "Menu: Aggiungere ricorrenza successiva"

  "Menu: Close all tabs"
  "Menu: Chiudere tutte le schede"

  "Menu: Close current tab"
  "Menu: Chiudi scheda corrente"

  "Menu: Comment selected text"
  "Menu: Commento testo selezionato"

  "Menu: Copy selected text"
  "Menu: Copia testo selezionato"

  "Menu: Create new plugin"
  "Menu: Creare nuovo plugin"

  "Menu: Create new theme"
  "Crea nuovo tema..."

  "Menu: Cut selected text"
  "Menu: Tagliare il testo selezionato"

  "Menu: Disable Vim mode"
  "Menu: Modalità Disable Vim"

  "Menu: Edit Tke theme"
  "Menu: Modifica Tke tema"

  "Menu: Edit snippets"
  "Menu: Modifica frammenti"

  "Menu: Edit user menu bindings"
  "Associazioni Edit Menu utente: Menu"

  "Menu: Edit user preferences"
  "Modificare le preferenze dell&#39;utente: Menu"

  "Menu: Enable Vim mode"
  "Menu: Attivare la modalità Vim"

  "Menu: Find"
  "Menu: Trova"

  "Menu: Find and Replace"
  "Menu: Trova e sostituisci"

  "Menu: Find in files"
  "Menu: Trova nei file"

  "Menu: Find matching character pair"
  "Menu: trovare corrispondenza coppia di caratteri"

  "Menu: Find next occurrence"
  "Menu: Trova l&#39;occorrenza successiva"

  "Menu: Find previous occurrence"
  "Menu: Trova occorrenza precedente"

  "Menu: Goto last tab"
  "Menu: ultima scheda Goto"

  "Menu: Goto next tab"
  "Menu: Goto scheda successiva"

  "Menu: Goto other pane"
  "Menu: Goto altro riquadro"

  "Menu: Goto previous tab"
  "Menu: Goto scheda precedente"

  "Menu: Hide Tab Bar"
  "Menu: Hide Tab Bar"

  "Menu: Hide console"
  "Menu: Hide console"

  "Menu: Hide sidebar"
  "Menu: Hide sidebar"

  "Menu: Hide status bar"
  "Nascondi barra di stato"

  "Menu: Import TextMate theme"
  "Menu: Import TextMate tema"

  "Menu: Indent selected text"
  "Menu: Rientro testo selezionato"

  "Menu: Insert enumeration"
  "Menu: Inserire enumerazione"

  "Menu: Install plugin"
  "Menu: installare plug-"

  "Menu: Lock file"
  "Menu: file di blocco"

  "Menu: Move to other pane"
  "Menu: Sposta altri riquadro"

  "Menu: New file"
  "Menu: Nuovo file"

  "Menu: Open directory"
  "Menu: directory aperta"

  "Menu: Open file"
  "Menu: Aprire il file"

  "Menu: Paste and format text from clipboard"
  "Menu: Pasta e formato di testo dal clipboard"

  "Menu: Paste text from clipboard"
  "Incolla testo dagli appunti"

  "Menu: Quit application"
  "Menu: Uscire applicazione"

  "Menu: Redo"
  "Menu: Redo"

  "Menu: Reload all plugins"
  "Menu: Ricarica tutti i plugin"

  "Menu: Reload all snippets"
  "Menu: Ricarica tutti i frammenti"

  "Menu: Restart tke"
  "Menu: Restart TKE"

  "Menu: Save all files"
  "Menu: Salvare tutti i file"

  "Menu: Save file"
  "Menu: Salva file"

  "Menu: Save file as"
  "Menu: Salva file come"

  "Menu: Select all occurrences"
  "Menu: Selezionare tutte le occorrenze"

  "Menu: Select all text"
  "Seleziona tutto il testo"

  "Menu: Set user bindings to global bindings"
  "Menu: impostare le associazioni degli utenti per associazioni globali"

  "Menu: Set user preferences to global preferences"
  "Menu: impostare le preferenze utente alle preferenze globali"

  "Menu: Show Tab Bar"
  "Menu: Mostra Tab Bar"

  "Menu: Show console"
  "Menu: Mostra console"

  "Menu: Show last profiling report"
  "Menu: Mostra ultimo rapporto profiling"

  "Menu: Show sidebar"
  "Menu: Visualizza sidebar"

  "Menu: Show status bar"
  "Menu: Mostra barra di stato"

  "Menu: Sort tabs"
  "Menu: Ordina schede"

  "Menu: Start profiling"
  "Menu: Start profiling"

  "Menu: Stop profiling"
  "Menu: Stop profiling"

  "Menu: Toggle split view mode"
  "Menu: Toggle modalità di visualizzazione divisa"

  "Menu: Uncomment selected text"
  "Menu: testo Uncomment selezionato"

  "Menu: Undo"
  "Menu: Annulla"

  "Menu: Unindent selected text"
  "Menu: testo Unindent selezionato"

  "Menu: Uninstall plugin"
  "Menu: Uninstall plugin di"

  "Menu: Unlock file"
  "Menu: Sblocca il file"

  "Menu: View User Guide"
  "Menu: Visualizza Guida per l&#39;utente"

  "Menu: View global menu bindings"
  "Menu: Visualizza le associazioni di menu globali"

  "Menu: View global preferences"
  "Menu: Visualizza preferenze globali"

  "Move to other pane"
  "Spostarsi altro riquadro"

  "New"
  "NEW"

  "Open Directory..."
  "Apri cartella"

  "Open File..."
  "Apri file..."

  "Open Recent"
  "Apri recenti"

  "Paste"
  "Pasta"

  "Paste and Format"
  "Incolla formato"

  "Plugins"
  "Plugin"

  "Preferences"
  "Preferenze"

  "Profiling started"
  "Profiling non avviato."

  "Profiling stopped"
  "Profiling non fermato."

  "Quit"
  "Esci"

  "Redo"
  "Ripeti"

  "Reload"
  "Reload"

  "Restart tke"
  "Restart TKE"

  "Save All"
  "Salva tutto"

  "Save As..."
  "Salva con nome..."

  "Select All"
  "Seleziona Tutto"

  "Select all occurrences"
  "Seleziona tutte le occorrenze"

  "Select next occurrence"
  "Selezionare ricorrenza successiva"

  "Select previous occurrence"
  "Selezionare occorrenza precedente"

  "Selected"
  "Selezionato"

  "Set Syntax"
  "Impostare Sintassi"

  "Set Theme"
  "Set Theme"

  "Set user to global"
  "Impostare l&#39;utente al globale"

  "Show Console"
  "Mostra console"

  "Show Last Profiling Report"
  "Mostra ultimo rapporto Profiling"

  "Show Sidebar"
  "Mostra barra laterale"

  "Show Status Bar"
  "Mostra barra di stato"

  "Show Tab Bar"
  "Mostra barra delle schede@info:whatsthis"

  "Show*Profiling*"
  "Show * Profiling *"

  "Snippets"
  "Snippets"

  "Sort Tabs"
  "Ordinare Tabs"

  "Split view"
  "Vista divisa"

  "Start Profiling"
  "Inizia Profiling"

  "Stop Profiling"
  "Smettere di Profiling"

  "Tabs"
  "Tabelle"

  "Text"
  "Testo"

  "Theme Creator"
  "Theme Creator"

  "Tools"
  "Strumenti"

  "Uncomment"
  "Rimuovi commento"

  "Undo"
  "Undo"

  "Unindent"
  "Annulla Rientro"

  "Uninstall..."
  "Disinstalla"

  "Unlock"
  "Sblocca"

  "User Guide"
  "Guida utente"

  "View"
  "Visualizza"

  "View global"
  "Mostra globale"

  "Vim Mode"
  "Modalità di Vim"

}

# plugins.tcl
msgcat::mcmset it {

  "ERROR:  Plugin name is not valid (only alphanumeric and underscores are allowed)"
  "ERRORE: Plugin nome non è valido (solo caratteri alfanumerici e di sottolineatura sono ammessi)"

  "ERROR:  Unable to write plugin file"
  "ERRORE: Impossibile scrivere il file plug-in"

  "Enter plugin name"
  "Immettere il nome del plug-in."

  "Plugin %s installed"
  "Plugin% s installato"

  "Plugin %s uninstalled"
  "Plugin% s disinstallato"

  "Plugin Errors"
  "Errori di plug-in"

  "Syntax errors found in selected plugins"
  "Gli errori di sintassi trovati in estensioni selezionate"

}

# sidebar.tcl
msgcat::mcmset it {

  "Add Parent Directory"
  "indirizzario parent"

  "Close Directory Files"
  "Chiudi Directory Files"

  "Delete"
  "Elimina"

  "Delete directory?"
  "(elimina directory)"

  "Delete file?"
  "Elimina file"

  "Duplicate"
  "Duplica"

  "Make Current Working Directory"
  "Directory di lavoro corrente"

  "New Directory"
  "Nuova directory"

  "New File"
  "Nuovo file"

  "Open"
  "Aprire il regalo"

  "Refresh Directory Files"
  "Aggiorna Directory Files"

  "Remove Parent from Sidebar"
  "Rimuovere Parent da Sidebar"

  "Remove from Sidebar"
  "Rimuovi dal Sidebar"

  "Rename"
  "Rinomina"

}

# snippets.tcl
msgcat::mcmset it {

  "Snippet: %s: %s"
  "Snippet:% s:% s"

  "Snippet: *"
  "Snippets"

}

# syntax.tcl
msgcat::mcmset it {

  "Syntax error in %s.syntax file"
  "Errore di sintassi nel file di s.syntax%"

  "Syntax:  %s"
  "Sintassi:% s"

  "Theme:  %s"
  "Tema: %s"

}

# themer.tcl
msgcat::mcmset it {

  "Create"
  "Crea"

  "Create New Theme"
  "Crea nuovo tema..."

  "Create custom"
  "Personalizza"

  "ERROR:  Unable to read %s"
  "ERRORE: Impossibile leggere% s"

  "ERROR:  Unable to write %s"
  "ERRORE: Impossibile scrivere% s"

  "Edit theme"
  "Modifica tema"

  "Enter theme name"
  "Inserire il nome del tema"

  "Error:  Theme is not a supported theme"
  "Errore: Tema non è un tema supportato"

  "Import"
  "Importazione"

  "Import TextMate Theme"
  "Import TextMate Theme"

  "Name:"
  "Nome:"

  "OK"
  "Ok"

  "Reset"
  "invia"

  "Select theme"
  "Seleziona tema"

}

# tke.tcl
msgcat::mcmset it {

  "ERROR:  %s"
  "Errore: %s"

  "Edit theme?"
  "Modifica tema"

  "Import TextMate theme?"
  "Importare TextMate tema?"

}

# tkedat.tcl
msgcat::mcmset it {

  "Unable to open %s for reading"
  "Impossibile aprire il file%1 in lettura."

  "Unable to open %s for writing"
  "Non è possibile aprire%1 in scrittura"

}

# General
msgcat::mcmset it {

  "Cancel"
  "Cancella"

  "Close"
  "Chiudi"

  "Find:"
  "Trova:"

  "Replace:"
  "Sostituisci"

  "Save"
  "Salva"

  "Save As"
  "Salva con nome"

}

