# api.tcl
msgcat::mcmset ja {

  "Argument list to api::add_file was not an even key/value pair"
  "APIへの引数リスト:: ADD_FILEもキー/値のペアではなかった"

  "Argument list to api::add_file was not in the form 'filename [<option> <value>]*'"
  "APIへの引数リスト:: ADD_FILE、フォーム &#39;ファイル名ではありませんでした[ <option><value> ] * &#39;"

  "get_home_directory can only be called within plugin code"
  "get_home_directoryのみプラグインのコード内で呼び出すことができます"

}

# bgproc.tcl
msgcat::mcmset ja {

  "Unable to run system command (%s)"
  "システム·コマンド（％s）を実行することができません"

}

# bindings.tcl
msgcat::mcmset ja {

  "Menu Bindings: Edit user menu bindings"
  "メニューバインディング：編集ユーザーメニューバインディング"

  "Menu Bindings: Reload menu bindings"
  "メニューバインディング：リロードメニューバインディング"

  "Menu Bindings: Use default menu bindings"
  "メニューバインディング：デフォルトのメニューバインディングを使用して、"

  "Menu Bindings: View global menu bindings"
  "メニューバインディング：グローバルメニューバインディングを見る"

}

# gui.tcl
msgcat::mcmset ja {

  "Close All Tabs"
  "すべてのタブを閉じる"

  "Close Other Tab(s)"
  "閉じるその他のタブ（S）"

  "Close Other*"
  "その他の*を閉じ"

  "Close Tab"
  "タブを閉じる"

  "Copyright %d"
  "著作％dの"

  "Delete tab?"
  "タブを削除しますか？"

  "Developer:"
  "デベロッパー"

  "Email:"
  "メール"

  "File attribute (%s) does not exist"
  "ファイル属性（％s）は存在しません"

  "File index is out of range"
  "ファイルインデックスが範囲外である"

  "Find:"
  "Find"

  "Global"
  "グローバル"

  "Line: %d, Column: %d"
  "ライン：％dが、カラム：％dの"

  "Locked"
  "ロックする"

  "Move to Other Pane"
  "他のペインに移動します"

  "Move*"
  "ムーブ"

  "Reload file?"
  "ファイルをリロード？"

  "Replace:"
  "置換："

  "Save request"
  "リクエストを保存"

  "Unable to find current file (pane: %s, tab: %s)"
  "（：％sは、タブ：％sのペイン）に、現在のファイルが見つかりません"

  "Untitled"
  "無題"

  "Version:"
  "Version:"

}

# markers.tcl
msgcat::mcmset ja {

  "Marker name:"
  "マーカー名："

}

# menus.tcl
msgcat::mcmset ja {

  "                                  Profiling Report Sorted By (%s)"
  "ソート順プロファイリングレポート（％s）が"

  "About Tke"
  "TKEについて"

  "About tke"
  "TKEについて"

  "Align cursors"
  "カーソルを合わせ"

  "All"
  "ALL"

  "Append next occurrence"
  "次のオカレンスを追加"

  "Clear All"
  "すべてクリア"

  "Close All"
  "すべて閉じる"

  "Comment"
  "コメント"

  "Copy"
  "コピー"

  "Create new..."
  "新しい作成..."

  "Create..."
  "する"

  "Cut"
  "CUT"

  "Edit"
  "編集"

  "Edit..."
  "編集"

  "FOOBAR"
  "Foobar"

  "File"
  "ファイル"

  "Find"
  "Find"

  "Find and Replace"
  "検索と置換"

  "Find in files"
  "ファイルから検索"

  "Find matching pair"
  "一致するペアを見つける"

  "Format Text"
  "テキストをフォーマットする"

  "Help"
  "ヘルプ"

  "Import TextMate theme..."
  "TextMateのテーマをインポート..."

  "Indent"
  "インデント"

  "Insert enumeration"
  "列挙型を挿入"

  "Install..."
  "インストール"

  "Launcher"
  "ランチャー"

  "Lock"
  "固定"

  "Menu: About tke"
  "メニュー：TKEについて"

  "Menu: Align cursors"
  "メニュー：カーソルを合わせ"

  "Menu: Append next occurrence"
  "メニュー：次のオカレンスを追加"

  "Menu: Close all tabs"
  "すべてのタブを閉じる"

  "Menu: Close current tab"
  "メニュー：現在のタブを閉じる"

  "Menu: Comment selected text"
  "メニュー：選択したテキストをコメント"

  "Menu: Copy selected text"
  "メニュー：コピー選択したテキスト"

  "Menu: Create new plugin"
  "メニュー：新しいプラグインを作成"

  "Menu: Create new theme"
  "メニュー：新しいテーマを作成する"

  "Menu: Cut selected text"
  "メニュー：カット選択したテキスト"

  "Menu: Disable Vim mode"
  "メニュー：Vimのモードを無効にします"

  "Menu: Edit Tke theme"
  "メニュー：編集TKEテーマ"

  "Menu: Enable Vim mode"
  "メニュー：Vimのモードを有効に"

  "Menu: Find"
  "メニュー：見つける"

  "Menu: Find and Replace"
  "検索と置換"

  "Menu: Find in files"
  "メニュー：ファイルから検索"

  "Menu: Find matching character pair"
  "メニュー：一致する文字のペアを探す"

  "Menu: Find next occurrence"
  "メニュー：次の出現箇所を検索"

  "Menu: Find previous occurrence"
  "メニュー：前の発生を検索"

  "Menu: Hide console"
  "メニュー：コンソールを非表示に"

  "Menu: Hide sidebar"
  "メニュー：サイドバーを隠す"

  "Menu: Hide status bar"
  "メニュー：非表示のステータスバー"

  "Menu: Import TextMate theme"
  "メニュー：輸入TextMateのテーマ"

  "Menu: Indent selected text"
  "メニュー：選択したテキストをインデント"

  "Menu: Insert enumeration"
  "メニュー：列挙型を挿入します"

  "Menu: Install plugin"
  "メニュー：インストールプラグイン"

  "Menu: Lock file"
  "メニュー：ロックファイル"

  "Menu: New file"
  "メニュー：新ファイル"

  "Menu: Open directory"
  "メニュー：オープンディレクトリ"

  "Menu: Open file"
  "メニュー：ファイルを開く"

  "Menu: Paste and format text from clipboard"
  "メニュー：クリップボードからの貼り付けやテキストの書式設定"

  "Menu: Paste text from clipboard"
  "クリップボードから貼り付け"

  "Menu: Quit application"
  "メニュー：アプリケーションを終了し"

  "Menu: Redo"
  "メニュー：やり直し"

  "Menu: Reload all plugins"
  "メニュー：すべてのプラグインを再ロード"

  "Menu: Restart tke"
  "メニュー：TKEを再起動します"

  "Menu: Save all files"
  "メニュー：すべてのファイルを保存"

  "Menu: Save file"
  "メニュー：ファイルを保存します"

  "Menu: Save file as"
  "メニュー：ファイルとして保存"

  "Menu: Select all occurrences"
  "メニュー：すべてのオカレンスを選択"

  "Menu: Show console"
  "メニュー：表示するコンソール"

  "Menu: Show last profiling report"
  "メニュー：ショー最後のプロファイリングレポート"

  "Menu: Show sidebar"
  "メニュー：表示するサイドバー"

  "Menu: Show status bar"
  "メニュー：表示するステータスバー"

  "Menu: Start profiling"
  "メニュー：スタートプロファイリング"

  "Menu: Stop profiling"
  "メニュー：ストッププロファイリング"

  "Menu: Uncomment selected text"
  "メニュー：コメント解除選択したテキスト"

  "Menu: Undo"
  "メニュー：元に戻す"

  "Menu: Unindent selected text"
  "メニュー：インデント解除選択したテキスト"

  "Menu: Uninstall plugin"
  "メニュー：アンプラグ"

  "Menu: Unlock file"
  "メニュー：ロック解除ファイル"

  "New"
  "新しい"

  "Open Directory..."
  "ディレクトリを開きます。..."

  "Open File..."
  "ファイルを開く"

  "Open Recent"
  "最近のオープン"

  "Paste"
  "貼り付け"

  "Paste and Format"
  "ペーストとフォーマット"

  "Plugins"
  "プラグイン"

  "Preferences..."
  "設定..."

  "Profiling started"
  "プロファイリングが開始されました"

  "Profiling stopped"
  "プロファイリングが停止"

  "Quit"
  "やめる"

  "Redo"
  "やり直す"

  "Reload"
  "再読み込み"

  "Restart tke"
  "TKEを再起動します"

  "Save All"
  "すべて保存"

  "Save As..."
  "名前を付けて保存..."

  "Select all occurrences"
  "すべてのオカレンスを選択"

  "Select next occurrence"
  "次のオカレンスを選択してください"

  "Select previous occurrence"
  "以前の発生を選択"

  "Selected"
  "選択"

  "Set Syntax"
  "構文を設定"

  "Show Last Profiling Report"
  "最後のプロファイリングレポートを表示"

  "Show*Profiling*"
  "表示*プロファイリング*"

  "Start Profiling"
  "プロファイリング開始"

  "Stop Profiling"
  "プロファイリングを停止"

  "Text"
  "Text"

  "Theme Creator"
  "テーマ作成者"

  "Tools"
  "道具"

  "Uncomment"
  "コメントを解除"

  "Undo"
  "アンドゥ"

  "Unindent"
  "インデント解除"

  "Uninstall..."
  "アンインストール"

  "Unlock"
  "アンロック"

  "View"
  "表示"

  "View Console"
  "ビューコンソール"

  "View Sidebar"
  "ビューサイドバー"

  "View Status Bar"
  "ステータス バー"

  "Vim Mode"
  "Vimのモード"

}

# plugins.tcl
msgcat::mcmset ja {

  "ERROR:  Plugin name is not valid (only alphanumeric and underscores are allowed)"
  "ERROR：プラグイン名が有効ではありません（英数字とアンダースコアは許可されています）"

  "ERROR:  Unable to write plugin file"
  "ERROR：プラグインファイルを書き込むことができません"

  "Enter plugin name"
  "プラグイン名を入力してください"

  "Plugin %s installed"
  "プラグイン％sのインストール"

  "Plugin %s uninstalled"
  "プラグイン％sをアンインストール"

  "Plugin Errors"
  "プラグインエラー"

  "Syntax errors found in selected plugins"
  "構文エラーは、選択したプラグインで発見"

}

# preferences.tcl
msgcat::mcmset ja {

  "Preferences: Edit user preferences"
  "初期設定：編集ユーザの嗜好"

  "Preferences: Reload preferences"
  "設定：リロード嗜好"

  "Preferences: Use default preferences"
  "環境設定：デフォルトの設定を使用し"

  "Preferences: View global preferences"
  "環境設定：グローバルプリファレンスを見る"

}

# sidebar.tcl
msgcat::mcmset ja {

  "Add Parent Directory"
  "親ディレクトリ"

  "Close Directory Files"
  "閉じるディレクトリファイル"

  "Delete"
  "削除"

  "Delete directory?"
  "ディレクトリを削除しますか？"

  "Delete file?"
  "ファイルを削除しますか？"

  "Duplicate"
  "複製"

  "Make Current Working Directory"
  "現在の作業ディレクトリを作る"

  "New Directory"
  "新しいディレクトリ"

  "New File"
  "新規ファイル"

  "Open"
  "オープン"

  "Refresh Directory Files"
  "リフレッシュディレクトリファイル"

  "Remove Parent from Sidebar"
  "サイドバーから親を削除する"

  "Remove from Sidebar"
  "サイドバーから削除"

  "Rename"
  "名前の変更"

}

# snippets.tcl
msgcat::mcmset ja {

  "Snippet: %s: %s"
  "スニペットた：％s：％sの"

  "Snippet: *"
  "スニペット：*"

  "Snippets: Add snippet"
  "スニペット：スニペットを追加"

  "Snippets: Reload all snippets"
  "スニペット：すべてのスニペットをリロード"

}

# syntax.tcl
msgcat::mcmset ja {

  "Syntax error in %s.syntax file"
  "パーセントs.syntaxファイルの構文エラー"

  "Syntax:  %s"
  "構文：％sは"

  "Theme:  %s"
  "テーマ：％sは"

}

# themer.tcl
msgcat::mcmset ja {

  "Create"
  "作る"

  "Create New Theme"
  "新しいテーマを作成する"

  "Create custom"
  "カスタム作成"

  "ERROR:  Unable to read %s"
  "ERROR：％sのを読み取ることができません"

  "ERROR:  Unable to write %s"
  "ERROR：％sを書き込むことができません"

  "Edit theme"
  "テーマを編集"

  "Enter theme name"
  "テーマ名を入力してください"

  "Error:  Theme is not a supported theme"
  "エラー：テーマは、サポートされているテーマではない"

  "Import"
  "輸入"

  "Import TextMate Theme"
  "TextMateのテーマをインポート"

  "Name:"
  "名"

  "OK"
  "Okay"

  "Reset"
  "リセット"

  "Select theme"
  "テーマの選択"

}

# tke.tcl
msgcat::mcmset ja {

  "ERROR:  %s"
  "ERROR：％sは"

  "Edit theme?"
  "テーマを編集？"

  "Import TextMate theme?"
  "TextMateのテーマをインポート？"

}

# tkedat.tcl
msgcat::mcmset ja {

  "Unable to open %s for reading"
  "読み取るための％sを開けません"

  "Unable to open %s for writing"
  "書き込み用の％sを開けません"

}

# General
msgcat::mcmset ja {

  "Cancel"
  "キャンセル"

  "Close"
  "閉じる"

  "Save"
  "保存"

  "Save As"
  "名前を付けて保存"

}

