# api.tcl
msgcat::mcmset ja {

  "Argument list to api::add_file was not an even key/value pair"
  "APIへの引数リスト:: ADD_FILEもキー/値のペアではなかった"

  "Plugin"
  "プラグイン"

}

# bgproc.tcl
msgcat::mcmset ja {

  "Unable to run system command"
  "システム コマンドを実行することができません。"

}

# diff.tcl
msgcat::mcmset ja {

  "    End: "
  "終了日"

  "    Start: "
  "開始日"

  "Enter difference command"
  "Difference コマンドを入力してください。"

  "Enter starting file"
  "開始ファイルを入力してください。"

  "Update"
  "の編集"

}

# embed_tke.tcl
msgcat::mcmset ja {

  "Find:"
  "Find"

  "Replace:"
  "置換："

}

# gui.tcl
msgcat::mcmset ja {

  "Case sensitivity"
  "大文字と小文字を区別する"

  "Close All Tabs"
  "すべてのタブを閉じる"

  "Close Other Tabs"
  "他のタブを閉じる"

  "Close Other*"
  "その他の*を閉じ"

  "Close Tab"
  "タブを閉じる"

  "Column"
  "列"

  "Copyright"
  "著作権"

  "Delete tab?"
  "タブを削除しますか？"

  "Developer"
  "デベロッパー"

  "Email"
  "Eメール"

  "Error"
  "エラー"

  "Favorited"
  "お気に入り"

  "File already exists.  Use '!' to force an overwrite"
  "ファイルは既に存在します。 使用 '!' 強制的に上書きする"

  "File attribute does not exist"
  "ファイル属性は存在しません"

  "File index is out of range"
  "ファイルインデックスが範囲外である"

  "Image displayed in fill-in forms which closes the form UI.  Used in forms such as search, search/replace, and find in files."
  "フォームUIを閉じフィルインの形で表示された画像。検索などの形で使用され、検索/置換、およびファイルで見つけます。"

  "Image used in tab menus to indicate that the file is associated with a difference view."
  "イメージファイルは、差分ビューに関連付けられていることを示すために、タブメニューで使用。"

  "Image used in tab menus to indicate that the file is locked."
  "イメージファイルがロックされていることを示すためのタブメニューで使用。"

  "Image used in tab menus to indicate that the file is readonly."
  "イメージファイルが読み取り専用であることを示すために、タブメニューで使用。"

  "Image used in tab to indicate that the tab contains a difference view."
  "イメージタブが違いビューが含まれていることを示すためにタブで使用されます。"

  "Image used in tab to indicate that the tab's file is readonly."
  "タブで使用される画像は、タブのファイルが読み取り専用であることを示します。"

  "Image used in tab to indicate that the tab’s file is locked."
  "画像は、タブのファイルがロックされていることを示すためにタブに使用されます。"

  "Image used in tab which, when clicked, closes the tab."
  "画像は、クリックすると、タブを閉じたタブに使用されます。"

  "License"
  "ナンバープレート"

  "Line"
  "直線"

  "Locked"
  "ロックする"

  "Move"
  "引き延ばす"

  "Must be in multicursor mode to insert numbers"
  "数字を挿入する multicursor モードでなければなりません"

  "No write permissions.  Use '!' to force write."
  "書き込みのアクセス許可はありません。 使用 '!' 書き込みを強制します。"

  "Release Type"
  "リリースの種類"

  "Reload file?"
  "ファイルをリロード？"

  "Replace"
  "置換"

  "Save request"
  "リクエストを保存"

  "Show in Sidebar"
  "サイドバーで表示"

  "Starting number:"
  "開始番号:"

  "Tcl/Tk Version"
  "Tcl/Tk バージョン"

  "Total Characters"
  "合計文字"

  "Total Lines"
  "集計行"

  "Unable to find current file"
  "現在のファイルを見つけることができません。"

  "Unable to successfully parse number string"
  "番号の文字列を正しく解析することができません。"

  "Unable to write file"
  "ファイルを書き込めません。"

  "Version"
  "バージョン"

  "tab"
  "タブ"

}

# markers.tcl
msgcat::mcmset ja {

  "Marker name:"
  "マーカー名："

}

# menus.tcl
msgcat::mcmset ja {

  "About TKE"
  "TKEについて"

  "Align Cursors"
  "??????????"

  "Append Next Occurrence"
  "?????????????"

  "Auto-Indent"
  "自動インデント"

  "Check for Update"
  "アップデートの確認"

  "Clear All"
  "すべてクリア"

  "Close All"
  "すべて閉じる"

  "Close Current"
  "??????"

  "Copy"
  "コピー"

  "Create at Current Line"
  "???????????"

  "Create..."
  "する"

  "Cut"
  "CUT"

  "Edit"
  "編集"

  "Edit Language"
  "言語を編集します。"

  "Edit Menu Edit user snippets"
  "メニュー編集ユーザー スニペットを編集します。"

  "Edit Menu: Copy text"
  "[編集] メニュー: テキストのコピー"

  "Edit Menu: Cut text"
  "[編集] メニュー: テキストを切り取る"

  "Edit Menu: Edit language snippets"
  "[編集] メニュー: 編集言語のスニペット"

  "Edit Menu: Edit session current language preferences"
  "[編集] メニュー: の編集のセッションは、現在の言語の設定"

  "Edit Menu: Edit session global preferences"
  "[編集] メニュー: 編集セッションのグローバル設定"

  "Edit Menu: Edit user current language preferences"
  "[編集] メニュー: 編集ユーザーの現在の言語設定"

  "Edit Menu: Edit user global preferences"
  "編集メニュー: ユーザーのグローバル設定を編集します。"

  "Edit Menu: Edit user menu bindings"
  "[編集] メニュー: 編集ユーザー メニューのバインディング"

  "Edit Menu: Format all text"
  "[編集] メニュー: すべてのテキストの書式設定します。"

  "Edit Menu: Format selected text"
  "[編集] メニュー: 選択したテキストの書式設定します。"

  "Edit Menu: Insert from clipboard"
  "[編集] メニュー: クリップボードから挿入します。"

  "Edit Menu: Insert snippet"
  "[編集] メニュー: 挿入スニペット"

  "Edit Menu: Paste and format text from clipboard"
  "[編集] メニュー: テキスト クリップボードからペーストおよび書式設定"

  "Edit Menu: Paste text from clipboard"
  "[編集] メニュー: クリップボードからテキストを貼り付ける"

  "Edit Menu: Redo"
  "[編集] メニュー: やり直し"

  "Edit Menu: Reload snippets"
  "[編集] メニュー: リロード スニペット"

  "Edit Menu: Select all text"
  "[編集] メニュー: すべてのテキストを選択します。"

  "Edit Menu: Set indent mode to IND"
  "[編集] メニュー: IND にインデント モードを設定します。"

  "Edit Menu: Set indent mode to IND+"
  "[編集] メニュー: IND + にインデント モードを設定します。"

  "Edit Menu: Set indent mode to OFF"
  "[編集] メニュー: インデント モードを OFF に設定します。"

  "Edit Menu: Set user bindings to global bindings"
  "[編集] メニュー: はグローバル バインドするユーザー バインドを設定します。"

  "Edit Menu: Set user preferences to global preferences"
  "グローバル設定に設定ユーザーを [編集] メニュー。"

  "Edit Menu: Undo"
  "[編集] メニュー: 元に戻す"

  "Edit Menu: View base preferences file"
  "[編集] メニュー: 表示基本設定ファイル"

  "Edit Menu: View global menu bindings"
  "[編集] メニュー: グローバル メニューのショートカットを表示します。"

  "Edit Session - Global"
  "??????? - ?????"

  "Edit Session - Language"
  "??????????-"

  "Edit User"
  "ユーザーを編集"

  "Edit User - Global"
  "????? ??????????"

  "Edit User - Language"
  "??????????????"

  "File"
  "ファイル"

  "File Menu: Close all tabs"
  "[ファイル] メニュー: すべてのタブを閉じる"

  "File Menu: Close current tab"
  "[ファイル] メニュー: 現在のタブを閉じる"

  "File Menu: Favorite file"
  "[ファイル] メニュー: お気に入りファイル"

  "File Menu: Lock file"
  "[ファイル] メニュー: ロック ファイル"

  "File Menu: New file"
  "[ファイル] メニュー: 新しいファイル"

  "File Menu: Open Favorite"
  "[ファイル] メニュー: 開いているお気に入り"

  "File Menu: Open Recent"
  "[ファイル] メニュー: 最近開いた画像ドキュメント"

  "File Menu: Open directory"
  "[ファイル] メニュー: オープン ディレクトリ"

  "File Menu: Open file"
  "ファイルを開く [ファイル] メニュー:"

  "File Menu: Quit application"
  "[ファイル] メニュー: アプリケーションを終了します。"

  "File Menu: Save all files"
  "すべてのファイルを保存ファイル] メニュー。"

  "File Menu: Save file"
  "[ファイル] メニュー: ファイルを保存します。"

  "File Menu: Save file as"
  "ファイルを保存するファイル] メニュー。"

  "File Menu: Show file difference"
  "[ファイル] メニュー: ファイルの相違点を表示します。"

  "File Menu: Unfavorite file"
  "[ファイル] メニュー: Unfavorite ファイル"

  "File Menu: Unlock file"
  "[ファイル] メニュー: ファイルのロックを解除します。"

  "Find In Files"
  "????????????"

  "Find Matching Pair"
  "?????????????"

  "Find Menu: Append next occurrence"
  "検索メニュー: は、次の出現箇所を追加します。"

  "Find Menu: Create marker at current line"
  "検索メニュー: は、現在の行のマーカーを作成します。"

  "Find Menu: Find"
  "メニューを見つける: 検索"

  "Find Menu: Find and Replace"
  "検索メニュー: 検索し、置換"

  "Find Menu: Find in files"
  "ファイル内の検索] メニュー: 検索"

  "Find Menu: Find matching character pair"
  "文字のペアに一致する検索メニュー: 検索"

  "Find Menu: Find next occurrence"
  "次を検索する検索] メニュー。"

  "Find Menu: Find previous occurrence"
  "検索メニュー: 前の出現箇所を見つける"

  "Find Menu: Goto next difference"
  "検索メニュー: 後藤次の相違点"

  "Find Menu: Goto previous difference"
  "検索メニュー: 後藤前の相違点"

  "Find Menu: Jump backward"
  "検索メニュー: 移動後方"

  "Find Menu: Jump forward"
  "前方検索メニュー: ジャンプ"

  "Find Menu: Remove all markers"
  "検索メニュー: すべてのマーカーを削除します。"

  "Find Menu: Remove marker from current line"
  "検索メニュー: は、現在の行からマーカーを削除します。"

  "Find Menu: Select all occurrences"
  "検索メニュー: 単語をすべて選択します。"

  "Find Menu: Show selected line change"
  "検索メニュー: 選択した表示行変更"

  "Find and Replace"
  "検索と置換"

  "Format Text"
  "テキストをフォーマットする"

  "From Clipboard"
  "クリップボードから"

  "Goto Last Tab"
  "後藤最後のタブ"

  "Goto Next Tab"
  "後藤次のタブ"

  "Goto Other Pane"
  "後藤他のペイン"

  "Goto Previous Tab"
  "後藤前のタブ"

  "Help"
  "ヘルプ"

  "Help Menu: About TKE"
  "[ヘルプ] メニュー: TKE について"

  "Help Menu: Check for update"
  "更新プログラムのチェックを [ヘルプ] メニュー:"

  "Help Menu: Send bug report"
  "[ヘルプ] メニュー: バグ報告を送る"

  "Help Menu: Send feedback"
  "[ヘルプ] メニュー: フィードバックの送信"

  "Help Menu: View user guide"
  "[ヘルプ] メニュー: ビュー ユーザー ガイド"

  "Hide Console"
  "コンソールを隠す"

  "Hide Line Numbers"
  "行番号を非表示します。"

  "Hide Meta Characters"
  "????????????"

  "Hide Sidebar"
  "隠すサイドバー"

  "Hide Status Bar"
  "隠すステータスバー"

  "Hide Tab Bar"
  "タブバーを非表示"

  "Indent"
  "インデント"

  "Indent Mode"
  "インデント モード"

  "Indent Off"
  "オフにインデントを設定します。"

  "Insert Enumeration"
  "??????????"

  "Insert Text"
  "テキストの挿入"

  "Install..."
  "インストール"

  "Jump Backward"
  "??????????"

  "Jump Forward"
  "??????????"

  "Launcher"
  "ランチャー"

  "Lock"
  "固定"

  "Markers"
  "マーカー"

  "Menu Bindings"
  "メニューバインディング"

  "Menus: About TKE"
  "TKE のメニュー。"

  "Merge Panes"
  "????????????"

  "Next Difference"
  "????"

  "Open Directory..."
  "ディレクトリを開きます。..."

  "Open Favorite"
  "オープン好き"

  "Open File..."
  "ファイルを開く"

  "Open Recent"
  "最近のオープン"

  "Paste"
  "貼り付け"

  "Paste and Format"
  "ペーストとフォーマット"

  "Plugins"
  "プラグイン"

  "Plugins Menu: Create new plugin"
  "プラグイン メニュー: 作成新しいプラグイン"

  "Plugins Menu: Install plugin"
  "プラグイン メニュー: インストールのプラグイン"

  "Plugins Menu: Reload all plugins"
  "プラグイン メニュー: は、すべてのプラグインを再読み込み"

  "Plugins Menu: Uninstall plugin"
  "プラグイン メニュー: プラグインをアンインストールします。"

  "Preferences"
  "選好"

  "Previous Difference"
  "?????"

  "Profiling Report Sorted By"
  "プロファイリング レポート順"

  "Profiling started"
  "プロファイリングが開始されました"

  "Profiling stopped"
  "プロファイリングが停止"

  "Quit"
  "やめる"

  "Redo"
  "やり直す"

  "Reload"
  "再読み込み"

  "Remove All Markers"
  "???????????????"

  "Remove From Current Line"
  "????????????"

  "Replace Line With Script"
  "?????????????"

  "Reset User to Base"
  "ユーザー ベースにリセットします。"

  "Restart TKE"
  "TKE ????????"

  "Save All"
  "すべて保存"

  "Save As..."
  "名前を付けて保存..."

  "Save Current"
  "?????????"

  "Select All"
  "すべて選択"

  "Select All Occurrences"
  "????????????"

  "Select Next Occurrence"
  "?????????????"

  "Select Previous Occurrence"
  "?????????????"

  "Selected"
  "選択"

  "Send Bug Report"
  "バグ報告を送る"

  "Send Feedback"
  "﻿フィードバックを送る"

  "Sessions"
  "?????"

  "Sessions Menu: Close current session"
  "セッション ・ メニュー: 現在のセッションを閉じる"

  "Sessions Menu: Delete session"
  "セッション ・ メニュー: 削除セッション"

  "Sessions Menu: Open session"
  "セッション ・ メニュー: オープン セッション"

  "Sessions Menu: Save current session"
  "セッション ・ メニュー: 現在のセッションを保存します。"

  "Sessions Menu: Save sessions as"
  "セッション ・ メニュー: としてセッションを保存します。"

  "Sessions Menu: Switch to session"
  "セッションにセッション ・ メニュー: スイッチ"

  "Set Syntax"
  "構文を設定"

  "Set Theme"
  "設定テーマ"

  "Set User to Global"
  "グローバルに設定されているユーザー"

  "Show Console"
  "コンソールの表示"

  "Show Diagnostic Logfile"
  "診断ログ ファイルを表示します。"

  "Show File Difference"
  "ファイルの相違点を表示します。"

  "Show Last Profiling Report"
  "最後のプロファイリングレポートを表示"

  "Show Line Numbers"
  "行番号を表示します。"

  "Show Meta Characters"
  "???????"

  "Show Selected Line Change"
  "???????????????"

  "Show Sidebar"
  "表示するサイドバー"

  "Show Status Bar"
  "表示ステータスバー"

  "Show Tab Bar"
  "表示タブバー"

  "Smart Indent"
  "スマート インデント"

  "Snippet"
  "スニペット"

  "Snippets"
  "スニペット"

  "Sort Tabs"
  "並べタブ"

  "Start Profiling"
  "プロファイリング開始"

  "Stop Profiling"
  "プロファイリングを停止"

  "Switch To"
  "?????? :"

  "Tabs"
  "タブ"

  "Text"
  "Text"

  "Text Menu: Align cursors"
  "テキスト メニュー: カーソルの位置合わせ"

  "Text Menu: Indent selected text"
  "テキスト メニュー: 選択したテキストにインデントを設定します。"

  "Text Menu: Insert enumeration"
  "テキスト メニュー: 挿入列挙"

  "Text Menu: Replace line with script"
  "テキスト メニュー: スクリプト行を置き換えます"

  "Text Menu: Toggle comment"
  "テキスト メニュー: コメント切り替え"

  "Text Menu: Unindent selected text"
  "テキスト メニュー: 選択したテキストのインデントを解除します。"

  "Toggle Comment"
  "????????"

  "Tools"
  "道具"

  "Tools Menu: Disable Vim mode"
  "[ツール] メニュー: Vim モードを無効にします。"

  "Tools Menu: Enable Vim mode"
  "[ツール] メニュー: Vim モードを有効にします。"

  "Tools Menu: Restart TKE"
  "[ツール] メニュー: 再起動 TKE"

  "Tools Menu: Run theme editor"
  "[ツール]メニュー：実行テーマエディタ"

  "Tools Menu: Show diagnostic logfile"
  "[ツール] メニュー: 診断ログ ファイルを表示します。"

  "Tools Menu: Show last profiling report"
  "[ツール] メニュー: 最後のプロファイリング レポートを表示します。"

  "Tools Menu: Start profiling"
  "[ツール] メニュー: プロファイリングを開始します。"

  "Tools Menu: Stop profiling"
  "[ツール] メニュー: プロファイリングを停止します。"

  "Undo"
  "アンドゥ"

  "Unindent"
  "インデント解除"

  "Uninstall..."
  "アンインストール"

  "Unlock"
  "アンロック"

  "User Guide"
  "マニュアル"

  "View"
  "表示"

  "View Base"
  "ビュー ベース"

  "View Global"
  "グローバル ビュー"

  "View Menu: Goto last tab"
  "[表示] メニュー: 後藤最後のタブ"

  "View Menu: Goto next tab"
  "[表示] メニュー: 後藤次のタブ"

  "View Menu: Goto other pane"
  "[表示] メニュー: 後藤他ペイン"

  "View Menu: Goto previous tab"
  "[表示] メニュー: 後藤前のタブ"

  "View Menu: Hide console"
  "[表示] メニュー: 非表示コンソール"

  "View Menu: Hide line numbers"
  "[表示] メニュー: 行番号を非表示します。"

  "View Menu: Hide meta characters"
  "[表示] メニュー: メタ文字を非表示します。"

  "View Menu: Hide sidebar"
  "[表示] メニュー: 非表示サイドバー"

  "View Menu: Hide status bar"
  "[表示] メニュー: ステータス バーの非表示"

  "View Menu: Hide tab bar"
  "[表示] メニュー: タブ バーの非表示"

  "View Menu: Merge panes"
  "[表示] メニュー: マージ ウィンドウ"

  "View Menu: Move to other pane"
  "他のウィンドウに移動する [表示] メニュー。"

  "View Menu: Show console"
  "[表示] メニュー: 表示コンソール"

  "View Menu: Show line numbers"
  "[表示] メニュー: 行番号を表示します。"

  "View Menu: Show meta characters"
  "[表示] メニュー: メタ文字を表示します。"

  "View Menu: Show sidebar"
  "[表示] メニュー: ショー ・ サイドバー"

  "View Menu: Show status bar"
  "[表示] メニュー: ステータス バーを表示します。"

  "View Menu: Show tab bar"
  "[表示] メニュー: タブ バーを表示"

  "View Menu: Sort tabs"
  "[表示] メニュー: 並び替えタブ"

  "View Menu: Toggle split view mode"
  "[表示] メニュー: トグル分割表示モード"

  "Vim Mode"
  "Vimのモード"

}

# plugins.tcl
msgcat::mcmset ja {

  "ERROR"
  "エラー"

  "ERROR:  Plugin name already exists"
  "エラー：プラグイン名がすでに存在"

  "ERROR:  Plugin name is not valid (only alphanumeric and underscores are allowed)"
  "ERROR：プラグイン名が有効ではありません（英数字とアンダースコアは許可されています）"

  "ERROR:  Unable to create plugin directory"
  "エラー：プラグインディレクトリを作成できません"

  "ERROR:  Unable to write plugin files"
  "エラー：プラグインファイルを書き込むことができません"

  "Enter plugin name"
  "プラグイン名を入力してください"

  "Plugin Errors"
  "プラグインエラー"

  "Plugin installed"
  "プラグインをインストール"

  "Plugin uninstalled"
  "プラグインのアンインストール"

  "Plugins successfully reloaded"
  "プラグインが正常にリロード"

  "Syntax errors found in selected plugins"
  "構文エラーは、選択したプラグインで発見"

}

# search.tcl
msgcat::mcmset ja {

  "No files found in specified directories"
  "ファイルの指定されたディレクトリが見つかりません"

  "No search results found"
  "検索結果は見つかりませんでした。"

  "Search wrapped to beginning of file"
  "ファイルの先頭に折り返し検索"

  "Search wrapped to end of file"
  "ファイルの最後に折り返し検索"

  "substitutions done"
  "置換実行"

}

# sidebar.tcl
msgcat::mcmset ja {

  "Add Parent Directory"
  "親ディレクトリ"

  "Close Directory Files"
  "閉じるディレクトリファイル"

  "Copy Pathname"
  "???????????"

  "Delete directories?"
  "ディレクトリを削除しますか。"

  "Delete directory?"
  "ディレクトリを削除しますか？"

  "Delete file?"
  "ファイルを削除しますか？"

  "Delete files?"
  "ファイルを削除しますか。"

  "Directory Name:"
  "ディレクトリ名:"

  "Duplicate"
  "複製"

  "File Name:"
  "ファイル名"

  "Folder Name:"
  "?????"

  "Image displayed in sidebar to indicate that a file is currently opened in an editing buffer."
  "サイドバーに表示される画像はファイルが現在編集バッファで開かれることを示します。"

  "Make Current Working Directory"
  "現在の作業ディレクトリを作る"

  "New Directory"
  "新しいディレクトリ"

  "Open Directory Files"
  "オープンディレクトリのファイル"

  "Refresh Directory Files"
  "リフレッシュディレクトリファイル"

  "Remove Parent from Sidebar"
  "サイドバーから親を削除する"

  "Remove from Sidebar"
  "サイドバーから削除"

  "Rename"
  "名前の変更"

  "Show Difference"
  "違いを示す"

}

# snippets.tcl
msgcat::mcmset ja {

  "Snippet: *"
  "スニペット：*"

}

# syntax.tcl
msgcat::mcmset ja {

  "Syntax"
  "統語論"

  "Syntax error in syntax file"
  "構文ファイルの構文エラー"

}

# theme.tcl
msgcat::mcmset ja {

  "Background (trough) color used in the sidebar scrollbar."
  "サイドバーのスクロールバーで使用される背景（トラフ）色。"

  "Background (trough) color used in the text scrollbars."
  "テキストスクロールバーで使用される背景（トラフ）色。"

  "Background color for all sidebar items that are not selected."
  "選択されていないすべてのサイドバーの項目の背景色です。"

  "Background color for all sidebar items that are selected."
  "選択されているすべてのサイドバーの項目の背景色です。"

  "Background color in difference viewer that shows added lines."
  "追加された行を示し、差分ビューアで背景色です。"

  "Background color in difference viewer that shows deleted lines."
  "削除された行を示し、差分ビューアで背景色です。"

  "Background color of insertion cursor."
  "挿入カーソルの背景色です。"

  "Background color of the editing buffer."
  "編集バッファの背景色です。"

  "Background color to display when a button-like ttk widget is pressed."
  "ボタンのようなTTKウィジェットが押されたときに表示する背景色です。"

  "Background color to use for selected text."
  "選択したテキストに使用する背景色です。"

  "Background color used for all other tabs that are not the current/active tab in the tabbar."
  "タブバーで現在/アクティブなタブでない他のすべてのタブに使用する背景色です。"

  "Background color used for the current/active menu item."
  "現在の/アクティブなメニュー項目に使用する背景色です。"

  "Background color used for the current/active tab in the tabbar."
  "タブバーで現在/アクティブなタブに使用する背景色です。"

  "Background color used in highlighted text."
  "ハイライトされたテキストに使用される背景色。"

  "Background color used in menus."
  "メニューで使用背景色です。"

  "Background color used in the tabbar area."
  "タブバーのエリアで使用される背景色。"

  "Color of border drawn around active editing buffer."
  "アクティブな編集バッファ周りに描か境界線の色です。"

  "Color of ttk entry widget text border when the entry has keyboard focus."
  "エントリにキーボードフォーカスがTTKエントリウィジェットのテキストの境界線の色です。"

  "Color used to draw the warning width line in the editing buffer (as well as the line separating the gutter from the editing buffer)."
  "色は、編集バッファに警告幅ライン（並びに編集バッファから樋を分離線）を描画するために使用されます。"

  "Default 'darkcolor' for all ttk widgets."
  "すべてのTTKのウィジェットのデフォルトの「darkcolor」。"

  "Default background color to use for all ttk widgets that are in a disabled state."
  "無効状態にあるすべてのTTKのウィジェットに使用するデフォルトの背景色。"

  "Default background color to use for all ttk widgets when the mouse cursor hovers over the widget."
  "マウスカーソルがウィジェットの上に置いたときに、すべてのTTKのウィジェットに使用するデフォルトの背景色。"

  "Default background color to use for all ttk widgets."
  "すべてのTTKのウィジェットに使用するデフォルトの背景色。"

  "Default border color for all ttk widgets."
  "すべてのTTKのウィジェットのデフォルト境界線の色。"

  "Default color for non-syntax highlighted text."
  "非構文のデフォルトの色は、テキストを強調しました。"

  "Default foreground text color to use for all ttk widgets that are in a disabled state."
  "無効状態にあるすべてのTTKのウィジェットに使用するテキストの前景色をデフォルト。"

  "Default foreground text color to use for all ttk widgets."
  "すべてのTTKのウィジェットに使用するテキストの前景色をデフォルト。"

  "Determines the number of grips strips to display in the grip area between resizable panes."
  "サイズ変更可能なペイン間のグリップエリアに表示するグリップストリップの数を決定します。"

  "Determines the thickness of the grip area between resizable panes."
  "サイズ変更可能なペイン間のグリップ領域の厚さを決定します。"

  "ERROR:  Unable to read"
  "エラー: を読み取れません。"

  "Foreground (slider) color used in the sidebar scrollbar."
  "サイドバーのスクロールバーで使用される前景（スライダー）カラー。"

  "Foreground (slider) color used in the text scrollbars."
  "テキストスクロールバーで使用される前景（スライダー）カラー。"

  "Foreground text color for strings."
  "文字列のテキストの前景色。"

  "Foreground text color to use for all miscellaneous1 labeled text."
  "すべてmiscellaneous1というテキストに使用するフォアグラウンドのテキストの色。"

  "Foreground text color to use for all miscellaneous2 labeled text."
  "すべてmiscellaneous2というテキストに使用するフォアグラウンドのテキストの色。"

  "Foreground text color to use for all miscellaneous3 labeled text."
  "すべてmiscellaneous3というテキストに使用するフォアグラウンドのテキストの色。"

  "Foreground text color to use for comments."
  "前景テキストの色は、コメントに使用します。"

  "Foreground text color to use for displaying line numbers."
  "前景テキストの色は、行番号を表示するために使用します。"

  "Foreground text color to use for displaying numbers."
  "前景テキストの色は、番号を表示するために使用します。"

  "Foreground text color to use for language-specific keywords."
  "前景テキストの色は、言語固有のキーワードを使用しています。"

  "Foreground text color to use for language-specific punctuation."
  "言語固有の句読点に使用するフォアグラウンドのテキストの色。"

  "Foreground text color to use for meta syntax."
  "メタ構文に使用するフォアグラウンドのテキストの色。"

  "Foreground text color to use for precompiler syntax."
  "前景テキストの色は、プリコンパイラの構文に使用します。"

  "Foreground text color to use for selected text."
  "前景テキストの色は、選択したテキストに使用します。"

  "Foreground text color used for menus item that are disabled."
  "無効になっているメニュー項目に使用するテキストの前景色。"

  "Foreground text color used for the current/active menu item."
  "現在の/アクティブなメニュー項目に使用するテキストの前景色。"

  "Foreground text color used in menus."
  "メニューで使用テキストの前景色。"

  "Foreground text/image color used in tabbar and tabs."
  "タブバーとタブで使用される前景テキスト/画像の​​色。"

  "Images"
  "画像"

  "Maximum thickness of the text scrollbar when it is active."
  "それがアクティブになっているテキストスクロールバーの最大厚さ。"

  "Maximum thickness of the text scrollbars when they are active."
  "彼らはアクティブなテキストスクロールバーの最大厚さ。"

  "Menu Options"
  "Menu Options（メニューの設定）"

  "Menu relief value."
  "メニューリリーフ値。"

  "Pixel height of the tabbar widget."
  "タブバーウィジェットのピクセルの高さ。"

  "Relief used in drawing the tabs."
  "救済は、タブの描画に使用されます。"

  "Relief value of the sidebar area."
  "サイドバー領域の救済値。"

  "Sidebar Options"
  "﻿サイドバーオプション"

  "Sidebar Scrollbar Options"
  "サイドバースクロールバーのオプション"

  "Specifies the color to display around the sidebar when the sidebar does not have the focus."
  "サイドバーにフォーカスがないときに、サイドバーの周りに表示する色を指定します。"

  "Specifies the color to display around the sidebar when the sidebar has the focus."
  "サイドバーにフォーカスがあるときに、サイドバーの周りに表示する色を指定します。"

  "Specifies the default background color to use for text that is selected in a standard ttk widget (this does not include the editing buffer)."
  "（これは編集バッファが含まれていません）標準TTKウィジェットで選択されているテキストに使用するデフォルトの背景色を指定します。"

  "Specifies the default foreground text color to use for text that is selected in a standard ttk widget (this does not include the editing buffer)."
  "（これは編集バッファが含まれていません）標準TTKウィジェットで選択されているテキストに使用するデフォルトのフォアグラウンド・テキストの色を指定します。"

  "Specifies the default relief to use when drawing ttk widgets."
  "TTKのウィジェットを描画するときに使用するデフォルトの救済を指定します。"

  "Specifies the disclosure image style to use in the sidebar."
  "サイドバーで使用する開示された画像スタイルを指定します。"

  "Specifies the pixel thickness of the highlight line."
  "ハイライト線のピクセルの太さを指定します。"

  "Syntax Colors"
  "構文の色"

  "Tab Options"
  "タブのオプション"

  "Text Scrollbar Options"
  "テキストスクロールバーのオプション"

  "Text color for all sidebar items that are not selected."
  "選択されていないすべてのサイドバーの項目のテキストの色。"

  "Text color for all sidebar items that are selected."
  "選択されているすべてのサイドバーの項目のテキストの色。"

  "ttk Widget Colors"
  "TTKウィジェットの色"

}

# themer.tcl
msgcat::mcmset ja {

  "   Show All"
  "すべて表示"

  "   Show Category"
  "カテゴリーを表示"

  "   Show Color"
  "表示色"

  "   Show Selected Option"
  "表示選択したオプション"

  "   Show Selected Value"
  "表示選択した値"

  "Categories"
  "カテゴリー"

  "Change Base Color"
  "変更ベースカラー"

  "Choose Theme"
  "テーマを選択"

  "Custom Directory"
  "カスタムディレクトリ"

  "Custom..."
  "カスタム..."

  "Delete swatch?"
  "スウォッチを削除しますか？"

  "Description"
  "内容："

  "Details"
  "詳細"

  "Done"
  "決定"

  "Export"
  "エクスポート"

  "GIF Photo"
  "GIF写真"

  "Import"
  "輸入"

  "Import BMP Data"
  "インポートBMPデータ"

  "Import BMP Mask"
  "インポートBMPマスク"

  "Import Error"
  "インポートエラー"

  "Import Theme File"
  "インポートテーマファイル"

  "Installation Directory"
  "インストールディレクトリ"

  "Modifications"
  "修正"

  "None"
  "なし"

  "One-Color Bitmap"
  "ワンカラービットマップ"

  "Preview"
  "プレビュー"

  "Relief: "
  "救援"

  "Save As:"
  "保存する："

  "Save theme changes?"
  "テーマの変更を保存しますか？"

  "Select Directory"
  "ディレクトリを選択"

  "Swatch"
  "スウォッチ"

  "Swatch Colors"
  "スウォッチの色"

  "Table Filters"
  "テーブルのフィルター"

  "The current theme has unsaved changes"
  "現在のテーマは保存されていない変更があります"

  "Tree Style: "
  "ツリーのスタイル："

  "Two-Color Bitmap"
  "二つの色のビットマップ"

  "User Directory"
  "ユーザーのディレクトリ"

  "Value"
  "明度"

  "Value: "
  "価格:"

}

# themes.tcl
msgcat::mcmset ja {

  "Theme"
  "テーマ"

  "Theme:*"
  "テーマ"

}

# tke.tcl
msgcat::mcmset ja {

  "Import TKE theme?"
  "インポートTKEのテーマ？"

  "Import TextMate theme?"
  "TextMateのテーマをインポート？"

}

# tkedat.tcl
msgcat::mcmset ja {

  "Unable to read"
  "読み取ることができません。"

}

# vim.tcl
msgcat::mcmset ja {

  "File successfully written"
  "ファイルが正常に書き込まれました。"

  "Filename already exists"
  "ファイル名が既に存在します。"

}

# General
msgcat::mcmset ja {

  "All"
  "ALL"

  "Cancel"
  "キャンセル"

  "Close"
  "閉じる"

  "Delete"
  "削除"

  "Favorite"
  "お気に入り"

  "Find"
  "Find"

  "Move to Other Pane"
  "他のペインに移動します"

  "New File"
  "新規ファイル"

  "Open"
  "オープン"

  "Save"
  "保存"

  "Save As"
  "名前を付けて保存"

  "Split View"
  "2 ??????"

  "Theme Editor"
  "テーマエディタ"

  "Unable to write"
  "書き込めません。"

  "Unfavorite"
  "気に入らない"

}

