# api.tcl
msgcat::mcmset ja {

  "Argument list to api::add_file was not an even key/value pair"
  "APIへの引数リスト:: ADD_FILEもキー/値のペアではなかった"

}

# bgproc.tcl
msgcat::mcmset ja {

  "Unable to run system command (%s)"
  "システム·コマンド（％s）を実行することができません"

}

# gui.tcl
msgcat::mcmset ja {

  "%s, Line: %d, Column: %d"
  "％sの、ライン：％d、列％dの"

  "Close All Tabs"
  "すべてのタブを閉じる"

  "Close Other Tab(s)"
  "閉じるその他のタブ（S）"

  "Close Other*"
  "その他の*を閉じ"

  "Close Tab"
  "タブを閉じる"

  "Copyright %d-%d"
  "著作権％D-％dの"

  "Delete tab?"
  "タブを削除しますか？"

  "Developer:"
  "デベロッパー"

  "Email:"
  "メール"

  "Favorited"
  "お気に入り"

  "File attribute (%s) does not exist"
  "ファイル属性（％s）は存在しません"

  "File index is out of range"
  "ファイルインデックスが範囲外である"

  "Line: %d, Column: %d"
  "ライン：％dが、カラム：％dの"

  "Locked"
  "ロックする"

  "Move to Other Pane"
  "他のペインに移動します"

  "Move*"
  "ムーブ"

  "Release Type:"
  "リリースの種類:"

  "Reload file?"
  "ファイルをリロード？"

  "Save request"
  "リクエストを保存"

  "Show in Sidebar"
  "サイドバーで表示"

  "Tcl/Tk Version:"
  "Tcl/Tk のバージョン:"

  "Total Lines: %d, Total Characters: %d"
  "総行：％dが、合計文字：％D"

  "Unable to find current file (tab: %s)"
  "現在のファイルが見つかりません（ペ：％s）を"

  "Untitled"
  "無題"

  "Version:"
  "Version:"

}

# markers.tcl
msgcat::mcmset ja {

  "Marker name:"
  "マーカー名："

}

# menus.tcl
msgcat::mcmset ja {

  "                                  Profiling Report Sorted By (%s)"
  "ソート順プロファイリングレポート（％s）が"

  "About TKE"
  "TKEについて"

  "Align cursors"
  "カーソルを合わせ"

  "All"
  "ALL"

  "Append next occurrence"
  "次のオカレンスを追加"

  "Check for Update"
  "アップデートの確認"

  "Clear All"
  "すべてクリア"

  "Close All"
  "すべて閉じる"

  "Comment"
  "コメント"

  "Copy"
  "コピー"

  "Create new..."
  "新しい作成..."

  "Create..."
  "する"

  "Cut"
  "CUT"

  "Disable Auto-Indent"
  "自動インデントを無効にします。"

  "Edit"
  "編集"

  "Edit current"
  "編集現在"

  "Edit user"
  "ユーザーの編集"

  "Edit..."
  "編集"

  "Enable Auto-Indent"
  "自動インデントを有効にします。"

  "File"
  "ファイル"

  "Find"
  "Find"

  "Find and Replace"
  "検索と置換"

  "Find in files"
  "ファイルから検索"

  "Find marker"
  "マーカーを見つける"

  "Find matching pair"
  "一致するペアを見つける"

  "Format Text"
  "テキストをフォーマットする"

  "From Clipboard"
  "クリップボードから"

  "Goto Last Tab"
  "後藤最後のタブ"

  "Goto Next Tab"
  "後藤次のタブ"

  "Goto Other Pane"
  "後藤他のペイン"

  "Goto Previous Tab"
  "後藤前のタブ"

  "Help"
  "ヘルプ"

  "Hide Console"
  "コンソールを隠す"

  "Hide Sidebar"
  "隠すサイドバー"

  "Hide Status Bar"
  "隠すステータスバー"

  "Hide Tab Bar"
  "タブバーを非表示"

  "Import TextMate theme..."
  "TextMateのテーマをインポート..."

  "Indent"
  "インデント"

  "Insert Text"
  "テキストの挿入"

  "Insert enumeration"
  "列挙型を挿入"

  "Install..."
  "インストール"

  "Launcher"
  "ランチャー"

  "Lock"
  "固定"

  "Menu Bindings"
  "メニューバインディング"

  "Menu: About TKE"
  "メニュー：TKEについて"

  "Menu: Align cursors"
  "メニュー：カーソルを合わせ"

  "Menu: Append next occurrence"
  "メニュー：次のオカレンスを追加"

  "Menu: Check for Update"
  "アップデートの確認"

  "Menu: Close all tabs"
  "すべてのタブを閉じる"

  "Menu: Close current tab"
  "メニュー：現在のタブを閉じる"

  "Menu: Comment selected text"
  "メニュー：選択したテキストをコメント"

  "Menu: Copy selected text"
  "メニュー：コピー選択したテキスト"

  "Menu: Create new plugin"
  "メニュー：新しいプラグインを作成"

  "Menu: Create new theme"
  "メニュー：新しいテーマを作成する"

  "Menu: Cut selected text"
  "メニュー：カット選択したテキスト"

  "Menu: Disable Vim mode"
  "メニュー：Vimのモードを無効にします"

  "Menu: Disable auto-indent"
  "メニュー： 自動インデントを無効にします。"

  "Menu: Edit Tke theme"
  "メニュー：編集TKEテーマ"

  "Menu: Edit current snippets"
  "メニュー：現在のスニペットを編集"

  "Menu: Edit user menu bindings"
  "メニュー：編集ユーザーメニューバインディング"

  "Menu: Edit user preferences"
  "メニュー：編集ユーザー設定"

  "Menu: Enable Vim mode"
  "メニュー：Vimのモードを有効に"

  "Menu: Enable auto-indent"
  "メニュー： 自動インデントを有効にします。"

  "Menu: Favorite file"
  "メニュー：好きなファイル"

  "Menu: Find"
  "メニュー：見つける"

  "Menu: Find and Replace"
  "検索と置換"

  "Menu: Find in files"
  "メニュー：ファイルから検索"

  "Menu: Find matching character pair"
  "メニュー：一致する文字のペアを探す"

  "Menu: Find next occurrence"
  "メニュー：次の出現箇所を検索"

  "Menu: Find previous occurrence"
  "メニュー：前の発生を検索"

  "Menu: Format all text"
  "メニュー：すべてのテキストの書式設定"

  "Menu: Format selected text"
  "メニュー：選択したテキストのフォーマット"

  "Menu: Goto last tab"
  "メニュー：後藤最後のタブ"

  "Menu: Goto next tab"
  "メニュー：後藤次のタブ"

  "Menu: Goto other pane"
  "メニュー：後藤他のペイン"

  "Menu: Goto previous tab"
  "メニュー：後藤前のタブ"

  "Menu: Hide Tab Bar"
  "メニュー：タブバーを非表示に"

  "Menu: Hide console"
  "メニュー：コンソールを非表示に"

  "Menu: Hide sidebar"
  "メニュー：サイドバーを隠す"

  "Menu: Hide status bar"
  "メニュー：非表示のステータスバー"

  "Menu: Import TextMate theme"
  "メニュー：輸入TextMateのテーマ"

  "Menu: Indent selected text"
  "メニュー：選択したテキストをインデント"

  "Menu: Insert enumeration"
  "メニュー：列挙型を挿入します"

  "Menu: Insert from clipboard"
  "クリップボードからの挿入"

  "Menu: Insert snippet"
  "メニュー：挿入スニペット"

  "Menu: Install plugin"
  "メニュー：インストールプラグイン"

  "Menu: Lock file"
  "メニュー：ロックファイル"

  "Menu: Move to other pane"
  "メニュー：他のウィンドウに移動"

  "Menu: New file"
  "メニュー：新ファイル"

  "Menu: Open Favorite"
  "メニュー：オープン好き"

  "Menu: Open Recent"
  "メニュー：最近のオープン"

  "Menu: Open directory"
  "メニュー：オープンディレクトリ"

  "Menu: Open file"
  "メニュー：ファイルを開く"

  "Menu: Paste and format text from clipboard"
  "メニュー：クリップボードからの貼り付けやテキストの書式設定"

  "Menu: Paste text from clipboard"
  "クリップボードから貼り付け"

  "Menu: Quit application"
  "メニュー：アプリケーションを終了し"

  "Menu: Redo"
  "メニュー：やり直し"

  "Menu: Reload all plugins"
  "メニュー：すべてのプラグインを再ロード"

  "Menu: Reload current snippets"
  "メニュー：現在のスニペットを再読み込み"

  "Menu: Restart tke"
  "メニュー：TKEを再起動します"

  "Menu: Save all files"
  "メニュー：すべてのファイルを保存"

  "Menu: Save file"
  "メニュー：ファイルを保存します"

  "Menu: Save file as"
  "メニュー：ファイルとして保存"

  "Menu: Select all occurrences"
  "メニュー：すべてのオカレンスを選択"

  "Menu: Select all text"
  "メニュー：すべてのテキストを選択"

  "Menu: Set user bindings to global bindings"
  "メニュー：グローバルバインディングに設定し、ユーザーのバインド"

  "Menu: Set user preferences to global preferences"
  "メニュー：グローバル設定へのユーザープリファレンスを設定"

  "Menu: Show Tab Bar"
  "メニュー：表示タブバー"

  "Menu: Show console"
  "メニュー：表示するコンソール"

  "Menu: Show last profiling report"
  "メニュー：ショー最後のプロファイリングレポート"

  "Menu: Show sidebar"
  "メニュー：表示するサイドバー"

  "Menu: Show status bar"
  "メニュー：表示するステータスバー"

  "Menu: Sort tabs"
  "メニュー：ソートタブ"

  "Menu: Start profiling"
  "メニュー：スタートプロファイリング"

  "Menu: Stop profiling"
  "メニュー：ストッププロファイリング"

  "Menu: Toggle split view mode"
  "メニュー：トグル分割ビューモード"

  "Menu: Uncomment selected text"
  "メニュー：コメント解除選択したテキスト"

  "Menu: Undo"
  "メニュー：元に戻す"

  "Menu: Unfavorite file"
  "メニュー：気に入らないファイル"

  "Menu: Unindent selected text"
  "メニュー：インデント解除選択したテキスト"

  "Menu: Uninstall plugin"
  "メニュー：アンプラグ"

  "Menu: Unlock file"
  "メニュー：ロック解除ファイル"

  "Menu: View User Guide"
  "メニュー：表示ユーザガイド"

  "Menu: View global menu bindings"
  "メニュー：表示グローバルメニューバインディング"

  "Menu: View global preferences"
  "メニュー：表示グローバルプリファレンス"

  "Move to other pane"
  "他のウィンドウに移動する"

  "New"
  "新しい"

  "Open Directory..."
  "ディレクトリを開きます。..."

  "Open Favorite"
  "オープン好き"

  "Open File..."
  "ファイルを開く"

  "Open Recent"
  "最近のオープン"

  "Paste"
  "貼り付け"

  "Paste and Format"
  "ペーストとフォーマット"

  "Plugins"
  "プラグイン"

  "Preferences"
  "選好"

  "Profiling started"
  "プロファイリングが開始されました"

  "Profiling stopped"
  "プロファイリングが停止"

  "Quit"
  "やめる"

  "Redo"
  "やり直す"

  "Reload"
  "再読み込み"

  "Reload current"
  "現在の再読み込み"

  "Reset user to base"
  "ベースにユーザーのリセット"

  "Restart tke"
  "TKEを再起動します"

  "Save All"
  "すべて保存"

  "Save As..."
  "名前を付けて保存..."

  "Select All"
  "すべて選択"

  "Select all occurrences"
  "すべてのオカレンスを選択"

  "Select next occurrence"
  "次のオカレンスを選択してください"

  "Select previous occurrence"
  "以前の発生を選択"

  "Selected"
  "選択"

  "Set Syntax"
  "構文を設定"

  "Set Theme"
  "設定テーマ"

  "Set user to global"
  "グローバルにユーザーを設定する"

  "Show Console"
  "コンソールの表示"

  "Show Last Profiling Report"
  "最後のプロファイリングレポートを表示"

  "Show Sidebar"
  "表示するサイドバー"

  "Show Status Bar"
  "表示ステータスバー"

  "Show Tab Bar"
  "表示タブバー"

  "Show*Profiling*"
  "表示*プロファイリング*"

  "Snippet"
  "スニペット"

  "Snippets"
  "スニペット"

  "Sort Tabs"
  "並べタブ"

  "Split view"
  "2 画面分割表示"

  "Start Profiling"
  "プロファイリング開始"

  "Stop Profiling"
  "プロファイリングを停止"

  "Tabs"
  "タブ"

  "Text"
  "Text"

  "Theme Creator"
  "テーマ作成者"

  "Tools"
  "道具"

  "Uncomment"
  "コメントを解除"

  "Undo"
  "アンドゥ"

  "Unindent"
  "インデント解除"

  "Uninstall..."
  "アンインストール"

  "Unlock"
  "アンロック"

  "User Guide"
  "マニュアル"

  "View"
  "表示"

  "View base"
  "ビュー·ベース"

  "View global"
  "グローバルを表示"

  "Vim Mode"
  "Vimのモード"

}

# plugins.tcl
msgcat::mcmset ja {

  "ERROR:  Plugin name already exists"
  "エラー：プラグイン名がすでに存在"

  "ERROR:  Plugin name is not valid (only alphanumeric and underscores are allowed)"
  "ERROR：プラグイン名が有効ではありません（英数字とアンダースコアは許可されています）"

  "ERROR:  Unable to create plugin directory"
  "エラー：プラグインディレクトリを作成できません"

  "ERROR:  Unable to write plugin files"
  "エラー：プラグインファイルを書き込むことができません"

  "Enter plugin name"
  "プラグイン名を入力してください"

  "Plugin %s installed"
  "プラグイン％sのインストール"

  "Plugin %s uninstalled"
  "プラグイン％sをアンインストール"

  "Plugin Errors"
  "プラグインエラー"

  "Plugins successfully reloaded"
  "プラグインが正常にリロード"

  "Syntax errors found in selected plugins"
  "構文エラーは、選択したプラグインで発見"

}

# sidebar.tcl
msgcat::mcmset ja {

  "Add Parent Directory"
  "親ディレクトリ"

  "Close Directory Files"
  "閉じるディレクトリファイル"

  "Delete"
  "削除"

  "Delete directory?"
  "ディレクトリを削除しますか？"

  "Delete file?"
  "ファイルを削除しますか？"

  "Duplicate"
  "複製"

  "Make Current Working Directory"
  "現在の作業ディレクトリを作る"

  "New Directory"
  "新しいディレクトリ"

  "New File"
  "新規ファイル"

  "Open"
  "オープン"

  "Open Directory Files"
  "オープンディレクトリのファイル"

  "Refresh Directory Files"
  "リフレッシュディレクトリファイル"

  "Remove Parent from Sidebar"
  "サイドバーから親を削除する"

  "Remove from Sidebar"
  "サイドバーから削除"

  "Rename"
  "名前の変更"

}

# snippets.tcl
msgcat::mcmset ja {

  "Snippet: %s: %s"
  "スニペットた：％s：％sの"

  "Snippet: *"
  "スニペット：*"

}

# syntax.tcl
msgcat::mcmset ja {

  "Syntax error in %s.syntax file"
  "パーセントs.syntaxファイルの構文エラー"

  "Syntax:  %s"
  "構文：％sは"

  "Theme:  %s"
  "テーマ：％sは"

}

# themer.tcl
msgcat::mcmset ja {

  "Create"
  "作る"

  "Create New Theme"
  "新しいテーマを作成する"

  "Create custom"
  "カスタム作成"

  "ERROR:  Unable to read %s"
  "ERROR：％sのを読み取ることができません"

  "ERROR:  Unable to write %s"
  "ERROR：％sを書き込むことができません"

  "Edit theme"
  "テーマを編集"

  "Enter theme name"
  "テーマ名を入力してください"

  "Error:  Theme is not a supported theme"
  "エラー：テーマは、サポートされているテーマではない"

  "Import"
  "輸入"

  "Import TextMate Theme"
  "TextMateのテーマをインポート"

  "Name:"
  "名"

  "OK"
  "Okay"

  "Reset"
  "リセット"

  "Select theme"
  "テーマの選択"

}

# tke.tcl
msgcat::mcmset ja {

  "ERROR:  %s"
  "ERROR：％sは"

  "Edit theme?"
  "テーマを編集？"

  "Import TextMate theme?"
  "TextMateのテーマをインポート？"

}

# tkedat.tcl
msgcat::mcmset ja {

  "Unable to open %s for reading"
  "読み取るための％sを開けません"

  "Unable to open %s for writing"
  "書き込み用の％sを開けません"

}

# General
msgcat::mcmset ja {

  "Cancel"
  "キャンセル"

  "Close"
  "閉じる"

  "Favorite"
  "お気に入り"

  "Find:"
  "Find"

  "Replace:"
  "置換："

  "Save"
  "保存"

  "Save As"
  "名前を付けて保存"

  "Unfavorite"
  "気に入らない"

}

