# api.tcl
msgcat::mcmset nl {

  "Argument list to api::add_file was not an even key/value pair"
  "Lijst met argumenten om api :: add_file was niet een even sleutel / waarde paar"

}

# bgproc.tcl
msgcat::mcmset nl {

  "Unable to run system command (%s)"
  "Niet worden uitgevoerd systeem commando (% s)"

}

# diff.tcl
msgcat::mcmset nl {

  "    End: "
  "nl-NL End:"

  "    Start: "
  "Start:"

  "Enter difference command"
  "Voer verschil opdracht"

  "Enter starting file"
  "Begin bestand invoeren"

  "Update"
  "Bijwerken"

}

# gui.tcl
msgcat::mcmset nl {

  "%d substitutions done"
  "%d vervangingen gedaan"

  "%s, Line: %d, Column: %d"
  "% S, Line:% d, kolom:% d"

  "Close All Tabs"
  "Sluit alle tabbladen"

  "Close Other Tab(s)"
  "Close Andere Tab (s)"

  "Close Other*"
  "Alle andere tabbladen sluiten"

  "Close Tab"
  "Tabblad sluiten"

  "Copyright %d-%d"
  "Copyright% d-% d"

  "Delete tab?"
  "Delete tab?"

  "Developer:"
  "Projectontwikkelaar;"

  "Email:"
  "E-mail"

  "Error"
  "Fout"

  "Favorited"
  "Favoriet"

  "File attribute (%s) does not exist"
  "Dossierattributen (% s) bestaat niet"

  "File index is out of range"
  "File index valt buiten het bereik"

  "Line: %d, Column: %d"
  "Line:% d, kolom:% d"

  "Locked"
  "Afgesloten"

  "Move to Other Pane"
  "Verplaatsen naar andere Pane"

  "Move*"
  "Move"

  "Must be in multicursor mode to insert numbers"
  "Moet in multicursor modus nummers invoegen"

  "No search results found"
  "﻿Geen resultaten gevonden..."

  "Release Type:"
  "Release Type:"

  "Reload file?"
  "Opnieuw laden"

  "Save request"
  "Sparen verzoek"

  "Search wrapped to beginning of file"
  "Zoek verpakt aan begin van bestand"

  "Search wrapped to end of file"
  "Zoek verpakt op einde van het bestand"

  "Show in Sidebar"
  "Show in Sidebar"

  "Starting number:"
  "Begin Pagina Nummer"

  "Tcl/Tk Version:"
  "Tcl/Tk versie:"

  "Total Lines: %d, Total Characters: %d"
  "Totaal Lijnen:% d, Total Characters:% d"

  "Unable to find current file (tab: %s)"
  "Kan huidige bestand te vinden (tabblad:% s)"

  "Unable to successfully parse number string"
  "Kan niet met succes nummer tekenreeks parseren"

  "Unable to write file"
  "Kan niet schrijven bestand"

  "Untitled"
  "Untitled"

  "Version:"
  "Versie:"

}

# markers.tcl
msgcat::mcmset nl {

  "Marker name:"
  "Naam Marker:"

}

# menus.tcl
msgcat::mcmset nl {

  "                                  Profiling Report Sorted By (%s)"
  "Profiling Report Geordend volgens (% s)"

  "About TKE"
  "Over TKE"

  "Align cursors"
  "Lijn cursors"

  "All"
  "Alle"

  "Append next occurrence"
  "Voeg volgende voorkomen"

  "Auto-Indent"
  "Automatisch inspringen"

  "Check for Update"
  "Zoek naar nieuwe versies"

  "Clear All"
  "Alles wissen"

  "Close All"
  "Alles sluiten"

  "Comment"
  "Commentaar"

  "Copy"
  "Kopiëren"

  "Create at current line"
  "Maken op de huidige regel"

  "Create new..."
  "Nieuw aanmaken"

  "Create..."
  "Maken..."

  "Cut"
  "Knip"

  "Edit"
  "Bewerken"

  "Edit Language"
  "Bewerk Taal"

  "Edit User"
  "Order bewerken"

  "Edit..."
  "Bewerken..."

  "File"
  "Bestand"

  "Find"
  "Query"

  "Find and Replace"
  "Zoeken en vervangen"

  "Find in files"
  "Zoeken in bestanden..."

  "Find matching pair"
  "Zoek bijpassende paar"

  "Format Text"
  "Tekst opmaken"

  "From Clipboard"
  "Van klembord"

  "Goto Last Tab"
  "Goto Last Tab"

  "Goto Next Tab"
  "Goto Volgende Tab"

  "Goto Other Pane"
  "Goto Andere Pane"

  "Goto Previous Tab"
  "Ga naar vorig tabblad"

  "Help"
  "Help"

  "Hide Console"
  "Verbergen Console"

  "Hide Line Numbers"
  "Regelnummers verbergen"

  "Hide Sidebar"
  "Zijbalk verbergen"

  "Hide Status Bar"
  "Verberg Status Bar"

  "Hide Tab Bar"
  "Hide Tab Bar"

  "Import TextMate theme..."
  "Import TextMate thema ..."

  "Indent"
  "Inspringen"

  "Indent Mode"
  "Streepje modus"

  "Indent Off"
  "Streepje uit"

  "Insert Text"
  "Index invoegen"

  "Insert enumeration"
  "Plaats opsomming"

  "Install..."
  "Installatie"

  "Jump backward"
  "Spring achteruit"

  "Jump forward"
  "Spring vooruit"

  "Launcher"
  "Launcher"

  "Lock"
  "Vergrendelen"

  "Markers"
  "markeerders"

  "Menu Bindings"
  "Menu Bindingen"

  "Menu Edit user snippets"
  "Menu bewerken gebruiker fragmenten"

  "Menu: About TKE"
  "Menu: Over TKE"

  "Menu: Align cursors"
  "Menu: Lijn cursors"

  "Menu: Append next occurrence"
  "Menu: Append volgende voorkomen"

  "Menu: Check for Update"
  "Menu: Check for Update"

  "Menu: Close all tabs"
  "Menu: Sluit alle tabbladen"

  "Menu: Close current tab"
  "Huidig tabblad sluiten"

  "Menu: Comment selected text"
  "Menu: Reactie geselecteerde tekst"

  "Menu: Copy selected text"
  "Menu: Geselecteerde tekst kopiëren"

  "Menu: Create marker at current line"
  "Menu: Marker op de huidige regel maken"

  "Menu: Create new plugin"
  "Menu: Maak een nieuwe plugin"

  "Menu: Create new theme"
  "Nieuw thema aanmaken..."

  "Menu: Cut selected text"
  "Menu: Geselecteerde tekst knippen"

  "Menu: Disable Vim mode"
  "Menu: Uitschakelen Vim modus"

  "Menu: Edit Tke theme"
  "Menu: Bewerken Tke thema"

  "Menu: Edit language preferences"
  "Menu: Bewerken taalvoorkeuren"

  "Menu: Edit language snippets"
  "Menu: Bewerken taal fragmenten"

  "Menu: Edit user menu bindings"
  "Menu: menu Gebruiker bewerken bindingen"

  "Menu: Edit user preferences"
  "Gebruikersvoorkeuren Edit: Menu"

  "Menu: Enable Vim mode"
  "Menu: Enable Vim modus"

  "Menu: Favorite file"
  "Menu: Favoriete bestand"

  "Menu: Find"
  "Menu: Zoek"

  "Menu: Find and Replace"
  "Zoeken en vervangen"

  "Menu: Find in files"
  "Zoek in bestanden..."

  "Menu: Find matching character pair"
  "Menu: Vind passende tekenpaar"

  "Menu: Find next occurrence"
  "Menu: Volgende instantie"

  "Menu: Find previous occurrence"
  "Menu: Zoek vorige exemplaar"

  "Menu: Format all text"
  "Menu: Formatteer alle tekst"

  "Menu: Format selected text"
  "Menu: Format geselecteerde tekst"

  "Menu: Goto last tab"
  "Menu: Ga naar laatste tabblad"

  "Menu: Goto next difference"
  "Menu: Goto volgende verschil"

  "Menu: Goto next tab"
  "Menu: Ga naar volgende tabblad"

  "Menu: Goto other pane"
  "Menu: Goto andere ruit"

  "Menu: Goto previous difference"
  "Menu: Goto vorige verschil"

  "Menu: Goto previous tab"
  "Menu: Ga naar vorige tabblad"

  "Menu: Hide Line Numbers"
  "Menu: Verbergen regelnummers"

  "Menu: Hide Tab Bar"
  "Menu: Hide Tab Bar"

  "Menu: Hide console"
  "Menu: Verbergen console"

  "Menu: Hide sidebar"
  "Menu: Verbergen zijbalk"

  "Menu: Hide status bar"
  "Menu: status te verbergen bar"

  "Menu: Import TextMate theme"
  "Menu: Import TextMate thema"

  "Menu: Indent selected text"
  "Menu: inspringen geselecteerde tekst"

  "Menu: Insert enumeration"
  "Menu: Invoegen opsomming"

  "Menu: Insert from clipboard"
  "Invoegen vanaf klembord"

  "Menu: Insert snippet"
  "Menu: snippet Insert"

  "Menu: Install plugin"
  "Menu: Installeer plugin"

  "Menu: Jump backward"
  "Menu: Achteruit springen"

  "Menu: Jump forward"
  "Menu: Sprong voorwaarts"

  "Menu: Lock file"
  "Menu: Lock file"

  "Menu: Move to other pane"
  "Menu: Overgang naar andere ruit"

  "Menu: New file"
  "Menu: Nieuw bestand"

  "Menu: Open Favorite"
  "Menu: Open Favoriete"

  "Menu: Open Recent"
  "Menu: Recent geopend"

  "Menu: Open directory"
  "Menu: Open directory"

  "Menu: Open file"
  "Menu: Bestand openen"

  "Menu: Paste and format text from clipboard"
  "Menu: Plakken en opmaken van het klembord"

  "Menu: Paste text from clipboard"
  "Tekst plakken vanaf het klembord"

  "Menu: Quit application"
  "Menu: Quit toepassing"

  "Menu: Redo"
  "Menu: Redo"

  "Menu: Reload all plugins"
  "Menu: Reload alle plugins"

  "Menu: Reload snippets"
  "Menu: Reload fragmenten"

  "Menu: Remove all markers"
  "Menu: Alle markeringen verwijderen"

  "Menu: Remove marker from current line"
  "Menu: Marker verwijderen uit de huidige regel"

  "Menu: Replace line with script"
  "Menu: Regel vervangen door script"

  "Menu: Restart tke"
  "Menu: Restart TKE"

  "Menu: Save all files"
  "Menu: Sla alle bestanden"

  "Menu: Save file"
  "Menu: Bestand opslaan"

  "Menu: Save file as"
  "Menu: Bestand opslaan als"

  "Menu: Select all occurrences"
  "Menu: Selecteer alle exemplaren"

  "Menu: Select all text"
  "Alle tekst selecteren"

  "Menu: Send Bug Report"
  "Menu: Send bugreport"

  "Menu: Send Feedback"
  "Menu: Feedback verzenden"

  "Menu: Set indent mode to IND"
  "Menu: Streepje modus instelt op IND"

  "Menu: Set indent mode to IND+"
  "Menu: Streepje modus instelt op IND +"

  "Menu: Set indent mode to OFF"
  ": Menureeks streepje modus op OFF"

  "Menu: Set user bindings to global bindings"
  "Menu: Stel gebruiker bindingen aan de mondiale bindingen"

  "Menu: Set user preferences to global preferences"
  "Menu: Stel gebruikersvoorkeuren tot wereldwijde voorkeuren"

  "Menu: Show Diagnostic Logfile"
  "Menu: Toon diagnostische Logfile"

  "Menu: Show Line Numbers"
  "Regelnummering tonen"

  "Menu: Show Tab Bar"
  "Menu: Show Tab Bar"

  "Menu: Show console"
  "Menu: Show console"

  "Menu: Show file difference"
  "Menu: Toon bestand verschil"

  "Menu: Show last profiling report"
  "Menu: Toon laatste profilering rapport"

  "Menu: Show selected line change"
  "Menu: Toon geselecteerde lijn wijzigen"

  "Menu: Show sidebar"
  "Menu: Show sidebar"

  "Menu: Show status bar"
  "Statusbalk tonen"

  "Menu: Sort tabs"
  "Menu: Sort tabs"

  "Menu: Start profiling"
  "Menu: Start profilering"

  "Menu: Stop profiling"
  "Menu: Stop profilering"

  "Menu: Toggle split view mode"
  "Menu: Toggle split view mode"

  "Menu: Uncomment selected text"
  "Menu: Uncomment geselecteerde tekst"

  "Menu: Undo"
  "Menu: Ongedaan maken"

  "Menu: Unfavorite file"
  "Menu: Unfavorite bestand"

  "Menu: Unindent selected text"
  "Menu: laten terugspringen geselecteerde tekst"

  "Menu: Uninstall plugin"
  "Menu: Uninstall plugin"

  "Menu: Unlock file"
  "Menu: Open bestand"

  "Menu: View User Guide"
  "Menu: View User Guide"

  "Menu: View global menu bindings"
  "Menu: Bekijk global menu bindingen"

  "Menu: View global preferences"
  "Menu: View globale voorkeuren"

  "Move to other pane"
  "Overgang naar andere ruit"

  "New"
  "Nieuw"

  "Next difference"
  "Volgend verschil"

  "No files found in specified directories"
  "Geen bestanden gevonden in de opgegeven mappen"

  "Open Directory..."
  "Map openen"

  "Open Favorite"
  "Open Favorite"

  "Open File..."
  "Bestand openen..."

  "Open Recent"
  "Recent geopend"

  "Paste"
  "Pasta"

  "Paste and Format"
  "Plak en Format"

  "Plugins"
  "Plug-in"

  "Preferences"
  "Voorkeuren"

  "Previous difference"
  "Vorig verschil"

  "Profiling started"
  "Profiling begonnen"

  "Profiling stopped"
  "Profiling gestopt"

  "Quit"
  "Ophouden"

  "Redo"
  "Opnieuw"

  "Reload"
  "Herladen"

  "Remove all markers"
  "Alle markeringen verwijderen"

  "Remove from current line"
  "Verwijderen uit de huidige regel"

  "Replace line with script"
  "Regel vervangen door script"

  "Reset User to Base"
  "Reset gebruiker naar Base"

  "Restart tke"
  "Herstart TKE"

  "Save All"
  "Alles opslaan"

  "Save As..."
  "Opslaan als"

  "Select All"
  "Alles selecteren"

  "Select all occurrences"
  "Selecteer alle exemplaren"

  "Select next occurrence"
  "Selecteer volgende voorkomen"

  "Select previous occurrence"
  "Selecteer vorige exemplaar"

  "Selected"
  "Geselecteerd"

  "Send Bug Report"
  "Bugrapport verzenden."

  "Send Feedback"
  "Feedback verzenden"

  "Set Syntax"
  "Stel Syntax"

  "Set Theme"
  "Serie Thema"

  "Set User to Global"
  "Gebruiker instellen naar globaal"

  "Show Console"
  "Show Console"

  "Show Diagnostic Logfile"
  "Toon diagnostische Logfile"

  "Show File Difference"
  "Toon bestand verschil"

  "Show Last Profiling Report"
  "Toon Laatste Profiling Report"

  "Show Line Numbers"
  "Regelnummering tonen"

  "Show Sidebar"
  "Zijbalk tonen"

  "Show Status Bar"
  "Statusbalk tonen"

  "Show Tab Bar"
  "Show Tab Bar"

  "Show selected line change"
  "Toon geselecteerde regel wijzigen"

  "Show*Profiling*"
  "Tonen * Profiling *"

  "Smart Indent"
  "Slimme streepje"

  "Snippet"
  "Snippet"

  "Snippets"
  "Snippets"

  "Sort Tabs"
  "Sorteren Tabs"

  "Split view"
  "Gesplitst beeld"

  "Start Profiling"
  "Start Profiling"

  "Stop Profiling"
  "Stop Profiling"

  "Tabs"
  "Tab"

  "Text"
  "Tekst"

  "Theme Creator"
  "Theme Creator"

  "Tools"
  "hulpmiddelen;"

  "Uncomment"
  "Uncomment"

  "Undo"
  "Ongedaan maken"

  "Unindent"
  "Laten terugspringen"

  "Uninstall..."
  "verwijderen"

  "Unlock"
  "Ontgrendelen"

  "User Guide"
  "Gebruikershandleiding"

  "View"
  "Bekijken"

  "View Base"
  "Weergave Base"

  "View Global"
  "Weergave Global"

  "Vim Mode"
  "Vim Mode"

}

# plugins.tcl
msgcat::mcmset nl {

  "ERROR (%s,%s): %s"
  "FOUT (%s, %s): %s"

  "ERROR:  Plugin name already exists"
  "FOUT: Plugin naam al bestaat"

  "ERROR:  Plugin name is not valid (only alphanumeric and underscores are allowed)"
  "FOUT: Plugin naam is niet geldig (alleen alfanumerieke en underscores zijn toegestaan)"

  "ERROR:  Unable to create plugin directory"
  "FOUT: Kan plugin directory"

  "ERROR:  Unable to write plugin files"
  "FOUT: Kan plugin bestanden weg te schrijven"

  "Enter plugin name"
  "Voer plugin naam"

  "Plugin %s installed"
  "Plugin% s geïnstalleerd"

  "Plugin %s uninstalled"
  "Plugin% s verwijderd"

  "Plugin Errors"
  "Plugin fouten"

  "Plugins successfully reloaded"
  "Plugins succes vernieuwd"

  "Syntax errors found in selected plugins"
  "Syntax fouten gevonden in geselecteerde plugins"

}

# sidebar.tcl
msgcat::mcmset nl {

  "Add Parent Directory"
  "Bovenliggende map"

  "Close Directory Files"
  "Sluiten Directory Bestanden"

  "Delete"
  "Verwijderen"

  "Delete directory?"
  "Delete directory?"

  "Delete file?"
  "Bestand verwijderen"

  "Directory Name:"
  "directory-naam"

  "Duplicate"
  "Dupliceren"

  "File Name:"
  "Bestandsnaam:"

  "Make Current Working Directory"
  "Make Current Working Directory"

  "New Directory"
  "Nieuwe directory"

  "New File"
  "Nieuw bestand"

  "Open"
  "Openen"

  "Open Directory Files"
  "Open Directory Bestanden"

  "Refresh Directory Files"
  "Vernieuwen Directory Bestanden"

  "Remove Parent from Sidebar"
  "Verwijder Parent uit Sidebar"

  "Remove from Sidebar"
  "Verwijderen uit Sidebar"

  "Rename"
  "Hernoem"

  "Show Difference"
  "Toon verschil"

}

# snippets.tcl
msgcat::mcmset nl {

  "Snippet: *"
  "Snippet: *"

}

# syntax.tcl
msgcat::mcmset nl {

  "Syntax error in %s.syntax file"
  "Syntax fout in% s.syntax bestand"

  "Syntax:  %s"
  "Syntax:% s"

  "Theme:  %s"
  "Thema:% s"

}

# themer.tcl
msgcat::mcmset nl {

  "Create"
  "Aanmaken"

  "Create New Theme"
  "Nieuw thema aanmaken..."

  "Create custom"
  "Maak aangepaste"

  "ERROR:  Unable to read %s"
  "FOUT: Kan niet lezen% s"

  "ERROR:  Unable to write %s"
  "FOUT: Kan niet schrijven% s"

  "Edit theme"
  "Thema bewerken"

  "Enter theme name"
  "Enter onderwerp naam"

  "Error:  Theme is not a supported theme"
  "Fout: Thema is geen ondersteund thema"

  "Import"
  "Invoer"

  "Import TextMate Theme"
  "Import TextMate Theme"

  "Name:"
  "Naam:"

  "OK"
  "Oké"

  "Reset"
  "Reset"

  "Select theme"
  "Themabestand selecteren"

}

# tke.tcl
msgcat::mcmset nl {

  "Edit theme?"
  "Bewerk thema?"

  "Import TextMate theme?"
  "Importeer TextMate thema?"

}

# tkedat.tcl
msgcat::mcmset nl {

  "Unable to open %s for reading"
  "Het bestand%1 kon niet worden geopend."

}

# vim.tcl
msgcat::mcmset nl {

  "File %s successfully written"
  "Bestand> %s met success geschreven!"

  "Filename %s already exists"
  "Bestandsnaam %s bestaat al"

}

# General
msgcat::mcmset nl {

  "Cancel"
  "Annuleren"

  "Close"
  "Sluiten"

  "Favorite"
  "Favoriet"

  "Find:"
  "ontdekken"

  "Replace:"
  "Vervangen:"

  "Save"
  "Opslaan"

  "Save As"
  "Opslaan als"

  "Unable to open %s for writing"
  "%1 kon niet worden geopend om naar te schrijven."

  "Unfavorite"
  "Unfavorite"

}

