# api.tcl
msgcat::mcmset nl {

  "Argument list to api::add_file was not an even key/value pair"
  "Lijst met argumenten om api :: add_file was niet een even sleutel / waarde paar"

  "Plugin"
  "Plugin"

}

# bgproc.tcl
msgcat::mcmset nl {

  "Unable to run system command"
  "Onvermogend voor stormloop systeem opdracht"

}

# diff.tcl
msgcat::mcmset nl {

  "    End: "
  "nl-NL End:"

  "    Start: "
  "Start:"

  "Enter difference command"
  "Voer verschil opdracht"

  "Enter starting file"
  "Begin bestand invoeren"

  "Update"
  "Bijwerken"

}

# edit.tcl
msgcat::mcmset nl {

  "File successfully written"
  "Bestand met succes geschreven"

  "Filename already exists"
  "Bestandsnaam bestaat al"

}

# embed_tke.tcl
msgcat::mcmset nl {

  "Find:"
  "ontdekken"

  "Replace:"
  "Vervangen:"

}

# gui.tcl
msgcat::mcmset nl {

  "All"
  "Alle"

  "Case sensitivity"
  "Hoofdletters/kleine letters"

  "Close All Tabs"
  "Sluit alle tabbladen"

  "Close Other Tabs"
  "Alle andere tabbladen sluiten"

  "Close Other*"
  "Alle andere tabbladen sluiten"

  "Close Tab"
  "Tabblad sluiten"

  "Column"
  "Kolom"

  "Copyright"
  "Auteursrecht"

  "Delete tab?"
  "Delete tab?"

  "Developer"
  "Ontwikkelaar"

  "Email"
  "E-mailadres"

  "Error"
  "Fout"

  "Favorited"
  "Favoriet"

  "File already exists.  Use '!' to force an overwrite"
  "Bestand bestaat al.  Gebruik '!' te dwingen een overschrijven"

  "File attribute does not exist"
  "Bestandskenmerk bestaat niet"

  "File index is out of range"
  "File index valt buiten het bereik"

  "Image displayed in fill-in forms which closes the form UI.  Used in forms such as search, search/replace, and find in files."
  "Afbeelding in fill-in vormen die de vorm UI sluit. Gebruikt in de vorm zoals zoeken, zoeken / vervangen, en vinden van bestanden."

  "Image used in tab menus to indicate that the file is associated with a difference view."
  "Afbeelding gebruikt tab menu&#39;s aan te geven dat het bestand is gekoppeld met een verschil weergeven."

  "Image used in tab menus to indicate that the file is locked."
  "Afbeelding gebruikt tab menu&#39;s aan te geven dat het bestand is vergrendeld."

  "Image used in tab menus to indicate that the file is readonly."
  "Afbeelding gebruikt in tabblad menu&#39;s om aan te geven dat het bestand is alleen-lezen."

  "Image used in tab to indicate that the tab contains a difference view."
  "Afbeelding gebruikt in het tabblad om aan te geven dat het tabblad bevat een verschil uitzicht."

  "Image used in tab to indicate that the tab's file is readonly."
  "Afbeelding gebruikt in het tabblad om aan te geven dat het dossier van de tab is alleen-lezen."

  "Image used in tab to indicate that the tab’s file is locked."
  "Afbeelding gebruikt in het tabblad om aan te geven dat het dossier van de tab is vergrendeld."

  "Image used in tab which, when clicked, closes the tab."
  "Afbeelding gebruikt in de tab die, wanneer geklikt, sluit het tabblad."

  "License"
  "Licentie"

  "Line"
  "Regel"

  "Locked"
  "Afgesloten"

  "Move"
  "Verplaats"

  "Must be in multicursor mode to insert numbers"
  "Moet in multicursor modus nummers invoegen"

  "No write permissions.  Use '!' to force write."
  "Geen schrijfrechten.  Gebruik '!' te dwingen schrijven."

  "Release Type"
  "Release Type"

  "Reload file?"
  "Opnieuw laden"

  "Replace"
  "Vervangen"

  "Save request"
  "Sparen verzoek"

  "Show in Sidebar"
  "Show in Sidebar"

  "Starting number:"
  "Begin Pagina Nummer"

  "Tcl/Tk Version"
  "Tcl/Tk versie"

  "Total Characters"
  "Totale tekens"

  "Total Lines"
  "Totale lijnen"

  "Unable to successfully parse number string"
  "Kan niet met succes nummer tekenreeks parseren"

  "Unable to write file"
  "Kan niet schrijven bestand"

  "Version"
  "Versie"

}

# markers.tcl
msgcat::mcmset nl {

  "Marker name:"
  "Naam Marker:"

}

# menus.tcl
msgcat::mcmset nl {

  "About TKE"
  "Over TKE"

  "Absolute"
  "Absolue"

  "Align Cursors"
  "Uitlijnen van Cursors"

  "Append Next Occurrence"
  "Volgende vindplaats toevoegen"

  "Auto-Indent"
  "Automatisch inspringen"

  "Bubble Down"
  "Bubble omlaag"

  "Bubble Up"
  "Bubble Up"

  "Change Working Directory"
  "Wijzigen Working Directory"

  "Character"
  "Personages"

  "Check for Update"
  "Zoek naar nieuwe versies"

  "Classic Mac"
  "Klassieke Mac"

  "Clear All"
  "Alles wissen"

  "Close All"
  "Alles sluiten"

  "Close Current"
  "Huidig tabblad sluiten"

  "Command"
  "besturingssignaal"

  "Command Result"
  "Resultaat van de opdracht"

  "Copy"
  "Kopiëren"

  "Create"
  "Creëren"

  "Create at Current Line"
  "Maken op de huidige regel"

  "Current Line"
  "Huidige regel:"

  "Current Number"
  "Huidige rijnummer"

  "Current Word"
  "Huidige woord"

  "Cursor"
  "Muiscursor"

  "Cursor from Line Start"
  "Cursor vanaf begin van de lijn"

  "Cursor to Line End"
  "Cursor lijneinde"

  "Cut"
  "Knip"

  "Display Text Info"
  "Schermtekst"

  "Edit"
  "Bewerken"

  "Edit Language"
  "Bewerk Taal"

  "Edit Menu Edit user snippets"
  "Menu bewerken gebruiker fragmenten bewerken"

  "Edit Menu: Align cursors"
  "Bewerkingsmenu: Uitlijnen cursors"

  "Edit Menu: Bubble lines down one line"
  "Bewerkingsmenu: Bubble lijnen één regel naar beneden"

  "Edit Menu: Bubble lines up one line"
  "Bewerkingsmenu: Bubble lijnen een regel omhoog"

  "Edit Menu: Convert case to lower"
  "Bewerkingsmenu: Convert geval te verlagen"

  "Edit Menu: Convert case to title"
  "Bewerkingsmenu: Geval omzetten in titel"

  "Edit Menu: Convert case to upper"
  "Bewerkingsmenu: Geval omzetten in hoofdletters"

  "Edit Menu: Copy text"
  "Bewerkingsmenu: Tekst van het exemplaar"

  "Edit Menu: Cut text"
  "Bewerkingsmenu: Tekst knippen"

  "Edit Menu: Delete current line"
  "Bewerkingsmenu: Huidige regel verwijderen"

  "Edit Menu: Delete current word"
  "Bewerkingsmenu: Huidige woord verwijderen"

  "Edit Menu: Delete from cursor to end of line"
  "Bewerkingsmenu: Verwijderen van cursor tot einde van regel"

  "Edit Menu: Delete from start of line to cursor"
  "Bewerkingsmenu: Verwijderen uit begin van regel met de cursor"

  "Edit Menu: Delete template"
  ": Bewerken verwijderen menusjabloon"

  "Edit Menu: Delete text between character"
  "Bewerkingsmenu: Tekst tussen teken verwijderen"

  "Edit Menu: Delete the current number"
  "Bewerkingsmenu: Verwijdert u het huidige nummer"

  "Edit Menu: Delete the whitespace to left of cursor"
  "Bewerkingsmenu: De witruimte links van de cursor verwijderen"

  "Edit Menu: Delete the whitespace to right of cursor"
  "Bewerkingsmenu: De witruimte naar rechts van de cursor verwijderen"

  "Edit Menu: Edit language snippets"
  "Bewerkingsmenu: Edit taal fragmenten"

  "Edit Menu: Edit session current language preferences"
  "Bewerkingsmenu: Sessie huidige taalvoorkeuren bewerken"

  "Edit Menu: Edit session global preferences"
  "Bewerkingsmenu: Sessie globale voorkeuren bewerken"

  "Edit Menu: Edit template"
  "Bewerkingsmenu: Template bewerken"

  "Edit Menu: Edit user current language preferences"
  "Bewerkingsmenu: Gebruikersvoorkeuren voor de huidige taal bewerken"

  "Edit Menu: Edit user global preferences"
  "Bewerkingsmenu: Global Gebruikersvoorkeuren bewerken"

  "Edit Menu: Edit user menu bindings"
  "Bewerkingsmenu: Gebruiker menu bindingen bewerken"

  "Edit Menu: Format indentation for text"
  "Bewerkingsmenu: Opmaak inspringing van tekst"

  "Edit Menu: Indent selected text"
  "Bewerkingsmenu: Geselecteerde tekst laten inspringen"

  "Edit Menu: Insert command result after current line"
  "Bewerkingsmenu: Opdracht resultaat invoegen na de huidige regel"

  "Edit Menu: Insert file contents after current line"
  "Bewerkingsmenu: Bestandsinhoud invoegen na de huidige regel"

  "Edit Menu: Insert from clipboard"
  "Bewerkingsmenu: Invoegen uit klembord"

  "Edit Menu: Insert line above current line"
  "Bewerkingsmenu: Regel boven de huidige regel invoegen"

  "Edit Menu: Insert line below current line"
  "Bewerkingsmenu: Regel onder de huidige regel invoegen"

  "Edit Menu: Insert snippet"
  "Bewerkingsmenu: Invoegen fragment"

  "Edit Menu: Join lines"
  "Bewerkingsmenu: Joinlijnen"

  "Edit Menu: Move cursor to bottom of screen"
  "Bewerkingsmenu: Cursor verplaatsen naar onderkant van scherm"

  "Edit Menu: Move cursor to end of current line"
  "Bewerkingsmenu: Beweeg cursor naar het einde van de huidige regel"

  "Edit Menu: Move cursor to first line"
  "Bewerkingsmenu: Cursor verplaatsen naar de eerste regel"

  "Edit Menu: Move cursor to last line"
  "Bewerkingsmenu: Cursor verplaatsen naar laatste regel"

  "Edit Menu: Move cursor to middle of screen"
  "Bewerkingsmenu: Cursor verplaatsen naar het midden van het scherm"

  "Edit Menu: Move cursor to next page"
  "Bewerkingsmenu: Cursor verplaatsen naar volgende pagina"

  "Edit Menu: Move cursor to next word"
  "Bewerkingsmenu: Cursor verplaatsen naar het volgende woord"

  "Edit Menu: Move cursor to previous page"
  "Bewerkingsmenu: Cursor verplaatsen naar vorige pagina"

  "Edit Menu: Move cursor to previous word"
  "Bewerkingsmenu: Cursor verplaatsen naar het vorige woord"

  "Edit Menu: Move cursor to start of current line"
  "Bewerkingsmenu: Cursor verplaatsen naar het begin van de huidige regel"

  "Edit Menu: Move cursor to top of screen"
  "Bewerkingsmenu: Cursor naar de bovenkant van het scherm"

  "Edit Menu: Move multicursors down one line"
  "Bewerkingsmenu: Multicursors een regel omlaag gaan"

  "Edit Menu: Move multicursors left one line"
  "Bewerkingsmenu: Multicursors links Eén regel gaan"

  "Edit Menu: Move multicursors right one line"
  "Bewerkingsmenu: Verplaatsen multicursors rechtermuisknop één regel"

  "Edit Menu: Move multicursors up one line"
  "Bewerkingsmenu: Multicursors één regel naar boven verplaatsen"

  "Edit Menu: Paste and format text from clipboard"
  "Bewerkingsmenu: Plakken en indeling tekst vanaf klembord"

  "Edit Menu: Paste text from clipboard"
  "Bewerkingsmenu: Tekst vanaf klembord plakken"

  "Edit Menu: Redo"
  "Menu bewerken: opnieuw uitvoeren"

  "Edit Menu: Reload snippets"
  "Bewerkingsmenu: Reload fragmenten"

  "Edit Menu: Reload template information"
  "Bewerkingsmenu: Reload sjablooninformatie"

  "Edit Menu: Replace line with script"
  "Bewerkingsmenu: Regel vervangen door script"

  "Edit Menu: Select all text"
  "Bewerkingsmenu: Selecteer alle tekst"

  "Edit Menu: Set indent mode to IND"
  "Bewerkingsmenu: Streepje modus instelt op IND"

  "Edit Menu: Set indent mode to IND+"
  "Bewerkingsmenu: Streepje modus instelt op IND +"

  "Edit Menu: Set indent mode to OFF"
  "Bewerkingsmenu: Streepje modus ingesteld op OFF"

  "Edit Menu: Set user bindings to global bindings"
  "Bewerkingsmenu: Gebruiker serverbindingen instellen naar globale bindings"

  "Edit Menu: Set user preferences to global preferences"
  "Bewerkingsmenu: Gebruikersvoorkeuren naar algemene voorkeuren instellen"

  "Edit Menu: Toggle case of current character"
  "Bewerkingsmenu: Toggle geval van huidige karakter"

  "Edit Menu: Toggle comment"
  "Bewerkingsmenu: Toggle commentaar"

  "Edit Menu: Undo"
  "Menu bewerken: ongedaan maken"

  "Edit Menu: Unindent selected text"
  "Bewerkingsmenu: Geselecteerde tekst inspringen"

  "Edit Menu: View base preferences file"
  "Bewerkingsmenu: Basis voorkeurenbestand bekijken"

  "Edit Menu: View global menu bindings"
  "Bewerkingsmenu: Bekijken globaal menu bindingen"

  "Edit Session - Global"
  "Session - Global bewerken"

  "Edit Session - Language"
  "Session - taal bewerken"

  "Edit User"
  "Order bewerken"

  "Edit User - Global"
  "Bewerken gebruiker - Global"

  "Edit User - Language"
  "Bewerken gebruiker - taal"

  "Enumeration"
  "telling"

  "File"
  "Bestand"

  "File Contents"
  "file-inhoud"

  "File Menu: Change working directory"
  "Bestandsmenu: Verandering het werk folder"

  "File Menu: Close all tabs"
  "Bestandsmenu: Sluit alle tabbladen"

  "File Menu: Close current tab"
  "Bestandsmenu: Sluit huidige tabblad"

  "File Menu: Delete current file"
  "Bestandsmenu: Verwijder het huidige bestand"

  "File Menu: Duplicate current file"
  "Bestandsmenu: Huidige bestand dupliceren"

  "File Menu: Favorite file"
  "Bestandsmenu: Favoriet bestand"

  "File Menu: Lock file"
  "Bestandsmenu: Vergrendelingsbestand"

  "File Menu: New file"
  "Bestandsmenu: Nieuw bestand"

  "File Menu: New file from template"
  "Bestandsmenu: Nieuw bestand van sjabloon"

  "File Menu: New window"
  "Bestandsmenu: Nieuw venster"

  "File Menu: Open Favorite"
  "Bestandsmenu: Open favoriet"

  "File Menu: Open Recent"
  "Beeld Inspecteur tonen"

  "File Menu: Open directory"
  "Bestandsmenu: Open Folder"

  "File Menu: Open file"
  "Bestandsmenu: Open bestand"

  "File Menu: Quit application"
  "Bestandsmenu: Toepassing afsluiten"

  "File Menu: Rename current file"
  "Bestandsmenu: Huidige bestand hernoemen"

  "File Menu: Reopen current file"
  "Bestandsmenu: Huidige bestand opnieuw te openen"

  "File Menu: Save all files"
  "Bestandsmenu: Alle bestanden opslaan"

  "File Menu: Save file"
  "Bestandsmenu: Bestand opslaan"

  "File Menu: Save file as"
  "Bestandsmenu: Bestand opslaan als"

  "File Menu: Save file as template"
  "Bestandsmenu: Bestand opslaan als sjabloon"

  "File Menu: Save selected lines"
  "Bestandsmenu: Opslaan geselecteerde lijnen"

  "File Menu: Set current file line ending to CR for Classic Mac"
  "Bestandsmenu: Set huidige bestand regel die eindigt CR voor klassieke Mac"

  "File Menu: Set current file line ending to CRLF for Windows"
  "Bestandsmenu: Set huidige bestand regel die eindigt naar CRLF voor Windows"

  "File Menu: Set current file line ending to LF for Unix"
  "Bestandsmenu: Set huidige bestand regel die eindigt om LF voor Unix"

  "File Menu: Show file difference"
  "Bestandsmenu: Toon bestand verschil"

  "File Menu: Unfavorite file"
  "Bestandsmenu: Unfavorite bestand"

  "File Menu: Unlock file"
  "Bestandsmenu: Ontgrendelen bestand"

  "Find In Files"
  "Zoeken in bestanden..."

  "Find Matching Pair"
  "Vinden Matching paar"

  "Find Menu: Append next occurrence"
  "Menu zoeken: Append volgende vindplaats"

  "Find Menu: Create marker at current line"
  "Menu zoeken: Marker op de huidige regel maken"

  "Find Menu: Find"
  "Menu zoeken: zoeken"

  "Find Menu: Find and Replace"
  "Menu zoeken: Zoeken en vervangen"

  "Find Menu: Find in files"
  "Menu zoeken: Zoeken in bestanden"

  "Find Menu: Find matching character pair"
  "Menu zoeken: Overeenkomende teken paar zoeken"

  "Find Menu: Find next occurrence"
  "Menu zoeken: Volgende exemplaar zoeken"

  "Find Menu: Find previous occurrence"
  "Menu zoeken: Vorige exemplaar zoeken"

  "Find Menu: Goto next difference"
  "Menu zoeken: Goto volgende verschil"

  "Find Menu: Goto previous difference"
  "Menu zoeken: Goto vorige verschil"

  "Find Menu: Jump backward"
  "Menu zoeken: Achteruit springen"

  "Find Menu: Jump forward"
  "Menu zoeken: Sprong voorwaarts"

  "Find Menu: Jump to line"
  "Menu zoeken: Ga naar regel"

  "Find Menu: Remove all markers"
  "Menu zoeken: Verwijder alle markeertekens"

  "Find Menu: Remove marker from current line"
  "Menu zoeken: Marker verwijderen uit de huidige regel"

  "Find Menu: Select all occurrences"
  "Menu zoeken: Selecteer alle exemplaren"

  "Find Menu: Show selected line change"
  "Menu zoeken: Toon geselecteerde lijn wijzigen"

  "Find and Replace"
  "Zoeken en vervangen"

  "Format Text"
  "Tekst opmaken"

  "From Clipboard"
  "Van klembord"

  "Goto Last Tab"
  "Goto Last Tab"

  "Goto Next Tab"
  "Goto Volgende Tab"

  "Goto Other Pane"
  "Goto Andere Pane"

  "Goto Previous Tab"
  "Ga naar vorig tabblad"

  "Help"
  "Help"

  "Help Menu: About TKE"
  "Menu Help: Over TKE"

  "Help Menu: Check for update"
  "Helpmenu: Controle voor update"

  "Help Menu: Send bug report"
  "Helpmenu: Bugrapport verzenden"

  "Help Menu: Send feedback"
  "Helpmenu: Feedback verzenden"

  "Help Menu: View user guide"
  "Helpmenu: Weergave gebruikershandleiding"

  "Hide Console"
  "Verbergen Console"

  "Hide Line Numbers"
  "Regelnummers verbergen"

  "Hide Marker Map"
  "Marker kaart verbergen"

  "Hide Meta Characters"
  "Verbergen metakarakters"

  "Hide Sidebar"
  "Zijbalk verbergen"

  "Hide Status Bar"
  "Verberg Status Bar"

  "Hide Tab Bar"
  "Hide Tab Bar"

  "Indent"
  "Inspringen"

  "Indent Off"
  "Streepje uit"

  "Indentation"
  "inkerving"

  "Insert"
  "Invoegen"

  "Install"
  "Installeer"

  "Join Lines"
  "Regels samenvoegen"

  "Jump Backward"
  "Spring achteruit"

  "Jump Forward"
  "Spring vooruit"

  "Jump To Line"
  "Ga naar regel"

  "Launcher"
  "Launcher"

  "Line Above Current"
  "Lijn boven de huidige"

  "Line Below Current"
  "Regel onder huidige"

  "Line Ending"
  "Einde van de lijn"

  "Line Number"
  "Regelnummer"

  "Line Numbering"
  "Regelnummering"

  "Lock"
  "Vergrendelen"

  "Lower Case"
  "Kleineletters"

  "Markers"
  "markeerders"

  "Menu Bindings"
  "Menu Bindingen"

  "Menus: About TKE"
  "Menu's: Over TKE"

  "Merge Panes"
  "Samenvoegen van deelvensters"

  "Move Cursors Down"
  "Cursors omlaag"

  "Move Cursors Left"
  "Cursors links verplaatsen"

  "Move Cursors Right"
  "Cursors rechts bewegen"

  "Move Cursors Up"
  "Cursors omhoog"

  "Move to First Line"
  "Ga naar eerste regel"

  "Move to Last Line"
  "Verplaatsen naar laatste regel"

  "Move to Line End"
  "Verplaats naar einde lijn"

  "Move to Line Start"
  "Verplaats naar begin lijn"

  "Move to Next Page"
  "Verplaatsen naar volgende pagina"

  "Move to Next Word"
  "Naar het volgende woord verplaatsen"

  "Move to Previous Page"
  "Verplaatsen naar vorige pagina"

  "Move to Previous Word"
  "Naar het vorige woord verplaatsen"

  "Move to Screen Bottom"
  "Naar de onderkant van het scherm verplaatsen"

  "Move to Screen Middle"
  "Verplaatsen naar het midden van het scherm"

  "Move to Screen Top"
  "Naar de bovenkant van het scherm verplaatsen"

  "New From Template"
  "Nieuw van sjabloon"

  "New Window"
  "Nieuw Venster"

  "Next Difference"
  "Volgend verschil"

  "Open Directory"
  "Map openen"

  "Open Favorite"
  "Open Favorite"

  "Open File"
  "Bestand openen"

  "Open Recent"
  "Recent geopend"

  "Paste"
  "Pasta"

  "Paste and Format"
  "Plak en Format"

  "Plugins"
  "Plug-in"

  "Plugins Menu: Create new plugin"
  "Plugins Menu: Maak nieuwe plugin"

  "Plugins Menu: Install plugin"
  "Plugins Menu: Installeren plugin"

  "Plugins Menu: Reload all plugins"
  "Plugins Menu: Herladen alle plugins"

  "Plugins Menu: Uninstall plugin"
  "Plugins Menu: Verwijderen plugin"

  "Preferences"
  "Voorkeuren"

  "Previous Difference"
  "Vorig verschil"

  "Profiling Report Sorted By"
  "Profilering verslag gesorteerd"

  "Profiling started"
  "Profiling begonnen"

  "Profiling stopped"
  "Profiling gestopt"

  "Quit"
  "Ophouden"

  "Redo"
  "Opnieuw"

  "Relative"
  "Relatief"

  "Reload"
  "Herladen"

  "Remove All Markers"
  "Alle markeringen verwijderen"

  "Remove From Current Line"
  "Verwijderen uit de huidige regel"

  "Reopen File"
  "Bestand opnieuw te openen"

  "Replace Line With Script"
  "Regel vervangen door Script"

  "Reset User to Base"
  "Reset gebruiker naar Base"

  "Restart TKE"
  "Opnieuw opstarten van TKE"

  "Run BIST"
  "BIST uitvoeren"

  "Save All"
  "Alles opslaan"

  "Save As Template"
  "opslaan als sjabloon"

  "Save Current"
  "Opslaan van de huidige"

  "Save Selection As"
  "Opslaan Keuze"

  "Select All"
  "Alles selecteren"

  "Select All Occurrences"
  "Selecteer alle exemplaren"

  "Select Next Occurrence"
  "Selecteer volgende vindplaats"

  "Select Previous Occurrence"
  "Selecteer vorige exemplaar"

  "Send Bug Report"
  "Bugrapport verzenden."

  "Send Feedback"
  "Feedback verzenden"

  "Sessions"
  "Sessies"

  "Sessions Menu: Close current session"
  "Sessies Menu: Huidige sessie sluiten"

  "Sessions Menu: Delete session"
  "Sessies Menu: Delete sessie"

  "Sessions Menu: Save current session"
  "Sessies Menu: Sla huidige sessie"

  "Sessions Menu: Save sessions as"
  "Sessies Menu: Opslaan als zittingen"

  "Sessions Menu: Switch to session"
  "Sessies Menu: Overschakelen naar sessie"

  "Set Syntax"
  "Stel Syntax"

  "Set Theme"
  "Serie Thema"

  "Set User to Global"
  "Gebruiker instellen naar globaal"

  "Show Console"
  "Show Console"

  "Show Diagnostic Logfile"
  "Toon diagnostische Logfile"

  "Show File Difference"
  "Toon bestand verschil"

  "Show Last Profiling Report"
  "Toon Laatste Profiling Report"

  "Show Line Numbers"
  "Regelnummering tonen"

  "Show Marker Map"
  "Marker Toon kaart"

  "Show Meta Characters"
  "Toon metakarakters"

  "Show Selected Line Change"
  "Toon geselecteerde lijn wijzigen"

  "Show Sidebar"
  "Zijbalk tonen"

  "Show Status Bar"
  "Statusbalk tonen"

  "Show Tab Bar"
  "Show Tab Bar"

  "Smart Indent"
  "Slimme streepje"

  "Snippet"
  "Snippet"

  "Snippets"
  "Snippets"

  "Sort Tabs"
  "Sorteren Tabs"

  "Start Profiling"
  "Start Profiling"

  "Stop Profiling"
  "Stop Profiling"

  "Switch To"
  "Overschakelen naar"

  "Tabs"
  "Tab"

  "Templates"
  "Templates"

  "Text Between Character"
  "Tekst tussen karakter"

  "Text Menu: Insert enumeration"
  "Tekstmenu: Invoegen (opsomming)"

  "Title Case"
  "Titel Hoofd/Kleineletters"

  "Toggle Case"
  "Toggle zaak"

  "Toggle Comment"
  "Knevel commentaar"

  "Tools"
  "hulpmiddelen;"

  "Tools Menu: Disable Vim mode"
  "Menu Extra: Vim modus uitschakelen"

  "Tools Menu: Enable Vim mode"
  "Menu Extra: Vim modus inschakelen"

  "Tools Menu: Restart TKE"
  "Menu Extra: Herstart TKE"

  "Tools Menu: Run BIST"
  "Menu Extra: Run BIST"

  "Tools Menu: Run theme editor"
  "Menu Extra: Run theme editor"

  "Tools Menu: Show diagnostic logfile"
  "Menu Extra: Toon diagnostische logfile"

  "Tools Menu: Show last profiling report"
  "Menu Extra: Toon laatste profilering verslag"

  "Tools Menu: Start profiling"
  "Menu Extra: Start profilering"

  "Tools Menu: Stop profiling"
  "Menu Extra: Stop profilering"

  "Transform"
  "Transformeren"

  "Undo"
  "Ongedaan maken"

  "Unindent"
  "Laten terugspringen"

  "Uninstall"
  "Deïnstalleren"

  "Unix"
  "Unix"

  "Unlock"
  "Ontgrendelen"

  "Upper Case"
  "bovenkast"

  "User Guide"
  "Gebruikershandleiding"

  "View"
  "Bekijken"

  "View Base"
  "Weergave Base"

  "View Global"
  "Weergave Global"

  "View Menu: Absolute line numbering"
  "Menu Beeld: Absolute lijn nummering"

  "View Menu: Display text information"
  "Menu Beeld: Tekstinformatie weergeven"

  "View Menu: Goto last tab"
  "Menu Beeld: Goto laatste tabblad"

  "View Menu: Goto next tab"
  "Menu Beeld: Goto volgende tabblad"

  "View Menu: Goto other pane"
  "Menu Beeld: Goto andere deelvenster"

  "View Menu: Goto previous tab"
  "Menu Beeld: Goto vorige tabblad"

  "View Menu: Hide console"
  "Menu Beeld: Verbergen console"

  "View Menu: Hide line numbers"
  "Menu Beeld: Verbergen regelnummers"

  "View Menu: Hide marker map"
  "Menu Beeld: Verbergen marker kaart"

  "View Menu: Hide meta characters"
  "Menu Beeld: Verbergen metakarakters"

  "View Menu: Hide sidebar"
  "Menu Beeld: Verbergen sidebar"

  "View Menu: Hide status bar"
  "Menu Beeld: Statusbalk te verbergen"

  "View Menu: Hide tab bar"
  "Menu Beeld: Hide tab bar"

  "View Menu: Merge panes"
  "Menu Beeld: Samenvoegen deelvensters"

  "View Menu: Move to other pane"
  "Menu Beeld: Verplaatsen naar andere deelvenster"

  "View Menu: Relative line numbering"
  "Menu Beeld: Relatieve regelnummering"

  "View Menu: Show console"
  "Menu Beeld: Toon console"

  "View Menu: Show line numbers"
  "Menu Beeld: Regelnummers weergeven"

  "View Menu: Show marker map"
  "Menu Beeld: Toon marker kaart"

  "View Menu: Show meta characters"
  "Menu Beeld: Toon metakarakters"

  "View Menu: Show sidebar"
  "Beeld Basisdia"

  "View Menu: Show status bar"
  "Menu Beeld: Toon statusbalk"

  "View Menu: Show tab bar"
  "Menu Beeld: Toon tabbalk"

  "View Menu: Sort tabs"
  "Menu Beeld: Sort tabs"

  "View Menu: Toggle split view mode"
  "Menu Beeld: Toggle splitsen weergavemodus"

  "Vim Mode"
  "Vim Mode"

  "Whitespace Backward"
  "Whitespace achteruit"

  "Whitespace Forward"
  "Whitespace Forward"

  "Windows"
  "Windows"

}

# plugins.tcl
msgcat::mcmset nl {

  "Always grant from developer"
  "Verlenen altijd van ontwikkelaar"

  "ERROR"
  "FOUT"

  "ERROR:  Plugin name already exists"
  "FOUT: Plugin naam al bestaat"

  "ERROR:  Plugin name is not valid (only alphanumeric and underscores are allowed)"
  "FOUT: Plugin naam is niet geldig (alleen alfanumerieke en underscores zijn toegestaan)"

  "ERROR:  Unable to create plugin directory"
  "FOUT: Kan plugin directory"

  "ERROR:  Unable to write plugin files"
  "FOUT: Kan plugin bestanden weg te schrijven"

  "Enter plugin name"
  "Voer plugin naam"

  "Grant"
  "Grant"

  "Grant permssion?"
  "Grant permssion?"

  "OK"
  "OK"

  "Plugin Errors"
  "Plugin fouten"

  "Plugin Trust Requested"
  "Plugin Trust Gevraagde"

  "Plugin installed"
  "Plugin geïnstalleerd"

  "Plugin requires permission to view or modify your system."
  "Plugin toestemming om te bekijken of uw systeem te wijzigen."

  "Plugin uninstalled"
  "Plugin verwijderd"

  "Plugins successfully reloaded"
  "Plugins succes vernieuwd"

  "Reject"
  "Afwijzen"

  "Syntax errors found in selected plugins"
  "Syntax fouten gevonden in geselecteerde plugins"

}

# search.tcl
msgcat::mcmset nl {

  "No files found in specified directories"
  "Geen bestanden gevonden in de opgegeven mappen"

  "No search results found"
  "﻿Geen resultaten gevonden..."

  "Search wrapped to beginning of file"
  "Zoek verpakt aan begin van bestand"

  "Search wrapped to end of file"
  "Zoek verpakt op einde van het bestand"

  "substitutions done"
  "vervangingen gedaan"

}

# sessions.tcl
msgcat::mcmset nl {

  "Save session?"
  "Sessie opslaan?"

  "Session state will be lost if not saved"
  "Sessie staat zullen verloren gaan als niet opgeslagen"

}

# sidebar.tcl
msgcat::mcmset nl {

  "Add Parent Directory"
  "Bovenliggende map"

  "Close Directory Files"
  "Sluiten Directory Bestanden"

  "Copy Pathname"
  "Padnaam kopiëren"

  "Delete directories?"
  "Verwijder mappen?"

  "Delete directory?"
  "Delete directory?"

  "Delete file?"
  "Bestand verwijderen"

  "Delete files?"
  "Bestanden verwijderen"

  "Directory Name:"
  "directory-naam"

  "Folder Name:"
  "Mapnaam:"

  "Image displayed in sidebar to indicate that a file is currently opened in an editing buffer."
  "Afbeelding in zijbalk geven dat actueel in een editing buffer wordt geopend."

  "Make Current Working Directory"
  "Make Current Working Directory"

  "New Directory"
  "Nieuwe directory"

  "New File From Template"
  "Nieuw van sjabloon"

  "Open Directory Files"
  "Open Directory Bestanden"

  "Refresh Directory Files"
  "Vernieuwen Directory Bestanden"

  "Remove Parent from Sidebar"
  "Verwijder Parent uit Sidebar"

  "Remove from Sidebar"
  "Verwijderen uit Sidebar"

  "Show Difference"
  "Toon verschil"

}

# snippets.tcl
msgcat::mcmset nl {

  "Snippet: *"
  "Snippet: *"

}

# syntax.tcl
msgcat::mcmset nl {

  "Syntax"
  "Syntaxis"

  "Syntax error in syntax file"
  "Syntaxisfout in syntaxis bestand"

}

# templates.tcl
msgcat::mcmset nl {

  "Template"
  "Template"

  "Template Name"
  "Template Naam"

  "deleted"
  "Verwijderd"

  "saved"
  "Opgeslagen."

}

# theme.tcl
msgcat::mcmset nl {

  "Background (trough) color used in the sidebar scrollbar."
  "Achtergrond (dal) kleur gebruikt in de zijbalk scrollbar."

  "Background (trough) color used in the text scrollbars."
  "Achtergrond (dal) kleur die wordt gebruikt in de tekst schuifbalken."

  "Background color for all sidebar items that are not selected."
  "Achtergrondkleur voor alle sidebar items die niet zijn geselecteerd."

  "Background color for all sidebar items that are selected."
  "Achtergrondkleur voor alle sidebar items die zijn geselecteerd."

  "Background color in difference viewer that shows added lines."
  "Achtergrondkleur in verschil viewer die toegevoegde lijnen toont."

  "Background color in difference viewer that shows deleted lines."
  "Achtergrondkleur in verschil viewer die verwijderde lijnen toont."

  "Background color of insertion cursor and background marker colors."
  "Achtergrondkleur van het inbrengen cursor en achtergrond marker kleuren."

  "Background color of the editing buffer."
  "Achtergrondkleur van de editing buffer."

  "Background color to display when a button-like ttk widget is pressed."
  "Achtergrondkleur wordt weergegeven wanneer een knop-achtige TTK widget wordt gedrukt."

  "Background color to use for selected text."
  "Achtergrondkleur te gebruiken voor geselecteerde tekst."

  "Background color used for all other tabs that are not the current/active tab in the tabbar."
  "Achtergrondkleur gebruikt voor alle andere tabbladen die niet de huidige / actieve tab in de tabbalk."

  "Background color used for the current/active menu item."
  "Achtergrondkleur gebruikt voor de huidige / actieve menu-item."

  "Background color used for the current/active tab in the tabbar."
  "Achtergrondkleur gebruikt voor de huidige / actieve tab in de tabbalk."

  "Background color used in highlighted text."
  "Achtergrondkleur gebruikt in de gemarkeerde tekst."

  "Background color used in menus."
  "Achtergrondkleur gebruikt in de menu&#39;s."

  "Background color used in the tabbar area."
  "Achtergrondkleur gebruikt in de tabbalk omgeving."

  "Color of border drawn around active editing buffer."
  "Kleur van de grens getrokken rond actieve bewerking buffer."

  "Color of ttk entry widget text border when the entry has keyboard focus."
  "Kleur van TTK binnenkomst widget tekst grens wanneer de invoer heeft toetsenbord focus."

  "Color used to draw the warning width line in the editing buffer (as well as the line separating the gutter from the editing buffer)."
  "Kleur gebruikt om de waarschuwing breedte regel in de editing buffer (evenals de lijn tussen de goot van de redactie buffer) te trekken."

  "Default 'darkcolor' for all ttk widgets."
  "Default &#39;darkcolor&#39; voor alle TTK widgets."

  "Default background color to use for all ttk widgets that are in a disabled state."
  "Standaard achtergrondkleur te gebruiken voor alle ttk widgets die zich in een uitgeschakelde toestand."

  "Default background color to use for all ttk widgets when the mouse cursor hovers over the widget."
  "Standaard achtergrondkleur te gebruiken voor alle TTK widgets wanneer de muis cursor over de widget zweeft."

  "Default background color to use for all ttk widgets."
  "Standaard achtergrondkleur te gebruiken voor alle TTK widgets."

  "Default border color for all ttk widgets."
  "Standaard randkleur voor alle TTK widgets."

  "Default color for non-syntax highlighted text."
  "Standaardkleur voor niet-syntax gemarkeerde tekst."

  "Default foreground text color to use for all ttk widgets that are in a disabled state."
  "Standaard voor- tekstkleur te gebruiken voor alle ttk widgets die zich in een uitgeschakelde toestand."

  "Default foreground text color to use for all ttk widgets."
  "Standaard voor- tekstkleur te gebruiken voor alle TTK widgets."

  "Determines the number of grips strips to display in the grip area between resizable panes."
  "Bepaalt het aantal grepen strips weer te geven in de greep gebied tussen resizable ruiten."

  "Determines the thickness of the grip area between resizable panes."
  "Bepaalt de dikte van de grip tussen resizable ruiten."

  "ERROR:  Unable to read"
  "Fout: kan ruw bestand niet lezen"

  "Foreground (slider) color used in the sidebar scrollbar."
  "Voorgrond (schuif) kleur gebruikt in de zijbalk scrollbar."

  "Foreground (slider) color used in the text scrollbars."
  "Voorgrond (schuif) kleur die wordt gebruikt in de tekst schuifbalken."

  "Foreground color used in menu items with checks or buttons."
  "Voorgrondkleur die wordt gebruikt in menu-items met cheques of knoppen."

  "Foreground text color for strings."
  "Voorgrond tekstkleur voor strijkers."

  "Foreground text color to use for all miscellaneous1 labeled text."
  "Voorgrond tekstkleur te gebruiken voor alle miscellaneous1 gelabelde tekst."

  "Foreground text color to use for all miscellaneous2 labeled text."
  "Voorgrond tekstkleur te gebruiken voor alle miscellaneous2 gelabelde tekst."

  "Foreground text color to use for all miscellaneous3 labeled text."
  "Voorgrond tekstkleur te gebruiken voor alle miscellaneous3 gelabelde tekst."

  "Foreground text color to use for comments."
  "Voorgrond tekstkleur te gebruiken voor commentaar."

  "Foreground text color to use for displaying line numbers."
  "Voorgrond tekstkleur te gebruiken voor het tonen van regelnummers."

  "Foreground text color to use for displaying numbers."
  "Voorgrond tekstkleur te gebruiken voor de weergave van getallen."

  "Foreground text color to use for language-specific keywords."
  "Voorgrond tekstkleur te gebruiken voor de taal-specifieke zoekwoorden."

  "Foreground text color to use for language-specific punctuation."
  "Voorgrond tekstkleur te gebruiken voor de taal-specifieke interpunctie."

  "Foreground text color to use for meta syntax."
  "Voorgrond tekstkleur te gebruiken voor de meta-syntax."

  "Foreground text color to use for precompiler syntax."
  "Voorgrond tekstkleur te gebruiken voor precompiler syntax."

  "Foreground text color to use for selected text."
  "Voorgrond tekstkleur te gebruiken voor geselecteerde tekst."

  "Foreground text color used for all other tabs that are not the current/active tab in the tabbar."
  "Voorgrond tekstkleur die wordt gebruikt voor alle andere tabbladen die niet de huidige/actieve tabblad in de tabbar zijn."

  "Foreground text color used for menus item that are disabled."
  "Voorgrond tekstkleur die wordt gebruikt voor het menu-item dat een handicap."

  "Foreground text color used for the current/active menu item."
  "Voorgrond tekstkleur die wordt gebruikt voor de huidige / actieve menu-item."

  "Foreground text color used for the current/active tab in the tabbar."
  "Voorgrond tekstkleur die wordt gebruikt voor de huidige/actieve tab in de tabbar."

  "Foreground text color used in menus."
  "Voorgrond tekstkleur gebruikt in de menu&#39;s."

  "Foreground text/image color used in tabbar and tabs."
  "Voorgrond tekst / afbeelding kleur gebruikt in de tabbalk en tabs."

  "Images"
  "Afbeeldingen"

  "Maximum thickness of the text scrollbar when it is active."
  "Maximale dikte van de tekst schuifbalk wanneer deze actief is."

  "Maximum thickness of the text scrollbars when they are active."
  "Maximale dikte van de tekst schuifbalken wanneer deze actief zijn."

  "Menu Options"
  "Menuopties"

  "Menu relief value."
  "Menu opluchting waarde."

  "Pixel height of the tabbar widget."
  "Pixel hoogte van de tabbalk widget."

  "Relief used in drawing the tabs."
  "Relief gebruikt bij het opstellen van de tabbladen."

  "Relief value of the sidebar area."
  "Reliëf waarde van de zijbalk gebied."

  "Sidebar Options"
  "Opslaan"

  "Sidebar Scrollbar Options"
  "Zijbalk Scrollbar Opties"

  "Specifies the color to display around the sidebar when the sidebar does not have the focus."
  "Geeft de kleur weer te geven rond de zijbalk wanneer de zijbalk niet de focus hebben."

  "Specifies the color to display around the sidebar when the sidebar has the focus."
  "Geeft de kleur weer te geven rond de zijbalk wanneer de zijbalk de focus heeft."

  "Specifies the default background color to use for text that is selected in a standard ttk widget (this does not include the editing buffer)."
  "Bepaalt de standaard achtergrondkleur gebruiken voor de tekst die is geselecteerd in een standaard TTK widget (dit omvat niet het bewerken buffer)."

  "Specifies the default foreground text color to use for text that is selected in a standard ttk widget (this does not include the editing buffer)."
  "Specificeert de standaard voorgrond tekstkleur te gebruiken voor de tekst die is geselecteerd in een standaard TTK widget (dit omvat niet het bewerken buffer)."

  "Specifies the default relief to use when drawing ttk widgets."
  "Hiermee wordt de standaard verlichting te gebruiken bij het opstellen TTK widgets."

  "Specifies the disclosure image style to use in the sidebar."
  "Specificeert de openbaarmaking stijl beeld te gebruiken in de zijbalk."

  "Specifies the pixel thickness of the highlight line."
  "Specificeert de pixel dikte van het hoogtepunt lijn."

  "Syntax Colors"
  "Syntax Kleuren"

  "Tab Options"
  "Tabblad Opties"

  "Text Scrollbar Options"
  "Tekst Scrollbar Opties"

  "Text color for all sidebar items that are not selected."
  "Tekstkleur voor alle sidebar items die niet zijn geselecteerd."

  "Text color for all sidebar items that are selected."
  "Tekstkleur voor alle sidebar items die zijn geselecteerd."

  "ttk Widget Colors"
  "TTK Widget Kleuren"

}

# themer.tcl
msgcat::mcmset nl {

  "   Show All"
  "Toon alle statussen"

  "   Show Category"
  "Categorie weergeven"

  "   Show Color"
  "Toon Kleur"

  "   Show Selected Option"
  "Toon geselecteerde optie"

  "   Show Selected Value"
  "Toon geselecteerde waarde"

  "Categories"
  "Categorieën"

  "Change Base Color"
  "Change Base Color"

  "Choose Theme"
  "Kies thema"

  "Custom Directory"
  "Aangepaste Map"

  "Custom..."
  "Eigen CSS"

  "Delete swatch?"
  "Delete staal?"

  "Description"
  "Beschrijving"

  "Details"
  "Details"

  "Done"
  "Klaar"

  "Export"
  "Exporteer"

  "GIF Photo"
  "GIF Photo"

  "Import"
  "Invoer"

  "Import BMP Data"
  "Gegevens importeren"

  "Import BMP Mask"
  "Importeer BMP Mask"

  "Import Error"
  "Import Error"

  "Import Theme File"
  "Importeer thema"

  "Installation Directory"
  "Installatie Gids"

  "Modifications"
  "Wijzigingen"

  "One-Color Bitmap"
  "One-Color Bitmap"

  "Preview"
  "Voorvertoning"

  "Relief: "
  "Relief"

  "Save As:"
  "Opslaan als"

  "Save theme changes?"
  "Opslaan thema veranderingen?"

  "Select Directory"
  "Kies Directory"

  "Swatch"
  "Staal"

  "Swatch Colors"
  "Swatch Kleuren"

  "Table Filters"
  "Tabel Filters"

  "The current theme has unsaved changes"
  "De huidige thema heeft opgeslagen wijzigingen"

  "Tree Style: "
  "Boom Stijl:"

  "Two-Color Bitmap"
  "Twee-Color Bitmap"

  "User Directory"
  "Gebruikersmap"

  "Value"
  "Een record matching '%value%' is gevonden."

  "Value: "
  "Waarde:"

}

# themes.tcl
msgcat::mcmset nl {

  "Theme"
  "Thema"

  "Theme:*"
  "Thema"

}

# tke.tcl
msgcat::mcmset nl {

  "Import TKE theme?"
  "Importeer thema"

  "Import TextMate theme?"
  "Importeer TextMate thema?"

}

# tkedat.tcl
msgcat::mcmset nl {

  "Unable to read"
  "Kan niet lezen"

}

# vim.tcl
msgcat::mcmset nl {

  "File format unrecognized"
  "Bestandsindeling niet herkend"

  "Filename directory does not exist"
  "Bestandsnaam directory bestaat niet"

  "Illegal modelines value"
  "Illegale modelines waarde"

  "Number width not a number"
  "Nummer breedte niet een nummer"

  "Shiftwidth value is not an integer"
  "Shiftwidth waarde is geen geheel getal."

  "Tabstop value is not an integer"
  "Tabstop waarde is geen geheel getal."

  "Unrecognized vim option"
  "Niet-herkende vim optie"

}

# General
msgcat::mcmset nl {

  "Cancel"
  "Annuleren"

  "Close"
  "Sluiten"

  "Delete"
  "Verwijderen"

  "Duplicate"
  "Dupliceren"

  "Favorite"
  "Favoriet"

  "File Name:"
  "Bestandsnaam:"

  "Find"
  "Query"

  "Move to Other Pane"
  "Verplaatsen naar andere Pane"

  "New File"
  "Nieuw bestand"

  "None"
  "Geen"

  "Open"
  "Openen"

  "Rename"
  "Hernoem"

  "Save"
  "Opslaan"

  "Save As"
  "Opslaan als"

  "Split View"
  "Venster opsplitsen"

  "Theme Editor"
  "Thema-editor"

  "Unable to write"
  "Niet in staat om te schrijven"

  "Unfavorite"
  "Unfavorite"

}

