# api.tcl
msgcat::mcmset no {

  "Argument list to api::add_file was not an even key/value pair"
  "Argument liste til api :: add_file var ikke en enda nøkkel / verdi-par"

  "Argument list to api::add_file was not in the form 'filename [<option> <value>]*'"
  "Argument liste til api :: add_file var ikke i form filnavn [ <option><value> ] * &#39;"

  "get_home_directory can only be called within plugin code"
  "get_home_directory kan bare kalles innenfor plugin-kode"

}

# bgproc.tcl
msgcat::mcmset no {

  "Unable to run system command (%s)"
  "Kan ikke kjøre systemkommando (% s)"

}

# gui.tcl
msgcat::mcmset no {

  "%s, Line: %d, Column: %d"
  "% S, Line:% d, Kolonne:% d"

  "Close All Tabs"
  "Lukk alle faner"

  "Close Other Tab(s)"
  "Lukk Other Tab (s)"

  "Close Other*"
  "Lukk Annet *"

  "Close Tab"
  "Lukk fane"

  "Copyright %d-%d"
  "Copyright% d-% d"

  "Delete tab?"
  "Slett fane?"

  "Developer:"
  "Utvikler"

  "Email:"
  "E-post:"

  "File attribute (%s) does not exist"
  "File attributt (% s) eksisterer ikke"

  "File index is out of range"
  "File indeksen er utenfor rekkevidde"

  "Line: %d, Column: %d"
  "Linje:% d, Kolonne:% d"

  "Locked"
  "låst"

  "Move to Other Pane"
  "Flytt til Annen Pane"

  "Move*"
  "flytte"

  "Reload file?"
  "Last filen?"

  "Save request"
  "Be"

  "Total Lines: %d, Total Characters: %d"
  "Totalt antall linjer:% d, Totalt antall tegn:% d"

  "Unable to find current file (tab: %s)"
  "Å finne aktuelle filen klarer (tab:% s)"

  "Untitled"
  "Untitled"

  "Version:"
  "Versjon"

}

# markers.tcl
msgcat::mcmset no {

  "Marker name:"
  "Marker navn:"

}

# menus.tcl
msgcat::mcmset no {

  "                                  Profiling Report Sorted By (%s)"
  "Profilering Rapporter Sorted By (% s)"

  "About TKE"
  "Om TKE"

  "Align cursors"
  "Juster pekere"

  "All"
  "Alle"

  "Append next occurrence"
  "Tilføy neste forekomst"

  "Clear All"
  "Fjern alle"

  "Close All"
  "Lukk alle"

  "Comment"
  "Kommentar"

  "Copy"
  "Kopier"

  "Create new..."
  "Opprett ny ..."

  "Create..."
  "frambringe"

  "Cut"
  "Kutt"

  "Edit"
  "Edit"

  "Edit user"
  "Rediger bruker"

  "Edit..."
  "Edit"

  "File"
  "Fil"

  "Find"
  "Søk"

  "Find and Replace"
  "Finn og erstatt"

  "Find in files"
  "Finner i filer"

  "Find marker"
  "Finn markør"

  "Find matching pair"
  "Finn matchende par"

  "Format Text"
  "Formater tekst"

  "Goto Last Tab"
  "Gå Siste Tab"

  "Goto Next Tab"
  "Gå til neste fane"

  "Goto Other Pane"
  "Gå til Annen Pane"

  "Goto Previous Tab"
  "Gå til forrige fane"

  "Help"
  "Help!"

  "Hide Console"
  "Skjul Console"

  "Hide Sidebar"
  "Skjul Sidebar"

  "Hide Status Bar"
  "Skjul Status Bar"

  "Hide Tab Bar"
  "Skjul Tab Bar"

  "Import TextMate theme..."
  "Import Textmate tema ..."

  "Indent"
  "innrykk"

  "Insert enumeration"
  "Sett oppregning"

  "Install..."
  "installere"

  "Launcher"
  "Launcher"

  "Lock"
  "Lås"

  "Menu Bindings"
  "Meny Bindinger"

  "Menu: About TKE"
  "Meny: Om TKE"

  "Menu: Align cursors"
  "Meny: Rett pekere"

  "Menu: Append next occurrence"
  "Meny: Legg ved neste forekomst"

  "Menu: Close all tabs"
  "Meny: Lukk alle faner"

  "Menu: Close current tab"
  "Meny: Lukk gjeldende fane"

  "Menu: Comment selected text"
  "Meny: Kommentar markert tekst"

  "Menu: Copy selected text"
  "Meny: Kopiere merket tekst"

  "Menu: Create new plugin"
  "Meny: Opprett ny plugin"

  "Menu: Create new theme"
  "Meny: Opprett nytt tema"

  "Menu: Cut selected text"
  "Meny: Klippe ut merket tekst"

  "Menu: Disable Vim mode"
  "Meny: Deaktiver Vim-modus"

  "Menu: Edit Tke theme"
  "Meny: Rediger TKE tema"

  "Menu: Edit snippets"
  "Meny: Rediger tekstutdrag"

  "Menu: Edit user menu bindings"
  "Meny: Rediger brukermeny bindinger"

  "Menu: Edit user preferences"
  "Meny: Rediger brukerpreferanser"

  "Menu: Enable Vim mode"
  "Meny: Aktiver Vim-modus"

  "Menu: Find"
  "Meny: Finn"

  "Menu: Find and Replace"
  "Meny: Finn og erstatt"

  "Menu: Find in files"
  "Meny: Finn i filer"

  "Menu: Find matching character pair"
  "Meny: Finn matchende karakter pair"

  "Menu: Find next occurrence"
  "Meny: Finn neste forekomst"

  "Menu: Find previous occurrence"
  "Meny: Finn forrige forekomst"

  "Menu: Goto last tab"
  "Meny: Goto siste kategorien"

  "Menu: Goto next tab"
  "Meny: Goto neste kategori"

  "Menu: Goto other pane"
  "Meny: Goto annen rute"

  "Menu: Goto previous tab"
  "Meny: Goto forrige kategori"

  "Menu: Hide Tab Bar"
  "Meny: Hide Tab Bar"

  "Menu: Hide console"
  "Meny: Skjul konsoll"

  "Menu: Hide sidebar"
  "Meny: Hide sidebar"

  "Menu: Hide status bar"
  "Meny: Skjul statuslinjen"

  "Menu: Import TextMate theme"
  "Meny: Import Textmate tema"

  "Menu: Indent selected text"
  "Meny: Innrykk merket tekst"

  "Menu: Insert enumeration"
  "Meny: Sett oppregning"

  "Menu: Install plugin"
  "Meny: Installer plugin"

  "Menu: Lock file"
  "Meny: Lock file"

  "Menu: Move to other pane"
  "Meny: Flytt til annen rute"

  "Menu: New file"
  "Meny: Ny fil"

  "Menu: Open directory"
  "Meny: Åpne telefonboken"

  "Menu: Open file"
  "Meny: Åpne fil"

  "Menu: Paste and format text from clipboard"
  "Meny: Lim inn og formatere tekst fra utklippstavlen"

  "Menu: Paste text from clipboard"
  "Meny: Lime inn tekst fra utklippstavlen"

  "Menu: Quit application"
  "Meny: Avslutt applikasjon"

  "Menu: Redo"
  "Meny: Gjør om"

  "Menu: Reload all plugins"
  "Meny: Last alle plugins"

  "Menu: Reload all snippets"
  "Meny: Last alle snutter"

  "Menu: Restart tke"
  "Meny: Restart tke"

  "Menu: Save all files"
  "Meny: Lagre alle filer"

  "Menu: Save file"
  "Meny: Lagre filen"

  "Menu: Save file as"
  "Meny: Lagre filen som"

  "Menu: Select all occurrences"
  "Meny: Velg alle forekomster"

  "Menu: Select all text"
  "Meny: Velg all tekst"

  "Menu: Set user bindings to global bindings"
  "Meny: Sett bruker bindinger til globale bindinger"

  "Menu: Set user preferences to global preferences"
  "Meny: Sett brukerinnstillinger til globale preferanser"

  "Menu: Show Tab Bar"
  "Meny: Vis Tab Bar"

  "Menu: Show console"
  "Meny: Vis konsoll"

  "Menu: Show last profiling report"
  "Meny: Vis siste profilering rapport"

  "Menu: Show sidebar"
  "Meny: Vis sidebar"

  "Menu: Show status bar"
  "Meny: Vis statuslinjen"

  "Menu: Sort tabs"
  "Meny: Sorter faner"

  "Menu: Start profiling"
  "Meny: Start profilering"

  "Menu: Stop profiling"
  "Meny: Stopp profilering"

  "Menu: Toggle split view mode"
  "Meny: Toggle split view-modus"

  "Menu: Uncomment selected text"
  "Meny: uncomment markert tekst"

  "Menu: Undo"
  "Meny: Angre"

  "Menu: Unindent selected text"
  "Meny: Fjern innrykk markert tekst"

  "Menu: Uninstall plugin"
  "Meny: Avinstaller plugin"

  "Menu: Unlock file"
  "Meny: Lås opp fil"

  "Menu: View User Guide"
  "Meny: Se Brukerhåndbok"

  "Menu: View global menu bindings"
  "Meny: Vis global meny bindinger"

  "Menu: View global preferences"
  "Meny: Vis globale preferanser"

  "Move to other pane"
  "Flytt til annen rute"

  "New"
  "Ny"

  "Open Directory..."
  "Open Directory ..."

  "Open File..."
  "Åpne fil"

  "Open Recent"
  "Åpne sist"

  "Paste"
  "Wij willen u informeren dat uw rekening is toegankelijk vanaf een onbevoegde computer"

  "Paste and Format"
  "Lim og Format"

  "Plugins"
  "Preferences..."

  "Preferences"
  "Innstillinger"

  "Profiling started"
  "Profilering i gang"

  "Profiling stopped"
  "Profilering stoppet"

  "Quit"
  "Avslutt"

  "Redo"
  "gjøre om"

  "Reload"
  "Restart tke"

  "Restart tke"
  "Save All"

  "Save All"
  "Lagre alle"

  "Save As..."
  "Lagre som ..."

  "Select All"
  "Merk alt"

  "Select all occurrences"
  "Velg alle forekomster"

  "Select next occurrence"
  "Velg neste forekomst"

  "Select previous occurrence"
  "Velg forrige forekomst"

  "Selected"
  "Valgt"

  "Set Syntax"
  "Sett Syntax"

  "Set Theme"
  "Sett Tema"

  "Set user to global"
  "Sett brukeren til global"

  "Show Console"
  "Vis Console"

  "Show Last Profiling Report"
  "Vis Siste Profiling Rapporter"

  "Show Sidebar"
  "Vis Sidebar"

  "Show Status Bar"
  "Vis statuslinje"

  "Show Tab Bar"
  "Vis Tab Bar"

  "Show*Profiling*"
  "Show * Profilering *"

  "Snippets"
  "Tekstutdrag"

  "Sort Tabs"
  "Sorter Tabs"

  "Split view"
  "Delt visning"

  "Start Profiling"
  "Begynn Profilering"

  "Stop Profiling"
  "Stopp Profilering"

  "Tabs"
  "Tab"

  "Text"
  "Tekst"

  "Theme Creator"
  "Tema Creator"

  "Tools"
  "Redskap"

  "Uncomment"
  "Undo"

  "Undo"
  "angre"

  "Unindent"
  "Fjern innrykk"

  "Uninstall..."
  "avinstallere"

  "Unlock"
  "Oppheve låsing"

  "User Guide"
  "Bruksanvisning"

  "View"
  "Vis"

  "View global"
  "Vis global"

  "Vim Mode"
  "Vim Mode"

}

# plugins.tcl
msgcat::mcmset no {

  "ERROR:  Plugin name is not valid (only alphanumeric and underscores are allowed)"
  "FEIL: Plugin navn er ikke gyldig (bare alfanumerisk og understrek er tillatt)"

  "ERROR:  Unable to write plugin file"
  "FEIL: Kan ikke skrive pluginfil"

  "Enter plugin name"
  "Skriv inn plugin navn"

  "Plugin %s installed"
  "Plugin% s installert"

  "Plugin %s uninstalled"
  "Plugin% s avinstallert"

  "Plugin Errors"
  "Plugin feil"

  "Syntax errors found in selected plugins"
  "Syntaksfeil som finnes i utvalgte plugins"

}

# sidebar.tcl
msgcat::mcmset no {

  "Add Parent Directory"
  "Legg Parent Directory"

  "Close Directory Files"
  "Lukk Directory filer"

  "Delete"
  "Slett"

  "Delete directory?"
  "Slett katalogen?"

  "Delete file?"
  "Slett filen?"

  "Duplicate"
  "Duplikat"

  "Make Current Working Directory"
  "Gjør nåværende arbeidskatalog"

  "New Directory"
  "Ny katalog"

  "New File"
  "Ny fil"

  "Open"
  "Åpen"

  "Refresh Directory Files"
  "Oppdater Directory filer"

  "Remove Parent from Sidebar"
  "Fjern Parent fra Sidebar"

  "Remove from Sidebar"
  "Fjern fra Sidebar"

  "Rename"
  "Gi nytt navn"

}

# snippets.tcl
msgcat::mcmset no {

  "Snippet: %s: %s"
  "Snippet:% s:% s"

  "Snippet: *"
  "Tekstutdrag: *"

}

# syntax.tcl
msgcat::mcmset no {

  "Syntax error in %s.syntax file"
  "Syntaksfeil i% s.syntax fil"

  "Syntax:  %s"
  "Syntax:% s"

  "Theme:  %s"
  "Tema:% s"

}

# themer.tcl
msgcat::mcmset no {

  "Create"
  "Opprett"

  "Create New Theme"
  "Lag nytt tema"

  "Create custom"
  "Lag tilpassede"

  "ERROR:  Unable to read %s"
  "FEIL: Kan ikke lese% s"

  "ERROR:  Unable to write %s"
  "FEIL: Kan ikke skrive% s"

  "Edit theme"
  "Rediger tema"

  "Enter theme name"
  "Oppgi temanavn"

  "Error:  Theme is not a supported theme"
  "Feil: Tema er ikke en støttet tema"

  "Import"
  "importere"

  "Import TextMate Theme"
  "Import Textmate Tema"

  "Name:"
  "Navn:"

  "OK"
  "Ok"

  "Reset"
  "Reset"

  "Select theme"
  "Velg tema"

}

# tke.tcl
msgcat::mcmset no {

  "ERROR:  %s"
  "FEIL:% s"

  "Edit theme?"
  "Redigere tema?"

  "Import TextMate theme?"
  "Importere Textmate tema?"

}

# tkedat.tcl
msgcat::mcmset no {

  "Unable to open %s for reading"
  "Kan ikke åpne% s for lesing"

  "Unable to open %s for writing"
  "Kan ikke åpne% s for skriving"

}

# General
msgcat::mcmset no {

  "Cancel"
  "Avbryt"

  "Close"
  "Lukk"

  "Find:"
  "Søk"

  "Replace:"
  "bytt"

  "Save"
  "lagre"

  "Save As"
  "Lagre som"

}

