# api.tcl
msgcat::mcmset no {

  "Argument list to api::add_file was not an even key/value pair"
  "Argument liste til api :: add_file var ikke en enda nøkkel / verdi-par"

}

# bgproc.tcl
msgcat::mcmset no {

  "Unable to run system command (%s)"
  "Kan ikke kjøre systemkommando (% s)"

}

# diff.tcl
msgcat::mcmset no {

  "    End: "
  "Slutt"

  "    Start: "
  "START"

  "Enter difference command"
  "Angi forskjellen kommandoen"

  "Enter starting file"
  "Angi start-filen"

  "Update"
  "Oppdater"

}

# gui.tcl
msgcat::mcmset no {

  "%s, Line: %d, Column: %d"
  "% S, Line:% d, Kolonne:% d"

  "Case sensitivity"
  "Bokstaver"

  "Close All Tabs"
  "Lukk alle faner"

  "Close Other Tab(s)"
  "Lukk Other Tab (s)"

  "Close Other*"
  "Lukk Annet *"

  "Close Tab"
  "Lukk fane"

  "Copyright %d-%d"
  "Copyright% d-% d"

  "Delete tab?"
  "Slett fane?"

  "Developer:"
  "Utvikler"

  "Email:"
  "E-post:"

  "Error"
  "Feil"

  "Favorited"
  "Favoritt"

  "File already exists.  Use '!' to force an overwrite"
  "Filen finnes allerede.  Bruk '!' å tvinge en overskriving"

  "File attribute (%s) does not exist"
  "File attributt (% s) eksisterer ikke"

  "File index is out of range"
  "File indeksen er utenfor rekkevidde"

  "License:"
  "Lisens"

  "Line: %d, Column: %d"
  "Linje:% d, Kolonne:% d"

  "Locked"
  "låst"

  "Move*"
  "flytte"

  "Must be in multicursor mode to insert numbers"
  "Må være i multicursor for å sette inn tall"

  "No write permissions.  Use '!' to force write."
  "Ingen skrivetilgang.  Bruk '!' tvinge skrive."

  "Release Type:"
  "Versjonstypen:"

  "Reload file?"
  "Last filen?"

  "Save request"
  "Be"

  "Show in Sidebar"
  "Vis i Sidebar"

  "Starting number:"
  "Startnummeret:"

  "Tcl/Tk Version:"
  "TCL/Tk-versjonen:"

  "Total Lines: %d, Total Characters: %d"
  "Totalt antall linjer:% d, Totalt antall tegn:% d"

  "Unable to find current file (tab: %s)"
  "Å finne aktuelle filen klarer (tab:% s)"

  "Unable to successfully parse number string"
  "Kan ikke analysere vellykket tallstreng"

  "Unable to write file"
  "Kan ikke skrive filen"

  "Version:"
  "Versjon"

}

# markers.tcl
msgcat::mcmset no {

  "Marker name:"
  "Marker navn:"

}

# menus.tcl
msgcat::mcmset no {

  "                                  Profiling Report Sorted By (%s)"
  "Profilering Rapporter Sorted By (% s)"

  "About TKE"
  "Om TKE"

  "Align Cursors"
  "Justere pekere"

  "Append Next Occurrence"
  "Legg til neste forekomst"

  "Auto-Indent"
  "Auto-innrykk"

  "Check for Update"
  "Søk etter oppdateringer"

  "Clear All"
  "Fjern alle"

  "Close All"
  "Lukk alle"

  "Close Current"
  "Lukker gjeldende"

  "Copy"
  "Kopier"

  "Create New..."
  "Opprette nye..."

  "Create at Current Line"
  "Opprette på gjeldende linje"

  "Create..."
  "frambringe"

  "Cut"
  "Kutt"

  "Edit"
  "Edit"

  "Edit Language"
  "Rediger språk"

  "Edit Session - Global"
  "Sesjon - Global"

  "Edit Session - Language"
  "Redigere Session - språk"

  "Edit User"
  "Rediger bruker"

  "Edit User - Global"
  "Rediger bruker - Global"

  "Edit User - Language"
  "Rediger bruker - språk"

  "Edit..."
  "Edit"

  "File"
  "Fil"

  "Find"
  "Søk"

  "Find In Files"
  "Finn filer"

  "Find Matching Pair"
  "Finn matchende par"

  "Find and Replace"
  "Finn og erstatt"

  "Format Text"
  "Formater tekst"

  "From Clipboard"
  "Fra utklippstavlen"

  "Goto Last Tab"
  "Gå Siste Tab"

  "Goto Next Tab"
  "Gå til neste fane"

  "Goto Other Pane"
  "Gå til Annen Pane"

  "Goto Previous Tab"
  "Gå til forrige fane"

  "Help"
  "Help!"

  "Hide Console"
  "Skjul Console"

  "Hide Line Numbers"
  "Skjul linjenumre"

  "Hide Meta Characters"
  "Skjule Meta tegn"

  "Hide Sidebar"
  "Skjul Sidebar"

  "Hide Status Bar"
  "Skjul Status Bar"

  "Hide Tab Bar"
  "Skjul Tab Bar"

  "Import TextMate Theme..."
  "Importere TextMate tema..."

  "Indent"
  "innrykk"

  "Indent Mode"
  "Innrykk modus"

  "Indent Off"
  "Innrykk av"

  "Insert Enumeration"
  "Sett inn opplisting"

  "Insert Text"
  "Sett inn tekst"

  "Install..."
  "installere"

  "Jump Backward"
  "Hoppe bakover"

  "Jump Forward"
  "Hoppe fremover"

  "Launcher"
  "Launcher"

  "Lock"
  "Lås"

  "Markers"
  "Markører"

  "Menu Bindings"
  "Meny Bindinger"

  "Menu Edit user snippets"
  "Menyen Rediger bruker tekstutdrag"

  "Menu: About TKE"
  "Meny: Om TKE"

  "Menu: Align cursors"
  "Meny: Rett pekere"

  "Menu: Append next occurrence"
  "Meny: Legg ved neste forekomst"

  "Menu: Check for Update"
  "Meny: Søk etter oppdateringer"

  "Menu: Close all tabs"
  "Meny: Lukk alle faner"

  "Menu: Close current session"
  "Meny: Lukk gjeldende økt"

  "Menu: Close current tab"
  "Meny: Lukk gjeldende fane"

  "Menu: Copy text"
  "Meny: Kopiere tekst"

  "Menu: Create marker at current line"
  "Meny: Opprette markør på gjeldende linje"

  "Menu: Create new plugin"
  "Meny: Opprett ny plugin"

  "Menu: Create new theme"
  "Meny: Opprett nytt tema"

  "Menu: Cut text"
  "Meny: Kutt tekst"

  "Menu: Delete session"
  "Meny: Slett økt"

  "Menu: Disable Vim mode"
  "Meny: Deaktiver Vim-modus"

  "Menu: Edit Tke theme"
  "Meny: Rediger TKE tema"

  "Menu: Edit language snippets"
  "Meny: Rediger språk tekstutdrag"

  "Menu: Edit session current language preferences"
  "Meny: Redigere økt gjeldende språkinnstillinger"

  "Menu: Edit session global preferences"
  "Meny: Redigere økt globale innstillinger"

  "Menu: Edit user current language preferences"
  "Meny: Redigere bruker gjeldende språkinnstillinger"

  "Menu: Edit user global preferences"
  "Meny: Redigere globale brukerinnstillinger"

  "Menu: Edit user menu bindings"
  "Meny: Rediger brukermeny bindinger"

  "Menu: Enable Vim mode"
  "Meny: Aktiver Vim-modus"

  "Menu: Favorite file"
  "Meny: Favoritt fil"

  "Menu: Find"
  "Meny: Finn"

  "Menu: Find and Replace"
  "Meny: Finn og erstatt"

  "Menu: Find in files"
  "Meny: Finn i filer"

  "Menu: Find matching character pair"
  "Meny: Finn matchende karakter pair"

  "Menu: Find next occurrence"
  "Meny: Finn neste forekomst"

  "Menu: Find previous occurrence"
  "Meny: Finn forrige forekomst"

  "Menu: Format all text"
  "Meny: Formater all tekst"

  "Menu: Format selected text"
  "Meny: Format markert tekst"

  "Menu: Goto last tab"
  "Meny: Goto siste kategorien"

  "Menu: Goto next difference"
  "Meny: Goto neste forskjellen"

  "Menu: Goto next tab"
  "Meny: Goto neste kategori"

  "Menu: Goto other pane"
  "Meny: Goto annen rute"

  "Menu: Goto previous difference"
  "Meny: Goto tidligere forskjellen"

  "Menu: Goto previous tab"
  "Meny: Goto forrige kategori"

  "Menu: Hide Line Numbers"
  "Meny: Skjul linjenumre"

  "Menu: Hide Tab Bar"
  "Meny: Hide Tab Bar"

  "Menu: Hide console"
  "Meny: Skjul konsoll"

  "Menu: Hide meta characters"
  "Meny: Skjule meta tegn"

  "Menu: Hide sidebar"
  "Meny: Hide sidebar"

  "Menu: Hide status bar"
  "Meny: Skjul statuslinjen"

  "Menu: Import TextMate theme"
  "Meny: Import Textmate tema"

  "Menu: Indent selected text"
  "Meny: Innrykk merket tekst"

  "Menu: Insert enumeration"
  "Meny: Sett oppregning"

  "Menu: Insert from clipboard"
  "Meny: Sett inn fra utklippstavlen"

  "Menu: Insert snippet"
  "Meny: Sett inn tekstutdrag"

  "Menu: Install plugin"
  "Meny: Installer plugin"

  "Menu: Jump backward"
  "Meny: Hoppe bakover"

  "Menu: Jump forward"
  "Meny: Hoppe fremover"

  "Menu: Lock file"
  "Meny: Lock file"

  "Menu: Merge panes"
  "Meny: Flettingen ruter"

  "Menu: Move to other pane"
  "Meny: Flytt til annen rute"

  "Menu: New file"
  "Meny: Ny fil"

  "Menu: Open Favorite"
  "Meny: Åpne Favoritt"

  "Menu: Open Recent"
  "Meny: Åpne sist"

  "Menu: Open directory"
  "Meny: Åpne telefonboken"

  "Menu: Open file"
  "Meny: Åpne fil"

  "Menu: Open session"
  "Meny: Åpne økt"

  "Menu: Paste and format text from clipboard"
  "Meny: Lim inn og formatere tekst fra utklippstavlen"

  "Menu: Paste text from clipboard"
  "Meny: Lime inn tekst fra utklippstavlen"

  "Menu: Quit application"
  "Meny: Avslutt applikasjon"

  "Menu: Redo"
  "Meny: Gjør om"

  "Menu: Reload all plugins"
  "Meny: Last alle plugins"

  "Menu: Reload snippets"
  "Meny: Reload tekstutdrag"

  "Menu: Remove all markers"
  "-Menyen: Fjern alle merkene"

  "Menu: Remove marker from current line"
  "Meny: Fjerne merket fra gjeldende linje"

  "Menu: Replace line with script"
  "Meny: Erstatte linje med skript"

  "Menu: Restart tke"
  "Meny: Restart tke"

  "Menu: Save all files"
  "Meny: Lagre alle filer"

  "Menu: Save current session"
  "Meny: Lagre gjeldende økt"

  "Menu: Save file"
  "Meny: Lagre filen"

  "Menu: Save file as"
  "Meny: Lagre filen som"

  "Menu: Save sessions as"
  "Meny: Lagre sesjoner som"

  "Menu: Select all occurrences"
  "Meny: Velg alle forekomster"

  "Menu: Select all text"
  "Meny: Velg all tekst"

  "Menu: Send Bug Report"
  "Menyen: Send feilrapport"

  "Menu: Send Feedback"
  "Menyen: Send tilbakemelding"

  "Menu: Set indent mode to IND"
  "Meny: Angi innrykk-modusen til IND"

  "Menu: Set indent mode to IND+"
  "Meny: Angi innrykk-modusen til IND +"

  "Menu: Set indent mode to OFF"
  "Meny: Angi innrykk-modusen til av"

  "Menu: Set user bindings to global bindings"
  "Meny: Sett bruker bindinger til globale bindinger"

  "Menu: Set user preferences to global preferences"
  "Meny: Sett brukerinnstillinger til globale preferanser"

  "Menu: Show Diagnostic Logfile"
  "Meny: Vis diagnostiske loggfil"

  "Menu: Show Line Numbers"
  "Meny: Vis linjenumre"

  "Menu: Show Tab Bar"
  "Meny: Vis Tab Bar"

  "Menu: Show console"
  "Meny: Vis konsoll"

  "Menu: Show file difference"
  "Meny: Vis fil forskjellen"

  "Menu: Show last profiling report"
  "Meny: Vis siste profilering rapport"

  "Menu: Show meta characters"
  "Meny: Vis meta tegn"

  "Menu: Show selected line change"
  "Meny: Vis valgt linje endring"

  "Menu: Show sidebar"
  "Meny: Vis sidebar"

  "Menu: Show status bar"
  "Meny: Vis statuslinjen"

  "Menu: Sort tabs"
  "Meny: Sorter faner"

  "Menu: Start profiling"
  "Meny: Start profilering"

  "Menu: Stop profiling"
  "Meny: Stopp profilering"

  "Menu: Switch to session"
  "Meny: Bytt til økt"

  "Menu: Toggle comment"
  "Meny: Vis/Skjul merknad"

  "Menu: Toggle split view mode"
  "Meny: Toggle split view-modus"

  "Menu: Undo"
  "Meny: Angre"

  "Menu: Unfavorite file"
  "Meny: unfavorite fil"

  "Menu: Unindent selected text"
  "Meny: Fjern innrykk markert tekst"

  "Menu: Uninstall plugin"
  "Meny: Avinstaller plugin"

  "Menu: Unlock file"
  "Meny: Lås opp fil"

  "Menu: View User Guide"
  "Meny: Se Brukerhåndbok"

  "Menu: View base preferences file"
  "Meny: Vis base innstillingsfilen"

  "Menu: View global menu bindings"
  "Meny: Vis global meny bindinger"

  "Merge Panes"
  "Flette ruter"

  "Next Difference"
  "Neste forskjellen"

  "Open Directory..."
  "Open Directory ..."

  "Open Favorite"
  "Åpne Favoritt"

  "Open File..."
  "Åpne fil"

  "Open Recent"
  "Åpne sist"

  "Paste"
  "Wij willen u informeren dat uw rekening is toegankelijk vanaf een onbevoegde computer"

  "Paste and Format"
  "Lim og Format"

  "Plugins"
  "Preferences..."

  "Preferences"
  "Innstillinger"

  "Previous Difference"
  "Tidligere forskjellen"

  "Profiling started"
  "Profilering i gang"

  "Profiling stopped"
  "Profilering stoppet"

  "Quit"
  "Avslutt"

  "Redo"
  "gjøre om"

  "Reload"
  "Restart tke"

  "Remove All Markers"
  "Fjerne alle merkene"

  "Remove From Current Line"
  "Fjern fra gjeldende linje"

  "Replace Line With Script"
  "Erstatte linje med skript"

  "Reset User to Base"
  "Tilbakestille bruker til Base"

  "Restart TKE"
  "Starte TKE"

  "Save All"
  "Lagre alle"

  "Save As..."
  "Lagre som ..."

  "Save Current"
  "Lagre gjeldende"

  "Select All"
  "Merk alt"

  "Select All Occurrences"
  "Velg alle forekomster"

  "Select Next Occurrence"
  "Velg neste forekomst"

  "Select Previous Occurrence"
  "Velg forrige forekomst"

  "Selected"
  "Valgt"

  "Send Bug Report"
  "Sende feilrapport"

  "Send Feedback"
  "Send tilbakemelding"

  "Sessions"
  "Sessions"

  "Set Syntax"
  "Sett Syntax"

  "Set Theme"
  "Sett Tema"

  "Set User to Global"
  "Angi brukeren globale"

  "Show Console"
  "Vis Console"

  "Show Diagnostic Logfile"
  "Vise diagnostisk loggfil"

  "Show File Difference"
  "Vise filen forskjellen"

  "Show Last Profiling Report"
  "Vis Siste Profiling Rapporter"

  "Show Line Numbers"
  "Vis linjenumre"

  "Show Meta Characters"
  "Viser Meta tegn"

  "Show Selected Line Change"
  "Vis valgte linjen endring"

  "Show Sidebar"
  "Vis Sidebar"

  "Show Status Bar"
  "Vis statuslinje"

  "Show Tab Bar"
  "Vis Tab Bar"

  "Show*Profiling*"
  "Show * Profilering *"

  "Smart Indent"
  "Smart innrykk"

  "Snippet"
  "Snippet"

  "Snippets"
  "Tekstutdrag"

  "Sort Tabs"
  "Sorter Tabs"

  "Split View"
  "Delt visning"

  "Start Profiling"
  "Begynn Profilering"

  "Stop Profiling"
  "Stopp Profilering"

  "Switch To"
  "Bytt til:"

  "Tabs"
  "Tab"

  "Text"
  "Tekst"

  "Theme Creator"
  "Tema Creator"

  "Toggle Comment"
  "Vis/Skjul merknad"

  "Tools"
  "Redskap"

  "Undo"
  "angre"

  "Unindent"
  "Fjern innrykk"

  "Uninstall..."
  "avinstallere"

  "Unlock"
  "Oppheve låsing"

  "User Guide"
  "Bruksanvisning"

  "View"
  "Vis"

  "View Base"
  "Vis Base"

  "View Global"
  "Vis globale"

  "Vim Mode"
  "Vim Mode"

}

# plugins.tcl
msgcat::mcmset no {

  "ERROR (%s,%s): %s"
  "FEIL (%s, %s): %s"

  "ERROR:  Plugin name already exists"
  "FEIL: Plugin navnet finnes allerede"

  "ERROR:  Plugin name is not valid (only alphanumeric and underscores are allowed)"
  "FEIL: Plugin navn er ikke gyldig (bare alfanumerisk og understrek er tillatt)"

  "ERROR:  Unable to create plugin directory"
  "FEIL: Kan ikke opprette plugin katalogen"

  "ERROR:  Unable to write plugin files"
  "FEIL: Kan ikke skrive plugin-filer"

  "Enter plugin name"
  "Skriv inn plugin navn"

  "Plugin %s installed"
  "Plugin% s installert"

  "Plugin %s uninstalled"
  "Plugin% s avinstallert"

  "Plugin Errors"
  "Plugin feil"

  "Plugins successfully reloaded"
  "Plugins hell reloaded"

  "Syntax errors found in selected plugins"
  "Syntaksfeil som finnes i utvalgte plugins"

}

# search.tcl
msgcat::mcmset no {

  "%d substitutions done"
  "%d erstatninger gjort"

  "No files found in specified directories"
  "Ingen filer funnet i angitte mapper"

  "No search results found"
  "Søkeresultater Funnet For"

  "Search wrapped to beginning of file"
  "Søk brytes til begynnelsen av filen"

  "Search wrapped to end of file"
  "Søk pakket til slutten av filen"

}

# sidebar.tcl
msgcat::mcmset no {

  "Add Parent Directory"
  "Legg Parent Directory"

  "Close Directory Files"
  "Lukk Directory filer"

  "Copy Pathname"
  "Kopiere banenavn"

  "Delete directory?"
  "Slett katalogen?"

  "Delete file?"
  "Slett filen?"

  "Directory Name:"
  "Mappenavn:"

  "Duplicate"
  "Duplikat"

  "File Name:"
  "Fil navn:"

  "Folder Name:"
  "Mappenavn"

  "Make Current Working Directory"
  "Gjør nåværende arbeidskatalog"

  "New Directory"
  "Ny katalog"

  "Open Directory Files"
  "Open Directory filer"

  "Refresh Directory Files"
  "Oppdater Directory filer"

  "Remove Parent from Sidebar"
  "Fjern Parent fra Sidebar"

  "Remove from Sidebar"
  "Fjern fra Sidebar"

  "Rename"
  "Gi nytt navn"

  "Show Difference"
  "Vis forskjellen"

}

# snippets.tcl
msgcat::mcmset no {

  "Snippet: *"
  "Tekstutdrag: *"

}

# syntax.tcl
msgcat::mcmset no {

  "Syntax error in %s.syntax file"
  "Syntaksfeil i% s.syntax fil"

  "Syntax:  %s"
  "Syntax:% s"

  "Theme:  %s"
  "Tema:% s"

}

# themer.tcl
msgcat::mcmset no {

  "Create"
  "Opprett"

  "Create New Theme"
  "Lag nytt tema"

  "Create custom"
  "Lag tilpassede"

  "ERROR:  Unable to read %s"
  "FEIL: Kan ikke lese% s"

  "ERROR:  Unable to write %s"
  "FEIL: Kan ikke skrive% s"

  "Edit theme"
  "Rediger tema"

  "Enter theme name"
  "Oppgi temanavn"

  "Error:  Theme is not a supported theme"
  "Feil: Tema er ikke en støttet tema"

  "Import"
  "importere"

  "Import TextMate Theme"
  "Import Textmate Tema"

  "Name:"
  "Navn:"

  "OK"
  "Ok"

  "Reset"
  "Reset"

  "Select theme"
  "Velg tema"

}

# tke.tcl
msgcat::mcmset no {

  "Edit theme?"
  "Redigere tema?"

  "Import TextMate theme?"
  "Importere Textmate tema?"

}

# tkedat.tcl
msgcat::mcmset no {

  "Unable to open %s for reading"
  "Kan ikke åpne %s for lesing"

}

# vim.tcl
msgcat::mcmset no {

  "File %s successfully written"
  "Filen %s ble skrevet"

  "Filename %s already exists"
  "Filnavn %s finnes allerede"

}

# General
msgcat::mcmset no {

  "All"
  "Alle"

  "Cancel"
  "Avbryt"

  "Close"
  "Lukk"

  "Delete"
  "Slett"

  "Favorite"
  "Favoritt"

  "Find:"
  "Søk"

  "Move to Other Pane"
  "Flytt til Annen Pane"

  "New File"
  "Ny fil"

  "Open"
  "Åpen"

  "Replace:"
  "bytt"

  "Save"
  "lagre"

  "Save As"
  "Lagre som"

  "Unable to open %s for writing"
  "Kan ikke åpne% s for skriving"

  "Unfavorite"
  "Unfavorite"

}

