# api.tcl
msgcat::mcmset pl {

  "Argument list to api::add_file was not an even key/value pair"
  "Lista argumentów API :: add_file nie było nawet parę klucz / wartość"

}

# bgproc.tcl
msgcat::mcmset pl {

  "Unable to run system command (%s)"
  "Komenda nie może uruchomić systemu (% s)"

}

# diff.tcl
msgcat::mcmset pl {

  "    End: "
  "Koniec:"

  "    Start: "
  "Start:"

  "Enter difference command"
  "Wprowadź polecenie różnica"

  "Enter starting file"
  "Wpisz początkowy plik"

  "Update"
  "Aktualizuj"

}

# gui.tcl
msgcat::mcmset pl {

  "%s, Line: %d, Column: %d"
  "% S, linia:% d, kolumna:% d"

  "Case sensitivity"
  "Case sensitive i case insensitive"

  "Close All Tabs"
  "Zamknij wszystkie karty"

  "Close Other Tab(s)"
  "Zamknij Inne Tab (s)"

  "Close Other*"
  "\"

  "Close Tab"
  "Zamknij kartę"

  "Copyright %d-%d"
  "Prawa autorskie% d-% d"

  "Delete tab?"
  "Usuń kartę?"

  "Developer:"
  "Twórca programu:"

  "Email:"
  "E-mail:"

  "Error"
  "Błąd"

  "Favorited"
  "Jako ulubione"

  "File already exists.  Use '!' to force an overwrite"
  "Plik już istnieje.  Użycie '!' wymusić zastępowaniem"

  "File attribute (%s) does not exist"
  "Atrybut pliku (% s) nie istnieje"

  "File index is out of range"
  "Wskaźnik pliku jest poza zakresem"

  "License:"
  "Licencja:"

  "Line: %d, Column: %d"
  "Linia:% d, kolumna:% d"

  "Locked"
  "Zablokowano"

  "Move*"
  "Przenieś"

  "Must be in multicursor mode to insert numbers"
  "Musi być w trybie multicursor, aby wstawić numery"

  "No write permissions.  Use '!' to force write."
  "Brak prawa do zapisu.  Użycie '!' wymusić zapisu."

  "Release Type:"
  "Typ Release:"

  "Reload file?"
  "Wczytaj plik na nowo"

  "Save request"
  "Zapisz zlecenie"

  "Show in Sidebar"
  "Pokaż w pasku bocznym"

  "Starting number:"
  "Numer startowy:"

  "Tcl/Tk Version:"
  "Wersji Tcl/Tk:"

  "Total Lines: %d, Total Characters: %d"
  "Liczba linii:% d, Liczba znaków:% d"

  "Unable to find current file (tab: %s)"
  "Nie można znaleźć aktualny plik (zakładka:% s)"

  "Unable to successfully parse number string"
  "Nie można pomyślnie przeanalizować ciąg liczb"

  "Unable to write file"
  "Nie można zapisać pliku"

  "Version:"
  "Wersja:"

}

# markers.tcl
msgcat::mcmset pl {

  "Marker name:"
  "Nazwa znacznik:"

}

# menus.tcl
msgcat::mcmset pl {

  "                                  Profiling Report Sorted By (%s)"
  "Profilowanie Zgłoś sortowanie wg (% s)"

  "About TKE"
  "O TKE"

  "Align Cursors"
  "Wyrówna? kursory"

  "Append Next Occurrence"
  "Dok?ada? kolejne wyst?pienie"

  "Auto-Indent"
  "Automatyczne wcięcia"

  "Check for Update"
  "Sprawdź aktualizacje"

  "Clear All"
  "Czyść wszystko"

  "Close All"
  "Zamknij wszystkie"

  "Close Current"
  "Zamknij bie??c? kart?"

  "Copy"
  "Kopiuj"

  "Create New..."
  "Utwórz nowe"

  "Create at Current Line"
  "Utwórz w bie??cym wierszu"

  "Create..."
  "Utwórz..."

  "Cut"
  "\"

  "Edit"
  "\"

  "Edit Language"
  "Zmień język"

  "Edit Menu Edit user snippets"
  "Edytować Menu Edytuj użytkownika urywki"

  "Edit Menu: Copy text"
  "Menu Edycja: Tekst kopiowanie"

  "Edit Menu: Cut text"
  "Menu Edycja: Wytnij tekst"

  "Edit Menu: Edit language snippets"
  "Menu Edytuj: Edycja urywki języka"

  "Edit Menu: Edit session current language preferences"
  "Menu Edycja: Edytuj preferencje językowe bieżącej sesji"

  "Edit Menu: Edit session global preferences"
  "Menu Edytuj: Edycja sesji globalne preferencje"

  "Edit Menu: Edit user current language preferences"
  "Menu Edytuj: Edycja użytkownika aktualne preferencje językowe"

  "Edit Menu: Edit user global preferences"
  "Menu Edytuj: Edycja globalne preferencje użytkownika"

  "Edit Menu: Edit user menu bindings"
  "Menu Edytuj: Edycja użytkownika menu powiązania"

  "Edit Menu: Format all text"
  "Edycja Menu: Format cały tekst"

  "Edit Menu: Format selected text"
  "Menu Edycja: Formatowanie zaznaczonego tekstu"

  "Edit Menu: Insert from clipboard"
  "Menu Edycja: Wstawianie ze schowka"

  "Edit Menu: Insert snippet"
  "Menu Edycja: Wstaw urywek"

  "Edit Menu: Paste and format text from clipboard"
  "Menu Edycja: Pasta i format tekstu ze schowka"

  "Edit Menu: Paste text from clipboard"
  "Menu Edycja: Wkleić tekst ze schowka"

  "Edit Menu: Redo"
  "Edycja, Menu: przerobić"

  "Edit Menu: Reload snippets"
  "Menu Edycja: Fragmenty przeładuj"

  "Edit Menu: Select all text"
  "Menu Edycja: Zaznacz cały tekst"

  "Edit Menu: Set indent mode to IND"
  "Edycja Menu: Tryb Ustaw wcięcie IND"

  "Edit Menu: Set indent mode to IND+"
  "Menu Edycja: Ustaw tryb tiret do IND +"

  "Edit Menu: Set indent mode to OFF"
  "Menu Edycja: Ustaw wcięcie tryb off"

  "Edit Menu: Set user bindings to global bindings"
  "Menu Edycja: Zestaw powiązania użytkownika do globalnych powiązań"

  "Edit Menu: Set user preferences to global preferences"
  "Menu Edycja: Ustawić preferencje użytkownika do globalnych preferencji"

  "Edit Menu: Undo"
  "Edycja, Menu: Cofnij"

  "Edit Menu: View base preferences file"
  "Edycja Menu: Widok podstawowy plik"

  "Edit Menu: View global menu bindings"
  "Edycja Menu: Widok menu globalnego powiązania"

  "Edit Session - Global"
  "Edytowa? sesji - globalny"

  "Edit Session - Language"
  "Edycja sesji - j?zyk"

  "Edit User"
  "Edycja użytkownika"

  "Edit User - Global"
  "Edytuj u?ytkownika - globalny"

  "Edit User - Language"
  "Edycja u?ytkownika - j?zyk"

  "Edit..."
  "Edytuj..."

  "File"
  "Plik"

  "File Menu: Close all tabs"
  "Menu plik: Zamknij wszystkie karty"

  "File Menu: Close current tab"
  "Menu plik: Zamknij kartę bieżącego"

  "File Menu: Favorite file"
  "Menu plik: Ulubiony plik"

  "File Menu: Lock file"
  "Menu plik: Blokada pliku"

  "File Menu: New file"
  "Menu plik: Nowy plik"

  "File Menu: Open Favorite"
  "Menu plik: Ulubione Otwórz"

  "File Menu: Open Recent"
  "Narzędzia Wyczyść wcięcia"

  "File Menu: Open directory"
  "Menu plik: Otwórz katalog"

  "File Menu: Open file"
  "Menu plik: Otwórz plik"

  "File Menu: Quit application"
  "Menu plik: Zamknij aplikację"

  "File Menu: Save all files"
  "Menu plik: Zapisz wszystkie pliki"

  "File Menu: Save file"
  "Menu plik: Zapisywanie plików"

  "File Menu: Save file as"
  "Menu plik: Zapisz plik jako"

  "File Menu: Show file difference"
  "Menu plik: Pokaż plik różnica"

  "File Menu: Unfavorite file"
  "Menu plik: Unfavorite plik"

  "File Menu: Unlock file"
  "Menu plik: Odblokować plik"

  "Find"
  "\"

  "Find In Files"
  "Znajd? w plikach..."

  "Find Matching Pair"
  "Znajd? pasuj?ce pary"

  "Find Menu: Append next occurrence"
  "Znajdź Menu: Dokładać kolejne wystąpienie"

  "Find Menu: Create marker at current line"
  "Znajdź Menu: Utworzyć znacznik w bieżącym wierszu"

  "Find Menu: Find"
  "Znajdź Menu: znaleźć"

  "Find Menu: Find and Replace"
  "Znajdź Menu: Znajdź i zamień"

  "Find Menu: Find in files"
  "Znajdź Menu: Znajdowanie w plikach"

  "Find Menu: Find matching character pair"
  "Znajdź Menu: Znajdź pasujące pary znaków"

  "Find Menu: Find next occurrence"
  "Znajdź Menu: Znajdź następne wystąpienie"

  "Find Menu: Find previous occurrence"
  "Znajdź Menu: Znaleźć poprzednie wystąpienie"

  "Find Menu: Goto next difference"
  "Znajdź Menu: Goto następnego różnica"

  "Find Menu: Goto previous difference"
  "Znajdź Menu: Goto poprzednich różnica"

  "Find Menu: Jump backward"
  "Znajdź Menu: Skok do tyłu"

  "Find Menu: Jump forward"
  "Znajdź Menu: Skok do przodu"

  "Find Menu: Remove all markers"
  "Znajdź Menu: Usunąć wszystkie markery"

  "Find Menu: Remove marker from current line"
  "Znajdź Menu: Usuń znacznik z bieżącego wiersza"

  "Find Menu: Select all occurrences"
  "Znajdź Menu: Wybierz wszystkie wystąpienia"

  "Find Menu: Show selected line change"
  "Znajdź Menu: Pokaż zaznaczona linia zmiany"

  "Find and Replace"
  "Znajdź i zamień"

  "Format Text"
  "Formatowanie tekstu"

  "From Clipboard"
  "Ze schowka"

  "Goto Last Tab"
  "Idź Ostatnio Tab"

  "Goto Next Tab"
  "Idź Następny Tab"

  "Goto Other Pane"
  "Idź Inne Pane"

  "Goto Previous Tab"
  "Idź do strony Poprzedni Tab"

  "Help"
  "Pomoc"

  "Help Menu: About TKE"
  "Menu Pomoc: O TKE"

  "Help Menu: Check for update"
  "Menu Pomoc: Sprawdź Aktualizacje"

  "Help Menu: Send bug report"
  "Menu Pomoc: Wyślij raport błędu"

  "Help Menu: Send feedback"
  "Menu Pomoc: Przesyłanie opinii"

  "Help Menu: View user guide"
  "Menu Pomoc: Podręcznik użytkownika widok"

  "Hide Console"
  "Ukryj konsoli"

  "Hide Line Numbers"
  "Ukryj numery linii"

  "Hide Meta Characters"
  "Ukryj Meta znaków"

  "Hide Sidebar"
  "Ukryj pasek"

  "Hide Status Bar"
  "Ukryj na pasku stanu:"

  "Hide Tab Bar"
  "Ukryj pasek zakładek"

  "Import TextMate Theme..."
  "Przywóz TextMate tematu..."

  "Indent"
  "Einzug"

  "Indent Mode"
  "Tryb tiret"

  "Indent Off"
  "Wcięcie od"

  "Insert Enumeration"
  "Wstaw Wyliczenie"

  "Insert Text"
  "Wstaw stronę"

  "Install..."
  "Zainstalować"

  "Jump Backward"
  "Przeskoczy? do ty?u"

  "Jump Forward"
  "Skok do przodu"

  "Launcher"
  "Wyrzutnia"

  "Lock"
  "Zablokować"

  "Markers"
  "Marker"

  "Menu Bindings"
  "Wiązania menu"

  "Menus: About TKE"
  "Menu: O TKE"

  "Merge Panes"
  "Scalanie okienek"

  "Next Difference"
  "Nast?pna ró?nica"

  "Open Directory..."
  "Otwórz katalog"

  "Open Favorite"
  "Otwórz Ulubione"

  "Open File..."
  "Otwórz plik..."

  "Open Recent"
  "Otwórz poprzedni"

  "Paste"
  "\"

  "Paste and Format"
  "Pasty i format"

  "Plugins"
  "Add-on"

  "Plugins Menu: Create new plugin"
  "Plugins Menu: Utwórz nowy plugin"

  "Plugins Menu: Install plugin"
  "Plugins Menu: Zainstalować plugin"

  "Plugins Menu: Reload all plugins"
  "Plugins Menu: Przeładować wszystkie pluginy"

  "Plugins Menu: Uninstall plugin"
  "Plugins Menu: Odinstaluj plugin"

  "Preferences"
  "Preferencje"

  "Previous Difference"
  "Poprzednia ró?nica"

  "Profiling started"
  "Profilowanie zaczęło"

  "Profiling stopped"
  "Profilowanie zatrzymany"

  "Quit"
  "Porzucić"

  "Redo"
  "Ponów"

  "Reload"
  "Reload"

  "Remove All Markers"
  "Usu? wszystkie markery"

  "Remove From Current Line"
  "Usun?? z bie??cego wiersza"

  "Replace Line With Script"
  "Zamie? wiersz skryptu"

  "Reset User to Base"
  "Badanie użytkownika do bazy"

  "Restart TKE"
  "Uruchom ponownie TKE"

  "Save All"
  "Zapisz wszystkie"

  "Save As..."
  "Zapisz Jako..."

  "Save Current"
  "Zapisz bie??cy"

  "Select All"
  "Wybierz wszystko"

  "Select All Occurrences"
  "Zaznacz wszystkie wyst?pienia"

  "Select Next Occurrence"
  "Zaznacz nast?pne wyst?pienie"

  "Select Previous Occurrence"
  "Zaznacz poprzednie wyst?pienie"

  "Selected"
  "Wybrano"

  "Send Bug Report"
  "Wyślij raport o błędzie."

  "Send Feedback"
  "\"

  "Sessions"
  "Sesje"

  "Sessions Menu: Close current session"
  "Sesje Menu: Zamknięcia bieżącej sesji"

  "Sessions Menu: Delete session"
  "Sesje Menu: Usuwanie sesji"

  "Sessions Menu: Open session"
  "Sesje Menu: Otwarta sesja"

  "Sessions Menu: Save current session"
  "Sesje Menu: Zapisywanie bieżącej sesji"

  "Sessions Menu: Save sessions as"
  "Sesje Menu: Zapisać sesje jako"

  "Sessions Menu: Switch to session"
  "Sesje Menu: Przełącznik do sesji"

  "Set Syntax"
  "Składnia set"

  "Set Theme"
  "Ustaw Theme"

  "Set User to Global"
  "Zestaw użytkownika do globalnego"

  "Show Console"
  "Pokaż Console"

  "Show Diagnostic Logfile"
  "Pokaż diagnostyczne Logfile"

  "Show File Difference"
  "Pokaż plik różnica"

  "Show Last Profiling Report"
  "Pokaż Ostatni raport profilowania"

  "Show Line Numbers"
  "Pokaż numery linii"

  "Show Meta Characters"
  "Poka? znaki Meta"

  "Show Selected Line Change"
  "Poka? zmiany wybranej linii"

  "Show Sidebar"
  "Pokaż pasek"

  "Show Status Bar"
  "Pasek stanu"

  "Show Tab Bar"
  "Pasek kart"

  "Smart Indent"
  "Inteligentnego wcięcia"

  "Snippet"
  "Urywek"

  "Snippets"
  "Urywki"

  "Sort Tabs"
  "Sortuj Tabs"

  "Split View"
  "Podziel widok"

  "Start Profiling"
  "Zacznij Profilowanie"

  "Stop Profiling"
  "Przestań Profilowanie"

  "Switch To"
  "Przejd? na kart?"

  "Tabs"
  "Tab"

  "Text"
  "SMS"

  "Text Menu: Align cursors"
  "Tekst Menu: Wyrównać kursory"

  "Text Menu: Indent selected text"
  "Tekst Menu: Wcięcia zaznaczonego tekstu"

  "Text Menu: Insert enumeration"
  "Tekst Menu: Wstaw Wyliczenie"

  "Text Menu: Replace line with script"
  "Tekst Menu: Zamień wiersz skryptu"

  "Text Menu: Toggle comment"
  "Tekst Menu: Przełącz komentarz"

  "Text Menu: Unindent selected text"
  "Tekst Menu: Zmniejszenie wcięcia zaznaczonego tekstu"

  "Theme Creator"
  "Theme Creator"

  "Toggle Comment"
  "Prze??cznik komentarz"

  "Tools"
  "Narzędzia"

  "Tools Menu: Create new theme"
  "Menu narzędzia: Załóż nowy temat"

  "Tools Menu: Disable Vim mode"
  "Menu narzędzia: Wyłączenie trybu Vim"

  "Tools Menu: Edit TKE theme"
  "Menu narzędzia: Edytowanie tematu TKE"

  "Tools Menu: Enable Vim mode"
  "Menu narzędzia: Włączanie trybu Vim"

  "Tools Menu: Import TextMate theme"
  "Menu narzędzia: Import TextMate tematu"

  "Tools Menu: Restart TKE"
  "Menu narzędzia: Restart TKE"

  "Tools Menu: Show diagnostic logfile"
  "Menu narzędzia: Pokaż logfile diagnostyczne"

  "Tools Menu: Show last profiling report"
  "Menu narzędzia: Pokaż ostatni raport profilowania"

  "Tools Menu: Start profiling"
  "Menu narzędzia: Uruchomić profilowania"

  "Tools Menu: Stop profiling"
  "Menu narzędzia: Stop, profilowanie"

  "Undo"
  "Cofnij"

  "Unindent"
  "Unindent"

  "Uninstall..."
  "\"

  "Unlock"
  "\"

  "User Guide"
  "podręcznik użytkownika"

  "View"
  "Widok"

  "View Base"
  "Widok bazy"

  "View Global"
  "Widok globalny"

  "View Menu: Goto last tab"
  "Menu Widok: Ostatnia zakładka Goto"

  "View Menu: Goto next tab"
  "Menu Widok: Następną kartę Goto"

  "View Menu: Goto other pane"
  "Menu Widok: Goto inne okienka"

  "View Menu: Goto previous tab"
  "Menu Widok: Poprzednią kartę Goto"

  "View Menu: Hide console"
  "Menu Widok: Ukrywanie konsoli"

  "View Menu: Hide line numbers"
  "Menu Widok: Numery linii Ukryj"

  "View Menu: Hide meta characters"
  "Menu Widok: Ukryj meta znaków"

  "View Menu: Hide sidebar"
  "Menu Widok: Bocznym Ukryj"

  "View Menu: Hide status bar"
  "Menu Widok: Ukryj pasek stanu"

  "View Menu: Hide tab bar"
  "Menu Widok: Ukryj pasek kart"

  "View Menu: Merge panes"
  "Zobacz Menu: Okienek korespondencji seryjnej"

  "View Menu: Move to other pane"
  "Menu Widok: Przenieść do innego okienka"

  "View Menu: Show console"
  "Menu Widok: Konsoli Pokaż"

  "View Menu: Show line numbers"
  "Menu Widok: Numery linii Pokaż"

  "View Menu: Show meta characters"
  "Menu Widok: Pokaż meta znaków"

  "View Menu: Show sidebar"
  "Menu Widok: Bocznym Pokaż"

  "View Menu: Show status bar"
  "Menu Widok: Pokaż pasek stanu"

  "View Menu: Show tab bar"
  "Menu Widok: Pokaż pasek kart"

  "View Menu: Sort tabs"
  "Menu Widok: Sort tabs"

  "View Menu: Toggle split view mode"
  "Menu Widok: Przełącz widok tryb rozdzielny"

  "Vim Mode"
  "Tryb vim"

}

# plugins.tcl
msgcat::mcmset pl {

  "ERROR (%s,%s): %s"
  "BŁĄD (%s, %s): %s"

  "ERROR:  Plugin name already exists"
  "BŁĄD: Plugin nazwie już istnieje"

  "ERROR:  Plugin name is not valid (only alphanumeric and underscores are allowed)"
  "BŁĄD: Plugin nazwa nie jest ważna (tylko alfanumeryczne i podkreślenia są dozwolone)"

  "ERROR:  Unable to create plugin directory"
  "BŁĄD: Nie można utworzyć katalogu wtyczek"

  "ERROR:  Unable to write plugin files"
  "BŁĄD: Nie można zapisać plików wtyczek"

  "Enter plugin name"
  "Wpisz nazwę wtyczki"

  "Plugin %s installed"
  "Zainstalowane wtyczki% s"

  "Plugin %s uninstalled"
  "Odinstalowaniu wtyczki% s"

  "Plugin Errors"
  "Błędy plugin"

  "Plugins successfully reloaded"
  "Wtyczki pomyślnie załadowany"

  "Syntax errors found in selected plugins"
  "Błędy składniowe w wybranych wtyczek znalezionych"

}

# search.tcl
msgcat::mcmset pl {

  "%d substitutions done"
  "%d zastępstwa zrobić"

  "No files found in specified directories"
  "Nie ma plików znajdujących się w określonych katalogach"

  "No search results found"
  "Nie znaleziono żadnych wyników wyszukiwania"

  "Search wrapped to beginning of file"
  "Szukaj zawijane do początku pliku"

  "Search wrapped to end of file"
  "Szukaj zawinięte na końcu pliku"

}

# sidebar.tcl
msgcat::mcmset pl {

  "Add Parent Directory"
  "Katalog nadrzędny"

  "Close Directory Files"
  "Zamknij katalog plików"

  "Copy Pathname"
  "Skopiuj ?cie?k?"

  "Delete directory?"
  "Usuń katalog?"

  "Delete file?"
  "Usunąć plik?"

  "Directory Name:"
  "Nazwa katalogu:"

  "Duplicate"
  "Duplikuj"

  "File Name:"
  "Nazwie pliku"

  "Folder Name:"
  "Nazwa katalogu:"

  "Make Current Working Directory"
  "Dodać bieżący katalog roboczy"

  "New Directory"
  "Nowy katalog"

  "Open Directory Files"
  "Pliki katalog otwarty"

  "Refresh Directory Files"
  "Odśwież pliki katalogu"

  "Remove Parent from Sidebar"
  "Usuń Parent z Sidebar"

  "Remove from Sidebar"
  "Usuń z paska bocznego"

  "Rename"
  "Zmień nazwę"

  "Show Difference"
  "Pokaż różnicę"

}

# snippets.tcl
msgcat::mcmset pl {

  "Snippet: *"
  "Fragment kodu: *"

}

# syntax.tcl
msgcat::mcmset pl {

  "Syntax error in %s.syntax file"
  "Błąd składni w pliku s.syntax%"

  "Syntax:  %s"
  "Składnia:% s"

  "Theme:  %s"
  "Temat:% s"

}

# themer.tcl
msgcat::mcmset pl {

  "Create"
  "Utwórz"

  "Create New Theme"
  "Stwórz nowy motyw..."

  "Create custom"
  "Tworzenie niestandardowego"

  "ERROR:  Unable to read %s"
  "BŁĄD: Nie można odczytać% s"

  "ERROR:  Unable to write %s"
  "BŁĄD: Nie można zapisać% s"

  "Edit theme"
  "Edytuj temat"

  "Enter theme name"
  "Wpisz nazwę motywu"

  "Error:  Theme is not a supported theme"
  "Błąd: Temat nie jest obsługiwana motyw"

  "Import"
  "Import"

  "Import TextMate Theme"
  "Import TextMate Theme"

  "Name:"
  "Imię i nazwisko:"

  "OK"
  "OK"

  "Reset"
  "Resetuj"

  "Select theme"
  "Wybierz plik motywu"

}

# tke.tcl
msgcat::mcmset pl {

  "Edit theme?"
  "Edycja tematu?"

  "Import TextMate theme?"
  "Import TextMate temat?"

}

# tkedat.tcl
msgcat::mcmset pl {

  "Unable to open %s for reading"
  "Nie można otworzyć pliku%1 do odczytu."

}

# vim.tcl
msgcat::mcmset pl {

  "File %s successfully written"
  "Plik %s pomyślnie napisany"

  "Filename %s already exists"
  "Nazwa pliku %s już istnieje"

}

# General
msgcat::mcmset pl {

  "All"
  "Wszystko"

  "Cancel"
  "Anuluj"

  "Close"
  "Zamknij"

  "Delete"
  "Usuń"

  "Favorite"
  "Ulubione"

  "Find:"
  "\"

  "Move to Other Pane"
  "Przejść do innych okienku"

  "New File"
  "Nowy plik"

  "Open"
  "Otwarte"

  "Replace:"
  "\"

  "Save"
  "Zapisz"

  "Save As"
  "Zapisz jako"

  "Unable to open %s for writing"
  "Nie można otworzyć%1 do zapisu"

  "Unfavorite"
  "Unfavorite"

}

