# api.tcl
msgcat::mcmset pl {

  "Argument list to api::add_file was not an even key/value pair"
  "Lista argumentów API :: add_file nie było nawet parę klucz / wartość"

  "Plugin"
  "Wtyczka"

}

# bgproc.tcl
msgcat::mcmset pl {

  "Unable to run system command"
  "Nie można uruchomić polecenia systemu"

}

# diff.tcl
msgcat::mcmset pl {

  "    End: "
  "Koniec:"

  "    Start: "
  "Start:"

  "Enter difference command"
  "Wprowadź polecenie różnica"

  "Enter starting file"
  "Wpisz początkowy plik"

  "Update"
  "Aktualizuj"

}

# edit.tcl
msgcat::mcmset pl {

  "File successfully written"
  "Plik zapisany"

  "Filename already exists"
  "Nazwa pliku już istnieje"

}

# embed_tke.tcl
msgcat::mcmset pl {

  "Find:"
  "Odnaleźć:"

  "Replace:"
  "Zastąpić:"

}

# gui.tcl
msgcat::mcmset pl {

  "All"
  "Wszystko"

  "Case sensitivity"
  "Case sensitive i case insensitive"

  "Close All Tabs"
  "Zamknij wszystkie karty"

  "Close Other Tabs"
  "Zamknij pozostałe karty"

  "Close Other*"
  "Zamknij pozostałe*"

  "Close Tab"
  "Zamknij kartę"

  "Column"
  "Kolumna"

  "Copyright"
  "Prawa Autorskie"

  "Delete tab?"
  "Usuń kartę?"

  "Developer"
  "Deweloper"

  "Email"
  "Email"

  "Error"
  "Błąd"

  "Favorited"
  "Jako ulubione"

  "File already exists.  Use '!' to force an overwrite"
  "Plik już istnieje.  Użycie '!' wymusić zastępowaniem"

  "File attribute does not exist"
  "Atrybut pliku nie istnieje"

  "File index is out of range"
  "Wskaźnik pliku jest poza zakresem"

  "Image displayed in fill-in forms which closes the form UI.  Used in forms such as search, search/replace, and find in files."
  "Obraz wyświetlany w wypełnianie formularzy, który zamyka formularz UI.  Używane w formach, takich jak wyszukiwanie, wyszukiwania i zamiany i znaleźć w plikach."

  "Image used in tab menus to indicate that the file is associated with a difference view."
  "Obraz używany w karcie menu do wskazania, że plik jest związane z widokiem różnica."

  "Image used in tab menus to indicate that the file is locked."
  "Obraz używany w karcie menu do wskazania, że plik jest zablokowany."

  "Image used in tab menus to indicate that the file is readonly."
  "Obraz używany w karcie menu do wskazania, że plik jest tylko do odczytu."

  "Image used in tab to indicate that the tab contains a difference view."
  "Obraz używany w kartę do wskazania, że karta zawiera widok różnica."

  "Image used in tab to indicate that the tab's file is readonly."
  "Obraz używany w kartę do wskazania, że kartę plik jest tylko do odczytu."

  "Image used in tab to indicate that the tab’s file is locked."
  "Obraz używany w kartę do wskazania, że plik karta jest zablokowana."

  "Image used in tab which, when clicked, closes the tab."
  "Obraz używany w karcie, po kliknięciu, zamknięcie karty."

  "License"
  "Licencja"

  "Line"
  "Linia"

  "Locked"
  "Zablokowano"

  "Move"
  "Przesuń"

  "Must be in multicursor mode to insert numbers"
  "Musi być w trybie multicursor, aby wstawić numery"

  "No write permissions.  Use '!' to force write."
  "Brak prawa do zapisu.  Użycie '!' wymusić zapisu."

  "Release Type"
  "Typ wydania"

  "Reload file?"
  "Wczytaj plik na nowo?"

  "Replace"
  "Zastąp"

  "Save request"
  "Zapisz zlecenie"

  "Show in Sidebar"
  "Pokaż w pasku bocznym"

  "Starting number:"
  "Numer startowy:"

  "Tcl/Tk Version"
  "Wersji Tcl/Tk"

  "Total Characters"
  "Znaki na całkowitego"

  "Total Lines"
  "Wiersze podsumowań"

  "Unable to successfully parse number string"
  "Nie można pomyślnie przeanalizować ciąg liczb"

  "Unable to write file"
  "Nie można zapisać pliku"

  "Version"
  "Wersja"

}

# markers.tcl
msgcat::mcmset pl {

  "Marker name:"
  "Nazwa znacznik:"

}

# menus.tcl
msgcat::mcmset pl {

  "About"
  "Autor"

  "Absolute"
  "Bezwzględne"

  "Absolute line numbering"
  "Bezwzględne numerację"

  "Align Cursors"
  "Wyrówna? kursory"

  "Align cursors"
  "Wyrównać kursory"

  "Append Next Occurrence"
  "Dołącz następnego wystąpienia"

  "Append next occurrence"
  "Dokładać kolejne wystąpienie"

  "Auto-Indent"
  "Automatyczne wcięcia"

  "Bubble Down"
  "Bańka dół"

  "Bubble Up"
  "Bańka się"

  "Bubble lines down one line"
  "Bańka linie w dół o jeden wiersz"

  "Bubble lines up one line"
  "Bańka linie górę o jeden wiersz"

  "Change Working Directory"
  "Zmiana katalogu roboczego"

  "Change working directory"
  "Zmień katalog bieżący"

  "Character"
  "Charakter"

  "Check for Update"
  "Sprawdź aktualizacje"

  "Check for update"
  "Sprawdź aktualizacje"

  "Classic Mac"
  "Klasyczny Mac"

  "Clear All"
  "Czyść wszystko"

  "Close All"
  "Zamknij wszystkie"

  "Close Current"
  "Zamknij bieżącą"

  "Close all tabs"
  "Zamknij wszystkie karty"

  "Close current session"
  "Zamyka bieżącą kartę wraz z sesją"

  "Close current tab"
  "Zamknij bieżącą kartę"

  "Command"
  "Polecenie"

  "Command Result"
  "Wynik polecenia"

  "Convert case to lower"
  "Przekonwertować przypadek do obniżenia"

  "Convert case to title"
  "Przekonwertować przypadek tytuł"

  "Convert case to upper"
  "Przekonwertować przypadek do górnej"

  "Copy"
  "Kopiuj"

  "Copy text"
  "Kopiowanie tekstu"

  "Create"
  "Utwórz"

  "Create at Current Line"
  "Utwórz w bie??cym wierszu"

  "Create marker at current line"
  "Utworzyć znacznik w bieżącym wierszu"

  "Create new plugin"
  "Utwórz nowy plugin"

  "Current Line"
  "Bieżąca linia"

  "Current Number"
  "Numer bieżącego wiersza"

  "Current Word"
  "Aktualne słowa"

  "Cursor"
  "Kursor"

  "Cursor from Line Start"
  "Kursor z linii Start"

  "Cursor to Line End"
  "Kursora do końca linii"

  "Cut"
  "Cięcie"

  "Cut text"
  "Wycięcie tekstu"

  "Delete current file"
  "Usuń bieżący plik"

  "Delete current line"
  "Usuń bieżącą linię"

  "Delete current word"
  "Usuń bieżące słowo"

  "Delete from cursor to end of line"
  "Usuwanie od kursora do końca linii"

  "Delete from start of line to cursor"
  "Usuń z początku wiersza kursor"

  "Delete session"
  "Usuń sesji"

  "Delete template"
  "Usuń szablon"

  "Delete text between character"
  "Usuń tekst między znak"

  "Delete the current number"
  "Usuń bieżący numer"

  "Delete the whitespace to left of cursor"
  "Usuń spacje na lewo od kursora"

  "Delete the whitespace to right of cursor"
  "Usuń spacje na prawo od kursora"

  "Disable Vim mode"
  "Wyłączenie trybu Vim"

  "Display Text Info"
  "Tekst do wyświetlenia"

  "Display text information"
  "wyświetlić informacje"

  "Duplicate current file"
  "Duplikat pliku bieżącego"

  "Edit"
  "Edytować"

  "Edit Custom Abbreviations"
  "Edycja własnych skrótów"

  "Edit Language"
  "Zmień język"

  "Edit Session"
  "Edycja sesji"

  "Edit User"
  "Edycja użytkownika"

  "Edit custom Emmet abbreviations"
  "Edycja własnych skrótów Emmet"

  "Edit language snippets"
  "Edytować urywki języka"

  "Edit session current language preferences"
  "Edytuj preferencje językowe bieżącej sesji"

  "Edit session global preferences"
  "Globalne ustawienia sesji"

  "Edit template"
  "Edycja szablonu"

  "Edit user current language preferences"
  "Edytuj preferencje językowe bieżącego użytkownika"

  "Edit user global preferences"
  "Globalne ustawienia użytkownika"

  "Edit user menu bindings"
  "Edytuj powiązania menu użytkownika"

  "Edit user snippets"
  "Edytuj użytkownika urywki"

  "Enable Vim mode"
  "Włączanie trybu Vim"

  "Enumeration"
  "wyliczenie"

  "Expand Abbreviation"
  "Rozwiń skrót"

  "Expand Emmet abbreviation"
  "Rozwiń skrót Emmet"

  "Favorite file"
  "Ulubionych plików"

  "File"
  "Plik"

  "File Contents"
  "Zawartość pliku"

  "Find In Files"
  "Znajdź w plikach"

  "Find Matching Pair"
  "Znajdź pasujące pary"

  "Find and Replace"
  "Znajdź i zamień"

  "Find in files"
  "Znajdź w plikach"

  "Find matching character pair"
  "Znaleźć pasujące pary znaków"

  "Find next occurrence"
  "Znajdź kolejne wystąpienie"

  "Find previous occurrence"
  "Znaleźć poprzednie wystąpienie"

  "Fold All"
  "Fold Wszystko"

  "Fold Method"
  "Klapki metody"

  "Fold Selected"
  "Złóż wybranych"

  "Fold all"
  "Zwiń wszystko"

  "Fold selected code"
  "Złóż wybranego kodu"

  "Folding"
  "Składanie"

  "Format Text"
  "Formatowanie tekstu"

  "Format indentation for text"
  "Formacie wcięcia dla tekstu"

  "From Clipboard"
  "Ze schowka"

  "Global"
  "Główne"

  "Goto Last Tab"
  "Idź Ostatnio Tab"

  "Goto Next Tab"
  "Idź Następny Tab"

  "Goto Other Pane"
  "Idź Inne Pane"

  "Goto Previous Tab"
  "Idź do strony Poprzedni Tab"

  "Goto last tab"
  "Ostatnia zakładka goto"

  "Goto next difference"
  "Goto następnego różnica"

  "Goto next tab"
  "Następną kartę goto"

  "Goto other pane"
  "Goto inne okienka"

  "Goto previous difference"
  "Poprzednia różnica"

  "Goto previous tab"
  "Poprzednia zakładka"

  "Help"
  "Pomoc"

  "Hide Console"
  "Ukryj konsoli"

  "Hide Line Numbers"
  "Ukryj numery linii"

  "Hide Marker Map"
  "Ukryj znacznik mapy"

  "Hide Meta Characters"
  "Ukryj Meta znaków"

  "Hide Sidebar"
  "Ukryj pasek"

  "Hide Status Bar"
  "Ukryj na pasku stanu"

  "Hide Tab Bar"
  "Ukryj pasek zakładek"

  "Hide console"
  "Ukrywanie konsoli"

  "Hide line numbers"
  "Ukryj numery linii"

  "Hide marker map"
  "Ukryj znacznik mapy"

  "Hide meta characters"
  "Ukryj meta znaków"

  "Hide sidebar"
  "Ukryj pasek"

  "Hide status bar"
  "Ukryj na pasku stanu"

  "Hide tab bar"
  "Ukryj pasek kart"

  "Indent"
  "Einzug"

  "Indent Off"
  "Wcięcie od"

  "Indent selected text"
  "Wcięcia zaznaczonego tekstu"

  "Indentation"
  "Wcięcia"

  "Insert"
  "Wstaw"

  "Insert command result after current line"
  "Wstaw wynik polecenia po bieżącym wierszu"

  "Insert enumeration"
  "Wstaw Wyliczenie"

  "Insert file contents after current line"
  "Wstaw zawartość pliku po bieżącym wierszu"

  "Insert from clipboard"
  "Wstawianie ze schowka"

  "Insert line above current line"
  "Wstaw wiersz powyżej bieżącej linii"

  "Insert line below current line"
  "Wstaw wiersz poniżej bieżącej linii"

  "Insert snippet"
  "Wstawianie urywków"

  "Install"
  "Instaluj"

  "Install plugin"
  "Zainstaluj wtyczkę"

  "Join Lines"
  "Połącz wiersze"

  "Join lines"
  "Połącz wiersze"

  "Jump Backward"
  "Skocz do tyłu"

  "Jump Forward"
  "Skok do przodu"

  "Jump To Line"
  "Przejdź do wiersza"

  "Jump backward"
  "Przeskoczyć do tyłu"

  "Jump forward"
  "Skok do przodu"

  "Jump to line"
  "Przejdź do wiersza"

  "Language"
  "Język"

  "Launcher"
  "Wyrzutnia"

  "Line Above Current"
  "Linii powyżej bieżącego"

  "Line Below Current"
  "Wiersz pod prąd"

  "Line Ending"
  "Zakończenia linii"

  "Line Number"
  "Numer wiersza"

  "Line Numbering"
  "Numeracja wierszy"

  "Lock"
  "Zablokować"

  "Lock file"
  "Blokada pliku"

  "Lower Case"
  "Małe litery"

  "Manual"
  "Manual"

  "Markers"
  "Marker"

  "Menu"
  "Menu"

  "Menu Bindings"
  "Wiązania menu"

  "Merge Panes"
  "Scalanie okienek"

  "Merge panes"
  "Scalanie okienek"

  "Move Cursors Down"
  "Przesunąć kursory"

  "Move Cursors Left"
  "Przenieść kursory lewo"

  "Move Cursors Right"
  "Przenieść prawo kursory"

  "Move Cursors Up"
  "Wrzucic kursory"

  "Move cursor to bottom of screen"
  "Przesuń kursor do dolnej części ekranu"

  "Move cursor to end of current line"
  "Przeniesienie kursora do końca linii bieżącej"

  "Move cursor to first line"
  "Przesuń kursor do pierwszego wiersza"

  "Move cursor to last line"
  "Przesunąć kursor do ostatniego wiersza"

  "Move cursor to middle of screen"
  "Przesuń kursor na środku ekranu"

  "Move cursor to next page"
  "Przesuń kursor do następnej strony"

  "Move cursor to next word"
  "Przeniesienie kursora do następnego wyrazu"

  "Move cursor to previous page"
  "Przesuń kursor do poprzedniej strony"

  "Move cursor to previous word"
  "Przesuń kursor do poprzedniego wyrazu"

  "Move cursor to start of current line"
  "Przesunięcie kursora na początek bieżącego wiersza"

  "Move cursor to top of screen"
  "Przesuń kursor do góry ekranu"

  "Move multicursors down one line"
  "Multicursors ruch w dół o jeden wiersz"

  "Move multicursors left one line"
  "Przenieść multicursors lewej jedna linia"

  "Move multicursors right one line"
  "Przenieść multicursors prawo jednej linii"

  "Move multicursors up one line"
  "Multicursors ruch w górę o jeden wiersz"

  "Move to First Line"
  "Przesuń do pierwszej linii"

  "Move to Last Line"
  "Przejść do ostatniego wiersza"

  "Move to Line End"
  "Przenieść do końca linii"

  "Move to Line Start"
  "Przenieść do linii Start"

  "Move to Next Page"
  "Przesuń na dół do następnej strony"

  "Move to Next Word"
  "Przejść do następnego wyrazu"

  "Move to Previous Page"
  "Przesuń w górę do poprzedniej strony"

  "Move to Previous Word"
  "Przejść do poprzedniego wyrazu"

  "Move to Screen Bottom"
  "Przesuń do ekranu dolnej"

  "Move to Screen Middle"
  "Przenieść na ekran Bliskim"

  "Move to Screen Top"
  "Przenieść na ekran Top"

  "Move to other pane"
  "Przenieść do innego okienka"

  "New From Template"
  "Nowy z szablonu"

  "New Window"
  "Nowe Okno"

  "New file"
  "Nowy plik"

  "New file from template"
  "Nowy plik z szablonu"

  "New window"
  "Nowe okno"

  "Next Difference"
  "Następna różnica"

  "Open Directory"
  "Otwórz katalog"

  "Open Favorite"
  "Otwórz Ulubione"

  "Open File"
  "Nazwa pliku"

  "Open Recent"
  "Otwórz poprzedni"

  "Open directory"
  "Otwórz katalog"

  "Open file"
  "Otwórz plik"

  "Paste"
  "Pasta"

  "Paste and Format"
  "Wklej i format"

  "Paste and format text from clipboard"
  "Wklej i format tekstu ze schowka"

  "Paste text from clipboard"
  "Wklej tekst ze schowka"

  "Plugins"
  "Add-on"

  "Preferences"
  "Preferencje"

  "Previous Difference"
  "Poprzedni Różnica"

  "Profiling Report Sorted By"
  "Profilowanie według raportu"

  "Profiling started"
  "Profilowanie zaczęło"

  "Profiling stopped"
  "Profilowanie zatrzymany"

  "Quit"
  "Porzucić"

  "Quit application"
  "Zakończ program"

  "Redo"
  "Ponów"

  "Relative"
  "Względny"

  "Relative line numbering"
  "Względne numerację"

  "Reload"
  "Przeładować"

  "Reload all plugins"
  "Przeładować wszystkie pluginy"

  "Reload snippets"
  "Fragmenty kodu Doładowującego"

  "Reload template information"
  "Załaduj ponownie szablon informacji"

  "Remove All Markers"
  "Usuń wszystkie znaczniki"

  "Remove Fold"
  "Usunąć fałd"

  "Remove From Current Line"
  "Usuń z bieżącej linii"

  "Remove all markers"
  "Usuń wszystkie markery"

  "Remove fold on current line"
  "Usunąć fałd na bieżącej linii"

  "Remove marker from current line"
  "Usuń znacznik z bieżącego wiersza"

  "Rename current file"
  "Zmiana nazwy bieżącego pliku"

  "Reopen File"
  "Otwórz plik"

  "Reopen current file"
  "Ponownie otworzyć bieżącego pliku"

  "Replace Line With Script"
  "Wymień Line z Script"

  "Replace line with script"
  "Wymień Line z Script"

  "Reset User to Base"
  "Badanie użytkownika do bazy"

  "Restart"
  "Zrestartuj"

  "Run"
  "Uruchom"

  "Run theme editor"
  "Motyw Editor"

  "Save All"
  "Zapisz wszystkie"

  "Save As Template"
  "Zapisz jako szablon"

  "Save Current"
  "Zapisz bie??cy"

  "Save Selection As"
  "Zapisz zaznaczenie jako"

  "Save all files"
  "Zapisz wszystkie pliki"

  "Save current session"
  "Zapisz bieżącą sesję"

  "Save file"
  "Zapisz plik"

  "Save file as"
  "Zapisz plik jako"

  "Save file as template"
  "Zapisz jako szablon"

  "Save selected lines"
  "Zapisz wybrane wiersze"

  "Save sessions as"
  "Zapisać sesje jako"

  "Select All"
  "Wybierz wszystko"

  "Select All Occurrences"
  "Wybierz wszystkie wystąpienia"

  "Select Next Occurrence"
  "Wybierz następnego wystąpienia"

  "Select Previous Occurrence"
  "Wybierz poprzednie wystąpienie"

  "Select all occurrences"
  "Wybierz wszystkie wystąpienia"

  "Select all text"
  "Zaznacz cały tekst"

  "Send Bug Report"
  "Wyślij raport o błędzie"

  "Send Feedback"
  "Wyślij opinię"

  "Send bug report"
  "Wyślij raport o błędzie"

  "Send feedback"
  "Prześlij opinię"

  "Sessions"
  "Sesje"

  "Set Syntax"
  "Składnia set"

  "Set Theme"
  "Ustaw Theme"

  "Set User to Global"
  "Zestaw użytkownika do globalnego"

  "Set current file line ending to CR for Classic Mac"
  "Ustaw bieżący plik lini do CR dla Classic Mac"

  "Set current file line ending to CRLF for Windows"
  "Ustaw bieżący plik lini do CRLF dla Windows"

  "Set current file line ending to LF for Unix"
  "Ustaw bieżący plik lini do LF dla Unix"

  "Set folding method to manual"
  "Zestaw składany Metoda do podręcznika"

  "Set folding method to none"
  "Zestaw składany Metoda none"

  "Set folding method to syntax"
  "Zestaw składany Metoda do składni"

  "Set indent mode to"
  "Ustawiono tryb tiret"

  "Set user bindings to global bindings"
  "Zestaw powiązania użytkownika do globalnych powiązań"

  "Set user preferences to global preferences"
  "Ustawić preferencje użytkownika do globalnych preferencji"

  "Show Console"
  "Pokaż Console"

  "Show Diagnostic Logfile"
  "Pokaż diagnostyczne Logfile"

  "Show File Difference"
  "Pokaż plik różnica"

  "Show Last Profiling Report"
  "Pokaż Ostatni raport profilowania"

  "Show Line Numbers"
  "Pokaż numery linii"

  "Show Marker Map"
  "Pokaż Mapa znaczników"

  "Show Meta Characters"
  "Pokaż Meta Postacie"

  "Show Selected Line Change"
  "Pokaż wybraną linię Zmień"

  "Show Sidebar"
  "Pokaż pasek"

  "Show Status Bar"
  "Pasek stanu"

  "Show Tab Bar"
  "Pasek kart"

  "Show console"
  "Pokaż konsolę"

  "Show diagnostic logfile"
  "Pokaż diagnostyczne logfile"

  "Show file difference"
  "Pokaż plik różnica"

  "Show last profiling report"
  "Pokaż ostatnie sprawozdanie do profilowania"

  "Show line numbers"
  "Pokaż numery linii"

  "Show marker map"
  "Pokaż Mapa znaczników"

  "Show meta characters"
  "Pokaż znaki meta"

  "Show selected line change"
  "Pokaż zmiany wybranej linii"

  "Show sidebar"
  "Pokaż pasek"

  "Show status bar"
  "Pasek statusu"

  "Show tab bar"
  "Pasek kart"

  "Smart Indent"
  "Inteligentnego wcięcia"

  "Snippet"
  "Urywek"

  "Snippets"
  "Urywki"

  "Sort Tabs"
  "Sortuj Tabs"

  "Sort tabs"
  "Sortowanie kart"

  "Start Profiling"
  "Zacznij Profilowanie"

  "Start profiling"
  "Uruchomić profilowania"

  "Stop Profiling"
  "Zatrzymaj profilowanie"

  "Stop profiling"
  "Zatrzymaj profilowanie"

  "Switch To"
  "Przełącz na"

  "Switch to session"
  "Przełącz się na tą sesję"

  "Tabs"
  "Tab"

  "Templates"
  "Szablony"

  "Text Between Character"
  "Tekst pomiędzy znaków"

  "Title Case"
  "Nr sprawy i nazwa"

  "Toggle Case"
  "Przypadku przełącznika"

  "Toggle Comment"
  "Prze??cznik komentarz"

  "Toggle case of current character"
  "Przypadku przełącznika postac"

  "Toggle comment"
  "Przełącznik komentarz"

  "Toggle split view mode"
  "Przełącz widok tryb rozdzielny"

  "Tools"
  "Narzędzia"

  "Transform"
  "przekształcać"

  "Undo"
  "Cofnij"

  "Unfavorite file"
  "Unfavorite pliku"

  "Unfold All"
  "Rozwiń wszystkieCopy "

  "Unfold all"
  "Rozwiń wszystko"

  "Unindent"
  "Unindent"

  "Unindent selected text"
  "Zmniejszenie wcięcia zaznaczonego tekstu"

  "Uninstall"
  "Odinstalowanie"

  "Uninstall plugin"
  "Odinstaluj wtyczkę"

  "Unix"
  "Unix"

  "Unlock"
  "Odblokować"

  "Unlock file"
  "Otworzyć plik"

  "Upper Case"
  "Wielkie litery"

  "User Guide"
  "podręcznik użytkownika"

  "View"
  "Widok"

  "View Base"
  "Widok bazy"

  "View Global"
  "Widok globalny"

  "View base preferences file"
  "Widok podstawowy plik"

  "View global menu bindings"
  "Zobacz menu globalnego powiązania"

  "View user guide"
  "Zobacz instrukcja"

  "Vim Mode"
  "Tryb vim"

  "Whitespace Backward"
  "Spacji do tyłu"

  "Whitespace Forward"
  "Spacji do przodu"

  "Windows"
  "Windows"

}

# plugins.tcl
msgcat::mcmset pl {

  "Always grant from developer"
  "Zawsze przyznać od dewelopera"

  "ERROR"
  "BŁĄD"

  "ERROR:  Plugin name already exists"
  "BŁĄD: Plugin nazwie już istnieje"

  "ERROR:  Plugin name is not valid (only alphanumeric and underscores are allowed)"
  "BŁĄD: Plugin nazwa nie jest ważna (tylko alfanumeryczne i podkreślenia są dozwolone)"

  "ERROR:  Unable to create plugin directory"
  "BŁĄD: Nie można utworzyć katalogu wtyczek"

  "ERROR:  Unable to write plugin files"
  "BŁĄD: Nie można zapisać plików wtyczek"

  "Enter plugin name"
  "Wpisz nazwę wtyczki"

  "Grant"
  "Grant"

  "Grant permission?"
  "pozwolenie Grant?"

  "OK"
  "OK"

  "Plugin Errors"
  "Błędy plugin"

  "Plugin Trust Requested"
  "Plugin Zaufanie Wnioskowana"

  "Plugin installed"
  "Plugin zainstalowałem"

  "Plugin requires permission to view or modify your system."
  "Wtyczka wymaga uprawnień do oglądania lub modyfikacji systemu."

  "Plugin uninstalled"
  "Plugin odinstalować"

  "Plugins successfully reloaded"
  "Wtyczki pomyślnie załadowany"

  "Reject"
  "Odrzucenie"

  "Syntax errors found in selected plugins"
  "Błędy składniowe w wybranych wtyczek znalezionych"

}

# search.tcl
msgcat::mcmset pl {

  "No files found in specified directories"
  "Nie ma plików znajdujących się w określonych katalogach"

  "No search results found"
  "Nie znaleziono żadnych wyników wyszukiwania"

  "Search wrapped to beginning of file"
  "Szukaj zawijane do początku pliku"

  "Search wrapped to end of file"
  "Szukaj zawinięte na końcu pliku"

  "substitutions done"
  "zastępstwa zrobione"

}

# sessions.tcl
msgcat::mcmset pl {

  "Save session?"
  "Zapisać sesję?"

  "Session state will be lost if not saved"
  "Stan sesji zostaną utracone, jeśli nie został zapisany"

}

# sidebar.tcl
msgcat::mcmset pl {

  "Add Parent Directory"
  "Katalog nadrzędny"

  "Close Directory Files"
  "Zamknij katalog plików"

  "Copy Pathname"
  "Kopiowanie ścieżka"

  "Delete directories?"
  "Usuwanie katalogów?"

  "Delete directory?"
  "Usuń katalog?"

  "Delete file?"
  "Usunąć plik?"

  "Delete files?"
  "Usuń pliki"

  "Directory Name:"
  "Nazwa katalogu:"

  "Folder Name:"
  "Nazwa katalogu:"

  "Image displayed in sidebar to indicate that a file is currently opened in an editing buffer."
  "Obraz wyświetlany na pasku bocznym do wskazania, że plik jest obecnie otwarte w edycji buforu."

  "Make Current Working Directory"
  "Dodać bieżący katalog roboczy"

  "New Directory"
  "Nowy katalog"

  "New File From Template"
  "Nowy z szablonu"

  "Open Directory Files"
  "Pliki katalog otwarty"

  "Refresh Directory Files"
  "Odśwież pliki katalogu"

  "Remove Parent from Sidebar"
  "Usuń Parent z Sidebar"

  "Remove from Sidebar"
  "Usuń z paska bocznego"

  "Show Difference"
  "Pokaż różnicę"

}

# snippets.tcl
msgcat::mcmset pl {

  "Snippet: *"
  "Fragment kodu: *"

}

# syntax.tcl
msgcat::mcmset pl {

  "Syntax error in syntax file"
  "Błąd składni w składni pliku"

}

# templates.tcl
msgcat::mcmset pl {

  "Delete template?"
  "Usuń szablon"

  "Template"
  "Szablon"

  "Template Name"
  "Nazwa szablonu"

  "deleted"
  "Usunięte"

  "saved"
  "zapisano"

  "will be permanently deleted"
  "zostaną trwale usunięte"

}

# theme.tcl
msgcat::mcmset pl {

  "Background (trough) color used in the sidebar scrollbar."
  "Kolor tła (koryta), stosowany na pasku przewijania paska bocznego."

  "Background (trough) color used in the text scrollbars."
  "Kolor tła (koryta), stosowany w paski przewijania tekstu."

  "Background color for all sidebar items that are not selected."
  "Kolor tła dla wszystkich elementów paska bocznego, które nie są zaznaczone."

  "Background color for all sidebar items that are selected."
  "Kolor tła dla wszystkich elementów paska bocznego, które są zaznaczone."

  "Background color in difference viewer that shows added lines."
  "Kolor tła w podglądzie różnica, która pokazuje dodane linie."

  "Background color in difference viewer that shows deleted lines."
  "Kolor tła w podglądzie różnica, która pokazuje usunięte wiersze."

  "Background color of insertion cursor and background marker colors."
  "Kolor tła i markerów kursor wstawiania tła kolorach."

  "Background color of the editing buffer."
  "Kolor tła edycji buforu."

  "Background color to display when a button-like ttk widget is pressed."
  "Kolor tła do wyświetlenia, gdy widget ttk jak przycisk jest naciśnięty."

  "Background color to use for selected text."
  "Kolor tła dla zaznaczonego tekstu."

  "Background color used for all other tabs that are not the current/active tab in the tabbar."
  "Kolor tła używane dla wszystkich innych kart, które są nie prąd/aktywnej karty w tabbar."

  "Background color used for the current/active menu item."
  "Kolor tła używane dla elementu menu bieżącego/aktywny."

  "Background color used for the current/active tab in the tabbar."
  "Kolor używany do prądu/aktywnej karty w tabbar tła."

  "Background color used in highlighted text."
  "Kolor tła w podświetlonego tekstu."

  "Background color used in menus."
  "Kolor tła w menu."

  "Background color used in the tabbar area."
  "Kolor używany w obszarze tabbar tła."

  "Color of border drawn around active editing buffer."
  "Kolor obramowania rysowane wokół aktywnej edycji buforu."

  "Color of ttk entry widget text border when the entry has keyboard focus."
  "Kolor ttk wpis widget tekst granicy wpis ma klawiaturę."

  "Color used to draw the warning width line in the editing buffer (as well as the line separating the gutter from the editing buffer)."
  "Kolor używany do rysowania linii szerokości ostrzeżenie w buforze edycji (jak również linię oddzielającą rynny z edycji buforu)."

  "Default 'darkcolor' for all ttk widgets."
  "Domyślnie 'darkcolor' dla wszystkich TTK widgetów."

  "Default background color to use for all ttk widgets that are in a disabled state."
  "Domyślny kolor tła dla wszystkich ttk wzory, które są w stanie wyłączonym."

  "Default background color to use for all ttk widgets when the mouse cursor hovers over the widget."
  "Domyślny kolor tła do wykorzystania wszystkie wzory ttk, gdy kursor myszy najedzie widżetu."

  "Default background color to use for all ttk widgets."
  "Domyślny kolor tła dla wszystkich widżetów ttk."

  "Default border color for all ttk widgets."
  "Domyślny kolor obramowania dla wszystkich widżetów ttk."

  "Default color for non-syntax highlighted text."
  "Domyślny kolor dla non składnia podświetlonego tekstu."

  "Default foreground text color to use for all ttk widgets that are in a disabled state."
  "Domyślny kolor tekstu pierwszego planu dla wszystkich ttk wzory, które są w stanie wyłączonym."

  "Default foreground text color to use for all ttk widgets."
  "Domyślnie tekst kolorem dla wszystkich widżetów ttk."

  "Determines the number of grips strips to display in the grip area between resizable panes."
  "Określa liczbę uchwytów pasków do wyświetlania w obszarze przyczepność między okienkami o zmiennym rozmiarze."

  "Determines the thickness of the grip area between resizable panes."
  "Określa grubość obszaru przyczepność między okienkami o zmiennym rozmiarze."

  "ERROR:  Unable to read"
  "BŁĄD: Nie można odczytać"

  "Foreground (slider) color used in the sidebar scrollbar."
  "Kolor pierwszoplanowy (suwak) używane na pasku przewijania paska bocznego."

  "Foreground (slider) color used in the text scrollbars."
  "Kolor pierwszoplanowy (suwak) używane w paski przewijania tekstu."

  "Foreground color used in menu items with checks or buttons."
  "Kolor pierwszoplanowy w elementy menu z przycisków lub kontroli."

  "Foreground text color for strings."
  "Kolorem tekstu dla ciągów."

  "Foreground text color to use for all miscellaneous1 labeled text."
  "Kolorem tekstu dla wszystkich miscellaneous1 oznaczony jako tekst."

  "Foreground text color to use for all miscellaneous2 labeled text."
  "Kolorem tekstu dla wszystkich miscellaneous2 oznaczony jako tekst."

  "Foreground text color to use for all miscellaneous3 labeled text."
  "Kolorem tekstu dla wszystkich miscellaneous3 oznaczony jako tekst."

  "Foreground text color to use for comments."
  "Kolorem tekstu dla komentarzy."

  "Foreground text color to use for displaying line numbers."
  "Kolorem tekstu umożliwia wyświetlanie numerów linii."

  "Foreground text color to use for displaying numbers."
  "Kolorem tekstu użyć do wyświetlania liczb."

  "Foreground text color to use for language-specific keywords."
  "Kolorem tekstu, aby użyć słów kluczowych języka."

  "Foreground text color to use for language-specific punctuation."
  "Kolorem tekstu dla określonego języka interpunkcja."

  "Foreground text color to use for meta syntax."
  "Kolorem tekstu dla meta składni."

  "Foreground text color to use for precompiler syntax."
  "Kolorem tekstu, aby użyć składni precompiler."

  "Foreground text color to use for selected text."
  "Kolorem tekstu dla zaznaczonego tekstu."

  "Foreground text color used for all other tabs that are not the current/active tab in the tabbar."
  "Tekstu kolorem używane dla wszystkich innych kart, które są nie prąd/aktywnej karty w tabbar."

  "Foreground text color used for menus item that are disabled."
  "Tekstu kolorem używany dla element menu, które są wyłączone."

  "Foreground text color used for the current/active menu item."
  "Tekstu kolorem używany dla elementu menu bieżącego/aktywny."

  "Foreground text color used for the current/active tab in the tabbar."
  "Tekstu kolorem używane dla bieżącego/aktywnej karty w tabbar."

  "Foreground text color used in menus."
  "Pierwszego planu kolor tekstu w menu."

  "Foreground text/image color used in tabbar and tabs."
  "Kolorem tekstu i obrazu używany w tabbar i karty."

  "Images"
  "Grafiki"

  "Maximum thickness of the text scrollbar when it is active."
  "Maksymalna grubość paska przewijania tekstu, gdy jest aktywny."

  "Maximum thickness of the text scrollbars when they are active."
  "Maksymalna grubość przewijania tekstu, gdy są one aktywne."

  "Menu Options"
  "Opcje menu"

  "Menu relief value."
  "Wartość pomocy menu."

  "Pixel height of the tabbar widget."
  "Pikseli wysokości tabbar widget."

  "Relief used in drawing the tabs."
  "Ulgi w rysunek karty."

  "Relief value of the sidebar area."
  "Wartość ulgi bocznym obszarze."

  "Sidebar Options"
  "Opcje bocznego panelu"

  "Sidebar Scrollbar Options"
  "Sidebar Opcje paska przewijania"

  "Specifies the color to display around the sidebar when the sidebar does not have the focus."
  "Określa kolor, aby wyświetlić wokół bocznym pasku bocznym nie ma fokusu."

  "Specifies the color to display around the sidebar when the sidebar has the focus."
  "Określa kolor, aby wyświetlić wokół bocznym pasku bocznym ma fokus."

  "Specifies the default background color to use for text that is selected in a standard ttk widget (this does not include the editing buffer)."
  "Określa domyślny kolor tła dla tekstu, który jest wybrany w widżetu standardowe ttk (nie dotyczy edycji buforu)."

  "Specifies the default foreground text color to use for text that is selected in a standard ttk widget (this does not include the editing buffer)."
  "Określa domyślny kolor tekstu pierwszego planu dla tekstu, który jest wybrany w widżetu standardowe ttk (nie dotyczy edycji buforu)."

  "Specifies the default relief to use when drawing ttk widgets."
  "Określa domyślny ulgę podczas rysowania widżetów ttk."

  "Specifies the disclosure image style to use in the sidebar."
  "Określa styl obrazu ujawnienie w pasku bocznym."

  "Specifies the pixel thickness of the highlight line."
  "Określa grubość pikseli linii podkreślenia."

  "Syntax Colors"
  "Składnia Kolory"

  "Tab Options"
  "Opcje Tab"

  "Text Scrollbar Options"
  "Tekst Opcje paska przewijania"

  "Text color for all sidebar items that are not selected."
  "Kolor tekstu dla wszystkich elementów paska bocznego, które nie są zaznaczone."

  "Text color for all sidebar items that are selected."
  "Kolor tekstu dla wszystkich elementów paska bocznego, które są zaznaczone."

  "ttk Widget Colors"
  "ttk Widget Kolory"

}

# themer.tcl
msgcat::mcmset pl {

  "   Show All"
  "Zobacz wszystko"

  "   Show Category"
  "Pokaż Kategoria"

  "   Show Color"
  "Pokaż Kolor"

  "   Show Selected Option"
  "Pokaż Wybrana opcja"

  "   Show Selected Value"
  "wybrana wartość"

  "Categories"
  "Kategorie"

  "Change Base Color"
  "Zmień Kolor podstawowy"

  "Choose Theme"
  "Wybierz Motyw"

  "Custom Directory"
  "Niestandardowe katalog"

  "Custom..."
  "Zdefiniuj..."

  "Delete swatch?"
  "Usuń próbkę?"

  "Description"
  "Opis"

  "Details"
  "Szczegóły"

  "Done"
  "Gotowe"

  "Export"
  "Exportuj"

  "GIF Photo"
  "GIF zdjęcie"

  "Import"
  "Import"

  "Import BMP Data"
  "Import BMP danych"

  "Import BMP Mask"
  "Import BMP Maska"

  "Import Error"
  "błąd importu"

  "Import Theme File"
  "Temat importu pliku"

  "Installation Directory"
  "Instalacja katalog"

  "Modifications"
  "Zmiany"

  "One-Color Bitmap"
  "Bitmap jednokolorowa"

  "Preview"
  "Podgląd"

  "Relief: "
  "Ulga: "

  "Save As:"
  "Zapisz jako:"

  "Save theme changes?"
  "Zapisz zmiany motywu?"

  "Select Directory"
  "Wybierz katalog"

  "Swatch"
  "Swatch Group"

  "Swatch Colors"
  "Swatch Kolory"

  "Table Filters"
  "Filtry Tabela"

  "The current theme has unsaved changes"
  "Obecny temat ma niezapisane zmiany"

  "Tree Style: "
  "Drzewo Styl: "

  "Two-Color Bitmap"
  "Bitmap dwóch kolorów"

  "User Directory"
  "Katalog użytkownika"

  "Value"
  "Wartość"

  "Value: "
  "Wartość:"

}

# themes.tcl
msgcat::mcmset pl {

  "Theme"
  "Temat"

  "Theme:*"
  "Temat:*"

}

# tke.tcl
msgcat::mcmset pl {

  "Import TKE theme?"
  "Import TKE tematem?"

  "Import TextMate theme?"
  "Import TextMate temat?"

}

# tkedat.tcl
msgcat::mcmset pl {

  "Unable to read"
  "Nie można czytać pliku"

}

# vim.tcl
msgcat::mcmset pl {

  "File format unrecognized"
  "Nierozpoznany format pliku"

  "Filename directory does not exist"
  "Nazwa_pliku katalog nie istnieje"

  "Folding method unrecognized"
  "Składane Metoda nierozpoznana"

  "Illegal modelines value"
  "Nielegalne ModeLine wartość"

  "Number width not a number"
  "Numer szerokość nie"

  "Shiftwidth value is not an integer"
  "Wartość Shiftwidth nie jest liczbą całkowitą"

  "Tabstop value is not an integer"
  "TabStop wartość nie jest liczbą całkowitą"

  "Unrecognized vim option"
  "Vim Nierozpoznana opcja"

}

# General
msgcat::mcmset pl {

  "Cancel"
  "Anuluj"

  "Close"
  "Zamknij"

  "Delete"
  "Usuń"

  "Duplicate"
  "Duplikuj"

  "Favorite"
  "Ulubione"

  "File Name:"
  "Nazwie pliku:"

  "Find"
  "Odnaleźć"

  "Move to Other Pane"
  "Przejść do innych okienku"

  "New File"
  "Nowy plik"

  "None"
  "Brak"

  "Open"
  "Otwarte"

  "Rename"
  "Zmień nazwę"

  "Save"
  "Zapisz"

  "Save As"
  "Zapisz jako"

  "Split View"
  "Podziel widok"

  "Syntax"
  "Składnia"

  "Theme Editor"
  "Motyw Editor"

  "Unable to write"
  "Nie można zapisać"

  "Unfavorite"
  "Usuń z ulub"

}

