# api.tcl
msgcat::mcmset pt {

  "Argument list to api::add_file was not an even key/value pair"
  "Lista de argumentos a api :: add_file não era um par ainda de chave / valor"

  "Plugin"
  "Plugin"

}

# bgproc.tcl
msgcat::mcmset pt {

  "Unable to run system command"
  "Não é possível executar o comando do sistema"

}

# diff.tcl
msgcat::mcmset pt {

  "    End: "
  "Término:"

  "    Start: "
  "Início:"

  "Enter difference command"
  "Digite o comando de diferença"

  "Enter starting file"
  "Insira o arquivo inicial"

  "Update"
  "Atualizar"

}

# edit.tcl
msgcat::mcmset pt {

  "File successfully written"
  "Arquivo gravado com êxito"

  "Filename already exists"
  "Nome do arquivo já existe."

}

# embed_tke.tcl
msgcat::mcmset pt {

  "Find:"
  "Encontrar"

  "Replace:"
  "Substituir:"

}

# gui.tcl
msgcat::mcmset pt {

  "All"
  "Tudo"

  "Case sensitivity"
  "Distinção entre maiúsculas e minúsculas"

  "Close All Tabs"
  "Fechar todas as guias"

  "Close Other Tabs"
  "Fechar as Outras Páginas"

  "Close Other*"
  "Feche os outros separadores"

  "Close Tab"
  "Fechar a Página"

  "Column"
  "Coluna"

  "Copyright"
  "Direitos de Autor"

  "Delete tab?"
  "Excluir guia?"

  "Developer"
  "Desenvolvedor"

  "Email"
  "E-mail"

  "Error"
  "Erro"

  "Favorited"
  "Favorito"

  "File already exists.  Use '!' to force an overwrite"
  "Arquivo já existe.  Uso '!' para forçar uma sobrescrever"

  "File attribute does not exist"
  "Atributo de arquivo não existe"

  "File index is out of range"
  "Índice arquivo está fora do intervalo"

  "Image displayed in fill-in forms which closes the form UI.  Used in forms such as search, search/replace, and find in files."
  "Imagem exibida em formulários de preenchimento que fecha o formulário da interface do usuário.  Usado em formulários como busca, busca/substituição e localizar em arquivos."

  "Image used in tab menus to indicate that the file is associated with a difference view."
  "Imagem usada nos menus de guia para indicar que o arquivo está associado uma visão de diferença."

  "Image used in tab menus to indicate that the file is locked."
  "Imagem usada nos menus de guia para indicar que o arquivo está bloqueado."

  "Image used in tab menus to indicate that the file is readonly."
  "Imagem usada nos menus de guia para indicar que o arquivo é somente leitura."

  "Image used in tab to indicate that the tab contains a difference view."
  "Imagem usada no guia para indicar que o guia contém uma visão de diferença."

  "Image used in tab to indicate that the tab's file is readonly."
  "Imagem usada no guia para indicar que arquivo a aba é somente leitura."

  "Image used in tab to indicate that the tab’s file is locked."
  "Imagem usada no guia para indicar que arquivo a aba é bloqueada."

  "Image used in tab which, when clicked, closes the tab."
  "Imagem usada no guia que, quando clicado, fecha a guia."

  "License"
  "Licença"

  "Line"
  "Linha"

  "Locked"
  "Bloqueado"

  "Move"
  "Mover"

  "Must be in multicursor mode to insert numbers"
  "Deve estar no modo de multicursor para inserir números"

  "No write permissions.  Use '!' to force write."
  "Sem permissões.  Uso '!' para forçar a escrever."

  "Release Type"
  "Tipo de lançamento"

  "Reload file?"
  "Actualizar o Ficheiro"

  "Replace"
  "Substituir"

  "Save request"
  "Salvar Pedido"

  "Show in Sidebar"
  "Show em Sidebar"

  "Starting number:"
  "Número de página inicial:"

  "Tcl/Tk Version"
  "Versão do Tcl/Tk"

  "Total Characters"
  "Personagens totais"

  "Total Lines"
  "Linhas totais"

  "Unable to successfully parse number string"
  "Não é possível analisar com êxito a cadeia numérica"

  "Unable to write file"
  "não foi possível escrever no arquivo"

  "Version"
  "Versão"

}

# markers.tcl
msgcat::mcmset pt {

  "Marker name:"
  "Nome do marcador:"

}

# menus.tcl
msgcat::mcmset pt {

  "About"
  "Sobre"

  "Absolute"
  "Absoluta"

  "Absolute line numbering"
  "Numeração de linha absoluta"

  "Align Cursors"
  "Alinhar os cursores"

  "Align cursors"
  "Alinhar os cursores"

  "Append Next Occurrence"
  "Acrescentar a próxima ocorrência"

  "Append next occurrence"
  "Acrescentar a próxima ocorrência"

  "Auto-Indent"
  "Auto Indentar"

  "Bubble Down"
  "Bolha para baixo"

  "Bubble Up"
  "Forem surgindo"

  "Bubble lines down one line"
  "Linhas de bolha para baixo uma linha"

  "Bubble lines up one line"
  "Linhas de bolha, uma linha"

  "Change Working Directory"
  "Alterar o diretório de trabalho"

  "Change working directory"
  "Altere o diretório de trabalho"

  "Character"
  "Personagem"

  "Check for Update"
  "Procurar atualização agora"

  "Check for update"
  "Buscar por atualizações"

  "Classic Mac"
  "Com seu clássico Mac"

  "Clear All"
  "Limpar Tudo"

  "Close All"
  "Fechar Tudo"

  "Close Current"
  "Fechar a Vista Actual"

  "Close all tabs"
  "Fechar todas as guias"

  "Close current session"
  "Fecha a página actual e a sessão residente nesta."

  "Close current tab"
  "Fechar o separador actual"

  "Command"
  "Comando"

  "Command Result"
  "Resultado do comando"

  "Convert case to lower"
  "Converter o caso para baixar"

  "Convert case to title"
  "Converter o caso para o título"

  "Convert case to upper"
  "Converter o caso ao superior"

  "Copy"
  "Copiar"

  "Copy text"
  "Copiar o Texto"

  "Create"
  "Criar"

  "Create at Current Line"
  "Criar na linha atual"

  "Create marker at current line"
  "Criar marcador na linha atual"

  "Create new plugin"
  "Criar novo plugin"

  "Current Line"
  "Linha actual:"

  "Current Number"
  "Número da linha actual"

  "Current Word"
  "Palavra atual"

  "Cursor"
  "Cursor"

  "Cursor from Line Start"
  "Cursor do início da linha"

  "Cursor to Line End"
  "Cursor para a linha final"

  "Cut"
  "Cortar"

  "Cut text"
  "Recorta o texto"

  "Delete current file"
  "Apagar a Actual"

  "Delete current line"
  "Apagar a Actual"

  "Delete current word"
  "Apagar a Actual"

  "Delete from cursor to end of line"
  "Apagar do cursor ao fim da linha"

  "Delete from start of line to cursor"
  "Excluir do início da linha de cursor"

  "Delete session"
  "Remover sessão"

  "Delete template"
  "Excluir"

  "Delete text between character"
  "Excluir o texto entre o caráter"

  "Delete the current number"
  "Apagar o número atual"

  "Delete the whitespace to left of cursor"
  "Excluir o espaço em branco à esquerda do cursor"

  "Delete the whitespace to right of cursor"
  "Excluir o espaço em branco à direita do cursor"

  "Disable Vim mode"
  "Desativar o modo de Vim"

  "Display Text Info"
  "Informações do visor"

  "Display text information"
  "Informações do Display"

  "Duplicate current file"
  "Arquivo atual duplicado"

  "Edit"
  "Editar"

  "Edit Language"
  "Editar idioma"

  "Edit Session"
  "Editar a sessão"

  "Edit User"
  "Editar Usuário"

  "Edit language snippets"
  "Editar trechos de linguagem"

  "Edit session current language preferences"
  "Editar preferências de idioma atual sessão"

  "Edit session global preferences"
  "Editar preferências de sessão global"

  "Edit template"
  "Editar"

  "Edit user current language preferences"
  "Editar preferências de idioma atual do usuário"

  "Edit user global preferences"
  "Editar preferências de usuário global"

  "Edit user menu bindings"
  "Editar ligações de menu de usuário"

  "Edit user snippets"
  "Editar trechos de usuário"

  "Enable Vim mode"
  "Ativar o modo de Vim"

  "Enumeration"
  "Enumeração"

  "Favorite file"
  "Arquivo favorito"

  "File"
  "Arquivo"

  "File Contents"
  "conteúdo de ficheiro"

  "Find In Files"
  "Procurar nos Ficheiros..."

  "Find Matching Pair"
  "Encontrar o par de correspondência"

  "Find and Replace"
  "Localizar e substituir"

  "Find in files"
  "Procurar nos Ficheiros..."

  "Find matching character pair"
  "Encontrar o par de caracteres correspondente"

  "Find next occurrence"
  "Localizar a próxima ocorrência"

  "Find previous occurrence"
  "Localizar a ocorrência anterior"

  "Fold All"
  "Dobre tudo"

  "Folding"
  "Dobragem"

  "Format Text"
  "Text Format"

  "Format indentation for text"
  "Recuo de formato para texto"

  "From Clipboard"
  "Correcção da Área de Transferência"

  "Global"
  "Global"

  "Goto Last Tab"
  "Ir à última guia"

  "Goto Next Tab"
  "Ir à Próxima Tab"

  "Goto Other Pane"
  "Outros Pane Goto"

  "Goto Previous Tab"
  "Ir à aba anterior"

  "Goto last tab"
  "Última guia goto"

  "Goto next difference"
  "Ir para a próxima diferença"

  "Goto next tab"
  "Ir para a próxima guia"

  "Goto other pane"
  "Ir para outro painel"

  "Goto previous difference"
  "Diferença Anterior"

  "Goto previous tab"
  "Aba anterior"

  "Help"
  "Ajuda"

  "Hide Console"
  "Ocultar Console"

  "Hide Line Numbers"
  "Esconder os números de linha"

  "Hide Marker Map"
  "Esconder mapa marcador"

  "Hide Meta Characters"
  "Esconder os Meta caracteres"

  "Hide Sidebar"
  "Esconder a Barra Lateral"

  "Hide Status Bar"
  "Ocultar Barra de Status"

  "Hide Tab Bar"
  "Esconder Tab Bar"

  "Hide console"
  "Esconde o console"

  "Hide line numbers"
  "Números de linha"

  "Hide marker map"
  "Esconder mapa marcador"

  "Hide meta characters"
  "Esconder os meta caracteres"

  "Hide sidebar"
  "Ocultar barra lateral"

  "Hide status bar"
  "Ocultar barra de Status"

  "Hide tab bar"
  "Ocultar barra de guia"

  "Indent"
  "Avançar"

  "Indent Off"
  "Travessão fora"

  "Indent selected text"
  "Recuar o texto selecionado"

  "Indentation"
  "Indentação"

  "Insert"
  "Inserir"

  "Insert command result after current line"
  "Inserir o resultado do comando depois da linha atual"

  "Insert enumeration"
  "Inserir a enumeração"

  "Insert file contents after current line"
  "Inserir o conteúdo do arquivo depois da linha atual"

  "Insert from clipboard"
  "Inserir a partir da área de transferência"

  "Insert line above current line"
  "Inserir linha acima da linha atual"

  "Insert line below current line"
  "Inserir linha abaixo da linha atual"

  "Insert snippet"
  "Inserir trecho"

  "Install"
  "Instalar"

  "Install plugin"
  "Instalar Plugin"

  "Join Lines"
  "Unir Linhas"

  "Join lines"
  "Unir Linhas"

  "Jump Backward"
  "Saltar para trás"

  "Jump Forward"
  "Saltar para a frente"

  "Jump To Line"
  "Saltar para a linha"

  "Jump backward"
  "Saltar para trás"

  "Jump forward"
  "Saltar para a frente"

  "Jump to line"
  "Saltar para a linha"

  "Language"
  "Idioma"

  "Launcher"
  "Lançador"

  "Line Above Current"
  "Linha superior corrente"

  "Line Below Current"
  "Linha abaixo a corrente"

  "Line Ending"
  "Linha final"

  "Line Number"
  "Número de Linha"

  "Line Numbering"
  "Numeração de Linhas"

  "Lock"
  "Fixar"

  "Lock file"
  "Bloqueio de arquivo"

  "Lower Case"
  "caixa baixa"

  "Markers"
  "Marcadores"

  "Menu"
  "Menu"

  "Menu Bindings"
  "Ligações de Menu"

  "Merge Panes"
  "Mesclar painéis"

  "Merge panes"
  "Mesclar painéis"

  "Move Cursors Down"
  "Mova os cursores para baixo"

  "Move Cursors Left"
  "Mover cursores esquerda"

  "Move Cursors Right"
  "Mover para a direita de cursores"

  "Move Cursors Up"
  "Mova os cursores para cima"

  "Move cursor to bottom of screen"
  "Mova o cursor para o fundo da tela"

  "Move cursor to end of current line"
  "Mover o cursor para o fim da linha atual"

  "Move cursor to first line"
  "Mova o cursor para a primeira linha"

  "Move cursor to last line"
  "Mova o cursor para a última linha"

  "Move cursor to middle of screen"
  "Mova o cursor para o meio da tela"

  "Move cursor to next page"
  "Mova o cursor para a próxima página"

  "Move cursor to next word"
  "Mova o cursor para a próxima palavra"

  "Move cursor to previous page"
  "Mova o cursor para a página anterior"

  "Move cursor to previous word"
  "Mova o cursor para a palavra anterior"

  "Move cursor to start of current line"
  "Mover o cursor para o início da linha atual"

  "Move cursor to top of screen"
  "Mova o cursor para a parte superior da tela"

  "Move multicursors down one line"
  "Multicursors mover para baixo uma linha"

  "Move multicursors left one line"
  "Mover o multicursors esquerdo de uma linha"

  "Move multicursors right one line"
  "Mover multicursors bem uma linha"

  "Move multicursors up one line"
  "Multicursors mover uma linha"

  "Move to First Line"
  "Mover para a primeira linha"

  "Move to Last Line"
  "Mover para a última linha"

  "Move to Line End"
  "Mover para o fim de linha"

  "Move to Line Start"
  "Mover para a linha de início"

  "Move to Next Page"
  "Mover para a próxima página"

  "Move to Next Word"
  "Mover para a próxima palavra"

  "Move to Previous Page"
  "Ir para página anterior"

  "Move to Previous Word"
  "Mover para a palavra anterior"

  "Move to Screen Bottom"
  "Mover para o fundo de tela"

  "Move to Screen Middle"
  "Mover para o meio da tela"

  "Move to Screen Top"
  "Mover para o topo da tela"

  "Move to other pane"
  "Mover para outro painel"

  "New From Template"
  "Novo a Partir de Modelo"

  "New Window"
  "Nova Janela"

  "New file"
  "Novo arquivo"

  "New file from template"
  "Novo a partir do modelo"

  "New window"
  "Nova janela"

  "Next Difference"
  "Próxima Diferença"

  "Open Directory"
  "Abrir uma Pasta"

  "Open Favorite"
  "Abrir Favorita"

  "Open File"
  "Abrir Ficheiro"

  "Open Recent"
  "Abrir um Recente"

  "Open directory"
  "Abrir diretório..."

  "Open file"
  "Abrir um ficheiro"

  "Paste"
  "Colar"

  "Paste and Format"
  "Colar formato"

  "Paste and format text from clipboard"
  "Formato e colar texto da área de transferência"

  "Paste text from clipboard"
  "Colar da área de transferência"

  "Plugins"
  "Plugins"

  "Preferences"
  "Preferências"

  "Previous Difference"
  "Diferença Anterior"

  "Profiling Report Sorted By"
  "Relatório de perfil classificado por"

  "Profiling started"
  "Profiling começou"

  "Profiling stopped"
  "Profiling parado"

  "Quit"
  "Desistir"

  "Quit application"
  "Sair da aplicação"

  "Redo"
  "Refazer"

  "Relative"
  "Relativo"

  "Relative line numbering"
  "Numeração de linha relativa"

  "Reload"
  "Recarregar"

  "Reload all plugins"
  "Recarregar os 'Plugins'"

  "Reload snippets"
  "Trechos de recarga"

  "Reload template information"
  "Informações do modelo de recarga"

  "Remove All Markers"
  "Remova todos os marcadores"

  "Remove From Current Line"
  "Remover da linha atual"

  "Remove all markers"
  "Remova todos os marcadores"

  "Remove marker from current line"
  "Remover o marcador de linha atual"

  "Rename current file"
  "Renomeie o arquivo atual"

  "Reopen File"
  "Reabrir o arquivo."

  "Reopen current file"
  "Reabrir o arquivo corrente"

  "Replace Line With Script"
  "Substituir a linha com Script"

  "Replace line with script"
  "Substituir a linha com script"

  "Reset User to Base"
  "Redefinir o usuário à Base"

  "Restart"
  "Reiniciar"

  "Run"
  "Executar"

  "Run theme editor"
  "Execute o editor de temas"

  "Save All"
  "Gravar Tudo"

  "Save As Template"
  "Salvar como modelo"

  "Save Current"
  "Salvar a skin atual"

  "Save Selection As"
  "Salvar seleção como"

  "Save all files"
  "Guardar todos os ficheiros"

  "Save current session"
  "Deseja gravar a sessão actual?"

  "Save file"
  "Salvar arquivo"

  "Save file as"
  "Gravar o Ficheiro Como..."

  "Save file as template"
  "Salve o arquivo como modelo"

  "Save selected lines"
  "Salvar as linhas selecionadas"

  "Save sessions as"
  "Guardar as sessões como"

  "Select All"
  "Selecionar tudo"

  "Select All Occurrences"
  "Selecionar todas as ocorrências"

  "Select Next Occurrence"
  "Selecione a próxima ocorrência"

  "Select Previous Occurrence"
  "Selecione a ocorrência anterior"

  "Select all occurrences"
  "Selecionar todas as ocorrências"

  "Select all text"
  "Seleccionar Todo o Texto"

  "Send Bug Report"
  "Comunicar um erro."

  "Send Feedback"
  "Enviar Comentário"

  "Send bug report"
  "Comunicar um erro."

  "Send feedback"
  "Enviar opinião"

  "Sessions"
  "Sessões"

  "Set Syntax"
  "Definir Sintaxe"

  "Set Theme"
  "Definir Tema"

  "Set User to Global"
  "Definir usuário Global"

  "Set current file line ending to CR for Classic Mac"
  "Definir a linha atual do arquivo final para CR para Mac Classic"

  "Set current file line ending to CRLF for Windows"
  "Definir o atual arquivo linha final de CRLF para Windows"

  "Set current file line ending to LF for Unix"
  "Definir a linha atual do arquivo final para se para Unix"

  "Set indent mode to"
  "Definir modo de travessão"

  "Set user bindings to global bindings"
  "Defina as ligações de usuário para globais ligações"

  "Set user preferences to global preferences"
  "Definir preferências de usuário para preferências globais"

  "Show Console"
  "Mostrar Console"

  "Show Diagnostic Logfile"
  "Mostrar arquivo de log de diagnóstico"

  "Show File Difference"
  "Mostrar a diferença de arquivo."

  "Show Last Profiling Report"
  "Mostrar Último Relatório Profiling"

  "Show Line Numbers"
  "Mostrar os Números de Linha"

  "Show Marker Map"
  "Exibir Marcador"

  "Show Meta Characters"
  "Mostrar os Meta caracteres"

  "Show Selected Line Change"
  "Mostrar a mudança de linha selecionada"

  "Show Sidebar"
  "Mostrar a Barra Lateral"

  "Show Status Bar"
  "Barra de Estado"

  "Show Tab Bar"
  "Barra de Páginas"

  "Show console"
  "Mostrar o console"

  "Show diagnostic logfile"
  "Mostrar arquivo de log de diagnóstico"

  "Show file difference"
  "Mostrar a diferença de arquivo"

  "Show last profiling report"
  "Mostrar o último relatório de perfil"

  "Show line numbers"
  "Mostrar números de linha"

  "Show marker map"
  "Exibir Marcador"

  "Show meta characters"
  "Mostrar os meta caracteres"

  "Show selected line change"
  "Mostrar a mudança de linha selecionada"

  "Show sidebar"
  "Mostrar a barra lateral"

  "Show status bar"
  "Mostrar barra de Status"

  "Show tab bar"
  "Barra de Páginas"

  "Smart Indent"
  "Travessão inteligente"

  "Snippet"
  "﻿Trecho"

  "Snippets"
  "Trechos"

  "Sort Tabs"
  "Sort Tabs"

  "Sort tabs"
  "Guias de classificação"

  "Start Profiling"
  "Comece Profiling"

  "Start profiling"
  "Iniciar criação de perfil"

  "Stop Profiling"
  "Pare Profiling"

  "Stop profiling"
  "Impedir a criação de perfil"

  "Switch To"
  "Trocar para"

  "Switch to session"
  "Alterne para a sessão"

  "Tabs"
  "Guias"

  "Templates"
  "Templates"

  "Text Between Character"
  "Texto entre caracteres"

  "Title Case"
  "Capitalização do título"

  "Toggle Case"
  "Mudar a capitalização"

  "Toggle Comment"
  "Comentário de alternância"

  "Toggle case of current character"
  "Caso de alternância de caractere atual"

  "Toggle comment"
  "Comentário de alternância"

  "Toggle split view mode"
  "Alternar modo de exibição dividido"

  "Tools"
  "Ferramentas"

  "Transform"
  "Transform"

  "Undo"
  "Anular"

  "Unfavorite file"
  "Arquivo favoritas"

  "Unfold All"
  "Todos se desdobram"

  "Unindent"
  "Unindent"

  "Unindent selected text"
  "Remover o recuo texto selecionado"

  "Uninstall"
  "Desinstalar"

  "Uninstall plugin"
  "Desinstalar plugin"

  "Unix"
  "Unix"

  "Unlock"
  "Unlock"

  "Unlock file"
  "Desbloquear arquivo"

  "Upper Case"
  "CAIXA SUPERIOR"

  "User Guide"
  "Guia do Usuário"

  "View"
  "Vista"

  "View Base"
  "Vista Base"

  "View Global"
  "Visão Global"

  "View base preferences file"
  "Arquivo de base de preferências de exibição"

  "View global menu bindings"
  "Ligações de modo de exibição de menu global"

  "View user guide"
  "Guia de Usuário"

  "Vim Mode"
  "Modo Vim"

  "Whitespace Backward"
  "Espaço em branco para trás"

  "Whitespace Forward"
  "Espaço em branco para a frente"

  "Windows"
  "Windows"

}

# plugins.tcl
msgcat::mcmset pt {

  "Always grant from developer"
  "Sempre conceder a partir desenvolvedor"

  "ERROR"
  "Erro"

  "ERROR:  Plugin name already exists"
  "ERRO: Nome do Plugin já existe"

  "ERROR:  Plugin name is not valid (only alphanumeric and underscores are allowed)"
  "ERRO: Plugin nome não é válido (apenas caracteres alfanuméricos e sublinhados são permitidos)"

  "ERROR:  Unable to create plugin directory"
  "Erro: Não foi possível criar o diretório de plugins"

  "ERROR:  Unable to write plugin files"
  "ERRO: Não é possível gravar arquivos de plugin"

  "Enter plugin name"
  "Digite o nome do plugin"

  "Grant"
  "Conceda"

  "Grant permission?"
  "Conceda permission?"

  "OK"
  "OK"

  "Plugin Errors"
  "Erros Plugin"

  "Plugin Trust Requested"
  "Plugin Confiança solicitada"

  "Plugin installed"
  "Plugin instalado"

  "Plugin requires permission to view or modify your system."
  "Plugin requer permissão para exibir ou modificar o seu sistema."

  "Plugin uninstalled"
  "Plugin desinstalado"

  "Plugins successfully reloaded"
  "Plugins recarregados com sucesso"

  "Reject"
  "Rejeitado"

  "Syntax errors found in selected plugins"
  "Os erros de sintaxe encontrados em plugins selecionados"

}

# search.tcl
msgcat::mcmset pt {

  "No files found in specified directories"
  "Não há arquivos encontrados em diretórios especificados"

  "No search results found"
  "Resultados Encontrados da Pesquisa"

  "Search wrapped to beginning of file"
  "Busca ajustada para início do arquivo."

  "Search wrapped to end of file"
  "Pesquisa envolto ao final do arquivo"

  "substitutions done"
  "feito de substituições"

}

# sessions.tcl
msgcat::mcmset pt {

  "Save session?"
  "Gravar a Sessão?"

  "Session state will be lost if not saved"
  "O estado da sessão será perdido se não for salvo"

}

# sidebar.tcl
msgcat::mcmset pt {

  "Add Parent Directory"
  "Directório pai"

  "Close Directory Files"
  "Fechar Arquivos Diretório"

  "Copy Pathname"
  "Copie o caminho do"

  "Delete directories?"
  "Apagar Diretórios Antigos"

  "Delete directory?"
  "Excluir diretório?"

  "Delete file?"
  "Excluir arquivo"

  "Delete files?"
  "Excluir Arquivos"

  "Directory Name:"
  "Nome do diretório:"

  "Folder Name:"
  "Nome da Pasta:"

  "Image displayed in sidebar to indicate that a file is currently opened in an editing buffer."
  "Imagem exibida na lateral para indicar que um arquivo é aberto no momento em um buffer de edição."

  "Make Current Working Directory"
  "Faça diretório de trabalho atual"

  "New Directory"
  "Novo Diretório"

  "New File From Template"
  "Novo a partir do modelo"

  "Open Directory Files"
  "Arquivos Open Directory"

  "Refresh Directory Files"
  "Atualizar arquivos do diretório"

  "Remove Parent from Sidebar"
  "Remover Pai de Sidebar"

  "Remove from Sidebar"
  "Retire do Sidebar"

  "Show Difference"
  "Mostrar a diferença"

}

# snippets.tcl
msgcat::mcmset pt {

  "Snippet: *"
  "﻿Trecho"

}

# syntax.tcl
msgcat::mcmset pt {

  "Syntax"
  "Sintaxe"

  "Syntax error in syntax file"
  "Erro de sintaxe no arquivo de sintaxe"

}

# templates.tcl
msgcat::mcmset pt {

  "Template"
  "Tema"

  "Template Name"
  "Nome do Template"

  "deleted"
  "deletado"

  "saved"
  "salvo"

}

# theme.tcl
msgcat::mcmset pt {

  "Background (trough) color used in the sidebar scrollbar."
  "Cor de fundo (calha) usado na barra de rolagem lateral."

  "Background (trough) color used in the text scrollbars."
  "Cor de fundo (calha) utilizado em barras de rolagem de texto."

  "Background color for all sidebar items that are not selected."
  "Cor de fundo para todos os itens da barra lateral que não estão selecionados."

  "Background color for all sidebar items that are selected."
  "Cor de fundo para todos os itens da barra lateral que estão selecionados."

  "Background color in difference viewer that shows added lines."
  "Cor de fundo no Visualizador de diferença que mostra adicionou linhas."

  "Background color in difference viewer that shows deleted lines."
  "Cor de fundo no Visualizador de diferença que mostra excluído linhas."

  "Background color of insertion cursor and background marker colors."
  "A cor do fundo do cursor de inserção e marcadores fundo cores."

  "Background color of the editing buffer."
  "Cor de fundo do buffer de edição."

  "Background color to display when a button-like ttk widget is pressed."
  "Cor de fundo a ser exibido quando um widget ttk como botão é pressionado."

  "Background color to use for selected text."
  "Cor de fundo a ser usado para o texto selecionado."

  "Background color used for all other tabs that are not the current/active tab in the tabbar."
  "Cor de fundo usada para todas as outras abas que não sejam a guia de corrente/ativo no tabbar."

  "Background color used for the current/active menu item."
  "Cor de fundo usada para o item de menu atual/ativo."

  "Background color used for the current/active tab in the tabbar."
  "Cor de fundo usado para guia de corrente/ativo no tabbar."

  "Background color used in highlighted text."
  "Cor de fundo usada no texto realçado."

  "Background color used in menus."
  "Cor de fundo usado em menus."

  "Background color used in the tabbar area."
  "Cor de fundo usada na área tabbar."

  "Color of border drawn around active editing buffer."
  "Cor da borda desenhada ao redor de buffer de edição ativa."

  "Color of ttk entry widget text border when the entry has keyboard focus."
  "Cor da borda de texto de ttk entrada widget quando a entrada tem o foco do teclado."

  "Color used to draw the warning width line in the editing buffer (as well as the line separating the gutter from the editing buffer)."
  "Cor usada para desenhar a linha de largura de aviso no buffer de edição (bem como a linha que separa a calha do buffer de edição)."

  "Default 'darkcolor' for all ttk widgets."
  "Padrão 'darkcolor' para todos os widgets ttk."

  "Default background color to use for all ttk widgets that are in a disabled state."
  "Cor de fundo padrão a ser usado para todos os widgets ttk que estão em um estado desabilitado."

  "Default background color to use for all ttk widgets when the mouse cursor hovers over the widget."
  "Cor de fundo a ser usado para todos os widgets ttk quando o cursor do mouse passa sobre o widget padrão."

  "Default background color to use for all ttk widgets."
  "Cor de fundo padrão a ser usado para todos os widgets ttk."

  "Default border color for all ttk widgets."
  "Cor da borda padrão para todos os widgets ttk."

  "Default color for non-syntax highlighted text."
  "Cor padrão para non-sintaxe texto realçado."

  "Default foreground text color to use for all ttk widgets that are in a disabled state."
  "Padrão de cor do primeiro plano de texto a ser usado para todos os widgets ttk que estão em um estado desabilitado."

  "Default foreground text color to use for all ttk widgets."
  "Padrão de cor do primeiro plano de texto a ser usado para todos os widgets ttk."

  "Determines the number of grips strips to display in the grip area between resizable panes."
  "Determina o número de tiras de apertos para exibir na área de aderência entre painéis redimensionáveis."

  "Determines the thickness of the grip area between resizable panes."
  "Determina a espessura da área de aderência entre painéis redimensionáveis."

  "ERROR:  Unable to read"
  "ERRO: Não é possível ler"

  "Foreground (slider) color used in the sidebar scrollbar."
  "Cor de primeiro plano (slider) usado na barra de rolagem lateral."

  "Foreground (slider) color used in the text scrollbars."
  "Cor de primeiro plano (slider) utilizado em barras de rolagem de texto."

  "Foreground color used in menu items with checks or buttons."
  "Usado em itens de menu com cheques ou botões de cor de primeiro plano."

  "Foreground text color for strings."
  "Cor do texto do primeiro plano para seqüências de caracteres."

  "Foreground text color to use for all miscellaneous1 labeled text."
  "Cor do primeiro plano de texto a ser usado para todos os miscellaneous1 rotulado de texto."

  "Foreground text color to use for all miscellaneous2 labeled text."
  "Cor do primeiro plano de texto a ser usado para todos os miscellaneous2 rotulado de texto."

  "Foreground text color to use for all miscellaneous3 labeled text."
  "Cor do primeiro plano de texto a ser usado para todos os miscellaneous3 rotulado de texto."

  "Foreground text color to use for comments."
  "Cor do primeiro plano de texto a ser usado para comentários."

  "Foreground text color to use for displaying line numbers."
  "Cor do texto do primeiro plano para usar para exibir números de linha."

  "Foreground text color to use for displaying numbers."
  "Cor do texto do primeiro plano para usar para exibir os números."

  "Foreground text color to use for language-specific keywords."
  "Cor do primeiro plano de texto a ser usado para palavras-chave específicas de idioma."

  "Foreground text color to use for language-specific punctuation."
  "Cor do primeiro plano de texto a ser usado para Pontuação de específicos do idioma."

  "Foreground text color to use for meta syntax."
  "Cor do texto do primeiro plano para usar sintaxe de meta."

  "Foreground text color to use for precompiler syntax."
  "Cor do texto do primeiro plano para usar sintaxe pré-compilador."

  "Foreground text color to use for selected text."
  "Cor do texto do primeiro plano para o texto selecionado."

  "Foreground text color used for all other tabs that are not the current/active tab in the tabbar."
  "Cor do texto do primeiro plano usado para todas as outras abas que não sejam a guia de corrente/ativo no tabbar."

  "Foreground text color used for menus item that are disabled."
  "Cor do texto do primeiro plano usado para item de menus que estão desativados."

  "Foreground text color used for the current/active menu item."
  "Cor de primeiro plano texto usado para o item de menu atual/ativo."

  "Foreground text color used for the current/active tab in the tabbar."
  "Cor do texto do primeiro plano usado para guia de corrente/ativo no tabbar."

  "Foreground text color used in menus."
  "Cor de primeiro plano texto usado nos menus."

  "Foreground text/image color used in tabbar and tabs."
  "Cor do texto/imagem de primeiro plano usado em tabbar e guias."

  "Images"
  "Imagens"

  "Maximum thickness of the text scrollbar when it is active."
  "Espessura máxima da barra de rolagem de texto quando ele estiver ativo."

  "Maximum thickness of the text scrollbars when they are active."
  "Espessura máxima das barras de rolagem de texto quando estão ativos."

  "Menu Options"
  "Opções de menu"

  "Menu relief value."
  "Valor de alívio do menu."

  "Pixel height of the tabbar widget."
  "Altura de pixel do tabbar widget."

  "Relief used in drawing the tabs."
  "Utilizados na elaboração das guias de alívio."

  "Relief value of the sidebar area."
  "Valor de relevo da área da barra lateral."

  "Sidebar Options"
  "Opção de Barra Lateral"

  "Sidebar Scrollbar Options"
  "Sidebar Opções de barra de rolagem"

  "Specifies the color to display around the sidebar when the sidebar does not have the focus."
  "Especifica a cor para exibir em torno de barra lateral quando a barra lateral não tem o foco."

  "Specifies the color to display around the sidebar when the sidebar has the focus."
  "Especifica a cor para exibir em torno de barra lateral quando a barra lateral tem o foco."

  "Specifies the default background color to use for text that is selected in a standard ttk widget (this does not include the editing buffer)."
  "Especifica a cor de fundo padrão a ser usado para o texto selecionado em um widget de ttk padrão (isso não inclui o buffer de edição)."

  "Specifies the default foreground text color to use for text that is selected in a standard ttk widget (this does not include the editing buffer)."
  "Especifica a cor do texto do primeiro plano padrão a ser usado para o texto selecionado em um widget de ttk padrão (isso não inclui o buffer de edição)."

  "Specifies the default relief to use when drawing ttk widgets."
  "Especifica o alívio de padrão para usar quando desenho ttk widgets."

  "Specifies the disclosure image style to use in the sidebar."
  "Especifica o estilo de imagem de divulgação para usar na barra lateral."

  "Specifies the pixel thickness of the highlight line."
  "Especifica a espessura de pixel da linha de destaque."

  "Syntax Colors"
  "Sintaxe Colors"

  "Tab Options"
  "Opções da Aba"

  "Text Scrollbar Options"
  "Opções de texto barra de rolagem"

  "Text color for all sidebar items that are not selected."
  "Cor do texto para todos os itens da barra lateral que não estão selecionados."

  "Text color for all sidebar items that are selected."
  "Cor do texto para todos os itens da barra lateral que estão selecionados."

  "ttk Widget Colors"
  "ttk Widget Colors"

}

# themer.tcl
msgcat::mcmset pt {

  "   Show All"
  "Mostrar tudo"

  "   Show Category"
  "Exibir Categoria"

  "   Show Color"
  "Mostrar Cor de Fundo"

  "   Show Selected Option"
  "Mostrar opção selecionada"

  "   Show Selected Value"
  "Mostrar o valor selecionado"

  "Categories"
  "Categorias"

  "Change Base Color"
  "Mudar a cor"

  "Choose Theme"
  "Escolha um Tema"

  "Custom Directory"
  "Directório Personalizado"

  "Custom..."
  "Personalizadas..."

  "Delete swatch?"
  "Excluir amostra?"

  "Description"
  "Descrição Longa"

  "Details"
  "Leia Mais ..."

  "Done"
  "Finalizado"

  "Export"
  "Exportar"

  "GIF Photo"
  "GIF Foto"

  "Import"
  "Importe"

  "Import BMP Data"
  "Importar dados"

  "Import BMP Mask"
  "Importar máscara"

  "Import Error"
  "Erro de Importação!"

  "Import Theme File"
  "Importar Arquivo de Tema"

  "Installation Directory"
  "Diretório de Instalação"

  "Modifications"
  "Modificações"

  "One-Color Bitmap"
  "Bitmap de uma cor"

  "Preview"
  "Visualizar"

  "Relief: "
  "Válvula de"

  "Save As:"
  "Salvar como:"

  "Save theme changes?"
  "Salve as alterações do tema?"

  "Select Directory"
  "Selecionar diretório"

  "Swatch"
  "Swatch"

  "Swatch Colors"
  "Swatch Colors"

  "Table Filters"
  "Filtros de Mesa"

  "The current theme has unsaved changes"
  "O tema atual tem alterações não salvas"

  "Tree Style: "
  "Estilo Tree:"

  "Two-Color Bitmap"
  "Bitmap de duas cores"

  "User Directory"
  "Directório de utilizador"

  "Value"
  "Valor"

  "Value: "
  "Valor:"

}

# themes.tcl
msgcat::mcmset pt {

  "Theme"
  "Tema"

  "Theme:*"
  "Tema"

}

# tke.tcl
msgcat::mcmset pt {

  "Import TKE theme?"
  "Tema Import TKE?"

  "Import TextMate theme?"
  "Importe tema TextMate?"

}

# tkedat.tcl
msgcat::mcmset pt {

  "Unable to read"
  "Não foi possível ler o ficheiro."

}

# vim.tcl
msgcat::mcmset pt {

  "File format unrecognized"
  "Formato de arquivo não reconhecido"

  "Filename directory does not exist"
  "Diretório de nome de arquivo não existe"

  "Illegal modelines value"
  "Valor ilegal modelines"

  "Number width not a number"
  "Número de largura não é um número"

  "Shiftwidth value is not an integer"
  "Shiftwidth valor não é um número inteiro"

  "Tabstop value is not an integer"
  "TabStop valor não é um número inteiro"

  "Unrecognized vim option"
  "Opção de não reconhecido o vim"

}

# General
msgcat::mcmset pt {

  "Cancel"
  "Cancelar"

  "Close"
  "Fecho"

  "Delete"
  "Excluir"

  "Duplicate"
  "Duplicação"

  "Favorite"
  "Favorito"

  "File Name:"
  "Nome do arquivo:"

  "Find"
  "Encontrar"

  "Move to Other Pane"
  "Mover para outro painel"

  "New File"
  "Novo arquivo"

  "None"
  "Nenhum"

  "Open"
  "Abrir"

  "Rename"
  "Renomear"

  "Save"
  "Salvar"

  "Save As"
  "Salvar como"

  "Split View"
  "Dividir a Vista"

  "Theme Editor"
  "Editor de temas"

  "Unable to write"
  "Não foi possível gravar o ficheiro"

  "Unfavorite"
  "Unfavorite"

}

