# api.tcl
msgcat::mcmset pt {

  "Argument list to api::add_file was not an even key/value pair"
  "Lista de argumentos a api :: add_file não era um par ainda de chave / valor"

}

# bgproc.tcl
msgcat::mcmset pt {

  "Unable to run system command (%s)"
  "Não é possível executar comandos do sistema (% s)"

}

# diff.tcl
msgcat::mcmset pt {

  "    End: "
  "Término:"

  "    Start: "
  "Início:"

  "Enter difference command"
  "Digite o comando de diferença"

  "Enter starting file"
  "Insira o arquivo inicial"

  "Update"
  "Atualizar"

}

# gui.tcl
msgcat::mcmset pt {

  "%s, Line: %d, Column: %d"
  "% S, linha% d, coluna% d"

  "Case sensitivity"
  "Distinção entre maiúsculas e minúsculas"

  "Close All Tabs"
  "Fechar todas as guias"

  "Close Other Tab(s)"
  "Fechar Outros Tab (s)"

  "Close Other*"
  "Feche os outros separadores"

  "Close Tab"
  "Fechar a Página"

  "Copyright %d-%d"
  "Copyright% d-% d"

  "Delete tab?"
  "Excluir guia?"

  "Developer:"
  "Desenvolvedor"

  "Email:"
  "E-mail:"

  "Error"
  "Erro"

  "Favorited"
  "Favorito"

  "File already exists.  Use '!' to force an overwrite"
  "Arquivo já existe.  Uso '!' para forçar uma sobrescrever"

  "File attribute (%s) does not exist"
  "Atributo do arquivo (% s) não existe"

  "File index is out of range"
  "Índice arquivo está fora do intervalo"

  "License:"
  "Licença:"

  "Line: %d, Column: %d"
  "Linha:% d, coluna% d"

  "Locked"
  "Bloqueado"

  "Move*"
  "Mudar"

  "Must be in multicursor mode to insert numbers"
  "Deve estar no modo de multicursor para inserir números"

  "No write permissions.  Use '!' to force write."
  "Sem permissões.  Uso '!' para forçar a escrever."

  "Release Type:"
  "Tipo lançamento:"

  "Reload file?"
  "Actualizar o Ficheiro"

  "Save request"
  "Salvar Pedido"

  "Show in Sidebar"
  "Show em Sidebar"

  "Starting number:"
  "Número de página inicial:"

  "Tcl/Tk Version:"
  "Versão do Tcl/Tk:"

  "Total Lines: %d, Total Characters: %d"
  "Total de linhas:% d, Total Personagens:% d"

  "Unable to find current file (tab: %s)"
  "Não foi possível localizar o arquivo atual (guia:% s)"

  "Unable to successfully parse number string"
  "Não é possível analisar com êxito a cadeia numérica"

  "Unable to write file"
  "não foi possível escrever no arquivo"

  "Version:"
  "Versão:"

}

# markers.tcl
msgcat::mcmset pt {

  "Marker name:"
  "Nome do marcador:"

}

# menus.tcl
msgcat::mcmset pt {

  "                                  Profiling Report Sorted By (%s)"
  "Profiling Relatório Ordenado por (% s)"

  "About TKE"
  "Sobre TKE"

  "Align Cursors"
  "Alinhar os cursores"

  "Append Next Occurrence"
  "Acrescentar a próxima ocorrência"

  "Auto-Indent"
  "Auto Indentar"

  "Check for Update"
  "Procurar atualização agora"

  "Clear All"
  "Limpar Tudo"

  "Close All"
  "Fechar Tudo"

  "Close Current"
  "Fechar a Vista Actual"

  "Copy"
  "Copiar"

  "Create New..."
  "Criar um Novo"

  "Create at Current Line"
  "Criar na linha atual"

  "Create..."
  "Criar..."

  "Cut"
  "Cortar"

  "Edit"
  "Editar"

  "Edit Language"
  "Editar idioma"

  "Edit Session - Global"
  "Editar a sessão - Global"

  "Edit Session - Language"
  "Editar a sessão - língua"

  "Edit User"
  "Editar Usuário"

  "Edit User - Global"
  "Editar usuário - Global"

  "Edit User - Language"
  "Editar usuário - idioma"

  "Edit..."
  "Editar..."

  "File"
  "Arquivo"

  "Find"
  "Encontrar"

  "Find In Files"
  "Procurar nos Ficheiros..."

  "Find Matching Pair"
  "Encontrar o par de correspondência"

  "Find and Replace"
  "Localizar e substituir"

  "Format Text"
  "Text Format"

  "From Clipboard"
  "Correcção da Área de Transferência"

  "Goto Last Tab"
  "Ir à última guia"

  "Goto Next Tab"
  "Ir à Próxima Tab"

  "Goto Other Pane"
  "Outros Pane Goto"

  "Goto Previous Tab"
  "Ir à aba anterior"

  "Help"
  "Ajuda"

  "Hide Console"
  "Ocultar Console"

  "Hide Line Numbers"
  "Esconder os números de linha"

  "Hide Meta Characters"
  "Esconder os Meta caracteres"

  "Hide Sidebar"
  "Esconder a Barra Lateral"

  "Hide Status Bar"
  "Ocultar Barra de Status"

  "Hide Tab Bar"
  "Esconder Tab Bar"

  "Import TextMate Theme..."
  "Tema de TextMate importação..."

  "Indent"
  "Avançar"

  "Indent Mode"
  "Modo de travessão"

  "Indent Off"
  "Travessão fora"

  "Insert Enumeration"
  "Inserir a enumeração"

  "Insert Text"
  "Inserir um Índice"

  "Install..."
  "Instalação"

  "Jump Backward"
  "Saltar para trás"

  "Jump Forward"
  "Saltar para a frente"

  "Launcher"
  "Lançador"

  "Lock"
  "Fixar"

  "Markers"
  "Marcadores"

  "Menu Bindings"
  "Ligações de Menu"

  "Menu Edit user snippets"
  "Trechos de usuário menu Editar"

  "Menu: About TKE"
  "Menu: Sobre TKE"

  "Menu: Align cursors"
  "Menu: Alinhe cursores"

  "Menu: Append next occurrence"
  "Menu: Anexar próxima ocorrência"

  "Menu: Check for Update"
  "Menu: Verificar Atualizações"

  "Menu: Close all tabs"
  "Fechar todas as guias"

  "Menu: Close current session"
  "Menu: Fechar sessão atual"

  "Menu: Close current tab"
  "Menu: guia atual Fechar"

  "Menu: Copy text"
  "Menu: Texto cópia"

  "Menu: Create marker at current line"
  "Menu: Criar marcador na linha atual"

  "Menu: Create new plugin"
  "Menu: Criar novo plugin"

  "Menu: Create new theme"
  "Criar um Novo Tema..."

  "Menu: Cut text"
  "Menu: Texto de corte"

  "Menu: Delete session"
  "Menu: Sessão de excluir"

  "Menu: Disable Vim mode"
  "Menu: modo Disable Vim"

  "Menu: Edit Tke theme"
  "Menu: Editar tema Tke"

  "Menu: Edit language snippets"
  "Menu: Trechos de idioma editar"

  "Menu: Edit session current language preferences"
  "Menu: Editar preferências de idioma atual sessão"

  "Menu: Edit session global preferences"
  "Menu: Editar preferências globais de sessão"

  "Menu: Edit user current language preferences"
  "Menu: Editar preferências de idioma atual do usuário"

  "Menu: Edit user global preferences"
  "Menu: Editar as preferências do usuário global"

  "Menu: Edit user menu bindings"
  "Ligações do menu Editar usuário: Menu"

  "Menu: Enable Vim mode"
  "Menu: Ative o modo Vim"

  "Menu: Favorite file"
  "Menu: arquivo Favorita"

  "Menu: Find"
  "Menu: Encontre"

  "Menu: Find and Replace"
  "Localizar e substituir"

  "Menu: Find in files"
  "Procurar nos Ficheiros"

  "Menu: Find matching character pair"
  "Menu: Encontre correspondência par de caracteres"

  "Menu: Find next occurrence"
  "Menu: Encontre próxima ocorrência"

  "Menu: Find previous occurrence"
  "Menu: Encontre ocorrência anterior"

  "Menu: Format all text"
  "Menu: Formate todo o texto"

  "Menu: Format selected text"
  "Menu: Formato texto selecionado"

  "Menu: Goto last tab"
  "Menu: Ir à última guia"

  "Menu: Goto next difference"
  "Menu: Diferença próxima Goto"

  "Menu: Goto next tab"
  "Menu: Ir à guia ao lado"

  "Menu: Goto other pane"
  "Menu: outro painel Goto"

  "Menu: Goto previous difference"
  "Menu: Diferença anterior Goto"

  "Menu: Goto previous tab"
  "Menu: Ir à guia anterior"

  "Menu: Hide Line Numbers"
  "Menu: Ocultar números de linha"

  "Menu: Hide Tab Bar"
  "Menu: Esconder Tab Bar"

  "Menu: Hide console"
  "Menu: Esconder consola"

  "Menu: Hide meta characters"
  "Menu: Ocultar os meta caracteres"

  "Menu: Hide sidebar"
  "Menu: ocultar barra lateral"

  "Menu: Hide status bar"
  "Menu: Ocultar barra de status"

  "Menu: Import TextMate theme"
  "Menu: tema Import TextMate"

  "Menu: Indent selected text"
  "Menu: Recuo texto selecionado"

  "Menu: Insert enumeration"
  "Menu: Inserir enumeração"

  "Menu: Insert from clipboard"
  "Inserir a partir da área de transferência"

  "Menu: Insert snippet"
  "Menu: Inserir trecho"

  "Menu: Install plugin"
  "Menu: Instalar plug-in"

  "Menu: Jump backward"
  "Menu: Saltar para trás"

  "Menu: Jump forward"
  "Menu: Salto para a frente"

  "Menu: Lock file"
  "Menu: arquivo de bloqueio"

  "Menu: Merge panes"
  "Menu: Painéis de mesclagem"

  "Menu: Move to other pane"
  "Menu: Mover para outro painel"

  "Menu: New file"
  "Menu: Novo arquivo"

  "Menu: Open Favorite"
  "Menu: Abra Favorita"

  "Menu: Open Recent"
  "Menu: Abrir recente"

  "Menu: Open directory"
  "Menu: Abrir diretório"

  "Menu: Open file"
  "Menu: Abrir arquivo"

  "Menu: Open session"
  "Menu: Sessão aberta"

  "Menu: Paste and format text from clipboard"
  "Menu: Colar e formato de texto da área de transferência"

  "Menu: Paste text from clipboard"
  "Colar texto da área de transferência"

  "Menu: Quit application"
  "Menu: Sair da aplicação"

  "Menu: Redo"
  "Menu: Refazer"

  "Menu: Reload all plugins"
  "Menu: Atualizar todos os plugins"

  "Menu: Reload snippets"
  "Menu: Trechos de recarga"

  "Menu: Remove all markers"
  "Menu: Remova todos os marcadores"

  "Menu: Remove marker from current line"
  "Menu: Remover o marcador de linha atual"

  "Menu: Replace line with script"
  "Menu: Substituir a linha com script"

  "Menu: Restart tke"
  "Menu: Restart tke"

  "Menu: Save all files"
  "Menu: Salve todos os arquivos"

  "Menu: Save current session"
  "Deseja gravar a sessão actual?"

  "Menu: Save file"
  "Menu: Salve o arquivo"

  "Menu: Save file as"
  "Menu: Salvar arquivo como"

  "Menu: Save sessions as"
  "Menu: Salvar sessões como"

  "Menu: Select all occurrences"
  "Menu: Selecione todas as ocorrências"

  "Menu: Select all text"
  "Seleccionar Todo o Texto"

  "Menu: Send Bug Report"
  "Menu: Enviar relatório de erros"

  "Menu: Send Feedback"
  "Menu: Send Feedback"

  "Menu: Set indent mode to IND"
  "Menu: Definir modo de travessão IND"

  "Menu: Set indent mode to IND+"
  "Menu: Definir modo de travessão IND +"

  "Menu: Set indent mode to OFF"
  "Menu: Definir modo de travessão para OFF"

  "Menu: Set user bindings to global bindings"
  "Menu: Define ligações de usuários para ligações globais"

  "Menu: Set user preferences to global preferences"
  "Menu: Definir as preferências do usuário para preferências globais"

  "Menu: Show Diagnostic Logfile"
  "Menu: Show diagnóstico Logfile"

  "Menu: Show Line Numbers"
  "Mostrar os Números de Linha"

  "Menu: Show Tab Bar"
  "Menu: Visualizar Tab Bar"

  "Menu: Show console"
  "Menu: Visualizar consola"

  "Menu: Show file difference"
  "Menu: Diferença de arquivo mostrar"

  "Menu: Show last profiling report"
  "Menu: Mostrar último relatório de profiling"

  "Menu: Show meta characters"
  "Menu: Show meta caracteres"

  "Menu: Show selected line change"
  "Menu: Mudança de linha de Show selecionado"

  "Menu: Show sidebar"
  "Menu: Mostrar barra lateral"

  "Menu: Show status bar"
  "Barra de Estado"

  "Menu: Sort tabs"
  "Menu: Ordenação de guias"

  "Menu: Start profiling"
  "Menu: Iniciar profiling"

  "Menu: Stop profiling"
  "Menu: Pare de perfis"

  "Menu: Switch to session"
  "Menu: Interruptor de sessão"

  "Menu: Toggle comment"
  "Menu: Comentário de alternância"

  "Menu: Toggle split view mode"
  "Menu: Alterna modo de exibição de divisão"

  "Menu: Undo"
  "Menu: Desfazer"

  "Menu: Unfavorite file"
  "Menu: arquivo Unfavorite"

  "Menu: Unindent selected text"
  "Menu: texto selecionado Unindent"

  "Menu: Uninstall plugin"
  "Menu: Desinstalar Plugin"

  "Menu: Unlock file"
  "Menu: Desbloquear arquivo"

  "Menu: View User Guide"
  "Menu: Ver Guia do Usuário"

  "Menu: View base preferences file"
  "Menu: Arquivo de base preferências de exibição"

  "Menu: View global menu bindings"
  "Menu: Ver ligações de menu global"

  "Merge Panes"
  "Mesclar painéis"

  "Next Difference"
  "Próxima Diferença"

  "Open Directory..."
  "Abrir diretório..."

  "Open Favorite"
  "Abrir Favorita"

  "Open File..."
  "Abrir um Ficheiro..."

  "Open Recent"
  "Abrir um Recente"

  "Paste"
  "Colar"

  "Paste and Format"
  "Colar formato"

  "Plugins"
  "Plugins"

  "Preferences"
  "Preferências"

  "Previous Difference"
  "Diferença Anterior"

  "Profiling started"
  "Profiling começou"

  "Profiling stopped"
  "Profiling parado"

  "Quit"
  "Desistir"

  "Redo"
  "Refazer"

  "Reload"
  "Recarregar"

  "Remove All Markers"
  "Remova todos os marcadores"

  "Remove From Current Line"
  "Remover da linha atual"

  "Replace Line With Script"
  "Substituir a linha com Script"

  "Reset User to Base"
  "Redefinir o usuário à Base"

  "Restart TKE"
  "Reiniciar TKE"

  "Save All"
  "Gravar Tudo"

  "Save As..."
  "Salvar como..."

  "Save Current"
  "Salvar a skin atual"

  "Select All"
  "Selecionar tudo"

  "Select All Occurrences"
  "Selecionar todas as ocorrências"

  "Select Next Occurrence"
  "Selecione a próxima ocorrência"

  "Select Previous Occurrence"
  "Selecione a ocorrência anterior"

  "Selected"
  "Selecionado"

  "Send Bug Report"
  "Comunicar um erro."

  "Send Feedback"
  "Enviar Comentário"

  "Sessions"
  "Sessões"

  "Set Syntax"
  "Definir Sintaxe"

  "Set Theme"
  "Definir Tema"

  "Set User to Global"
  "Definir usuário Global"

  "Show Console"
  "Mostrar Console"

  "Show Diagnostic Logfile"
  "Mostrar arquivo de log de diagnóstico"

  "Show File Difference"
  "Mostrar a diferença de arquivo."

  "Show Last Profiling Report"
  "Mostrar Último Relatório Profiling"

  "Show Line Numbers"
  "Mostrar os Números de Linha"

  "Show Meta Characters"
  "Mostrar os Meta caracteres"

  "Show Selected Line Change"
  "Mostrar a mudança de linha selecionada"

  "Show Sidebar"
  "Mostrar a Barra Lateral"

  "Show Status Bar"
  "Barra de Estado"

  "Show Tab Bar"
  "Barra de Páginas"

  "Show*Profiling*"
  "Show * Profiling *"

  "Smart Indent"
  "Travessão inteligente"

  "Snippet"
  "﻿Trecho"

  "Snippets"
  "Trechos"

  "Sort Tabs"
  "Sort Tabs"

  "Split View"
  "Dividir a Vista"

  "Start Profiling"
  "Comece Profiling"

  "Stop Profiling"
  "Pare Profiling"

  "Switch To"
  "Trocar para"

  "Tabs"
  "Guias"

  "Text"
  "Texto"

  "Theme Creator"
  "Theme Creator"

  "Toggle Comment"
  "Comentário de alternância"

  "Tools"
  "Ferramentas"

  "Undo"
  "Anular"

  "Unindent"
  "Unindent"

  "Uninstall..."
  "Desinstalação..."

  "Unlock"
  "Unlock"

  "User Guide"
  "Guia do Usuário"

  "View"
  "Vista"

  "View Base"
  "Vista Base"

  "View Global"
  "Visão Global"

  "Vim Mode"
  "Modo Vim"

}

# plugins.tcl
msgcat::mcmset pt {

  "ERROR (%s,%s): %s"
  "ERRO (%s, %s): %s"

  "ERROR:  Plugin name already exists"
  "ERRO: Nome do Plugin já existe"

  "ERROR:  Plugin name is not valid (only alphanumeric and underscores are allowed)"
  "ERRO: Plugin nome não é válido (apenas caracteres alfanuméricos e sublinhados são permitidos)"

  "ERROR:  Unable to create plugin directory"
  "Erro: Não foi possível criar o diretório de plugins"

  "ERROR:  Unable to write plugin files"
  "ERRO: Não é possível gravar arquivos de plugin"

  "Enter plugin name"
  "Digite o nome do plugin"

  "Plugin %s installed"
  "Plugin% s instalado"

  "Plugin %s uninstalled"
  "Plugin% s desinstalado"

  "Plugin Errors"
  "Erros Plugin"

  "Plugins successfully reloaded"
  "Plugins recarregados com sucesso"

  "Syntax errors found in selected plugins"
  "Os erros de sintaxe encontrados em plugins selecionados"

}

# search.tcl
msgcat::mcmset pt {

  "%d substitutions done"
  "substituições de %d feitas"

  "No files found in specified directories"
  "Não há arquivos encontrados em diretórios especificados"

  "No search results found"
  "Resultados Encontrados da Pesquisa"

  "Search wrapped to beginning of file"
  "Busca ajustada para início do arquivo."

  "Search wrapped to end of file"
  "Pesquisa envolto ao final do arquivo"

}

# sidebar.tcl
msgcat::mcmset pt {

  "Add Parent Directory"
  "Directório pai"

  "Close Directory Files"
  "Fechar Arquivos Diretório"

  "Copy Pathname"
  "Copie o caminho do"

  "Delete directory?"
  "Excluir diretório?"

  "Delete file?"
  "Excluir arquivo"

  "Directory Name:"
  "Nome do diretório:"

  "Duplicate"
  "Duplicação"

  "File Name:"
  "Nome do arquivo:"

  "Folder Name:"
  "Nome da Pasta:"

  "Make Current Working Directory"
  "Faça diretório de trabalho atual"

  "New Directory"
  "Novo Diretório"

  "Open Directory Files"
  "Arquivos Open Directory"

  "Refresh Directory Files"
  "Atualizar arquivos do diretório"

  "Remove Parent from Sidebar"
  "Remover Pai de Sidebar"

  "Remove from Sidebar"
  "Retire do Sidebar"

  "Rename"
  "Renomear"

  "Show Difference"
  "Mostrar a diferença"

}

# snippets.tcl
msgcat::mcmset pt {

  "Snippet: *"
  "﻿Trecho"

}

# syntax.tcl
msgcat::mcmset pt {

  "Syntax error in %s.syntax file"
  "Erro de sintaxe no arquivo de s.syntax%"

  "Syntax:  %s"
  "Sintaxe:% s"

  "Theme:  %s"
  "Tema:% s"

}

# themer.tcl
msgcat::mcmset pt {

  "Create"
  "Criar"

  "Create New Theme"
  "Criar um Novo Tema..."

  "Create custom"
  "Criar personalizado"

  "ERROR:  Unable to read %s"
  "ERRO: Não foi possível ler% s"

  "ERROR:  Unable to write %s"
  "ERRO: Não foi possível gravar% s"

  "Edit theme"
  "Editar tema"

  "Enter theme name"
  "Digite o nome do tema"

  "Error:  Theme is not a supported theme"
  "Erro: Tema não é um tema apoiado"

  "Import"
  "Importe"

  "Import TextMate Theme"
  "Importação TextMate Tema"

  "Name:"
  "Nome:"

  "OK"
  "OK"

  "Reset"
  "Reset"

  "Select theme"
  "Seleccione o Ficheiro do Tema"

}

# tke.tcl
msgcat::mcmset pt {

  "Edit theme?"
  "Edite tema?"

  "Import TextMate theme?"
  "Importe tema TextMate?"

}

# tkedat.tcl
msgcat::mcmset pt {

  "Unable to open %s for reading"
  "Não foi possível abrir o ficheiro%1 para leitura."

}

# vim.tcl
msgcat::mcmset pt {

  "File %s successfully written"
  "Arquivo %s gravado com êxito"

  "Filename %s already exists"
  "Nome do arquivo %s já existe."

}

# General
msgcat::mcmset pt {

  "All"
  "Tudo"

  "Cancel"
  "Cancelar"

  "Close"
  "Fecho"

  "Delete"
  "Excluir"

  "Favorite"
  "Favorito"

  "Find:"
  "Encontrar"

  "Move to Other Pane"
  "Mover para outro painel"

  "New File"
  "Novo arquivo"

  "Open"
  "Abrir"

  "Replace:"
  "Substituir:"

  "Save"
  "Salvar"

  "Save As"
  "Salvar como"

  "Unable to open %s for writing"
  "Não foi possível abrir%1 para escrita"

  "Unfavorite"
  "Unfavorite"

}

