# api.tcl
msgcat::mcmset pt {

  "Argument list to api::add_file was not an even key/value pair"
  "Lista de argumentos a api :: add_file não era um par ainda de chave / valor"

  "Plugin"
  "Plugin"

}

# bgproc.tcl
msgcat::mcmset pt {

  "Unable to run system command"
  "Não é possível executar o comando do sistema"

}

# diff.tcl
msgcat::mcmset pt {

  "    End: "
  "Término:"

  "    Start: "
  "Início:"

  "Enter difference command"
  "Digite o comando de diferença"

  "Enter starting file"
  "Insira o arquivo inicial"

  "Update"
  "Atualizar"

}

# edit.tcl
msgcat::mcmset pt {

  "File successfully written"
  "Arquivo gravado com êxito"

  "Filename already exists"
  "Nome do arquivo já existe."

}

# embed_tke.tcl
msgcat::mcmset pt {

  "Find:"
  "Encontrar"

  "Replace:"
  "Substituir:"

}

# gui.tcl
msgcat::mcmset pt {

  "All"
  "Tudo"

  "Case sensitivity"
  "Distinção entre maiúsculas e minúsculas"

  "Close All Tabs"
  "Fechar todas as guias"

  "Close Other Tabs"
  "Fechar as Outras Páginas"

  "Close Other*"
  "Feche os outros separadores"

  "Close Tab"
  "Fechar a Página"

  "Column"
  "Coluna"

  "Copyright"
  "Direitos de Autor"

  "Delete tab?"
  "Excluir guia?"

  "Developer"
  "Desenvolvedor"

  "Email"
  "E-mail"

  "Error"
  "Erro"

  "Favorited"
  "Favorito"

  "File already exists.  Use '!' to force an overwrite"
  "Arquivo já existe.  Uso '!' para forçar uma sobrescrever"

  "File attribute does not exist"
  "Atributo de arquivo não existe"

  "File index is out of range"
  "Índice arquivo está fora do intervalo"

  "Image displayed in fill-in forms which closes the form UI.  Used in forms such as search, search/replace, and find in files."
  "Imagem exibida em formulários de preenchimento que fecha o formulário da interface do usuário.  Usado em formulários como busca, busca/substituição e localizar em arquivos."

  "Image used in tab menus to indicate that the file is associated with a difference view."
  "Imagem usada nos menus de guia para indicar que o arquivo está associado uma visão de diferença."

  "Image used in tab menus to indicate that the file is locked."
  "Imagem usada nos menus de guia para indicar que o arquivo está bloqueado."

  "Image used in tab menus to indicate that the file is readonly."
  "Imagem usada nos menus de guia para indicar que o arquivo é somente leitura."

  "Image used in tab to indicate that the tab contains a difference view."
  "Imagem usada no guia para indicar que o guia contém uma visão de diferença."

  "Image used in tab to indicate that the tab's file is readonly."
  "Imagem usada no guia para indicar que arquivo a aba é somente leitura."

  "Image used in tab to indicate that the tab’s file is locked."
  "Imagem usada no guia para indicar que arquivo a aba é bloqueada."

  "Image used in tab which, when clicked, closes the tab."
  "Imagem usada no guia que, quando clicado, fecha a guia."

  "License"
  "Licença"

  "Line"
  "Linha"

  "Locked"
  "Bloqueado"

  "Move"
  "Mover"

  "Must be in multicursor mode to insert numbers"
  "Deve estar no modo de multicursor para inserir números"

  "No write permissions.  Use '!' to force write."
  "Sem permissões.  Uso '!' para forçar a escrever."

  "Release Type"
  "Tipo de lançamento"

  "Reload file?"
  "Actualizar o Ficheiro"

  "Replace"
  "Substituir"

  "Save request"
  "Salvar Pedido"

  "Show in Sidebar"
  "Show em Sidebar"

  "Starting number:"
  "Número de página inicial:"

  "Tcl/Tk Version"
  "Versão do Tcl/Tk"

  "Total Characters"
  "Personagens totais"

  "Total Lines"
  "Linhas totais"

  "Unable to successfully parse number string"
  "Não é possível analisar com êxito a cadeia numérica"

  "Unable to write file"
  "não foi possível escrever no arquivo"

  "Version"
  "Versão"

}

# markers.tcl
msgcat::mcmset pt {

  "Marker name:"
  "Nome do marcador:"

}

# menus.tcl
msgcat::mcmset pt {

  "About TKE"
  "Sobre TKE"

  "Align Cursors"
  "Alinhar os cursores"

  "Append Next Occurrence"
  "Acrescentar a próxima ocorrência"

  "Auto-Indent"
  "Auto Indentar"

  "Bubble Down"
  "Bolha para baixo"

  "Bubble Up"
  "Forem surgindo"

  "Change Working Directory"
  "Alterar o diretório de trabalho"

  "Character"
  "Personagem"

  "Check for Update"
  "Procurar atualização agora"

  "Clear All"
  "Limpar Tudo"

  "Close All"
  "Fechar Tudo"

  "Close Current"
  "Fechar a Vista Actual"

  "Command"
  "Comando"

  "Command Result"
  "Resultado do comando"

  "Copy"
  "Copiar"

  "Create at Current Line"
  "Criar na linha atual"

  "Create..."
  "Criar..."

  "Current Line"
  "Linha actual:"

  "Current Word"
  "Palavra atual"

  "Cursor"
  "Cursor"

  "Cursor from Line Start"
  "Cursor do início da linha"

  "Cursor to Line End"
  "Cursor para a linha final"

  "Cut"
  "Cortar"

  "Display Text Info"
  "Informações do visor"

  "Edit"
  "Editar"

  "Edit Language"
  "Editar idioma"

  "Edit Menu Edit user snippets"
  "Editar Menu Editar trechos de usuário"

  "Edit Menu: Align cursors"
  "Menu Editar: Alinhar cursores"

  "Edit Menu: Bubble lines down one line"
  "Menu Editar: Linhas de bolha para baixo uma linha"

  "Edit Menu: Bubble lines up one line"
  "Editar Menu: Linhas de bolha uma linha"

  "Edit Menu: Convert case to lower"
  "Menu Editar: Converter caso para baixar"

  "Edit Menu: Convert case to title"
  "Menu Editar: Converter caso a título"

  "Edit Menu: Convert case to upper"
  "Menu Editar: Converter o caso ao superior"

  "Edit Menu: Copy text"
  "Menu Editar: Texto de copiar"

  "Edit Menu: Cut text"
  "Menu Editar: Recortar o texto"

  "Edit Menu: Delete backward numbers"
  "Menu Editar: Apagar os números para trás"

  "Edit Menu: Delete backward whitespace"
  "Menu Editar: Excluir o espaço em branco para trás"

  "Edit Menu: Delete current line"
  "Menu Editar: Excluir a linha atual"

  "Edit Menu: Delete current word"
  "Menu Editar: Excluir palavra atual"

  "Edit Menu: Delete forward numbers"
  "Menu Editar: Apagar os números para a frente"

  "Edit Menu: Delete forward whitespace"
  "Menu Editar: Excluir o espaço em branco para a frente"

  "Edit Menu: Delete from cursor to end of line"
  "Menu Editar: Excluir do cursor ao fim da linha"

  "Edit Menu: Delete from start of line to cursor"
  "Menu Editar: Excluir do início da linha de cursor"

  "Edit Menu: Delete text between character"
  "Menu Editar: Excluir texto entre caracteres"

  "Edit Menu: Edit language snippets"
  "Menu Editar: Editar trechos de linguagem"

  "Edit Menu: Edit session current language preferences"
  "Menu Editar: Editar preferências de idioma atual sessão"

  "Edit Menu: Edit session global preferences"
  "Menu Editar: Editar preferências globais de sessão"

  "Edit Menu: Edit user current language preferences"
  "Menu Editar: Editar preferências de idioma atual do usuário"

  "Edit Menu: Edit user global preferences"
  "Menu Editar: Editar as preferências do usuário global"

  "Edit Menu: Edit user menu bindings"
  "Menu Editar: Editar ligações de menu de usuário"

  "Edit Menu: Format indentation for text"
  "Editar Menu: Formatar o recuo para o texto"

  "Edit Menu: Indent selected text"
  "Menu Editar: Travessão texto selecionado"

  "Edit Menu: Insert command result after current line"
  "Editar Menu: Inserir o resultado do comando depois da linha atual"

  "Edit Menu: Insert file contents after current line"
  "Editar Menu: Inserir o conteúdo do arquivo depois da linha atual"

  "Edit Menu: Insert from clipboard"
  "Menu Editar: Inserção da área de transferência"

  "Edit Menu: Insert line above current line"
  "Editar Menu: Inserir linha acima da linha atual"

  "Edit Menu: Insert line below current line"
  "Editar Menu: Inserir linha abaixo da linha atual"

  "Edit Menu: Insert snippet"
  "Menu Editar: Trecho de inserção"

  "Edit Menu: Join lines"
  "Menu Editar: Linhas de junção"

  "Edit Menu: Move cursor to bottom of screen"
  "Menu Editar: Mover o cursor para o fundo da tela"

  "Edit Menu: Move cursor to end of current line"
  "Menu Editar: Mover o cursor ao fim da linha atual"

  "Edit Menu: Move cursor to first line"
  "Menu Editar: Mover o cursor para a primeira linha"

  "Edit Menu: Move cursor to last line"
  "Menu Editar: Mover o cursor para a última linha"

  "Edit Menu: Move cursor to middle of screen"
  "Menu Editar: Mover o cursor para o meio da tela"

  "Edit Menu: Move cursor to next page"
  "Menu Editar: Mover o cursor para a próxima página"

  "Edit Menu: Move cursor to next word"
  "Menu Editar: Mover o cursor para a próxima palavra"

  "Edit Menu: Move cursor to previous page"
  "Menu Editar: Mover o cursor para a página anterior"

  "Edit Menu: Move cursor to previous word"
  "Menu Editar: Mover o cursor para a palavra anterior"

  "Edit Menu: Move cursor to start of current line"
  "Menu Editar: Mover o cursor para o início da linha atual"

  "Edit Menu: Move cursor to top of screen"
  "Menu Editar: Mover o cursor para a parte superior da tela"

  "Edit Menu: Move multicursors down one line"
  "Menu Editar: Mover a multicursors para baixo uma linha"

  "Edit Menu: Move multicursors left one line"
  "Menu Editar: Mover à esquerda de uma linha de multicursors"

  "Edit Menu: Move multicursors right one line"
  "Menu Editar: Mover a multicursors direito a uma linha"

  "Edit Menu: Move multicursors up one line"
  "Menu Editar: Mover a multicursors uma linha"

  "Edit Menu: Paste and format text from clipboard"
  "Menu Editar: Colar e formatar texto da prancheta"

  "Edit Menu: Paste text from clipboard"
  "Menu Editar: Colar texto da área de transferência"

  "Edit Menu: Redo"
  "Editar Menu: refazer"

  "Edit Menu: Reload snippets"
  "Menu Editar: Trechos de Reload"

  "Edit Menu: Replace line with script"
  "Menu Editar: Substitua a linha com script"

  "Edit Menu: Select all text"
  "Editar Menu: Selecione todo o texto"

  "Edit Menu: Set indent mode to IND"
  "Menu Editar: Definir modo de travessão IND"

  "Edit Menu: Set indent mode to IND+"
  "Menu Editar: Definir modo de travessão IND +"

  "Edit Menu: Set indent mode to OFF"
  "Menu Editar: Definir modo de travessão para OFF"

  "Edit Menu: Set user bindings to global bindings"
  "Menu Editar: Defina ligações de usuário para globais ligações"

  "Edit Menu: Set user preferences to global preferences"
  "Menu Editar: Definir preferências de usuário para preferências globais"

  "Edit Menu: Toggle case of current character"
  "Menu Editar: Alternar caso de caractere atual"

  "Edit Menu: Toggle comment"
  "Menu Editar: Comentário de ativar/desativar"

  "Edit Menu: Undo"
  "Editar Menu: desfazer"

  "Edit Menu: Unindent selected text"
  "Menu Editar: Unindent texto selecionado"

  "Edit Menu: View base preferences file"
  "Menu Editar: Arquivo de base de preferências de exibição"

  "Edit Menu: View global menu bindings"
  "Editar Menu: Exibir menu global ligações"

  "Edit Session - Global"
  "Editar a sessão - Global"

  "Edit Session - Language"
  "Editar a sessão - língua"

  "Edit User"
  "Editar Usuário"

  "Edit User - Global"
  "Editar usuário - Global"

  "Edit User - Language"
  "Editar usuário - idioma"

  "Enumeration"
  "Enumeração"

  "File"
  "Arquivo"

  "File Contents"
  "conteúdo de ficheiro"

  "File Menu: Change working directory"
  "Menu arquivo: Altere o diretório de trabalho"

  "File Menu: Close all tabs"
  "Menu arquivo: Fechar todas as guias"

  "File Menu: Close current tab"
  "Menu arquivo: Fechar a guia atual"

  "File Menu: Favorite file"
  "Menu arquivo: Arquivo de favoritos"

  "File Menu: Lock file"
  "Menu arquivo: Arquivo de bloqueio"

  "File Menu: New file"
  "Menu arquivo: Novo arquivo"

  "File Menu: New window"
  "Menu arquivo: Nova janela"

  "File Menu: Open Favorite"
  "Menu arquivo: Aberto favorito"

  "File Menu: Open Recent"
  "Ferramentas Selector da Direcção"

  "File Menu: Open directory"
  "Menu arquivo: Diretório aberto"

  "File Menu: Open file"
  "Menu arquivo: Abrir arquivo"

  "File Menu: Quit application"
  "Menu arquivo: Pare de aplicação"

  "File Menu: Reopen current file"
  "Menu arquivo: Reabrir o arquivo corrente"

  "File Menu: Save all files"
  "Menu arquivo: Salvar todos os arquivos"

  "File Menu: Save file"
  "Menu arquivo: Salve o arquivo."

  "File Menu: Save file as"
  "Menu arquivo: Salve o arquivo como"

  "File Menu: Save selected lines"
  "Menu arquivo: Salvar as linhas selecionadas"

  "File Menu: Show file difference"
  "Menu arquivo: Mostrar a diferença de arquivo"

  "File Menu: Unfavorite file"
  "Menu arquivo: Arquivo favoritas"

  "File Menu: Unlock file"
  "Menu arquivo: Desbloquear arquivo"

  "Find In Files"
  "Procurar nos Ficheiros..."

  "Find Matching Pair"
  "Encontrar o par de correspondência"

  "Find Menu: Append next occurrence"
  "Menu localizar: Acrescentar a próxima ocorrência"

  "Find Menu: Create marker at current line"
  "Menu localizar: Criar marcador na linha atual"

  "Find Menu: Find"
  "Encontrar o Menu: encontrar"

  "Find Menu: Find and Replace"
  "Menu localizar: Localizar e substituir"

  "Find Menu: Find in files"
  "Menu localizar: Localizar em arquivos"

  "Find Menu: Find matching character pair"
  "Menu localizar: Encontrar o par de caracteres correspondente"

  "Find Menu: Find next occurrence"
  "Menu localizar: Localizar a próxima ocorrência"

  "Find Menu: Find previous occurrence"
  "Menu localizar: Localizar a ocorrência anterior"

  "Find Menu: Goto next difference"
  "Encontrar Menu: Diferença próxima Goto"

  "Find Menu: Goto previous difference"
  "Menu localizar: Diferença anterior Goto"

  "Find Menu: Jump backward"
  "Menu localizar: Saltar para trás"

  "Find Menu: Jump forward"
  "Menu localizar: Salto para a frente"

  "Find Menu: Jump to line"
  "Menu localizar: Salto de linha"

  "Find Menu: Remove all markers"
  "Menu localizar: Remova todos os marcadores"

  "Find Menu: Remove marker from current line"
  "Menu localizar: Remover o marcador de linha atual"

  "Find Menu: Select all occurrences"
  "Menu localizar: Selecionar todas as ocorrências"

  "Find Menu: Show selected line change"
  "Menu localizar: Mudança de linha de Show selecionado"

  "Find and Replace"
  "Localizar e substituir"

  "Format Text"
  "Text Format"

  "From Clipboard"
  "Correcção da Área de Transferência"

  "Goto Last Tab"
  "Ir à última guia"

  "Goto Next Tab"
  "Ir à Próxima Tab"

  "Goto Other Pane"
  "Outros Pane Goto"

  "Goto Previous Tab"
  "Ir à aba anterior"

  "Help"
  "Ajuda"

  "Help Menu: About TKE"
  "Menu Ajuda: Sobre TKE"

  "Help Menu: Check for update"
  "Menu Ajuda: Verificar atualização"

  "Help Menu: Send bug report"
  "Menu Ajuda: Enviar relatório de erros"

  "Help Menu: Send feedback"
  "-Menu Ajuda: Gabarito de Send"

  "Help Menu: View user guide"
  "Menu Ajuda: Guia do usuário exibir"

  "Hide Console"
  "Ocultar Console"

  "Hide Line Numbers"
  "Esconder os números de linha"

  "Hide Marker Map"
  "Esconder mapa marcador"

  "Hide Meta Characters"
  "Esconder os Meta caracteres"

  "Hide Sidebar"
  "Esconder a Barra Lateral"

  "Hide Status Bar"
  "Ocultar Barra de Status"

  "Hide Tab Bar"
  "Esconder Tab Bar"

  "Indent"
  "Avançar"

  "Indent Off"
  "Travessão fora"

  "Indentation"
  "Indentação"

  "Insert"
  "Inserir"

  "Install..."
  "Instalação"

  "Join Lines"
  "Unir Linhas"

  "Jump Backward"
  "Saltar para trás"

  "Jump Forward"
  "Saltar para a frente"

  "Jump To Line"
  "Saltar para a linha"

  "Launcher"
  "Lançador"

  "Line Above Current"
  "Linha superior corrente"

  "Line Below Current"
  "Linha abaixo a corrente"

  "Line Number"
  "Número de Linha"

  "Lock"
  "Fixar"

  "Lower Case"
  "caixa baixa"

  "Markers"
  "Marcadores"

  "Menu Bindings"
  "Ligações de Menu"

  "Menus: About TKE"
  "Menus: Sobre TKE"

  "Merge Panes"
  "Mesclar painéis"

  "Move Cursors Down"
  "Mova os cursores para baixo"

  "Move Cursors Left"
  "Mover cursores esquerda"

  "Move Cursors Right"
  "Mover para a direita de cursores"

  "Move Cursors Up"
  "Mova os cursores para cima"

  "Move to First Line"
  "Mover para a primeira linha"

  "Move to Last Line"
  "Mover para a última linha"

  "Move to Line End"
  "Mover para o fim de linha"

  "Move to Line Start"
  "Mover para a linha de início"

  "Move to Next Page"
  "Mover para a próxima página"

  "Move to Next Word"
  "Mover para a próxima palavra"

  "Move to Previous Page"
  "Ir para página anterior"

  "Move to Previous Word"
  "Mover para a palavra anterior"

  "Move to Screen Bottom"
  "Mover para o fundo de tela"

  "Move to Screen Middle"
  "Mover para o meio da tela"

  "Move to Screen Top"
  "Mover para o topo da tela"

  "New Window"
  "Nova Janela"

  "Next Difference"
  "Próxima Diferença"

  "Numbers Backward"
  "Números para trás"

  "Numbers Forward"
  "Números para a frente"

  "Open Directory..."
  "Abrir diretório..."

  "Open Favorite"
  "Abrir Favorita"

  "Open File..."
  "Abrir um Ficheiro..."

  "Open Recent"
  "Abrir um Recente"

  "Paste"
  "Colar"

  "Paste and Format"
  "Colar formato"

  "Plugins"
  "Plugins"

  "Plugins Menu: Create new plugin"
  "Menu de plugins: Criar novo plugin"

  "Plugins Menu: Install plugin"
  "Menu de plugins: Instalar plugin"

  "Plugins Menu: Reload all plugins"
  "Menu de plugins: Recarregar todos os plugins"

  "Plugins Menu: Uninstall plugin"
  "Menu de plugins: Desinstalar o plugin"

  "Preferences"
  "Preferências"

  "Previous Difference"
  "Diferença Anterior"

  "Profiling Report Sorted By"
  "Relatório de perfil classificado por"

  "Profiling started"
  "Profiling começou"

  "Profiling stopped"
  "Profiling parado"

  "Quit"
  "Desistir"

  "Redo"
  "Refazer"

  "Reload"
  "Recarregar"

  "Remove All Markers"
  "Remova todos os marcadores"

  "Remove From Current Line"
  "Remover da linha atual"

  "Reopen File"
  "Reabrir o arquivo."

  "Replace Line With Script"
  "Substituir a linha com Script"

  "Reset User to Base"
  "Redefinir o usuário à Base"

  "Restart TKE"
  "Reiniciar TKE"

  "Save All"
  "Gravar Tudo"

  "Save As..."
  "Salvar como..."

  "Save Current"
  "Salvar a skin atual"

  "Save Selection As..."
  "Salvar seleção como..."

  "Select All"
  "Selecionar tudo"

  "Select All Occurrences"
  "Selecionar todas as ocorrências"

  "Select Next Occurrence"
  "Selecione a próxima ocorrência"

  "Select Previous Occurrence"
  "Selecione a ocorrência anterior"

  "Send Bug Report"
  "Comunicar um erro."

  "Send Feedback"
  "Enviar Comentário"

  "Sessions"
  "Sessões"

  "Sessions Menu: Close current session"
  "Menu de sessões: Fechar a sessão atual"

  "Sessions Menu: Delete session"
  "Sessões de Menu: Sessão de excluir"

  "Sessions Menu: Save current session"
  "Sessões Menu: Salvar a sessão atual"

  "Sessions Menu: Save sessions as"
  "Sessões Menu: Salvar sessões como"

  "Sessions Menu: Switch to session"
  "Menu de sessões: Interruptor de sessão"

  "Set Syntax"
  "Definir Sintaxe"

  "Set Theme"
  "Definir Tema"

  "Set User to Global"
  "Definir usuário Global"

  "Show Console"
  "Mostrar Console"

  "Show Diagnostic Logfile"
  "Mostrar arquivo de log de diagnóstico"

  "Show File Difference"
  "Mostrar a diferença de arquivo."

  "Show Last Profiling Report"
  "Mostrar Último Relatório Profiling"

  "Show Line Numbers"
  "Mostrar os Números de Linha"

  "Show Marker Map"
  "Exibir Marcador"

  "Show Meta Characters"
  "Mostrar os Meta caracteres"

  "Show Selected Line Change"
  "Mostrar a mudança de linha selecionada"

  "Show Sidebar"
  "Mostrar a Barra Lateral"

  "Show Status Bar"
  "Barra de Estado"

  "Show Tab Bar"
  "Barra de Páginas"

  "Smart Indent"
  "Travessão inteligente"

  "Snippet"
  "﻿Trecho"

  "Snippets"
  "Trechos"

  "Sort Tabs"
  "Sort Tabs"

  "Start Profiling"
  "Comece Profiling"

  "Stop Profiling"
  "Pare Profiling"

  "Switch To"
  "Trocar para"

  "Tabs"
  "Guias"

  "Text Between Character"
  "Texto entre caracteres"

  "Text Menu: Insert enumeration"
  "Texto Menu: Enumeração de inserção"

  "Title Case"
  "Capitalização do título"

  "Toggle Case"
  "Mudar a capitalização"

  "Toggle Comment"
  "Comentário de alternância"

  "Tools"
  "Ferramentas"

  "Tools Menu: Disable Vim mode"
  "Menu ' ferramentas ': Desativar o modo de Vim"

  "Tools Menu: Enable Vim mode"
  "Menu de ferramentas: Habilitar o modo de Vim"

  "Tools Menu: Restart TKE"
  "Menu de ferramentas: Restart TKE"

  "Tools Menu: Run theme editor"
  "Menu Ferramentas: Executar editor tema"

  "Tools Menu: Show diagnostic logfile"
  "Menu de ferramentas: Mostrar o arquivo de log de diagnóstico"

  "Tools Menu: Show last profiling report"
  "Menu de ferramentas: Mostrar o último relatório de perfil"

  "Tools Menu: Start profiling"
  "Menu de ferramentas: Iniciar criação de perfil"

  "Tools Menu: Stop profiling"
  "Menu Ferramentas: Parar a criação de perfil"

  "Transform"
  "Transform"

  "Undo"
  "Anular"

  "Unindent"
  "Unindent"

  "Uninstall..."
  "Desinstalação..."

  "Unlock"
  "Unlock"

  "Upper Case"
  "CAIXA SUPERIOR"

  "User Guide"
  "Guia do Usuário"

  "View"
  "Vista"

  "View Base"
  "Vista Base"

  "View Global"
  "Visão Global"

  "View Menu: Display text information"
  "Menu exibir: Visualizar informações de texto"

  "View Menu: Goto last tab"
  "Menu exibir: Última guia Goto"

  "View Menu: Goto next tab"
  "Menu exibir: Próxima guia Goto"

  "View Menu: Goto other pane"
  "Menu exibir: Goto outro painel"

  "View Menu: Goto previous tab"
  "Menu exibir: Guia anterior do Goto"

  "View Menu: Hide console"
  "Menu exibir: Console de ocultar"

  "View Menu: Hide line numbers"
  "Menu exibir: Esconder os números de linha"

  "View Menu: Hide marker map"
  "Menu exibir: Esconder marcador mapa"

  "View Menu: Hide meta characters"
  "Ver Menu: Ocultar os meta caracteres"

  "View Menu: Hide sidebar"
  "Menu exibir: Barra lateral de ocultar"

  "View Menu: Hide status bar"
  "Menu exibir: Ocultar a barra de status"

  "View Menu: Hide tab bar"
  "Menu exibir: Ocultar a barra de guia"

  "View Menu: Merge panes"
  "Menu exibir: Painéis de mesclagem"

  "View Menu: Move to other pane"
  "Menu exibir: Mover para outro painel"

  "View Menu: Show console"
  "Menu exibir: Console de mostrar"

  "View Menu: Show line numbers"
  "Menu exibir: Mostrar números de linha"

  "View Menu: Show marker map"
  "Menu exibir: Mostrar marcador mapa"

  "View Menu: Show meta characters"
  "Menu exibir: Mostrar meta caracteres"

  "View Menu: Show sidebar"
  "Ver Mostrar a Barra Lateral"

  "View Menu: Show status bar"
  "Menu exibir: Mostrar barra de status"

  "View Menu: Show tab bar"
  "Menu exibir: Mostrar barra de guia"

  "View Menu: Sort tabs"
  "Menu exibir: Guias de tipo"

  "View Menu: Toggle split view mode"
  "Menu exibir: Alternar o modo de exibição de dividir"

  "Vim Mode"
  "Modo Vim"

  "Whitespace Backward"
  "Espaço em branco para trás"

  "Whitespace Forward"
  "Espaço em branco para a frente"

}

# plugins.tcl
msgcat::mcmset pt {

  "Always grant from developer"
  "Sempre conceder a partir desenvolvedor"

  "ERROR"
  "Erro"

  "ERROR:  Plugin name already exists"
  "ERRO: Nome do Plugin já existe"

  "ERROR:  Plugin name is not valid (only alphanumeric and underscores are allowed)"
  "ERRO: Plugin nome não é válido (apenas caracteres alfanuméricos e sublinhados são permitidos)"

  "ERROR:  Unable to create plugin directory"
  "Erro: Não foi possível criar o diretório de plugins"

  "ERROR:  Unable to write plugin files"
  "ERRO: Não é possível gravar arquivos de plugin"

  "Enter plugin name"
  "Digite o nome do plugin"

  "Grant"
  "Conceda"

  "Grant permssion?"
  "Conceda permssion?"

  "OK"
  "OK"

  "Plugin Errors"
  "Erros Plugin"

  "Plugin Trust Requested"
  "Plugin Confiança solicitada"

  "Plugin installed"
  "Plugin instalado"

  "Plugin requires permission to view or modify your system."
  "Plugin requer permissão para exibir ou modificar o seu sistema."

  "Plugin uninstalled"
  "Plugin desinstalado"

  "Plugins successfully reloaded"
  "Plugins recarregados com sucesso"

  "Reject"
  "Rejeitado"

  "Syntax errors found in selected plugins"
  "Os erros de sintaxe encontrados em plugins selecionados"

}

# search.tcl
msgcat::mcmset pt {

  "No files found in specified directories"
  "Não há arquivos encontrados em diretórios especificados"

  "No search results found"
  "Resultados Encontrados da Pesquisa"

  "Search wrapped to beginning of file"
  "Busca ajustada para início do arquivo."

  "Search wrapped to end of file"
  "Pesquisa envolto ao final do arquivo"

  "substitutions done"
  "feito de substituições"

}

# sessions.tcl
msgcat::mcmset pt {

  "Save session?"
  "Gravar a Sessão?"

  "Session state will be lost if not saved"
  "O estado da sessão será perdido se não for salvo"

}

# sidebar.tcl
msgcat::mcmset pt {

  "Add Parent Directory"
  "Directório pai"

  "Close Directory Files"
  "Fechar Arquivos Diretório"

  "Copy Pathname"
  "Copie o caminho do"

  "Delete directories?"
  "Apagar Diretórios Antigos"

  "Delete directory?"
  "Excluir diretório?"

  "Delete file?"
  "Excluir arquivo"

  "Delete files?"
  "Excluir Arquivos"

  "Directory Name:"
  "Nome do diretório:"

  "Duplicate"
  "Duplicação"

  "File Name:"
  "Nome do arquivo:"

  "Folder Name:"
  "Nome da Pasta:"

  "Image displayed in sidebar to indicate that a file is currently opened in an editing buffer."
  "Imagem exibida na lateral para indicar que um arquivo é aberto no momento em um buffer de edição."

  "Make Current Working Directory"
  "Faça diretório de trabalho atual"

  "New Directory"
  "Novo Diretório"

  "Open Directory Files"
  "Arquivos Open Directory"

  "Refresh Directory Files"
  "Atualizar arquivos do diretório"

  "Remove Parent from Sidebar"
  "Remover Pai de Sidebar"

  "Remove from Sidebar"
  "Retire do Sidebar"

  "Rename"
  "Renomear"

  "Show Difference"
  "Mostrar a diferença"

}

# snippets.tcl
msgcat::mcmset pt {

  "Snippet: *"
  "﻿Trecho"

}

# syntax.tcl
msgcat::mcmset pt {

  "Syntax"
  "Sintaxe"

  "Syntax error in syntax file"
  "Erro de sintaxe no arquivo de sintaxe"

}

# theme.tcl
msgcat::mcmset pt {

  "Background (trough) color used in the sidebar scrollbar."
  "Cor de fundo (calha) usado na barra de rolagem lateral."

  "Background (trough) color used in the text scrollbars."
  "Cor de fundo (calha) utilizado em barras de rolagem de texto."

  "Background color for all sidebar items that are not selected."
  "Cor de fundo para todos os itens da barra lateral que não estão selecionados."

  "Background color for all sidebar items that are selected."
  "Cor de fundo para todos os itens da barra lateral que estão selecionados."

  "Background color in difference viewer that shows added lines."
  "Cor de fundo no Visualizador de diferença que mostra adicionou linhas."

  "Background color in difference viewer that shows deleted lines."
  "Cor de fundo no Visualizador de diferença que mostra excluído linhas."

  "Background color of insertion cursor and background marker colors."
  "A cor do fundo do cursor de inserção e marcadores fundo cores."

  "Background color of the editing buffer."
  "Cor de fundo do buffer de edição."

  "Background color to display when a button-like ttk widget is pressed."
  "Cor de fundo a ser exibido quando um widget ttk como botão é pressionado."

  "Background color to use for selected text."
  "Cor de fundo a ser usado para o texto selecionado."

  "Background color used for all other tabs that are not the current/active tab in the tabbar."
  "Cor de fundo usada para todas as outras abas que não sejam a guia de corrente/ativo no tabbar."

  "Background color used for the current/active menu item."
  "Cor de fundo usada para o item de menu atual/ativo."

  "Background color used for the current/active tab in the tabbar."
  "Cor de fundo usado para guia de corrente/ativo no tabbar."

  "Background color used in highlighted text."
  "Cor de fundo usada no texto realçado."

  "Background color used in menus."
  "Cor de fundo usado em menus."

  "Background color used in the tabbar area."
  "Cor de fundo usada na área tabbar."

  "Color of border drawn around active editing buffer."
  "Cor da borda desenhada ao redor de buffer de edição ativa."

  "Color of ttk entry widget text border when the entry has keyboard focus."
  "Cor da borda de texto de ttk entrada widget quando a entrada tem o foco do teclado."

  "Color used to draw the warning width line in the editing buffer (as well as the line separating the gutter from the editing buffer)."
  "Cor usada para desenhar a linha de largura de aviso no buffer de edição (bem como a linha que separa a calha do buffer de edição)."

  "Default 'darkcolor' for all ttk widgets."
  "Padrão 'darkcolor' para todos os widgets ttk."

  "Default background color to use for all ttk widgets that are in a disabled state."
  "Cor de fundo padrão a ser usado para todos os widgets ttk que estão em um estado desabilitado."

  "Default background color to use for all ttk widgets when the mouse cursor hovers over the widget."
  "Cor de fundo a ser usado para todos os widgets ttk quando o cursor do mouse passa sobre o widget padrão."

  "Default background color to use for all ttk widgets."
  "Cor de fundo padrão a ser usado para todos os widgets ttk."

  "Default border color for all ttk widgets."
  "Cor da borda padrão para todos os widgets ttk."

  "Default color for non-syntax highlighted text."
  "Cor padrão para non-sintaxe texto realçado."

  "Default foreground text color to use for all ttk widgets that are in a disabled state."
  "Padrão de cor do primeiro plano de texto a ser usado para todos os widgets ttk que estão em um estado desabilitado."

  "Default foreground text color to use for all ttk widgets."
  "Padrão de cor do primeiro plano de texto a ser usado para todos os widgets ttk."

  "Determines the number of grips strips to display in the grip area between resizable panes."
  "Determina o número de tiras de apertos para exibir na área de aderência entre painéis redimensionáveis."

  "Determines the thickness of the grip area between resizable panes."
  "Determina a espessura da área de aderência entre painéis redimensionáveis."

  "ERROR:  Unable to read"
  "ERRO: Não é possível ler"

  "Foreground (slider) color used in the sidebar scrollbar."
  "Cor de primeiro plano (slider) usado na barra de rolagem lateral."

  "Foreground (slider) color used in the text scrollbars."
  "Cor de primeiro plano (slider) utilizado em barras de rolagem de texto."

  "Foreground text color for strings."
  "Cor do texto do primeiro plano para seqüências de caracteres."

  "Foreground text color to use for all miscellaneous1 labeled text."
  "Cor do primeiro plano de texto a ser usado para todos os miscellaneous1 rotulado de texto."

  "Foreground text color to use for all miscellaneous2 labeled text."
  "Cor do primeiro plano de texto a ser usado para todos os miscellaneous2 rotulado de texto."

  "Foreground text color to use for all miscellaneous3 labeled text."
  "Cor do primeiro plano de texto a ser usado para todos os miscellaneous3 rotulado de texto."

  "Foreground text color to use for comments."
  "Cor do primeiro plano de texto a ser usado para comentários."

  "Foreground text color to use for displaying line numbers."
  "Cor do texto do primeiro plano para usar para exibir números de linha."

  "Foreground text color to use for displaying numbers."
  "Cor do texto do primeiro plano para usar para exibir os números."

  "Foreground text color to use for language-specific keywords."
  "Cor do primeiro plano de texto a ser usado para palavras-chave específicas de idioma."

  "Foreground text color to use for language-specific punctuation."
  "Cor do primeiro plano de texto a ser usado para Pontuação de específicos do idioma."

  "Foreground text color to use for meta syntax."
  "Cor do texto do primeiro plano para usar sintaxe de meta."

  "Foreground text color to use for precompiler syntax."
  "Cor do texto do primeiro plano para usar sintaxe pré-compilador."

  "Foreground text color to use for selected text."
  "Cor do texto do primeiro plano para o texto selecionado."

  "Foreground text color used for all other tabs that are not the current/active tab in the tabbar."
  "Cor do texto do primeiro plano usado para todas as outras abas que não sejam a guia de corrente/ativo no tabbar."

  "Foreground text color used for menus item that are disabled."
  "Cor do texto do primeiro plano usado para item de menus que estão desativados."

  "Foreground text color used for the current/active menu item."
  "Cor de primeiro plano texto usado para o item de menu atual/ativo."

  "Foreground text color used for the current/active tab in the tabbar."
  "Cor do texto do primeiro plano usado para guia de corrente/ativo no tabbar."

  "Foreground text color used in menus."
  "Cor de primeiro plano texto usado nos menus."

  "Foreground text/image color used in tabbar and tabs."
  "Cor do texto/imagem de primeiro plano usado em tabbar e guias."

  "Images"
  "Imagens"

  "Maximum thickness of the text scrollbar when it is active."
  "Espessura máxima da barra de rolagem de texto quando ele estiver ativo."

  "Maximum thickness of the text scrollbars when they are active."
  "Espessura máxima das barras de rolagem de texto quando estão ativos."

  "Menu Options"
  "Opções de menu"

  "Menu relief value."
  "Valor de alívio do menu."

  "Pixel height of the tabbar widget."
  "Altura de pixel do tabbar widget."

  "Relief used in drawing the tabs."
  "Utilizados na elaboração das guias de alívio."

  "Relief value of the sidebar area."
  "Valor de relevo da área da barra lateral."

  "Sidebar Options"
  "Opção de Barra Lateral"

  "Sidebar Scrollbar Options"
  "Sidebar Opções de barra de rolagem"

  "Specifies the color to display around the sidebar when the sidebar does not have the focus."
  "Especifica a cor para exibir em torno de barra lateral quando a barra lateral não tem o foco."

  "Specifies the color to display around the sidebar when the sidebar has the focus."
  "Especifica a cor para exibir em torno de barra lateral quando a barra lateral tem o foco."

  "Specifies the default background color to use for text that is selected in a standard ttk widget (this does not include the editing buffer)."
  "Especifica a cor de fundo padrão a ser usado para o texto selecionado em um widget de ttk padrão (isso não inclui o buffer de edição)."

  "Specifies the default foreground text color to use for text that is selected in a standard ttk widget (this does not include the editing buffer)."
  "Especifica a cor do texto do primeiro plano padrão a ser usado para o texto selecionado em um widget de ttk padrão (isso não inclui o buffer de edição)."

  "Specifies the default relief to use when drawing ttk widgets."
  "Especifica o alívio de padrão para usar quando desenho ttk widgets."

  "Specifies the disclosure image style to use in the sidebar."
  "Especifica o estilo de imagem de divulgação para usar na barra lateral."

  "Specifies the pixel thickness of the highlight line."
  "Especifica a espessura de pixel da linha de destaque."

  "Syntax Colors"
  "Sintaxe Colors"

  "Tab Options"
  "Opções da Aba"

  "Text Scrollbar Options"
  "Opções de texto barra de rolagem"

  "Text color for all sidebar items that are not selected."
  "Cor do texto para todos os itens da barra lateral que não estão selecionados."

  "Text color for all sidebar items that are selected."
  "Cor do texto para todos os itens da barra lateral que estão selecionados."

  "ttk Widget Colors"
  "ttk Widget Colors"

}

# themer.tcl
msgcat::mcmset pt {

  "   Show All"
  "Mostrar tudo"

  "   Show Category"
  "Exibir Categoria"

  "   Show Color"
  "Mostrar Cor de Fundo"

  "   Show Selected Option"
  "Mostrar opção selecionada"

  "   Show Selected Value"
  "Mostrar o valor selecionado"

  "Categories"
  "Categorias"

  "Change Base Color"
  "Mudar a cor"

  "Choose Theme"
  "Escolha um Tema"

  "Custom Directory"
  "Directório Personalizado"

  "Custom..."
  "Personalizadas..."

  "Delete swatch?"
  "Excluir amostra?"

  "Description"
  "Descrição Longa"

  "Details"
  "Leia Mais ..."

  "Done"
  "Finalizado"

  "Export"
  "Exportar"

  "GIF Photo"
  "GIF Foto"

  "Import"
  "Importe"

  "Import BMP Data"
  "Importar dados"

  "Import BMP Mask"
  "Importar máscara"

  "Import Error"
  "Erro de Importação!"

  "Import Theme File"
  "Importar Arquivo de Tema"

  "Installation Directory"
  "Diretório de Instalação"

  "Modifications"
  "Modificações"

  "None"
  "Nenhum"

  "One-Color Bitmap"
  "Bitmap de uma cor"

  "Preview"
  "Visualizar"

  "Relief: "
  "Válvula de"

  "Save As:"
  "Salvar como:"

  "Save theme changes?"
  "Salve as alterações do tema?"

  "Select Directory"
  "Selecionar diretório"

  "Swatch"
  "Swatch"

  "Swatch Colors"
  "Swatch Colors"

  "Table Filters"
  "Filtros de Mesa"

  "The current theme has unsaved changes"
  "O tema atual tem alterações não salvas"

  "Tree Style: "
  "Estilo Tree:"

  "Two-Color Bitmap"
  "Bitmap de duas cores"

  "User Directory"
  "Directório de utilizador"

  "Value"
  "Valor"

  "Value: "
  "Valor:"

}

# themes.tcl
msgcat::mcmset pt {

  "Theme"
  "Tema"

  "Theme:*"
  "Tema"

}

# tke.tcl
msgcat::mcmset pt {

  "Import TKE theme?"
  "Tema Import TKE?"

  "Import TextMate theme?"
  "Importe tema TextMate?"

}

# tkedat.tcl
msgcat::mcmset pt {

  "Unable to read"
  "Não foi possível ler o ficheiro."

}

# General
msgcat::mcmset pt {

  "Cancel"
  "Cancelar"

  "Close"
  "Fecho"

  "Delete"
  "Excluir"

  "Favorite"
  "Favorito"

  "Find"
  "Encontrar"

  "Move to Other Pane"
  "Mover para outro painel"

  "New File"
  "Novo arquivo"

  "Open"
  "Abrir"

  "Save"
  "Salvar"

  "Save As"
  "Salvar como"

  "Split View"
  "Dividir a Vista"

  "Theme Editor"
  "Editor de temas"

  "Unable to write"
  "Não foi possível gravar o ficheiro"

  "Unfavorite"
  "Unfavorite"

}

