# api.tcl
msgcat::mcmset ru {

  "Argument list to api::add_file was not an even key/value pair"
  "Список аргументов api::add_file некорректен по парам ключ/значение"

}

# bgproc.tcl
msgcat::mcmset ru {

  "Unable to run system command"
  "Невозможно выполнить системную команду"

}

# bist.tcl (In development mode -- selectable in the Advanced preferences section -- select "Tools / Run BIST")
msgcat::mcmset ru {

  "Built-In Self Test"
  "Встроенный самоконтроль"

  "Decrementing order"
  "Порядок уменьшения"

  "Edit Test"
  "Редактировать тест"

  "Edit Test File"
  "Редактировать файл теста"

  "FAILED"
  "НЕУДАЧНО"

  "Fail"
  "Неудача"

  "Fail Count"
  "Количество неудач"

  "Failed"
  "Неудачно"

  "Filter"
  "Фильтр"

  "Incrementing order"
  "Порядок увеличения"

  "Iteration"
  "Итерация"

  "Iteration count"
  "Счетчик итераций"

  "Loop"
  "Цикл"

  "Loop count"
  "Счетчик циклов"

  "Loop type"
  "Тип цикла"

  "New Test"
  "Новый тест"

  "New Test File"
  "Новый тестовый файл"

  "New Test Name"
  "Название нового теста"

  "Output"
  "Вывод"

  "PASSED"
  "ПРОЙДЕНО"

  "Pass"
  "Проход"

  "Pass Count"
  "Счетчик проходов"

  "Passed"
  "Пройдено успешно"

  "RUNNING BIST"
  "ВЫПОЛНЕНИЕ BIST"

  "Random"
  "Случайно"

  "Refresh"
  "Обновить"

  "Results"
  "Результаты"

  "Run Count"
  "Запустить счет"

  "Run iterations"
  "Запустить итерации"

  "Run loops"
  "Запустить циклы"

  "Running"
  "Выполняется"

  "Runtime"
  "Время исполнения"

  "Selection method"
  "Метод отбора"

  "Setup"
  "Настройка"

  "Total"
  "Всего"

  "hours"
  "часов"

  "minutes"
  "минут"

  "seconds"
  "секунд"

}

# bitmap.tcl (Strings are found in the theme editor for a bitmapped image)
msgcat::mcmset ru {

  "Center image"
  "Центрировать изображение"

  "Flip image horizontally"
  "Повернуть изображение горизонтально"

  "Flip image vertically"
  "Повернуть изображение вертикально"

  "Move image down"
  "Изображение вниз"

  "Move image left"
  "Изображение налево"

  "Move image right"
  "Изображение направо"

  "Move image up"
  "Изображение вверх"

  "Rotate image 90 degrees"
  "Повернуть на 90 градусов"

  "Transform Tools"
  "Трансформации"

}

# diff.tcl (Go to File menu and select "Show File Differences".  Strings are shown at bottom of editor.)
msgcat::mcmset ru {

  "    End: "
  "    По:"

  "    Start: "
  "    С:"

  "Enter difference command"
  "Введите команду различения"

  "Enter starting file"
  "Введите начальный файл"

}

# edit.tcl
msgcat::mcmset ru {

  "File successfully written"
  "Файл успешно сохранен"

  "Filename already exists"
  "Файл уже существует"

  "Image URL"
  "URL изображения"

  "Link URL"
  "URL ссылки"

}

# emmet.tcl
msgcat::mcmset ru {

  "Abbreviation"
  "Тег"

  "Select File to Save"
  "Выберите файл для сохранения"

}

# files.tcl
msgcat::mcmset ru {

  "Delete tab?"
  "Удалить вкладку?"

  "Reload file?"
  "Перезагрузить файл?"

  "Unable to determine how to move to trash"
  "Невозможно переместить в корзину"

  "Unable to determine platform"
  "Невозможно определить ОС"

  "Unable to write file"
  "Невозможно сохранить файл"

  "Unable to write remote file"
  "Невозможно сохранить сетевой файл"

}

# gui.tcl
msgcat::mcmset ru {

  "Case sensitivity"
  "Чувствительность к регистру символов"

  "Close All Other Tabs"
  "Закрыть все другие вкладки"

  "Close All Tabs"
  "Закрыть все вкладки"

  "Close All Tabs In Pane"
  "Закрыть все вкладки в панели"

  "Close Other Tabs In Pane"
  "Закрыть другие вкладки в панели"

  "Close Tab"
  "Закрыть вкладку"

  "Column"
  "Столбец"

  "Copyright"
  "Авторские права"

  "Credits"
  "Соавторы"

  "Developer"
  "Разработчик"

  "Email"
  "Эл.почта"

  "Error"
  "Ошибка"

  "Exact"
  "Точное совпадение"

  "Favorited"
  "Избранное"

  "File already exists.  Use '!' to force an overwrite"
  "Файл уже существует.  Используйте '!' для перезаписи"

  "File index is out of range"
  "Индекс файла вне диапазона"

  "Glob"
  "Шаблон glob"

  "Hide Tab"
  "Спрятать вкладку"

  "Image displayed in fill-in forms which closes the form UI.  Used in forms such as search, search/replace, and find in files."
  "Изображение для закрытия диалога.  Используется в диалогах типа поиска, поиска/замены и поиска в файлах."

  "Image displayed in find field to search for next match."
  "Изображение в поле поиска следующего совпадения."

  "Image displayed in find field to search for previous match."
  "Изображение в поле поиска предыдущего совпадения."

  "Image used in tab menus to indicate that the file is associated with a difference view."
  "Изображение во вкладках означающее, что этот файл для просмотра различий."

  "Image used in tab menus to indicate that the file is locked."
  "Изображение во вкладках означающее, что файл заблокирован."

  "Image used in tab menus to indicate that the file is readonly."
  "Изображение во вкладках означающее, что файл только для чтения."

  "Image used in tab to indicate that the tab contains a difference view."
  "Изображение во вкладках означающее, что это просмотр различий."

  "Image used in tab to indicate that the tab's file is readonly."
  "Изображение во вкладках означающее, что файл только для чтения."

  "Image used in tab to indicate that the tab’s file is locked."
  "Изображение во вкладках означающее, что файл заблокирован."

  "Image used in tab which, when clicked, closes the tab."
  "Изображение во вкладках, при клике на котором вкладка закрывается."

  "Image used in the menus to indicate that a menu item is not selected."
  "Изображение в меню для указания, что пункт меню не выбран."

  "Image used in the menus to indicate that a menu item is selected."
  "Изображение в меню для указания, что пункт меню выбран."

  "Image used in the preferences window in the Advanced tab."
  "Изображение в окне Настройки для вкладки Дополнительно."

  "Image used in the preferences window in the Appearance tab."
  "Изображение в окне Настройки для вкладки Внешний вид."

  "Image used in the preferences window in the Documentation tab."
  "Изображение в окне Настройки для вкладки Документация."

  "Image used in the preferences window in the Editor tab."
  "Изображение в окне Настройки для вкладки Редактор."

  "Image used in the preferences window in the Emmet tab."
  "Изображение в окне Настройки для вкладки Emmet."

  "Image used in the preferences window in the Find tab."
  "Изображение в окне Настройки для вкладки Поиск."

  "Image used in the preferences window in the General tab."
  "Изображение в окне Настройки для вкладки Общие."

  "Image used in the preferences window in the Plugins tab."
  "Изображение в окне Настройки для вкладки Плагины."

  "Image used in the preferences window in the Shortcuts tab."
  "Изображение в окне Настройки для вкладки Комбинации клавиш."

  "Image used in the preferences window in the Sidebar tab."
  "Изображение в окне Настройки для вкладки Боковая панель."

  "Image used in the preferences window in the Snippets tab."
  "Изображение в окне Настройки для вкладки Фрагменты кода."

  "Image used in the preferences window in the View tab."
  "Изображение в окне Настройки для вкладки Вид."

  "Image used in the preferences window to indicate that a table item is deselected."
  "Изображение в окне Настройки означающее, что элемент таблицы не выбран."

  "Image used in the preferences window to indicate that a table item is selected."
  "Изображение в окне Настройки означающее, что элемент таблицы выбран."

  "Image used in the preferences window to indicate that something is true."
  "Изображение в окне настройки означающее, что что-то истинно."

  "Images used in tab which will be displayed when the mouse enters the close button area"
  "Изображение во вкладке, отображаемое при наведении курсора мыши на кнопку Закрыть"

  "In"
  "В"

  "License"
  "Лицензия"

  "Locked"
  "Заблокирован"

  "Move"
  "Переместить"

  "Must be in multicursor mode to insert numbers"
  "Должен быть режим multicursor для ввода чисел"

  "No write permissions.  Use '!' to force write."
  "Нет разрешения на запись.  Используйте '!' для перезаписи."

  "Regexp"
  "Регулярное выражение"

  "Release Type"
  "Тип релиза"

  "Replace"
  "Заменить"

  "Replace All"
  "Заменить все"

  "Save request"
  "Запрос на сохранение"

  "Save this search"
  "Сохранить этот поиск"

  "Starting number:"
  "Начальный номер:"

  "Tcl/Tk Version"
  "Версия Tcl/Tk"

  "Total Characters"
  "Всего символов"

  "Total Lines"
  "Всего строк"

  "Unable to successfully parse number string"
  "Невозможно разобрать строку с числом"

  "for"
  "для"

}

# indent.tcl
msgcat::mcmset ru {

  "No Indent"
  "Без отступа"

}

# ipanel.tcl (Information panel displayed in the sidebar)
msgcat::mcmset ru {

  "Binary"
  "Бинарный"

  "Close Panel"
  "Закрыть панель"

  "Counts"
  "Счетчики"

  "Modified"
  "Изменен"

  "No"
  "Нет"

  "Read Time"
  "Время чтения"

  "Update Info"
  "Обновить сведения"

  "Yes"
  "Да"

  "value copied to clipboard"
  "значение, скопированное в буфер обмена"

}

# markers.tcl
msgcat::mcmset ru {

  "Marker name:"
  "Имя маркера:"

}

# menus.tcl
msgcat::mcmset ru {

  "About"
  "О программе"

  "Absolute"
  "Абсолютная"

  "Absolute line numbering"
  "Абсолютная нумерация строк"

  "Add Next Line"
  "Добавить следующую строку"

  "Add Previous Line"
  "Добавить предыдущую строку"

  "Add next line to selection"
  "Добавить следующую строку с выделением"

  "Add previous line to selection"
  "Добавить предыдущую строку с выделением"

  "Align Cursors Only"
  "Выровнять только курсоры"

  "Align Cursors and Text"
  "Выровнять курсоры и текст"

  "Align Panes"
  "Выровнять панели"

  "Align current lines in both panes"
  "Выровнять текущие строки в обеих панелях"

  "Align cursors and text"
  "Выровнять курсоры и текст"

  "Align cursors only"
  "Выровнять только курсоры"

  "All Levels"
  "Все уровни"

  "All language-specific settings for the current session will be removed and the global settings will be applied for the specified language."
  "Будут удалены все языковые настройки для текущего сеанса и глобальные настройки будут применяться для указанного языка."

  "All language-specific settings will be removed and the global settings will be applied for the specified language."
  "Будут удалены все языковые настройки и глобальные настройки будут применяться для указанного языка."

  "Append current find text to selection"
  "Добавить текущий найденный текст в выделение"

  "Balance Inward"
  "Сбалансировать внутри"

  "Balance Outward"
  "Сбалансировать снаружи"

  "Balance tag pair moving inward"
  "Сбалансировать пары тегов, перемещая внутрь"

  "Balance tag pair moving outward"
  "Сбалансировать пары тегов, перемещая наружу"

  "Bold"
  "Жирный"

  "Bubble Down"
  "Опустить вниз"

  "Bubble Up"
  "Поднять вверх"

  "Bubble lines down one line"
  "Опустить на одну строку вниз"

  "Bubble lines up one line"
  "Поднять на одну строку вверх"

  "Change Working Directory"
  "Сменить рабочий каталог"

  "Change working directory"
  "Сменить рабочий каталог"

  "Check for update"
  "Проверить обновления"

  "Checkbox"
  "Чекбокс"

  "Classic Mac"
  "Классический Mac"

  "Clear All"
  "Очистить все"

  "Close All"
  "Закрыть все"

  "Close All Folds"
  "Закрыть все складки"

  "Close Current"
  "Закрыть текущую"

  "Close Current Fold"
  "Закрыть текущую складку"

  "Close Selected Folds"
  "Закрыть выбранные складки"

  "Close all folds"
  "Закрыть все складки"

  "Close all tabs"
  "Закрыть все вкладки"

  "Close current session"
  "Закрыть текущий сеанс"

  "Close current tab"
  "Закрыть текущую вкладку"

  "Close fold at current line - all levels"
  "Закрыть складку на текущей строке - все уровни"

  "Close fold at current line - one level"
  "Закрыть складку на текущей строке - один уровень"

  "Close selected folds - all levels"
  "Закрыть выбранные складки - все уровни"

  "Close selected folds - one level"
  "Закрыть выбранные складки - один уровень"

  "Code"
  "Код"

  "Command"
  "Команда"

  "Command Result"
  "Результат команды"

  "Convert case to lower"
  "Преобразовать в нижний регистр"

  "Convert case to title"
  "Преобразовать в титульный регистр"

  "Convert case to upper"
  "Преобразовать в верхний регистр"

  "Copy text"
  "Копировать текст"

  "Create Fold From Selection"
  "Создать складку из выделения"

  "Create at Current Line"
  "Создать в текущей строке"

  "Create fold from selection"
  "Создать складку из выделения"

  "Create marker at current line"
  "Создать маркер в текущей строке"

  "Create new plugin"
  "Создать новый плагин"

  "Current Bounded Text"
  "Текущий ограниченный текст"

  "Current Paragraph"
  "Текущий параграф"

  "Current Sentence"
  "Текущее предложение"

  "Cut"
  "Вырезать"

  "Cut text"
  "Вырезать текст"

  "Decrement by 0.1"
  "Уменьшить на 0.1"

  "Decrement by 1"
  "Уменьшить на 1"

  "Decrement by 10"
  "Уменьшить на 10"

  "Decrement number by 0.1"
  "Уменьшить число на 0.1"

  "Decrement number by 1"
  "Уменьшить число на 1"

  "Decrement number by 10"
  "Уменьшить число на 10"

  "Delete All Folds"
  "Удалить все складки"

  "Delete Current Fold"
  "Удалить текущую складку"

  "Delete Selected Folds"
  "Удалить выбранные складки"

  "Delete Session"
  "Удалить сеанс"

  "Delete User"
  "Удалить Пользователя"

  "Delete all folds"
  "Удалить все складки"

  "Delete all selected folds"
  "Удалить все выбранные складки"

  "Delete current file"
  "Удалить текущий файл"

  "Delete fold at current line"
  "Удалить складки на текущей строке"

  "Delete language preferences?"
  "Удалить настройки языка?"

  "Delete session"
  "Удалить сессию"

  "Delete session language preferences?"
  "Удалить языковые настройки сессии?"

  "Delete template"
  "Удалить шаблон"

  "Disable Vim mode"
  "Отключить режим Vim"

  "Disable code folding"
  "Отключить сворачивание кода"

  "Disable two-pane scrolling Synchronization"
  "Отключить синхронизацию прокрутки двух панелей"

  "Display Text Info"
  "Отображать информацию о тексте"

  "Display text information"
  "Отображать информацию о тексте"

  "Duplicate current file"
  "Дублировать текущий файл"

  "Edit Custom Abbreviations"
  "Редактировать настройки тегов"

  "Edit Language"
  "Редактировать настройки языка"

  "Edit Session"
  "Редактировать настройки сессии"

  "Edit User"
  "Редактировать настройки пользователя"

  "Edit custom Emmet abbreviations"
  "Редактировать настройки тегов Emmet"

  "Edit language snippets"
  "Редактировать фрагменты кода"

  "Edit session current language preferences"
  "Редактировать текущие языковые настройки сессии"

  "Edit session global preferences"
  "Редактировать глобальные настройки сессии"

  "Edit template"
  "Редактировать шаблон"

  "Edit user current language preferences"
  "Редактировать текущие настройки языка пользователя"

  "Edit user global preferences"
  "Редактировать глобальные настройки пользователя"

  "Edit user snippets"
  "Редактировать фрагменты кода пользователя"

  "Enable Code Folding"
  "Включить сворачивание кода"

  "Enable Synchronized Scrolling"
  "Включить синхронизацию прокрутки"

  "Enable Vim mode"
  "Включить режим Vim"

  "Enable two-pane scrolling synchronization"
  "Включить синхронизацию прокрутки двух панелей"

  "Encode/Decode Image to Data:URL"
  "Кодировать/декодировать изображение в Data:URL"

  "Encode/Decode image to data:URL"
  "Кодировать/декодировать изображение в data:URL"

  "Enter selection mode"
  "В режим выделения"

  "Enumeration"
  "Перечисление"

  "Evaluate Math Expression"
  "Вычислить математическое выражение"

  "Evaluate the current math expression"
  "Вычислить текущее математическое выражение"

  "Expand Abbreviation"
  "Раскрыть тег"

  "Expand Emmet abbreviation"
  "Раскрыть тег Emmet"

  "Export As"
  "Експортировать как"

  "Export Custom Themes"
  "Експортировать настроенные темы"

  "Export complete"
  "Експортировать полностью"

  "Export current plugin"
  "Экспортировать текущий плагин"

  "Export file contents"
  "Експортировать содержимое файла"

  "Favorite file"
  "Избранный файл"

  "File Contents"
  "Содержимое файла"

  "Find In Files"
  "Найти в файлах"

  "Find Matching Bracket"
  "Найти соответствующую скобку"

  "Find Next"
  "Найти следующее"

  "Find Next Bracket Mismatch"
  "Найти следующее несоответствие скобок"

  "Find Previous"
  "Найти предыдущее"

  "Find Previous Bracket Mismatch"
  "Найти предыдущее несоответствие скобок"

  "Find and Replace"
  "Найти и заменить"

  "Find in files"
  "Найти в файлах"

  "Find matching character pair"
  "Найти совпадающие пары символов"

  "Find next mismatching bracket"
  "Найти следующую несовпадающую скобку"

  "Find previous mismatching bracket"
  "Найти предыдущую несовпадающую скобку"

  "Folding"
  "Сворачивание"

  "Format"
  "Форматировать"

  "Format Text"
  "Форматировать текст"

  "Format indentation for text"
  "Форматировать отступы для текста"

  "From Clipboard"
  "Из буфера обмена"

  "Global"
  "Глобальное"

  "Go to Matching Pair"
  "Перейти к совпадающей паре"

  "Go to matching tag pair"
  "Перейти к совпадающей паре тегов"

  "Go to next edit point"
  "Перейти к следующей точке редактирования"

  "Go to previous edit point"
  "Перейти к предыдущей точке редактирования"

  "Goto Last Tab"
  "На последнюю вкладку"

  "Goto Next Tab"
  "На следующую вкладку"

  "Goto Other Pane"
  "На другую панель"

  "Goto Previous Tab"
  "На предыдущую вкладку"

  "Goto last tab"
  "На последнюю вкладку"

  "Goto next difference"
  "На следующее различие"

  "Goto next tab"
  "На следующую вкладку"

  "Goto other pane"
  "На другую панель"

  "Goto previous difference"
  "На предыдущее различие"

  "Goto previous tab"
  "На предыдущую вкладку"

  "Header"
  "Заголовок"

  "Help"
  "Помощь"

  "Hide All Tabs"
  "Скрыть все вкладки"

  "Hide Current Tab"
  "Скрыть текущую вкладку"

  "Hide Line Numbers"
  "Скрыть номера строк"

  "Hide Marker Map"
  "Скрыть карту маркеров"

  "Hide Meta Characters"
  "Скрыть метасимволы"

  "Hide Sidebar"
  "Скрыть боковую панель"

  "Hide Status Bar"
  "Скрыть строку состояния"

  "Hide Tab Bar"
  "Скрыть панель вкладок"

  "Hide Tcl Console"
  "Скрыть консоль Tcl"

  "Hide Tcl console"
  "Скрыть консоль Tcl"

  "Hide line numbers"
  "Скрыть номера строк"

  "Hide marker map"
  "Скрыть карту маркеров"

  "Hide meta characters"
  "Скрыть метасимволы"

  "Hide sidebar"
  "Скрыть боковую панель"

  "Hide status bar"
  "Скрыть строку состояния"

  "Hide tab bar"
  "Скрыть панель вкладок"

  "Highlight"
  "Подсветить"

  "Image"
  "Изображение"

  "Import plugin bundle"
  "Импортировать плагины"

  "Increment by 0.1"
  "Увеличить на 0.1"

  "Increment by 1"
  "Увеличить на 1"

  "Increment by 10"
  "Увеличить на 10"

  "Increment number by 0.1"
  "Увеличить число на 0.1"

  "Increment number by 1"
  "Увеличить число на 1"

  "Increment number by 10"
  "Увеличить число на 10"

  "Indent"
  "Отступ"

  "Indent Off"
  "Отключить отступ"

  "Indent selected text"
  "Отступ для выделенного текста"

  "Indentation"
  "Отступ"

  "Insert bold formatting"
  "Вставить жирный текст"

  "Insert checklist formatting"
  "Вставить список"

  "Insert code formatting"
  "Вставить форматированный код"

  "Insert command result after current line"
  "Вставить результат команды после текущей строки"

  "Insert enumeration"
  "Вставить перечисление"

  "Insert file contents after current line"
  "Вставить содержимое файла после текущей строки"

  "Insert from clipboard"
  "Вставить из буфера обмена"

  "Insert header style"
  "Вставить заголовок"

  "Insert highlight formatting"
  "Вставить подсветку"

  "Insert image formatting"
  "Вставить изображение"

  "Insert italics formatting"
  "Вставить курсив"

  "Insert line above current line"
  "Вставить строку над текущей строкой"

  "Insert line below current line"
  "Вставить строку под текущей строкой"

  "Insert link formatting"
  "Вставить ссылку"

  "Insert ordered list formatting"
  "Вставить упорядоченный список"

  "Insert snippet"
  "Вставить фрагмент кода"

  "Insert strikethrough formatting"
  "Вставить зачеркнутый текст"

  "Insert subscript formatting"
  "Вставить подстрочные знаки"

  "Insert superscript formatting"
  "Вставить надстрочные знаки"

  "Insert underline formatting"
  "Вставить подчеркнутый текст"

  "Insert unordered list formatting"
  "Вставить неупорядоченный список"

  "Install plugin"
  "Установить плагин"

  "Italics"
  "Курсив"

  "Join Lines"
  "Объединить строки"

  "Join lines"
  "Объединить строки"

  "Jump Backward"
  "Перейти назад"

  "Jump Forward"
  "Перейти вперед"

  "Jump To Line"
  "Перейти к строке"

  "Jump backward"
  "Перейти назад"

  "Jump forward"
  "Перейти вперед"

  "Jump to Next Fold Mark"
  "Перейти к следующей складке"

  "Jump to Previous Fold Mark"
  "Перейти к предыдущей складке"

  "Jump to line"
  "Перейти к строке"

  "Jump to the next fold indicator"
  "Перейти к следующему индикатору складки"

  "Jump to the previous fold indicator"
  "Перейти к предыдущему индикатору складки"

  "Line Above Current"
  "Строка над текущей"

  "Line Below Current"
  "Строка под текущей"

  "Line Ending"
  "Окончание строки"

  "Line Number"
  "Номер строки"

  "Line Numbering"
  "Нумерация строк"

  "Line Wrapping"
  "Сворачивание строк"

  "Link"
  "Ссылка"

  "Lock"
  "Блокировать"

  "Lock file"
  "Блокировать файл"

  "Lower Case"
  "Нижний регистр"

  "Markers"
  "Маркеры"

  "Menu"
  "Меню"

  "Merge Lines"
  "Совместить строки"

  "Merge Panes"
  "Совместить панели"

  "Merge panes"
  "Совместить панели"

  "Move Cursors Down"
  "Переместить курсоры вниз"

  "Move Cursors Left"
  "Переместить курсоры влево"

  "Move Cursors Right"
  "Переместить курсоры вправо"

  "Move Cursors Up"
  "Переместить курсоры вверх"

  "Move cursor to bottom of screen"
  "Переместить курсор в низ экрана"

  "Move cursor to end of current line"
  "Переместить курсор в конец текущей строки"

  "Move cursor to first line"
  "Переместить курсор в первую строку"

  "Move cursor to last line"
  "Переместить курсор в последнюю строку"

  "Move cursor to middle of screen"
  "Переместить курсор в середину экрана"

  "Move cursor to next page"
  "Переместить курсор на следующую страницу"

  "Move cursor to next word"
  "Переместить курсор на следующее слово"

  "Move cursor to previous page"
  "Переместить курсор на предыдущую страницу"

  "Move cursor to previous word"
  "Переместить курсор на предыдущее слово"

  "Move cursor to start of current line"
  "Переместить курсор в начало текущей строки"

  "Move cursor to top of screen"
  "Переместить курсор в верх экрана"

  "Move multicursors down one line"
  "Переместить мультикурсоры на одну строку вниз"

  "Move multicursors left one line"
  "Переместить мультикурсоры на одну строку влево"

  "Move multicursors right one line"
  "Переместить мультикурсоры на одну строку вправо"

  "Move multicursors up one line"
  "Переместить мультикурсоры на одну строку вверх"

  "Move to First Line"
  "Перейти на первую строку"

  "Move to Last Line"
  "Перейти на последнюю строку"

  "Move to Line End"
  "Перейти на конец строки"

  "Move to Line Start"
  "Перейти на начало строки"

  "Move to Next Page"
  "Перейти на следующую страницу"

  "Move to Next Word"
  "Перейти на следующее слово"

  "Move to Previous Page"
  "Перейти на предыдущую страницу"

  "Move to Previous Word"
  "Перейти на предыдущее слово"

  "Move to Screen Bottom"
  "Перейти в низ экрана"

  "Move to Screen Middle"
  "Перейти в середину экрана"

  "Move to Screen Top"
  "Перейти в верх экрана"

  "Move to other pane"
  "Перейти на другую панель"

  "New From Template"
  "Создать из шаблона"

  "New Window"
  "Новое окно"

  "New file"
  "Новый файл"

  "New file from template"
  "Новый файл из шаблона"

  "New window"
  "Новое окно"

  "Next Difference"
  "Следующее различие"

  "Next Edit Point"
  "Следующая точка редактирования"

  "One Level"
  "Один уровень"

  "Open All Folds"
  "Открыть все складки"

  "Open Current Fold"
  "Открыть текущую складку"

  "Open Directory"
  "Открыть каталог"

  "Open Favorite"
  "Открыть избранное"

  "Open File"
  "Открыть файл"

  "Open Recent"
  "Открыть недавние"

  "Open Remote"
  "Открыть удаленные"

  "Open Selected Folds"
  "Открыть выделенные складки"

  "Open all folds"
  "Открыть все складки"

  "Open directory"
  "Открыть каталог"

  "Open file"
  "Открыть файл"

  "Open fold at current line - all levels"
  "Открыть складку в текущей строке - все уровни"

  "Open fold at current line - one level"
  "Открыть складку в текущей строке - один уровень"

  "Open folds to show cursor"
  "Открыть складки, чтобы показать курсор"

  "Open remote file or directory"
  "Открыть файл или каталог как сетевой"

  "Open selected folds - all levels"
  "Открыть выбранные складки - все уровни"

  "Open selected folds - one level"
  "Открыть выбранные складки - один уровень"

  "Ordered Bullet"
  "Упорядоченный список"

  "Panes"
  "Панели"

  "Paste"
  "Вставить"

  "Paste and Format"
  "Вставить и форматировать"

  "Paste and format text from clipboard"
  "Вставить и форматировать текст из буфера обмена"

  "Paste text from clipboard"
  "Вставить текст из буфера обмена"

  "Plugin Developer Guide"
  "Руководство разработчика плагинов"

  "Previous Difference"
  "Предыдущее различие"

  "Previous Edit Point"
  "Предыдущая точка редактирования"

  "Profiling Report Sorted By"
  "Отчет профилирования, сортированный по"

  "Profiling started"
  "Профилирование от"

  "Profiling stopped"
  "Профилирование по"

  "Quit"
  "Выход"

  "Quit application"
  "Выход из приложения"

  "Recent Directories"
  "Недавние каталоги"

  "Recent Files"
  "Недавние файлы"

  "Redo"
  "Вернуть"

  "Reflect CSS Value"
  "Отображать значение CSS"

  "Reflect current CSS value"
  "Отображать текущее значение CSS"

  "Relative"
  "Относительная"

  "Relative line numbering"
  "Относительная нумерация строк"

  "Reload"
  "Перезагрузить"

  "Reload all plugins"
  "Перезагрузить все плагины"

  "Reload snippets"
  "Перезагрузить фрагменты кода"

  "Reload template information"
  "Перезагрузить информацию шаблона"

  "Remove All From Current Buffer"
  "Удалить все из текущего буфера"

  "Remove All Markers"
  "Удалить все маркеры"

  "Remove Formatting"
  "Удалить форматирование"

  "Remove From Current Line"
  "Удалить из текущей строки"

  "Remove Tag"
  "Удалить тег"

  "Remove all markers"
  "Удалить все маркеры"

  "Remove all markers from current buffer"
  "Удалить все маркеры из текущего буфера"

  "Remove formatting from selected text"
  "Удалить форматирование в выделенном тексте"

  "Remove marker from current line"
  "Удалить маркер из текущей строки"

  "Remove tag"
  "Удалить тег"

  "Rename current file"
  "Переименовать текущий файл"

  "Reopen File"
  "Переоткрыть файл"

  "Reopen current file"
  "Переоткрыть текущий файл"

  "Replace Line With Script"
  "Заменить строку скриптом"

  "Replace line with script"
  "Заменить строку скриптом"

  "Restart"
  "Перезапуск"

  "Run theme editor"
  "Вызов редактора тем"

  "Save All"
  "Сохранить все"

  "Save As Remote"
  "Сохранить как сетевой"

  "Save As Template"
  "Сохранить как шаблон"

  "Save Current"
  "Сохранить текущий"

  "Save Selection As"
  "Сохранить выделенное как"

  "Save all files"
  "Сохранить все файлы"

  "Save current session"
  "Сохранить текущую сессию"

  "Save file"
  "Сохранить файл"

  "Save file as"
  "Сохранить файл как"

  "Save file as remote file"
  "Сохранить файл как сетевой"

  "Save file as template"
  "Сохранить файл как шаблон"

  "Save selected lines"
  "Сохранить выделенные строки"

  "Save sessions as"
  "Сохранить сессии как"

  "Search References"
  "Поиск справочной информации"

  "Search language reference documentation"
  "Поиск справочной документации по языку"

  "Search reference documentation"
  "Поиск справочной документации"

  "Select"
  "Выделить"

  "Select All Matches"
  "Выделить все совпадения"

  "Select Current Match"
  "Выделить текущее совпадение"

  "Select Mode"
  "Режим выделения"

  "Select Next Item"
  "Выделить следующее"

  "Select Previous Item"
  "Выделить предыдущее"

  "Select all find matches"
  "Выделить все найденные совпадения"

  "Select all text"
  "Выделить весь текст"

  "Select current bracketed text, strings or comment block"
  "Выделить текущий текст в скобках, строки или блок комментариев"

  "Select current line"
  "Выделить текущую строку"

  "Select current paragraph"
  "Выделить текущий параграф"

  "Select current sentence"
  "Выделить текущее предложение"

  "Select current word"
  "Выделить текущее слово"

  "Select next tag item"
  "Выделить следующий тег"

  "Select previous tag item"
  "Выделить предыдущий тег"

  "Send Bug Report"
  "Отправить отчет об ошибке"

  "Send Feedback"
  "Отправить отзыв"

  "Send bug report"
  "Отправить отчет об ошибке"

  "Send feedback"
  "Отправить отзыв"

  "Set Syntax"
  "Установить синтаксис"

  "Set Theme"
  "Установить тему"

  "Set current file line ending to CR for Classic Mac"
  "Установить окончание строк файла в CR для классического Mac"

  "Set current file line ending to CRLF for Windows"
  "Установить окончание строк файла в CRLF для Windows"

  "Set current file line ending to LF for Unix"
  "Установить окончание строк файла в LF для Unix"

  "Set indent mode to"
  "Установить режим отступа"

  "Show All Tabs"
  "Показать все вкладки"

  "Show Cursor"
  "Показать курсор"

  "Show Diagnostic Logfile"
  "Показать журнал диагностики"

  "Show File Difference"
  "Показать различия файла"

  "Show Installed"
  "Показать установленные"

  "Show Last Profiling Report"
  "Показать последний отчет профилирования"

  "Show Line Numbers"
  "Показать номера строк"

  "Show Marker Map"
  "Показать карту маркеров"

  "Show Meta Characters"
  "Показать метасимволы"

  "Show Selected Line Change"
  "Показать изменения выбранных строк"

  "Show Sidebar"
  "Показать боковую панель"

  "Show Status Bar"
  "Показать строку состояния"

  "Show Tab Bar"
  "Показать панель вкладок"

  "Show Tcl Console"
  "Показать консоль Tcl"

  "Show Tcl console"
  "Показать консоль Tcl"

  "Show diagnostic logfile"
  "Показать журнал диагностики"

  "Show file difference"
  "Показать файл различий"

  "Show installed plugins"
  "Показать установленные плагины"

  "Show last profiling report"
  "Показать последний отчет профилирования"

  "Show meta characters"
  "Показать метасимволы"

  "Show plugin developer guide"
  "Показать руководство разработчика плагинов"

  "Show plugin source directory in sidebar"
  "Показать каталог исходников плагинов в боковой панели"

  "Show plugins directory in sidebar"
  "Показать каталог плагинов в боковой панели"

  "Show selected line change"
  "Показать изменения выбранных строк"

  "Sort Tabs"
  "Сортировать вкладки"

  "Sort tabs"
  "Сортировать вкладки"

  "Split/Join Tag"
  "Разбить/Объединить тег"

  "Split/Join tag"
  "Разбить/Объединить тег"

  "Start Profiling"
  "Начать профилирование"

  "Start profiling"
  "Начать профилирование"

  "Stop Profiling"
  "Остановить профилирование"

  "Stop profiling"
  "Остановить профилирование"

  "Strikethrough"
  "Зачёркнутый"

  "Subscript"
  "Подстрочный"

  "Superscript"
  "Надстрочный"

  "Switch To"
  "Переключить на"

  "Switch to session"
  "Переключить на сессию"

  "Tabs"
  "Вкладки"

  "Tips & Tricks"
  "Советы и подсказки"

  "Title Case"
  "Титульный регистр"

  "Toggle Case"
  "Переключить регистр"

  "Toggle Comment"
  "Переключить комментирование"

  "Toggle bird's eye view mode"
  "Переключить режим просмотра с птичьего полета"

  "Toggle case of current character"
  "Переключить регистр текущего символа"

  "Toggle comment"
  "Переключить комментарий"

  "Toggle split view mode"
  "Переключить режим раздельного просмотра"

  "Toggle tag/rule comment"
  "Переключить комментарий тег/правило"

  "Transform"
  "Преобразование"

  "Unable to delete file"
  "Невозможно удалить файл"

  "Unable to write export file"
  "Невозможно экспортировать файл"

  "Underline"
  "Подчеркивание"

  "Undo"
  "Отменить"

  "Unfavorite file"
  "Удалить файл из списка избранных"

  "Unindent"
  "Убрать отступ"

  "Unindent selected text"
  "Убрать отступ выделенного текста"

  "Uninstall plugin"
  "Отменить установку плагина"

  "Unlock"
  "Разблокировать"

  "Unlock file"
  "Разблокировать файл"

  "Unordered Bullet"
  "Неупорядоченный список"

  "Update Image Size"
  "Обновить размер изображения"

  "Update img tag width and height attributes"
  "Обновить атрибуты ширины и высоты изображения"

  "Upper Case"
  "Верхний регистр"

  "User Guide"
  "Руководство пользователя"

  "View Emmet Reference Guide"
  "Руководство по Emmet"

  "View the Emmet reference guide"
  "Руководство по Emmet"

  "View tips & tricks articles"
  "Просмотр подсказок и советов"

  "View user guide"
  "Просмотр руководства пользователя"

  "Vim Mode"
  "Режим Vim"

  "Wrap With Abbreviation"
  "Свернуть с тегом"

  "Wrap tag with Emmet abbreviation"
  "Свернуть тег с Emmet"

  "formatting"
  "форматирование"

}

# plugins.tcl
msgcat::mcmset ru {

  "Always grant from developer"
  "Всегда доверять разработчику"

  "ERROR"
  "ОШИБКА"

  "ERROR:  Plugin name already exists"
  "ОШИБКА: Плагин с таким именем уже существует"

  "ERROR:  Plugin name is not valid (only alphanumeric and underscores are allowed)"
  "ОШИБКА: Имя плагина некорректно (допустимы только буквы, цифры и подчеркивание)"

  "ERROR:  Unable to create plugin directory"
  "ОШИБКА: Невозможно создать каталог плагина"

  "ERROR:  Unable to write plugin files"
  "ОШИБКА: Невозможно сохранить файлы плагина"

  "Editing"
  "Редактирование"

  "Enter plugin name"
  "Введите имя плагина"

  "Grant"
  "Разрешить"

  "Grant permission?"
  "Разрешить?"

  "Plugin Errors"
  "Ошибки плагина"

  "Plugin Trust Requested"
  "Требуется разрешение для плагина"

  "Plugin import completed successfully"
  "Импорт плагина успешно завершен"

  "Plugin installed"
  "Плагин установлен"

  "Plugin requires permission to view or modify your system."
  "Требуется разрешение плагину на просмотр или изменение системы."

  "Plugin uninstalled"
  "Установка плагина отменена"

  "Plugins successfully reloaded"
  "Плагины успешно перезагружены"

  "Reject"
  "Отклонить"

  "Syntax errors found in selected plugins"
  "В выбранных плагинах обнаружены ошибки"

  "Unable to unzip plugin"
  "Не удалось распаковать плагин"

  "Unable to zip plugin"
  "Не удалось упаковать плагин"

  "Version Control"
  "Управление версиями"

}

# plugmgr.tcl
msgcat::mcmset ru {

  "Available"
  "Доступно"

  "Export Plugin"
  "Экспортировать плагин"

  "Installed"
  "Установлен"

  "Markdown"
  "формат Markdown"

  "Plugin Manager"
  "Менеджер плагинов"

  "Plugin export completed successfully"
  "Экспорт плагина успешно завершен"

  "Release Notes"
  "Примечания к выпуску"

}

# pref_ui.tcl
msgcat::mcmset ru {

  "Abbreviation Aliases"
  "Псевдонимы тегов"

  "Add"
  "Добавить"

  "Add Language Reference"
  "Добавить руководство по языку"

  "Additional space between lines"
  "Дополнительное пространство между строками"

  "Addons"
  "Дополнения"

  "Advanced"
  "Расширения"

  "Alias"
  "Псевдоним"

  "Allow scrolling in tab bar"
  "Позволить прокрутку в панели вкладок"

  "Angled bracket"
  "Угловая скобка"

  "Appearance"
  "Внешний вид"

  "Append characters to search string if entered within"
  "Добавить символы в строку поиска, если вводятся внутри"

  "Auto-match Characters"
  "Символы автосовпадения"

  "Automatically check for updates on start"
  "Автоматически проверять наличие обновлений при запуске"

  "Automatically highlight matching bracket"
  "Автоматически выделять соответствующую скобку"

  "Automatically highlight mismatching brackets"
  "Автоматически выделять несоответствующую скобку"

  "Automatically insert vendor prefixes"
  "Автоматически вставлять префиксы поставщиков"

  "Automatically load last session on start"
  "Автоматически загружать последнюю сессию при запуске"

  "Automatically set the current working directory to the current tabs directory"
  "Автоматически устанавливать рабочий каталог в каталог текущей вкладки"

  "Backtick"
  "Обратный апостроф"

  "Base Directory"
  "Основной каталог"

  "Behaviors"
  "Поведение"

  "Bird's Eye View Font Size"
  "Размер шрифта с высоты птичьего полета"

  "Bird's Eye View Width"
  "Ширина панели с высоты птичьего полета"

  "Buffer"
  "Буфер"

  "Choose Color"
  "Выбрать цвет"

  "Choose Logfile Directory"
  "Выбрать каталог для журнала"

  "Clear"
  "Очистить"

  "Clipboard"
  "Буфер обмена"

  "Clipboard History"
  "История буфера обмена"

  "Clipboard history depth"
  "Глубина истории буфера обмена"

  "Close find panels when editing buffer gets focus"
  "Закрыть панели поиска, когда редактируемый буфер получит фокус"

  "Closing"
  "Закрытие"

  "Color value case"
  "Регистр значения цвета"

  "Command launcher entry"
  "Ввод команды запуска"

  "Command launcher preview"
  "Предосмотр команды запуска"

  "Convert to lowercase"
  "Преобразовать в нижний регистр"

  "Convert to uppercase"
  "Преобразовать в верхний регистр"

  "Creator"
  "Автор"

  "Curly bracket"
  "Фигурная скобка"

  "Current"
  "Текущий"

  "Current Directory"
  "Текущий каталог"

  "Current File Pathname"
  "Путь к текущему файлу"

  "Current Filename"
  "Путь к текущему файлу"

  "Current Line Column"
  "Позиция в текущей строке"

  "Current Line Number"
  "Номер текущей строки"

  "Current editing buffer directory"
  "Каталог редактируемого файла"

  "Current working directory"
  "Текущий рабочий каталог"

  "Date"
  "Дата"

  "Default Find in Files search method"
  "Метод поиска в файлах по умолчанию"

  "Default Find search method"
  "Метод поиска по умолчанию"

  "Default Markdown Export Extension"
  "Расширение по умолчанию для формата Markdown"

  "Default Plugin Export Directory"
  "Каталог экспорта плагинов по умолчанию "

  "Default Theme Export Directory"
  "Каталог экспорта тем по умолчанию"

  "Default sidebar width on startup"
  "Ширина боковой панели при запуске"

  "Default theme"
  "Тема по умолчанию"

  "Default unit for floating point values"
  "Единица вещественных чисел по умолчанию"

  "Default unit for integer values"
  "Единица целых чисел по умолчанию"

  "Delete snippet"
  "Удалить фрагмент кода"

  "Delete user bindings and use default?"
  "Удалить настройки пользователя и использовать стандартные?"

  "Development"
  "Разработка"

  "Displayed Information"
  "Отображаемые сведения"

  "Double-quote"
  "Двойные кавычки"

  "Editor"
  "Редактор"

  "Enable Vim Mode"
  "Включить режим Vim"

  "Enable auto-indentation"
  "Включить автоотступ"

  "Enable development mode"
  "Включить режим разработки"

  "Enable fuzzy search"
  "Включить нечёткий поиск"

  "Enable relative line numbering"
  "Включить относительную нумерацию строк"

  "Enabled"
  "Включен"

  "End-of-line character when saving"
  "Символы конца строки при сохранении"

  "Exit the application after the last tab is closed"
  "Выйти из приложения после закрытия последней вкладки"

  "Export Settings"
  "Настройки экспорта"

  "Extensions"
  "Расширения"

  "Fonts"
  "Шрифты"

  "Format snippet indentation after insert"
  "Делать отступ фрагмента после вставки"

  "General"
  "Общие"

  "Get More Themes"
  "Получить другие темы"

  "Hide Patterns"
  "Шаблоны скрытия файлов"

  "Hide binary files"
  "Не показывать двоичные файлы"

  "Hiding"
  "Скрытие файлов"

  "Host"
  "Хост"

  "Imported"
  "Импортирован"

  "Indentation spaces"
  "Число пробелов отступа"

  "Info Panel"
  "Панель информации"

  "Insert unsorted files at the top of a manually sorted directory"
  "Вставить несортированные файлы наверх каталога, сортированного вручную"

  "Insertion cursor width"
  "Ширина курсора вставки"

  "Keep information panel visible when sidebar doesn't have focus"
  "Оставить панель информации видимой, когда курсор не в боковой панели"

  "Keyword"
  "Ключевое слово"

  "Languages"
  "Языки"

  "Last"
  "Последний"

  "Last accessed"
  "Последний доступ"

  "Line Wrapping Default"
  "Линия сворачивания"

  "Line count to find Vim modeline information"
  "Число строк для режима modeline в Vim"

  "Line number alignment"
  "Выравнивание номеров строк"

  "Logfile Directory"
  "Каталог файла журнала"

  "Manage Themes"
  "Управление темами"

  "Manage theme visibility"
  "Управление видимостью тем"

  "Maximum undo history (set to 0 for unlimited)"
  "Максимальное число отмен (0 - без ограничений)"

  "Menu Item"
  "Пункт меню"

  "Menu bindings"
  "Горячие клавиши меню"

  "Mounts"
  "Монтирования"

  "Node Aliases"
  "Псевдонимы узлов"

  "Profiler Options"
  "Параметры профилировщика"

  "Prompt user to save preference changes in global or named session"
  "Запрос на сохранение изменений настроек в глобальной или данной сессии"

  "Properties"
  "Свойства"

  "Reading time words per minute"
  "Время чтения (слов в минуту)"

  "Recently opened history depth"
  "Длина списка недавно открытых файлов"

  "Remember last position of command launcher"
  "Запомнить последнюю позицию запуска команды"

  "Remote Base Directory"
  "Основной сетевой каталог"

  "Remove root directory after last sub-file is closed"
  "Убрать каталог после закрытия его последнего файла"

  "Remove trailing whitespace on save"
  "Удалить хвостовые пробелы при сохранении"

  "Report Options"
  "Параметры отчета"

  "Retain case"
  "Оставить регистр"

  "Return"
  "Вернуться"

  "Ruler column"
  "Столбец линейки"

  "Save changes to current session?"
  "Сохранить изменения в текущей сессии?"

  "Save changes to global preferences?"
  "Сохранить изменения глобальных настроек?"

  "Search Shortcuts"
  "Поиск назначений клавиш"

  "Search Snippets"
  "Поиск фрагментов кода"

  "Select Command Launcher Entry Font"
  "Выбрать шрифт ввода командной строки"

  "Select Command Launcher Preview Font"
  "Выбрать шрифт предосмотра командной строки"

  "Select Editor Font"
  "Выбрать шрифт редактора"

  "Select Settings Sharing Directory"
  "Выбрать общую директорию настроек"

  "Select a plugin"
  "Выбрать плагин"

  "Select a shortcut and hit the Return or Space key to edit the shortcut"
  "Выберите строку и нажмите Return или пробел для редактирования"

  "Select default browsing directory"
  "Выбрать директорию просмотра по умолчанию"

  "Selected Text"
  "Выделенный текст"

  "Session"
  "Сессия"

  "Set"
  "Задать"

  "Set Find in Files line context"
  "Контекст строки поиска в файлах"

  "Set default open/save browsing directory to"
  "Директория по умолчанию для открытия/сохранения"

  "Set find history depth"
  "Глубина истории поиска"

  "Set jump distance"
  "Расстояние перехода"

  "Sharing"
  "Общие"

  "Sharing Items"
  "Совместно используемые элементы"

  "Shortcut"
  "Клавиши"

  "Shortcuts"
  "Клавиши"

  "Show 'Find in Files' result in other pane"
  "Показать результат поиска в файлах в другой панели"

  "Show Move To Trash for local files/directories instead of Delete"
  "Перемещение в корзину локальных файлов/каталогов вместо Удаления"

  "Show Tcl console at startup"
  "Вызов консоли Tcl при запуске"

  "Show bird's eye view"
  "Показать просмотр с высоты птичьего полета"

  "Show diagnostic logfile at startup"
  "Показать журнал диагностики при запуске"

  "Show difference file in other pane than original"
  "Показать файл отличий в другой (не исходной) панели"

  "Show difference file version information"
  "Показать сведения о версии файла отличий"

  "Show folders at top"
  "Показать папки вверху"

  "Show hidden files"
  "Показать скрытые файлы"

  "Show language submenu"
  "Показать подменю языков"

  "Show menubar"
  "Показать меню"

  "Single-quote"
  "Одиночная кавычка"

  "Snippet Completion Characters"
  "Символы завершения фрагмента кода"

  "Snippet Text"
  "Текст фрагмента кода"

  "Sort tabs alphabetically on open"
  "Сортировать вкладки по алфавиту при открытии"

  "Sorting Column"
  "Столбец сортировки"

  "Space"
  "Пробел"

  "Spaces per tab"
  "Число пробелов в табуляции"

  "Square bracket"
  "Квадратная скобка"

  "Stable"
  "Стабильный"

  "Symbol between CSS property and value"
  "Символ между свойством CSS и значением"

  "Symbol placed at end of CSS property"
  "Символ в конце свойства CSS"

  "Syntax Coloring"
  "Подсветка синтаксиса"

  "Tab"
  "Табулостоп"

  "Tab Stop"
  "Табулостоп"

  "This operation cannot be reversed."
  "Эта операция необратима."

  "Time"
  "Время"

  "Unknown"
  "Неизвестно"

  "Update information panel whenever the sidebar selection changes"
  "Обновлять панель информации при смене выделенной строки боковой панели"

  "Update using release type"
  "Обновление согласно типу релиза"

  "Updates"
  "Обновления"

  "Use Default"
  "Использовать по умолчанию"

  "Use appropriate EOL character on system"
  "Использовать соответствующий системе символ EOL"

  "Use carriate return linefeed sequence"
  "Использовать возврат каретки и перевод строки"

  "Use current width"
  "Использовать текущую ширину"

  "Use directory"
  "Использовать директорию"

  "Use linefeed character"
  "Использовать символ перевода строки"

  "Use original EOL character from file"
  "Использовать символ EOL файла"

  "Use shortened colors"
  "Использовать сокращенные значения цветов"

  "Use single carriage return character"
  "Использовать символ возврата каретки"

  "Variable"
  "Переменная"

  "Variables"
  "Переменные"

  "Visible"
  "Видимый"

  "You have changed global preferences which will not be visible because you are currently within a named session."
  "Вы изменили глобальные настройки, которые не будут видны, потому что вы находитесь сейчас в данной сессии."

  "You have changed the current session's preferences which will not be applied globally."
  "Вы изменили настройки текущей сессии, которые не будут применяться глобально."

  "milliseconds"
  "миллисекунд"

  "pixels"
  "пикселей"

  "theme"
  "тема"

}

# remote.tcl
msgcat::mcmset ru {

  "Close Connection"
  "Закрыть соединение"

  "Connection does not exist"
  "Нет соединения"

  "Connection failed"
  "Сбой соединения."

  "Connection passed"
  "Соединение установлено"

  "Connections"
  "Соединения"

  "Create New Folder"
  "Создать новую папку"

  "Delete Connection"
  "Удалить соединение"

  "Delete Group"
  "Удалить группу"

  "Delete connection?"
  "Удалить соединение?"

  "Delete group?"
  "Удалить группу"

  "Edit Connection"
  "Редактировать соединение"

  "Enter Password"
  "Введите пароль"

  "Folder Name"
  "Название каталога"

  "Group"
  "Группа"

  "Group Name"
  "Название группы"

  "Group Name: "
  "Название группы: "

  "Image used in remote file selector for the history back button."
  "Изображение при выборе сетевых файлов для кнопки Назад в истории."

  "Image used in remote file selector for the history forward button."
  "Изображение при выборе сетевых файлов для кнопки Вперед в истории."

  "Image used in remote file selector to indicate a file."
  "Изображение при выборе сетевых файлов для указания файла."

  "Image used in remote file selector to indicate a folder."
  "Изображение при выборе сетевых файлов для указания каталога."

  "Image used in remote file selector to indicate that a connection is being opened."
  "Изображение при выборе сетевых файлов для указания, что соединение устанавливается."

  "Image used in remote file selector to indicate that a connection is opened."
  "Изображение при выборе сетевых файлов для указания, что соединение установлено."

  "New Connection"
  "Новое соединение"

  "New Folder"
  "Новый каталог"

  "New Group"
  "Новая группа"

  "Open Connection"
  "Открыть соединение"

  "Open Remote File"
  "Открыть сетевой файл"

  "Optional"
  "Опционально"

  "Password"
  "Пароль"

  "Password: "
  "Пароль: "

  "Port"
  "Порт"

  "Remote Directory"
  "Сетевой каталог"

  "Rename Group"
  "Переименовать группу"

  "Save File Remotely"
  "Сохранить файл в сети"

  "Server"
  "Сервер"

  "Test Connection"
  "Проверка соединения"

  "Type"
  "Тип"

  "Unable to connect to"
  "Невозможно соединиться с"

  "Unable to read remote directory contents."
  "Не удается прочитать удаленный каталог."

  "Username"
  "Логин"

  "server"
  "сервер"

}

# search.tcl
msgcat::mcmset ru {

  "No files found in specified directories"
  "В указанных каталогах файлы не найдены"

  "No search results found"
  "Поиск безуспешен"

  "Search wrapped to beginning of file"
  "Повторный поиск до начала файла"

  "Search wrapped to end of file"
  "Повторный поиск до конца файла"

  "substitutions done"
  "сделано замен"

}

# select.tcl (Go to Edit menu, select "Select Mode" and hit the '?' key to view strings.)
msgcat::mcmset ru {

  "Add Selection Matches"
  "Добавить совпадения"

  "All To"
  "Все в"

  "Anchor"
  "Якорь"

  "Angled Brackets"
  "Угловые скобки"

  "Backticks"
  "Обратные кавычки"

  "Block"
  "Блок"

  "Character"
  "Символ"

  "Child"
  "Потомок"

  "Clear Selection"
  "Снять выделение"

  "Comment"
  "Комментарий"

  "Curly Brackets"
  "Фигурные скобки"

  "Delete Selected Text"
  "Удалить выделенное"

  "Double Quotes"
  "Двойные кавычки"

  "Down"
  "Вниз"

  "Exit Selection Mode"
  "Выход из режима выделения"

  "Invert Selected Text"
  "Инвертировать выделение"

  "Keep Selection"
  "Сохранить выделение"

  "Left"
  "Влево"

  "Line To"
  "Строка до"

  "Modes"
  "Режимы"

  "Motions"
  "Перемещения"

  "Next Sibling"
  "Следующий потомок"

  "Paragraph"
  "Параграф"

  "Parent"
  "Родитель"

  "Previous"
  "Предыдущий"

  "Previous Sibling"
  "Предыдущий потомок"

  "Right"
  "Вправо"

  "Selection Mode Command Help"
  "Справка по командам режима выделения"

  "Sentence"
  "Предложение"

  "Shift Down"
  "Сдвиг вниз"

  "Shift Left"
  "Сдвиг влево"

  "Shift Right"
  "Сдвиг вправо"

  "Shift Up"
  "Сдвиг вверх"

  "Single Quotes"
  "Одинарные кавычки"

  "Square Brackets"
  "Квадратные скобки"

  "Swap Anchor"
  "Обменять якорь"

  "Toggle Help"
  "Переключить справку"

  "Toggle Quote Inclusion"
  "Переключить включение кавычек"

  "Type '?' for help.  Hit the ESCAPE key to exit selection mode"
  "Нажмите '?' для справки.  Нажмите ESCAPE для выхода из режима выделения"

  "Undo Last Change"
  "Отменить последнее изменение"

  "Up"
  "Вверх"

  "Word"
  "Слово"

  "matching instances"
  "совпадений"

}

# sessions.tcl
msgcat::mcmset ru {

  "Save session?"
  "Сохранить сессию?"

  "Session state will be lost if not saved"
  "Состояние сессии будет потеряно, если не сохранить"

}

# share.tcl
msgcat::mcmset ru {

  "Export Settings Data"
  "Экспорт настроек"

  "Favorites"
  "Избранное"

  "Remote Connections"
  "Сетевые соединения"

  "Settings to export"
  "Параметры экспорта"

  "Themes"
  "Темы"

}

# sidebar.tcl
msgcat::mcmset ru {

  "Add Parent Directory"
  "Добавить родительский каталог"

  "By Name"
  "По имени"

  "Close Directory Files"
  "Закрыть файлы каталога"

  "Copy Pathname"
  "Копировать путь"

  "Decreasing"
  "Уменьшение"

  "Delete directories?"
  "Удалить каталоги?"

  "Delete directory?"
  "Удалить каталог?"

  "Delete file?"
  "Удалить файл?"

  "Delete files?"
  "Удалить файлы"

  "Directory Name:"
  "Имя каталога:"

  "Disconnect From Server"
  "Отсоединиться от сервера"

  "Folder Name:"
  "Имя каталога:"

  "Hide"
  "Скрыть"

  "Hide Directory Files"
  "Скрыть файлы каталога"

  "Image displayed in sidebar to indicate a directory that is collapsed"
  "Изображение в боковой панели для свернутого каталога"

  "Image displayed in sidebar to indicate a directory that is showing its contents"
  "Изображение в боковой панели для развернутого каталога"

  "Image displayed in sidebar to indicate a file"
  "Изображение в боковой панели для файла"

  "Image displayed in sidebar to indicate a selected directory that is collapsed"
  "Изображение в боковой панели для выбранного свернутого каталога"

  "Image displayed in sidebar to indicate a selected directory that is expanded"
  "Изображение в боковой панели для выбранного развернутого каталога"

  "Image displayed in sidebar to indicate that a file is currently opened but hidden"
  "Изображение в боковой панели для открытия скрытого файла"

  "Image displayed in sidebar to indicate that a file is currently opened in an editing buffer."
  "Изображение в боковой панели для открытого в редакторе файла."

  "Increasing"
  "Увеличение"

  "Make Current Working Directory"
  "Создать текущий рабочий каталог"

  "Manually"
  "Вручную"

  "New Directory"
  "Новый каталог"

  "New File From Template"
  "Новый файл из шаблона"

  "Open Directory Files"
  "Открыть файлы каталога"

  "Refresh Directory Files"
  "Обновить файлы каталога"

  "Remove Parent from Sidebar"
  "Убрать родителя из боковой панели"

  "Remove from Sidebar"
  "Убрать из боковой панели"

  "Show"
  "Показать"

  "Show Difference"
  "Показать различия"

  "Show Directory Files"
  "Показать файлы каталога"

  "Show Info"
  "Показать сведения"

  "Sort"
  "Сортировать"

  "Unable to duplicate file"
  "Не удается дублировать файл"

}

# snippets.tcl
msgcat::mcmset ru {

  "Snippet: *"
  "Фрагмент кода: *"

}

# startup.tcl
msgcat::mcmset ru {

  "Change Directory"
  "Сменить каталог"

  "Copies settings data from an existing directory to your home directory."
  "Копирует настройки из существующего каталога в ваш домашний каталог."

  "Copy settings from directory"
  "Копировать настройки из каталога"

  "Create settings locally"
  "Создать настройки локально"

  "Creates new settings information and places it in your home directory"
  "Создает новые настройки и помещает их в ваш домашний каталог"

  "Finish"
  "Конец"

  "If you need would like to change your sharing settings, you can do so within Preferences under the General/Sharing tab."
  "Если вы хотите изменить общие настройки, вы можете сделать это в Настройках на вкладке Общие."

  "Items that are selected will be copied to your local home directory. Items that are not selected will be created in your home directory."
  "Выбранные элементы будут скопированы в ваш локальный домашний каталог. Невыбранные элементы будут созданы в вашем домашнем каталоге."

  "Items that are selected will be shared with other computers. Items that are not selected will be stored locally and will not be shared."
  "Выбранные элементы будут доступны с других компьютеров. Невыбранные элементы будут храниться локально и не будут расшарены."

  "Select Settings Directory"
  "Выбрать каталог настроек"

  "Settings"
  "Настройки"

  "Settings Options"
  "Опции настроек"

  "Setup Complete"
  "Установка завершена"

  "Share"
  "Совместный доступ"

  "Shares settings data from a new or existing directory (ex., iCloud Drive, Google Drive, Dropbox, etc.).  Any changes made to settings data will be available to other sharers."
  "Делает общими настройки из нового или существующего каталога (напр., iCloud Drive, Google Drive, Dropbox и т.д.). Любые изменения, внесенные в настройки, будут доступны другим пользователям."

  "Thanks for using TKE, the advanced programmer's editor.  Since this is a new installation of TKE, let's help you get things set up. \\n \\n Click 'Next' below to get things going."
  "Спасибо за использование TKE, редактора для продвинутых программистов.  Поскольку это первый запуск TKE, давайте его настроим. \\n \\n Кликните 'Далее' для продолжения."

  "Use shared settings"
  "Использовать настройки совместного доступа"

  "Welcome"
  "Добро пожаловать"

  "Welcome To"
  "Добро пожаловать в"

}

# syntax.tcl
msgcat::mcmset ru {

  "Syntax error in syntax file"
  "Ошибка в файле синтаксиса"

}

# templates.tcl
msgcat::mcmset ru {

  "Delete template?"
  "Удалить шаблон"

  "Template"
  "Шаблон"

  "Template Name"
  "Название шаблона"

  "deleted"
  "удален"

  "saved"
  "сохранен"

  "will be permanently deleted"
  "будет удален навсегда"

}

# theme.tcl
msgcat::mcmset ru {

  "Amount of border to display around command launcher in pixels"
  "Размер границы для отображения вокруг команды запуска в пикселях"

  "Background (trough) color used in a standard scrollbar."
  "Цвет фона стандратной линейки прокрутки."

  "Background (trough) color used in the sidebar scrollbar."
  "Цвет фона линейки прокрутки боковой панели."

  "Background (trough) color used in the text scrollbars."
  "Цвет фона линейки прокрутки текста."

  "Background color displayed in embedded language code."
  "Цвет фона вставленного блока программного кода."

  "Background color for all sidebar items that are not selected."
  "Цвет фона для всех невыбранных элементов боковой панели."

  "Background color for all sidebar items that are selected."
  "Цвет фона для всех выбранных элементов боковой панели."

  "Background color for markers in the line gutter and scrollbar"
  "Цвет фона для маркеров в линейках желоба и прокрутки"

  "Background color for matching search text"
  "Цвет фона для найденного текста"

  "Background color in difference viewer that shows added lines."
  "Цвет фона в окне просмотра различий для добавленных строк."

  "Background color in difference viewer that shows deleted lines."
  "Цвет фона в окне просмотра различий для удаленных строк."

  "Background color of insertion cursor and background marker colors."
  "Цвет фона курсора вставки и маркеров."

  "Background color of linemap area."
  "Цвет фона полосы номеров строк."

  "Background color of list items when not selected"
  "Цвет фона невыбранных элементов списка"

  "Background color of move bar."
  "Цвет фона полосы перемещения."

  "Background color of selection in command launcher"
  "Цвет фона выделения в команде запуска"

  "Background color of textual display in command launcher"
  "Цвет фона отображения текста в команде запуска"

  "Background color of the editing buffer."
  "Цвет фона текста редактора."

  "Background color to display when a button-like ttk widget is pressed."
  "Цвет фона отображения при нажатии виджетов типа ttk кнопок."

  "Background color to use for active information values to indicate they are clickable."
  "Цвет фона активных сообщений для указания, что они кликабельны."

  "Background color to use for displaying character information that requires the user's attention."
  "Цвет фона для отображения информации, требующей внимания пользователя."

  "Background color to use for selected text."
  "Цвет фона выделенного текста."

  "Background color to use for the file information panel."
  "Цвет фона информационной панели файлов."

  "Background color used for all other tabs that are not the current/active tab in the tabbar."
  "Цвет фона всех вкладок, которые не являются текущими/активными в панели вкладок."

  "Background color used for the current/active menu item."
  "Цвет фона текущего/активного пункта меню."

  "Background color used for the current/active tab in the tabbar."
  "Цвет фона текущей/активной вкладки в панели вкладок."

  "Background color used in highlighted text."
  "Цвет фона, используемый в выделенном тексте."

  "Background color used in menus."
  "Цвет фона меню."

  "Background color used in the tabbar area."
  "Цвет фона области панели вкладок."

  "Color of border around command launcher"
  "Цвет бордюра вокруг команды запуска"

  "Color of border drawn around active editing buffer."
  "Цвет бордюра вокруг текущего текста редактора."

  "Color of space between tabs."
  "Цвет области между вкладками."

  "Color of the spacer between the command launcher entry field and the result list"
  "Цвет области между полем ввода команды запуска и списком результатов"

  "Color of ttk entry widget text border when the entry has keyboard focus."
  "Цвет бордюра ttk текста, когда на нем стоит курсор ввода."

  "Color to use for highlighting closed folds in the line number gutter"
  "Цвет выделения закрытых складок в полосе номеров строк"

  "Color used to draw the line which separates the linemap from the text area."
  "Цвет разделительной линии между номерами строк и редактируемым текстом."

  "Color used to draw the warning width line in the editing buffer (as well as the line separating the gutter from the editing buffer)."
  "Цвет строки предупреждений в тексте редактора (и линии, отделяющей желоб от текста)."

  "Command Launcher Options"
  "Параметры запуска команд"

  "Default 'darkcolor' for all ttk widgets."
  "'Темный цвет' по умолчанию для всех ttk виджетов."

  "Default background color to use for all ttk widgets that are in a disabled state."
  "Цвет фона по умолчанию для всех ttk виджетов в неактивном состоянии."

  "Default background color to use for all ttk widgets when the mouse cursor hovers over the widget."
  "Цвет фона по умолчанию для всех ttk виджетов при наведении на них курсора мыши."

  "Default background color to use for all ttk widgets."
  "Цвет фона по умолчанию для всех ttk виджетов."

  "Default border color for all ttk widgets."
  "Цвет бордюра по умолчанию для всех ttk виджетов."

  "Default color for non-syntax highlighted text."
  "Цвет по умолчанию для выделенного несинтаксического текста."

  "Default foreground text color to use for all ttk widgets that are in a disabled state."
  "Цвет фона текста по умолчанию для всех ttk виджетов в неактивном состоянии."

  "Default foreground text color to use for all ttk widgets."
  "Цвет фона текста по умолчанию для всех ttk виджетов."

  "Determines the number of grips strips to display in the grip area between resizable panes."
  "Определяет размер полоски в области захвата между панелями с изменяемыми размерами."

  "Determines the thickness of the grip area between resizable panes."
  "Определяет толщину области захвата между панелями с изменяемыми размерами."

  "ERROR:  Unable to read"
  "ОШИБКА: Невозможно прочитать"

  "Foreground (slider) color used in a standard scrollbar."
  "Цвет текста (бегунка) в стандартной линейке прокрутки."

  "Foreground (slider) color used in the sidebar scrollbar."
  "Цвет текста (бегунка) в стандартной линейке прокрутки."

  "Foreground (slider) color used in the text scrollbars when pane synchronization is enabled."
  "Цвет текста (бегунка) в линейке прокрутки текста при включенной панели синхронизации."

  "Foreground (slider) color used in the text scrollbars."
  "Цвет текста (бегунка) в линейке прокрутки текста."

  "Foreground color for matching search text"
  "Цвет текста для найденного текста"

  "Foreground color of list items when not selected"
  "Цвет текста для невыбранных элементов списка"

  "Foreground color of move bar."
  "Цвет текста полосы перемещения."

  "Foreground color of selection in command launcher"
  "Цвет текста для выбора команды запуска"

  "Foreground color of textual display in command launcher"
  "Цвет текста в команде запуска"

  "Foreground color to use for title text in the information panel."
  "Цвет текста заголовка в панели информации."

  "Foreground color to use for value text in the information panel."
  "Цвет текста значения в панели информации."

  "Foreground color used in menu items with checks or buttons."
  "Цвет текста переключателей или кнопок меню."

  "Foreground text color for strings."
  "Цвет текста для строк."

  "Foreground text color to use for all miscellaneous1 labeled text."
  "Цвет текста для всех текстов, помеченных miscellaneous1."

  "Foreground text color to use for all miscellaneous2 labeled text."
  "Цвет текста для всех текстов, помеченных miscellaneous2."

  "Foreground text color to use for all miscellaneous3 labeled text."
  "Цвет текста для всех текстов, помеченных miscellaneous3."

  "Foreground text color to use for comments."
  "Цвет текста комментариев."

  "Foreground text color to use for displaying line numbers."
  "Цвет текста номеров строк."

  "Foreground text color to use for displaying numbers."
  "Цвет текста чисел."

  "Foreground text color to use for function calls."
  "Цвет текста для вызовов функций."

  "Foreground text color to use for language-specific keywords."
  "Цвет текста ключевых слов языка программирования."

  "Foreground text color to use for language-specific punctuation."
  "Цвет текста знаков препинания."

  "Foreground text color to use for meta syntax."
  "Цвет текста метасинтаксиса."

  "Foreground text color to use for precompiler syntax."
  "Цвет текста предкомпилированного синтаксиса."

  "Foreground text color to use for readable meta syntax."
  "Цвет текста читаемого метасинтаксиса."

  "Foreground text color to use for selected text."
  "Цвет текста для выделенного текста."

  "Foreground text color to use for variables."
  "Цвет текста для переменных."

  "Foreground text color used for all other tabs that are not the current/active tab in the tabbar."
  "Цвет текста вкладок, которые не являются текущими/активными в панели вкладок."

  "Foreground text color used for menus item that are disabled."
  "Цвет текста неактивных пунктов меню."

  "Foreground text color used for the current/active menu item."
  "Цвет текста активного/текущего пункта меню."

  "Foreground text color used for the current/active tab in the tabbar."
  "Цвет текста текущей/активной вкладки в панели вкладок."

  "Foreground text color used in menus."
  "Цвет текста, используемый в меню."

  "Foreground text/image color used in tabbar and tabs."
  "Цвет текста/изображения в панели вкладок и вкладках."

  "Images"
  "Изображения"

  "Maximum thickness of the command launcher scrollbar when it is active."
  "Максимальная толщина линейки прокрутки в команде запуска, когда она активна."

  "Maximum thickness of the text scrollbar when it is active."
  "Максимальная толщина полосы прокрутки текста, когда он активен."

  "Maximum thickness of the text scrollbars when they are active."
  "Максимальная толщина полос прокрутки текстов, когда они активны."

  "Menu Options"
  "Настройки меню"

  "Menu relief value."
  "Рельеф отображения меню."

  "Pixel height of the spacer between the command launcher entry field and the result list"
  "Высота в пикселях разделителя между полем ввода команды запуска и списком результатов"

  "Pixel height of the tabbar widget."
  "Высота в пикселях панели вкладок."

  "Relief used in drawing the tabs."
  "Рельеф отображения вкладок."

  "Relief value of the sidebar area."
  "Рельеф отображения боковой панели."

  "Scrollbar slider color used in the command launcher results list"
  "Цвет бегунка полосы прокрутки в списке результатов запуска команды"

  "Sidebar Info Panel Options"
  "Параметры области информации в боковой панели"

  "Sidebar Options"
  "Параметры боковой панели"

  "Sidebar Scrollbar Options"
  "Параметры полосы прокрутки боковой панели"

  "Specifies background color of command launcher entry and list"
  "Задает цвет фона в полях ввода команды запуска и списка"

  "Specifies foreground color of command launcher entry and list"
  "Задает цвет текста в полях ввода команды запуска и списка"

  "Specifies the color drawn around the border of the sidebar when a dragged file is droppable"
  "Задает цвет вокруг бордюра боковой панели при опускании перетаскиваемого файла"

  "Specifies the color to display around the sidebar when the sidebar does not have the focus."
  "Задает цвет для бордюра боковой панели, когда она не имеет фокус."

  "Specifies the color to display around the sidebar when the sidebar has the focus."
  "Задает цвет для бордюра боковой панели, когда она имеет фокус."

  "Specifies the default background color to use for text that is selected in a standard ttk widget (this does not include the editing buffer)."
  "Задает цвет фона текста, выделенного в стандартном ttk виджете (исключая текст редактора)."

  "Specifies the default foreground text color to use for text that is selected in a standard ttk widget (this does not include the editing buffer)."
  "Задает цвет текста по умолчанию для текста, выделенного в стандартном ttk виджете (исключая текст редактора)."

  "Specifies the default relief to use when drawing ttk widgets."
  "Задает рельеф по умолчанию для отображения ttk виджетов."

  "Specifies the pixel thickness of the highlight line."
  "Задает толщину в пикселях выделенной строки."

  "Standard Scrollbars"
  "Стандартные линейки прокрутки"

  "Syntax Colors"
  "Цвета для синтаксиса"

  "Tab Options"
  "Параметры вкладок"

  "Text Scrollbar Options"
  "Параметры линейки прокрутки текста"

  "Text color for all sidebar items that are not selected."
  "Цвет текста всех невыделенных строк боковой панели."

  "Text color for all sidebar items that are selected."
  "Цвет текста всех выделенных строк боковой панели."

  "ttk Widget Colors"
  "Цвета ttk виджетов"

}

# themer.tcl (Select "Tools / Theme Editor" to view window containing these strings)
msgcat::mcmset ru {

  "   Show Selected Option"
  "   Показать выбранную опцию"

  "   Show Selected Value"
  "   Показать выбранное значение"

  "By"
  "Автор"

  "Categories"
  "Категории"

  "Change Base Color"
  "Изменить основной цвет"

  "Choose Theme"
  "Выбрать тему"

  "Created By"
  "Сделано"

  "Custom Directory"
  "Заданный каталог"

  "Custom..."
  "Задать..."

  "Delete swatch?"
  "Удалить образец?"

  "Description"
  "Описание"

  "Details"
  "Подробности"

  "Done"
  "Готово"

  "Enable Copy Mode"
  "Включить режим копирования"

  "Export BMP Data"
  "Экспорт данных BMP"

  "Export BMP Mask"
  "Экспорт маски BMP"

  "Export Bitmap Data"
  "Экспорт растровых данных"

  "Export Theme As"
  "Экспортировать тему как"

  "GIF Photo"
  "Фото GIF"

  "Import BMP Data"
  "Импорт данных BMP"

  "Import BMP Mask"
  "Импорт маски BMP"

  "Import Bitmap Data"
  "Импорт растровых данных"

  "Import Error"
  "Ошибка импорта"

  "Import Theme File"
  "Импорт файла темы"

  "Installation Directory"
  "Каталог установки"

  "License File"
  "Файл лицензии"

  "Modifications"
  "Модификации"

  "One-Color Bitmap"
  "Монохромное изображение"

  "Paste Theme Items"
  "Вставить элементы темы"

  "Relief: "
  "Рельеф: "

  "Save As:"
  "Сохранить как:"

  "Save error"
  "Ошибка при сохранении"

  "Save theme changes?"
  "Сохранить изменения темы?"

  "Select Directory"
  "Выберите каталог"

  "Show All"
  "Показать все"

  "Show Category"
  "Показать категорию"

  "Show Color"
  "Показать цвет"

  "Show Selected Option"
  "Показать выбранный параметр"

  "Show Selected Value"
  "Показать выбранное значение"

  "Swatch"
  "Образец"

  "Swatch Colors"
  "Цвета образца"

  "Table Copy"
  "Копирование таблицы"

  "Table Filters"
  "Фильтры таблицы"

  "Table Search"
  "Табличный поиск"

  "The current theme has unsaved changes."
  "Есть несохраненные изменения текущей темы."

  "Theme Name"
  "Название темы"

  "Tree Style: "
  "Стиль дерева: "

  "Two-Color Bitmap"
  "Двухцветное изображение"

  "Unknown color value format"
  "Неизвестный формат значения цвета"

  "User Directory"
  "Каталог пользователя"

  "Value: "
  "Значение: "

  "Website"
  "Сайт"

}

# themes.tcl
msgcat::mcmset ru {

  "Batch custom theme export completed successfully"
  "Экспорт темы успешно завершен"

  "Theme"
  "Тема"

  "Theme:*"
  "Тема:*"

}

# tke.tcl
msgcat::mcmset ru {

  "Import TKE plugin?"
  "Импортировать плагин TKE?"

  "Import TKE theme?"
  "Импортировать тему ТКЕ?"

  "Import TextMate theme?"
  "Импортировать тему TextMate?"

}

# tkedat.tcl
msgcat::mcmset ru {

  "Unable to read"
  "Не удается прочитать"

}

# vim.tcl
msgcat::mcmset ru {

  "COMMAND MODE"
  "КОМАНДНЫЙ РЕЖИМ"

  "File format unrecognized"
  "Неизвестный формат файла"

  "Filename directory does not exist"
  "Каталог с таким именем не существует"

  "Folding method unrecognized"
  "Неизвестный метод сворачивания"

  "INSERT MODE"
  "РЕЖИМ ВСТАВКИ"

  "Illegal modelines value"
  "Некорректное значение modelines"

  "MULTIMOVE MODE"
  "РЕЖИМ MULTIMOVE"

  "Number width not a number"
  "Значение ширины не число"

  "Selection value is unsupported"
  "Выбранное значение не поддерживается"

  "Shiftwidth value is not an integer"
  "Ширина смещения - не целое число"

  "Tabstop value is not an integer"
  "Значение табулостопа - не целое число"

  "Unrecognized vim option"
  "Неизвестная опция vim"

  "VISUAL BLOCK MODE"
  "ВИЗУАЛЬНЫЙ РЕЖИМ БЛОКА"

  "VISUAL LINE MODE"
  "ВИЗУАЛЬНЫЙ РЕЖИМ СТРОКИ"

  "VISUAL MODE"
  "ВИЗУАЛЬНЫЙ РЕЖИМ"

}

# General
msgcat::mcmset ru {

  "All"
  "Все"

  "Attributes"
  "Атрибуты"

  "Auto-Indent"
  "Авто-отступ"

  "Back"
  "Назад"

  "Bird's Eye View"
  "С высоты птичьего полета"

  "Browse"
  "Выбор"

  "Cancel"
  "Отмена"

  "Check for Update"
  "Проверить обновления"

  "Choose"
  "Выбрать"

  "Close"
  "Закрыть"

  "Copy"
  "Копировать"

  "Create"
  "Создать"

  "Current Line"
  "Текущая строка"

  "Current Word"
  "Текущее слово"

  "Cursor"
  "Переход"

  "Delete"
  "Удалить"

  "Directory"
  "Каталог"

  "Documentation"
  "Документация"

  "Duplicate"
  "Дублировать"

  "Edit"
  "Правка"

  "Enable code folding"
  "Включить сворачивание кода"

  "Encoding"
  "Кодировка"

  "Export"
  "Экспорт"

  "Favorite"
  "Избранное"

  "File"
  "Файл"

  "File Name:"
  "Имя файла:"

  "File System"
  "Файловая система"

  "Find"
  "Поиск"

  "Find next occurrence"
  "Найти следующее"

  "Find previous occurrence"
  "Найти предыдущее"

  "Image displayed in sidebar information panel for closing the panel"
  "Изображение в панели информации для закрытия панели"

  "Image displayed in sidebar information panel for refreshing content"
  "Изображение в панели информации для обновления содержимого"

  "Image displayed in sidebar information panel for showing file in sidebar"
  "Изображение в панели информации для показа файлов в боковой панели"

  "Import"
  "Импорт"

  "Insert"
  "Вставка"

  "Install"
  "Установить"

  "Language"
  "Язык"

  "Language Documentation"
  "Документация по языку"

  "Launcher"
  "Запуск команды"

  "Line"
  "Строка"

  "Miscellaneous"
  "Разное"

  "Move To Trash"
  "Удалить в корзину"

  "Move to Other Pane"
  "Переместить в другую панель"

  "Name"
  "Имя"

  "New File"
  "Новый файл"

  "Next"
  "Далее"

  "Node"
  "Узел"

  "None"
  "None"

  "OK"
  "ОК"

  "Open"
  "Открыть"

  "Options"
  "Опции"

  "Output Directory"
  "Каталог для сохранения"

  "Parenthesis"
  "Скобки"

  "Plugin"
  "Плагин"

  "Plugins"
  "Плагины"

  "Preferences"
  "Настройки"

  "Preview"
  "Предосмотр"

  "Rename"
  "Переименовать"

  "Run"
  "Запуск"

  "Save"
  "Сохранить"

  "Save As"
  "Сохранить как"

  "Search"
  "Поиск"

  "Selected"
  "Выделено"

  "Sessions"
  "Сессии"

  "Show in Sidebar"
  "Показать в боковой панели"

  "Show line numbers"
  "Показать номера строк"

  "Show marker map"
  "Показать маркеры"

  "Show sidebar"
  "Показать боковую панель"

  "Show status bar"
  "Показать строку состояния"

  "Show tab bar"
  "Показать панель вкладок"

  "Sidebar"
  "Боковая панель"

  "Smart Indent"
  "Умный отступ"

  "Snippet"
  "Фрагмент кода"

  "Snippets"
  "Фрагменты кода"

  "Split View"
  "Расщепленный вид"

  "Syntax"
  "Синтаксис"

  "TKE Updater"
  "Обновление TKE"

  "Templates"
  "Шаблоны"

  "Test"
  "Тест"

  "Theme Editor"
  "Редактор тем"

  "Tools"
  "Инструменты"

  "Unable to rename file"
  "Не удается переименовать файл"

  "Unable to write"
  "Не удается записать"

  "Unfavorite"
  "Удалить из избранного"

  "Uninstall"
  "Отменить установку"

  "Update"
  "Обновить"

  "Value"
  "Значение"

  "Version"
  "Версия"

  "View"
  "Вид"

}

