# api.tcl
msgcat::mcmset ru {

  "Argument list to api::add_file was not an even key/value pair"
  "Список параметров АНИ :: add_file не было даже пары ключ / значение"

  "Plugin-%s: %s"
  "Плагин % s: %s"

}

# bgproc.tcl
msgcat::mcmset ru {

  "Unable to run system command (%s)"
  "Невозможно запустить командной системы (% ы)"

}

# diff.tcl
msgcat::mcmset ru {

  "    End: "
  "До :"

  "    Start: "
  "С :"

  "Enter difference command"
  "Введите команду разница"

  "Enter starting file"
  "Введите начальный файл"

  "Update"
  "Обновить"

}

# gui.tcl
msgcat::mcmset ru {

  "%s, Line: %d, Column: %d"
  "% С, линия:% д, Колонка:% г"

  "Case sensitivity"
  "Чувствительность к регистру символов"

  "Close All Tabs"
  "Закрыть все вкладки"

  "Close Other Tab(s)"
  "Закрыть Другое Tab (ы)"

  "Close Other*"
  "Закрыть Другое *"

  "Close Tab"
  "Закрыть вкладку"

  "Copyright %d-%d"
  "Copyright% г-г%"

  "Delete tab?"
  "Удалить вкладку?"

  "Developer:"
  "Девелопер"

  "Email:"
  "Эл. почта:"

  "Error"
  "Ошибка"

  "Favorited"
  "В избранном"

  "File already exists.  Use '!' to force an overwrite"
  "Файл уже существует.  Используйте '!' заставить перезаписи"

  "File attribute (%s) does not exist"
  "Атрибут файла (% ы) не существует"

  "File index is out of range"
  "Индекс файла находится вне диапазона"

  "License:"
  "????????:"

  "Line: %d, Column: %d"
  "Линия:% д, Колонка:% г"

  "Locked"
  "ТРУБА ЗАКРЫТАЯ"

  "Move*"
  "Переезд"

  "Must be in multicursor mode to insert numbers"
  "Должно быть в multicursor режиме, чтобы вставить номера"

  "No write permissions.  Use '!' to force write."
  "Нет разрешения на запись.  Используйте '!' заставить писать."

  "Release Type:"
  "Тип релиза:"

  "Reload file?"
  "Перезагрузить файл"

  "Save request"
  "Запрос"

  "Show in Sidebar"
  "Показать на боковой панели"

  "Starting number:"
  "Стартовый номер"

  "Tcl/Tk Version:"
  "Версия Tcl/Tk:"

  "Total Lines: %d, Total Characters: %d"
  "Всего линии:% D, Персонажей:% D"

  "Unable to find current file (tab: %s)"
  "Не удалось найти текущий файл (закладка:% ы)"

  "Unable to successfully parse number string"
  "Не в состоянии успешно разбирать строку номера"

  "Unable to write file"
  "Не удается записать файл"

  "Version:"
  "Версия:"

}

# markers.tcl
msgcat::mcmset ru {

  "Marker name:"
  "Имя Маркер:"

}

# menus.tcl
msgcat::mcmset ru {

  "                                  Profiling Report Sorted By (%s)"
  "Профилирование Сообщить Сортировка по (% ы)"

  "About TKE"
  "О ТКЕ"

  "Align Cursors"
  "????????? ???????"

  "Append Next Occurrence"
  "???????? ????????? ?????????"

  "Auto-Indent"
  "Авто отступ"

  "Check for Update"
  "Проверить обновления"

  "Clear All"
  "Удалить все"

  "Close All"
  "Закрыть все"

  "Close Current"
  "??????? ???????"

  "Copy"
  "Копия"

  "Create at Current Line"
  "??????? ? ??????? ??????"

  "Create..."
  "Создать..."

  "Cut"
  "Вырезать"

  "Edit"
  "Редактировать"

  "Edit Language"
  "Редактировать Язык"

  "Edit Menu Edit user snippets"
  "Редактировать редактировать меню пользователя фрагментов"

  "Edit Menu: Copy text"
  "Меню Правка: Копирование текста"

  "Edit Menu: Cut text"
  "Меню Правка: Вырезание текста"

  "Edit Menu: Edit language snippets"
  "Меню Правка: Редактирование фрагментов"

  "Edit Menu: Edit session current language preferences"
  "Меню Правка: Сессии изменить текущие языковые настройки"

  "Edit Menu: Edit session global preferences"
  "Меню Правка: Изменить глобальные настройки сессии"

  "Edit Menu: Edit user current language preferences"
  "Меню Правка: Изменить текущие настройки языка пользователя"

  "Edit Menu: Edit user global preferences"
  "Меню Правка: Изменить глобальные настройки пользователя"

  "Edit Menu: Edit user menu bindings"
  "Меню Правка: Изменить привязки меню пользователя"

  "Edit Menu: Format all text"
  "Меню Правка: Отформатировать весь текст"

  "Edit Menu: Format selected text"
  "Меню Правка: Формат выделенного текста"

  "Edit Menu: Insert from clipboard"
  "Меню Правка: Вставка из буфера обмена"

  "Edit Menu: Insert snippet"
  "Меню Правка: Вставка фрагмента"

  "Edit Menu: Paste and format text from clipboard"
  "Меню Правка: Вставка и формата текста из буфера обмена"

  "Edit Menu: Paste text from clipboard"
  "Меню Правка: Вставить текст из буфера обмена"

  "Edit Menu: Redo"
  "Меню Правка: повтор"

  "Edit Menu: Reload snippets"
  "Меню Правка: Перезагрузка фрагментов"

  "Edit Menu: Select all text"
  "Меню «Правка»: Выберите весь текст"

  "Edit Menu: Set indent mode to IND"
  "Меню Правка: Задать отступ режим IND"

  "Edit Menu: Set indent mode to IND+"
  "Меню Правка: Задать отступ режим IND +"

  "Edit Menu: Set indent mode to OFF"
  "Меню Правка: Значение отступа режим OFF"

  "Edit Menu: Set user bindings to global bindings"
  "Меню Правка: Глобальные привязки присвоено пользователем привязки"

  "Edit Menu: Set user preferences to global preferences"
  "Меню Правка: Задать пользовательские настройки, чтобы глобальные предпочтения"

  "Edit Menu: Undo"
  "Меню Правка: отменить"

  "Edit Menu: View base preferences file"
  "Меню Правка: Просмотр базовой настройки файла"

  "Edit Menu: View global menu bindings"
  "Меню Правка: Просмотр привязки глобальных меню"

  "Edit Session - Global"
  "????????????? ?????? - ???????????"

  "Edit Session - Language"
  "????????????? ?????? - ????"

  "Edit User"
  "Редактировать страницу пользователя"

  "Edit User - Global"
  "?????????????? ???????????? - ???????????"

  "Edit User - Language"
  "?????????????? ???????????? - ????"

  "File"
  "Файл"

  "File Menu: Close all tabs"
  "Меню файл: Закрыть все вкладки"

  "File Menu: Close current tab"
  "Меню файл: Закрыть текущую вкладку"

  "File Menu: Favorite file"
  "Меню файл: Любимый файл"

  "File Menu: Lock file"
  "Меню файл: Файл блокировки"

  "File Menu: New file"
  "Меню файл: Новый файл"

  "File Menu: Open Favorite"
  "Меню файл: Открытый любимый"

  "File Menu: Open Recent"
  "Меню файл: Открыть последние"

  "File Menu: Open directory"
  "Меню файл: Открытая директория"

  "File Menu: Open file"
  "В меню файл: Открыть файл"

  "File Menu: Quit application"
  "Меню файл: Выйти из приложения"

  "File Menu: Save all files"
  "Меню файл: Сохранить все файлы"

  "File Menu: Save file"
  "Меню файл: Сохранить файл"

  "File Menu: Save file as"
  "Меню файл: Сохранить файл как"

  "File Menu: Show file difference"
  "Меню файл: Показать файл разница"

  "File Menu: Unfavorite file"
  "Меню файл: Unfavorite файла"

  "File Menu: Unlock file"
  "Меню файл: Разблокировать файл"

  "Find"
  "Находить"

  "Find In Files"
  "? ??????"

  "Find Matching Pair"
  "????? ??????????? ????"

  "Find Menu: Append next occurrence"
  "Меню Поиск: Добавить следующее вхождение"

  "Find Menu: Create marker at current line"
  "Меню Поиск: Создать маркер в текущей строке"

  "Find Menu: Find"
  "Найти меню: найти"

  "Find Menu: Find and Replace"
  "Меню Поиск: Поиск и замена"

  "Find Menu: Find in files"
  "Меню Поиск: Найти в файлах"

  "Find Menu: Find matching character pair"
  "Меню Поиск: Найти совпадающие пары символов"

  "Find Menu: Find next occurrence"
  "Меню Поиск: Найти следующее вхождение"

  "Find Menu: Find previous occurrence"
  "Меню Поиск: Найти предыдущее вхождение"

  "Find Menu: Goto next difference"
  "Меню Поиск: Гото следующий разница"

  "Find Menu: Goto previous difference"
  "Меню Поиск: Гото предыдущего различия"

  "Find Menu: Jump backward"
  "Меню Поиск: Прыжок назад"

  "Find Menu: Jump forward"
  "Меню Поиск: Прыжок вперед"

  "Find Menu: Remove all markers"
  "Меню Поиск: Удалить все маркеры"

  "Find Menu: Remove marker from current line"
  "Меню Поиск: Удалить маркер из текущей строки"

  "Find Menu: Select all occurrences"
  "Найти меню: Выберите все вхождения"

  "Find Menu: Show selected line change"
  "Меню Поиск: Показать выбранные линии изменения"

  "Find and Replace"
  "Найти и заменить"

  "Format Text"
  "Формат"

  "From Clipboard"
  "Из буфера обмена"

  "Goto Last Tab"
  "На Последняя вкладка"

  "Goto Next Tab"
  "На Следующая вкладка"

  "Goto Other Pane"
  "На Другая панель"

  "Goto Previous Tab"
  "На Предыдущая вкладка"

  "Help"
  "Помощь"

  "Help Menu: About TKE"
  "Меню Справка: О TKE"

  "Help Menu: Check for update"
  "Меню Справка: Проверка обновлений"

  "Help Menu: Send bug report"
  "Меню Справка: Отправить отчет об ошибке"

  "Help Menu: Send feedback"
  "Меню Справка: Отправить отзыв"

  "Help Menu: View user guide"
  "Меню Справка: Просмотр руководства пользователя"

  "Hide Console"
  "Скрыть Console"

  "Hide Line Numbers"
  "Скрыть числа"

  "Hide Meta Characters"
  "?????? ???? ???????"

  "Hide Sidebar"
  "Скрыть боковую панель"

  "Hide Status Bar"
  "Панель состояния (Status bar)"

  "Hide Tab Bar"
  "Скрыть панель вкладок,"

  "Indent"
  "Отступ"

  "Indent Mode"
  "Отступ режим"

  "Indent Off"
  "Отступ от"

  "Insert Enumeration"
  "???????? ????????????"

  "Insert Text"
  "Вставить текст"

  "Install..."
  "Устанавливать"

  "Jump Backward"
  "??????? ?????"

  "Jump Forward"
  "??????? ??????"

  "Launcher"
  "Пусковая установка"

  "Lock"
  "шлюз"

  "Markers"
  "Указатели"

  "Menu Bindings"
  "Меню Наручники"

  "Menus: About TKE"
  "Меню: О TKE"

  "Merge Panes"
  "??????????? ????????"

  "Next Difference"
  "????????? ???????"

  "Open Directory..."
  "Open Directory ..."

  "Open Favorite"
  "Открыть Любимое"

  "Open File..."
  "Открытая линия"

  "Open Recent"
  "Недавний"

  "Paste"
  "Паста"

  "Paste and Format"
  "Вставить и Формат"

  "Plugins"
  "Плагин"

  "Plugins Menu: Create new plugin"
  "Плагины меню: Создать новый плагин"

  "Plugins Menu: Install plugin"
  "Плагины меню: Установить плагин"

  "Plugins Menu: Reload all plugins"
  "Плагины меню: Перезагрузить все плагины"

  "Plugins Menu: Uninstall plugin"
  "Плагины меню: Удалить плагин"

  "Preferences"
  "Предпочтения"

  "Previous Difference"
  "?????????? ???????"

  "Profiling started"
  "Профилирования начал"

  "Profiling stopped"
  "Профилирования остановился"

  "Quit"
  "Выход"

  "Redo"
  "Вернуть"

  "Reload"
  "Перезагрузить"

  "Remove All Markers"
  "??????? ??? ???????"

  "Remove From Current Line"
  "??????? ?? ??????? ??????"

  "Replace Line With Script"
  "???????? ?????? ???????"

  "Reset User to Base"
  "Восстановить базу пользователя"

  "Restart TKE"
  "????????????? TKE"

  "Save All"
  "Сохранить все"

  "Save As..."
  "Сохранить как"

  "Save Current"
  "????????? ???????"

  "Select All"
  "Выбрать все"

  "Select All Occurrences"
  "???????? ??? ?????????"

  "Select Next Occurrence"
  "??????? ????????? ?????????"

  "Select Previous Occurrence"
  "??????? ?????????? ?????????"

  "Selected"
  "Выбранный"

  "Send Bug Report"
  "Отправить отчет об ошибке"

  "Send Feedback"
  "Отправить отзыв"

  "Sessions"
  "??????"

  "Sessions Menu: Close current session"
  "Сессий меню: Закрыть текущий сеанс"

  "Sessions Menu: Delete session"
  "Меню сессий: Удалить сессия"

  "Sessions Menu: Open session"
  "Сессий меню: Открытая сессия"

  "Sessions Menu: Save current session"
  "Сессий меню: Сохранение текущей сессии"

  "Sessions Menu: Save sessions as"
  "Сессий меню: Сохранить сессий как"

  "Sessions Menu: Switch to session"
  "Сессий меню: Перейти на сессии"

  "Set Syntax"
  "Установите Синтаксис"

  "Set Theme"
  "Заданную тему"

  "Set User to Global"
  "Задать пользователя для глобальной"

  "Show Console"
  "Показать консоль"

  "Show Diagnostic Logfile"
  "Показать файл журнала диагностики"

  "Show File Difference"
  "Показать файл разницы"

  "Show Last Profiling Report"
  "Показать Последний профилирования отчет"

  "Show Line Numbers"
  "Показать номера строк"

  "Show Meta Characters"
  "???????? ??????? ????"

  "Show Selected Line Change"
  "???????? ????????? ????? ?????????"

  "Show Sidebar"
  "Показать боковую панель"

  "Show Status Bar"
  "Панель состояния (Status bar)"

  "Show Tab Bar"
  "Показать Панель вкладок"

  "Smart Indent"
  "Смарт отступа"

  "Snippet"
  "Фрагмента"

  "Snippets"
  "Обрывки"

  "Sort Tabs"
  "Сортировка Вкладки"

  "Start Profiling"
  "Запуск профилирования"

  "Stop Profiling"
  "Остановить профилирование"

  "Switch To"
  "????????????? ??"

  "Tabs"
  "Флажки"

  "Text"
  "Text"

  "Text Menu: Align cursors"
  "Текст меню: Выровнять курсоры"

  "Text Menu: Indent selected text"
  "Текст меню: Отступ выделенного текста"

  "Text Menu: Insert enumeration"
  "Текста меню: Перечисление Вставка"

  "Text Menu: Replace line with script"
  "Текст меню: Замените строку скрипта"

  "Text Menu: Toggle comment"
  "Текст меню: Toggle комментарий"

  "Text Menu: Unindent selected text"
  "Текст меню: Отмена отступа выделенного текста"

  "Toggle Comment"
  "??????????? ???????????"

  "Tools"
  "Инструмент"

  "Tools Menu: Disable Vim mode"
  "Меню Сервис: Отключить режим Vim"

  "Tools Menu: Enable Vim mode"
  "Меню Сервис: Включить режим Vim"

  "Tools Menu: Restart TKE"
  "Меню Сервис: Перезагрузка TKE"

  "Tools Menu: Run theme editor"
  "Меню Инструменты: Запустите редактор тема"

  "Tools Menu: Show diagnostic logfile"
  "Меню Сервис: Показать диагностический лог"

  "Tools Menu: Show last profiling report"
  "Меню Сервис: Показать последний отчет профилирования"

  "Tools Menu: Start profiling"
  "Меню Сервис: Начало профилирования"

  "Tools Menu: Stop profiling"
  "Меню Сервис: Остановить профилирование"

  "Undo"
  "Отменить"

  "Unindent"
  "Unindent"

  "Uninstall..."
  "menyahpasang"

  "Unlock"
  "Разблокировать"

  "User Guide"
  "Руководство пользователя"

  "View"
  "Просмотр"

  "View Base"
  "Просмотр базы"

  "View Global"
  "Вид глобальной"

  "View Menu: Goto last tab"
  "Меню Вид: Последняя вкладка Гото"

  "View Menu: Goto next tab"
  "Меню Вид: Перейти к следующей вкладке"

  "View Menu: Goto other pane"
  "Меню Вид: Перейти к другой области"

  "View Menu: Goto previous tab"
  "Меню Вид: Перейти к предыдущей вкладке"

  "View Menu: Hide console"
  "Меню Вид: Скрыть консоль"

  "View Menu: Hide line numbers"
  "В меню Вид: Скрыть номера строк"

  "View Menu: Hide meta characters"
  "В меню Вид: Скрыть мета символы"

  "View Menu: Hide sidebar"
  "В меню Вид: Скрыть боковую панель"

  "View Menu: Hide status bar"
  "В меню Вид: Скрыть строку состояния"

  "View Menu: Hide tab bar"
  "В меню Вид: Скрыть панель вкладок"

  "View Menu: Merge panes"
  "В меню Вид: Слияние областей"

  "View Menu: Move to other pane"
  "Меню Вид: Перейти к другой области"

  "View Menu: Show console"
  "В меню Вид: Показать консоль"

  "View Menu: Show line numbers"
  "В меню Вид: Показать номера строк"

  "View Menu: Show meta characters"
  "В меню Вид: Показывать мета символы"

  "View Menu: Show sidebar"
  "Меню Вид: Боковой панели шоу"

  "View Menu: Show status bar"
  "В меню Вид: Показать строку состояния"

  "View Menu: Show tab bar"
  "В меню Вид: Показать панель вкладок"

  "View Menu: Sort tabs"
  "Меню Вид: Вкладки Сортировка"

  "View Menu: Toggle split view mode"
  "В меню Вид: Toggle Сплит режим просмотра"

  "Vim Mode"
  "Режим Вим"

}

# plugins.tcl
msgcat::mcmset ru {

  "ERROR (%s,%s): %s"
  "Ошибка (%s, %s): %s"

  "ERROR:  Plugin name already exists"
  "ОШИБКА: Плагин именем уже существует"

  "ERROR:  Plugin name is not valid (only alphanumeric and underscores are allowed)"
  "ОШИБКА: Плагин имя недопустимо (только буквенно-цифровой и подчеркивания позволяется)"

  "ERROR:  Unable to create plugin directory"
  "ОШИБКА: Невозможно создать каталог плагинов"

  "ERROR:  Unable to write plugin files"
  "ОШИБКА: Невозможно записать файлы плагина"

  "Enter plugin name"
  "Введите плагин имя"

  "Plugin %s installed"
  "Плагин% с установлен"

  "Plugin %s uninstalled"
  "Плагин% с удаления"

  "Plugin Errors"
  "Плагин ошибки"

  "Plugins successfully reloaded"
  "Плагины успешно перезагружается"

  "Syntax errors found in selected plugins"
  "Синтаксические ошибки, найденные в выбранных плагинов"

}

# search.tcl
msgcat::mcmset ru {

  "%d substitutions done"
  "подстановки %d сделали"

  "No files found in specified directories"
  "Файлы не найдены в указанных каталогах"

  "No search results found"
  "Результаты не найдены."

  "Search wrapped to beginning of file"
  "Поиск, завернутые в начале файла"

  "Search wrapped to end of file"
  "Поиск, завернутые в конец файла"

}

# sidebar.tcl
msgcat::mcmset ru {

  "Add Parent Directory"
  "Каталог"

  "Close Directory Files"
  "Закрыть Каталог файлов"

  "Copy Pathname"
  "?????????? ????"

  "Delete directory?"
  "Удалить каталог?"

  "Delete file?"
  "Удалить файл?"

  "Directory Name:"
  "Имя файла"

  "Duplicate"
  "Удвоить"

  "File Name:"
  "&Имя файла:"

  "Folder Name:"
  "???????? ?????"

  "Make Current Working Directory"
  "Сделать текущий рабочий каталог"

  "New Directory"
  "Новый Справочник"

  "Open Directory Files"
  "Открытие файлов Каталог"

  "Refresh Directory Files"
  "Обновить каталог файлов"

  "Remove Parent from Sidebar"
  "Удалить родительский от боковой панели"

  "Remove from Sidebar"
  "Удалить из боковой панели"

  "Rename"
  "Переименовать"

  "Show Difference"
  "Показать разницу"

}

# snippets.tcl
msgcat::mcmset ru {

  "Snippet: *"
  "Фрагмент: *"

}

# syntax.tcl
msgcat::mcmset ru {

  "Syntax error in %s.syntax file"
  "Ошибка синтаксиса в% файле s.syntax"

  "Syntax: %s"
  "Синтаксис: %s"

}

# theme.tcl
msgcat::mcmset ru {

  "ERROR:  Unable to read %s"
  "ОШИБКА: Невозможно прочитать% с"

  "Images"
  "Изображения"

  "Menu Options"
  "Настройки меню"

  "Sidebar Options"
  "Параметры боковой панели"

  "Sidebar Scrollbar Options"
  "Sidebar Опции полоса прокрутки"

  "Syntax Colors"
  "Синтаксис цвета"

  "Tab Options"
  "Вкладка Параметры"

  "Text Scrollbar Options"
  "Текст полоса прокрутки Опции"

  "ttk Widget Colors"
  "ТТК Виджет Цвета"

}

# themer.tcl
msgcat::mcmset ru {

  "   Show All"
  "Показать все"

  "   Show Category"
  "Показать категорию"

  "   Show Color"
  "Показать цвет фона"

  "   Show Selected Option"
  "Показать выбранные опции"

  "   Show Selected Value"
  "Выберете значение"

  "Categories"
  "Категории"

  "Change Base Color"
  "Изменить База Цвет"

  "Choose Theme"
  "Выбрать тему:"

  "Custom Directory"
  "Пользовательские Каталог"

  "Custom..."
  "Заказ..."

  "Delete swatch?"
  "Удалить образец?"

  "Description"
  "Описание"

  "Details"
  "Детали"

  "Done"
  "Готово"

  "Export"
  "Экспорт"

  "GIF Photo"
  "GIF фото"

  "Import"
  "Импорт"

  "Import BMP Data"
  "Импорт данных"

  "Import BMP Mask"
  "Импорт BMP Маска"

  "Import Error"
  "ошибка импорта:"

  "Import Theme File"
  "Импорт файла Тема"

  "Installation Directory"
  "Каталог установки"

  "Modifications"
  "Измененных"

  "None"
  "Нет"

  "One-Color Bitmap"
  "Один-битовых цветовых"

  "Preview"
  "Предварительный просмотр"

  "Relief: "
  "Предохранительный:"

  "Save As:"
  "Сохранить как"

  "Save theme changes?"
  "Сохранить изменения теме?"

  "Select Directory"
  "Выберите папку"

  "Swatch"
  "Swatch"

  "Swatch Colors"
  "Swatch цвета"

  "Table Filters"
  "Таблица Фильтры"

  "The current theme has unsaved changes"
  "В настоящее время тема имеет несохраненные изменения"

  "Theme Editor %s %s"
  "Тема редактор% s% s"

  "Tree Style: "
  "Дерево Стиль:"

  "Two-Color Bitmap"
  "Двухцветного Bitmap"

  "User Directory"
  "Каталог пользователя"

  "Value"
  "Значение"

  "Value: "
  "Значение:"

}

# themes.tcl
msgcat::mcmset ru {

  "Theme:  %s"
  "Стиль:% с"

  "Theme:*"
  "Тема"

}

# tke.tcl
msgcat::mcmset ru {

  "Import TKE theme?"
  "Импорт ТКЕ тема?"

  "Import TextMate theme?"
  "Импорт TextMate тему?"

}

# tkedat.tcl
msgcat::mcmset ru {

  "Unable to open %s for reading"
  "Не удается открыть %s для чтения"

}

# vim.tcl
msgcat::mcmset ru {

  "File %s successfully written"
  "Файл %s успешно записаны"

  "Filename %s already exists"
  "Имя файла %s уже существует"

}

# General
msgcat::mcmset ru {

  "All"
  "All"

  "Cancel"
  "Отмена"

  "Close"
  "Клоуз"

  "Delete"
  "Удалить"

  "Favorite"
  "Любимый"

  "Find:"
  "Находить"

  "Move to Other Pane"
  "Переехать в другой панели"

  "New File"
  "Новый файл"

  "Open"
  "Открыть"

  "Replace:"
  "Заменить:"

  "Save"
  "Сохранить"

  "Save As"
  "Сохранить как"

  "Split View"
  "????????? ????? ? ?? ??????????"

  "Theme Editor"
  "Визуальный редактор темы"

  "Unable to open %s for writing"
  "Невозможно открыть% с для записи"

  "Unfavorite"
  "Unfavorite"

}

