# api.tcl
msgcat::mcmset ru {

  "Argument list to api::add_file was not an even key/value pair"
  "Список параметров АНИ :: add_file не было даже пары ключ / значение"

}

# bgproc.tcl
msgcat::mcmset ru {

  "Unable to run system command (%s)"
  "Невозможно запустить командной системы (% ы)"

}

# gui.tcl
msgcat::mcmset ru {

  "%s, Line: %d, Column: %d"
  "% С, линия:% д, Колонка:% г"

  "Close All Tabs"
  "Закрыть все вкладки"

  "Close Other Tab(s)"
  "Закрыть Другое Tab (ы)"

  "Close Other*"
  "Закрыть Другое *"

  "Close Tab"
  "Закрыть вкладку"

  "Copyright %d-%d"
  "Copyright% г-г%"

  "Delete tab?"
  "Удалить вкладку?"

  "Developer:"
  "Девелопер"

  "Email:"
  "Эл. почта:"

  "Favorited"
  "В избранном"

  "File attribute (%s) does not exist"
  "Атрибут файла (% ы) не существует"

  "File index is out of range"
  "Индекс файла находится вне диапазона"

  "Line: %d, Column: %d"
  "Линия:% д, Колонка:% г"

  "Locked"
  "ТРУБА ЗАКРЫТАЯ"

  "Move to Other Pane"
  "Переехать в другой панели"

  "Move*"
  "Переезд"

  "Release Type:"
  "Тип релиза:"

  "Reload file?"
  "Перезагрузить файл"

  "Save request"
  "Запрос"

  "Show in Sidebar"
  "Показать на боковой панели"

  "Tcl/Tk Version:"
  "Версия Tcl/Tk:"

  "Total Lines: %d, Total Characters: %d"
  "Всего линии:% D, Персонажей:% D"

  "Unable to find current file (tab: %s)"
  "Не удалось найти текущий файл (закладка:% ы)"

  "Untitled"
  "Без имени"

  "Version:"
  "Версия:"

}

# markers.tcl
msgcat::mcmset ru {

  "Marker name:"
  "Имя Маркер:"

}

# menus.tcl
msgcat::mcmset ru {

  "                                  Profiling Report Sorted By (%s)"
  "Профилирование Сообщить Сортировка по (% ы)"

  "About TKE"
  "О ТКЕ"

  "Align cursors"
  "Совместите курсоры"

  "All"
  "All"

  "Append next occurrence"
  "Добавьте следующее вхождение"

  "Check for Update"
  "Проверить обновления"

  "Clear All"
  "Удалить все"

  "Close All"
  "Закрыть все"

  "Comment"
  "Комментарий"

  "Copy"
  "Копия"

  "Create new..."
  "создать новый"

  "Create..."
  "Создать..."

  "Cut"
  "Вырезать"

  "Disable Auto-Indent"
  "Отключить авто отступ"

  "Edit"
  "Редактировать"

  "Edit current"
  "Редактировать тока"

  "Edit user"
  "Редактирование пользователя"

  "Edit..."
  "Правка..."

  "Enable Auto-Indent"
  "Включить Авто отступ"

  "File"
  "Файл"

  "Find"
  "Находить"

  "Find and Replace"
  "Найти и заменить"

  "Find in files"
  "Найти в файлах"

  "Find marker"
  "Найти маркер"

  "Find matching pair"
  "Найти подходящую пару"

  "Format Text"
  "Формат"

  "From Clipboard"
  "Из буфера обмена"

  "Goto Last Tab"
  "На Последняя вкладка"

  "Goto Next Tab"
  "На Следующая вкладка"

  "Goto Other Pane"
  "На Другая панель"

  "Goto Previous Tab"
  "На Предыдущая вкладка"

  "Help"
  "Помощь"

  "Hide Console"
  "Скрыть Console"

  "Hide Sidebar"
  "Скрыть боковую панель"

  "Hide Status Bar"
  "Панель состояния (Status bar)"

  "Hide Tab Bar"
  "Скрыть панель вкладок,"

  "Import TextMate theme..."
  "Импорт TextMate тема ..."

  "Indent"
  "Отступ"

  "Insert Text"
  "Вставить текст"

  "Insert enumeration"
  "Вставьте перечисление"

  "Install..."
  "Устанавливать"

  "Launcher"
  "Пусковая установка"

  "Lock"
  "шлюз"

  "Menu Bindings"
  "Меню Наручники"

  "Menu: About TKE"
  "Меню: О ТКЕ"

  "Menu: Align cursors"
  "Меню: Совместите курсоры"

  "Menu: Append next occurrence"
  "Меню: Добавьте следующее вхождение"

  "Menu: Check for Update"
  "Меню: Проверить обновления"

  "Menu: Close all tabs"
  "Меню: Закрыть все вкладки"

  "Menu: Close current tab"
  "Меню: Закрыть вкладку тока"

  "Menu: Comment selected text"
  "Меню: Комментарий выделенный текст"

  "Menu: Copy selected text"
  "Меню: Копировать выделенный текст"

  "Menu: Create new plugin"
  "Меню: Создание нового плагина"

  "Menu: Create new theme"
  "Меню: Создать новую тему"

  "Menu: Cut selected text"
  "Меню: Вырезать выделенный текст"

  "Menu: Disable Vim mode"
  "Меню: Режим Отключить Вим"

  "Menu: Disable auto-indent"
  "Меню: Отключить авто отступ"

  "Menu: Edit Tke theme"
  "Меню: Редактирование ТКЕ тему"

  "Menu: Edit current snippets"
  "Меню: Редактирование текущие поместив"

  "Menu: Edit user menu bindings"
  "Привязки меню Правка пользователь: Меню"

  "Menu: Edit user preferences"
  "Предпочтения Редактировать пользовательские: Меню"

  "Menu: Enable Vim mode"
  "Меню: Включить режим Vim"

  "Menu: Enable auto-indent"
  "Меню: Включить Авто отступ"

  "Menu: Favorite file"
  "Меню: Любимое файл"

  "Menu: Find"
  "Меню: Найти"

  "Menu: Find and Replace"
  "Найти и заменить"

  "Menu: Find in files"
  "Меню: Найти в файлах"

  "Menu: Find matching character pair"
  "Меню: Найти соответствие символов пару"

  "Menu: Find next occurrence"
  "Меню: Найти следующее вхождение"

  "Menu: Find previous occurrence"
  "Меню: Найти предыдущее вхождение"

  "Menu: Format all text"
  "Меню: Формат весь текст"

  "Menu: Format selected text"
  "Меню: Формат выделенный текст"

  "Menu: Goto last tab"
  "Меню: На последней вкладке"

  "Menu: Goto next tab"
  "Меню: На следующей вкладке"

  "Menu: Goto other pane"
  "Меню: На другой панели"

  "Menu: Goto previous tab"
  "Меню: На предыдущей вкладке"

  "Menu: Hide Tab Bar"
  "Меню: Скрыть панель вкладок,"

  "Menu: Hide console"
  "Меню: Скрыть консоль"

  "Menu: Hide sidebar"
  "Меню: Скрыть в боковой панели"

  "Menu: Hide status bar"
  "Меню: бар Свернуть статус"

  "Menu: Import TextMate theme"
  "Меню: Импорт TextMate тема"

  "Menu: Indent selected text"
  "Меню: отступ выделенного текста"

  "Menu: Insert enumeration"
  "Меню: Вставьте перечисление"

  "Menu: Insert from clipboard"
  "Вставка из буфера обмена"

  "Menu: Insert snippet"
  "Меню: Вставка фрагмент"

  "Menu: Install plugin"
  "Меню: Установите плагин"

  "Menu: Lock file"
  "Меню: Файл блокировки"

  "Menu: Move to other pane"
  "Меню: переход к другой панели"

  "Menu: New file"
  "Меню: Новый файл"

  "Menu: Open Favorite"
  "Меню: Open Любимое"

  "Menu: Open Recent"
  "Меню: Открыть недавние"

  "Menu: Open directory"
  "Меню: Open Directory"

  "Menu: Open file"
  "Меню: Открыть файл"

  "Menu: Paste and format text from clipboard"
  "Меню: Вставить и формат текста из буфера обмена"

  "Menu: Paste text from clipboard"
  "Меню: Вставить текст из буфера обмена"

  "Menu: Quit application"
  "Меню: Закройте приложение"

  "Menu: Redo"
  "Меню: Повторить"

  "Menu: Reload all plugins"
  "Меню: Reload все плагины"

  "Menu: Reload current snippets"
  "Меню: Перезагрузка текущей поместив"

  "Menu: Restart tke"
  "Меню: Перезагрузка ТКЕ"

  "Menu: Save all files"
  "Меню: Сохраните все файлы"

  "Menu: Save file"
  "Меню: Сохранить файл"

  "Menu: Save file as"
  "Меню: Сохранить файл как"

  "Menu: Select all occurrences"
  "Меню: Выберите все вхождения"

  "Menu: Select all text"
  "Меню: Выбрать весь текст"

  "Menu: Set user bindings to global bindings"
  "Меню: Установите пользовательские привязки к глобальным привязок"

  "Menu: Set user preferences to global preferences"
  "Меню: Установите пользовательские предпочтения на глобальные предпочтения"

  "Menu: Show Tab Bar"
  "Меню: Показать Панель вкладок"

  "Menu: Show console"
  "Меню: Показать консоль"

  "Menu: Show last profiling report"
  "Меню: Показать отчет в прошлом профилирования"

  "Menu: Show sidebar"
  "Меню: Показать боковой панели"

  "Menu: Show status bar"
  "Меню: бар Показать статус"

  "Menu: Sort tabs"
  "Меню: вкладки сортировки"

  "Menu: Start profiling"
  "Меню: Начните профилирование"

  "Menu: Stop profiling"
  "Меню: Стоп профилирование"

  "Menu: Toggle split view mode"
  "Меню: Переключить режим разделения вид"

  "Menu: Uncomment selected text"
  "Меню: Раскомментируйте выделенный текст"

  "Menu: Undo"
  "Меню: Отменить"

  "Menu: Unfavorite file"
  "Меню: Unfavorite файл"

  "Menu: Unindent selected text"
  "Меню: Unindent выделенный текст"

  "Menu: Uninstall plugin"
  "Меню: Удалите плагин"

  "Menu: Unlock file"
  "Меню: Разблокировать файл"

  "Menu: View User Guide"
  "Меню: Вид Руководство пользователя"

  "Menu: View global menu bindings"
  "Меню: Просмотреть глобальную привязки меню"

  "Menu: View global preferences"
  "Меню: Вид глобальные предпочтения"

  "Move to other pane"
  "Переместить в другой панели"

  "New"
  "Новый"

  "Open Directory..."
  "Open Directory ..."

  "Open Favorite"
  "Открыть Любимое"

  "Open File..."
  "Открытая линия"

  "Open Recent"
  "Недавний"

  "Paste"
  "Паста"

  "Paste and Format"
  "Вставить и Формат"

  "Plugins"
  "Плагин"

  "Preferences"
  "Предпочтения"

  "Profiling started"
  "Профилирования начал"

  "Profiling stopped"
  "Профилирования остановился"

  "Quit"
  "Выход"

  "Redo"
  "Вернуть"

  "Reload"
  "Перезагрузить"

  "Reload current"
  "Перезагрузка текущей"

  "Reset user to base"
  "Сброс пользователю основывать"

  "Restart tke"
  "Перезагрузка ТКЕ"

  "Save All"
  "Сохранить все"

  "Save As..."
  "Сохранить как"

  "Select All"
  "Выбрать все"

  "Select all occurrences"
  "Выберите все вхождения"

  "Select next occurrence"
  "Выберите следующее вхождение"

  "Select previous occurrence"
  "Выберите предыдущее вхождение"

  "Selected"
  "Выбранный"

  "Set Syntax"
  "Установите Синтаксис"

  "Set Theme"
  "Заданную тему"

  "Set user to global"
  "Установите пользователю глобальной"

  "Show Console"
  "Показать консоль"

  "Show Last Profiling Report"
  "Показать Последний профилирования отчет"

  "Show Sidebar"
  "Показать боковую панель"

  "Show Status Bar"
  "Панель состояния (Status bar)"

  "Show Tab Bar"
  "Показать Панель вкладок"

  "Show*Profiling*"
  "Показать * Профилирование *"

  "Snippet"
  "Фрагмента"

  "Snippets"
  "Обрывки"

  "Sort Tabs"
  "Сортировка Вкладки"

  "Split view"
  "Раздельно папки и их содержимое"

  "Start Profiling"
  "Запуск профилирования"

  "Stop Profiling"
  "Остановить профилирование"

  "Tabs"
  "Флажки"

  "Text"
  "Text"

  "Theme Creator"
  "Тема Создатель"

  "Tools"
  "Инструмент"

  "Uncomment"
  "Раскомментировать"

  "Undo"
  "Отменить"

  "Unindent"
  "Unindent"

  "Uninstall..."
  "menyahpasang"

  "Unlock"
  "Разблокировать"

  "User Guide"
  "Руководство пользователя"

  "View"
  "Просмотр"

  "View base"
  "Посмотреть база"

  "View global"
  "Просмотреть глобальную"

  "Vim Mode"
  "Режим Вим"

}

# plugins.tcl
msgcat::mcmset ru {

  "ERROR:  Plugin name already exists"
  "ОШИБКА: Плагин именем уже существует"

  "ERROR:  Plugin name is not valid (only alphanumeric and underscores are allowed)"
  "ОШИБКА: Плагин имя недопустимо (только буквенно-цифровой и подчеркивания позволяется)"

  "ERROR:  Unable to create plugin directory"
  "ОШИБКА: Невозможно создать каталог плагинов"

  "ERROR:  Unable to write plugin files"
  "ОШИБКА: Невозможно записать файлы плагина"

  "Enter plugin name"
  "Введите плагин имя"

  "Plugin %s installed"
  "Плагин% с установлен"

  "Plugin %s uninstalled"
  "Плагин% с удаления"

  "Plugin Errors"
  "Плагин ошибки"

  "Plugins successfully reloaded"
  "Плагины успешно перезагружается"

  "Syntax errors found in selected plugins"
  "Синтаксические ошибки, найденные в выбранных плагинов"

}

# sidebar.tcl
msgcat::mcmset ru {

  "Add Parent Directory"
  "Каталог"

  "Close Directory Files"
  "Закрыть Каталог файлов"

  "Delete"
  "Удалить"

  "Delete directory?"
  "Удалить каталог?"

  "Delete file?"
  "Удалить файл?"

  "Duplicate"
  "Удвоить"

  "Make Current Working Directory"
  "Сделать текущий рабочий каталог"

  "New Directory"
  "Новый Справочник"

  "New File"
  "Новый файл"

  "Open"
  "Открыть"

  "Open Directory Files"
  "Открытие файлов Каталог"

  "Refresh Directory Files"
  "Обновить каталог файлов"

  "Remove Parent from Sidebar"
  "Удалить родительский от боковой панели"

  "Remove from Sidebar"
  "Удалить из боковой панели"

  "Rename"
  "Переименовать"

}

# snippets.tcl
msgcat::mcmset ru {

  "Snippet: %s: %s"
  "Фрагмент:% S:% с"

  "Snippet: *"
  "Фрагмент: *"

}

# syntax.tcl
msgcat::mcmset ru {

  "Syntax error in %s.syntax file"
  "Ошибка синтаксиса в% файле s.syntax"

  "Syntax:  %s"
  "Синтаксис:% с"

  "Theme:  %s"
  "Стиль:% с"

}

# themer.tcl
msgcat::mcmset ru {

  "Create"
  "Создайте"

  "Create New Theme"
  "Создать новую тему"

  "Create custom"
  "Создание пользовательских"

  "ERROR:  Unable to read %s"
  "ОШИБКА: Невозможно прочитать% с"

  "ERROR:  Unable to write %s"
  "ОШИБКА: Невозможно записать% с"

  "Edit theme"
  "Редактировать тему"

  "Enter theme name"
  "Введите название темы"

  "Error:  Theme is not a supported theme"
  "Ошибка: Тема не поддерживается тема"

  "Import"
  "Импорт"

  "Import TextMate Theme"
  "Импорт TextMate Стиль"

  "Name:"
  "ФИО:"

  "OK"
  "ОК (в порядке)"

  "Reset"
  "Сбросом"

  "Select theme"
  "Выберите тему."

}

# tke.tcl
msgcat::mcmset ru {

  "ERROR:  %s"
  "ОШИБКА:% с"

  "Edit theme?"
  "Редактировать тему?"

  "Import TextMate theme?"
  "Импорт TextMate тему?"

}

# tkedat.tcl
msgcat::mcmset ru {

  "Unable to open %s for reading"
  "Невозможно открыть% с для чтения"

  "Unable to open %s for writing"
  "Невозможно открыть% с для записи"

}

# General
msgcat::mcmset ru {

  "Cancel"
  "Отмена"

  "Close"
  "Клоуз"

  "Favorite"
  "Любимый"

  "Find:"
  "Находить"

  "Replace:"
  "Заменить:"

  "Save"
  "Сохранить"

  "Save As"
  "Сохранить как"

  "Unfavorite"
  "Unfavorite"

}

