# api.tcl
msgcat::mcmset sv {

  "Argument list to api::add_file was not an even key/value pair"
  "Argument listan till api :: add_file var inte en ens nyckel / värde-par"

}

# bgproc.tcl
msgcat::mcmset sv {

  "Unable to run system command (%s)"
  "Det går inte att köra systemet kommandot (% s)"

}

# diff.tcl
msgcat::mcmset sv {

  "    End: "
  "Slut:"

  "    Start: "
  "Start:"

  "Enter difference command"
  "Ange skillnaden kommando"

  "Enter starting file"
  "Ange start fil"

  "Update"
  "Uppdatera"

}

# gui.tcl
msgcat::mcmset sv {

  "%s, Line: %d, Column: %d"
  "% S, Rad:% d, Kolumn:% d"

  "Case sensitivity"
  "Skiftlägeskänslighet"

  "Close All Tabs"
  "Stäng alla flikar"

  "Close Other Tab(s)"
  "Stäng Other Tab (er)"

  "Close Other*"
  "Stäng övriga flikar"

  "Close Tab"
  "Stäng flik"

  "Copyright %d-%d"
  "Copyright% d-% d"

  "Delete tab?"
  "Radera flik?"

  "Developer:"
  "Utvecklare:"

  "Email:"
  "E-post:"

  "Error"
  "Fel"

  "Favorited"
  "Favorit"

  "File already exists.  Use '!' to force an overwrite"
  "Filen finns redan.  Använd '!' tvinga en överskrivning"

  "File attribute (%s) does not exist"
  "File attribut (% s) finns inte"

  "File index is out of range"
  "File index är utanför intervallet"

  "License:"
  "Licens"

  "Line: %d, Column: %d"
  "Rad:% d, Kolumn:% d"

  "Locked"
  "Spärrad"

  "Move*"
  "Move"

  "Must be in multicursor mode to insert numbers"
  "Måste vara i multicursor läge infoga nummer"

  "No write permissions.  Use '!' to force write."
  "Ingen skrivbehörighet.  Använd '!' tvinga skriva."

  "Release Type:"
  "Utgivningstyp:"

  "Reload file?"
  "Ladda om filen"

  "Save request"
  "Spara begäran"

  "Show in Sidebar"
  "Show i Sidebar"

  "Starting number:"
  "Sidnummer för första sidan:"

  "Tcl/Tk Version:"
  "Tcl/Tk Version:"

  "Total Lines: %d, Total Characters: %d"
  "Totalt antal rader:% d, totalt Tecken:% d"

  "Unable to find current file (tab: %s)"
  "Det gick inte att hitta aktuell fil (flik:% s)"

  "Unable to successfully parse number string"
  "Inte att framgångsrikt parsa nummer sträng"

  "Unable to write file"
  "Kan inte skriva filen"

  "Version:"
  "Version:"

}

# markers.tcl
msgcat::mcmset sv {

  "Marker name:"
  "Marker namn:"

}

# menus.tcl
msgcat::mcmset sv {

  "                                  Profiling Report Sorted By (%s)"
  "Profilering Rapport Sorterat efter (% s)"

  "About TKE"
  "Om TKE"

  "Align Cursors"
  "Justera markörer"

  "Append Next Occurrence"
  "Lägg nästa förekomst"

  "Auto-Indent"
  "Automatisk indentering"

  "Check for Update"
  "Leta efter uppdatering"

  "Clear All"
  "Avmarkera alla"

  "Close All"
  "Stäng alla"

  "Close Current"
  "Stäng aktuell flik"

  "Copy"
  "Kopiera"

  "Create New..."
  "Skapa ny"

  "Create at Current Line"
  "Skapa på aktuell rad"

  "Create..."
  "Skapa"

  "Cut"
  "Klipp ut"

  "Edit"
  "Ändra"

  "Edit Language"
  "Redigera språk"

  "Edit Menu Edit user snippets"
  "Redigera menyn Redigera användare snuttar"

  "Edit Menu: Copy text"
  "Redigera-menyn: Kopiera text"

  "Edit Menu: Cut text"
  "Redigera-menyn: Klipp ut text"

  "Edit Menu: Edit language snippets"
  "Redigera-menyn: Redigera språk snuttar"

  "Edit Menu: Edit session current language preferences"
  "Redigera-menyn: Redigera session aktuella språkinställningar"

  "Edit Menu: Edit session global preferences"
  "Redigera-menyn: Redigera globala inställningar för session"

  "Edit Menu: Edit user current language preferences"
  "Redigera-menyn: Redigera användarinställningar nuvarande språk"

  "Edit Menu: Edit user global preferences"
  "Redigera-menyn: Redigera globala användarinställningar"

  "Edit Menu: Edit user menu bindings"
  "Redigera-menyn: Redigera användaren menyn bindningar"

  "Edit Menu: Format all text"
  "Redigera-menyn: Formatera alla text"

  "Edit Menu: Format selected text"
  "Redigera-menyn: Formatera markerad text"

  "Edit Menu: Insert from clipboard"
  "Redigera-menyn: Infoga från Urklipp"

  "Edit Menu: Insert snippet"
  "Redigera-menyn: Infoga kodavsnittet"

  "Edit Menu: Paste and format text from clipboard"
  "Redigera-menyn: Klistra in och formatera text från Urklipp"

  "Edit Menu: Paste text from clipboard"
  "Redigera-menyn: Klistra in text från Urklipp"

  "Edit Menu: Redo"
  "Redigera-menyn: gör om"

  "Edit Menu: Reload snippets"
  "Redigera-menyn: Reload snuttar"

  "Edit Menu: Select all text"
  "Redigera-menyn: Markera all text"

  "Edit Menu: Set indent mode to IND"
  "Redigera-menyn: Ange indrag läge till IND"

  "Edit Menu: Set indent mode to IND+"
  "Redigera-menyn: Ange indrag läge till IND +"

  "Edit Menu: Set indent mode to OFF"
  "Redigera-menyn: Ange indrag läge off"

  "Edit Menu: Set user bindings to global bindings"
  "Redigera-menyn: Ange användaren bindningar till globala bindningar"

  "Edit Menu: Set user preferences to global preferences"
  "Redigera-menyn: Ange användarinställningar för att globala inställningar"

  "Edit Menu: Undo"
  "Redigera-menyn: ångra"

  "Edit Menu: View base preferences file"
  "Redigera-menyn: Visa bas inställningsfilen"

  "Edit Menu: View global menu bindings"
  "Redigera-menyn: Visa GLOBALMENU bindningar"

  "Edit Session - Global"
  "Redigera Session - Global"

  "Edit Session - Language"
  "Redigera Session - språk"

  "Edit User"
  "Redigera medlem"

  "Edit User - Global"
  "Redigera användare - Global"

  "Edit User - Language"
  "Redigera användare - språk"

  "Edit..."
  "Redigera..."

  "File"
  "File"

  "File Menu: Close all tabs"
  "Arkiv-menyn: Stäng alla flikar"

  "File Menu: Close current tab"
  "Arkiv-menyn: Nära ström tab"

  "File Menu: Favorite file"
  "Arkiv-menyn: Favorit-fil"

  "File Menu: Lock file"
  "Arkiv-menyn: Låsfil"

  "File Menu: New file"
  "Arkiv-menyn: Ny fil"

  "File Menu: Open Favorite"
  "Arkiv-menyn: Öppna favorit"

  "File Menu: Open Recent"
  "Arkiv Exportera"

  "File Menu: Open directory"
  "Arkiv-menyn: Open directory"

  "File Menu: Open file"
  "Arkiv-menyn: Öppna fil"

  "File Menu: Quit application"
  "Arkiv-menyn: Avsluta programmet"

  "File Menu: Save all files"
  "Arkiv-menyn: Spara alla filer"

  "File Menu: Save file"
  "Arkiv-menyn: Spara filen"

  "File Menu: Save file as"
  "Arkiv-menyn: Spara filen som"

  "File Menu: Show file difference"
  "Arkiv-menyn: Visar filen skillnad"

  "File Menu: Unfavorite file"
  "Arkiv-menyn: Unfavorite fil"

  "File Menu: Unlock file"
  "Arkiv-menyn: Låsa upp filen"

  "Find"
  "Sök i"

  "Find In Files"
  "Sök i filer..."

  "Find Matching Pair"
  "Hitta matchande par"

  "Find Menu: Append next occurrence"
  "Sök-menyn: Lägga till nästa förekomst"

  "Find Menu: Create marker at current line"
  "Sök-menyn: Skapa markör på aktuell rad"

  "Find Menu: Find"
  "Meny: hitta"

  "Find Menu: Find and Replace"
  "Sök-menyn: Söka och ersätta"

  "Find Menu: Find in files"
  "Sök-menyn: Hitta i filer"

  "Find Menu: Find matching character pair"
  "Sök-menyn: Hitta matchande tecken par"

  "Find Menu: Find next occurrence"
  "Sök-menyn: Hitta nästa förekomst"

  "Find Menu: Find previous occurrence"
  "Sök-menyn: Hitta föregående förekomst"

  "Find Menu: Goto next difference"
  "Sök-menyn: Gå till nästa skillnaden"

  "Find Menu: Goto previous difference"
  "Sök-menyn: Gå till föregående skillnad"

  "Find Menu: Jump backward"
  "Sök-menyn: Hoppa bakåt"

  "Find Menu: Jump forward"
  "Sök-menyn: Hoppa framåt"

  "Find Menu: Remove all markers"
  "Sök-menyn: Ta bort alla markörer"

  "Find Menu: Remove marker from current line"
  "Sök-menyn: Ta bort markör från aktuell rad"

  "Find Menu: Select all occurrences"
  "Sök-menyn: Markera alla förekomster"

  "Find Menu: Show selected line change"
  "Sök-menyn: Visa markerad linje förändring"

  "Find and Replace"
  "Sök och ersätt"

  "Format Text"
  "Formatera text"

  "From Clipboard"
  "Från Urklipp"

  "Goto Last Tab"
  "Goto Last Tab"

  "Goto Next Tab"
  "Gå till nästa flik"

  "Goto Other Pane"
  "Goto andra delfönstret"

  "Goto Previous Tab"
  "Gå till föregående flik"

  "Help"
  "Hjälp"

  "Help Menu: About TKE"
  "Hjälp-menyn: Om TKE"

  "Help Menu: Check for Update"
  "Hjälp-menyn: Leta efter uppdatering"

  "Help Menu: Send Bug Report"
  "Hjälp-menyn: Skicka felrapport"

  "Help Menu: Send Feedback"
  "Hjälp-menyn: Skicka Feedback"

  "Help Menu: View User Guide"
  "Hjälpmeny: Visa User Guide"

  "Hide Console"
  "Dölj konsol"

  "Hide Line Numbers"
  "Dölja radnummer"

  "Hide Meta Characters"
  "Dölja Meta tecken"

  "Hide Sidebar"
  "Dölj sidorad"

  "Hide Status Bar"
  "Dölj statusrad"

  "Hide Tab Bar"
  "Hide Tab Bar"

  "Import TextMate Theme..."
  "Importera TextMate tema..."

  "Indent"
  "Indrag"

  "Indent Mode"
  "Strecksatsen läge"

  "Indent Off"
  "Indrag av"

  "Insert Enumeration"
  "Infoga uppräkning"

  "Insert Text"
  "Infoga text"

  "Install..."
  "Installera"

  "Jump Backward"
  "Hoppa bakåt"

  "Jump Forward"
  "Hoppa framåt"

  "Launcher"
  "Launcher"

  "Lock"
  "Lock"

  "Markers"
  "Marker"

  "Menu Bindings"
  "Meny Bindningar"

  "Merge Panes"
  "Slå ihop fönsterrutorna"

  "Next Difference"
  "Nästa skillnad"

  "Open Directory..."
  "Öppna katalog"

  "Open Favorite"
  "Öppen Favoritspel"

  "Open File..."
  "Öppna fil..."

  "Open Recent"
  "Öppna senaste"

  "Paste"
  "limma"

  "Paste and Format"
  "Klistra in och format"

  "Plugins"
  "Insticksprogram"

  "Plugins Menu: Create new plugin"
  "Plugins-menyn: Skapa nya plugin"

  "Plugins Menu: Install plugin"
  "Plugins-menyn: Installera plugin"

  "Plugins Menu: Reload all plugins"
  "Plugins-menyn: Ladda alla plugins"

  "Plugins Menu: Uninstall plugin"
  "Plugins-menyn: Avinstallera plugin"

  "Preferences"
  "Favoriter"

  "Previous Difference"
  "Föregående skillnad"

  "Profiling started"
  "Profilering började"

  "Profiling stopped"
  "Profilering stoppad"

  "Quit"
  "% quit"

  "Redo"
  "Återställ"

  "Reload"
  "Ladda om"

  "Remove All Markers"
  "Ta bort alla markörer"

  "Remove From Current Line"
  "Ta bort från aktuell rad"

  "Replace Line With Script"
  "Ersätta Line med skriptet"

  "Reset User to Base"
  "Återställa användare till Base"

  "Restart TKE"
  "Starta om TKE"

  "Save All"
  "Spara allt"

  "Save As..."
  "Spara som"

  "Save Current"
  "Spara ström"

  "Select All"
  "Markera alla"

  "Select All Occurrences"
  "Markera alla förekomster"

  "Select Next Occurrence"
  "Markera nästa förekomst"

  "Select Previous Occurrence"
  "Markera föregående förekomst"

  "Selected"
  "Vald"

  "Send Bug Report"
  "Skicka felrapport."

  "Send Feedback"
  "Sänd feedback"

  "Sessions"
  "Sessioner"

  "Sessions Menu: Close current session"
  "Sessioner meny: Stäng nuvarande session"

  "Sessions Menu: Delete session"
  "Sessioner-menyn: Ta bort session"

  "Sessions Menu: Open session"
  "Sessioner meny: Öppen session"

  "Sessions Menu: Save current session"
  "Sessioner meny: Spara aktuell session"

  "Sessions Menu: Save sessions as"
  "Sessioner meny: Spara sessioner som"

  "Sessions Menu: Switch to session"
  "Sessioner Menu: Växla till session"

  "Set Syntax"
  "Ställ Syntax"

  "Set Theme"
  "Ställ tema"

  "Set User to Global"
  "Ställa in användare till Global"

  "Show Console"
  "Visa konsol"

  "Show Diagnostic Logfile"
  "Visa diagnostisk loggfil"

  "Show File Difference"
  "Visa filen skillnaden"

  "Show Last Profiling Report"
  "Visa Senaste Profilering Rapport"

  "Show Line Numbers"
  "Rad nummer"

  "Show Meta Characters"
  "Meta tecken visas"

  "Show Selected Line Change"
  "Visa markerad rad förändringar"

  "Show Sidebar"
  "Visa sidorad"

  "Show Status Bar"
  "Visa statusrad"

  "Show Tab Bar"
  "Visa Tab Bar"

  "Show*Profiling*"
  "Visa * Profilering *"

  "Smart Indent"
  "Smart strecksatsen"

  "Snippet"
  "Fragment"

  "Snippets"
  "Utdrag"

  "Sort Tabs"
  "Sort Tabs"

  "Split View"
  "Dela vy"

  "Start Profiling"
  "Börja Profilering"

  "Stop Profiling"
  "Stoppa Profilering"

  "Switch To"
  "Växla till"

  "Tabs"
  "Tabbar"

  "Text"
  "Text"

  "Text Menu: Align cursors"
  "Text-menyn: Justera markörer"

  "Text Menu: Indent selected text"
  "Text-menyn: Indrag markerad text"

  "Text Menu: Insert enumeration"
  "Text-menyn: Infoga uppräkning"

  "Text Menu: Replace line with script"
  "Text-menyn: Ersätta line med skriptet"

  "Text Menu: Toggle comment"
  "Text-menyn: Växla kommentar"

  "Text Menu: Unindent selected text"
  "Text-menyn: Ångra indrag av markerad text"

  "Theme Creator"
  "Theme Creator"

  "Toggle Comment"
  "Toggle kommentar"

  "Tools"
  "Verktyg"

  "Tools Menu: Create new theme"
  "Verktyg-menyn: Skapa nytt tema"

  "Tools Menu: Disable Vim mode"
  "Verktyg-menyn: Inaktivera Vim läge"

  "Tools Menu: Edit Tke theme"
  "Verktyg-menyn: Redigera Tke tema"

  "Tools Menu: Enable Vim mode"
  "Verktyg-menyn: Aktivera Vim-läge"

  "Tools Menu: Import TextMate theme"
  "Verktyg-menyn: Import TextMate tema"

  "Tools Menu: Restart tke"
  "Verktyg-menyn: Omstart tke"

  "Tools Menu: Show Diagnostic Logfile"
  "Verktyg-menyn: Visa diagnostisk loggfil"

  "Tools Menu: Show last profiling report"
  "Verktyg-menyn: Visar senaste profilering rapport"

  "Tools Menu: Start profiling"
  "Verktyg-menyn: Starta profilering"

  "Tools Menu: Stop profiling"
  "Verktyg-menyn: Stoppa profilering"

  "Undo"
  "Ord"

  "Unindent"
  "Unindent"

  "Uninstall..."
  "avinstallera"

  "Unlock"
  "Lås upp"

  "User Guide"
  "User Guide"

  "View"
  "Visa"

  "View Base"
  "Visa Base"

  "View Global"
  "Visa globala"

  "View Menu: Goto last tab"
  "Visa-menyn: Gå till sista fliken"

  "View Menu: Goto next tab"
  "Visa-menyn: Gå till nästa flik"

  "View Menu: Goto other pane"
  "Visa-menyn: Gå till annan fönsterruta"

  "View Menu: Goto previous tab"
  "Visa-menyn: Gå till föregående tab"

  "View Menu: Hide Line Numbers"
  "Visa-menyn: Dölja radnummer"

  "View Menu: Hide Tab Bar"
  "Visa-menyn: Dölja flikraden"

  "View Menu: Hide console"
  "Visa-menyn: Dölj konsolen"

  "View Menu: Hide meta characters"
  "Visa-menyn: Dölja meta tecken"

  "View Menu: Hide sidebar"
  "Visa-menyn: Dölj Sidpanelen"

  "View Menu: Hide status bar"
  "Visa-menyn: Dölja statusfältet"

  "View Menu: Merge panes"
  "Visa-menyn: Sammanfoga fönsterrutor"

  "View Menu: Move to other pane"
  "Visa-menyn: Flytta till andra"

  "View Menu: Show Line Numbers"
  "Visa-menyn: Visar radnummer"

  "View Menu: Show Tab Bar"
  "Visa-menyn: Visa flikfältet"

  "View Menu: Show console"
  "Visa-menyn: Visa konsolen"

  "View Menu: Show meta characters"
  "Visa-menyn: Visa meta tecken"

  "View Menu: Show sidebar"
  "Visa Förlaga"

  "View Menu: Show status bar"
  "Visa-menyn: Visa statusfält"

  "View Menu: Sort tabs"
  "Visa-menyn: Sort tabs"

  "View Menu: Toggle split view mode"
  "Visa-menyn: Växla split view-läge"

  "Vim Mode"
  "Vim Läge"

}

# plugins.tcl
msgcat::mcmset sv {

  "ERROR (%s,%s): %s"
  "FEL (%s, %s): %s"

  "ERROR:  Plugin name already exists"
  "FEL: Plugin namn finns redan"

  "ERROR:  Plugin name is not valid (only alphanumeric and underscores are allowed)"
  "FEL: Plugin namn är inte giltigt (endast alfanumeriska och understreck är tillåtna)"

  "ERROR:  Unable to create plugin directory"
  "FEL: Det går inte att skapa plugin katalog"

  "ERROR:  Unable to write plugin files"
  "FEL: Det går inte att skriva plugin-filer"

  "Enter plugin name"
  "Ange plugin namn"

  "Plugin %s installed"
  "Plugin% s installerad"

  "Plugin %s uninstalled"
  "Plugin% s avinstalle"

  "Plugin Errors"
  "Plugin fel"

  "Plugins successfully reloaded"
  "Insticksprogram framgångsrikt reloaded"

  "Syntax errors found in selected plugins"
  "Syntax fel i utvalda plugins"

}

# search.tcl
msgcat::mcmset sv {

  "%d substitutions done"
  "%d substitutioner gjort"

  "No files found in specified directories"
  "Inga filer Funna i angivna kataloger"

  "No search results found"
  "Inga sökresultat som hittade"

  "Search wrapped to beginning of file"
  "Sök insvept till början av filen"

  "Search wrapped to end of file"
  "Sök insvept till slutet av filen"

}

# sidebar.tcl
msgcat::mcmset sv {

  "Add Parent Directory"
  "Moderkatalog"

  "Close Directory Files"
  "Stäng Directory filer"

  "Copy Pathname"
  "Kopiera sökväg"

  "Delete directory?"
  "Radera katalog?"

  "Delete file?"
  "Ta bort"

  "Directory Name:"
  "namn i katalog"

  "Duplicate"
  "Duplicera"

  "File Name:"
  "Filnamn:"

  "Folder Name:"
  "Mappnamnet:"

  "Make Current Working Directory"
  "Gör aktuell katalog"

  "New Directory"
  "Ny katalog"

  "Open Directory Files"
  "Open Directory filer"

  "Refresh Directory Files"
  "Refresh register-filer"

  "Remove Parent from Sidebar"
  "Avlägsna Parent från sidofältet"

  "Remove from Sidebar"
  "Ta bort från sidofältet"

  "Rename"
  "Byt namn"

  "Show Difference"
  "Visa skillnaden"

}

# snippets.tcl
msgcat::mcmset sv {

  "Snippet: *"
  "Fragment: *"

}

# syntax.tcl
msgcat::mcmset sv {

  "Syntax error in %s.syntax file"
  "Syntax error in% s.syntax fil"

  "Syntax:  %s"
  "Syntax:% s"

  "Theme:  %s"
  "Tema:% s"

}

# themer.tcl
msgcat::mcmset sv {

  "Create"
  "Skapa"

  "Create New Theme"
  "Skapa nytt tema..."

  "Create custom"
  "Skapa anpassade"

  "ERROR:  Unable to read %s"
  "FEL: Det går inte att läsa% s"

  "ERROR:  Unable to write %s"
  "FEL: Kan inte skriva% s"

  "Edit theme"
  "Redigera tema"

  "Enter theme name"
  "Ange tema namn"

  "Error:  Theme is not a supported theme"
  "Fel: Tema är inte ett tema som stöds"

  "Import"
  "Importera"

  "Import TextMate Theme"
  "Import Textmate tema"

  "Name:"
  "Namn:"

  "OK"
  "OK"

  "Reset"
  "Återställ"

  "Select theme"
  "Välj temafil"

}

# tke.tcl
msgcat::mcmset sv {

  "Edit theme?"
  "Redigera tema?"

  "Import TextMate theme?"
  "Importerar Textmate tema?"

}

# tkedat.tcl
msgcat::mcmset sv {

  "Unable to open %s for reading"
  "Kan inte öppna%1 för läsning."

}

# vim.tcl
msgcat::mcmset sv {

  "File %s successfully written"
  "Filen %s har skrivit"

  "Filename %s already exists"
  "Filnamn %s finns redan"

}

# General
msgcat::mcmset sv {

  "All"
  "ALL"

  "Cancel"
  "Avbryt"

  "Close"
  "Stäng"

  "Delete"
  "Radera"

  "Favorite"
  "Gunstling"

  "Find:"
  "Sök i"

  "Move to Other Pane"
  "Flytta till andra Pane"

  "New File"
  "Ny fil"

  "Open"
  "Öppen"

  "Replace:"
  "Ersätt:"

  "Save"
  "Spara"

  "Save As"
  "Spara som..."

  "Unable to open %s for writing"
  "Kunde inte öppna%1 för skrivning"

  "Unfavorite"
  "Unfavorite"

}

