# api.tcl
msgcat::mcmset sv {

  "Argument list to api::add_file was not an even key/value pair"
  "Argument listan till api :: add_file var inte en ens nyckel / värde-par"

  "Plugin"
  "Tillägg"

}

# bgproc.tcl
msgcat::mcmset sv {

  "Unable to run system command"
  "Det går inte att köra systemet kommandot"

}

# diff.tcl
msgcat::mcmset sv {

  "    End: "
  "Slut:"

  "    Start: "
  "Start:"

  "Enter difference command"
  "Ange skillnaden kommando"

  "Enter starting file"
  "Ange start fil"

  "Update"
  "Uppdatera"

}

# edit.tcl
msgcat::mcmset sv {

  "File successfully written"
  "Arkivera lyckosam skrev"

  "Filename already exists"
  "Filnamn finns redan"

}

# embed_tke.tcl
msgcat::mcmset sv {

  "Find:"
  "Sök i"

  "Replace:"
  "Ersätt:"

}

# gui.tcl
msgcat::mcmset sv {

  "All"
  "ALL"

  "Case sensitivity"
  "Skiftlägeskänslighet"

  "Close All Tabs"
  "Stäng alla flikar"

  "Close Other Tabs"
  "Stäng övriga flikar"

  "Close Other*"
  "Stäng övriga flikar"

  "Close Tab"
  "Stäng flik"

  "Column"
  "Kolumn"

  "Copyright"
  "Copyright"

  "Delete tab?"
  "Radera flik?"

  "Developer"
  "Utvecklare"

  "Email"
  "Epost"

  "Error"
  "Fel"

  "Favorited"
  "Favorit"

  "File already exists.  Use '!' to force an overwrite"
  "Filen finns redan.  Använd '!' tvinga en överskrivning"

  "File attribute does not exist"
  "Filattributet finns inte"

  "File index is out of range"
  "File index är utanför intervallet"

  "Image displayed in fill-in forms which closes the form UI.  Used in forms such as search, search/replace, and find in files."
  "Bilden visas i fylla former som stänger formuläret UI.  Används i former som Sök, Sök/Ersätt och hitta i filer."

  "Image used in tab menus to indicate that the file is associated with a difference view."
  "Bilden används i fliken menyer för att ange att filen är associerad med en skillnad."

  "Image used in tab menus to indicate that the file is locked."
  "Bilden används i fliken menyer för att ange att filen är låst."

  "Image used in tab menus to indicate that the file is readonly."
  "Bilden används i fliken menyer för att ange att filen är skrivskyddad."

  "Image used in tab to indicate that the tab contains a difference view."
  "Bilden används i fliken för att ange att fliken innehåller en skillnad vy."

  "Image used in tab to indicate that the tab's file is readonly."
  "Bilden används i fliken för att ange att den fliken filen är skrivskyddad."

  "Image used in tab to indicate that the tab’s file is locked."
  "Bilden används i fliken för att ange att den fliken filen är låst."

  "Image used in tab which, when clicked, closes the tab."
  "Bilden används i fliken som, när du klickar på stänger fliken."

  "License"
  "Licens"

  "Line"
  "Linje"

  "Locked"
  "Spärrad"

  "Move"
  "Flytta"

  "Must be in multicursor mode to insert numbers"
  "Måste vara i multicursor läge infoga nummer"

  "No write permissions.  Use '!' to force write."
  "Ingen skrivbehörighet.  Använd '!' tvinga skriva."

  "Release Type"
  "Release typ"

  "Reload file?"
  "Ladda om filen"

  "Replace"
  "Ersätt"

  "Save request"
  "Spara begäran"

  "Show in Sidebar"
  "Show i Sidebar"

  "Starting number:"
  "Sidnummer för första sidan:"

  "Tcl/Tk Version"
  "Tcl/Tk Version"

  "Total Characters"
  "Totala tecken"

  "Total Lines"
  "Totala linjer"

  "Unable to successfully parse number string"
  "Inte att framgångsrikt parsa nummer sträng"

  "Unable to write file"
  "Kan inte skriva filen"

  "Version"
  "Version"

}

# markers.tcl
msgcat::mcmset sv {

  "Marker name:"
  "Marker namn:"

}

# menus.tcl
msgcat::mcmset sv {

  "About TKE"
  "Om TKE"

  "Absolute"
  "Grekland"

  "Align Cursors"
  "Justera markörer"

  "Append Next Occurrence"
  "Lägg nästa förekomst"

  "Auto-Indent"
  "Automatisk indentering"

  "Bubble Down"
  "Bubbla ner"

  "Bubble Up"
  "Bubbla upp"

  "Change Working Directory"
  "Ändra arbetar katalog"

  "Character"
  "Teckenattribut"

  "Check for Update"
  "Leta efter uppdatering"

  "Classic Mac"
  "Klassiska Mac"

  "Clear All"
  "Avmarkera alla"

  "Close All"
  "Stäng alla"

  "Close Current"
  "Stäng aktuell flik"

  "Command"
  "Kommando"

  "Command Result"
  "Kommandot resultatet"

  "Copy"
  "Kopiera"

  "Create"
  "Skapa"

  "Create at Current Line"
  "Skapa på aktuell rad"

  "Current Line"
  "Aktuell rad:"

  "Current Number"
  "Aktuellt radnummer"

  "Current Word"
  "Aktuella ord"

  "Cursor"
  "markör"

  "Cursor from Line Start"
  "Markören från linje Start"

  "Cursor to Line End"
  "Markören till linjens ände"

  "Cut"
  "Klipp ut"

  "Display Text Info"
  "Displayinformation"

  "Edit"
  "Ändra"

  "Edit Language"
  "Redigera språk"

  "Edit Menu Edit user snippets"
  "Redigera menyn Redigera användare snuttar"

  "Edit Menu: Align cursors"
  "Redigera-menyn: Justera markörer"

  "Edit Menu: Bubble lines down one line"
  "Redigera-menyn: Bubbla linjer en rad nedåt"

  "Edit Menu: Bubble lines up one line"
  "Redigera-menyn: Bubbla linjer upp en rad"

  "Edit Menu: Convert case to lower"
  "Redigera-menyn: Konvertera fall till lägre"

  "Edit Menu: Convert case to title"
  "Redigera-menyn: Konvertera fallet till titel"

  "Edit Menu: Convert case to upper"
  "Redigera-menyn: Konvertera fallet till övre"

  "Edit Menu: Copy text"
  "Redigera-menyn: Kopiera text"

  "Edit Menu: Cut text"
  "Redigera-menyn: Klipp ut text"

  "Edit Menu: Delete current line"
  "Redigera-menyn: Ta bort den aktuella raden"

  "Edit Menu: Delete current word"
  "Redigera-menyn: Ta bort aktuella ord"

  "Edit Menu: Delete from cursor to end of line"
  "Redigera-menyn: Ta bort från markören till slutet av raden"

  "Edit Menu: Delete from start of line to cursor"
  "Redigera-menyn: Ta bort från början av linje till markören"

  "Edit Menu: Delete template"
  "Redigera-menyn: Ta bort mallen"

  "Edit Menu: Delete text between character"
  "Redigera-menyn: Ta bort text mellan karaktär"

  "Edit Menu: Delete the current number"
  "Redigera-menyn: Ta bort aktuellt nummer"

  "Edit Menu: Delete the whitespace to left of cursor"
  "Redigera-menyn: Ta bort tomt utrymme till vänster om markören"

  "Edit Menu: Delete the whitespace to right of cursor"
  "Redigera-menyn: Ta bort whitespace till höger om markören"

  "Edit Menu: Edit language snippets"
  "Redigera-menyn: Redigera språk snuttar"

  "Edit Menu: Edit session current language preferences"
  "Redigera-menyn: Redigera session aktuella språkinställningar"

  "Edit Menu: Edit session global preferences"
  "Redigera-menyn: Redigera globala inställningar för session"

  "Edit Menu: Edit template"
  "Redigera-menyn: Redigera mall"

  "Edit Menu: Edit user current language preferences"
  "Redigera-menyn: Redigera användarinställningar nuvarande språk"

  "Edit Menu: Edit user global preferences"
  "Redigera-menyn: Redigera globala användarinställningar"

  "Edit Menu: Edit user menu bindings"
  "Redigera-menyn: Redigera användaren menyn bindningar"

  "Edit Menu: Format indentation for text"
  "Redigera-menyn: Format indrag för text"

  "Edit Menu: Indent selected text"
  "Redigera-menyn: Indrag markerad text"

  "Edit Menu: Insert command result after current line"
  "Redigera-menyn: Infoga kommandot resultatet efter aktuell rad"

  "Edit Menu: Insert file contents after current line"
  "Redigera-menyn: Infoga filen innehållet efter aktuell rad"

  "Edit Menu: Insert from clipboard"
  "Redigera-menyn: Infoga från Urklipp"

  "Edit Menu: Insert line above current line"
  "Redigera-menyn: Infoga rad ovanför aktuell rad"

  "Edit Menu: Insert line below current line"
  "Redigera-menyn: Infoga raden under aktuell rad"

  "Edit Menu: Insert snippet"
  "Redigera-menyn: Infoga kodavsnittet"

  "Edit Menu: Join lines"
  "Redigera-menyn: Kopplingslinjer"

  "Edit Menu: Move cursor to bottom of screen"
  "Redigera-menyn: Flytta markören till botten av skärmen"

  "Edit Menu: Move cursor to end of current line"
  "Redigera-menyn: Flytta markören till slutet av aktuell rad"

  "Edit Menu: Move cursor to first line"
  "Redigera-menyn: Flytta markören till första raden"

  "Edit Menu: Move cursor to last line"
  "Redigera-menyn: Flytta markören till sista raden"

  "Edit Menu: Move cursor to middle of screen"
  "Redigera-menyn: Flytta markören till mitten av skärmen"

  "Edit Menu: Move cursor to next page"
  "Redigera-menyn: Flytta markören till nästa sida"

  "Edit Menu: Move cursor to next word"
  "Redigera-menyn: Flytta markören till nästa ord"

  "Edit Menu: Move cursor to previous page"
  "Redigera-menyn: Flytta markören till föregående sida"

  "Edit Menu: Move cursor to previous word"
  "Redigera-menyn: Flytta markören till föregående ord"

  "Edit Menu: Move cursor to start of current line"
  "Redigera-menyn: Flytta markören till början av aktuell rad"

  "Edit Menu: Move cursor to top of screen"
  "Redigera-menyn: Flytta markören till toppen av skärmen"

  "Edit Menu: Move multicursors down one line"
  "Redigera-menyn: Flytta multicursors en rad nedåt"

  "Edit Menu: Move multicursors left one line"
  "Redigera-menyn: Flytta multicursors lämnade en rad"

  "Edit Menu: Move multicursors right one line"
  "Redigera-menyn: Flytta multicursors rätt en rad"

  "Edit Menu: Move multicursors up one line"
  "Redigera-menyn: Flytta multicursors en rad uppåt"

  "Edit Menu: Paste and format text from clipboard"
  "Redigera-menyn: Klistra in och formatera text från Urklipp"

  "Edit Menu: Paste text from clipboard"
  "Redigera-menyn: Klistra in text från Urklipp"

  "Edit Menu: Redo"
  "Redigera-menyn: gör om"

  "Edit Menu: Reload snippets"
  "Redigera-menyn: Reload snuttar"

  "Edit Menu: Reload template information"
  "Redigera-menyn: Ladda mallinformation"

  "Edit Menu: Replace line with script"
  "Redigera-menyn: Ersätta line med skriptet"

  "Edit Menu: Select all text"
  "Redigera-menyn: Markera all text"

  "Edit Menu: Set indent mode to IND"
  "Redigera-menyn: Ange indrag läge till IND"

  "Edit Menu: Set indent mode to IND+"
  "Redigera-menyn: Ange indrag läge till IND +"

  "Edit Menu: Set indent mode to OFF"
  "Redigera-menyn: Ange indrag läge off"

  "Edit Menu: Set user bindings to global bindings"
  "Redigera-menyn: Ange användaren bindningar till globala bindningar"

  "Edit Menu: Set user preferences to global preferences"
  "Redigera-menyn: Ange användarinställningar för att globala inställningar"

  "Edit Menu: Toggle case of current character"
  "Redigera-menyn: Växla fall av nuvarande karaktär"

  "Edit Menu: Toggle comment"
  "Redigera-menyn: Växla kommentar"

  "Edit Menu: Undo"
  "Redigera-menyn: ångra"

  "Edit Menu: Unindent selected text"
  "Redigera-menyn: Ångra indrag av markerad text"

  "Edit Menu: View base preferences file"
  "Redigera-menyn: Visa bas inställningsfilen"

  "Edit Menu: View global menu bindings"
  "Redigera-menyn: Visa GLOBALMENU bindningar"

  "Edit Session - Global"
  "Redigera Session - Global"

  "Edit Session - Language"
  "Redigera Session - språk"

  "Edit User"
  "Redigera medlem"

  "Edit User - Global"
  "Redigera användare - Global"

  "Edit User - Language"
  "Redigera användare - språk"

  "Enumeration"
  "räkning"

  "File"
  "File"

  "File Contents"
  "filinnehåll"

  "File Menu: Change working directory"
  "Arkiv-menyn: Ändra arbetskatalogen"

  "File Menu: Close all tabs"
  "Arkiv-menyn: Stäng alla flikar"

  "File Menu: Close current tab"
  "Arkiv-menyn: Nära ström tab"

  "File Menu: Delete current file"
  "Arkiv-menyn: Ta bort den aktuella filen"

  "File Menu: Duplicate current file"
  "Arkiv-menyn: Duplicera nuvarande fil"

  "File Menu: Favorite file"
  "Arkiv-menyn: Favorit-fil"

  "File Menu: Lock file"
  "Arkiv-menyn: Låsfil"

  "File Menu: New file"
  "Arkiv-menyn: Ny fil"

  "File Menu: New file from template"
  "Arkiv-menyn: Ny fil från mall"

  "File Menu: New window"
  "Arkiv-menyn: Nytt fönster"

  "File Menu: Open Favorite"
  "Arkiv-menyn: Öppna favorit"

  "File Menu: Open Recent"
  "Arkiv Exportera"

  "File Menu: Open directory"
  "Arkiv-menyn: Open directory"

  "File Menu: Open file"
  "Arkiv-menyn: Öppna fil"

  "File Menu: Quit application"
  "Arkiv-menyn: Avsluta programmet"

  "File Menu: Rename current file"
  "Arkiv-menyn: Byta namn på nuvarande fil"

  "File Menu: Reopen current file"
  "Arkiv-menyn: Återuppta nuvarande fil"

  "File Menu: Save all files"
  "Arkiv-menyn: Spara alla filer"

  "File Menu: Save file"
  "Arkiv-menyn: Spara filen"

  "File Menu: Save file as"
  "Arkiv-menyn: Spara filen som"

  "File Menu: Save file as template"
  "Arkiv-menyn: Spara som mall"

  "File Menu: Save selected lines"
  "Arkiv-menyn: Spara markerade rader"

  "File Menu: Set current file line ending to CR for Classic Mac"
  "Arkiv-menyn: Ange nuvarande fil linje slutar till CR för klassiska Mac"

  "File Menu: Set current file line ending to CRLF for Windows"
  "Arkiv-menyn: Ange nuvarande fil rader som slutar med CRLF för Windows"

  "File Menu: Set current file line ending to LF for Unix"
  "Arkiv-menyn: Ange nuvarande fil linje slutar att LF för Unix"

  "File Menu: Show file difference"
  "Arkiv-menyn: Visar filen skillnad"

  "File Menu: Unfavorite file"
  "Arkiv-menyn: Unfavorite fil"

  "File Menu: Unlock file"
  "Arkiv-menyn: Låsa upp filen"

  "Find In Files"
  "Sök i filer..."

  "Find Matching Pair"
  "Hitta matchande par"

  "Find Menu: Append next occurrence"
  "Sök-menyn: Lägga till nästa förekomst"

  "Find Menu: Create marker at current line"
  "Sök-menyn: Skapa markör på aktuell rad"

  "Find Menu: Find"
  "Meny: hitta"

  "Find Menu: Find and Replace"
  "Sök-menyn: Söka och ersätta"

  "Find Menu: Find in files"
  "Sök-menyn: Hitta i filer"

  "Find Menu: Find matching character pair"
  "Sök-menyn: Hitta matchande tecken par"

  "Find Menu: Find next occurrence"
  "Sök-menyn: Hitta nästa förekomst"

  "Find Menu: Find previous occurrence"
  "Sök-menyn: Hitta föregående förekomst"

  "Find Menu: Goto next difference"
  "Sök-menyn: Gå till nästa skillnaden"

  "Find Menu: Goto previous difference"
  "Sök-menyn: Gå till föregående skillnad"

  "Find Menu: Jump backward"
  "Sök-menyn: Hoppa bakåt"

  "Find Menu: Jump forward"
  "Sök-menyn: Hoppa framåt"

  "Find Menu: Jump to line"
  "Sök-menyn: Hoppa till rad"

  "Find Menu: Remove all markers"
  "Sök-menyn: Ta bort alla markörer"

  "Find Menu: Remove marker from current line"
  "Sök-menyn: Ta bort markör från aktuell rad"

  "Find Menu: Select all occurrences"
  "Sök-menyn: Markera alla förekomster"

  "Find Menu: Show selected line change"
  "Sök-menyn: Visa markerad linje förändring"

  "Find and Replace"
  "Sök och ersätt"

  "Format Text"
  "Formatera text"

  "From Clipboard"
  "Från Urklipp"

  "Goto Last Tab"
  "Goto Last Tab"

  "Goto Next Tab"
  "Gå till nästa flik"

  "Goto Other Pane"
  "Goto andra delfönstret"

  "Goto Previous Tab"
  "Gå till föregående flik"

  "Help"
  "Hjälp"

  "Help Menu: About TKE"
  "Hjälp-menyn: Om TKE"

  "Help Menu: Check for update"
  "Hjälp-menyn: Leta efter uppdatering"

  "Help Menu: Send bug report"
  "Hjälp-menyn: Skicka felrapport"

  "Help Menu: Send feedback"
  "Hjälp-menyn: Skicka feedback"

  "Help Menu: View user guide"
  "Hjälpmeny: Visa användarhandboken"

  "Hide Console"
  "Dölj konsol"

  "Hide Line Numbers"
  "Dölja radnummer"

  "Hide Marker Map"
  "Dölja markörkarta"

  "Hide Meta Characters"
  "Dölja Meta tecken"

  "Hide Sidebar"
  "Dölj sidorad"

  "Hide Status Bar"
  "Dölj statusrad"

  "Hide Tab Bar"
  "Hide Tab Bar"

  "Indent"
  "Indrag"

  "Indent Off"
  "Indrag av"

  "Indentation"
  "Indentering"

  "Insert"
  "Infoga"

  "Install"
  "Installera"

  "Join Lines"
  "Kombinera rader"

  "Jump Backward"
  "Hoppa bakåt"

  "Jump Forward"
  "Hoppa framåt"

  "Jump To Line"
  "Hoppa till rad"

  "Launcher"
  "Launcher"

  "Line Above Current"
  "Linje ovanför aktuell"

  "Line Below Current"
  "Rad under nuvarande"

  "Line Ending"
  "Linje som slutar"

  "Line Number"
  "radnummer"

  "Line Numbering"
  "Radnumrering"

  "Lock"
  "Lock"

  "Lower Case"
  "Små bokstäver"

  "Markers"
  "Marker"

  "Menu Bindings"
  "Meny Bindningar"

  "Menus: About TKE"
  "Menyer: Om TKE"

  "Merge Panes"
  "Slå ihop fönsterrutorna"

  "Move Cursors Down"
  "Flytta markören nedåt"

  "Move Cursors Left"
  "Flytta markören åt vänster"

  "Move Cursors Right"
  "Flytta markören höger"

  "Move Cursors Up"
  "Flytta markören upp"

  "Move to First Line"
  "Flytta till första raden"

  "Move to Last Line"
  "Flytta till sista raden"

  "Move to Line End"
  "Flytta till slutet"

  "Move to Line Start"
  "Flytta till linje Start"

  "Move to Next Page"
  "Flytta till nästa sida"

  "Move to Next Word"
  "Flytta till nästa ord"

  "Move to Previous Page"
  "Flytta till föregående sida"

  "Move to Previous Word"
  "Flytta till föregående ord"

  "Move to Screen Bottom"
  "Jag flytta skärmen botten"

  "Move to Screen Middle"
  "Jag flytta skärmen mitten"

  "Move to Screen Top"
  "Jag flytta skärmen topp"

  "New From Template"
  "Ny från mall"

  "New Window"
  "Nytt fönster"

  "Next Difference"
  "Nästa skillnad"

  "Open Directory"
  "Öppna katalog"

  "Open Favorite"
  "Öppen Favoritspel"

  "Open File"
  "Öppna fil"

  "Open Recent"
  "Öppna senaste"

  "Paste"
  "limma"

  "Paste and Format"
  "Klistra in och format"

  "Plugins"
  "Insticksprogram"

  "Plugins Menu: Create new plugin"
  "Plugins-menyn: Skapa nya plugin"

  "Plugins Menu: Install plugin"
  "Plugins-menyn: Installera plugin"

  "Plugins Menu: Reload all plugins"
  "Plugins-menyn: Ladda alla plugins"

  "Plugins Menu: Uninstall plugin"
  "Plugins-menyn: Avinstallera plugin"

  "Preferences"
  "Favoriter"

  "Previous Difference"
  "Föregående skillnad"

  "Profiling Report Sorted By"
  "Profilering rapporten sorterade efter"

  "Profiling started"
  "Profilering började"

  "Profiling stopped"
  "Profilering stoppad"

  "Quit"
  "% quit"

  "Redo"
  "Återställ"

  "Relative"
  "Relativ"

  "Reload"
  "Ladda om"

  "Remove All Markers"
  "Ta bort alla markörer"

  "Remove From Current Line"
  "Ta bort från aktuell rad"

  "Reopen File"
  "Öppnar filen igen"

  "Replace Line With Script"
  "Ersätta Line med skriptet"

  "Reset User to Base"
  "Återställa användare till Base"

  "Restart TKE"
  "Starta om TKE"

  "Run BIST"
  "Köra BIST"

  "Save All"
  "Spara allt"

  "Save As Template"
  "Spara som mall"

  "Save Current"
  "Spara ström"

  "Save Selection As"
  "Spara markering som"

  "Select All"
  "Markera alla"

  "Select All Occurrences"
  "Markera alla förekomster"

  "Select Next Occurrence"
  "Markera nästa förekomst"

  "Select Previous Occurrence"
  "Markera föregående förekomst"

  "Send Bug Report"
  "Skicka felrapport."

  "Send Feedback"
  "Sänd feedback"

  "Sessions"
  "Sessioner"

  "Sessions Menu: Close current session"
  "Sessioner meny: Stäng nuvarande session"

  "Sessions Menu: Delete session"
  "Sessioner-menyn: Ta bort session"

  "Sessions Menu: Save current session"
  "Sessioner meny: Spara aktuell session"

  "Sessions Menu: Save sessions as"
  "Sessioner meny: Spara sessioner som"

  "Sessions Menu: Switch to session"
  "Sessioner Menu: Växla till session"

  "Set Syntax"
  "Ställ Syntax"

  "Set Theme"
  "Ställ tema"

  "Set User to Global"
  "Ställa in användare till Global"

  "Show Console"
  "Visa konsol"

  "Show Diagnostic Logfile"
  "Visa diagnostisk loggfil"

  "Show File Difference"
  "Visa filen skillnaden"

  "Show Last Profiling Report"
  "Visa Senaste Profilering Rapport"

  "Show Line Numbers"
  "Rad nummer"

  "Show Marker Map"
  "Visa markörkarta"

  "Show Meta Characters"
  "Meta tecken visas"

  "Show Selected Line Change"
  "Visa markerad rad förändringar"

  "Show Sidebar"
  "Visa sidorad"

  "Show Status Bar"
  "Visa statusrad"

  "Show Tab Bar"
  "Visa Tab Bar"

  "Smart Indent"
  "Smart strecksatsen"

  "Snippet"
  "Fragment"

  "Snippets"
  "Utdrag"

  "Sort Tabs"
  "Sort Tabs"

  "Start Profiling"
  "Börja Profilering"

  "Stop Profiling"
  "Stoppa Profilering"

  "Switch To"
  "Växla till"

  "Tabs"
  "Tabbar"

  "Templates"
  "Mallar"

  "Text Between Character"
  "Text mellan karaktär"

  "Text Menu: Insert enumeration"
  "Text-menyn: Infoga uppräkning"

  "Title Case"
  "Alltid stor begynnelsebokstav"

  "Toggle Case"
  "Växla skiftläge"

  "Toggle Comment"
  "Toggle kommentar"

  "Tools"
  "Verktyg"

  "Tools Menu: Disable Vim mode"
  "Verktyg-menyn: Inaktivera Vim läge"

  "Tools Menu: Enable Vim mode"
  "Verktyg-menyn: Aktivera Vim-läge"

  "Tools Menu: Restart TKE"
  "Verktyg-menyn: Omstart TKE"

  "Tools Menu: Run BIST"
  "Verktyg-menyn: Kör BIST"

  "Tools Menu: Run theme editor"
  "Verktyg-menyn: Kör tema redaktör"

  "Tools Menu: Show diagnostic logfile"
  "Verktyg-menyn: Visa diagnostisk loggfil"

  "Tools Menu: Show last profiling report"
  "Verktyg-menyn: Visar senaste profilering rapport"

  "Tools Menu: Start profiling"
  "Verktyg-menyn: Starta profilering"

  "Tools Menu: Stop profiling"
  "Verktyg-menyn: Stoppa profilering"

  "Transform"
  "transformera"

  "Undo"
  "Ord"

  "Unindent"
  "Unindent"

  "Uninstall"
  "Avinstallera"

  "Unix"
  "Unix"

  "Unlock"
  "Lås upp"

  "Upper Case"
  "Stora bokstäver"

  "User Guide"
  "User Guide"

  "View"
  "Visa"

  "View Base"
  "Visa Base"

  "View Global"
  "Visa globala"

  "View Menu: Absolute line numbering"
  "Visa-menyn: Absolut radnumrering"

  "View Menu: Display text information"
  "Visa-menyn: Visar textinformation"

  "View Menu: Goto last tab"
  "Visa-menyn: Gå till sista fliken"

  "View Menu: Goto next tab"
  "Visa-menyn: Gå till nästa flik"

  "View Menu: Goto other pane"
  "Visa-menyn: Gå till annan fönsterruta"

  "View Menu: Goto previous tab"
  "Visa-menyn: Gå till föregående tab"

  "View Menu: Hide console"
  "Visa-menyn: Dölj konsolen"

  "View Menu: Hide line numbers"
  "Visa-menyn: Dölja radnummer"

  "View Menu: Hide marker map"
  "Visa-menyn: Dölja markörkarta"

  "View Menu: Hide meta characters"
  "Visa-menyn: Dölja meta tecken"

  "View Menu: Hide sidebar"
  "Visa-menyn: Dölj Sidpanelen"

  "View Menu: Hide status bar"
  "Visa-menyn: Dölja statusfältet"

  "View Menu: Hide tab bar"
  "Visa-menyn: Dölja flikraden"

  "View Menu: Merge panes"
  "Visa-menyn: Sammanfoga fönsterrutor"

  "View Menu: Move to other pane"
  "Visa-menyn: Flytta till andra"

  "View Menu: Relative line numbering"
  "Visa-menyn: Relativa radnumrering"

  "View Menu: Show console"
  "Visa-menyn: Visa konsolen"

  "View Menu: Show line numbers"
  "Visa-menyn: Visar radnummer"

  "View Menu: Show marker map"
  "Visa-menyn: Visar markörkarta"

  "View Menu: Show meta characters"
  "Visa-menyn: Visa meta tecken"

  "View Menu: Show sidebar"
  "Visa Förlaga"

  "View Menu: Show status bar"
  "Visa-menyn: Visa statusfält"

  "View Menu: Show tab bar"
  "Visa-menyn: Visa flikfältet"

  "View Menu: Sort tabs"
  "Visa-menyn: Sort tabs"

  "View Menu: Toggle split view mode"
  "Visa-menyn: Växla split view-läge"

  "Vim Mode"
  "Vim Läge"

  "Whitespace Backward"
  "Whitespace bakåt"

  "Whitespace Forward"
  "Whitespace framåt"

  "Windows"
  "Windows"

}

# plugins.tcl
msgcat::mcmset sv {

  "Always grant from developer"
  "Bevilja alltid från utvecklaren"

  "ERROR"
  "FEL"

  "ERROR:  Plugin name already exists"
  "FEL: Plugin namn finns redan"

  "ERROR:  Plugin name is not valid (only alphanumeric and underscores are allowed)"
  "FEL: Plugin namn är inte giltigt (endast alfanumeriska och understreck är tillåtna)"

  "ERROR:  Unable to create plugin directory"
  "FEL: Det går inte att skapa plugin katalog"

  "ERROR:  Unable to write plugin files"
  "FEL: Det går inte att skriva plugin-filer"

  "Enter plugin name"
  "Ange plugin namn"

  "Grant"
  "Grant"

  "Grant permssion?"
  "Grant permssion?"

  "OK"
  "OK"

  "Plugin Errors"
  "Plugin fel"

  "Plugin Trust Requested"
  "Plugin Förtroende Begärd"

  "Plugin installed"
  "Plugin installerat"

  "Plugin requires permission to view or modify your system."
  "Plugin kräver tillstånd för att visa eller ändra ditt system."

  "Plugin uninstalled"
  "Plugin avinstalleras"

  "Plugins successfully reloaded"
  "Insticksprogram framgångsrikt reloaded"

  "Reject"
  "Avvisa"

  "Syntax errors found in selected plugins"
  "Syntax fel i utvalda plugins"

}

# search.tcl
msgcat::mcmset sv {

  "No files found in specified directories"
  "Inga filer Funna i angivna kataloger"

  "No search results found"
  "Inga sökresultat som hittade"

  "Search wrapped to beginning of file"
  "Sök insvept till början av filen"

  "Search wrapped to end of file"
  "Sök insvept till slutet av filen"

  "substitutions done"
  "substitutioner gjort"

}

# sessions.tcl
msgcat::mcmset sv {

  "Save session?"
  "Spara session?"

  "Session state will be lost if not saved"
  "Sessionstillstånd går förlorad om inte sparats"

}

# sidebar.tcl
msgcat::mcmset sv {

  "Add Parent Directory"
  "Moderkatalog"

  "Close Directory Files"
  "Stäng Directory filer"

  "Copy Pathname"
  "Kopiera sökväg"

  "Delete directories?"
  "Ta bort kataloger?"

  "Delete directory?"
  "Radera katalog?"

  "Delete file?"
  "Ta bort"

  "Delete files?"
  "Ta bort filer"

  "Directory Name:"
  "namn i katalog"

  "Folder Name:"
  "Mappnamnet:"

  "Image displayed in sidebar to indicate that a file is currently opened in an editing buffer."
  "Bild som visas i sidofältet som anger att en fil för närvarande öppnas i en redigering buffert."

  "Make Current Working Directory"
  "Gör aktuell katalog"

  "New Directory"
  "Ny katalog"

  "New File From Template"
  "Ny från mall"

  "Open Directory Files"
  "Open Directory filer"

  "Refresh Directory Files"
  "Refresh register-filer"

  "Remove Parent from Sidebar"
  "Avlägsna Parent från sidofältet"

  "Remove from Sidebar"
  "Ta bort från sidofältet"

  "Show Difference"
  "Visa skillnaden"

}

# snippets.tcl
msgcat::mcmset sv {

  "Snippet: *"
  "Fragment: *"

}

# syntax.tcl
msgcat::mcmset sv {

  "Syntax"
  "Syntax"

  "Syntax error in syntax file"
  "Syntaxfel i syntax filen"

}

# templates.tcl
msgcat::mcmset sv {

  "Template"
  "Mall"

  "Template Name"
  "Mallnamn"

  "deleted"
  "borttagen"

  "saved"
  "sparad"

}

# theme.tcl
msgcat::mcmset sv {

  "Background (trough) color used in the sidebar scrollbar."
  "Bakgrundsfärg (tråg) används i sidofältet rullningslisten."

  "Background (trough) color used in the text scrollbars."
  "Bakgrundsfärg (tråg) används i text scrollbars."

  "Background color for all sidebar items that are not selected."
  "Bakgrundsfärgen för alla sidofältet objekt som inte är markerade."

  "Background color for all sidebar items that are selected."
  "Bakgrundsfärgen för alla sidofältet objekt som är markerade."

  "Background color in difference viewer that shows added lines."
  "Bakgrundsfärg i skillnaden viewer som visar lagt till rader."

  "Background color in difference viewer that shows deleted lines."
  "Bakgrundsfärg i skillnaden viewer som visar bort linjer."

  "Background color of insertion cursor and background marker colors."
  "Bakgrundsfärg på insättningspunkten och bakgrundsmarkeringsfärger."

  "Background color of the editing buffer."
  "Bakgrundsfärgen på redigering bufferten."

  "Background color to display when a button-like ttk widget is pressed."
  "Bakgrundsfärgen visas när du trycker på en knapp-liknande ttk widget."

  "Background color to use for selected text."
  "Bakgrundsfärgen för markerad text."

  "Background color used for all other tabs that are not the current/active tab in the tabbar."
  "Bakgrundsfärgen används för alla andra flikar som inte fliken ström/aktiv i tabbar."

  "Background color used for the current/active menu item."
  "Bakgrundsfärgen används för ström/aktiv menyalternativet."

  "Background color used for the current/active tab in the tabbar."
  "Bakgrundsfärgen för fliken ström/aktiv i tabbar."

  "Background color used in highlighted text."
  "Bakgrundsfärgen används i markerad text."

  "Background color used in menus."
  "Bakgrundsfärgen används i menyer."

  "Background color used in the tabbar area."
  "Bakgrundsfärgen används i området tabbar."

  "Color of border drawn around active editing buffer."
  "Färgen på gränsen dras runt aktiv redigering buffert."

  "Color of ttk entry widget text border when the entry has keyboard focus."
  "Färgen på ttk posten widget text kantlinje när transaktionen har tangentbordsfokus."

  "Color used to draw the warning width line in the editing buffer (as well as the line separating the gutter from the editing buffer)."
  "Färgen används för att rita linjen varning bredd i redigering bufferten (liksom linjen som skiljer rännstenen från redigering bufferten)."

  "Default 'darkcolor' for all ttk widgets."
  "Standard \"

  "Default background color to use for all ttk widgets that are in a disabled state."
  "Standardbakgrundsfärgen för alla ttk widgets som är i ett inaktiverat tillstånd."

  "Default background color to use for all ttk widgets when the mouse cursor hovers over the widget."
  "Standard bakgrundsfärg att använda för alla ttk widgets när muspekaren för muspekaren över widgeten."

  "Default background color to use for all ttk widgets."
  "Standardbakgrundsfärgen för alla ttk widgets."

  "Default border color for all ttk widgets."
  "Standard Kantfärg för alla ttk widgets."

  "Default color for non-syntax highlighted text."
  "Standardfärgen för icke-syntax markerad text."

  "Default foreground text color to use for all ttk widgets that are in a disabled state."
  "Standard text förgrundsfärgen för alla ttk widgets som är i ett inaktiverat tillstånd."

  "Default foreground text color to use for all ttk widgets."
  "Standard text förgrundsfärgen för alla ttk widgets."

  "Determines the number of grips strips to display in the grip area between resizable panes."
  "Bestämmer hur många grepp remsorna ska visas i området grepp mellan resizable fönster."

  "Determines the thickness of the grip area between resizable panes."
  "Bestämmer tjockleken på området grepp mellan resizable fönster."

  "ERROR:  Unable to read"
  "FEL: Det gick inte att läsa"

  "Foreground (slider) color used in the sidebar scrollbar."
  "Förgrundsfärgen (reglaget) används i sidofältet rullningslisten."

  "Foreground (slider) color used in the text scrollbars."
  "Förgrundsfärgen (reglaget) används i text scrollbars."

  "Foreground color used in menu items with checks or buttons."
  "Förgrundsfärgen används i menypunkterna med kontroller eller knappar."

  "Foreground text color for strings."
  "Förgrundsfärgen text för strängar."

  "Foreground text color to use for all miscellaneous1 labeled text."
  "Förgrundsfärgen text att använda för alla miscellaneous1 märkt text."

  "Foreground text color to use for all miscellaneous2 labeled text."
  "Förgrundsfärgen text att använda för alla miscellaneous2 märkt text."

  "Foreground text color to use for all miscellaneous3 labeled text."
  "Förgrundsfärgen text att använda för alla miscellaneous3 märkt text."

  "Foreground text color to use for comments."
  "Förgrundsfärgen text att använda för kommentarer."

  "Foreground text color to use for displaying line numbers."
  "Förgrundsfärgen text att använda för att Visa radnummer."

  "Foreground text color to use for displaying numbers."
  "Förgrundsfärgen text att använda för att visa numren."

  "Foreground text color to use for language-specific keywords."
  "Förgrundsfärgen text att använda för språkspecifika sökord."

  "Foreground text color to use for language-specific punctuation."
  "Förgrundsfärgen text att använda för språkspecifika skiljetecken."

  "Foreground text color to use for meta syntax."
  "Förgrundsfärgen text att använda meta syntax."

  "Foreground text color to use for precompiler syntax."
  "Förgrundsfärgen text att använda för förkompilator syntax."

  "Foreground text color to use for selected text."
  "Förgrundsfärgen text ska användas för markerad text."

  "Foreground text color used for all other tabs that are not the current/active tab in the tabbar."
  "Text Förgrundsfärgen används för alla andra flikar som inte fliken ström/aktiv i tabbar."

  "Foreground text color used for menus item that are disabled."
  "Text Förgrundsfärgen används för menyer som är inaktiverade."

  "Foreground text color used for the current/active menu item."
  "Text Förgrundsfärgen används för ström/aktiv menyalternativet."

  "Foreground text color used for the current/active tab in the tabbar."
  "Text Förgrundsfärgen används för fliken ström/aktiv i tabbar."

  "Foreground text color used in menus."
  "Förgrundsfärgen text som används i menyer."

  "Foreground text/image color used in tabbar and tabs."
  "Text/bild Förgrundsfärgen används i flikarna och tabbar."

  "Images"
  "Bilder"

  "Maximum thickness of the text scrollbar when it is active."
  "Maximal tjocklek text rullningslisten när det är aktivt."

  "Maximum thickness of the text scrollbars when they are active."
  "Största tjocklek av scrollbarsna text när de är aktiva."

  "Menu Options"
  "Menyalternativ"

  "Menu relief value."
  "Menyn lättnad värde."

  "Pixel height of the tabbar widget."
  "Pixelhöjd för widgeten tabbar."

  "Relief used in drawing the tabs."
  "Lättnad i ritning flikarna."

  "Relief value of the sidebar area."
  "Lättnad värdet av sidofältet området."

  "Sidebar Options"
  "Sidopanelens alternativ"

  "Sidebar Scrollbar Options"
  "Sidebar Scrollbar Alternativ"

  "Specifies the color to display around the sidebar when the sidebar does not have the focus."
  "Anger färgen ska visas runt bufferten när sidofältet inte har fokus."

  "Specifies the color to display around the sidebar when the sidebar has the focus."
  "Anger färgen ska visas runt bufferten när sidofältet är i fokus."

  "Specifies the default background color to use for text that is selected in a standard ttk widget (this does not include the editing buffer)."
  "Anger standardbakgrundsfärgen ska användas för text som är markerad i en standard ttk widget (detta inte omfattar redigering bufferten)."

  "Specifies the default foreground text color to use for text that is selected in a standard ttk widget (this does not include the editing buffer)."
  "Anger standard förgrundsfärgen text ska användas för text som är markerad i en standard ttk widget (detta inte omfattar redigering bufferten)."

  "Specifies the default relief to use when drawing ttk widgets."
  "Anger befrielsen som standard att använda när du ritar ttk widgets."

  "Specifies the disclosure image style to use in the sidebar."
  "Anger den avslöjande bild stilen att använda i sidofältet."

  "Specifies the pixel thickness of the highlight line."
  "Anger pixel tjocklek Markera raden."

  "Syntax Colors"
  "Syntax Färger"

  "Tab Options"
  "Flik Alternativ"

  "Text Scrollbar Options"
  "Text scrollbar Alternativ"

  "Text color for all sidebar items that are not selected."
  "Textfärg för alla sidofältet objekt som inte är markerade."

  "Text color for all sidebar items that are selected."
  "Textfärg för alla sidofältet objekt som är markerade."

  "ttk Widget Colors"
  "TTK Widget Färger"

}

# themer.tcl
msgcat::mcmset sv {

  "   Show All"
  "Visa alla"

  "   Show Category"
  "Show Category"

  "   Show Color"
  "Visa Color"

  "   Show Selected Option"
  "Visa valda alternativet"

  "   Show Selected Value"
  "Visa valt värde"

  "Categories"
  "Nyhetsarkiv"

  "Change Base Color"
  "Byt Base Färg"

  "Choose Theme"
  "Välj ett tema"

  "Custom Directory"
  "Custom Directory"

  "Custom..."
  "Anpassad..."

  "Delete swatch?"
  "Radera swatch?"

  "Description"
  "Beskrivning"

  "Details"
  "Visa ”Detaljer” knappen"

  "Done"
  "Klar"

  "Export"
  "Exportera"

  "GIF Photo"
  "GIF-bild"

  "Import"
  "Importera"

  "Import BMP Data"
  "Importera BMP data"

  "Import BMP Mask"
  "Importera BMP maskerar"

  "Import Error"
  "Fel vid import"

  "Import Theme File"
  "Import temafil"

  "Installation Directory"
  "Installationskatalog"

  "Modifications"
  "Ändringar"

  "One-Color Bitmap"
  "Enfärgs Bitmap"

  "Preview"
  "Förhandsgranska"

  "Relief: "
  "understöd"

  "Save As:"
  "Spara som"

  "Save theme changes?"
  "Spara tema ändringar?"

  "Select Directory"
  "Välj katalog"

  "Swatch"
  "Swatch"

  "Swatch Colors"
  "Swatch Färger"

  "Table Filters"
  "Tabell Filter"

  "The current theme has unsaved changes"
  "Det aktuella temat har osparade ändringar"

  "Tree Style: "
  "Träd Stil:"

  "Two-Color Bitmap"
  "Två-Color Bitmap"

  "User Directory"
  "Användarkatalog"

  "Value"
  "Värde"

  "Value: "
  "Värde"

}

# themes.tcl
msgcat::mcmset sv {

  "Theme"
  "Tema"

  "Theme:*"
  "Tema"

}

# tke.tcl
msgcat::mcmset sv {

  "Import TKE theme?"
  "Import TKE tema?"

  "Import TextMate theme?"
  "Importerar Textmate tema?"

}

# tkedat.tcl
msgcat::mcmset sv {

  "Unable to read"
  "Kan inte läsa fil."

}

# vim.tcl
msgcat::mcmset sv {

  "File format unrecognized"
  "Okänt filformat"

  "Filename directory does not exist"
  "Filnamn katalogen finns inte"

  "Illegal modelines value"
  "Olagliga lägesrader värde"

  "Shiftwidth value is not an integer"
  "Shiftwidth värde är inte ett heltal"

  "Tabstop value is not an integer"
  "Tabbstopp värdet är inte ett heltal"

}

# General
msgcat::mcmset sv {

  "Cancel"
  "Avbryt"

  "Close"
  "Stäng"

  "Delete"
  "Radera"

  "Duplicate"
  "Duplicera"

  "Favorite"
  "Gunstling"

  "File Name:"
  "Filnamn:"

  "Find"
  "Sök i"

  "Move to Other Pane"
  "Flytta till andra Pane"

  "New File"
  "Ny fil"

  "None"
  "Ingen"

  "Open"
  "Öppen"

  "Rename"
  "Byt namn"

  "Save"
  "Spara"

  "Save As"
  "Spara som..."

  "Split View"
  "Dela vy"

  "Theme Editor"
  "Temaredigeraren"

  "Unable to write"
  "Kan inte skriva"

  "Unfavorite"
  "Unfavorite"

}

