# api.tcl
msgcat::mcmset sv {

  "Argument list to api::add_file was not an even key/value pair"
  "Argument listan till api :: add_file var inte en ens nyckel / värde-par"

}

# bgproc.tcl
msgcat::mcmset sv {

  "Unable to run system command (%s)"
  "Det går inte att köra systemet kommandot (% s)"

}

# gui.tcl
msgcat::mcmset sv {

  "%s, Line: %d, Column: %d"
  "% S, Rad:% d, Kolumn:% d"

  "Close All Tabs"
  "Stäng alla flikar"

  "Close Other Tab(s)"
  "Stäng Other Tab (er)"

  "Close Other*"
  "Stäng övriga flikar"

  "Close Tab"
  "Stäng flik"

  "Copyright %d-%d"
  "Copyright% d-% d"

  "Delete tab?"
  "Radera flik?"

  "Developer:"
  "Utvecklare:"

  "Email:"
  "E-post:"

  "Favorited"
  "Favorit"

  "File attribute (%s) does not exist"
  "File attribut (% s) finns inte"

  "File index is out of range"
  "File index är utanför intervallet"

  "Line: %d, Column: %d"
  "Rad:% d, Kolumn:% d"

  "Locked"
  "Spärrad"

  "Move to Other Pane"
  "Flytta till andra Pane"

  "Move*"
  "Move"

  "Release Type:"
  "Utgivningstyp:"

  "Reload file?"
  "Ladda om filen"

  "Save request"
  "Spara begäran"

  "Show in Sidebar"
  "Show i Sidebar"

  "Total Lines: %d, Total Characters: %d"
  "Totalt antal rader:% d, totalt Tecken:% d"

  "Unable to find current file (tab: %s)"
  "Det gick inte att hitta aktuell fil (flik:% s)"

  "Untitled"
  "Untitled"

  "Version:"
  "Version:"

}

# markers.tcl
msgcat::mcmset sv {

  "Marker name:"
  "Marker namn:"

}

# menus.tcl
msgcat::mcmset sv {

  "                                  Profiling Report Sorted By (%s)"
  "Profilering Rapport Sorterat efter (% s)"

  "About TKE"
  "Om TKE"

  "Align cursors"
  "Rikta markörer"

  "All"
  "ALL"

  "Append next occurrence"
  "Bifoga nästa förekomst"

  "Check for Update"
  "Leta efter uppdatering"

  "Clear All"
  "Avmarkera alla"

  "Close All"
  "Stäng alla"

  "Comment"
  "Kommentar"

  "Copy"
  "Kopiera"

  "Create new..."
  "Skapa nytt"

  "Create..."
  "Skapa"

  "Cut"
  "Klipp ut"

  "Edit"
  "Ändra"

  "Edit current"
  "Redigera Ström"

  "Edit user"
  "Redigera användare"

  "Edit..."
  "Redigera..."

  "File"
  "File"

  "Find"
  "Sök i"

  "Find and Replace"
  "Sök och ersätt"

  "Find in files"
  "Sök i filer..."

  "Find marker"
  "Hitta markör"

  "Find matching pair"
  "Hitta matchande par"

  "Format Text"
  "Formatera text"

  "From Clipboard"
  "Från Urklipp"

  "Goto Last Tab"
  "Goto Last Tab"

  "Goto Next Tab"
  "Gå till nästa flik"

  "Goto Other Pane"
  "Goto andra delfönstret"

  "Goto Previous Tab"
  "Gå till föregående flik"

  "Help"
  "Hjälp"

  "Hide Console"
  "Dölj konsol"

  "Hide Sidebar"
  "Dölj sidorad"

  "Hide Status Bar"
  "Dölj statusrad"

  "Hide Tab Bar"
  "Hide Tab Bar"

  "Import TextMate theme..."
  "Import Textmate tema ..."

  "Indent"
  "Indrag"

  "Insert Text"
  "Infoga text"

  "Insert enumeration"
  "Sätt uppräkning"

  "Install..."
  "Installera"

  "Launcher"
  "Launcher"

  "Lock"
  "Lock"

  "Menu Bindings"
  "Meny Bindningar"

  "Menu: About TKE"
  "Meny: Om TKE"

  "Menu: Align cursors"
  "Meny: Rikta markörer"

  "Menu: Append next occurrence"
  "Meny: Bifoga nästa förekomst"

  "Menu: Check for Update"
  "Meny: Leta efter uppdatering"

  "Menu: Close all tabs"
  "Meny: Stäng alla flikar"

  "Menu: Close current tab"
  "Meny: Stäng aktuell flik"

  "Menu: Comment selected text"
  "Meny: Kommentar markerad text"

  "Menu: Copy selected text"
  "Meny: Kopiera markerad text"

  "Menu: Create new plugin"
  "Meny: Skapa nytt plugin"

  "Menu: Create new theme"
  "Skapa nytt tema..."

  "Menu: Cut selected text"
  "Meny: Klipp ut markerad text"

  "Menu: Disable Vim mode"
  "Meny: Inaktivera Vim-läge"

  "Menu: Edit Tke theme"
  "Meny: Redigera Tke tema"

  "Menu: Edit current snippets"
  "Meny: Redigera nuvarande snuttar"

  "Menu: Edit user menu bindings"
  "Meny: Redigera användarmenyns bindningar"

  "Menu: Edit user preferences"
  "Meny: Redigera användarinställningar"

  "Menu: Enable Vim mode"
  "Meny: Aktivera Vim-läge"

  "Menu: Favorite file"
  "Meny: Favorit fil"

  "Menu: Find"
  "Meny: Sök"

  "Menu: Find and Replace"
  "Sök och ersätt"

  "Menu: Find in files"
  "Meny: Hitta filer"

  "Menu: Find matching character pair"
  "Meny: Hitta matchande teckenparet"

  "Menu: Find next occurrence"
  "Meny: Hitta nästa förekomst"

  "Menu: Find previous occurrence"
  "Meny: Sök föregående förekomst"

  "Menu: Format all text"
  "Meny: Formatera all text"

  "Menu: Format selected text"
  "Meny: Format markerad text"

  "Menu: Goto last tab"
  "Meny: Gå till sista fliken"

  "Menu: Goto next tab"
  "Meny: Gå till nästa flik"

  "Menu: Goto other pane"
  "Meny: Gå till andra rutan"

  "Menu: Goto previous tab"
  "Meny: Gå till föregående flik"

  "Menu: Hide Tab Bar"
  "Meny: Hide Tab Bar"

  "Menu: Hide console"
  "Meny: Hide-konsol"

  "Menu: Hide sidebar"
  "Meny: Hide sidebar"

  "Menu: Hide status bar"
  "Meny: Hide statusfältet"

  "Menu: Import TextMate theme"
  "Meny: Import Textmate tema"

  "Menu: Indent selected text"
  "Meny: indrag markerad text"

  "Menu: Insert enumeration"
  "Meny: Sätt uppräkning"

  "Menu: Insert from clipboard"
  "Infoga via urklipp"

  "Menu: Insert snippet"
  "Meny: Infoga snutt"

  "Menu: Install plugin"
  "Meny: Installera plugin"

  "Menu: Lock file"
  "Meny: Lås fil"

  "Menu: Move to other pane"
  "Meny: Flytta till andra rutan"

  "Menu: New file"
  "Meny: Ny fil"

  "Menu: Open Favorite"
  "Meny: Öppna Favorit"

  "Menu: Open Recent"
  "Meny: Öppna senaste"

  "Menu: Open directory"
  "Meny: Öppna telefonboken"

  "Menu: Open file"
  "Meny: Öppna filen"

  "Menu: Paste and format text from clipboard"
  "Meny: Klistra in och formatera text från Urklipp"

  "Menu: Paste text from clipboard"
  "Klistra in text från urklipp"

  "Menu: Quit application"
  "Meny: Avsluta programmet"

  "Menu: Redo"
  "Meny: Gör om"

  "Menu: Reload all plugins"
  "Meny: Ladda alla plugins"

  "Menu: Reload current snippets"
  "Meny: Ladda nuvarande snuttar"

  "Menu: Restart tke"
  "Meny: Omstart tke"

  "Menu: Save all files"
  "Meny: Spara alla filer"

  "Menu: Save file"
  "Meny: Spara fil"

  "Menu: Save file as"
  "Meny: Spara filen som"

  "Menu: Select all occurrences"
  "Meny: Välj alla förekomster"

  "Menu: Select all text"
  "Markera all text"

  "Menu: Set user bindings to global bindings"
  "Meny: Ställ användar bindningar till globala bindningar"

  "Menu: Set user preferences to global preferences"
  "Meny: Ange användarinställningar till globala inställningar"

  "Menu: Show Tab Bar"
  "Meny: Visa Tab Bar"

  "Menu: Show console"
  "Meny: Visa konsol"

  "Menu: Show last profiling report"
  "Meny: Visa senaste profilering rapport"

  "Menu: Show sidebar"
  "Meny: Visa sidebar"

  "Menu: Show status bar"
  "Visa statusrad"

  "Menu: Sort tabs"
  "Meny: Sortera flikar"

  "Menu: Start profiling"
  "Meny: Start profilering"

  "Menu: Stop profiling"
  "Meny: Stoppa profilering"

  "Menu: Toggle split view mode"
  "Meny: Växla delad vy läge"

  "Menu: Uncomment selected text"
  "Meny: Avkommentera markerad text"

  "Menu: Undo"
  "Meny: Ångra"

  "Menu: Unfavorite file"
  "Meny: Unfavorite fil"

  "Menu: Unindent selected text"
  "Meny: unindent markerad text"

  "Menu: Uninstall plugin"
  "Meny: Avinstallera plugin"

  "Menu: Unlock file"
  "Meny: Lås upp fil"

  "Menu: View User Guide"
  "Meny: Se Användarhandbok"

  "Menu: View global menu bindings"
  "Meny: Visa global meny bindningar"

  "Menu: View global preferences"
  "Meny: Visa globala inställningar"

  "Move to other pane"
  "Flytta till andra rutan"

  "New"
  "Nytt"

  "Open Directory..."
  "Öppna katalog"

  "Open Favorite"
  "Öppen Favoritspel"

  "Open File..."
  "Öppna fil..."

  "Open Recent"
  "Öppna senaste"

  "Paste"
  "limma"

  "Paste and Format"
  "Klistra in och format"

  "Plugins"
  "Insticksprogram"

  "Preferences"
  "Favoriter"

  "Profiling started"
  "Profilering började"

  "Profiling stopped"
  "Profilering stoppad"

  "Quit"
  "% quit"

  "Redo"
  "Återställ"

  "Reload"
  "Ladda om"

  "Reload current"
  "Ladda nuvarande"

  "Reset user to base"
  "Återställ användaren att basera"

  "Restart tke"
  "Starta om tke"

  "Save All"
  "Spara allt"

  "Save As..."
  "Spara som"

  "Select All"
  "Markera alla"

  "Select all occurrences"
  "Välj alla förekomster"

  "Select next occurrence"
  "Välj nästa förekomst"

  "Select previous occurrence"
  "Välj föregående förekomst"

  "Selected"
  "Vald"

  "Set Syntax"
  "Ställ Syntax"

  "Set Theme"
  "Ställ tema"

  "Set user to global"
  "Ställ in användare till global"

  "Show Console"
  "Visa konsol"

  "Show Last Profiling Report"
  "Visa Senaste Profilering Rapport"

  "Show Sidebar"
  "Visa sidorad"

  "Show Status Bar"
  "Visa statusrad"

  "Show Tab Bar"
  "Visa Tab Bar"

  "Show*Profiling*"
  "Visa * Profilering *"

  "Snippet"
  "Fragment"

  "Snippets"
  "Utdrag"

  "Sort Tabs"
  "Sort Tabs"

  "Split view"
  "Delad vy"

  "Start Profiling"
  "Börja Profilering"

  "Stop Profiling"
  "Stoppa Profilering"

  "Tabs"
  "Tabbar"

  "Text"
  "Text"

  "Theme Creator"
  "Theme Creator"

  "Tools"
  "Verktyg"

  "Uncomment"
  "Avkommentera"

  "Undo"
  "Ord"

  "Unindent"
  "Unindent"

  "Uninstall..."
  "avinstallera"

  "Unlock"
  "Lås upp"

  "User Guide"
  "User Guide"

  "View"
  "Visa"

  "View base"
  "Se bas"

  "View global"
  "Visa global"

  "Vim Mode"
  "Vim Läge"

}

# plugins.tcl
msgcat::mcmset sv {

  "ERROR:  Plugin name already exists"
  "FEL: Plugin namn finns redan"

  "ERROR:  Plugin name is not valid (only alphanumeric and underscores are allowed)"
  "FEL: Plugin namn är inte giltigt (endast alfanumeriska och understreck är tillåtna)"

  "ERROR:  Unable to create plugin directory"
  "FEL: Det går inte att skapa plugin katalog"

  "ERROR:  Unable to write plugin files"
  "FEL: Det går inte att skriva plugin-filer"

  "Enter plugin name"
  "Ange plugin namn"

  "Plugin %s installed"
  "Plugin% s installerad"

  "Plugin %s uninstalled"
  "Plugin% s avinstalle"

  "Plugin Errors"
  "Plugin fel"

  "Plugins successfully reloaded"
  "Insticksprogram framgångsrikt reloaded"

  "Syntax errors found in selected plugins"
  "Syntax fel i utvalda plugins"

}

# sidebar.tcl
msgcat::mcmset sv {

  "Add Parent Directory"
  "Moderkatalog"

  "Close Directory Files"
  "Stäng Directory filer"

  "Delete"
  "Radera"

  "Delete directory?"
  "Radera katalog?"

  "Delete file?"
  "Ta bort"

  "Duplicate"
  "Duplicera"

  "Make Current Working Directory"
  "Gör aktuell katalog"

  "New Directory"
  "Ny katalog"

  "New File"
  "Ny fil"

  "Open"
  "Öppen"

  "Open Directory Files"
  "Open Directory filer"

  "Refresh Directory Files"
  "Refresh register-filer"

  "Remove Parent from Sidebar"
  "Avlägsna Parent från sidofältet"

  "Remove from Sidebar"
  "Ta bort från sidofältet"

  "Rename"
  "Byt namn"

}

# snippets.tcl
msgcat::mcmset sv {

  "Snippet: %s: %s"
  "Snippet:% s:% s"

  "Snippet: *"
  "Fragment: *"

}

# syntax.tcl
msgcat::mcmset sv {

  "Syntax error in %s.syntax file"
  "Syntax error in% s.syntax fil"

  "Syntax:  %s"
  "Syntax:% s"

  "Theme:  %s"
  "Tema:% s"

}

# themer.tcl
msgcat::mcmset sv {

  "Create"
  "Skapa"

  "Create New Theme"
  "Skapa nytt tema..."

  "Create custom"
  "Skapa anpassade"

  "ERROR:  Unable to read %s"
  "FEL: Det går inte att läsa% s"

  "ERROR:  Unable to write %s"
  "FEL: Kan inte skriva% s"

  "Edit theme"
  "Redigera tema"

  "Enter theme name"
  "Ange tema namn"

  "Error:  Theme is not a supported theme"
  "Fel: Tema är inte ett tema som stöds"

  "Import"
  "Importera"

  "Import TextMate Theme"
  "Import Textmate tema"

  "Name:"
  "Namn:"

  "OK"
  "OK"

  "Reset"
  "Återställ"

  "Select theme"
  "Välj temafil"

}

# tke.tcl
msgcat::mcmset sv {

  "ERROR:  %s"
  "FEL:% s"

  "Edit theme?"
  "Redigera tema?"

  "Import TextMate theme?"
  "Importerar Textmate tema?"

}

# tkedat.tcl
msgcat::mcmset sv {

  "Unable to open %s for reading"
  "Kan inte öppna%1 för läsning."

  "Unable to open %s for writing"
  "Kunde inte öppna%1 för skrivning"

}

# General
msgcat::mcmset sv {

  "Cancel"
  "Avbryt"

  "Close"
  "Stäng"

  "Favorite"
  "Gunstling"

  "Find:"
  "Sök i"

  "Replace:"
  "Ersätt:"

  "Save"
  "Spara"

  "Save As"
  "Spara som..."

  "Unfavorite"
  "Unfavorite"

}

