# api.tcl
msgcat::mcmset zh {

  "Argument list to api::add_file was not an even key/value pair"
  "参数列表API :: ADD_FILE是不是连键/值对"

  "Argument list to api::add_file was not in the form 'filename [<option> <value>]*'"
  "参数列表API :: ADD_FILE是不是在窗体的文件名[ <option><value> ] *&#39;"

  "get_home_directory can only be called within plugin code"
  "get_home_directory只能在插件代码中调用"

}

# bgproc.tcl
msgcat::mcmset zh {

  "Unable to run system command (%s)"
  "无法执行系统命令（％S）"

}

# bindings.tcl
msgcat::mcmset zh {

  "Menu Bindings: Edit user menu bindings"
  "菜单绑定：编辑用户菜单绑定"

  "Menu Bindings: Reload menu bindings"
  "菜单绑定：刷新菜单绑定"

  "Menu Bindings: Use default menu bindings"
  "菜单绑定：使用默认的菜单绑定"

  "Menu Bindings: View global menu bindings"
  "菜单绑定：查看全局菜单绑定"

}

# gui.tcl
msgcat::mcmset zh {

  "Close All Tabs"
  "關閉全部的頁籤"

  "Close Other Tab(s)"
  "关闭其他选项卡（S）"

  "Close Other*"
  "关闭其他*"

  "Close Tab"
  "关闭标签页"

  "Copyright %d-%d"
  "版权所有％的d-％d个"

  "Delete tab?"
  "删除标签？"

  "Developer:"
  "开发商："

  "Email:"
  "电子邮件："

  "File attribute (%s) does not exist"
  "文件属性（％s）不存在"

  "File index is out of range"
  "文件索引超出范围"

  "Find:"
  "查找"

  "Line: %d, Column: %d"
  "行数：％d，列数：％d"

  "Line: %d, Column: %d, Total Lines: %d, Total Characters: %d"
  "行数：％d，列数：％d，行总数：％d个，总字符数：％d"

  "Locked"
  "已锁定"

  "Move to Other Pane"
  "移动到另一个窗格"

  "Move*"
  "移动"

  "Reload file?"
  "重装文件？"

  "Replace:"
  "替换:"

  "Save request"
  "保存请求"

  "Unable to find current file (tab: %s)"
  "找不到当前文件（制表：％S）"

  "Untitled"
  "未命名"

  "Version:"
  "版本："

}

# markers.tcl
msgcat::mcmset zh {

  "Marker name:"
  "标志名称："

}

# menus.tcl
msgcat::mcmset zh {

  "                                  Profiling Report Sorted By (%s)"
  "剖析报告排序方法（％S）"

  "About Tke"
  "关于"

  "About tke"
  "关于"

  "Align cursors"
  "游标对齐"

  "All"
  "所有"

  "Append next occurrence"
  "追加下一个出现"

  "Clear All"
  "全部清除"

  "Close All"
  "全部关闭"

  "Comment"
  "备注"

  "Copy"
  "复制"

  "Create new..."
  "新建"

  "Create..."
  "建立..."

  "Cut"
  "剪切"

  "Edit"
  "编辑"

  "Edit..."
  "編輯..."

  "FOOBAR"
  "Foobar"

  "File"
  "文件"

  "Find"
  "查找"

  "Find and Replace"
  "查找和替换"

  "Find in files"
  "在文件中查找"

  "Find marker"
  "標記"

  "Find matching pair"
  "找到匹配的一对"

  "Format Text"
  "设置文本格式"

  "Goto Last Tab"
  "转到最后一个标签页"

  "Goto Next Tab"
  "转到下一个标签"

  "Goto Other Pane"
  "转到其他窗格"

  "Goto Previous Tab"
  "转到前一个标签"

  "Help"
  "帮助"

  "Import TextMate theme..."
  "进口TextMate的主题..."

  "Indent"
  "縮排"

  "Insert enumeration"
  "将枚举"

  "Install..."
  "安装"

  "Launcher"
  "发射台"

  "Lock"
  "鎖定"

  "Menu: About tke"
  "菜单：关于将军澳支线"

  "Menu: Align cursors"
  "菜单：游标对齐"

  "Menu: Append next occurrence"
  "菜单：追加下一个出现"

  "Menu: Close all tabs"
  "关闭全部标签页"

  "Menu: Close current tab"
  "菜单：关闭当前标签页"

  "Menu: Comment selected text"
  "菜单：注释选定的文本"

  "Menu: Copy selected text"
  "菜单：复制选中的文本"

  "Menu: Create new plugin"
  "菜单：创建新的插件"

  "Menu: Create new theme"
  "菜单：创建新的主题"

  "Menu: Cut selected text"
  "菜单：剪切选中的文本"

  "Menu: Disable Vim mode"
  "菜单：禁用Vim的模式"

  "Menu: Edit Tke theme"
  "菜单：编辑将军澳支线主题"

  "Menu: Enable Vim mode"
  "菜单：启动Vim的模式"

  "Menu: Find"
  "菜单：查找"

  "Menu: Find and Replace"
  "查找和替换"

  "Menu: Find in files"
  "菜单：在文件中查找"

  "Menu: Find matching character pair"
  "菜单：查找匹配字符对"

  "Menu: Find next occurrence"
  "菜单：查找下一个出现"

  "Menu: Find previous occurrence"
  "菜单：查找上一个匹配"

  "Menu: Goto last tab"
  "菜单：转到最后一个标签页"

  "Menu: Goto next tab"
  "菜单：转到下一个标签"

  "Menu: Goto other pane"
  "菜单：转到另一个窗格"

  "Menu: Goto previous tab"
  "菜单：跳转到前一个标签"

  "Menu: Hide console"
  "菜单：隐藏控制台"

  "Menu: Hide sidebar"
  "菜单：隐藏侧边栏"

  "Menu: Hide status bar"
  "菜单：隐藏状态栏"

  "Menu: Import TextMate theme"
  "菜单：进口TextMate的主题"

  "Menu: Indent selected text"
  "菜单：缩进选定的文本"

  "Menu: Insert enumeration"
  "菜单：将枚举"

  "Menu: Install plugin"
  "菜单：安装插件"

  "Menu: Lock file"
  "菜单：文件锁定"

  "Menu: New file"
  "菜单：新建文件"

  "Menu: Open directory"
  "菜单：打开目录"

  "Menu: Open file"
  "菜单：打开文件"

  "Menu: Paste and format text from clipboard"
  "菜单：粘贴和格式从剪贴板中的文本"

  "Menu: Paste text from clipboard"
  "从剪贴板粘贴文本"

  "Menu: Quit application"
  "菜单：退出应用程序"

  "Menu: Redo"
  "菜单：重做"

  "Menu: Reload all plugins"
  "菜单：重新载入所有插件"

  "Menu: Restart tke"
  "菜单：重新启动将军澳支线"

  "Menu: Save all files"
  "菜单：保存所有文件"

  "Menu: Save file"
  "菜单：保存文件"

  "Menu: Save file as"
  "菜单：文件另存为"

  "Menu: Select all occurrences"
  "菜单：选择所有出现"

  "Menu: Show console"
  "菜单：显示控制台"

  "Menu: Show last profiling report"
  "菜单：显示最近分析报告"

  "Menu: Show sidebar"
  "菜单：显示侧边栏"

  "Menu: Show status bar"
  "菜单：显示状态栏"

  "Menu: Sort tabs"
  "菜单：排序选项卡"

  "Menu: Start profiling"
  "菜单：剖析"

  "Menu: Stop profiling"
  "菜单：停止剖析"

  "Menu: Toggle split pane"
  "菜单：切换分割窗格"

  "Menu: Uncomment selected text"
  "菜单：取消对选定的文本"

  "Menu: Undo"
  "菜单：撤消"

  "Menu: Unindent selected text"
  "菜单：取消缩进选定的文本"

  "Menu: Uninstall plugin"
  "菜单：卸载插件"

  "Menu: Unlock file"
  "菜单：文件解锁"

  "New"
  "新建"

  "Open Directory..."
  "开放目录..."

  "Open File..."
  "開啟檔案"

  "Open Recent"
  "打开最近"

  "Paste"
  "粘贴"

  "Paste and Format"
  "粘贴和格式"

  "Plugins"
  "插件"

  "Preferences..."
  "偏好設定..."

  "Profiling started"
  "分析开始"

  "Profiling stopped"
  "停止剖析"

  "Quit"
  "退出"

  "Redo"
  "重複"

  "Reload"
  "重新加载"

  "Restart tke"
  "重新启动TKE"

  "Save All"
  "全部儲存"

  "Save As..."
  "保存为"

  "Select all occurrences"
  "选择所有事件"

  "Select next occurrence"
  "选择下一个出现"

  "Select previous occurrence"
  "选择上发生"

  "Selected"
  "选定"

  "Set Syntax"
  "设置语法"

  "Show Last Profiling Report"
  "显示最后剖析报告"

  "Show split pane"
  "显示拆分窗格"

  "Show*Profiling*"
  "显示*评测*"

  "Sort Tabs"
  "分类标签"

  "Start Profiling"
  "开始分析"

  "Stop Profiling"
  "停止分析"

  "Tabs"
  "標籤"

  "Text"
  "文本"

  "Theme Creator"
  "主题造物主"

  "Tools"
  "工具"

  "Uncomment"
  "取消注释"

  "Undo"
  "復原"

  "Unindent"
  "取消缩进"

  "Uninstall..."
  "卸载"

  "Unlock"
  "解锁用户"

  "View"
  "查看"

  "View Console"
  "查看控制台"

  "View Sidebar"
  "查看侧边栏"

  "View Status Bar"
  "狀態列"

  "Vim Mode"
  "Vim的模式"

}

# plugins.tcl
msgcat::mcmset zh {

  "ERROR:  Plugin name is not valid (only alphanumeric and underscores are allowed)"
  "错误：插件名称无效（字母数字和下划线是允许的）"

  "ERROR:  Unable to write plugin file"
  "错误：无法写入插件文件"

  "Enter plugin name"
  "输入插件名称"

  "Plugin %s installed"
  "插件％s的安装"

  "Plugin %s uninstalled"
  "插件％s的卸载"

  "Plugin Errors"
  "插件错误"

  "Syntax errors found in selected plugins"
  "在选定的外挂，发现语法错误"

}

# preferences.tcl
msgcat::mcmset zh {

  "Preferences: Edit user preferences"
  "首选项：修改用户首选项"

  "Preferences: Reload preferences"
  "喜好：刷新喜好"

  "Preferences: Use default preferences"
  "首选项：使用默认的首选项"

  "Preferences: View global preferences"
  "喜好：查看全球首选项"

}

# sidebar.tcl
msgcat::mcmset zh {

  "Add Parent Directory"
  "母目錄"

  "Close Directory Files"
  "关闭目录文件"

  "Delete"
  "刪除"

  "Delete directory?"
  "删除目录？"

  "Delete file?"
  "删除文件？"

  "Duplicate"
  "复制"

  "Make Current Working Directory"
  "使当前工作目录"

  "New Directory"
  "新目录"

  "New File"
  "新文件"

  "Open"
  "打开"

  "Refresh Directory Files"
  "刷新目录文件"

  "Remove Parent from Sidebar"
  "从边栏移除父"

  "Remove from Sidebar"
  "从边栏移除"

  "Rename"
  "重命名"

}

# snippets.tcl
msgcat::mcmset zh {

  "Snippet: %s: %s"
  "片段：％S：％s的"

  "Snippet: *"
  "片段"

  "Snippets: Add snippet"
  "片段：添加片段"

  "Snippets: Reload all snippets"
  "片段：刷新所有片段"

}

# syntax.tcl
msgcat::mcmset zh {

  "Syntax error in %s.syntax file"
  "在％s.syntax文件中的语法错误"

  "Syntax:  %s"
  "语法：％s的"

  "Theme:  %s"
  "主题：％S"

}

# themer.tcl
msgcat::mcmset zh {

  "Create"
  "创建"

  "Create New Theme"
  "创建新主题"

  "Create custom"
  "创建自定义"

  "ERROR:  Unable to read %s"
  "错误：无法读取％s的"

  "ERROR:  Unable to write %s"
  "错误：无法写入％s的"

  "Edit theme"
  "主题"

  "Enter theme name"
  "进入主题名称"

  "Error:  Theme is not a supported theme"
  "错误：主题是不受支持的主题"

  "Import"
  "進口"

  "Import TextMate Theme"
  "进口TextMate的主题"

  "Name:"
  "名称："

  "OK"
  "确定"

  "Reset"
  "重置"

  "Select theme"
  "选择主题"

}

# tke.tcl
msgcat::mcmset zh {

  "ERROR:  %s"
  "错误：％s"

  "Edit theme?"
  "编辑主题？"

  "Import TextMate theme?"
  "进口TextMate的主题？"

}

# tkedat.tcl
msgcat::mcmset zh {

  "Unable to open %s for reading"
  "无法打开％s的读取"

  "Unable to open %s for writing"
  "无法打开％s的写入"

}

# General
msgcat::mcmset zh {

  "Cancel"
  "取消"

  "Close"
  "关闭"

  "Save"
  "保存"

  "Save As"
  "保存为"

}

