# api.tcl
msgcat::mcmset zh {

  "Argument list to api::add_file was not an even key/value pair"
  "参数列表API :: ADD_FILE是不是连键/值对"

  "Plugin-%s: %s"
  "插件 %s: %s"

}

# bgproc.tcl
msgcat::mcmset zh {

  "Unable to run system command (%s)"
  "无法执行系统命令（％S）"

}

# diff.tcl
msgcat::mcmset zh {

  "    End: "
  "结束："

  "    Start: "
  "开始："

  "Enter difference command"
  "请输入不同的命令"

  "Enter starting file"
  "输入起始文件"

  "Update"
  "升级"

}

# gui.tcl
msgcat::mcmset zh {

  "%s, Line: %d, Column: %d"
  "％s的，行数：％d，列数：％d"

  "Case sensitivity"
  "区分大小写"

  "Close All Tabs"
  "關閉全部的頁籤"

  "Close Other Tab(s)"
  "关闭其他选项卡（S）"

  "Close Other*"
  "关闭其他*"

  "Close Tab"
  "关闭标签页"

  "Copyright %d-%d"
  "版权所有％的d-％d个"

  "Delete tab?"
  "删除标签？"

  "Developer:"
  "开发商："

  "Email:"
  "电子邮件："

  "Error"
  "錯誤"

  "Favorited"
  "评选"

  "File already exists.  Use '!' to force an overwrite"
  "文件已存在。 使用 '!' 强制覆盖"

  "File attribute (%s) does not exist"
  "文件属性（％s）不存在"

  "File index is out of range"
  "文件索引超出范围"

  "License:"
  "??"

  "Line: %d, Column: %d"
  "行数：％d，列数：％d"

  "Locked"
  "已锁定"

  "Move*"
  "移动"

  "Must be in multicursor mode to insert numbers"
  "必须在 multicursor 模式下插入数字"

  "No write permissions.  Use '!' to force write."
  "没有写权限。 使用 '!'，迫使写。"

  "Release Type:"
  "释放"

  "Reload file?"
  "重装文件？"

  "Save request"
  "保存请求"

  "Show in Sidebar"
  "显示在侧栏"

  "Starting number:"
  "开始点编号:"

  "Tcl/Tk Version:"
  "Tcl/Tk 版本："

  "Total Lines: %d, Total Characters: %d"
  "行总数：％d个，总字符数：％d"

  "Unable to find current file (tab: %s)"
  "找不到当前文件（制表：％S）"

  "Unable to successfully parse number string"
  "无法成功分析数字字符串"

  "Unable to write file"
  "无法写入文件"

  "Version:"
  "版本："

}

# markers.tcl
msgcat::mcmset zh {

  "Marker name:"
  "标志名称："

}

# menus.tcl
msgcat::mcmset zh {

  "                                  Profiling Report Sorted By (%s)"
  "剖析报告排序方法（％S）"

  "About TKE"
  "关于将军澳支线"

  "Align Cursors"
  "????"

  "Append Next Occurrence"
  "????????"

  "Auto-Indent"
  "自动缩进"

  "Check for Update"
  "检查更新"

  "Clear All"
  "全部清除"

  "Close All"
  "全部关闭"

  "Close Current"
  "????"

  "Copy"
  "复制"

  "Create at Current Line"
  "???????"

  "Create..."
  "建立..."

  "Cut"
  "剪切"

  "Edit"
  "编辑"

  "Edit Language"
  "编辑语言"

  "Edit Menu Edit user snippets"
  "编辑菜单编辑用户代码段"

  "Edit Menu: Copy text"
  "编辑菜单: 复制文本"

  "Edit Menu: Cut text"
  "编辑菜单: 剪切文本"

  "Edit Menu: Edit language snippets"
  "编辑菜单: 编辑语言片段"

  "Edit Menu: Edit session current language preferences"
  "编辑菜单: 编辑会话当前语言首选项"

  "Edit Menu: Edit session global preferences"
  "编辑菜单: 编辑会话全球首选项"

  "Edit Menu: Edit user current language preferences"
  "编辑菜单: 编辑用户当前的语言首选项"

  "Edit Menu: Edit user global preferences"
  "编辑菜单: 编辑用户全球首选项"

  "Edit Menu: Edit user menu bindings"
  "编辑菜单: 编辑用户菜单绑定"

  "Edit Menu: Format all text"
  "编辑菜单: 设置格式的所有文本"

  "Edit Menu: Format selected text"
  "编辑菜单: 设置所选的文本的格式"

  "Edit Menu: Insert from clipboard"
  "从剪贴板上的编辑菜单: 插入"

  "Edit Menu: Insert snippet"
  "编辑菜单: 插入代码段"

  "Edit Menu: Paste and format text from clipboard"
  "编辑菜单: 粘贴和格式将文本从剪贴板"

  "Edit Menu: Paste text from clipboard"
  "编辑菜单: 将文本从剪贴板粘贴"

  "Edit Menu: Redo"
  "编辑菜单: 重做"

  "Edit Menu: Reload snippets"
  "编辑菜单: 重新加载代码片段"

  "Edit Menu: Select all text"
  "编辑菜单: 选择所有文本"

  "Edit Menu: Set indent mode to IND"
  "编辑菜单: 设置缩进模式向移民局"

  "Edit Menu: Set indent mode to IND+"
  "编辑菜单: 设置缩进模式为 IND +"

  "Edit Menu: Set indent mode to OFF"
  "编辑菜单: 将缩进模式设置为 OFF"

  "Edit Menu: Set user bindings to global bindings"
  "编辑菜单: 设置用户绑定到全局绑定"

  "Edit Menu: Set user preferences to global preferences"
  "编辑菜单: 设置全球首选项中设置的用户首选项"

  "Edit Menu: Undo"
  "编辑菜单: 撤消"

  "Edit Menu: View base preferences file"
  "编辑菜单: 查看基地首选项文件"

  "Edit Menu: View global menu bindings"
  "编辑菜单: 查看全局菜单绑定"

  "Edit Session - Global"
  "????-??"

  "Edit Session - Language"
  "????-??"

  "Edit User"
  "編輯用戶"

  "Edit User - Global"
  "????-??"

  "Edit User - Language"
  "????-??"

  "File"
  "文件"

  "File Menu: Close all tabs"
  "文件菜单: 关闭所有选项卡"

  "File Menu: Close current tab"
  "文件菜单: 关闭当前选项卡"

  "File Menu: Favorite file"
  "文件菜单: 最喜欢文件"

  "File Menu: Lock file"
  "文件菜单: 锁定文件"

  "File Menu: New file"
  "文件菜单: 新建文件"

  "File Menu: Open Favorite"
  "文件菜单: 打开收藏夹"

  "File Menu: Open Recent"
  "打开最近的文件菜单:"

  "File Menu: Open directory"
  "文件菜单: 打开目录"

  "File Menu: Open file"
  "文件菜单: 打开文件"

  "File Menu: Quit application"
  "文件菜单: 退出应用程序"

  "File Menu: Save all files"
  "文件菜单: 保存所有文件"

  "File Menu: Save file"
  "文件菜单: 保存文件"

  "File Menu: Save file as"
  "文件菜单: 文件另存为"

  "File Menu: Show file difference"
  "文件菜单: 显示文件差异"

  "File Menu: Unfavorite file"
  "文件菜单: 太罗嗦文件"

  "File Menu: Unlock file"
  "文件菜单: 解锁文件"

  "Find"
  "查找"

  "Find In Files"
  "??????..."

  "Find Matching Pair"
  "??????"

  "Find Menu: Append next occurrence"
  "查找菜单: 追加下一个匹配项"

  "Find Menu: Create marker at current line"
  "在当前行查找菜单: 创建标记"

  "Find Menu: Find"
  "查找菜单: 找到"

  "Find Menu: Find and Replace"
  "查找菜单: 查找和替换"

  "Find Menu: Find in files"
  "查找/在文件中查找"

  "Find Menu: Find matching character pair"
  "查找菜单: 寻找匹配的字符对"

  "Find Menu: Find next occurrence"
  "查找菜单: 查找下一个实例"

  "Find Menu: Find previous occurrence"
  "查找菜单: 查找上一个"

  "Find Menu: Goto next difference"
  "查找菜单: 转到下一个差异"

  "Find Menu: Goto previous difference"
  "查找菜单: 转到上一个差异"

  "Find Menu: Jump backward"
  "查找菜单: 向后跳"

  "Find Menu: Jump forward"
  "查找菜单: 向前跳"

  "Find Menu: Remove all markers"
  "查找菜单: 删除所有标记"

  "Find Menu: Remove marker from current line"
  "从当前行查找菜单: 删除标记"

  "Find Menu: Select all occurrences"
  "查找菜单: 选择的所有匹配项"

  "Find Menu: Show selected line change"
  "查找菜单: 显示选定线变化"

  "Find and Replace"
  "查找和替换"

  "Format Text"
  "设置文本格式"

  "From Clipboard"
  "从剪贴板"

  "Goto Last Tab"
  "转到最后一个标签页"

  "Goto Next Tab"
  "转到下一个标签"

  "Goto Other Pane"
  "转到其他窗格"

  "Goto Previous Tab"
  "转到前一个标签"

  "Help"
  "帮助"

  "Help Menu: About TKE"
  "帮助菜单: 关于将军澳支线"

  "Help Menu: Check for update"
  "帮助菜单: 检查更新"

  "Help Menu: Send bug report"
  "帮助菜单: 发送错误报告"

  "Help Menu: Send feedback"
  "帮助菜单: 发送反馈"

  "Help Menu: View user guide"
  "帮助菜单: 查看用户指南"

  "Hide Console"
  "隐藏控制台"

  "Hide Line Numbers"
  "隐藏行号"

  "Hide Meta Characters"
  "?? Meta ??"

  "Hide Sidebar"
  "隐藏边栏"

  "Hide Status Bar"
  "隐藏状态栏"

  "Hide Tab Bar"
  "隐藏标签栏"

  "Indent"
  "縮排"

  "Indent Mode"
  "缩进模式"

  "Indent Off"
  "关闭缩进"

  "Insert Enumeration"
  "????"

  "Insert Text"
  "插入文字"

  "Install..."
  "安装"

  "Jump Backward"
  "???"

  "Jump Forward"
  "???"

  "Launcher"
  "发射台"

  "Lock"
  "鎖定"

  "Markers"
  "标记"

  "Menu Bindings"
  "菜单绑定"

  "Menus: About TKE"
  "菜单: 关于将军澳支线"

  "Merge Panes"
  "????"

  "Next Difference"
  "?????"

  "Open Directory..."
  "开放目录..."

  "Open Favorite"
  "打开收藏"

  "Open File..."
  "開啟檔案"

  "Open Recent"
  "打开最近"

  "Paste"
  "粘贴"

  "Paste and Format"
  "粘贴和格式"

  "Plugins"
  "插件"

  "Plugins Menu: Create new plugin"
  "插件菜单: 创建新的插件"

  "Plugins Menu: Install plugin"
  "插件菜单: 安装插件"

  "Plugins Menu: Reload all plugins"
  "重新加载所有插件插件菜单:"

  "Plugins Menu: Uninstall plugin"
  "插件菜单: 卸载插件"

  "Preferences"
  "首选项"

  "Previous Difference"
  "?????"

  "Profiling started"
  "分析开始"

  "Profiling stopped"
  "停止剖析"

  "Quit"
  "退出"

  "Redo"
  "重複"

  "Reload"
  "重新加载"

  "Remove All Markers"
  "??????"

  "Remove From Current Line"
  "??????"

  "Replace Line With Script"
  "??????"

  "Reset User to Base"
  "将用户重置为基地"

  "Restart TKE"
  "?????????"

  "Save All"
  "全部儲存"

  "Save As..."
  "保存为"

  "Save Current"
  "????"

  "Select All"
  "全选"

  "Select All Occurrences"
  "???????"

  "Select Next Occurrence"
  "????????"

  "Select Previous Occurrence"
  "????????"

  "Selected"
  "选定"

  "Send Bug Report"
  "发送报告"

  "Send Feedback"
  "发送 feedback"

  "Sessions"
  "??"

  "Sessions Menu: Close current session"
  "会话菜单: 关闭当前会话"

  "Sessions Menu: Delete session"
  "会话菜单: 删除会话"

  "Sessions Menu: Open session"
  "会话菜单: 打开的会话"

  "Sessions Menu: Save current session"
  "会话菜单: 保存当前会话"

  "Sessions Menu: Save sessions as"
  "会话菜单: 保存会话作为"

  "Sessions Menu: Switch to session"
  "切换到会话的会话菜单:"

  "Set Syntax"
  "设置语法"

  "Set Theme"
  "设置主题"

  "Set User to Global"
  "设置的用户到全球"

  "Show Console"
  "显示控制台"

  "Show Diagnostic Logfile"
  "显示诊断日志文件"

  "Show File Difference"
  "显示不同"

  "Show Last Profiling Report"
  "显示最后剖析报告"

  "Show Line Numbers"
  "显示数字"

  "Show Meta Characters"
  "?? Meta ??"

  "Show Selected Line Change"
  "???????"

  "Show Sidebar"
  "显示侧边栏"

  "Show Status Bar"
  "显示状态"

  "Show Tab Bar"
  "显示标签栏"

  "Smart Indent"
  "智能缩进"

  "Snippet"
  "片段"

  "Snippets"
  "片段"

  "Sort Tabs"
  "分类标签"

  "Start Profiling"
  "开始分析"

  "Stop Profiling"
  "停止分析"

  "Switch To"
  "???..."

  "Tabs"
  "標籤"

  "Text"
  "文本"

  "Text Menu: Align cursors"
  "菜单文本: 对齐光标"

  "Text Menu: Indent selected text"
  "文本菜单: 缩进选定的文本"

  "Text Menu: Insert enumeration"
  "文本菜单: 插入枚举"

  "Text Menu: Replace line with script"
  "文本菜单: 用脚本替换行"

  "Text Menu: Toggle comment"
  "文本菜单: 切换注释"

  "Text Menu: Unindent selected text"
  "文本菜单: 取消缩进选定的文本"

  "Toggle Comment"
  "??/????"

  "Tools"
  "工具"

  "Tools Menu: Disable Vim mode"
  "工具菜单: 禁用 Vim 模式"

  "Tools Menu: Enable Vim mode"
  "工具菜单: 启用 Vim 模式"

  "Tools Menu: Restart TKE"
  "工具菜单: 重启将军澳支线"

  "Tools Menu: Run theme editor"
  "工具菜单：运行的主题编辑器"

  "Tools Menu: Show diagnostic logfile"
  "工具菜单: 显示诊断日志文件"

  "Tools Menu: Show last profiling report"
  "工具菜单: 显示最后的分析报告"

  "Tools Menu: Start profiling"
  "工具菜单: 启动性能分析"

  "Tools Menu: Stop profiling"
  "工具菜单: 停止性能分析"

  "Undo"
  "復原"

  "Unindent"
  "取消缩进"

  "Uninstall..."
  "卸载"

  "Unlock"
  "解锁用户"

  "User Guide"
  "用户指南"

  "View"
  "查看"

  "View Base"
  "视图基础"

  "View Global"
  "查看全球"

  "View Menu: Goto last tab"
  "视图菜单: 转到最后一个选项卡"

  "View Menu: Goto next tab"
  "视图菜单: 转到下一个选项卡"

  "View Menu: Goto other pane"
  "视图菜单: 转到另一窗格"

  "View Menu: Goto previous tab"
  "视图菜单: 转到上一个选项卡"

  "View Menu: Hide console"
  "视图菜单: 隐藏控制台"

  "View Menu: Hide line numbers"
  "视图菜单: 隐藏行号"

  "View Menu: Hide meta characters"
  "视图菜单: 隐藏 meta 字符"

  "View Menu: Hide sidebar"
  "视图菜单: 隐藏侧边栏"

  "View Menu: Hide status bar"
  "视图菜单: 隐藏状态栏"

  "View Menu: Hide tab bar"
  "视图菜单: 隐藏选项卡栏"

  "View Menu: Merge panes"
  "视图菜单: 合并窗格"

  "View Menu: Move to other pane"
  "视图菜单: 将移动到另一个窗格"

  "View Menu: Show console"
  "视图菜单: 显示控制台"

  "View Menu: Show line numbers"
  "视图菜单: 显示行号"

  "View Menu: Show meta characters"
  "视图菜单: 显示 meta 字符"

  "View Menu: Show sidebar"
  "视图菜单: 显示侧边栏"

  "View Menu: Show status bar"
  "视图菜单: 显示状态栏"

  "View Menu: Show tab bar"
  "视图菜单: 显示选项卡栏"

  "View Menu: Sort tabs"
  "视图菜单: 排序选项卡"

  "View Menu: Toggle split view mode"
  "视图菜单: 切换拆分视图模式"

  "Vim Mode"
  "Vim的模式"

}

# plugins.tcl
msgcat::mcmset zh {

  "ERROR (%s,%s): %s"
  "错误的 s）： %s"

  "ERROR:  Plugin name already exists"
  "错误：插件名称已存在"

  "ERROR:  Plugin name is not valid (only alphanumeric and underscores are allowed)"
  "错误：插件名称无效（字母数字和下划线是允许的）"

  "ERROR:  Unable to create plugin directory"
  "错误：无法创建插件目录"

  "ERROR:  Unable to write plugin files"
  "错误：无法写入文件的插件"

  "Enter plugin name"
  "输入插件名称"

  "Plugin %s installed"
  "插件％s的安装"

  "Plugin %s uninstalled"
  "插件％s的卸载"

  "Plugin Errors"
  "插件错误"

  "Plugins successfully reloaded"
  "插件重新加载成功"

  "Syntax errors found in selected plugins"
  "在选定的外挂，发现语法错误"

}

# search.tcl
msgcat::mcmset zh {

  "%d substitutions done"
  "%d 个换人做"

  "No files found in specified directories"
  "指定的目录中未找到文件"

  "No search results found"
  "个搜索结果"

  "Search wrapped to beginning of file"
  "搜索到文件的开头包裹"

  "Search wrapped to end of file"
  "搜索包裹到文件结尾"

}

# sidebar.tcl
msgcat::mcmset zh {

  "Add Parent Directory"
  "母目錄"

  "Close Directory Files"
  "关闭目录文件"

  "Copy Pathname"
  "?????"

  "Delete directory?"
  "删除目录？"

  "Delete file?"
  "删除文件？"

  "Directory Name:"
  "目录名称:"

  "Duplicate"
  "复制"

  "File Name:"
  "文件名："

  "Folder Name:"
  "??????"

  "Make Current Working Directory"
  "使当前工作目录"

  "New Directory"
  "新目录"

  "Open Directory Files"
  "打开目录文件"

  "Refresh Directory Files"
  "刷新目录文件"

  "Remove Parent from Sidebar"
  "从边栏移除父"

  "Remove from Sidebar"
  "从边栏移除"

  "Rename"
  "重命名"

  "Show Difference"
  "显示不同"

}

# snippets.tcl
msgcat::mcmset zh {

  "Snippet: *"
  "片段"

}

# syntax.tcl
msgcat::mcmset zh {

  "Syntax error in %s.syntax file"
  "在％s.syntax文件中的语法错误"

  "Syntax: %s"
  "语法: %s"

}

# theme.tcl
msgcat::mcmset zh {

  "ERROR:  Unable to read %s"
  "错误：无法读取％s的"

  "Images"
  "图像"

  "Menu Options"
  "菜单选项"

  "Sidebar Options"
  "侧边栏选项"

  "Sidebar Scrollbar Options"
  "侧边栏滚动条选项"

  "Syntax Colors"
  "语法颜色"

  "Tab Options"
  "TAB选项"

  "Text Scrollbar Options"
  "文字滚动条选项"

  "ttk Widget Colors"
  "TTK的Widget颜色"

}

# themer.tcl
msgcat::mcmset zh {

  "   Show All"
  "显示全部"

  "   Show Category"
  "显示细节"

  "   Show Color"
  "显示颜色"

  "   Show Selected Option"
  "显示当前选项"

  "   Show Selected Value"
  "選擇值"

  "Categories"
  "分类"

  "Change Base Color"
  "更改颜色"

  "Choose Theme"
  "选择主题"

  "Custom Directory"
  "自定义目录"

  "Custom..."
  "自定义..."

  "Delete swatch?"
  "删除色盘"

  "Description"
  "描述"

  "Details"
  "详细"

  "Done"
  "完成"

  "Export"
  "导出"

  "GIF Photo"
  "GIF图片"

  "Import"
  "進口"

  "Import BMP Data"
  "匯入資料"

  "Import BMP Mask"
  "导入BMP面膜"

  "Import Error"
  "﻿导入错误"

  "Import Theme File"
  "导入主题文件"

  "Installation Directory"
  "安装目录"

  "Modifications"
  "其他"

  "None"
  "无"

  "One-Color Bitmap"
  "单色位图"

  "Preview"
  "預覽"

  "Relief: "
  "救济"

  "Save As:"
  "另存為:"

  "Save theme changes?"
  "保存主题的变化？"

  "Select Directory"
  "选择目录"

  "Swatch"
  "色盘"

  "Swatch Colors"
  "斯沃琪颜色"

  "Table Filters"
  "表过滤器"

  "The current theme has unsaved changes"
  "目前的主题有未保存的更改"

  "Theme Editor %s %s"
  "主题编辑器％s％S"

  "Tree Style: "
  "树风格："

  "Two-Color Bitmap"
  "双色位图"

  "User Directory"
  "用户目录"

  "Value"
  "數值"

  "Value: "
  "值:"

}

# themes.tcl
msgcat::mcmset zh {

  "Theme:  %s"
  "主题：％S"

  "Theme:*"
  "主题"

}

# tke.tcl
msgcat::mcmset zh {

  "Import TKE theme?"
  "进口TKE主题？"

  "Import TextMate theme?"
  "进口TextMate的主题？"

}

# tkedat.tcl
msgcat::mcmset zh {

  "Unable to open %s for reading"
  "无法打开 %s 进行阅读"

}

# vim.tcl
msgcat::mcmset zh {

  "File %s successfully written"
  "文件 %s 成功地写"

  "Filename %s already exists"
  "文件名 %s 已存在"

}

# General
msgcat::mcmset zh {

  "All"
  "所有"

  "Cancel"
  "取消"

  "Close"
  "关闭"

  "Delete"
  "刪除"

  "Favorite"
  "我的最愛"

  "Find:"
  "查找"

  "Move to Other Pane"
  "移动到另一个窗格"

  "New File"
  "新文件"

  "Open"
  "打开"

  "Replace:"
  "替换:"

  "Save"
  "保存"

  "Save As"
  "保存为"

  "Split View"
  "????"

  "Theme Editor"
  "主题编辑器"

  "Unable to open %s for writing"
  "无法打开％s的写入"

  "Unfavorite"
  "不喜欢的"

}

