# api.tcl
msgcat::mcmset zh {

  "Argument list to api::add_file was not an even key/value pair"
  "参数列表API :: ADD_FILE是不是连键/值对"

  "Plugin"
  "插件"

}

# bgproc.tcl
msgcat::mcmset zh {

  "Unable to run system command"
  "无法运行系统命令"

}

# diff.tcl
msgcat::mcmset zh {

  "    End: "
  "结束："

  "    Start: "
  "开始："

  "Enter difference command"
  "请输入不同的命令"

  "Enter starting file"
  "输入起始文件"

  "Update"
  "升级"

}

# edit.tcl
msgcat::mcmset zh {

  "File successfully written"
  "成功地写入文件"

  "Filename already exists"
  "文件名已经存在"

}

# embed_tke.tcl
msgcat::mcmset zh {

  "Find:"
  "查找"

  "Replace:"
  "替换:"

}

# gui.tcl
msgcat::mcmset zh {

  "All"
  "所有"

  "Case sensitivity"
  "区分大小写"

  "Close All Tabs"
  "關閉全部的頁籤"

  "Close Other Tabs"
  "关闭其他标签"

  "Close Other*"
  "关闭其他*"

  "Close Tab"
  "关闭标签页"

  "Column"
  "列"

  "Copyright"
  "Copyright"

  "Credits"
  "贡献"

  "Delete tab?"
  "删除标签？"

  "Developer"
  "开发者"

  "Email"
  "电子邮箱"

  "Error"
  "錯誤"

  "Favorited"
  "评选"

  "File already exists.  Use '!' to force an overwrite"
  "文件已存在。 使用 '!' 强制覆盖"

  "File attribute does not exist"
  "文件属性不存在"

  "File index is out of range"
  "文件索引超出范围"

  "Hide Tab"
  "隐藏选项卡"

  "Image displayed in fill-in forms which closes the form UI.  Used in forms such as search, search/replace, and find in files."
  "图像显示在填充窗体关闭窗体的用户界面。 用于形式，如搜索，搜索/替换，并在文件中查找。"

  "Image used in tab menus to indicate that the file is associated with a difference view."
  "在选项卡菜单用于指示该文件是与差异视图相关联的图像。"

  "Image used in tab menus to indicate that the file is locked."
  "图像选项卡菜单中用于指示该文件已锁定。"

  "Image used in tab menus to indicate that the file is readonly."
  "选项卡菜单中用于指示该文件是只读的图像。"

  "Image used in tab to indicate that the tab contains a difference view."
  "在选项卡用于指示选项卡包含不同视图的图像。"

  "Image used in tab to indicate that the tab's file is readonly."
  "在选项卡用于指示该标签的文件是只读的图像。"

  "Image used in tab to indicate that the tab’s file is locked."
  "在选项卡用于指示该标签的文件被锁定的图像。"

  "Image used in tab which, when clicked, closes the tab."
  "用图像的选项卡，单击时，将关闭选项卡。"

  "Image used in the preferences window in the Advanced tab."
  "在首选项窗口中高级选项卡所用的图像。"

  "Image used in the preferences window in the Appearance tab."
  "在首选项窗口中外观选项卡中使用的图像。"

  "Image used in the preferences window in the Editor tab."
  "在首选项窗口中编辑器选项卡中使用的图像。"

  "Image used in the preferences window in the Emmet tab."
  "在首选项窗口中的埃米特选项卡所用的图像。"

  "Image used in the preferences window in the Find tab."
  "在首选项窗口中查找选项卡中使用的图像。"

  "Image used in the preferences window in the General tab."
  "在首选项窗口中的常规选项卡所用的图像。"

  "Image used in the preferences window in the Sidebar tab."
  "在首选项窗口中的侧边栏选项卡所用的图像。"

  "Image used in the preferences window in the Snippets tab."
  "在首选项窗口中代码段选项卡中使用的图像。"

  "Image used in the preferences window in the View tab."
  "在视图选项卡中的首选项窗口中使用的图像。"

  "Image used in the preferences window to indicate that a table item is deselected."
  "在首选项窗口用于显示一个表项取消选择图像。"

  "Image used in the preferences window to indicate that a table item is selected."
  "在首选项窗口用于指示表项选中的图像。"

  "Image used in the shortcuts window in the Shortcuts tab."
  "在快捷方式窗口中快捷方式选项卡中使用的图像。"

  "License"
  "许可证"

  "Line"
  "线条"

  "Locked"
  "已锁定"

  "Move"
  "移动"

  "Must be in multicursor mode to insert numbers"
  "必须在 multicursor 模式下插入数字"

  "No write permissions.  Use '!' to force write."
  "没有写权限。 使用 '!'，迫使写。"

  "Release Type"
  "发行类型（特殊）"

  "Reload file?"
  "重装文件？"

  "Replace"
  "替换"

  "Save request"
  "保存请求"

  "Show in Sidebar"
  "显示在侧栏"

  "Starting number:"
  "开始点编号:"

  "Tcl/Tk Version"
  "Tcl/Tk 版本"

  "Total Characters"
  "总字符数"

  "Total Lines"
  "总行数"

  "Unable to successfully parse number string"
  "无法成功分析数字字符串"

  "Unable to write file"
  "无法写入文件"

  "Unable to write remote file"
  "无法写入远程文件"

  "Version"
  "版本"

}

# markers.tcl
msgcat::mcmset zh {

  "Marker name:"
  "标志名称："

}

# menus.tcl
msgcat::mcmset zh {

  "About"
  "关于"

  "Absolute"
  "绝对值"

  "Absolute line numbering"
  "绝对行编号"

  "Align Cursors"
  "對齊光標"

  "Align Panes"
  "对齐窗格"

  "Align current lines in both panes"
  "对齐两个窗格中的当前行"

  "Align cursors"
  "调整光标"

  "All Levels"
  "所有级别"

  "Append Next Occurrence"
  "追加下一個事件"

  "Append next occurrence"
  "追加下一个匹配项"

  "Auto-Indent"
  "自动缩进"

  "Bubble Down"
  "泡下来"

  "Bubble Up"
  "向上冒泡"

  "Bubble lines down one line"
  "泡沫行下移一行"

  "Bubble lines up one line"
  "泡沫排成一条线"

  "Change Working Directory"
  "改变工作目录"

  "Change working directory"
  "改变工作目录"

  "Character"
  "字符"

  "Check for update"
  "檢查更新"

  "Classic Mac"
  "经典的 Mac"

  "Clear All"
  "全部清除"

  "Close All"
  "全部关闭"

  "Close All Folds"
  "关闭所有折叠"

  "Close Current"
  "關閉電流"

  "Close Current Fold"
  "关闭当前折叠"

  "Close Selected Folds"
  "关闭选定的褶皱"

  "Close all folds"
  "关闭所有折叠"

  "Close all tabs"
  "关闭全部标签页"

  "Close current session"
  "关闭当前会话"

  "Close current tab"
  "关闭当前选项卡"

  "Close fold at current line - all levels"
  "在当前行-各级紧密褶皱"

  "Close fold at current line - one level"
  "在当前行-一个级别的紧密褶皱"

  "Close selected folds - all levels"
  "关闭选定的褶皱-所有级别"

  "Close selected folds - one level"
  "关闭选定的褶皱-一个级别"

  "Command"
  "命令"

  "Command Result"
  "命令结果"

  "Convert case to lower"
  "转换大小写来降低"

  "Convert case to title"
  "转换标题为例"

  "Convert case to upper"
  "转换为上部的案例"

  "Copy text"
  "复制文本"

  "Create Fold From Selection"
  "从选择创建折叠"

  "Create at Current Line"
  "創建於當前行"

  "Create fold from selection"
  "从所选内容创建折叠"

  "Create marker at current line"
  "在当前行上创建标记"

  "Create new plugin"
  "创建新的插件"

  "Current Number"
  "当前数量"

  "Cursor from Line Start"
  "光标从行开始"

  "Cursor to Line End"
  "光标移动到行尾"

  "Cut"
  "剪切"

  "Cut text"
  "剪切文本"

  "Delete All Folds"
  "删除所有折叠"

  "Delete Current Fold"
  "删除当前折叠"

  "Delete Selected Folds"
  "删除选定的褶皱"

  "Delete all folds"
  "删除所有折叠"

  "Delete all selected folds"
  "删除所有选定的褶皱"

  "Delete current file"
  "删除当前文件"

  "Delete current line"
  "删除当前行"

  "Delete current word"
  "删除当前的单词"

  "Delete fold at current line"
  "删除当前行折叠"

  "Delete from cursor to end of line"
  "删除从光标结束的行"

  "Delete from start of line to cursor"
  "删除行的起始处到光标处"

  "Delete session"
  "删除会话？"

  "Delete template"
  "删除模板"

  "Delete text between character"
  "删除字符之间的文本"

  "Delete the current number"
  "删除当前号码"

  "Delete the whitespace to left of cursor"
  "删除光标左侧的空白处"

  "Delete the whitespace to right of cursor"
  "删除光标右边的空白"

  "Disable Vim mode"
  "禁用 Vim 模式"

  "Disable code folding"
  "禁用代码折叠"

  "Disable two-pane scrolling Synchronization"
  "禁用两个窗格滚动同步"

  "Display Text Info"
  "显示文字"

  "Display text information"
  "显示文本信息"

  "Duplicate current file"
  "重复当前文件"

  "Edit"
  "编辑"

  "Edit Custom Abbreviations"
  "编辑自定义缩写"

  "Edit Language"
  "编辑语言"

  "Edit Session"
  "编辑日程"

  "Edit User"
  "編輯用戶"

  "Edit custom Emmet abbreviations"
  "编辑自定义埃米特缩写"

  "Edit language snippets"
  "编辑语言片段"

  "Edit session current language preferences"
  "编辑会话当前语言首选项"

  "Edit session global preferences"
  "编辑会话全球首选项"

  "Edit settings sharing preferences"
  "编辑共享首选项的设置"

  "Edit template"
  "删除模板"

  "Edit user current language preferences"
  "编辑用户当前的语言首选项"

  "Edit user global preferences"
  "编辑用户全球首选项"

  "Edit user menu bindings"
  "编辑用户菜单绑定"

  "Edit user snippets"
  "编辑片段"

  "Enable Code Folding"
  "启用代码折叠"

  "Enable Synchronized Scrolling"
  "启用同步滚动"

  "Enable Vim mode"
  "启用 Vim 模式"

  "Enable two-pane scrolling synchronization"
  "使两个窗格滚动同步"

  "Enumeration"
  "列举法"

  "Expand Abbreviation"
  "展开缩写"

  "Expand Emmet abbreviation"
  "展开埃米特缩写"

  "Export As"
  "匯出為："

  "Export Settings"
  "导出设置"

  "Export complete"
  "导出完成"

  "Export file contents"
  "导出文件的内容"

  "Export settings data"
  "导出设置"

  "Favorite file"
  "最喜欢的文件"

  "File Contents"
  "強製文件獲取內容"

  "Find In Files"
  "在文件中查找"

  "Find Matching Bracket"
  "查找匹配的括号"

  "Find Next Bracket Mismatch"
  "查找下一个括号不匹配"

  "Find Previous Bracket Mismatch"
  "找到前括号不匹配"

  "Find and Replace"
  "查找和替换"

  "Find in files"
  "在文件中查找"

  "Find matching character pair"
  "找到匹配的字符对"

  "Find next mismatching bracket"
  "查找下一个匹配括号"

  "Find next occurrence"
  "查找下一个实例"

  "Find previous mismatching bracket"
  "发现以前不匹配的括号"

  "Find previous occurrence"
  "查找上一个"

  "Folding"
  "摺頁"

  "Format Text"
  "设置文本格式"

  "Format indentation for text"
  "文本的缩进格式"

  "From Clipboard"
  "从剪贴板"

  "Global"
  "全局"

  "Goto Last Tab"
  "转到最后一个标签页"

  "Goto Next Tab"
  "转到下一个标签"

  "Goto Other Pane"
  "转到其他窗格"

  "Goto Previous Tab"
  "转到前一个标签"

  "Goto last tab"
  "转到最后一个选项卡"

  "Goto next difference"
  "下一个差异"

  "Goto next tab"
  "转到下一个选项卡"

  "Goto other pane"
  "转到另一窗格"

  "Goto previous difference"
  "上一个差异"

  "Goto previous tab"
  "上一选项卡"

  "Help"
  "帮助"

  "Hide All Tabs"
  "隐藏所有"

  "Hide Console"
  "隐藏控制台"

  "Hide Current Tab"
  "当前标签页"

  "Hide Line Numbers"
  "隐藏行号"

  "Hide Marker Map"
  "隐藏标记地图"

  "Hide Meta Characters"
  "隱藏元字符"

  "Hide Sidebar"
  "隐藏边栏"

  "Hide Status Bar"
  "隐藏状态栏"

  "Hide Tab Bar"
  "隐藏标签栏"

  "Hide console"
  "隐藏控制台"

  "Hide line numbers"
  "行号"

  "Hide marker map"
  "隐藏标记地图"

  "Hide meta characters"
  "隐藏 meta 字符"

  "Hide sidebar"
  "隱藏側邊攔"

  "Hide status bar"
  "显示/隐藏状态栏"

  "Hide tab bar"
  "隐藏选项卡栏"

  "Indent"
  "縮排"

  "Indent Off"
  "关闭缩进"

  "Indent selected text"
  "缩进选定的文本"

  "Indentation"
  "缩进"

  "Insert command result after current line"
  "在当前行之后插入命令结果"

  "Insert enumeration"
  "插入枚举"

  "Insert file contents after current line"
  "在当前行之后插入文件的内容"

  "Insert from clipboard"
  "通过剪贴板插入内容"

  "Insert line above current line"
  "当前行前面插入一行"

  "Insert line below current line"
  "插入当前行下方"

  "Insert snippet"
  "插入代码段"

  "Install"
  "安装"

  "Install plugin"
  "安装新插件"

  "Join Lines"
  "联接线"

  "Join lines"
  "联接线"

  "Jump Backward"
  "向後跳"

  "Jump Forward"
  "跳躍前進"

  "Jump To Line"
  "跳转到行"

  "Jump backward"
  "往後跳"

  "Jump forward"
  "往前跳"

  "Jump to Next Fold Mark"
  "跳转到下一个摺痕"

  "Jump to Previous Fold Mark"
  "跳转到以前的摺痕"

  "Jump to line"
  "跳转到行"

  "Jump to the next fold indicator"
  "跳转到下一个折叠指示器"

  "Jump to the previous fold indicator"
  "跳转到以前的折叠指示器"

  "Line Above Current"
  "高于当前行"

  "Line Below Current"
  "当前下面一行"

  "Line Ending"
  "行尾"

  "Line Number"
  "行號"

  "Line Numbering"
  "行編號"

  "Lock"
  "鎖定"

  "Lock file"
  "锁定文件"

  "Lower Case"
  "小写字母"

  "Markers"
  "标记"

  "Menu"
  "菜单"

  "Menu Bindings"
  "菜单绑定"

  "Merge Panes"
  "合併窗格"

  "Merge panes"
  "合并窗格"

  "Move Cursors Down"
  "将光标向下移动"

  "Move Cursors Left"
  "光标左移"

  "Move Cursors Right"
  "光标右移"

  "Move Cursors Up"
  "向上移动光标"

  "Move cursor to bottom of screen"
  "将光标移动到屏幕的底部"

  "Move cursor to end of current line"
  "移动光标以结束当前行"

  "Move cursor to first line"
  "将光标移动到第一行"

  "Move cursor to last line"
  "将光标移动到最后一行"

  "Move cursor to middle of screen"
  "将光标移动到屏幕的中间"

  "Move cursor to next page"
  "将光标移动到下一个页面"

  "Move cursor to next word"
  "将光标移动到下一个单词"

  "Move cursor to previous page"
  "将光标移动到前一页"

  "Move cursor to previous word"
  "将光标移动到前一个单词"

  "Move cursor to start of current line"
  "将光标移至当前行首"

  "Move cursor to top of screen"
  "将光标移动到屏幕的顶部"

  "Move multicursors down one line"
  "Multicursors 下移一行"

  "Move multicursors left one line"
  "移动 multicursors 左的一行"

  "Move multicursors right one line"
  "移动 multicursors 右一线"

  "Move multicursors up one line"
  "移动 multicursors 上一行"

  "Move to First Line"
  "移动到第一行"

  "Move to Last Line"
  "移动，最后一行"

  "Move to Line End"
  "移动行结束"

  "Move to Line Start"
  "移动线开始"

  "Move to Next Page"
  "移到下一页"

  "Move to Next Word"
  "移动到下一个单词"

  "Move to Previous Page"
  "移动到前一页"

  "Move to Previous Word"
  "移动到前一个单词"

  "Move to Screen Bottom"
  "移动到屏幕底部"

  "Move to Screen Middle"
  "移动屏幕中间"

  "Move to Screen Top"
  "移动屏幕顶部"

  "Move to other pane"
  "移动到另一个窗格"

  "New From Template"
  "由模板新建"

  "New Window"
  "新窗口"

  "New file"
  "新建文件"

  "New file from template"
  "模板新建的文件"

  "New window"
  "新建窗口"

  "Next Difference"
  "接下來差異"

  "One Level"
  "一个级别"

  "Open All Folds"
  "打开所有折叠"

  "Open Current Fold"
  "打开当前折叠"

  "Open Directory"
  "打开目录"

  "Open Favorite"
  "打开收藏"

  "Open File"
  "打开文件"

  "Open Recent"
  "打开最近"

  "Open Remote"
  "远程"

  "Open Selected Folds"
  "打开选择的褶皱"

  "Open all folds"
  "打开所有折叠"

  "Open directory"
  "開啟目錄"

  "Open file"
  "打开文件"

  "Open fold at current line - all levels"
  "在当前行的所有级别打开折叠"

  "Open fold at current line - one level"
  "在当前行-一个级别打开折叠"

  "Open folds to show cursor"
  "开放的褶皱，显示光标"

  "Open remote file or directory"
  "打开远程文件或目录"

  "Open selected folds - all levels"
  "打开选定的褶皱-所有级别"

  "Open selected folds - one level"
  "打开选定的褶皱-一个级别"

  "Panes"
  "窗格"

  "Paste"
  "粘贴"

  "Paste and Format"
  "粘贴和格式"

  "Paste and format text from clipboard"
  "从剪贴板粘贴和格式文本"

  "Paste text from clipboard"
  "从剪贴板粘贴文本"

  "Previous Difference"
  "上一頁差異"

  "Profiling Report Sorted By"
  "按排序的分析报告"

  "Profiling started"
  "分析开始"

  "Profiling stopped"
  "停止剖析"

  "Quit"
  "退出"

  "Quit application"
  "退出应用程序"

  "Recent Directories"
  "最近的目录"

  "Recent Files"
  "最近的文件"

  "Redo"
  "重複"

  "Relative"
  "亲戚"

  "Relative line numbering"
  "相对行号"

  "Reload"
  "重新加载"

  "Reload all plugins"
  "重新加载所有的插件"

  "Reload snippets"
  "重新加载的代码段"

  "Reload template information"
  "重新加载模板信息"

  "Remove All Markers"
  "刪除所有標記"

  "Remove From Current Line"
  "從當前行中刪除"

  "Remove all markers"
  "删除所有标记"

  "Remove marker from current line"
  "删除从当前行的标记"

  "Rename current file"
  "重命名当前文件"

  "Reopen File"
  "重新打开文件"

  "Reopen current file"
  "重新打开当前文件"

  "Replace Line With Script"
  "替換線隨著腳本"

  "Replace line with script"
  "用脚本替换行"

  "Reset User to Base"
  "将用户重置为基地"

  "Restart"
  "重新启动"

  "Run"
  "运行"

  "Run theme editor"
  "运行主题编辑器"

  "Save All"
  "全部儲存"

  "Save As Remote"
  "另存为远程"

  "Save As Template"
  "另保存模板"

  "Save Current"
  "保存當前"

  "Save Selection As"
  "保存作为选择"

  "Save all files"
  "保存所有文件"

  "Save current session"
  "当前会话"

  "Save file"
  "另存文件"

  "Save file as"
  "保存文件为..."

  "Save file as remote file"
  "将文件另存为远程文件"

  "Save file as template"
  "保存模板"

  "Save selected lines"
  "保存所选的行"

  "Save sessions as"
  "保存会话作为"

  "Select All"
  "全选"

  "Select All Occurrences"
  "選擇所有事例"

  "Select Next Occurrence"
  "選擇下一個發生"

  "Select Previous Occurrence"
  "選擇上發生"

  "Select all occurrences"
  "选择所有匹配项"

  "Select all text"
  "选择文本"

  "Send Bug Report"
  "发送报告"

  "Send Feedback"
  "发送 feedback"

  "Send bug report"
  "缺陷跟踪管理系统"

  "Send feedback"
  "发送反馈"

  "Set Syntax"
  "设置语法"

  "Set Theme"
  "设置主题"

  "Set User to Global"
  "设置的用户到全球"

  "Set current file line ending to CR for Classic Mac"
  "设置当前文件行 CR 为经典 Mac 的结局"

  "Set current file line ending to CRLF for Windows"
  "设置当前文件行到 CRLF Windows 结束"

  "Set current file line ending to LF for Unix"
  "设置当前文件行结束到 LF unix"

  "Set indent mode to"
  "将缩进模式设置为"

  "Set user bindings to global bindings"
  "设置用户绑定到全局绑定"

  "Set user preferences to global preferences"
  "设置的用户首选项设置为全局首选项"

  "Show All Tabs"
  "显示所有选项卡"

  "Show Console"
  "显示控制台"

  "Show Cursor"
  "显示光标"

  "Show Diagnostic Logfile"
  "显示诊断日志文件"

  "Show File Difference"
  "显示不同"

  "Show Last Profiling Report"
  "显示最后剖析报告"

  "Show Line Numbers"
  "显示数字"

  "Show Marker Map"
  "显示标记"

  "Show Meta Characters"
  "顯示元字符"

  "Show Selected Line Change"
  "顯示選定的線路變化"

  "Show Sidebar"
  "显示侧边栏"

  "Show Status Bar"
  "显示状态"

  "Show Tab Bar"
  "显示标签栏"

  "Show diagnostic logfile"
  "显示诊断日志文件"

  "Show file difference"
  "显示不同"

  "Show last profiling report"
  "显示上次分析报告"

  "Show meta characters"
  "显示 meta 字符"

  "Show selected line change"
  "显示所选的行的变化"

  "Smart Indent"
  "智能缩进"

  "Snippet"
  "片段"

  "Sort Tabs"
  "分类标签"

  "Sort tabs"
  "排序选项卡"

  "Start Profiling"
  "开始分析"

  "Start profiling"
  "启动性能分析"

  "Stop Profiling"
  "停止分析"

  "Stop profiling"
  "停止性能分析"

  "Switch To"
  "切換到"

  "Switch to session"
  "切换到会话"

  "Tabs"
  "標籤"

  "Text Between Character"
  "字符之间的文本"

  "Tips & Tricks"
  "自定义"

  "Title Case"
  "词首字母大写"

  "Toggle Case"
  "切换大小写"

  "Toggle Comment"
  "切換註釋"

  "Toggle case of current character"
  "切换大小写的当前字符"

  "Toggle comment"
  "开启/关闭注释"

  "Toggle split view mode"
  "拆分视图模式切换:"

  "Tools"
  "工具"

  "Transform"
  "变换"

  "Unable to write export file"
  "无法写入导出文件"

  "Undo"
  "復原"

  "Unfavorite file"
  "太罗嗦的文件"

  "Unindent"
  "取消缩进"

  "Unindent selected text"
  "取消所選文本的縮排"

  "Uninstall"
  "卸载"

  "Uninstall plugin"
  "卸载插件"

  "Unix"
  "Unix"

  "Unlock"
  "解锁用户"

  "Unlock file"
  "解锁文件"

  "Upper Case"
  "大寫字母"

  "User Guide"
  "用户指南"

  "View"
  "查看"

  "View Base"
  "视图基础"

  "View Global"
  "查看全球"

  "View base preferences file"
  "查看基地首选项文件"

  "View global menu bindings"
  "查看全局菜单绑定"

  "View tips & tricks articles"
  "视图提示与技巧的文章"

  "View user guide"
  "用户指南"

  "Vim Mode"
  "Vim的模式"

  "Whitespace Backward"
  "落后的空白"

  "Whitespace Forward"
  "空格前"

  "Windows"
  "Windows"

}

# plugins.tcl
msgcat::mcmset zh {

  "Always grant from developer"
  "从开发人员总是给予"

  "ERROR"
  "错误"

  "ERROR:  Plugin name already exists"
  "错误：插件名称已存在"

  "ERROR:  Plugin name is not valid (only alphanumeric and underscores are allowed)"
  "错误：插件名称无效（字母数字和下划线是允许的）"

  "ERROR:  Unable to create plugin directory"
  "错误：无法创建插件目录"

  "ERROR:  Unable to write plugin files"
  "错误：无法写入文件的插件"

  "Enter plugin name"
  "输入插件名称"

  "Grant"
  "授予"

  "Grant permission?"
  "格兰特PERMSSION？"

  "Plugin Errors"
  "插件错误"

  "Plugin Trust Requested"
  "插件信任请求"

  "Plugin installed"
  "插件已安装"

  "Plugin requires permission to view or modify your system."
  "插件需要权限来查看或修改您的系统。"

  "Plugin uninstalled"
  "插件已卸载"

  "Plugins successfully reloaded"
  "插件重新加载成功"

  "Reject"
  "拒绝"

  "Syntax errors found in selected plugins"
  "在选定的外挂，发现语法错误"

}

# pref_ui.tcl
msgcat::mcmset zh {

  "Abbreviation Aliases"
  "缩写别名"

  "Add"
  "添加"

  "Addons"
  "插件"

  "Allow scrolling in tab bar"
  "允许在标签栏中滚动"

  "Angled bracket"
  "直角的支架"

  "Auto-match Characters"
  "自动匹配字符"

  "Automatically check for updates on start"
  "自动检查更新开始"

  "Automatically highlight matching bracket"
  "自动突出显示匹配的括号"

  "Automatically highlight mismatching brackets"
  "自动突出显示不匹配的括号"

  "Automatically insert vendor prefixes"
  "自动插入供应商前缀"

  "Automatically load last session on start"
  "自动加载上一届会议上开始"

  "Automatically set the current working directory to the current tabs directory"
  "自动将当前的工作目录设置为当前选项卡目录"

  "Backtick"
  "引号"

  "Base Directory"
  "基目录"

  "Behaviors"
  "行为"

  "Buffer"
  "缓冲区"

  "Choose"
  "選擇"

  "Choose Logfile Directory"
  "选择日志文件目录"

  "Clear"
  "清空"

  "Clipboard"
  "剪贴板"

  "Clipboard history depth"
  "剪贴板历史深度"

  "Color value case"
  "颜色值"

  "Command launcher entry"
  "命令启动程序项"

  "Command launcher preview"
  "命令启动程序预览"

  "Convert to lowercase"
  "转换为小写"

  "Convert to uppercase"
  "轉換為大寫"

  "Curly bracket"
  "花括号"

  "Current"
  "现金"

  "Current Directory"
  "目前的目錄"

  "Current File Pathname"
  "当前的文件路径名"

  "Current Filename"
  "当前文件名"

  "Current Line Column"
  "当前列"

  "Current Line Number"
  "当前行号"

  "Current editing buffer directory"
  "当前编辑缓冲区目录"

  "Current working directory"
  "当前工作目录"

  "Date"
  "日期"

  "Default Markdown Export Extension"
  "默认降价出口扩展名"

  "Default unit for floating point values"
  "默认单位为浮点值"

  "Default unit for integer values"
  "默认单位为整数值的"

  "Delete snippet"
  "删除代码段"

  "Development"
  "开发"

  "Double-quote"
  "\"

  "Edit preferences using GUI"
  "编辑首选项使用 GUI"

  "Editor"
  "编辑"

  "Enable Vim Mode"
  "启用 Vim 模式"

  "Enable auto-indentation"
  "启用自动缩进"

  "Enable development mode"
  "使发展模式"

  "Enable fuzzy search"
  "使模糊搜索"

  "Enable relative line numbering"
  "启用相对行号"

  "End-of-line character when saving"
  "行尾字符保存时"

  "Exit the application after the last tab is closed"
  "最后一个选项卡关闭后退出应用程序"

  "Format snippet indentation after insert"
  "格式代码段缩进后插入"

  "General"
  "通用"

  "Hide Patterns"
  "隐藏模式"

  "Hide binary files"
  "隐藏的二进制文件"

  "Hiding"
  "棄保潛逃"

  "Host"
  "主机"

  "Indentation Spaces"
  "缩进空格"

  "Keyword"
  "关键词"

  "Languages"
  "语言"

  "Last"
  "最后"

  "Last accessed"
  "最后访问："

  "Line count to find for Vim modeline information"
  "行计数来寻找 Vim modeline 信息"

  "Logfile Directory"
  "日志文件目录"

  "Maximum undo history (set to 0 for unlimited)"
  "最大撤消历史记录 (设置为 0 表示无限制)"

  "Menu bindings"
  "菜单绑定"

  "Mounts"
  "坐骑"

  "Node Aliases"
  "别名"

  "Parenthesis"
  "括号"

  "Profiler Options"
  "探查器选项"

  "Properties"
  "房源"

  "Recently opened history depth"
  "最近打开历史深度"

  "Remember last position of command launcher"
  "请记住命令启动程序的最后一个位置"

  "Remote Base Directory"
  "远程的基目录"

  "Remove root directory after last sub-file is closed"
  "最后一个子文件关闭后删除根目录"

  "Remove trailing whitespace on save"
  "删除尾随空格上保存"

  "Report Options"
  "报表选项"

  "Retain case"
  "保留案例"

  "Return"
  "返回"

  "Ruler column"
  "统治者列"

  "Search Shortcuts"
  "搜尋捷徑鍵"

  "Search Snippets"
  "搜索代码段"

  "Select Settings Sharing Directory"
  "选择设置共享目录"

  "Select default browsing directory"
  "选择默认浏览目录"

  "Selected Text"
  "所选文字"

  "Set"
  "设置"

  "Set Find History Depth"
  "设置查找历史深度"

  "Set Find in Files Line Context"
  "在文件行上下文中设置查找"

  "Set Jump Distance"
  "设置的跳距离"

  "Set default open/save browsing directory to"
  "设置默认打开/保存浏览目录"

  "Sharing Items"
  "共享项目"

  "Shortcut"
  "快捷键"

  "Shortcuts"
  "快捷键"

  "Show 'Find in Files' result in other pane"
  "在其他窗格中显示在文件中查找结果"

  "Show diagnostic logfile at startup"
  "启动时显示诊断日志文件"

  "Show difference file in other pane than original"
  "在其他窗格中比原始显示差异文件"

  "Show difference file version information"
  "显示差异文件版本信息"

  "Show folders at top"
  "显示在顶部的文件夹"

  "Show menubar"
  "显示菜单栏"

  "Single-quote"
  "单引号"

  "Snippet Completion Characters"
  "代码段完成字符"

  "Snippet Text"
  "文字片段"

  "Sort tabs alphabetically on open"
  "排序按字母顺序在打开的标签页"

  "Sorting Column"
  "列进行排序"

  "Space"
  "空间"

  "Spaces per tab"
  "每个制表位"

  "Square bracket"
  "方括号"

  "Stable"
  "稳定"

  "Symbol between CSS property and value"
  "CSS 属性和值之间的符号"

  "Symbol placed at end of CSS property"
  "将符号放置在 CSS 属性的结尾"

  "Syntax Coloring"
  "语法着色"

  "Tab"
  "Tab標籤"

  "Tab Stop"
  "制表符"

  "Time"
  "时间"

  "Update using release type"
  "更新使用释放类型"

  "Updates"
  "更新"

  "Use appropriate EOL character on system"
  "在系统上使用适当的 EOL 字符"

  "Use carriate return linefeed sequence"
  "使用 carriate 返回换行符序列"

  "Use directory"
  "使用目录"

  "Use linefeed character"
  "使用换行符的字符"

  "Use original EOL character from file"
  "使用文件的原始的 EOL 字符"

  "Use shortened colors"
  "使用缩短的颜色"

  "Use single carriage return character"
  "使用单个回车符"

  "User guide format"
  "用户指南格式"

  "Variables"
  "變量"

}

# remote.tcl
msgcat::mcmset zh {

  "Close Connection"
  "关闭连接？"

  "Create New Folder"
  "创建新文件夹"

  "Delete Connection"
  "删除连接"

  "Delete Group"
  "删除群组"

  "Delete connection?"
  "删除连接吗？"

  "Delete group?"
  "删除群组"

  "Edit Connection"
  "编辑连接"

  "Enter Password"
  "输入密码"

  "Folder Name"
  "文件夹名"

  "Group"
  "群组"

  "Group Name"
  "群组名称"

  "Group Name: "
  "分组名称："

  "Image used in remote file selector to indicate a file."
  "在远程文件选择器中用于指示文件的图像。"

  "Image used in remote file selector to indicate a folder."
  "在远程文件选择器中用于指示文件夹中的图像。"

  "Image used in remote file selector to indicate that a connection is being opened."
  "在远程文件选择器中用于指示连接被打开的图像。"

  "Image used in remote file selector to indicate that a connection is opened."
  "在远程文件选择器中用于指示连接打开的图像。"

  "Name"
  "您的姓名"

  "New Connection"
  "新建连接"

  "New Folder"
  "新文件夹"

  "New Group"
  "新集团"

  "Open Connection"
  "打开连接"

  "Open Remote File"
  "远程文件"

  "Optional"
  "選擇性"

  "Password"
  "密码"

  "Password: "
  "密码："

  "Port"
  "端口号"

  "Remote Directory"
  "远程目录"

  "Rename Group"
  "重新命名群組"

  "Save File Remotely"
  "将文件保存到远程"

  "Server"
  "服务器"

  "Test"
  "测试"

  "Test Connection"
  "测试连接"

  "Type"
  "类型"

  "Unable to connect to"
  "无法连接"

  "Username"
  "用户名"

  "server"
  "服务器"

}

# search.tcl
msgcat::mcmset zh {

  "No files found in specified directories"
  "指定的目录中未找到文件"

  "No search results found"
  "个搜索结果"

  "Search wrapped to beginning of file"
  "搜索到文件的开头包裹"

  "Search wrapped to end of file"
  "搜索包裹到文件结尾"

  "substitutions done"
  "换人做"

}

# sessions.tcl
msgcat::mcmset zh {

  "Save session?"
  "保存会话"

  "Session state will be lost if not saved"
  "如果不保存会话状态都将丢失"

}

# share.tcl
msgcat::mcmset zh {

  "Emmet"
  "蚂蚁"

  "Export Settings Data"
  "导出设置"

  "Favorites"
  "收藏"

  "Remote Connections"
  "远程连接"

  "Settings to export"
  "要导出的设置"

  "Sharing Setup"
  "共享设置"

  "Themes"
  "主題"

}

# sidebar.tcl
msgcat::mcmset zh {

  "Add Parent Directory"
  "母目錄"

  "Close Directory Files"
  "关闭目录文件"

  "Copy Pathname"
  "複製路徑名"

  "Delete directories?"
  "删除目录吗?"

  "Delete directory?"
  "删除目录？"

  "Delete file?"
  "删除文件？"

  "Delete files?"
  "删除文件?"

  "Directory Name:"
  "目录名称:"

  "Disconnect From Server"
  "从服务器断开连接"

  "Folder Name:"
  "文件夾名稱:"

  "Hide"
  "隐藏"

  "Hide Directory Files"
  "隐藏目录文件"

  "Image displayed in sidebar to indicate a directory that is collapsed"
  "在侧边栏来指示折叠目录中显示图像"

  "Image displayed in sidebar to indicate a directory that is showing its contents"
  "在侧边栏来指示显示其内容的目录中显示图像"

  "Image displayed in sidebar to indicate a file"
  "在侧边栏来指示文件中显示图像"

  "Image displayed in sidebar to indicate a selected directory that is collapsed"
  "在侧边栏来指示折叠所选的目录中显示图像"

  "Image displayed in sidebar to indicate a selected directory that is expanded"
  "在侧边栏来指示扩展所选的目录中显示图像"

  "Image displayed in sidebar to indicate that a file is currently opened but hidden"
  "图像显示在侧栏以指示文件当前是打开，但隐藏"

  "Image displayed in sidebar to indicate that a file is currently opened in an editing buffer."
  "在侧边栏来指示在编辑缓冲区中当前打开文件中显示的图像。"

  "Make Current Working Directory"
  "使当前工作目录"

  "New Directory"
  "新目录"

  "New File From Template"
  "模板新建的文件"

  "Open Directory Files"
  "打开目录文件"

  "Refresh Directory Files"
  "刷新目录文件"

  "Remove Parent from Sidebar"
  "从边栏移除父"

  "Remove from Sidebar"
  "从边栏移除"

  "Show"
  "显示"

  "Show Difference"
  "显示不同"

  "Show Directory Files"
  "显示目录文件"

}

# snippets.tcl
msgcat::mcmset zh {

  "Snippet: *"
  "片段"

}

# startup.tcl
msgcat::mcmset zh {

  "Change Directory"
  "切换目录"

  "Copies settings data from an existing directory to your home directory.  Click 'Customize Settings' below to customize which settings data will be copied."
  "将设置数据从现有的目录复制到您的主目录。 单击自定义设置下面自定义哪些设置数据将被复制。"

  "Copy settings from directory"
  "从目录复制设置"

  "Create settings locally"
  "创建本地设置"

  "Creates new settings information and places it in your home directory"
  "创建新设置信息，并将其放在您的主目录"

  "Finish"
  "完成"

  "If you need would like to change your settings location and/or data, you can do so within the Edit/Sharing/Edit... menu."
  "如果你需要想要改变你的设置位置和/或数据，你可以在编辑/共享/菜单编辑...。"

  "Items that are selected will be copied to your local home directory. Items that are not selected will be created in your home directory."
  "选定的项将复制到您当地的主目录。未选中的项目将在您的主目录中创建。"

  "Items that are selected will be shared with other computers. Items that are not selected will be stored locally and will not be shared."
  "选定的项将与其他计算机共享。未选中的项目将存储在本地，并不会被共享。"

  "Next"
  "下一个"

  "Select Settings Directory"
  "选择设置目录"

  "Settings"
  "设置"

  "Settings Options"
  "設置選項"

  "Setup Complete"
  "安装完成"

  "Share"
  "分享"

  "Shares settings data from a new or existing directory (ex., iCloud Drive, Google Drive, Dropbox, etc.).  Any changes made to settings data will be available to other sharers.  Click 'Customize Settings' below to customize which settings data will be shared."
  "共享设置数据从一个新的或现有的目录 (例如，iCloud 谷歌驱动器，Dropbox，等.)。 对设置数据所做的任何更改将提供到其他的共享资源文件。 单击自定义设置下面自定义的设置数据将共享。"

  "Thanks for using TKE, the advanced programmer's editor.  Since this is a new installation of TKE, let's help you get things set up. \\n \\n Click 'Next' below to get things going."
  "感谢您使用将军澳支线，高级的程序员编辑器。 由于这是一个新安装的将军澳支线，让我们帮助你把事情设置。\\n \\n 点击下一步来维持生活。"

  "Use shared settings"
  "使用共享的设置"

  "Welcome"
  "歡迎"

  "Welcome To"
  "欢迎来到"

}

# syntax.tcl
msgcat::mcmset zh {

  "Syntax"
  "语法"

  "Syntax error in syntax file"
  "在语法文件中的语法错误"

}

# templates.tcl
msgcat::mcmset zh {

  "Delete template?"
  "删除模板"

  "Template"
  "模板"

  "Template Name"
  "模板名称"

  "deleted"
  "已删除"

  "saved"
  "已经保存"

  "will be permanently deleted"
  "將被永久刪除"

}

# theme.tcl
msgcat::mcmset zh {

  "Background (trough) color used in the sidebar scrollbar."
  "用在侧边栏滚动条的背景 (槽) 颜色。"

  "Background (trough) color used in the text scrollbars."
  "用在文本滚动条的背景 (槽) 颜色。"

  "Background color displayed in embedded language code."
  "在嵌入式的语言代码中显示的背景色。"

  "Background color for all sidebar items that are not selected."
  "所有未选中的侧边栏项的背景色。"

  "Background color for all sidebar items that are selected."
  "所有选定的侧边栏项的背景色。"

  "Background color in difference viewer that shows added lines."
  "在差异查看器中显示的背景色添加行。"

  "Background color in difference viewer that shows deleted lines."
  "背景颜色显示的差异查看器中删除行。"

  "Background color of insertion cursor and background marker colors."
  "插入光标和背景颜色标记背景颜色。"

  "Background color of the editing buffer."
  "编辑缓冲区的背景色。"

  "Background color to display when a button-like ttk widget is pressed."
  "要显示按下一个按钮类似 ttk 小部件时的背景颜色。"

  "Background color to use for displaying character information that requires the user's attention."
  "用来显示字符信息，需要用户注意的背景色。"

  "Background color to use for selected text."
  "要用于所选文本的背景色。"

  "Background color used for all other tabs that are not the current/active tab in the tabbar."
  "用其他的选项卡，是不是在 tabbar 电流/活动选项卡的背景颜色。"

  "Background color used for the current/active menu item."
  "用当前/主菜单项的背景颜色。"

  "Background color used for the current/active tab in the tabbar."
  "用 tabbar 在当前/活动选项卡的背景颜色。"

  "Background color used in highlighted text."
  "在突出显示的文本所用的背景颜色。"

  "Background color used in menus."
  "在菜单中所用的背景颜色。"

  "Background color used in the tabbar area."
  "在 tabbar 地区所用的背景颜色。"

  "Color of border drawn around active editing buffer."
  "在活跃的编辑缓冲区周围绘制的边框的颜色。"

  "Color of ttk entry widget text border when the entry has keyboard focus."
  "当该条目具有键盘焦点时 ttk 条目构件文本边框的颜色。"

  "Color used to draw the warning width line in the editing buffer (as well as the line separating the gutter from the editing buffer)."
  "用来绘制中编辑缓冲区 (以及线装订线分离编辑缓冲区) 的警告宽度线的颜色。"

  "Default 'darkcolor' for all ttk widgets."
  "默认为所有 ttk 部件 ' 灯光'。"

  "Default background color to use for all ttk widgets that are in a disabled state."
  "默认背景颜色用于所有 ttk 部件处于禁用状态。"

  "Default background color to use for all ttk widgets when the mouse cursor hovers over the widget."
  "默认背景颜色时鼠标光标悬停在小部件要使用的所有 ttk 部件。"

  "Default background color to use for all ttk widgets."
  "默认背景颜色用于所有 ttk 部件。"

  "Default border color for all ttk widgets."
  "所有的 ttk 部件的默认边框颜色。"

  "Default color for non-syntax highlighted text."
  "非语法突出显示的文本的默认颜色。"

  "Default foreground text color to use for all ttk widgets that are in a disabled state."
  "默认前景色文本颜色用于所有 ttk 部件处于禁用状态。"

  "Default foreground text color to use for all ttk widgets."
  "默认前景色文本颜色用于所有 ttk 部件。"

  "Determines the number of grips strips to display in the grip area between resizable panes."
  "决定握把带在了抓地力之间可调整大小的窗格中显示的数目。"

  "Determines the thickness of the grip area between resizable panes."
  "确定了抓地力可调整大小的窗格之间的厚度。"

  "ERROR:  Unable to read"
  "错误: 无法读取"

  "Foreground (slider) color used in the sidebar scrollbar."
  "(滑块) 使用前景色在侧边栏滚动条。"

  "Foreground (slider) color used in the text scrollbars when pane synchronization is enabled."
  "（滑块） 使用前景色在文本滚动条时启用窗格同步。"

  "Foreground (slider) color used in the text scrollbars."
  "(滑块) 使用前景色在文本滚动条。"

  "Foreground color used in menu items with checks or buttons."
  "在用支票或按钮的菜单项所用的前景颜色。"

  "Foreground text color for strings."
  "字符串文本景色。"

  "Foreground text color to use for all miscellaneous1 labeled text."
  "用于所有 miscellaneous1 的前景文本颜色标记文本。"

  "Foreground text color to use for all miscellaneous2 labeled text."
  "用于所有 miscellaneous2 的前景文本颜色标记文本。"

  "Foreground text color to use for all miscellaneous3 labeled text."
  "用于所有 miscellaneous3 的前景文本颜色标记文本。"

  "Foreground text color to use for comments."
  "用于注释的前景文本颜色。"

  "Foreground text color to use for displaying line numbers."
  "用于显示行号的前景文本颜色。"

  "Foreground text color to use for displaying numbers."
  "用来显示数字的前景文本颜色。"

  "Foreground text color to use for language-specific keywords."
  "用于语言特定的关键字的前景文本颜色。"

  "Foreground text color to use for language-specific punctuation."
  "要用于特定语言的标点符号的前景文本颜色。"

  "Foreground text color to use for meta syntax."
  "用于元语法的前景文本颜色。"

  "Foreground text color to use for precompiler syntax."
  "用于预编译器语法的前景文本颜色。"

  "Foreground text color to use for selected text."
  "要用于所选文本的前景文本颜色。"

  "Foreground text color used for all other tabs that are not the current/active tab in the tabbar."
  "用其他的选项卡，是不是在 tabbar 电流/活动选项卡的前景文本颜色。"

  "Foreground text color used for menus item that are disabled."
  "文本使用前景色为被禁用的菜单项。"

  "Foreground text color used for the current/active menu item."
  "用当前/主菜单项的前景文本颜色。"

  "Foreground text color used for the current/active tab in the tabbar."
  "用当前/活动选项卡中的 tabbar 前景文本颜色。"

  "Foreground text color used in menus."
  "在菜单中所用的前景文本颜色。"

  "Foreground text/image color used in tabbar and tabs."
  "文本/图像使用前景色 tabbar 和选项卡中。"

  "Images"
  "图像"

  "Maximum thickness of the text scrollbar when it is active."
  "文本滚动条时处于活动状态的最大厚度。"

  "Maximum thickness of the text scrollbars when they are active."
  "最大厚度的文本滚动条时他们是活跃的。"

  "Menu Options"
  "菜单选项"

  "Menu relief value."
  "菜单救济值。"

  "Pixel height of the tabbar widget."
  "Tabbar 小部件的像素高度。"

  "Relief used in drawing the tabs."
  "使用绘图选项卡中的救济。"

  "Relief value of the sidebar area."
  "救济的侧栏区域的值。"

  "Sidebar Options"
  "侧边栏选项"

  "Sidebar Scrollbar Options"
  "侧边栏滚动条选项"

  "Specifies the color to display around the sidebar when the sidebar does not have the focus."
  "指定要显示在侧边栏时侧边栏没有焦点的颜色。"

  "Specifies the color to display around the sidebar when the sidebar has the focus."
  "指定要显示在侧边栏侧边栏获得焦点时的颜色。"

  "Specifies the default background color to use for text that is selected in a standard ttk widget (this does not include the editing buffer)."
  "指定要用于在标准 ttk 窗口小部件 (这不包括编辑缓冲区) 中选择的文本的默认背景色。"

  "Specifies the default foreground text color to use for text that is selected in a standard ttk widget (this does not include the editing buffer)."
  "指定要用于在标准 ttk 窗口小部件 (这不包括编辑缓冲区) 中选择的文本的默认前景文本颜色。"

  "Specifies the default relief to use when drawing ttk widgets."
  "指定绘制 ttk 部件时要使用的默认救济。"

  "Specifies the pixel thickness of the highlight line."
  "指定像素的突出显示线的粗细。"

  "Syntax Colors"
  "语法颜色"

  "Tab Options"
  "TAB选项"

  "Text Scrollbar Options"
  "文字滚动条选项"

  "Text color for all sidebar items that are not selected."
  "所有未选中的侧边栏项目的文本颜色。"

  "Text color for all sidebar items that are selected."
  "所有选定的侧边栏项的文本颜色。"

  "ttk Widget Colors"
  "TTK的Widget颜色"

}

# themer.tcl
msgcat::mcmset zh {

  "   Show Selected Option"
  "显示当前选项"

  "   Show Selected Value"
  "選擇值"

  "Categories"
  "分类"

  "Change Base Color"
  "更改颜色"

  "Choose Theme"
  "选择主题"

  "Custom Directory"
  "自定义目录"

  "Custom..."
  "自定义..."

  "Delete swatch?"
  "删除色盘"

  "Description"
  "描述"

  "Details"
  "详细"

  "Done"
  "完成"

  "Enable Copy Mode"
  "启用复制模式"

  "GIF Photo"
  "GIF图片"

  "Import"
  "進口"

  "Import BMP Data"
  "匯入資料"

  "Import BMP Mask"
  "导入BMP面膜"

  "Import Error"
  "﻿导入错误"

  "Import Theme File"
  "导入主题文件"

  "Installation Directory"
  "安装目录"

  "Modifications"
  "其他"

  "One-Color Bitmap"
  "单色位图"

  "Paste Theme Items"
  "粘贴主题项目"

  "Relief: "
  "救济"

  "Save As:"
  "另存為:"

  "Save theme changes?"
  "保存主题的变化？"

  "Search"
  "搜索"

  "Select Directory"
  "选择目录"

  "Show All"
  "显示全部"

  "Show Category"
  "显示类别"

  "Show Color"
  "显示背景颜色"

  "Show Selected Option"
  "显示所选的选项"

  "Show Selected Value"
  "選擇值"

  "Swatch"
  "色盘"

  "Swatch Colors"
  "斯沃琪颜色"

  "Table Copy"
  "表复制"

  "Table Filters"
  "表过滤器"

  "Table Search"
  "表搜索"

  "The current theme has unsaved changes"
  "目前的主题有未保存的更改"

  "Tree Style: "
  "树风格："

  "Two-Color Bitmap"
  "双色位图"

  "User Directory"
  "用户目录"

  "Value"
  "數值"

  "Value: "
  "值:"

}

# themes.tcl
msgcat::mcmset zh {

  "Theme:*"
  "主题"

}

# tke.tcl
msgcat::mcmset zh {

  "Import TKE theme?"
  "进口TKE主题？"

  "Import TextMate theme?"
  "进口TextMate的主题？"

}

# tkedat.tcl
msgcat::mcmset zh {

  "Unable to read"
  "无法读取"

}

# vim.tcl
msgcat::mcmset zh {

  "File format unrecognized"
  "无法识别的文件格式"

  "Filename directory does not exist"
  "文件名的目录不存在"

  "Folding method unrecognized"
  "折叠方法无法识别"

  "Illegal modelines value"
  "非法 modeline 值"

  "Number width not a number"
  "数字宽度不是一个数字"

  "Shiftwidth value is not an integer"
  "数值非整数。"

  "Tabstop value is not an integer"
  "数值非整数。"

  "Unrecognized vim option"
  "无法识别的 vim 选项"

}

# General
msgcat::mcmset zh {

  "Back"
  "返回"

  "Browse"
  "瀏覽"

  "Cancel"
  "取消"

  "Check for Update"
  "检查更新"

  "Close"
  "关闭"

  "Copy"
  "复制"

  "Create"
  "创建"

  "Current Line"
  "当前行"

  "Current Word"
  "当前的单词"

  "Cursor"
  "光标"

  "Delete"
  "刪除"

  "Directory"
  "目錄"

  "Duplicate"
  "复制"

  "Enable code folding"
  "启用代码折叠"

  "Export"
  "导出"

  "Favorite"
  "我的最愛"

  "File"
  "文件"

  "File Name:"
  "文件名："

  "Find"
  "查找"

  "Insert"
  "插入"

  "Language"
  "语言"

  "Launcher"
  "发射台"

  "Move to Other Pane"
  "移动到另一个窗格"

  "New File"
  "新文件"

  "None"
  "无"

  "OK"
  "確定"

  "Open"
  "打开"

  "Plugins"
  "插件"

  "Preferences"
  "首选项"

  "Preview"
  "預覽"

  "Rename"
  "重命名"

  "Save"
  "保存"

  "Save As"
  "保存为"

  "Sessions"
  "會議"

  "Sharing"
  "分享"

  "Show console"
  "显示航行控制台"

  "Show line numbers"
  "显示行号"

  "Show marker map"
  "显示标记"

  "Show sidebar"
  "显示侧边栏"

  "Show status bar"
  "显示状态栏"

  "Show tab bar"
  "显示选项栏"

  "Snippets"
  "片段"

  "Split View"
  "拆分視圖"

  "Templates"
  "模板"

  "Theme"
  "主题"

  "Theme Editor"
  "主题编辑器"

  "Unable to write"
  "无法写入<％s>"

  "Unfavorite"
  "不喜欢的"

}

